/**
 * Combat-relevant spell catalog for the simulator.
 * ~50 spells with pre-tagged heuristic metadata.
 */

import type { SimSpell } from "./types";

export const COMBAT_SPELLS: Record<string, SimSpell> = {
  // ─── Wizard Level 1 ─────────────────────────────────────────────────
  magic_missile: {
    name: "Magic Missile",
    level: 1,
    type: "wizard",
    castingTime: 1,
    savingThrow: "none",
    category: "single_damage",
    targetMode: "single",
    estimatedDamage: { count: 1, sides: 4, bonus: 1 },
    duration: 0,
    counters: [],
    conditions: [],
    scalesWithLevel: true,
    maxDiceCount: 5,
  },
  sleep: {
    name: "Sleep",
    level: 1,
    type: "wizard",
    castingTime: 1,
    savingThrow: "none",
    category: "cc",
    targetMode: "zone_aoe",
    estimatedDamage: null,
    duration: 5,
    counters: [],
    conditions: ["held"],
  },
  shield: {
    name: "Shield",
    level: 1,
    type: "wizard",
    castingTime: 1,
    savingThrow: "none",
    category: "buff",
    targetMode: "self",
    estimatedDamage: null,
    duration: 5,
    counters: ["magic_missile"],
    conditions: [],
  },
  charm_person: {
    name: "Charm Person",
    level: 1,
    type: "wizard",
    castingTime: 1,
    savingThrow: "spell",
    category: "cc",
    targetMode: "single",
    estimatedDamage: null,
    duration: -1,
    counters: [],
    conditions: ["charmed"],
  },
  burning_hands: {
    name: "Burning Hands",
    level: 1,
    type: "wizard",
    castingTime: 1,
    savingThrow: "spell",
    category: "aoe_damage",
    targetMode: "zone_aoe",
    estimatedDamage: { count: 1, sides: 3, bonus: 2 },
    duration: 0,
    counters: [],
    conditions: [],
    damageType: "fire",
    scalesWithLevel: true,
    maxDiceCount: 1, // Burning Hands: 1d3+2/level, max 1d3+20 — bonus scales, not dice
  },

  // ─── Wizard Level 2 ─────────────────────────────────────────────────
  detect_invisibility: {
    name: "Detect Invisibility",
    level: 2,
    type: "wizard",
    castingTime: 2,
    savingThrow: "none",
    category: "counter",
    targetMode: "self",
    estimatedDamage: null,
    duration: 5,
    counters: ["invisible"],
    conditions: [],
    requiresConcentration: true,
  },
  mirror_image: {
    name: "Mirror Image",
    level: 2,
    type: "wizard",
    castingTime: 2,
    savingThrow: "none",
    category: "buff",
    targetMode: "self",
    estimatedDamage: null,
    duration: 3,
    counters: [],
    conditions: [],
  },
  invisibility: {
    name: "Invisibility",
    level: 2,
    type: "wizard",
    castingTime: 2,
    savingThrow: "none",
    category: "buff",
    targetMode: "self",
    estimatedDamage: null,
    duration: -1,
    counters: [],
    conditions: ["invisible"],
  },
  melf_acid_arrow: {
    name: "Melf's Acid Arrow",
    level: 2,
    type: "wizard",
    castingTime: 2,
    savingThrow: "none",
    category: "single_damage",
    targetMode: "single",
    estimatedDamage: { count: 2, sides: 4, bonus: 0 },
    duration: 0,
    counters: [],
    conditions: [],
    damageType: "acid",
  },
  blur: {
    name: "Blur",
    level: 2,
    type: "wizard",
    castingTime: 2,
    savingThrow: "none",
    category: "buff",
    targetMode: "self",
    estimatedDamage: null,
    duration: 3,
    counters: [],
    conditions: [],
  },
  web: {
    name: "Web",
    level: 2,
    type: "wizard",
    castingTime: 2,
    savingThrow: "spell",
    category: "cc",
    targetMode: "zone_aoe",
    estimatedDamage: null,
    duration: 4,
    counters: [],
    conditions: ["held"],
  },

  // ─── Wizard Level 3 ─────────────────────────────────────────────────
  fireball: {
    name: "Fireball",
    level: 3,
    type: "wizard",
    castingTime: 3,
    savingThrow: "spell",
    category: "aoe_damage",
    targetMode: "zone_aoe",
    estimatedDamage: { count: 6, sides: 6, bonus: 0 },
    duration: 0,
    counters: [],
    conditions: [],
    damageType: "fire",
    scalesWithLevel: true,
    maxDiceCount: 10,
  },
  lightning_bolt: {
    name: "Lightning Bolt",
    level: 3,
    type: "wizard",
    castingTime: 3,
    savingThrow: "spell",
    category: "aoe_damage",
    targetMode: "zone_aoe",
    estimatedDamage: { count: 6, sides: 6, bonus: 0 },
    duration: 0,
    counters: [],
    conditions: [],
    damageType: "lightning",
    scalesWithLevel: true,
    maxDiceCount: 10,
  },
  dispel_magic: {
    name: "Dispel Magic",
    level: 3,
    type: "wizard",
    castingTime: 3,
    savingThrow: "none",
    category: "counter",
    targetMode: "single",
    estimatedDamage: null,
    duration: 0,
    counters: ["invisible", "hasted", "charmed", "held", "slowed"],
    conditions: [],
  },
  haste: {
    name: "Haste",
    level: 3,
    type: "wizard",
    castingTime: 3,
    savingThrow: "none",
    category: "buff",
    targetMode: "zone_aoe",
    estimatedDamage: null,
    duration: 3,
    counters: [],
    conditions: ["hasted"],
  },
  hold_person_wiz: {
    name: "Hold Person",
    level: 3,
    type: "wizard",
    castingTime: 3,
    savingThrow: "spell",
    category: "cc",
    targetMode: "single",
    estimatedDamage: null,
    duration: 2,
    counters: [],
    conditions: ["held"],
  },
  slow: {
    name: "Slow",
    level: 3,
    type: "wizard",
    castingTime: 3,
    savingThrow: "spell",
    category: "cc",
    targetMode: "zone_aoe",
    estimatedDamage: null,
    duration: 3,
    counters: [],
    conditions: ["slowed"],
  },
  protection_from_evil_10: {
    name: "Protection from Evil 10'",
    level: 3,
    type: "wizard",
    castingTime: 3,
    savingThrow: "none",
    category: "buff",
    targetMode: "zone_aoe",
    estimatedDamage: null,
    duration: 4,
    counters: [],
    conditions: [],
  },

  // ─── Wizard Level 4 ─────────────────────────────────────────────────
  ice_storm: {
    name: "Ice Storm",
    level: 4,
    type: "wizard",
    castingTime: 4,
    savingThrow: "none",
    category: "aoe_damage",
    targetMode: "zone_aoe",
    estimatedDamage: { count: 3, sides: 10, bonus: 0 },
    duration: 0,
    counters: [],
    conditions: [],
    damageType: "cold",
  },
  stoneskin: {
    name: "Stoneskin",
    level: 4,
    type: "wizard",
    castingTime: 1,
    savingThrow: "none",
    category: "buff",
    targetMode: "self",
    estimatedDamage: null,
    duration: -1,
    counters: [],
    conditions: [],
  },
  improved_invisibility: {
    name: "Improved Invisibility",
    level: 4,
    type: "wizard",
    castingTime: 4,
    savingThrow: "none",
    category: "buff",
    targetMode: "self",
    estimatedDamage: null,
    duration: 4,
    counters: [],
    conditions: ["invisible"],
  },
  wall_of_fire: {
    name: "Wall of Fire",
    level: 4,
    type: "wizard",
    castingTime: 4,
    savingThrow: "spell",
    category: "aoe_damage",
    targetMode: "zone_aoe",
    estimatedDamage: { count: 2, sides: 6, bonus: 0 },
    duration: 0,
    counters: [],
    conditions: [],
    damageType: "fire",
    scalesWithLevel: true,
    maxDiceCount: 2, // 2d6 + caster level bonus applied via scaling
  },

  // ─── Wizard Level 5 ─────────────────────────────────────────────────
  cone_of_cold: {
    name: "Cone of Cold",
    level: 5,
    type: "wizard",
    castingTime: 5,
    savingThrow: "spell",
    category: "aoe_damage",
    targetMode: "zone_aoe",
    estimatedDamage: { count: 5, sides: 4, bonus: 5 },
    duration: 0,
    counters: [],
    conditions: [],
    damageType: "cold",
    scalesWithLevel: true,
    maxDiceCount: 10,
  },
  cloudkill: {
    name: "Cloudkill",
    level: 5,
    type: "wizard",
    castingTime: 5,
    savingThrow: "paralyzation",
    category: "aoe_damage",
    targetMode: "zone_aoe",
    estimatedDamage: { count: 1, sides: 10, bonus: 0 },
    duration: 0,
    counters: [],
    conditions: [],
    damageType: "poison",
  },
  hold_monster: {
    name: "Hold Monster",
    level: 5,
    type: "wizard",
    castingTime: 5,
    savingThrow: "spell",
    category: "cc",
    targetMode: "single",
    estimatedDamage: null,
    duration: 2,
    counters: [],
    conditions: ["held"],
  },
  feeblemind: {
    name: "Feeblemind",
    level: 5,
    type: "wizard",
    castingTime: 5,
    savingThrow: "spell",
    category: "cc",
    targetMode: "single",
    estimatedDamage: null,
    duration: -1,
    counters: [],
    conditions: ["silenced", "charmed"], // Effectively removes caster from combat
  },

  // ─── Priest Level 1 ────────────────────────────────────────────────
  cure_light_wounds: {
    name: "Cure Light Wounds",
    level: 1,
    type: "priest",
    castingTime: 5,
    savingThrow: "none",
    category: "heal",
    targetMode: "ally",
    estimatedDamage: { count: 1, sides: 8, bonus: 0 },
    duration: 0,
    counters: [],
    conditions: [],
  },
  bless: {
    name: "Bless",
    level: 1,
    type: "priest",
    castingTime: 1,
    savingThrow: "none",
    category: "buff",
    targetMode: "zone_aoe",
    estimatedDamage: null,
    duration: 6,
    counters: [],
    conditions: [],
  },
  command: {
    name: "Command",
    level: 1,
    type: "priest",
    castingTime: 1,
    savingThrow: "spell",
    category: "cc",
    targetMode: "single",
    estimatedDamage: null,
    duration: 1,
    counters: [],
    conditions: ["held"],
  },
  sanctuary: {
    name: "Sanctuary",
    level: 1,
    type: "priest",
    castingTime: 4,
    savingThrow: "none",
    category: "buff",
    targetMode: "self",
    estimatedDamage: null,
    duration: 4,
    counters: [],
    conditions: [],
  },

  // ─── Priest Level 2 ────────────────────────────────────────────────
  hold_person: {
    name: "Hold Person",
    level: 2,
    type: "priest",
    castingTime: 5,
    savingThrow: "spell",
    category: "cc",
    targetMode: "single",
    estimatedDamage: null,
    duration: 4,
    counters: [],
    conditions: ["held"],
  },
  spiritual_hammer: {
    name: "Spiritual Hammer",
    level: 2,
    type: "priest",
    castingTime: 5,
    savingThrow: "none",
    category: "single_damage",
    targetMode: "single",
    estimatedDamage: { count: 1, sides: 6, bonus: 3 },
    duration: 3,
    counters: [],
    conditions: [],
    requiresConcentration: true,
  },
  aid: {
    name: "Aid",
    level: 2,
    type: "priest",
    castingTime: 5,
    savingThrow: "none",
    category: "buff",
    targetMode: "ally",
    estimatedDamage: null,
    duration: 6,
    counters: [],
    conditions: [],
  },
  silence_15: {
    name: "Silence 15'",
    level: 2,
    type: "priest",
    castingTime: 5,
    savingThrow: "spell",
    category: "cc",
    targetMode: "zone_aoe",
    estimatedDamage: null,
    duration: 3,
    counters: [],
    conditions: ["silenced"],
  },

  // ─── Priest Level 3 ────────────────────────────────────────────────
  cure_serious_wounds: {
    name: "Cure Serious Wounds",
    level: 3,
    type: "priest",
    castingTime: 7,
    savingThrow: "none",
    category: "heal",
    targetMode: "ally",
    estimatedDamage: { count: 2, sides: 8, bonus: 1 },
    duration: 0,
    counters: [],
    conditions: [],
  },
  dispel_magic_priest: {
    name: "Dispel Magic",
    level: 3,
    type: "priest",
    castingTime: 6,
    savingThrow: "none",
    category: "counter",
    targetMode: "single",
    estimatedDamage: null,
    duration: 0,
    counters: ["invisible", "hasted", "charmed", "held", "slowed"],
    conditions: [],
  },
  prayer: {
    name: "Prayer",
    level: 3,
    type: "priest",
    castingTime: 6,
    savingThrow: "none",
    category: "buff",
    targetMode: "zone_aoe",
    estimatedDamage: null,
    duration: 5,
    counters: [],
    conditions: [],
  },

  // ─── Priest Level 4 ────────────────────────────────────────────────
  cure_critical_wounds: {
    name: "Cure Critical Wounds",
    level: 4,
    type: "priest",
    castingTime: 8,
    savingThrow: "none",
    category: "heal",
    targetMode: "ally",
    estimatedDamage: { count: 3, sides: 8, bonus: 3 },
    duration: 0,
    counters: [],
    conditions: [],
  },
  free_action: {
    name: "Free Action",
    level: 4,
    type: "priest",
    castingTime: 7,
    savingThrow: "none",
    category: "counter",
    targetMode: "ally",
    estimatedDamage: null,
    duration: 0,
    counters: ["held", "slowed"],
    conditions: [],
  },

  // ─── Priest Level 5 ────────────────────────────────────────────────
  flame_strike: {
    name: "Flame Strike",
    level: 5,
    type: "priest",
    castingTime: 8,
    savingThrow: "spell",
    category: "aoe_damage",
    targetMode: "zone_aoe",
    estimatedDamage: { count: 6, sides: 8, bonus: 0 },
    duration: 0,
    counters: [],
    conditions: [],
    damageType: "fire",
  },

  // ─── Priest Level 6 ────────────────────────────────────────────────
  heal_full: {
    name: "Heal",
    level: 6,
    type: "priest",
    castingTime: 1,
    savingThrow: "none",
    category: "heal",
    targetMode: "ally",
    estimatedDamage: { count: 1, sides: 1, bonus: 0 }, // Placeholder, resolved specially
    duration: 0,
    counters: [],
    conditions: [],
  },
};

// Pre-built lookup map for O(1) exact matching
const CATALOG_NAME_TO_KEY = new Map<string, string>(
  Object.entries(COMBAT_SPELLS).map(([key, spell]) => [spell.name.toLowerCase(), key])
);

/**
 * Match a spell name from the DB against the combat spell catalog.
 * Returns the catalog key if found (exact match first, then fuzzy substring).
 */
export function matchSpellToCatalog(spellName: string): string | null {
  const normalized = spellName.toLowerCase().replace(/[''`]/g, "'");

  // Exact match (O(1))
  const exact = CATALOG_NAME_TO_KEY.get(normalized);
  if (exact) return exact;

  // Fuzzy: catalog name is a substring of the DB spell name (single pass)
  for (const [catalogName, key] of CATALOG_NAME_TO_KEY) {
    if (normalized.includes(catalogName)) return key;
  }

  return null;
}
