/**
 * Presets for common temporary effects, taken from the AD&D 2e sources
 * (see docs/agents/research/2026-10-05-temporary-effects.md). A preset only
 * pre-fills the effect form — players adjust rolled amounts (e.g. 1d8 temp HP)
 * and anything else before saving. Values are in player terms (+ = advantage).
 */
import type { EffectFlag, EffectModifier } from "@/lib/supabase/types";

export type EffectPresetGroup = "spell" | "monster" | "condition" | "injury" | "environment";

export const EFFECT_PRESET_GROUPS: EffectPresetGroup[] = [
  "spell",
  "monster",
  "condition",
  "injury",
  "environment",
];

export interface PresetModifier extends Omit<EffectModifier, "condition"> {
  condition?: { de: string; en: string };
}

export interface EffectPreset {
  key: string;
  group: EffectPresetGroup;
  icon: string;
  name: string;
  name_en: string;
  notes: string;
  notes_en: string;
  duration: string;
  duration_en: string;
  /** Book or monster the numbers come from. */
  source: string;
  modifiers: PresetModifier[];
  flags: EffectFlag[];
}

const FEAR = { de: "Furcht", en: "fear" };
const EVIL = { de: "Böse", en: "evil" };

export const EFFECT_PRESETS: EffectPreset[] = [
  // ── Zauber ────────────────────────────────────────────────────────────
  {
    key: "bless",
    group: "spell",
    icon: "✨",
    name: "Segen",
    name_en: "Bless",
    notes: "+1 auf Angriffe und Moral, +1 auf Rettungswürfe gegen Furcht. Nicht kumulativ.",
    notes_en: "+1 to attack and morale, +1 to saves vs. fear. Not cumulative.",
    duration: "6 Runden",
    duration_en: "6 rounds",
    source: "PHB, Priest 1",
    modifiers: [
      { target: "attack", op: "delta", value: 1 },
      { target: "savesAll", op: "delta", value: 1, condition: FEAR },
    ],
    flags: [],
  },
  {
    key: "curse",
    group: "spell",
    icon: "🕯",
    name: "Fluch",
    name_en: "Curse",
    notes: "Umkehrung von Segen: −1 auf Angriffe und Moral.",
    notes_en: "Reverse of Bless: −1 to attack and morale.",
    duration: "6 Runden",
    duration_en: "6 rounds",
    source: "PHB, Priest 1",
    modifiers: [{ target: "attack", op: "delta", value: -1 }],
    flags: [],
  },
  {
    key: "prayerAlly",
    group: "spell",
    icon: "🙏",
    name: "Gebet (Verbündete)",
    name_en: "Prayer (allies)",
    notes: "+1 auf Angriff, Schaden und Rettungswürfe. Zusammen mit Gesang +2.",
    notes_en: "+1 to attack, damage and saves. Together with Chant +2.",
    duration: "1 Runde/Stufe",
    duration_en: "1 round/level",
    source: "PHB, Priest 3",
    modifiers: [
      { target: "attack", op: "delta", value: 1 },
      { target: "damage", op: "delta", value: 1 },
      { target: "savesAll", op: "delta", value: 1 },
    ],
    flags: [],
  },
  {
    key: "prayerEnemy",
    group: "spell",
    icon: "🙏",
    name: "Gebet (Gegner)",
    name_en: "Prayer (enemies)",
    notes: "Gegnerisches Gebet: −1 auf Angriff, Schaden und Rettungswürfe.",
    notes_en: "Enemy prayer: −1 to attack, damage and saves.",
    duration: "1 Runde/Stufe",
    duration_en: "1 round/level",
    source: "PHB, Priest 3",
    modifiers: [
      { target: "attack", op: "delta", value: -1 },
      { target: "damage", op: "delta", value: -1 },
      { target: "savesAll", op: "delta", value: -1 },
    ],
    flags: [],
  },
  {
    key: "chantAlly",
    group: "spell",
    icon: "🎶",
    name: "Gesang (Verbündete)",
    name_en: "Chant (allies)",
    notes: "+1 auf Angriff, Schaden und Rettungswürfe, solange der Priester singt.",
    notes_en: "+1 to attack, damage and saves while the priest chants.",
    duration: "solange gesungen wird",
    duration_en: "while chanting",
    source: "PHB, Priest 2",
    modifiers: [
      { target: "attack", op: "delta", value: 1 },
      { target: "damage", op: "delta", value: 1 },
      { target: "savesAll", op: "delta", value: 1 },
    ],
    flags: [],
  },
  {
    key: "aid",
    group: "spell",
    icon: "🛡",
    name: "Hilfe",
    name_en: "Aid",
    notes: "Wie Segen, dazu 1W8 temporäre TP (würfeln und eintragen). Werden zuerst verbraucht.",
    notes_en: "Like Bless, plus 1d8 temporary HP (roll and enter). Lost first.",
    duration: "1 Runde + 1/Stufe",
    duration_en: "1 round + 1/level",
    source: "PHB, Priest 2",
    modifiers: [
      { target: "attack", op: "delta", value: 1 },
      { target: "savesAll", op: "delta", value: 1, condition: FEAR },
      { target: "tempHp", op: "delta", value: 0 },
    ],
    flags: [],
  },
  {
    key: "haste",
    group: "spell",
    icon: "⚡",
    name: "Hast",
    name_en: "Haste",
    notes: "Doppelte Bewegung und Angriffe, −2 Initiative. Altert um 1 Jahr.",
    notes_en: "Double movement and attacks, −2 initiative. Ages the target 1 year.",
    duration: "3 Runden + 1/Stufe",
    duration_en: "3 rounds + 1/level",
    source: "PHB, Wizard 3",
    modifiers: [
      { target: "movement", op: "factor", value: 2 },
      { target: "attacksPerRound", op: "factor", value: 2 },
    ],
    flags: [],
  },
  {
    key: "slow",
    group: "spell",
    icon: "🐌",
    name: "Verlangsamen",
    name_en: "Slow",
    notes: "Halbe Bewegung und Angriffe, RK 4 schlechter, −4 auf Angriffe, kein GE-Bonus.",
    notes_en: "Half movement and attacks, AC 4 worse, −4 to attack, no Dex bonus.",
    duration: "3 Runden + 1/Stufe",
    duration_en: "3 rounds + 1/level",
    source: "PHB, Wizard 3",
    modifiers: [
      { target: "movement", op: "factor", value: 0.5 },
      { target: "attacksPerRound", op: "factor", value: 0.5 },
      { target: "attack", op: "delta", value: -4 },
      { target: "ac", op: "delta", value: -4 },
    ],
    flags: ["noDexAc"],
  },
  {
    key: "rayOfEnfeeblement",
    group: "spell",
    icon: "🪫",
    name: "Schwächestrahl",
    name_en: "Ray of Enfeeblement",
    notes: "Stärke wird 5, alle STR-Boni entfallen.",
    notes_en: "Strength becomes 5, all Strength bonuses are lost.",
    duration: "1 Runde/Stufe",
    duration_en: "1 round/level",
    source: "PHB, Wizard 2",
    modifiers: [{ target: "str", op: "set", value: 5 }],
    flags: [],
  },
  {
    key: "strength",
    group: "spell",
    icon: "💪",
    name: "Stärke",
    name_en: "Strength",
    notes: "+1W8 (Krieger), +1W6 (Priester/Schurke), +1W4 (Magier) — Wurf eintragen. Max. 18/xx.",
    notes_en: "+1d8 (warrior), +1d6 (priest/rogue), +1d4 (wizard) — enter the roll. Max 18/xx.",
    duration: "1 Stunde/Stufe",
    duration_en: "1 hour/level",
    source: "PHB, Wizard 2",
    modifiers: [{ target: "str", op: "delta", value: 4 }],
    flags: [],
  },
  {
    key: "catsGrace",
    group: "spell",
    icon: "🐈",
    name: "Katzenanmut",
    name_en: "Cat's Grace",
    notes: "+1W8 (Schurke) bis +1W4 (Priester) GE — Wurf eintragen. Max. 19.",
    notes_en: "+1d8 (rogue) to +1d4 (priest) Dex — enter the roll. Max 19.",
    duration: "1 Stunde/Stufe",
    duration_en: "1 hour/level",
    source: "Wizard's Spell Compendium 1",
    modifiers: [{ target: "dex", op: "delta", value: 4 }],
    flags: [],
  },
  {
    key: "contagion",
    group: "spell",
    icon: "☠",
    name: "Seuche",
    name_en: "Contagion",
    notes: "STR, GE und CHA −2, Angriffe −2.",
    notes_en: "Str, Dex and Cha −2, attacks −2.",
    duration: "bis Krankheit geheilt",
    duration_en: "until disease is cured",
    source: "PHB, Wizard 4",
    modifiers: [
      { target: "str", op: "delta", value: -2 },
      { target: "dex", op: "delta", value: -2 },
      { target: "cha", op: "delta", value: -2 },
      { target: "attack", op: "delta", value: -2 },
    ],
    flags: [],
  },
  {
    key: "scourge",
    group: "spell",
    icon: "☠",
    name: "Geißel",
    name_en: "Scourge",
    notes: "STR, GE und CHA −3, Angriffe −3.",
    notes_en: "Str, Dex and Cha −3, attacks −3.",
    duration: "bis Krankheit geheilt",
    duration_en: "until disease is cured",
    source: "Priest's Spell Compendium 2",
    modifiers: [
      { target: "str", op: "delta", value: -3 },
      { target: "dex", op: "delta", value: -3 },
      { target: "cha", op: "delta", value: -3 },
      { target: "attack", op: "delta", value: -3 },
    ],
    flags: [],
  },
  {
    key: "blindness",
    group: "spell",
    icon: "🙈",
    name: "Blindheit",
    name_en: "Blindness",
    notes: "−4 auf Angriffe, Angreifer +4 (RK 4 schlechter).",
    notes_en: "−4 to attack, attackers +4 (AC 4 worse).",
    duration: "bis gebannt",
    duration_en: "until dispelled",
    source: "PHB, Wizard 2",
    modifiers: [
      { target: "attack", op: "delta", value: -4 },
      { target: "ac", op: "delta", value: -4 },
    ],
    flags: ["blinded"],
  },
  {
    key: "deafness",
    group: "spell",
    icon: "🙉",
    name: "Taubheit",
    name_en: "Deafness",
    notes: "20 % Patzerchance bei Zaubern mit verbaler Komponente, −1 auf Überraschung.",
    notes_en: "20% miscast chance for spells with a verbal component, −1 to surprise.",
    duration: "bis gebannt",
    duration_en: "until dispelled",
    source: "PHB, Wizard 2",
    modifiers: [{ target: "spellFailure", op: "delta", value: 20 }],
    flags: ["deafened"],
  },
  {
    key: "faerieFire",
    group: "spell",
    icon: "🔥",
    name: "Feenfeuer",
    name_en: "Faerie Fire",
    notes: "Angreifer +2 in Dunkelheit, +1 im Zwielicht.",
    notes_en: "Attackers +2 in darkness, +1 in twilight.",
    duration: "4 Runden/Stufe",
    duration_en: "4 rounds/level",
    source: "PHB, Priest 1",
    modifiers: [
      { target: "ac", op: "delta", value: -2, condition: { de: "Dunkelheit", en: "darkness" } },
    ],
    flags: [],
  },
  {
    key: "protectionFromEvil",
    group: "spell",
    icon: "🛡",
    name: "Schutz vor Bösem",
    name_en: "Protection from Evil",
    notes: "Böse Angreifer −2, Rettungswürfe gegen ihre Angriffe +2.",
    notes_en: "Evil attackers −2, saves vs. their attacks +2.",
    duration: "2 Runden/Stufe",
    duration_en: "2 rounds/level",
    source: "PHB, Wizard 1 / Priest 1",
    modifiers: [
      { target: "ac", op: "delta", value: 2, condition: EVIL },
      { target: "savesAll", op: "delta", value: 2, condition: EVIL },
    ],
    flags: [],
  },
  {
    key: "bestowCurse",
    group: "spell",
    icon: "🕯",
    name: "Unheil (Fluch)",
    name_en: "Bestow Curse",
    notes:
      "Ergebnis 51–75: −4 auf Angriffe und Rettungswürfe. Andere Ergebnisse: Attribut auf 3 oder Gegenstände fallen lassen.",
    notes_en:
      "Result 51–75: −4 to attack and saves. Other results: an ability becomes 3 or items are dropped.",
    duration: "1 Turn/Stufe",
    duration_en: "1 turn/level",
    source: "PHB, Wizard 4 (Remove Curse reversed)",
    modifiers: [
      { target: "attack", op: "delta", value: -4 },
      { target: "savesAll", op: "delta", value: -4 },
    ],
    flags: [],
  },
  {
    key: "emotionCourage",
    group: "spell",
    icon: "🦁",
    name: "Emotion: Mut",
    name_en: "Emotion: Courage",
    notes: "+1 Angriff, +3 Schaden, +5 temporäre TP, kein Schild, keine Moralproben.",
    notes_en: "+1 attack, +3 damage, +5 temporary HP, no shield, no morale checks.",
    duration: "solange konzentriert",
    duration_en: "while concentrating",
    source: "PHB, Wizard 4",
    modifiers: [
      { target: "attack", op: "delta", value: 1 },
      { target: "damage", op: "delta", value: 3 },
      { target: "tempHp", op: "delta", value: 5 },
    ],
    flags: ["noShield"],
  },
  {
    key: "emotionHope",
    group: "spell",
    icon: "🌅",
    name: "Emotion: Hoffnung",
    name_en: "Emotion: Hope",
    notes: "+2 auf Moral, Rettungswürfe, Angriff und Schaden.",
    notes_en: "+2 to morale, saves, attack and damage.",
    duration: "solange konzentriert",
    duration_en: "while concentrating",
    source: "PHB, Wizard 4",
    modifiers: [
      { target: "attack", op: "delta", value: 2 },
      { target: "damage", op: "delta", value: 2 },
      { target: "savesAll", op: "delta", value: 2 },
    ],
    flags: [],
  },
  {
    key: "chillTouch",
    group: "spell",
    icon: "❄",
    name: "Kühle Berührung",
    name_en: "Chill Touch",
    notes: "−1 STR pro Berührung (kumulativ), kehrt mit 1 Punkt pro Stunde zurück.",
    notes_en: "−1 Str per touch (cumulative), returns at 1 point per hour.",
    duration: "1 STR/Stunde zurück",
    duration_en: "1 Str/hour back",
    source: "PHB, Wizard 1",
    modifiers: [{ target: "str", op: "delta", value: -1 }],
    flags: [],
  },
  // ── Monster ───────────────────────────────────────────────────────────
  {
    key: "shadowTouch",
    group: "monster",
    icon: "👤",
    name: "Schatten-Berührung",
    name_en: "Shadow touch",
    notes: "−1 STR pro Treffer. Bei STR 0 wird das Opfer zum Schatten.",
    notes_en: "−1 Str per hit. At Str 0 the victim becomes a shadow.",
    duration: "kehrt nach 2W4 Turns zurück",
    duration_en: "returns after 2d4 turns",
    source: "Monstrous Manual, Shadow",
    modifiers: [{ target: "str", op: "delta", value: -1 }],
    flags: [],
  },
  {
    key: "mummyRot",
    group: "monster",
    icon: "🧟",
    name: "Mumienfäule",
    name_en: "Mummy rot",
    notes:
      "−2 CHA pro Monat (dauerhaft), Heilung nur zu 10 %, Heilzauber wirken nicht. Nur Krankheit heilen hilft.",
    notes_en:
      "−2 Cha per month (permanent), heals at 10%, cure wounds has no effect. Only cure disease helps.",
    duration: "bis Krankheit geheilt",
    duration_en: "until disease is cured",
    source: "Monstrous Manual, Mummy",
    modifiers: [{ target: "cha", op: "delta", value: -2 }],
    flags: [],
  },
  {
    key: "dragonFear",
    group: "monster",
    icon: "🐉",
    name: "Drachenfurcht",
    name_en: "Dragon fear",
    notes: "Nach misslungenem Rettungswurf: −2 auf Angriff und Schaden.",
    notes_en: "After a failed save: −2 to attack and damage.",
    duration: "solange der Drache kämpft",
    duration_en: "while the dragon fights",
    source: "Monstrous Manual, Dragon",
    modifiers: [
      { target: "attack", op: "delta", value: -2 },
      { target: "damage", op: "delta", value: -2 },
    ],
    flags: ["frightened"],
  },
  {
    key: "ghoulParalysis",
    group: "monster",
    icon: "🧊",
    name: "Ghul-Lähmung",
    name_en: "Ghoul paralysis",
    notes: "Gelähmt: Angriffe gegen den Charakter treffen automatisch.",
    notes_en: "Paralyzed: attacks against the character hit automatically.",
    duration: "3–8 Runden",
    duration_en: "3–8 rounds",
    source: "Monstrous Manual, Ghoul",
    modifiers: [],
    flags: ["held", "helpless", "noAttacks", "cannotCast"],
  },
  {
    key: "stinkingCloud",
    group: "monster",
    icon: "🤢",
    name: "Übelkeit (Stinkwolke)",
    name_en: "Nausea (Stinking Cloud)",
    notes: "Taumelnd vor Übelkeit: keine Angriffe.",
    notes_en: "Reeling with nausea: no attacks.",
    duration: "1W4+1 Runden nach Verlassen",
    duration_en: "1d4+1 rounds after leaving",
    source: "PHB, Wizard 2",
    modifiers: [],
    flags: ["nauseated", "noAttacks"],
  },
  // ── Zustände ──────────────────────────────────────────────────────────
  {
    key: "unconscious",
    group: "condition",
    icon: "💤",
    name: "Bewusstlos",
    name_en: "Unconscious",
    notes: "Hilflos: Angriffe treffen automatisch.",
    notes_en: "Helpless: attacks hit automatically.",
    duration: "",
    duration_en: "",
    source: "PHB / DMG",
    modifiers: [],
    flags: ["unconscious", "helpless", "noAttacks", "cannotCast"],
  },
  {
    key: "stunned",
    group: "condition",
    icon: "💫",
    name: "Betäubt",
    name_en: "Stunned",
    notes: "Angreifer +4.",
    notes_en: "Attackers +4.",
    duration: "",
    duration_en: "",
    source: "PHB, Table 51",
    modifiers: [{ target: "ac", op: "delta", value: -4 }],
    flags: ["stunned"],
  },
  {
    key: "prone",
    group: "condition",
    icon: "🛌",
    name: "Liegend",
    name_en: "Prone",
    notes:
      "Nahkampf gegen ihn +4, eigener Nahkampf −4, gegen Fernkampf RK 2 besser. Aufstehen kostet einen Angriff.",
    notes_en:
      "Melee against him +4, own melee −4, AC 2 better vs. missiles. Standing up costs an attack.",
    duration: "",
    duration_en: "",
    source: "Combat & Tactics",
    modifiers: [
      { target: "attack", op: "delta", value: -4, condition: { de: "Nahkampf", en: "melee" } },
      { target: "ac", op: "delta", value: -4, condition: { de: "Nahkampf", en: "melee" } },
    ],
    flags: ["prone"],
  },
  {
    key: "held",
    group: "condition",
    icon: "⛓",
    name: "Gehalten / gelähmt",
    name_en: "Held / paralyzed",
    notes: "Kann sich weder bewegen noch sprechen. Angriffe treffen automatisch.",
    notes_en: "Cannot move or speak. Attacks hit automatically.",
    duration: "",
    duration_en: "",
    source: "PHB, Hold Person",
    modifiers: [{ target: "movement", op: "factor", value: 0 }],
    flags: ["held", "helpless", "noAttacks", "cannotCast"],
  },
  {
    key: "frightened",
    group: "condition",
    icon: "😱",
    name: "Verängstigt",
    name_en: "Frightened",
    notes: "Flieht mit voller Geschwindigkeit, kann Gehaltenes fallen lassen.",
    notes_en: "Flees at full speed, may drop held items.",
    duration: "",
    duration_en: "",
    source: "PHB, Fear",
    modifiers: [],
    flags: ["frightened"],
  },
  // ── Verletzungen ──────────────────────────────────────────────────────
  {
    key: "legInjured",
    group: "injury",
    icon: "🦵",
    name: "Bein verletzt",
    name_en: "Leg injured",
    notes: "Halbe Bewegung, kein Sturmangriff und kein Rennen.",
    notes_en: "Half movement, no charging or running.",
    duration: "bis geheilt",
    duration_en: "until healed",
    source: "Combat & Tactics, critical hits",
    modifiers: [{ target: "movement", op: "factor", value: 0.5 }],
    flags: [],
  },
  {
    key: "armInjured",
    group: "injury",
    icon: "💪",
    name: "Arm verletzt",
    name_en: "Arm injured",
    notes: "−2 auf Angriffe mit diesem Arm (bei schwerer Verletzung −4).",
    notes_en: "−2 to attacks with this arm (−4 if severe).",
    duration: "bis geheilt",
    duration_en: "until healed",
    source: "Combat & Tactics, critical hits",
    modifiers: [{ target: "attack", op: "delta", value: -2 }],
    flags: [],
  },
  {
    key: "bleeding",
    group: "injury",
    icon: "🩸",
    name: "Blutung",
    name_en: "Bleeding",
    notes: "Leicht: 1W2 TP pro Turn, schwer: 1W2 TP pro Runde — bis verbunden oder geheilt.",
    notes_en: "Minor: 1d2 HP per turn, major: 1d2 HP per round — until bandaged or healed.",
    duration: "bis verbunden",
    duration_en: "until bandaged",
    source: "Combat & Tactics, critical hits",
    modifiers: [],
    flags: ["ongoingDamage"],
  },
  // ── Umwelt ────────────────────────────────────────────────────────────
  {
    key: "debilitatingPoison",
    group: "environment",
    icon: "🧪",
    name: "Schwächendes Gift",
    name_en: "Debilitating poison",
    notes: "Alle Attribute halbiert, halbe Bewegung, keine Heilung bis neutralisiert.",
    notes_en: "All abilities halved, half movement, no healing until neutralized.",
    duration: "1W3 Tage",
    duration_en: "1d3 days",
    source: "PHB / DMG, Poison",
    modifiers: [
      { target: "allAbilities", op: "factor", value: 0.5 },
      { target: "movement", op: "factor", value: 0.5 },
    ],
    flags: [],
  },
  {
    key: "exhaustion",
    group: "environment",
    icon: "🥵",
    name: "Erschöpfung",
    name_en: "Exhaustion",
    notes: "−2 auf Angriffe, halbe Bewegung. Endet nach mindestens 1 Turn Rast.",
    notes_en: "−2 to attack, half movement. Ends after at least 1 turn of rest.",
    duration: "bis ausgeruht",
    duration_en: "until rested",
    source: "PHB, Movement / Combat & Tactics",
    modifiers: [
      { target: "attack", op: "delta", value: -2 },
      { target: "movement", op: "factor", value: 0.5 },
    ],
    flags: [],
  },
  {
    key: "forcedMarch",
    group: "environment",
    icon: "🥾",
    name: "Gewaltmarsch",
    name_en: "Forced march",
    notes:
      "−1 auf Angriffe pro Tag Gewaltmarsch (kumulativ). Ein halber Tag Rast hebt einen Tag auf.",
    notes_en:
      "−1 to attack per day of forced march (cumulative). Half a day of rest removes one day.",
    duration: "bis ausgeruht",
    duration_en: "until rested",
    source: "PHB, Overland movement",
    modifiers: [{ target: "attack", op: "delta", value: -1 }],
    flags: [],
  },
];

export function getEffectPreset(key: string | null | undefined): EffectPreset | undefined {
  return EFFECT_PRESETS.find((p) => p.key === key);
}

export interface EffectDraft {
  name: string;
  notes: string;
  duration_text: string;
  preset_key: string | null;
  modifiers: EffectModifier[];
  flags: EffectFlag[];
}

/** Form values for a preset in the given language. */
export function presetToDraft(preset: EffectPreset, locale: string): EffectDraft {
  const en = locale === "en";
  return {
    name: en ? preset.name_en : preset.name,
    notes: en ? preset.notes_en : preset.notes,
    duration_text: en ? preset.duration_en : preset.duration,
    preset_key: preset.key,
    modifiers: preset.modifiers.map(({ condition, ...m }) =>
      condition ? { ...m, condition: en ? condition.en : condition.de } : { ...m }
    ),
    flags: [...preset.flags],
  };
}
