-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 1 (Batch 2: 15 Spells — Bird Charm I to Compass)
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  description = 'Beschwört bis zu 3 kleine Vögel pro Stufe des Zauberkundigen. Darunter fallen Vögel bis Papageiengröße — Papageien und Kolibris sind bevorzugte Ziele, da sie keinen Rettungswurf gegen den Zauber erhalten. Die beschworenen Vögel verstehen rudimentäre Befehle des Zauberkundigen, und Papageien können sogar Nachrichten von bis zu drei Wörtern wiederholen. Materialkomponente: V, M (eine kleine Korallenpfeife, die der Zauberkundige selbst schnitzen muss — der Prozess dauert mehrere Tage und erfordert ein ungewöhnlich großes Stück Koralle).',
  description_en = 'Summons up to 3 small birds per caster level. Includes birds up to parrot size — parrots and hummingbirds are the most favored targets, as they make no saving throw against the spell. The summoned birds understand the caster''s rudimentary commands, and parrots can even repeat up to three-word messages. Material component: V, M (a small coral whistle the caster must carve himself — the process takes several days and requires an unusually large piece of coral).'
WHERE LOWER(name_en) = LOWER('Bird Charm I — Pluma') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Macht eine Waffe für Heimlichkeit und dunkle Taten geeignet. Die Waffe wird dunkel, lautlos und reflektionsfrei. Sie erzeugt keine Geräusche beim Auftreffen auf Wesen oder Objekte, und vergossenes Blut haftet an der Klinge, ohne zu spritzen oder zu tropfen. Die Waffe wird magisch zum Zweck des Angriffs, erhält aber keine Angriffs- oder Schadensboni. Der Zauber endet sofort, wenn die Waffe nach dem Wirken mit neuer Magie in Berührung kommt: Berühren eines magischen Gegenstands, Treffen einer magisch geschützten Kreatur, oder Einwirkung eines Zaubers auf die Klinge. Wird NICHT beendet durch: Betreten eines Gebiets mit bestehendem Zauber (z.B. Dauerlicht) oder wenn der Träger selbst einen Zauber wirkt. Komponenten: V, S, M.',
  description_en = 'Makes a weapon suitable for stealth and dark deeds. The weapon becomes dark, silent, and nonreflective. It makes no noise when striking beings or objects, and blood shed by it adheres to the blade without spraying or dripping. The weapon becomes magical for attack purposes but gains no attack or damage bonuses. The spell ends immediately if the weapon comes into physical contact with new magic after casting: touching a magical object, striking a magically protected creature, or being exposed to a spell affecting the blade. NOT ended by: entering an area of a pre-existing spell (continual light, etc.) or when the wielder casts a spell. Components: V, S, M.'
WHERE LOWER(name_en) = LOWER('Blacksteel') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Lässt einen dichten Ring aus dorniger Hecke von 3 m Durchmesser um den Zauberkundigen emporwachsen. Die Hecke reicht dem Zauberkundigen bis zur Brust, ist oben offen und unverrückbar fixiert. Innerhalb des Dornenrings verbessert sich die RK des Zauberkundigen um 2 gegen alle physischen Angriffe — auch wenn die Hecke durchbrochen wurde. Der Zauberkundige kann frei durch die Hecke hindurchgehen, ohne Schaden zu nehmen. Menschengroße oder kleinere Kreaturen können nicht hindurchdrängen; größere Kreaturen bewegen sich mit halber Geschwindigkeit und erleiden 1W8 Schaden pro Runde. Ein Anrennen verursacht doppelten Schaden. 20 Schadenspunkte mit Klingenwaffen schaffen eine Bresche zur Mitte, 40 Punkte ganz hindurch. Die Hecke brennt nicht (außer durch magisches Feuer). Keine bekannte Magie kann die Dauer verlängern. Materialkomponente: V, S, M (drei Dornen oder geschnitzte Holz-/Knochenspitzen in Dornenform).',
  description_en = 'Causes a thick ring of thorny hedge, 3 m in diameter, to rise around the caster. The hedge is chest-high, open at the top, and immovably fixed in place. Within the thorn ring, the caster''s AC improves by 2 against all physical attacks — even if the hedge has been breached. The caster can pass freely through the hedge without taking damage. Man-sized or smaller creatures cannot push through; larger creatures move at half speed and take 1d8 damage per round. Charging deals double damage. 20 damage points with edged weapons create a one-man breach to the center, 40 points all the way through. The hedge does not burn (except from magical fire). No known magic can extend the duration. Material component: V, S, M (three thorns or whittled wooden/bone spikes in thorn shape).'
WHERE LOWER(name_en) = LOWER('Blackthorns') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Lässt ein Bündel federleichter, leuchtender Blumen nach Wahl des Zauberkundigen erscheinen. Die Blumen sind extrem leicht und fangen jede Brise ein, treiben wie Löwenzahnsamen. Sie halten nur eine Stunde, dann lösen sie sich spurlos auf. Zauberkundige wählen häufig eine bestimmte Blumensorte als persönliches Markenzeichen. Nicht-Elfen betrachten diesen Zauber als nutzlose Beschwörung typisch für Elfen. Die Daleland-Elfen nutzen ihn jedoch zum Werben, Dekorieren und Feiern. Komponenten: V, S.',
  description_en = 'Causes a bundle of feather-light, brilliant flowers of the caster''s choice to appear. The flowers are extremely lightweight and catch any breeze, drifting like dandelion seeds. They last only one hour, then dissolve without trace. Wizards commonly choose a particular flower type as a personal signature. Non-elves tend to view this spell as a useless conjuration typical of elves. The Daleland elves, however, use it in courting, decoration, and celebration. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Bloom') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht der berührten Kreatur, an Orten normal zu atmen, wo sie normalerweise ersticken würde — unter Wasser, unter einer Lawine, bei Verschüttung durch einen Sandsturm etc. Materialkomponente: V, S, M (ein Tuch, das während des Wirkens über den Mund des Zauberkundigen gehalten werden muss).',
  description_en = 'Enables the touched creature to breathe normally in places where it would normally suffocate — underwater, under an avalanche, while buried by a sandstorm, etc. Material component: V, S, M (a cloth that must be held over the caster''s mouth during casting).'
WHERE LOWER(name_en) = LOWER('Breathe — Old Empire') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verwandelt normales Wasser in einen magischen Trank, der vor Ablauf der Zauberdauer getrunken werden muss. Der Trank beseitigt Kater und andere Nebenwirkungen von Trunkenheit und hebt jeden aktuellen Rauschzustand auf. Wirkt nur gegen alkoholbedingte Veränderungen der Physiologie — unwirksam gegen Drogen oder Gifte. Materialkomponente: V, S, M (normales Wasser in einem Zinnkrug).',
  description_en = 'Transforms normal water into a magical potion that must be imbibed before the spell duration ends. The potion removes hangovers and other ill effects of inebriation and negates any current state of drunkenness. Only effective against alcohol-based changes in the target''s physiology — ineffective against drugged stupors and poisons. Material component: V, S, M (common water served in a pewter mug).'
WHERE LOWER(name_en) = LOWER('Bugman''s Mug') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Macht Sand brennbar. Der Sand behält seine natürliche Form und Textur, erhält aber die brennbaren Eigenschaften von Laternenöl. Er brennt mit einer farblosen, geruchlosen Flamme für eine Stunde oder bis zum Ende der Zauberdauer. Kann offensiv genutzt werden, indem der Sand auf einen Gegner geworfen und angezündet wird — funktioniert dann genau wie brennendes Öl. Eine Handvoll brennender Sand erzeugt die gleiche Wärme wie ein kleines Lagerfeuer und kann zum Kochen verwendet werden. Brennender Sand kann durch keine natürlichen Mittel gelöscht werden, ideal bei nassen oder windigen Bedingungen. Komponenten: V, M.',
  description_en = 'Causes sand to become combustible. The sand retains its natural form and texture but gains the flammable properties of lantern oil. It burns with a colorless, odorless flame for one hour or until the spell duration ends. Can be used offensively by hurling the sand at an opponent and lighting it — functions exactly as burning oil. A single handful of burning sand gives off the same heat as a small campfire and can be used for cooking. Burning sand cannot be extinguished by any natural means, making it ideal in wet or windy conditions. Components: V, M.'
WHERE LOWER(name_en) = LOWER('Burning Sands') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verzaubert einen Jaguar, Ozelot oder ein anderes natürliches Raubtier der Katzenfamilie. Anders als die Vogelzauber der Pluma-Magie beschwört dieser Zauber die Katze nicht herbei — sie muss für den Zauberkundigen sichtbar und in Reichweite sein. Die verzauberte Katze versteht rudimentäre Befehle und führt einfache Aufgaben aus: Bewachen, Kämpfen oder Begleiten. Wird die Katze ohne den Zauberkundigen fortgeschickt (z.B. um eine Nachricht zu überbringen), macht sie jeden Tag einen Rettungswurf gegen Zauber; bei Erfolg wird der Zauber gebrochen. Komponenten: V, M.',
  description_en = 'Charms a jaguar, ocelot, or other natural feline creature. Unlike the bird charm spells of pluma magic, this spell does not summon the creature — the feline must be visible to the caster and within range. The charmed cat understands the caster''s rudimentary commands and performs simple tasks: guarding, fighting, or accompanying the caster. If sent somewhere without the caster (e.g., to carry a message), the cat makes a saving throw vs. spell every day it is separated; on success, the spell is broken. Components: V, M.'
WHERE LOWER(name_en) = LOWER('Cat Charm — Hishna') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Schleudert einen einzelnen Gegenstand von maximal 1,4 kg Gewicht in gerader Linie in die vom Zauberkundigen gezeigte Richtung. Der Gegenstand fliegt bis zur Reichweitengrenze und fällt dann zu Boden. Das Objekt muss lose und frei stehend sein, nicht von jemandem gehalten. Kann offensiv eingesetzt werden: Der Gegenstand trifft mit dem ETW0 des Zauberkundigen plus +3 Bonus. Das Geschoss gilt als +3 magische Waffe zum Zweck des Treffens (durchdringt Schutz vor normalen Geschossen), hat aber keinen Schadensbonus. Der Schaden hängt vom geschleuderten Gegenstand ab. Komponenten: V, S.',
  description_en = 'Hurls any single item weighing 1.4 kg or less in a straight line in the direction pointed by the caster. The item flies until it reaches the range limit, then falls to the ground. The object must be loose, freestanding, and not held by someone. Can be used offensively: the item hits with the caster''s THAC0 plus +3 bonus. The missile counts as a +3 magical weapon for purposes of hitting (penetrates Protection from Normal Missiles) but has no damage bonus. Damage depends on the item hurled. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Catapult') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verursacht bei erfolgreichem Berührungsangriff 1W8 Schadenspunkte. Nichtkörperliche, nichtlebende und extraplanare Kreaturen werden nicht betroffen, außer Untoten — diese werden stattdessen geheilt. Der verursachte Schaden muss natürlich heilen oder magisch geheilt werden. Anders als der Priester-Zauber Leichte Wunden Heilen hat dieser Zauber keine umkehrbare Form. Wird oft in Kombination mit dem Zauber Spektralhand (2. Stufe) eingesetzt. Das Wirken dieses Zaubers ist eine böse Handlung. Materialkomponente: V, S, M (eine auf die Hände aufgetragene Paste, aktiviert durch ein Befehlswort; Kosten 75 GM für drei Anwendungen).',
  description_en = 'Inflicts 1d8 points of damage on a successful touch attack. Noncorporeal, nonliving, and extraplanar creatures are not affected, except undead — which are cured instead. The inflicted damage must be healed naturally or cured with magic. Unlike the priest spell Cure Light Wounds, this spell has no reversed form. Often used in combination with the 2nd-level Spectral Hand spell. Casting this spell is an evil act. Material component: V, S, M (paste rubbed on the hands and activated by a command word; cost 75 gp for three castings).'
WHERE LOWER(name_en) = LOWER('Cause Light Wounds') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verändert die Färbung der berührten Kreatur, sodass sie sich dem Hintergrund anpasst. Auf Entfernungen über 9,1 m kann die Kreatur nicht entdeckt werden (es sei denn, jemand in der Nähe zeigt auf sie). Bei 9,1 m oder weniger hat die Kreatur eine 20%-Chance, sich im Schatten zu verbergen, ohne stillstehen zu müssen. Kreaturen mit der Fähigkeit „Im Schatten Verbergen" erhalten +20% Bonus, wenn sie stillstehen. Fernkampfangriffe gegen die geschützte Kreatur erleiden −4 Abzug. Bei allmählichem Hintergrundwechsel (Wald zu grüner Wiese) passt sich die Tarnung automatisch an. Bei abruptem Wechsel (Wald zu grauer Steinwand) dauert es eine Runde. Materialkomponente: V, S, M (die abgestreifte Haut einer kleinen Eidechse).',
  description_en = 'Alters the coloration of the touched creature to match the surrounding background. At distances greater than 9.1 m, the creature cannot be spotted (unless pointed out by someone standing closer). At 9.1 m or closer, the creature has a 20% chance to hide in shadows without needing to remain still. Creatures with Hide in Shadows ability gain +20% bonus if they remain still. Missile attacks against the protected creature suffer −4 penalty. When moving through areas where the background changes gradually (forest to green field), the chameleon coloration changes automatically. With abrupt background changes (forest to gray stone wall), one round is required. Material component: V, S, M (the shed skin of a small lizard).'
WHERE LOWER(name_en) = LOWER('Chameleon') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Zauberkundige muss mindestens Charisma 11 haben. Betrifft 1W4+4 Männer der 3. Stufe oder weniger in einem 4,6-m-Radius. „Mann" ist definiert als jeder männliche Mensch, Halbmensch oder Humanoide der Größe L oder kleiner mit 3 TW oder weniger. Wirkt ähnlich wie Bezaubern von Personen — Worte und Bitten des Zauberkundigen werden im günstigsten Licht gesehen. Schädigt der Zauberkundige ein betroffenes Wesen, wird der Zauber aufgehoben. Wirkt nicht auf Männer, die in der aktuellen Begegnung bereits vom Zauberkundigen Schaden erlitten haben. Ein Anführer in der Gruppe kann den Zauber sofort aufheben, wenn sein CHA + 1W8 mindestens 6 Punkte über dem CHA des Zauberkundigen liegt. Rettungswurf gegen Zauber negiert für einzelne Betroffene. Komponenten: V, S.',
  description_en = 'The caster must have at least Charisma 11. Affects 1d4+4 men of 3rd level or less in a 4.6 m radius. "Man" is defined as any male human, demihuman, or humanoid creature of size L or less with 3 HD or less. Works similarly to Charm Person — the caster''s words and requests are seen in the most favorable light. If the caster harms an affected creature, the spell is negated. Won''t work on any man who has taken damage from the caster in the current encounter. A leader in the group can negate the charm immediately if the leader''s CHA plus 1d8 is six or more points higher than the caster''s CHA. Saving throw vs. spell negates for individual targets. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Charm Man I') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt eine 10,2 cm große Kugel in der Hand des Zauberkundigen, die auf ein Ziel bis zu 27,4 m Entfernung geschleudert werden kann. Angriffswurfbonus: +3 bis 9,1 m, +2 bis 18,3 m, +1 bis 27,4 m. Verfehlt die Kugel oder gelingt der Rettungswurf, ist sie wirkungslos. Die Farbe der Kugel bestimmt den Effekt — der Zauberkundige kann jede Farbe seiner Stufe oder darunter wählen: Stufe 1 — Perlenweiss (Licht): Ziel von Licht umgeben, −4 auf Angriffe/RW/RK für 1 Runde. Stufe 2 — Rubinrot (Hitze): −1 STR und −1 GES für 1 Runde, schmilzt 1 m³ Eis. Stufe 3 — Flammenorange (Feuer): Entzündet Brennbares in 0,9 m Radius. Stufe 4 — Bernsteingelb (Blindheit): −4 Angriffe/RW/RK für 1 Runde/Stufe. Stufe 5 — Smaragdgrün (Stinkende Wolke). Stufe 6 — Türkis (Magnetismus). Stufe 7 — Blau (Lähmung). Höhere Stufen: weitere Effekte. Materialkomponente: V, S, M (ein Edelstein der entsprechenden Farbe oder ein Diamant, Mindestwert 50 GM).',
  description_en = 'Creates a 10.2 cm sphere in the caster''s hand that can be hurled at a target up to 27.4 m away. Attack roll bonus: +3 up to 9.1 m, +2 up to 18.3 m, +1 up to 27.4 m. If the orb misses or the saving throw succeeds, it is ineffective. The orb''s color determines the effect — the caster can choose any color of his level or lower: Level 1 — Pearly White (Light): Target surrounded by light, −4 attacks/saves/AC for 1 round. Level 2 — Ruby Red (Heat): −1 STR and −1 DEX for 1 round, melts 1 m³ ice. Level 3 — Flame Orange (Fire): Ignites combustibles within 0.9 m. Level 4 — Amber Yellow (Blindness): −4 attacks/saves/AC for 1 round/level. Level 5 — Emerald Green (Stinking Cloud). Level 6 — Turquoise (Magnetism). Level 7 — Blue (Paralysis). Higher levels: additional effects. Material component: V, S, M (a gem of appropriate hue or any diamond, minimum value 50 gp).'
WHERE LOWER(name_en) = LOWER('Chromatic Orb') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Durch diesen Zauber bündeln Lehrlinge und Verbündete eines Roten Zauberers ihre Macht. Der Rote Zauberer erhält zusätzliche Zauber pro Tag entsprechend der Summe seiner eigenen Stufe plus der Stufen aller Zauberer im Kreis (bis max. Stufe 30). Dies erhöht nur die Anzahl der memorierbaren Zauber, nicht die Zauberstufe des Wirkenden — er erhält keine Zauber höherer Stufe als er normalerweise wirken kann. Alle Kreismitglieder müssen der Schule des Zauberkundigen oder verbündeten Schulen angehören. Alle Teilnehmer (außer dem Empfänger) müssen den Kreiszauber memoriert haben und gleichzeitig wirken. Die Erschaffung des Kreises dauert eine Anzahl Runden gleich der Anzahl der Teilnehmer. Komponenten: V, S.',
  description_en = 'Through this spell, apprentices and allies of a Red Wizard pool their power. The Red Wizard receives additional spells per day equal to the sum of his own level plus the levels of all wizards in the circle (max level 30). This only increases the number of memorizable spells, not the caster''s level — he gains no spells of higher level than he can normally cast. All circle members must belong to the caster''s school or its allied schools. All participants (except the recipient) must have memorized the circle spell and cast it simultaneously. Creating the circle takes a number of rounds equal to the number of participants. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Circle — Red Wizard') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Wu Jen formt gewöhnlichen Rauch zu einer nebligen Leiter. Der Rauch muss von einem Feuer aus grünem Holz stammen. Bis zu 3 m Wolkenleiter pro Stufe des Zauberkundigen können geformt werden. Die Leiter wiegt praktisch nichts und kann von einer Person leicht gehandhabt werden. Sie ist stets stabil und starr — muss nicht angelehnt oder gestützt werden. Der Wu Jen platziert sie einfach in der gewünschten Position und klettert. Nur der Wu Jen und eine weitere Kreatur pro Stufe (vom Wu Jen bestimmt) können die Leiter benutzen. Vor Ablauf der Dauer kann der Wu Jen einen weiteren Wolkenleiter-Zauber auf eine bestehende Leiter wirken, um deren Form zu erhalten. Materialkomponente: V, S, M (ein großes Feuer aus grünem Holz).',
  description_en = 'The wu jen molds ordinary smoke into a misty ladder. The smoke must come from a fire of green wood. Up to 3 m of cloud ladder can be shaped per caster level. The ladder weighs virtually nothing and one person can easily handle one of any length. It is always steady and rigid — need not be supported or leaned against an object. The wu jen simply places it in position and climbs. Only the wu jen and one other creature per level (designated by the wu jen) can use the ladder. Before the spell expires, the wu jen can cast an additional cloud ladder spell on an existing ladder to maintain its form. Material component: V, S, M (a large fire of green wood).'
WHERE LOWER(name_en) = LOWER('Cloud Ladder') AND spell_type = 'wizard';
