-- ═══════════════════════════════════════════════════════════════════════════════
-- PHB Priest Spells Level 6 (Batch 1: 15 Spells)
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  description = 'Beschwört einen Luftdiener — ein mächtiges Luftelemental (16 TW, RK 3, 8W4 Schaden), das eine vom Priester bestimmte Aufgabe erfüllt. Der Luftdiener ist unglaublich schnell (72 m/Runde fliegend) und kann Gegenstände oder Kreaturen über große Entfernungen transportieren (max. 227 kg). Er kann auch eine bestimmte Kreatur aufspüren und zum Priester bringen. Der Luftdiener ist unsichtbar und nahezu geräuschlos. Wenn er seinen Auftrag nicht innerhalb von 1 Tag/Stufe erfüllen kann, wird er wütend und greift den Priester an. Materialkomponenten: V, S, M (das heilige Symbol, Weihrauch und Opfergaben im Wert von mind. 100 GM).',
  description_en = 'Summons an aerial servant — a powerful air elemental (16 HD, AC 3, 8d4 damage) that fulfills a task set by the priest. The aerial servant is incredibly fast (72 m/round flying) and can transport objects or creatures over great distances (max 227 kg). It can also track down a specific creature and bring it to the priest. The aerial servant is invisible and nearly silent. If it cannot fulfill its mission within 1 day/level, it becomes enraged and attacks the priest. Material components: V, S, M (the holy symbol, incense, and offerings worth at least 100 gp).'
WHERE name = 'Luftdiener' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Wie Tierbeschwörung I und II, aber beschwört bis zu 16 TW an normalen Tieren. Die Tiere erscheinen aus der Umgebung, gehorchen einfachen Befehlen und kämpfen bis zum Tod. Mögliche Tiere hängen vom Terrain ab. Bei 16 TW können mächtige Tiere gerufen werden: Bären, Großkatzen, Krokodile etc. Dauer 3 Runden/Stufe. Materialkomponente: V, S.',
  description_en = 'Like Animal Summoning I and II, but summons up to 16 HD of normal animals. The animals emerge from the surroundings, obey simple commands, and fight to death. Available animals depend on terrain. With 16 HD, powerful animals can be summoned: bears, great cats, crocodiles, etc. Duration 3 rounds/level. Components: V, S.'
WHERE name = 'Tierbeschwörung III' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Verleiht einem nichtlebenden Gegenstand (Stuhl, Statue, Teppich, Rüstung etc.) die Fähigkeit sich zu bewegen und einfache Befehle auszuführen. Der Gegenstand bewegt sich mit einer Rate, die von seiner Größe und Form abhängt (3-18 m/Runde). Ein belebter Gegenstand kann angreifen: Schaden basiert auf Größe und Material (z.B. ein belebter Stuhl 1W4, eine belebte Statue 2W8). Der Gegenstand hat Trefferpunkte basierend auf Material und Größe. Er kann keine komplexen Aufgaben erfüllen — nur einfache Bewegungen und Angriffe. Dauer 1 Runde/Stufe. Materialkomponente: V, S.',
  description_en = 'Grants a non-living object (chair, statue, carpet, armor, etc.) the ability to move and carry out simple commands. The object moves at a rate depending on its size and shape (3-18 m/round). An animated object can attack: damage is based on size and material (e.g., animated chair 1d4, animated statue 2d8). The object has hit points based on material and size. It cannot perform complex tasks — only simple movements and attacks. Duration 1 round/level. Components: V, S.'
WHERE name = 'Objekt Beleben' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Erzeugt eine unsichtbare Barriere in einem 3-m-Radius um den Priester, die alle Tiere (normal und magisch bis 4 TW) daran hindert einzudringen. Tiere mit mehr als 4 TW erhalten einen Rettungswurf gegen Zauber. Die Barriere bewegt sich mit dem Priester. Tiere, die bereits im Bereich sind, werden nicht hinausgedrängt — nur neue Tiere werden abgehalten. Der Zauber schützt gegen Tierangriffe, Insektenschwärme und ähnliches. Funktioniert nicht gegen Lykanthropen oder andere Gestaltwandler. Dauer 1 Stunde/Stufe. Materialkomponente: V, S, M (das heilige Symbol und ein Tropfen Quecksilber).',
  description_en = 'Creates an invisible barrier in a 3 m radius around the priest that prevents all animals (normal and magical up to 4 HD) from entering. Animals with more than 4 HD receive a saving throw vs. spell. The barrier moves with the priest. Animals already in the area are not pushed out — only new animals are blocked. The spell protects against animal attacks, insect swarms, and similar. Does not work against lycanthropes or other shapechangers. Duration 1 hour/level. Material component: V, S, M (the holy symbol and a drop of mercury).'
WHERE name = 'Anti-Tier-Hülle' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Erzeugt eine kreisförmige oder rechteckige Barriere aus wirbelnden, rasiermesserscharfen Klingen aus göttlicher Kraft. Die Barriere ist bis zu 18 m lang und 6 m hoch. Jede Kreatur, die die Barriere durchquert, erleidet 8W8 Schadenspunkte (kein Rettungswurf). Kreaturen in der Barriere beim Wirken erleiden ebenfalls vollen Schaden. Die Klingen schneiden durch alle Materialien außer Kraftwänden und Antimagie-Hüllen. Die Barriere ist undurchsichtig und blockiert Sicht. Dauer 3 Runden/Stufe. Materialkomponente: V, S.',
  description_en = 'Creates a circular or rectangular barrier of whirling, razor-sharp blades of divine force. The barrier is up to 18 m long and 6 m high. Any creature passing through the barrier takes 8d8 damage (no saving throw). Creatures in the barrier at casting also take full damage. The blades cut through all materials except Walls of Force and Anti-Magic Shells. The barrier is opaque and blocks sight. Duration 3 rounds/level. Components: V, S.'
WHERE name = 'Klingenbarriere' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Wie der Magier-Zauber Elementar Beschwören, aber der Priester ruft 1-3 Tiere herbei, die sofort kämpfen. Die herbeigerufenen Tiere haben insgesamt bis zu 2 × Stufe des Priesters TW. Der Priester kann die Art der Tiere nicht wählen — der SL bestimmt sie basierend auf dem Terrain. Die Tiere sind loyal und kämpfen bis zum Tod. Dauer Spezial — die Tiere bleiben, bis sie sterben, der Priester sie entlässt, oder sie ihren Auftrag erfüllt haben. Materialkomponente: V, S.',
  description_en = 'Like the wizard''s Conjure Elemental, but the priest summons 1-3 animals that fight immediately. The summoned animals have a total of up to 2 × priest level HD. The priest cannot choose the animal type — the DM determines them based on terrain. The animals are loyal and fight to death. Duration special — animals stay until they die, the priest dismisses them, or they fulfill their mission. Components: V, S.'
WHERE name = 'Tiere Herbeirufen' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Beschwört ein Feuerelementar (12 TW, RK 2, 3W8 Schaden) aus einem vorhandenen Feuer (mind. ein großes Lagerfeuer). Das Elemental dient dem Priester, solange dieser seine volle Konzentration darauf verwendet. Bei Konzentrationsverlust (Schaden, Ablenkung) wird das Elemental unkontrolliert und greift den Priester an! Das Feuerelementar kann nur durch Wasser (3W6 Schaden), Magie Bannen oder Vernichtung gestoppt werden. Es entzündet alles Brennbare in seiner Nähe. Dauer 1 Stunde/Stufe. Materialkomponenten: V, S, M (das heilige Symbol, ein großes offenes Feuer und Opfergaben).',
  description_en = 'Summons a fire elemental (12 HD, AC 2, 3d8 damage) from an existing fire (at least a large campfire). The elemental serves the priest as long as full concentration is maintained. On concentration loss (damage, distraction), the elemental becomes uncontrolled and attacks the priest! The fire elemental can only be stopped by water (3d6 damage), Dispel Magic, or destruction. It ignites all combustibles nearby. Duration 1 hour/level. Material components: V, S, M (the holy symbol, a large open fire, and offerings).'
WHERE name = 'Feuerelementar Beschwören' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Der Priester kennt immer den kürzesten und sichersten Weg zu einem bestimmten Ort — sei es ein Gebäude, eine Stadt, ein Dungeon-Ausgang oder eine bestimmte Person. Der Zauber zeigt den direkten Weg (nicht unbedingt den einfachsten), umgeht aber tödliche Fallen und verschlossene Wege. Er funktioniert auch in Labyrinthen und unter der Erde. In magisch geschützten Bereichen (Labyrinth-Zauber, Verbotene Bereiche) muss ein Rettungswurf gegen Zauber bestanden werden. Umkehrbar: Weg Verlieren — lässt ein Ziel den Weg verlieren (Rettungswurf negiert). Dauer 1 Stunde/Stufe. Materialkomponenten: V, S, M (ein Satz Wahrsageinstrumente — Knochen, Stöcke, Steine etc.).',
  description_en = 'The priest always knows the shortest and safest route to a specific location — be it a building, city, dungeon exit, or specific person. The spell shows the direct path (not necessarily the easiest), bypassing lethal traps and locked passages. It also works in labyrinths and underground. In magically protected areas (Maze spell, Forbidden areas), a saving throw vs. spell must be passed. Reversible: Lose the Path — causes a target to become lost (save negates). Duration 1 hour/level. Material components: V, S, M (a set of divination instruments — bones, sticks, stones, etc.).'
WHERE name = 'Weg Finden' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Der Priester verwandelt Eicheln oder Holundeerbeeren in magische Brandgeschosse. Eicheln: Bis zu 4 Eicheln werden zu Granaten — jede kann geworfen werden (9 m Reichweite) und explodiert bei Aufprall in einem 1,5-m-Radius für 2W8 Feuerschaden (Rettungswurf halbiert). Holunderbeeren: Bis zu 8 Beeren werden zu verzögerten Brandbomben — wenn sie in Feuer geworfen werden, explodieren sie 1 Runde später für 1W8 Feuerschaden pro Beere im 1,5-m-Radius. Der Priester kann die Variante beim Wirken wählen. Dauer Spezial — die Samen behalten ihre Magie 1 Runde/Stufe. Materialkomponenten: V, S, M (Eicheln oder Holunderbeeren).',
  description_en = 'The priest transforms acorns or holly berries into magical incendiary missiles. Acorns: Up to 4 acorns become grenades — each can be thrown (9 m range) and explodes on impact in a 1.5 m radius for 2d8 fire damage (save halves). Holly berries: Up to 8 berries become delayed incendiary bombs — when thrown into fire, they explode 1 round later for 1d8 fire damage per berry in 1.5 m radius. The priest chooses the variant at casting. Duration special — seeds retain their magic for 1 round/level. Material components: V, S, M (acorns or holly berries).'
WHERE name = 'Feuersamen' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Versiegelt einen Bereich von bis zu 5,4 m × 5,4 m pro Stufe gegen planare Reisen und Teleportation. Keine Kreatur kann den Bereich durch Teleportation, Dimensionstür, Ebenenreise, ätherisches Reisen oder ähnliche Mittel betreten oder verlassen. Der Priester kann Ausnahmen festlegen (bestimmte Kreaturen, bestimmte Gesinnungen). Kreaturen, die trotzdem versuchen den Bereich zu betreten, erleiden 4W6 Schaden (Rettungswurf halbiert). Der Priester muss den Bereich mit Weihwasser (oder Unheiligem Wasser) markieren. Permanent bis gebannt. Materialkomponenten: V, S, M (Weihwasser und Weihrauch im Wert von mind. 1.000 GM pro 5,4 m × 5,4 m).',
  description_en = 'Seals an area of up to 5.4 m × 5.4 m per level against planar travel and teleportation. No creature can enter or leave the area through teleportation, Dimension Door, Plane Shift, ethereal travel, or similar means. The priest can specify exceptions (certain creatures, certain alignments). Creatures that still attempt to enter take 4d6 damage (save halves). The priest must mark the area with holy water (or unholy water). Permanent until dispelled. Material components: V, S, M (holy water and incense worth at least 1,000 gp per 5.4 m × 5.4 m).'
WHERE name = 'Bann' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Der mächtigste Heilzauber. Heilt ALLE Trefferpunkte einer berührten Kreatur vollständig (bis zum Maximum). Zusätzlich heilt der Zauber alle Krankheiten, Blindheit, Taubheit und Schwachsinn. Er heilt jedoch NICHT: fehlende Gliedmaßen (dafür Regeneration), Stufenverlust (dafür Wiederherstellung) oder Tod. Umkehrbar: Schaden — reduziert eine berührte Kreatur auf 1W4 TP und infiziert sie mit einer schweren Krankheit (Rettungswurf gegen Zauber negiert). Materialkomponente: V, S.',
  description_en = 'The most powerful healing spell. Heals ALL hit points of a touched creature completely (to maximum). Additionally, the spell cures all diseases, blindness, deafness, and feeblemind. However, it does NOT heal: missing limbs (Regenerate needed), level loss (Restoration needed), or death. Reversible: Harm — reduces a touched creature to 1d4 HP and infects it with a serious disease (saving throw vs. spell negates). Components: V, S.'
WHERE name = 'Heilung' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Erzeugt ein großes Festmahl, das bis zu 1 Kreatur/Stufe für 12 Stunden mit übermenschlichem Mut und Stärke erfüllt. Die Teilnehmer des Festmahls erhalten: Immunität gegen Furcht, +1 auf Trefferwürfe und Schadenswürfe, und 1W4+4 temporäre Trefferpunkte. Das Festmahl heilt außerdem alle bestehenden Furchteffekte. Die Nahrung erscheint magisch und umfasst ein vollständiges Mahl mit Getränken. Das Mahl dauert 1 volle Stunde — die Effekte beginnen erst nach Abschluss des Mahls. Materialkomponenten: V, S, M (das heilige Symbol und Nahrungsmittel im Wert von mind. 100 GM).',
  description_en = 'Creates a great feast that fills up to 1 creature/level with superhuman courage and strength for 12 hours. Feast participants gain: immunity to fear, +1 to attack and damage rolls, and 1d4+4 temporary hit points. The feast also cures all existing fear effects. The food appears magically and includes a complete meal with drinks. The meal takes 1 full hour — effects only begin after the meal is completed. Material components: V, S, M (the holy symbol and foodstuffs worth at least 100 gp).'
WHERE name = 'Heldenmahl' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Verwandelt einen großen Eichenast (oder kleinen Eichenbaum) in einen mächtigen Baumherren-ähnlichen Wächter (12 TW, RK 0, 4W6 Schaden). Der Wächter gehorcht einfachen Befehlen des Priesters: Wache halten, Angreifen, Verteidigen etc. Er kann sich mit 9 m/Runde bewegen und durch Wald und Dickicht navigieren. Der Wächter ist immun gegen die meisten normalen Waffen (nur magische Waffen +1 oder besser) und anfällig für Feuer (doppelter Schaden). Wenn er getötet wird, verwandelt er sich in einen normalen Haufen Holz zurück. Dauer permanent (bis getötet oder verwandelt). Materialkomponenten: V, S, M (der Priester muss den Eichenast eigenhändig schneiden und mit dem heiligen Symbol berühren).',
  description_en = 'Transforms a large oak branch (or small oak tree) into a powerful treant-like guardian (12 HD, AC 0, 4d6 damage). The guardian obeys simple commands: guard, attack, defend, etc. It can move at 9 m/round and navigate through forest and thicket. The guardian is immune to most normal weapons (only magical weapons +1 or better) and vulnerable to fire (double damage). When killed, it reverts to a normal pile of wood. Duration permanent (until killed or transformed). Material components: V, S, M (the priest must cut the oak branch by hand and touch it with the holy symbol).'
WHERE name = 'Lebenseiche' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Der Priester teilt ein Gewässer (Fluss, See, Meer etc.) und erzeugt einen trockenen Korridor von 1 m Breite pro Stufe und bis zu 6 m Tiefe pro Stufe. Die Wasserwände stehen links und rechts wie unsichtbare Mauern. Kreaturen und Gegenstände können den Korridor frei durchqueren. Der Boden ist schlammig aber begehbar. Am Ende der Zauberdauer stürzt das Wasser zurück — Kreaturen im Korridor müssen einen Rettungswurf bestehen oder werden fortgerissen (Ertrinken möglich). Dauer 1 Stunde/Stufe. Materialkomponenten: V, S, M (das heilige Symbol und ein Stab).',
  description_en = 'The priest parts a body of water (river, lake, sea, etc.) creating a dry corridor 1 m wide per level and up to 6 m deep per level. Water walls stand left and right like invisible barriers. Creatures and objects can freely traverse the corridor. The bottom is muddy but walkable. At the spell''s end, the water rushes back — creatures in the corridor must save or be swept away (drowning possible). Duration 1 hour/level. Material components: V, S, M (the holy symbol and a staff).'
WHERE name = 'Wasser Teilen' AND spell_type = 'priest';
