-- ═══════════════════════════════════════════════════════════════════════════════
-- PHB Priest Spells Level 5 (Batch 2: 7 Spells)
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  description = 'Der Priester bindet eine Kreatur an eine vom Priester gestellte Aufgabe oder Quest. Ähnlich dem Magier-Zauber Geas (6. Stufe), aber göttlichen Ursprungs. Das Ziel erhält einen Rettungswurf gegen Zauber. Bei Misserfolg MUSS die Kreatur die Aufgabe erfüllen. Pro Tag des Nicht-Befolgens wird die Kreatur um 1 Punkt in einem Attribut geschwächt (SL-Wahl). Bei 0 in einem Attribut stirbt sie. Der Quest kann nicht durch Magie Bannen aufgehoben werden — nur durch Begrenzter Wunsch, Wunsch oder Erfüllung der Aufgabe. Wenn die Aufgabe unmöglich ist, kann ein neuer Quest als Ersatz dienen. Materialkomponente: V, S.',
  description_en = 'The priest binds a creature to a task or quest set by the priest. Similar to the wizard Geas spell (6th level) but of divine origin. The target receives a saving throw vs. spell. On failure, the creature MUST fulfill the task. For each day of non-compliance, the creature weakens by 1 point in an attribute (DM choice). At 0 in any attribute, it dies. The quest cannot be removed by Dispel Magic — only by Limited Wish, Wish, or task completion. If the task is impossible, a new quest can serve as replacement. Components: V, S.'
WHERE name = 'Quest' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Der Priester erzeugt einen schimmernden Regenbogen, der als Brücke oder als Waffe dient. Als Brücke: Der Regenbogen erstreckt sich über bis zu 36 m pro Stufe und kann von bis zu 10 Personen gleichzeitig begangen werden (Tragkraft 90 kg pro Person). Er funktioniert wie ein stabiler Steg. Als Waffe: Der Priester kann den Regenbogen in einem 36-m-Bogen schwingen, der jede Kreatur im Pfad trifft und für 1W6 Runden Blindheit verursacht (Rettungswurf gegen Zauber negiert). Nur eine Anwendung pro Wirken möglich. Dauer 1 Runde/Stufe. Materialkomponenten: V, S, M (das heilige Symbol und ein Stück Quarz oder Prisma).',
  description_en = 'The priest creates a shimmering rainbow that serves as a bridge or a weapon. As bridge: extends up to 36 m per level and can be walked by up to 10 persons simultaneously (90 kg capacity per person). It functions as a stable walkway. As weapon: the priest can swing the rainbow in a 36 m arc, striking every creature in the path and causing blindness for 1d6 rounds (saving throw vs. spell negates). Only one application per casting. Duration 1 round/level. Material components: V, S, M (the holy symbol and a piece of quartz or prism).'
WHERE name = 'Regenbogen' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Erweckt eine tote Kreatur zum Leben zurück. Die Kreatur darf nicht länger als 1 Tag pro Stufe des Priesters tot sein. Die Kreatur kehrt mit 1 TP zurück und muss 1 Tag pro Stufe, die sie im Leben hatte, ruhen, um vollständig zu genesen. Sie verliert permanent 1 Punkt Konstitution (bei KON 0 ist die Auferstehung unmöglich). Die Kreatur muss einen Systemschock-Wurf bestehen oder die Erweckung schlägt fehl. Funktioniert nicht auf Elfen (die reinkarniert werden müssen), Untote, Konstrukte oder Kreaturen, die nicht bereit sind zurückzukehren. Umkehrbar: Finger des Todes — tötet eine Kreatur sofort (Rettungswurf gegen Tod negiert; bei Erfolg 2W8+1 Schaden). Materialkomponenten: V, S, M (das heilige Symbol und Weihrauch).',
  description_en = 'Raises a dead creature back to life. The creature must not have been dead longer than 1 day per priest level. The creature returns with 1 HP and must rest 1 day per level it had in life to fully recover. It permanently loses 1 point of Constitution (at CON 0, resurrection is impossible). The creature must make a system shock roll or the raising fails. Does not work on elves (who must be reincarnated), undead, constructs, or creatures unwilling to return. Reversible: Slay Living — kills a creature instantly (save vs. death negates; on success 2d8+1 damage). Material components: V, S, M (the holy symbol and incense).'
WHERE name = 'Tote Erwecken' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Lässt natürlichen Fels in einem Bereich von bis zu 3 m × 3 m pro Stufe scharfe, harte Stacheln wachsen. Die Stacheln sind in den Boden eingebettet und kaum sichtbar (wie natürliche Steine). Kreaturen, die den Bereich betreten, erleiden 1W4 Schaden pro 3 m Bewegung und müssen bei jedem Schritt einen Rettungswurf bestehen oder werden für 1W4+1 Runden verlangsamt (halbe Bewegungsrate). Schuhe bieten keinen Schutz (die Stacheln durchdringen normales Schuhwerk). Nur Kreaturen mit harten Hufen oder fliegende Kreaturen sind immun. Dauer 3W4 Runden + 1 Stunde/Stufe. Materialkomponente: V, S, M (mehrere scharfe Steinsplitter).',
  description_en = 'Causes natural rock in an area of up to 3 m × 3 m per level to grow sharp, hard spikes. The spikes are embedded in the ground and barely visible (like natural stones). Creatures entering the area take 1d4 damage per 3 m of movement and must save each step or be slowed for 1d4+1 rounds (half movement rate). Shoes offer no protection (spikes penetrate normal footwear). Only creatures with hard hooves or flying creatures are immune. Duration 3d4 rounds + 1 hour/level. Material component: V, S, M (several sharp stone splinters).'
WHERE name = 'Stachelfelsen' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Wie der gleichnamige Magier-Zauber (5. Stufe). Verwandelt bis zu 10 m³/Stufe natürlichen Fels in Schlamm. Kreaturen sinken mit 1,5 m/Runde. Umkehrbar: Schlamm zu Fels. Permanent. Materialkomponenten: V, S, M (Ton und Wasser bzw. Sand und Wasser).',
  description_en = 'Like the wizard spell of the same name (5th level). Transmutes up to 10 m³/level of natural rock into mud. Creatures sink at 1.5 m/round. Reversible: Mud to Rock. Permanent. Material components: V, S, M (clay and water, or sand and water).'
WHERE name = 'Fels zu Schlamm (Priester)' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Wie der gleichnamige Magier-Zauber (6. Stufe). Der Priester sieht die Dinge wie sie wirklich sind: Unsichtbares wird sichtbar, Illusionen durchschaut, Verwandlungen in wahrer Form erkannt, Gesinnungen offenbart, ätherischer Grenzbereich sichtbar. Reichweite 36 m. Durchdringt magische Dunkelheit und Illusionen aller Art. Dauer 1 Runde/Stufe. Materialkomponenten: V, S, M (eine Salbe für die Augen aus seltenen Zutaten im Wert von mind. 300 GM).',
  description_en = 'Like the wizard spell of the same name (6th level). The priest sees things as they truly are: invisible becomes visible, illusions seen through, transformations recognized in true form, alignments revealed, Ethereal border visible. Range 36 m. Penetrates magical darkness and illusions of all kinds. Duration 1 round/level. Material components: V, S, M (an eye ointment from rare ingredients worth at least 300 gp).'
WHERE name = 'Wahres Sehen (Priester)' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Wie der gleichnamige Magier-Zauber (4. Stufe), aber als Priester-Zauber der 5. Stufe. Erzeugt eine undurchsichtige Feuerwand bis zu 6 m/Stufe Länge, 6 m hoch. Kreaturen innerhalb von 3 m auf der heißen Seite erleiden 2W4 Feuerschaden, Durchschreiten verursacht 2W6+Stufe Feuerschaden. Untote erleiden doppelten Schaden. Dauer Konzentration oder 1 Runde/Stufe. Materialkomponente: V, S, M (Phosphor).',
  description_en = 'Like the wizard spell of the same name (4th level), but as a 5th-level priest spell. Creates an opaque wall of fire up to 6 m/level in length, 6 m high. Creatures within 3 m on the hot side take 2d4 fire damage, passing through deals 2d6+level fire damage. Undead take double damage. Duration concentration or 1 round/level. Material component: V, S, M (phosphorus).'
WHERE name = 'Feuerwand (Priester)' AND spell_type = 'priest';
