-- ═══════════════════════════════════════════════════════════════════════════════
-- PHB Wizard Spells Level 7-9: Komplette Beschreibungs-Neuschreibung (DE + EN)
-- Alle mechanischen Details, Materialkomponenten, Spezialfälle
-- Metrisch, eng an Originaltexten orientiert
-- ═══════════════════════════════════════════════════════════════════════════════

-- ─── WIZARD LEVEL 7 ──────────────────────────────────────────────────────────

UPDATE public.spells SET
  description = 'Wie der Verbannung-Zauber (5. Stufe), aber mächtiger. Der Zaubernde verbannt eine oder mehrere extraplanare Kreaturen (Dämonen, Teufel, Elementare etc.) auf ihre Heimatebene. Das Ziel erhält einen Rettungswurf gegen Zauber mit Modifikatoren basierend auf der TW-Differenz. Mehrere Kreaturen können gleichzeitig verbannt werden, solange ihre kombinierten TW die doppelte Stufe des Zaubernden nicht übersteigen. Materialkomponenten, die der Kreatur verhasst sind, verbessern die Chance um −1 bis −6. Der Zauber ist permanent — die verbannten Kreaturen können nicht auf natürlichem Weg zurückkehren. Materialkomponenten: V, S, M (Gegenstände, die den zu verbannenden Kreaturen verhasst sind).',
  description_en = 'Like the Dismissal spell (5th level), but more powerful. The caster banishes one or more extraplanar creatures (demons, devils, elementals, etc.) to their home plane. The target receives a saving throw vs. spell with modifiers based on HD difference. Multiple creatures can be banished simultaneously as long as their combined HD do not exceed twice the caster''s level. Material components loathsome to the creature improve the chance by −1 to −6. The spell is permanent — banished creatures cannot return by natural means. Material components: V, S, M (items the creatures to be banished find loathsome).'
WHERE name = 'Verbannung' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Zaubernde erlangt die Kontrolle über 1W4+1 Untote mit insgesamt bis zu 3 TW pro Stufe des Zaubernden. Die Untoten erhalten keinen Rettungswurf. Kontrollierte Untote gehorchen den verbalen Befehlen des Zaubernden vollständig — sie können kämpfen, Wache halten, Gegenstände tragen etc. Intelligente Untote (Vampire, Lichs etc.) erhalten einen Rettungswurf gegen Zauber mit Bonus gleich ihrer Intelligenz. Der Zaubernde kann den Untoten komplexe Befehle geben, wenn er ihre Sprache spricht. Dauer 3W4 Runden + 1 Runde/Stufe. Nach Zauberende sind die Untoten feindlich gesinnt. Materialkomponenten: V, S, M (ein kleiner Stück Knochen und ein Stück rohes Fleisch).',
  description_en = 'The caster gains control over 1d4+1 undead with a total of up to 3 HD per caster level. The undead receive no saving throw. Controlled undead fully obey the caster''s verbal commands — they can fight, stand guard, carry objects, etc. Intelligent undead (vampires, liches, etc.) receive a saving throw vs. spell with a bonus equal to their Intelligence. The caster can give complex commands if he speaks their language. Duration 3d4 rounds + 1 round/level. After the spell ends, the undead are hostile. Material components: V, S, M (a small piece of bone and a piece of raw meat).'
WHERE name = 'Untote Kontrollieren' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Wie der normale Feuerball (3. Stufe), aber mit zwei wesentlichen Unterschieden: Erstens verursacht er 1W6+1 Schaden pro Stufe (statt 1W6), und zweitens kann der Zaubernde die Detonation um bis zu 5 Runden verzögern. Die erbsengroße Flamme schwebt am Zielpunkt und detoniert entweder nach der festgelegten Verzögerung oder wenn eine Kreatur sie berührt. Der Schaden beträgt max. 15W6+15 (bei Stufe 15+). Rettungswurf gegen Zauber halbiert den Schaden. Der Explosionsradius beträgt 6 m. Materialkomponenten: V, S, M (eine winzige Kugel aus Fledermausdung und Schwefel, umhüllt mit Talg).',
  description_en = 'Like the normal Fireball (3rd level), but with two key differences: first, it deals 1d6+1 damage per level (instead of 1d6), and second, the caster can delay the detonation by up to 5 rounds. The pea-sized flame hovers at the target point and detonates either after the set delay or when a creature touches it. Maximum damage is 15d6+15 (at level 15+). Saving throw vs. spell halves the damage. Explosion radius is 6 m. Material components: V, S, M (a tiny ball of bat guano and sulphur, wrapped in tallow).'
WHERE name = 'Verzögerter Feuerball' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Zaubernde kann sofort einen einzelnen Gegenstand herbeizaubern, der sich bis zu 0,5 m³ groß sein kann und nicht mehr als 227 kg wiegen darf. Der Gegenstand muss dem Zaubernden bekannt sein (er muss ihn zuvor gesehen oder genau beschrieben bekommen haben). Der Gegenstand wird von seinem aktuellen Standort teleportiert und erscheint in den Händen des Zaubernden. Lebende Kreaturen können nicht herbeigezaubert werden. Magische Gegenstände erhalten einen Rettungswurf (als ob vom Besitzer gewürfelt). Materialkomponente: V, S, M (eine winzige Nachbildung des gewünschten Gegenstands).',
  description_en = 'The caster can instantly summon a single object of up to 0.5 m³ in size and no more than 227 kg in weight. The object must be known to the caster (he must have seen it before or had it described in detail). The object is teleported from its current location and appears in the caster''s hands. Living creatures cannot be summoned. Magical items receive a saving throw (as if rolled by the owner). Material component: V, S, M (a tiny replica of the desired object).'
WHERE name = 'Drawmijs Sofortige Beschwörung' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Zaubernde verwandelt sich in ein zweidimensionales Wesen — völlig flach und seitwärts unsichtbar. In dieser Form ist der Zaubernde nur von vorne oder hinten sichtbar — von der Seite betrachtet verschwindet er vollständig. Er kann sich durch Ritzen und Spalten von nur 2,5 cm Breite zwängen. Der Zaubernde kann weiter zaubern, angreifen und sich normal bewegen. Angreifer, die von der Seite angreifen, haben eine 75% Chance, den Zaubernden zu verfehlen. Flächeneffekte (Feuerball etc.) wirken normal. Dauer 3 Runden + 1 Runde/Stufe. Materialkomponenten: V, S, M (ein Stück Elfenbein, das nicht weniger als 200 GM wert ist, geformt wie eine kleine Silhouette).',
  description_en = 'The caster transforms himself into a two-dimensional being — completely flat and invisible from the side. In this form, the caster is only visible from the front or back — viewed from the side, he vanishes completely. He can squeeze through cracks and gaps of only 2.5 cm width. The caster can still cast spells, attack, and move normally. Attackers from the side have a 75% chance of missing. Area effects (Fireball, etc.) work normally. Duration 3 rounds + 1 round/level. Material components: V, S, M (a piece of ivory worth at least 200 gp, shaped like a small silhouette).'
WHERE name = 'Duo-Dimension' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Zaubernde streckt seinen Finger aus und richtet einen tödlichen Strahl negativer Energie auf eine einzelne Kreatur. Das Ziel muss einen Rettungswurf gegen Tod bestehen oder stirbt sofort. Bei erfolgreichem Rettungswurf erleidet das Ziel trotzdem 2W8+1 Schadenspunkte. Der Zauber wirkt nicht gegen Untote (die von negativer Energie gestärkt werden) oder Kreaturen, die immun gegen Todesmagie sind. Der Todeseffekt ist sofort und kann nur durch Auferstehung, Wunsch oder ähnliche mächtige Magie rückgängig gemacht werden. Materialkomponente: V, S.',
  description_en = 'The caster extends his finger and directs a deadly ray of negative energy at a single creature. The target must make a saving throw vs. death or die instantly. On a successful save, the target still takes 2d8+1 damage. The spell does not work on undead (who are strengthened by negative energy) or creatures immune to death magic. The death effect is instant and can only be reversed by Resurrection, Wish, or similar powerful magic. Components: V, S.'
WHERE name = 'Todesfinger' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt einen würfelförmigen Käfig aus magischer Kraft (6 m × 6 m × 6 m). Der Käfig besteht entweder aus Kraftstäben (2,5 cm Abstand — nichts kann passieren außer Luft) oder aus Kraftwänden (solide, undurchdringlich). Der Käfig ist unzerstörbar durch physische oder magische Mittel — nur Magie Bannen oder Desintegration können ihn aufheben. Teleportation aus dem Käfig heraus ist unmöglich. Selbst ätherische Kreaturen können nicht entkommen. Im Innern ist frische Luft vorhanden. Dauer 1 Stunde/Stufe. Materialkomponenten: V, S, M (Rubinstaub im Wert von 1.500 GM, der beim Wirken verzehrt wird).',
  description_en = 'Creates a cube-shaped cage of magical force (6 m × 6 m × 6 m). The cage consists of either force bars (2.5 cm apart — nothing can pass except air) or solid force walls (impenetrable). The cage is indestructible by physical or magical means — only Dispel Magic or Disintegrate can remove it. Teleportation out of the cage is impossible. Even ethereal creatures cannot escape. Fresh air is present inside. Duration 1 hour/level. Material components: V, S, M (ruby dust worth 1,500 gp, consumed in casting).'
WHERE name = 'Kraftkäfig' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ein mächtiger Wunschzauber mit Einschränkungen. Der Begrenzter Wunsch kann: einen Zauber der 1.-7. Stufe jeder Klasse duplizieren, einen einzelnen vergangenen Ereigniseffekt rückgängig machen, einen temporären Attributsbonus von +1 gewähren, einen verlorenen Gegenstand wiederbeschaffen (sofern er noch existiert) oder ähnliche Effekte erzeugen. Der Zauber kann NICHT: Tote dauerhaft erwecken, permanente Attributserhöhungen gewähren, Wünsche der 9. Stufe duplizieren, oder die Realität grundlegend verändern. Die genaue Interpretation liegt beim SL — schlecht formulierte Wünsche können unerwartete Nebenwirkungen haben. Die Ausführung des Zaubers altert den Zaubernden um 1 Jahr. Komponenten: V, S.',
  description_en = 'A powerful wish spell with limitations. The Limited Wish can: duplicate any spell of 1st-7th level of any class, undo a single past event effect, grant a temporary +1 attribute bonus, retrieve a lost item (if it still exists), or produce similar effects. The spell CANNOT: permanently raise the dead, grant permanent attribute increases, duplicate 9th-level wishes, or fundamentally alter reality. Exact interpretation is up to the DM — poorly worded wishes can have unexpected side effects. Casting the spell ages the caster by 1 year. Components: V, S.'
WHERE name = 'Begrenzter Wunsch' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Wie der Unsichtbarkeit, 10 Fuß Radius Zauber, aber wirkt auf eine viel größere Anzahl von Kreaturen. Der Zauber macht bis zu 10 Kreaturen/Stufe des Zaubernden oder alternativ alle Kreaturen in einem 54-m-Radius unsichtbar. Die Unsichtbarkeit bricht individuell bei offensiven Handlungen. Im Gegensatz zur normalen Gruppenabdeckung müssen die Kreaturen nicht im Radius des Zaubernden bleiben — sie sind nach dem Wirken frei beweglich und bleiben unsichtbar. Dauer permanent bis zur individuellen offensiven Handlung oder bis gebannt. Materialkomponenten: V, S, M (eine Wimper in Gummi arabicum).',
  description_en = 'Like the Invisibility, 10'' Radius spell, but affects a much larger number of creatures. The spell makes up to 10 creatures/level or alternatively all creatures in a 54 m radius invisible. Invisibility breaks individually upon offensive actions. Unlike normal group coverage, creatures need not stay within the caster''s radius — they are free to move after casting and remain invisible. Duration permanent until individual offensive action or until dispelled. Material components: V, S, M (an eyelash in gum arabic).'
WHERE name = 'Massenunsuchtbarkeit' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Beschwört 1W3 Monster der 5. Stufe (RK 2, 5 TW, 2W8 Schaden), die sofort dem Zaubernden dienen. Die genaue Art wird vom SL basierend auf dem Terrain bestimmt. Monster erscheinen in 1W4 Runden und kämpfen bis zum Tod oder Zauberende. Dauer 6 Runden + 1 Runde/Stufe. Materialkomponenten: V, S, M (ein kleiner Beutel und ein Kerzenstummel).',
  description_en = 'Summons 1d3 5th-level monsters (AC 2, 5 HD, 2d8 damage) that immediately serve the caster. The exact type is determined by the DM based on terrain. Monsters appear in 1d4 rounds and fight to death or spell''s end. Duration 6 rounds + 1 round/level. Material components: V, S, M (a small bag and a candle stub).'
WHERE name = 'Monsterbeschwörung V' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt eine extradimensionale Behausung — eine prächtige Villa mit bis zu Stufe × 3 Räumen, ausgestattet mit Möbeln, Beleuchtung und Nahrung für bis zu 2 × Stufe Personen. Die Villa hat einen unsichtbaren Eingang, der nur dem Zaubernden und von ihm benannten Gästen sichtbar ist. Im Inneren herrschen angenehme Temperaturen. Die Villa bietet vollständigen Schutz vor den Elementen und den meisten Kreaturen. Dauer Stufe des Zaubernden in Stunden. Unsichtbare Diener (wie der Zauber 1. Stufe) bedienen die Gäste. Materialkomponenten: V, S, M (eine Miniatur-Elfenbein-Tür, ein Stück polierter Marmor und ein Silberlöffel, zusammen mind. 500 GM wert).',
  description_en = 'Creates an extradimensional dwelling — a magnificent mansion with up to level × 3 rooms, furnished with furniture, lighting, and food for up to 2 × level persons. The mansion has an invisible entrance visible only to the caster and named guests. Comfortable temperatures prevail inside. The mansion provides full protection from the elements and most creatures. Duration caster''s level in hours. Unseen servants (like the 1st-level spell) attend to guests. Material components: V, S, M (a miniature ivory door, a piece of polished marble, and a silver spoon, worth at least 500 gp together).'
WHERE name = 'Mordenkainens Prächtige Villa' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt ein schimmerndes Schwert aus reiner magischer Kraft, das selbstständig kämpft. Das Schwert greift jedes vom Zaubernden bezeichnete Ziel an, mit einem THAC0 von 19 minus der Stufe des Zaubernden (max. THAC0 7). Es verursacht 5W4 Schaden pro Treffer und kann nur von magischen Kreaturen oder Zaubern getroffen werden (RK −3, TP gleich der Stufe des Zaubernden). Das Schwert schwebt und kämpft innerhalb von 9 m um den Zaubernden, benötigt keine Konzentration, und kann durch Wände und Barrieren fliegen. Magie Bannen oder Antimagie-Hülle beenden das Schwert. Dauer 1 Runde/Stufe. Materialkomponenten: V, S, M (eine Miniatur-Platinschwertklinge im Wert von 500 GM plus ein Stück Diamant und einen Splitter Eisen).',
  description_en = 'Creates a shimmering sword of pure magical force that fights independently. The sword attacks any target designated by the caster, with a THAC0 of 19 minus the caster''s level (max THAC0 7). It deals 5d4 damage per hit and can only be hit by magical creatures or spells (AC −3, HP equal to the caster''s level). The sword hovers and fights within 9 m of the caster, requires no concentration, and can fly through walls and barriers. Dispel Magic or Anti-Magic Shell end the sword. Duration 1 round/level. Material components: V, S, M (a miniature platinum sword blade worth 500 gp plus a piece of diamond and a sliver of iron).'
WHERE name = 'Mordenkainens Schwert' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt einen unsichtbaren, dimensionalen Durchgang durch eine feste Barriere (Stein, Metall, Holz etc.). Der Durchgang ist nur für den Zaubernden sichtbar und nutzbar — andere Kreaturen sehen und spüren nur eine feste Wand. Der Zaubernde kann den Durchgang nach Belieben betreten und verlassen. Die Phasentür kann bis zu 3 m dick sein und durchdringt jedes nichtmagische Material. Magische Barrieren (Kraftwand, Antimagie-Hülle) blockieren den Durchgang. Die Tür erlaubt 1 Durchgang pro 2 Stufen des Zaubernden, danach verschwindet sie. Permanent bis alle Durchgänge aufgebraucht sind oder gebannt wird. Komponenten: V.',
  description_en = 'Creates an invisible dimensional passage through a solid barrier (stone, metal, wood, etc.). The passage is visible and usable only to the caster — other creatures see and feel only a solid wall. The caster can enter and exit the passage at will. The phase door can be up to 3 m thick and penetrates any nonmagical material. Magical barriers (Wall of Force, Anti-Magic Shell) block the passage. The door allows 1 passage per 2 caster levels, then vanishes. Permanent until all passages are used or dispelled. Component: V.'
WHERE name = 'Phasentür' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Zaubernde spricht ein einzelnes Wort der Macht, das eine Kreatur mit 90 oder weniger aktuellen Trefferpunkten sofort für 1W4+4 Runden betäubt (kein Rettungswurf). Kreaturen mit 91-120 TP werden für 1W4 Runden betäubt. Kreaturen mit mehr als 120 TP sind immun. Betäubte Kreaturen können nicht handeln, sprechen oder sich bewegen — sie können weiter sehen und hören, aber sonst nichts tun. Danach erholen sie sich automatisch und sind 1W4 Runden benommen (−2 auf Trefferwürfe, RK und Rettungswürfe). Komponente: V.',
  description_en = 'The caster speaks a single word of power that instantly stuns a creature with 90 or fewer current hit points for 1d4+4 rounds (no saving throw). Creatures with 91-120 HP are stunned for 1d4 rounds. Creatures with more than 120 HP are immune. Stunned creatures cannot act, speak, or move — they can still see and hear but nothing else. Afterward they recover automatically and are dazed for 1d4 rounds (−2 to attack rolls, AC, and saving throws). Component: V.'
WHERE name = 'Machtwort: Betäubung' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt sieben Strahlen in einem kegelförmigen Bereich (21 m lang, 1,5 m breit am Ausgangspunkt, 9 m breit am Ende). Jede Kreatur im Bereich wird von 1-2 zufälligen Strahlen getroffen. Die sieben Farben und ihre Effekte: Rot — 20 Feuerschaden (Rettungswurf halbiert); Orange — 40 Säureschaden (Rettungswurf halbiert); Gelb — 80 Blitzschaden (Rettungswurf halbiert); Grün — Gift (Rettungswurf oder Tod); Blau — Versteinerung (Rettungswurf negiert); Indigo — Wahnsinn (Rettungswurf negiert); Violett — auf andere Ebene geschickt (Rettungswurf negiert). Jede Kreatur wird von 1W4−1 Strahlen getroffen (min. 1). Materialkomponente: V, S.',
  description_en = 'Creates seven beams in a cone-shaped area (21 m long, 1.5 m wide at origin, 9 m wide at end). Each creature in the area is struck by 1-2 random beams. The seven colors and effects: Red — 20 fire damage (save halves); Orange — 40 acid damage (save halves); Yellow — 80 lightning damage (save halves); Green — poison (save or die); Blue — petrification (save negates); Indigo — insanity (save negates); Violet — sent to another plane (save negates). Each creature is hit by 1d4−1 beams (min 1). Components: V, S.'
WHERE name = 'Prismatischer Spray' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Kehrt die Schwerkraft in einem Bereich von 9 m × 9 m um. Alle Kreaturen und Gegenstände im Bereich „fallen" zur Decke hinauf (oder in den Himmel, wenn im Freien). Der Fallschaden beträgt 1W6 pro 3 m Fallhöhe (wie normaler Fall). Kreaturen, die sich an etwas festhalten können, vermeiden den Fall (GES-Wurf). Wenn der Zauber endet, fallen alle Kreaturen wieder herunter (erneuter Fallschaden). Fliegende Kreaturen können normal manövrieren. Dauer 1 Runde/Stufe. Materialkomponenten: V, S, M (ein Magnet und Eisenfeilspäne).',
  description_en = 'Reverses gravity in a 9 m × 9 m area. All creatures and objects in the area "fall" upward to the ceiling (or into the sky if outdoors). Fall damage is 1d6 per 3 m of fall height (like normal falling). Creatures that can grab hold of something avoid the fall (DEX check). When the spell ends, all creatures fall back down (further fall damage). Flying creatures can maneuver normally. Duration 1 round/level. Material components: V, S, M (a magnet and iron filings).'
WHERE name = 'Schwerkraft Umkehren' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Macht eine Kreatur oder einen Gegenstand unsichtbar und verhindert jede Ortung durch Wahrsagungszauber. Das Ziel kann nicht durch Hellsehen, ESP, Kristallkugel, Magie Entdecken oder ähnliche Mittel aufgespürt werden. Zusätzlich wird die Kreatur in einen Zustand versetzt, der dem Scheintod ähnelt — sie altert nicht, benötigt keine Nahrung und ist gegen alle Umwelteinflüsse immun. Die Kreatur kann nur durch eine spezifische, vom Zaubernden festgelegte Auslösebedingung erweckt werden. Wahres Sehen enthüllt die Kreatur. Permanent bis aufgehoben oder Auslöser eintritt. Materialkomponenten: V, S, M (eine Basilisken-Schuppe und ein Stück Gummi arabicum).',
  description_en = 'Makes a creature or object invisible and prevents any location by divination spells. The target cannot be found by Clairvoyance, ESP, Crystal Ball, Detect Magic, or similar means. Additionally, the creature is placed in a state resembling suspended animation — it does not age, needs no food, and is immune to all environmental effects. The creature can only be awakened by a specific trigger condition set by the caster. True Seeing reveals the creature. Permanent until lifted or trigger occurs. Material components: V, S, M (a basilisk scale and a piece of gum arabic).'
WHERE name = 'Sequestrierung' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt ein Duplikat einer Kreatur aus Schnee und Eis, das teilweise real ist. Das Simulakrum hat die Hälfte der TP des Originals und kennt alles, was das Original zum Zeitpunkt der Erschaffung wusste. Es hat die Fähigkeiten und Fertigkeiten des Originals, aber auf der halben Effektivitätsstufe. Das Simulakrum gehorcht dem Zaubernden bedingungslos. Es kann nicht heilen (außer durch begrenzte Wunsch-Magie) und kann nicht lernen oder sich weiterentwickeln. Wird es getötet, zerfällt es zu Schnee. Magie Bannen oder Wahres Sehen enthüllt es als Fälschung. Permanent bis zerstört. Materialkomponenten: V, S, M (Schnee oder Eis als Basis, Rubinstaub im Wert von 500 GM pro TW des Originals, und ein Stück der Originalkreatur — Haar, Blut etc.).',
  description_en = 'Creates a duplicate of a creature from snow and ice that is partially real. The simulacrum has half the HP of the original and knows everything the original knew at the time of creation. It has the original''s abilities and skills but at half effectiveness level. The simulacrum obeys the caster unconditionally. It cannot heal (except by Limited Wish magic) and cannot learn or improve. When killed, it dissolves into snow. Dispel Magic or True Seeing reveals it as fake. Permanent until destroyed. Material components: V, S, M (snow or ice as base, ruby dust worth 500 gp per HD of original, and a piece of the original creature — hair, blood, etc.).'
WHERE name = 'Trugbild (Simulakrum)' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Jeder Zauber, der direkt auf den Zaubernden gerichtet wird, wird automatisch zum Angreifer zurückreflektiert. Die Reflexion betrifft bis zu 1W4+6 Zauberstufen an eingehenden Zaubern (z.B. ein 5.-Stufe-Zauber verbraucht 5 Stufen der Kapazität). Flächenzauber werden nicht reflektiert — nur Zauber, die den Zaubernden als Einzelziel haben. Berührungs-Zauber werden ebenfalls reflektiert (der Angreifer wird von seinem eigenen Zauber getroffen). Wenn die Kapazität der Zauberreflexion aufgebraucht ist, endet der Zauber. Dauer bis Kapazität aufgebraucht oder 3 Runden/Stufe (was zuerst eintritt). Materialkomponente: V, S, M (ein kleines silbernes Spiegel).',
  description_en = 'Any spell directed specifically at the caster is automatically reflected back at the attacker. The reflection affects up to 1d4+6 spell levels of incoming spells (e.g., a 5th-level spell uses 5 levels of capacity). Area spells are not reflected — only spells targeting the caster individually. Touch spells are also reflected (the attacker is hit by his own spell). When the reflection capacity is exhausted, the spell ends. Duration until capacity is used or 3 rounds/level (whichever comes first). Material component: V, S, M (a small silver mirror).'
WHERE name = 'Zauberreflexion' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verwandelt den Zaubernden (und seine gesamte Ausrüstung) in eine steinerne Statue. In Statuenform ist der Zaubernde immun gegen die meisten Angriffe — er hat die Härte und Schadenresistenz von Stein. Er kann nicht durch Gift, Gas, Kälte oder ähnliches beeinflusst werden. Der Zaubernde kann nach Belieben zwischen Statuen- und normaler Form wechseln (erfordert 1 Segment). In Statuenform kann er seine Umgebung wahrnehmen (sehen und hören). Er kann nicht zaubern oder sprechen. Physischer Schaden an der Statue wird beim Zurückverwandeln als Schaden am Zaubernden übertragen. Dauer 6 Stunden/Stufe. Materialkomponenten: V, S, M (Kalk, Sand und ein Tropfen Wasser plus Eisen).',
  description_en = 'Transforms the caster (and all equipment) into a stone statue. In statue form, the caster is immune to most attacks — he has the hardness and damage resistance of stone. He cannot be affected by poison, gas, cold, or similar. The caster can switch between statue and normal form at will (requires 1 segment). In statue form he can perceive his surroundings (see and hear). He cannot cast spells or speak. Physical damage to the statue is transferred as damage to the caster when reverting. Duration 6 hours/level. Material components: V, S, M (calciumite, sand, and a drop of water plus iron).'
WHERE name = 'Statue' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Wie der normale Teleportieren-Zauber, aber ohne Fehlerrisiko. Der Zaubernde teleportiert sich sofort und fehlerfrei zu einem bekannten Ort auf derselben Ebene. Im Gegensatz zum normalen Teleportieren gibt es keine Chance auf „hoch" oder „tief" Ankunft — der Zaubernde kommt IMMER exakt am gewünschten Ort an. Der Ort muss dem Zaubernden bekannt sein (auch nur aus Beschreibung). Alles was er trägt (max. 113 kg nichtlebend) wird mittransportiert. Materialkomponente: V.',
  description_en = 'Like the normal Teleport spell, but without any error risk. The caster teleports instantly and without error to a known location on the same plane. Unlike normal Teleport, there is no chance of "high" or "low" arrival — the caster ALWAYS arrives at exactly the desired location. The location must be known to the caster (even from description alone). Everything carried (max 113 kg nonliving) is transported. Component: V.'
WHERE name = 'Teleportieren ohne Fehler' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Zauber teleportiert einen Gegenstand (max. 0,5 m³/Stufe) zu einem vom Zaubernden bestimmten Ort — entweder an einen bekannten Ort auf derselben Ebene oder auf die Ätherische Ebene (wie Leomunds Geheime Truhe, aber ohne Miniatur-Schlüssel). Bei Teleportation auf die Ätherische Ebene ist der Gegenstand praktisch unwiederbringlich (nur durch Begrenzter Wunsch, Wunsch oder eine Reise auf die Ätherische Ebene). Bei Teleportation an einen bekannten Ort gelten die normalen Teleportieren-Genauigkeitsregeln. Kann auch verwendet werden, um die Teleportation eines Gegenstands zu beschleunigen. Materialkomponente: V, S.',
  description_en = 'The spell teleports an object (max 0.5 m³/level) to a location determined by the caster — either to a known location on the same plane or to the Ethereal Plane (like Leomund''s Secret Chest, but without a miniature key). When teleported to the Ethereal Plane, the object is virtually irrecoverable (only by Limited Wish, Wish, or an Ethereal Plane journey). When teleported to a known location, normal Teleport accuracy rules apply. Can also be used to expedite teleportation of objects. Components: V, S.'
WHERE name = 'Verschwinden' AND spell_type = 'wizard';

-- ─── WIZARD LEVEL 8 ──────────────────────────────────────────────────────────

UPDATE public.spells SET
  description = 'Der Zauber hat zwei Anwendungen: Antipathie — erzeugt eine Aura um den Zaubernden oder einen Gegenstand, die eine bestimmte Kreaturenart (oder Gesinnung) abstößt. Betroffene Kreaturen müssen den Bereich (9-m-Radius) verlassen und erleiden −2 auf DEX, solange sie sich darin aufhalten. Rettungswurf gegen Zauber negiert. Sympathie — erzeugt eine anziehende Aura, die eine bestimmte Kreaturenart (oder Gesinnung) anzieht. Betroffene Kreaturen fühlen sich zum Bereich hingezogen und verweilen dort, widerwillig zu gehen. Rettungswurf gegen Zauber erlaubt das Verlassen. Dauer 2 Stunden/Stufe. Materialkomponenten: V, S, M (für Antipathie: ein Tropfen Essig; für Sympathie: ein Tropfen Honig; plus 1.000 GM in Gold).',
  description_en = 'The spell has two applications: Antipathy — creates an aura around the caster or an object that repels a specific creature type (or alignment). Affected creatures must leave the area (9 m radius) and suffer −2 to DEX while within. Saving throw vs. spell negates. Sympathy — creates an attractive aura that draws a specific creature type (or alignment). Affected creatures feel compelled to approach and remain, reluctant to leave. Saving throw vs. spell allows leaving. Duration 2 hours/level. Material components: V, S, M (for Antipathy: a drop of vinegar; for Sympathy: a drop of honey; plus 1,000 gp in gold).'
WHERE name = 'Antipathie-Sympathie' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt eine riesige, schwebende Hand aus magischer Kraft (RK −2, TP gleich dem vollen TP-Wert des Zaubernden), die einen Gegner angreift. Die geballte Faust trifft als Kämpfer mit THAC0 der halben Stufe des Zaubernden und verursacht 1W6+Stufe Schaden pro Treffer. Die Faust kann eine einzelne Kreatur pro Runde angreifen und bewegt sich mit einer Geschwindigkeit von 6 m/Runde. Sie kann nicht getäuscht werden und greift weiter an, bis das Ziel stirbt oder der Zauber endet. Magie Bannen, Desintegration oder eine Kraftwand kann die Faust aufhalten. Dauer 1 Runde/Stufe. Materialkomponente: V, S, M (ein Handschuh und eine Prise Knetmasse).',
  description_en = 'Creates a huge, floating hand of magical force (AC −2, HP equal to the caster''s full HP value) that attacks an opponent. The clenched fist attacks as a fighter with THAC0 of half the caster''s level and deals 1d6+level damage per hit. The fist can attack a single creature per round and moves at 6 m/round. It cannot be fooled and continues attacking until the target dies or the spell ends. Dispel Magic, Disintegrate, or a Wall of Force can stop the fist. Duration 1 round/level. Material component: V, S, M (a glove and a pinch of putty).'
WHERE name = 'Bigbys Geballte Faust' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Fesselt eine mächtige außerplanare Kreatur (Dämon, Dschinn, Elementar etc.) an einen Ort und verhindert ihre Flucht. Es gibt mehrere Varianten der Bindung: Verkettung (Kreatur an einen Ort gebunden), Einkerkerung (Kreatur in einem Miniaturkäfig gefangen), Begrenzung (Kreatur in einem magischen Kreis), Metamorphose (Kreatur in eine andere Form verwandelt), Verzögerter Dienst (Kreatur dient dem Zaubernden unter bestimmten Bedingungen), und Schlaf (Kreatur in magischem Schlaf). Das Ziel erhält einen Rettungswurf gegen Zauber mit einem Modifikator von −1 pro 2 Stufen des Zaubernden. Permanent bis aufgehoben. Materialkomponenten: V, S, M (variiert je nach Bindungsform — mindestens 500 GM an speziellen Materialien).',
  description_en = 'Binds a powerful extraplanar creature (demon, djinni, elemental, etc.) to a location and prevents its escape. Several binding variants exist: Chaining (creature bound to location), Hedged Prison (creature in miniature cage), Bound (creature in magic circle), Metamorphosis (creature transformed), Minimus Containment (creature shrunk into gem), and Slumber (creature in magical sleep). The target receives a saving throw vs. spell with a modifier of −1 per 2 caster levels. Permanent until lifted. Material components: V, S, M (varies by binding form — at least 500 gp of special materials).'
WHERE name = 'Bindung' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt ein Duplikat des Zaubernden aus einem Stück Fleisch des Zaubernden (Haut, Blut, Haar etc.). Der Klon wächst in 2W4 Monaten zu einer vollständigen Kopie heran. Wenn der Zaubernde stirbt, erwacht der Klon mit allen Erinnerungen und Fähigkeiten des Zaubernden zum Zeitpunkt der Klonentnahme. Wenn der Zaubernde noch lebt, wenn der Klon reift, werden beide Körper wahnsinnig und versuchen einander zu töten — der Überlebende behält die Vernunft. Es kann nur ein Klon gleichzeitig existieren. Der Klon hat dieselbe Stufe und Fähigkeiten wie das Original zum Zeitpunkt der Entnahme. Materialkomponenten: V, S, M (ein Stück Fleisch des Zaubernden und eine spezielle Nährlösung im Wert von 1.000 GM).',
  description_en = 'Creates a duplicate of the caster from a piece of the caster''s flesh (skin, blood, hair, etc.). The clone grows to full maturity in 2d4 months. If the caster dies, the clone awakens with all memories and abilities of the caster at the time the flesh was taken. If the caster is still alive when the clone matures, both bodies go insane and attempt to kill each other — the survivor retains sanity. Only one clone can exist at a time. The clone has the same level and abilities as the original at the time of extraction. Material components: V, S, M (a piece of the caster''s flesh and a special nutrient solution worth 1,000 gp).'
WHERE name = 'Klon' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Wie der Sendung-Zauber, aber der Zaubernde kann eine Nachricht von 25 Worten an eine bekannte Kreatur senden und gleichzeitig eine Suggestion einweben. Das Ziel erhält einen Rettungswurf gegen Zauber, um die Suggestion abzuwehren — selbst wenn der Rettungswurf erfolgreich ist, empfängt das Ziel die Nachricht. Reichweite unbegrenzt (auf derselben Ebene). Das Ziel kann mit bis zu 25 Worten antworten. Materialkomponenten: V, S, M (ein kurzes Stück Kupferdraht und ein kleiner Kupferbecher).',
  description_en = 'Like the Sending spell, but the caster can send a 25-word message to a known creature and simultaneously weave in a Suggestion. The target receives a saving throw vs. spell to resist the suggestion — even on a successful save, the target receives the message. Range unlimited (on the same plane). The target can reply with up to 25 words. Material components: V, S, M (a short piece of copper wire and a small copper cup).'
WHERE name = 'Forderung' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verwandelt einen gläsernen Gegenstand in ein Material so hart wie Stahl — aber mit der Transparenz von Glas. Glasstahl hat die Festigkeit von echtem Stahl: gleiche Trefferpunkte, gleiche Bruchresistenz, gleiche Schadenstoleranz. Es kann als Rüstung (mit dem Vorteil der Durchsichtigkeit — man kann dahinterliegende Dinge sehen) oder als Waffe (ein gläsernes Schwert so scharf wie Stahl) verwendet werden. Der Zauber wirkt auf bis zu 5 kg Glas pro Stufe des Zaubernden. Permanent. Materialkomponente: V, S, M (ein kleines Stück Glas und ein kleiner Stahlsplitter).',
  description_en = 'Transforms a glass object into a material as hard as steel — but with the transparency of glass. Glassteel has the strength of real steel: same hit points, same breaking resistance, same damage tolerance. It can be used as armor (with the advantage of transparency — one can see through it) or as a weapon (a glass sword as sharp as steel). The spell works on up to 5 kg of glass per caster level. Permanent. Material component: V, S, M (a small piece of glass and a small steel splinter).'
WHERE name = 'Glasstahl' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt eine Wolke aus glühender Asche und Rauch (6 m Radius, 6 m Höhe), die sich mit 3 m/Runde in Windrichtung bewegt. Die Wolke verursacht zunächst 1W2 Schaden pro Runde an allen Kreaturen darin (kein Rettungswurf). Nach der 3. Runde entzündet sich die Wolke explosionsartig und verursacht 1W2 Schaden pro Stufe des Zaubernden an allen Kreaturen im Bereich (Rettungswurf gegen Zauber halbiert). Die Wolke bewegt sich wie eine Nebelwolke und kann durch starke Winde zerstreut werden (was die Entzündung verhindert). Dauer 1W6+Stufe Runden (explodiert in der Runde nach dem natürlichen Ende). Materialkomponenten: V, S, M (eine Nussschale oder ein Stück Kohle und ein Tropfen Öl).',
  description_en = 'Creates a cloud of glowing embers and smoke (6 m radius, 6 m height) that moves at 3 m/round in wind direction. The cloud initially deals 1d2 damage per round to all creatures within (no save). After the 3rd round, the cloud ignites explosively dealing 1d2 damage per caster level to all creatures in the area (saving throw vs. spell halves). The cloud moves like a fog cloud and can be dispersed by strong winds (preventing ignition). Duration 1d6+level rounds (explodes the round after natural end). Material components: V, S, M (a nutshell or piece of coal and a drop of oil).'
WHERE name = 'Brandwolke' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Wie der Monster Bezaubern Zauber, aber betrifft alle Kreaturen in einem 9-m-Radius (kein TW-Limit). Jede Kreatur erhält einen individuellen Rettungswurf gegen Zauber (WEI-Modifikator). Bezauberte Kreaturen betrachten den Zaubernden als vertrauenswürdigen Freund. Die Dauer und die Befreiungschancen sind wie beim Monster Bezaubern (abhängig von den TW der Kreatur). Alle bezauberten Kreaturen sind voneinander unabhängig — wenn eine den Zauber bricht, bleiben die anderen bezaubert. Materialkomponente: V, S.',
  description_en = 'Like the Charm Monster spell, but affects all creatures in a 9 m radius (no HD limit). Each creature receives an individual saving throw vs. spell (WIS modifier). Charmed creatures regard the caster as a trusted friend. Duration and escape chances are as per Charm Monster (depending on creature''s HD). All charmed creatures are independent — if one breaks the spell, the others remain charmed. Components: V, S.'
WHERE name = 'Massenbezauberung' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verbannt eine Kreatur in ein extradimensionales Labyrinth. Die Kreatur erhält keinen Rettungswurf. Die Zeit, die die Kreatur benötigt, um den Ausgang zu finden, hängt von ihrer Intelligenz ab: INT 2 oder weniger = 2W4 Runden × 10; INT 3-5 = 2W4 Runden; INT 6-8 = 1W4 Runden; INT 9-11 = 1W4 Runden −1 (min. 1); INT 12-14 = 2W4 Segmente; INT 15-17 = 1W4 Segmente; INT 18+ = 1 Segment. Minotauren und Kreaturen mit perfektem Richtungssinn entkommen sofort (1 Segment). Die Kreatur kehrt zum gleichen Ort zurück, von dem sie verschwunden ist. Der Irrgarten kann nicht von außen betreten oder beeinflusst werden. Materialkomponente: V, S.',
  description_en = 'Banishes a creature into an extradimensional maze. The creature receives no saving throw. Time to find the exit depends on Intelligence: INT 2 or less = 2d4 turns × 10; INT 3-5 = 2d4 turns; INT 6-8 = 1d4 turns; INT 9-11 = 1d4 turns −1 (min 1); INT 12-14 = 2d4 segments; INT 15-17 = 1d4 segments; INT 18+ = 1 segment. Minotaurs and creatures with perfect direction sense escape immediately (1 segment). The creature returns to the same spot it vanished from. The maze cannot be entered or affected from outside. Components: V, S.'
WHERE name = 'Irrgarten' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Zaubernde oder eine berührte Kreatur wird vollständig immun gegen alle Formen geistiger Beeinflussung: ESP, Bezauberung, Suggestion, Geas, Massensuggestion, Beherrschung, Schwachsinn, Wahnsinn und ähnliche Effekte. Auch magische Gegenstände wie Helme der Gedankenkontrolle sind wirkungslos. Der Geschützte erscheint unter Wahrsagungszaubern (Hellsehen etc.) als „nicht vorhanden" — er kann nicht aufgespürt oder beobachtet werden. Dauer 24 Stunden. Materialkomponenten: V, S.',
  description_en = 'The caster or a touched creature becomes completely immune to all forms of mental influence: ESP, Charm, Suggestion, Geas, Mass Suggestion, Domination, Feeblemind, insanity, and similar effects. Magical items like Helms of Telepathy are also ineffective. The protected creature appears as "not present" to divination spells (Clairvoyance, etc.) — it cannot be found or observed. Duration 24 hours. Components: V, S.'
WHERE name = 'Gedankenleere' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Beschwört 1W3 Monster der 6. Stufe (RK 0, 6 TW, 3W4 Schaden), die sofort dem Zaubernden dienen. Die genaue Art wird vom SL bestimmt. Monster erscheinen in 1W4 Runden und kämpfen bis zum Tod oder Zauberende. Dauer 7 Runden + 1 Runde/Stufe. Materialkomponenten: V, S, M (ein kleiner Beutel und ein Kerzenstummel).',
  description_en = 'Summons 1d3 6th-level monsters (AC 0, 6 HD, 3d4 damage) that immediately serve the caster. The exact type is determined by the DM. Monsters appear in 1d4 rounds and fight to death or spell''s end. Duration 7 rounds + 1 round/level. Material components: V, S, M (a small bag and a candle stub).'
WHERE name = 'Monsterbeschwörung VI' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt eine transparente Kugel aus telekinetischer Kraft um eine einzelne Kreatur. Im Gegensatz zu Otilukes Widerstandsfähiger Kugel kann der Zaubernde die Kugel telekinetisch bewegen — mit 3 m/Runde in jede Richtung oder bis zu 54 m schleudern. Beim Schleudern erleidet die eingeschlossene Kreatur 1W4 Schaden pro 3 m Aufprall und muss einen Rettungswurf gegen Tod bestehen oder das Bewusstsein verlieren. Die Kugel hat RK −5 und kann nur durch Magie Bannen oder Desintegration zerstört werden. Frische Luft ist vorhanden. Dauer 1 Runde/Stufe. Materialkomponenten: V, S, M (ein Stück klarer Kristall, eine Prise Eisenstaub und ein Paar kleine Magnete).',
  description_en = 'Creates a transparent sphere of telekinetic force around a single creature. Unlike Otiluke''s Resilient Sphere, the caster can telekinetically move the sphere — at 3 m/round in any direction or hurl it up to 54 m. When hurled, the enclosed creature takes 1d4 damage per 3 m of impact and must save vs. death or lose consciousness. The sphere has AC −5 and can only be destroyed by Dispel Magic or Disintegrate. Fresh air is present. Duration 1 round/level. Material components: V, S, M (a piece of clear crystal, a pinch of iron dust, and a pair of small magnets).'
WHERE name = 'Otilukes Telekinesekugel' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Zwingt eine Kreatur zu einem unwiderstehlichen, lächerlichen Tanz. Das Ziel erhält keinen Rettungswurf. Die tanzende Kreatur kann nicht angreifen, zaubern oder sich kontrolliert bewegen — sie tanzt wild und unkontrolliert. Ihre RK verschlechtert sich um 4, Rettungswürfe erleiden −2. Andere Kreaturen erhalten +4 auf Trefferwürfe gegen den Tänzer (von hinten). Die tanzende Kreatur lässt gehaltene Gegenstände nach 1W4 Runden fallen. Nach Zauberende ist die Kreatur 1W4 Runden benommen (−2 auf Trefferwürfe und RK). Dauer 1W4+1 Runden. Reichweite Berührung oder 9 m. Materialkomponente: V, S.',
  description_en = 'Forces a creature into an irresistible, ridiculous dance. The target receives no saving throw. The dancing creature cannot attack, cast spells, or move in a controlled manner — it dances wildly and uncontrollably. Its AC worsens by 4, saving throws suffer −2. Other creatures gain +4 to attack rolls against the dancer (from behind). The dancing creature drops held items after 1d4 rounds. After the spell ends, the creature is dazed for 1d4 rounds (−2 to attack rolls and AC). Duration 1d4+1 rounds. Range touch or 9 m. Components: V, S.'
WHERE name = 'Ottos Unwiderstehlicher Tanz' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Macht einen Zauber (oder mehrere) permanent auf einer Kreatur, einem Gegenstand oder einem Bereich. Folgende Zauber können permanent gemacht werden: Magie Entdecken, Unsichtbarkeit, Licht, Schutz vor Bösem, Schutz vor normalen Geschossen, Vergrößern, Hast und andere (nach Ermessen des SL). Pro Wirken von Permanenz verliert der Zaubernde permanent 1 Punkt Konstitution. Der resultierende permanente Effekt kann durch Magie Bannen aufgehoben werden (bei Kreaturen) oder ist tatsächlich permanent (bei Gegenständen/Bereichen). Materialkomponente: V, S.',
  description_en = 'Makes a spell (or several) permanent on a creature, object, or area. The following spells can be made permanent: Detect Magic, Invisibility, Light, Protection from Evil, Protection from Normal Missiles, Enlarge, Haste, and others (DM discretion). Each casting of Permanency costs the caster 1 point of Constitution permanently. The resulting permanent effect can be removed by Dispel Magic (on creatures) or is truly permanent (on objects/areas). Components: V, S.'
WHERE name = 'Permanenz' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der mächtigste Verwandlungszauber: verwandelt jedes Objekt oder jede Kreatur in jedes andere Objekt oder jede andere Kreatur. Dauer und Dauerhaftigkeit hängen davon ab, wie ähnlich sich Original und neue Form sind (gemessen an Größe, Intelligenz, Königreich). Ähnliche Verwandlungen (Mensch→Mensch) sind sehr lange haltbar, während extreme Verwandlungen (Stein→Mensch) nur Stunden halten. Das Ziel erhält einen Rettungswurf gegen Zauber bei unfreiwilliger Verwandlung. Die verwandelte Kreatur erhält die physischen Fähigkeiten der neuen Form, behält aber zunächst ihren Intellekt (der sich über die Zeit angleicht). Materialkomponente: V, S, M (Quecksilber, Gummi arabicum und Rauch).',
  description_en = 'The most powerful polymorph spell: transforms any object or creature into any other object or creature. Duration and permanence depend on how similar original and new form are (measured by size, intelligence, kingdom). Similar transformations (human→human) are very long-lasting, while extreme ones (stone→human) last only hours. The target receives a saving throw vs. spell on unwilling transformation. The transformed creature gains the physical abilities of the new form but initially retains its intellect (which adjusts over time). Material component: V, S, M (mercury, gum arabic, and smoke).'
WHERE name = 'Beliebig Verwandeln' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Zaubernde spricht ein einzelnes Wort der Macht, das eine Kreatur mit 100 oder weniger aktuellen TP sofort und permanent erblindet (kein Rettungswurf). Kreaturen mit 101-200 TP werden für 1W4+1 Runden geblendet. Kreaturen mit mehr als 200 TP werden für 1W4+1 Runden benommen (−2 auf Trefferwürfe und RK). Die Blindheit kann nur durch Heilung, Wiederherstellung, Wunsch oder ähnliche mächtige Magie geheilt werden. Magie Bannen hat keine Wirkung auf die Blindheit. Komponente: V.',
  description_en = 'The caster speaks a single word of power that instantly and permanently blinds a creature with 100 or fewer current HP (no saving throw). Creatures with 101-200 HP are blinded for 1d4+1 rounds. Creatures with more than 200 HP are dazed for 1d4+1 rounds (−2 to attack rolls and AC). The blindness can only be cured by Heal, Restoration, Wish, or similar powerful magic. Dispel Magic has no effect on the blindness. Component: V.'
WHERE name = 'Machtwort: Blindheit' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt eine schimmernde, mehrschichtige Wand aus Lichtbändern (bis zu 6 m breit pro Stufe, 6 m hoch). Die Wand hat sieben farbige Schichten mit jeweils eigenem Effekt. Von außen nach innen: Rot — blockiert nichtmagische Geschosse, 20 Feuerschaden (Rettungswurf halbiert); Orange — blockiert magische Geschosse, 40 Säureschaden (Rettungswurf halbiert); Gelb — blockiert Gift/Gas, 80 Blitzschaden (Rettungswurf halbiert); Grün — blockiert Atemwaffen, Rettungswurf gegen Gift oder Tod; Blau — blockiert Wahrsagung, Versteinerung (Rettungswurf negiert); Indigo — blockiert Zauber, Wahnsinn (Rettungswurf negiert); Violett — blockiert alles, auf andere Ebene geschickt (Rettungswurf negiert). Jede Schicht kann nur durch den entsprechenden Gegenzauber aufgelöst werden. Dauer 1 Stunde/Stufe. Materialkomponente: V, S.',
  description_en = 'Creates a shimmering, multi-layered wall of light bands (up to 6 m wide per level, 6 m high). The wall has seven colored layers, each with its own effect. From outside in: Red — blocks nonmagical missiles, 20 fire damage (save halves); Orange — blocks magical missiles, 40 acid damage (save halves); Yellow — blocks poison/gas, 80 lightning damage (save halves); Green — blocks breath weapons, save vs. poison or die; Blue — blocks divination, petrification (save negates); Indigo — blocks spells, insanity (save negates); Violet — blocks everything, sent to another plane (save negates). Each layer can only be dissolved by its specific counterspell. Duration 1 hour/level. Components: V, S.'
WHERE name = 'Prismatische Wand' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt eine mächtige illusorische Tarnung über einem Bereich von bis zu 9 m × 9 m pro Stufe. Innerhalb der Abschirmung erscheint alles so, wie der Zaubernde es bestimmt: Kreaturen können unsichtbar oder anders aussehend gemacht werden, das Terrain kann verändert werden, und Wahrsagungszauber werden blockiert. Der Zauber ist mächtiger als normale Illusionen — er umfasst alle Sinne und kann nicht durch einfaches Berühren durchschaut werden. Wahres Sehen zeigt die echte Szene hinter der Abschirmung. Dauer 1 Stunde/Stufe. Materialkomponente: V, S.',
  description_en = 'Creates a powerful illusory camouflage over an area of up to 9 m × 9 m per level. Within the screen, everything appears as the caster determines: creatures can be made invisible or appear different, terrain can be altered, and divination spells are blocked. The spell is more powerful than normal illusions — it encompasses all senses and cannot be penetrated by simple touching. True Seeing shows the real scene behind the screen. Duration 1 hour/level. Components: V, S.'
WHERE name = 'Abschirmung' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Gewährt einer Kreatur Immunität gegen eine bestimmte Zauberform oder einen bestimmten Zauberer. Die geschützte Kreatur ist vollständig immun gegen die Zauber des gewählten Zauberers oder gegen eine bestimmte Zauberschule (z.B. alle Beschwörungszauber). Alternativ kann die Immunität gegen einen bestimmten Zaubereffekt gerichtet sein (z.B. Furcht, Versteinerung, Bezauberung). Die Immunität kann nicht umgangen werden — auch nicht durch höherstufige Zauber der gleichen Schule. Dauer 1 Stunde/Stufe. Materialkomponenten: V, S, M (ein Diamant im Wert von mind. 500 GM, der beim Wirken verzehrt wird).',
  description_en = 'Grants a creature immunity to a specific spell form or a specific spellcaster. The protected creature is completely immune to the chosen caster''s spells or to a specific school of magic (e.g., all Enchantment spells). Alternatively, the immunity can target a specific spell effect (e.g., fear, petrification, charm). The immunity cannot be bypassed — not even by higher-level spells of the same school. Duration 1 hour/level. Material components: V, S, M (a diamond worth at least 500 gp, consumed in casting).'
WHERE name = 'Sertens Zauberimmunität' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Versenkt eine Kreatur oder einen Gegenstand in den Boden. Das Ziel sinkt bis zu 1,5 m pro Stufe des Zaubernden in die Erde. Die Erde schließt sich über dem Ziel und hält es gefangen. Lebende Kreaturen erhalten einen Rettungswurf gegen Zauber. Eingegrabene Kreaturen haben keine Luft — sie ersticken, wenn sie nicht ausgraben können oder Magie verwenden. Freilegen erfordert Graben (physisch oder magisch). Der Zauber wirkt auf Erde, Sand, Schlamm — nicht auf Stein oder Metall. Permanent bis die Kreatur/der Gegenstand befreit wird. Materialkomponenten: V, S.',
  description_en = 'Sinks a creature or object into the ground. The target sinks up to 1.5 m per caster level into the earth. The earth closes over the target, trapping it. Living creatures receive a saving throw vs. spell. Buried creatures have no air — they suffocate if they cannot dig out or use magic. Unearthing requires digging (physical or magical). The spell works on earth, sand, mud — not on stone or metal. Permanent until the creature/object is freed. Components: V, S.'
WHERE name = 'Versinken' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Zaubernde schreibt ein mächtiges magisches Symbol auf eine Oberfläche. Wenn eine Kreatur das Symbol liest oder berührt, wird der jeweilige Effekt ausgelöst. Mögliche Symbole: Tod (Kreaturen bis 80 TP sterben, kein Rettungswurf), Zwietracht (alle Betroffenen streiten 5W4 Runden), Furcht (Panik wie der Furcht-Zauber), Hoffnungslosigkeit (wie der Emotions-Zauber), Wahnsinn (permanent), Schmerz (−4 auf GES und Trefferwürfe für 2W10 Runden), Schlaf (4W6+Stufe TP an Kreaturen schlafen ein), Betäubung (alle im Bereich 3W4 Runden betäubt). Das Symbol ist permanent bis ausgelöst und kann nur durch Magie Bannen entfernt werden. Materialkomponenten: V, S, M (Quecksilber und Diamantenstaub im Wert von mind. 5.000 GM).',
  description_en = 'The caster inscribes a powerful magical symbol on a surface. When a creature reads or touches the symbol, its effect is triggered. Possible symbols: Death (creatures up to 80 HP die, no save), Discord (all affected argue for 5d4 rounds), Fear (panic as per Fear spell), Hopelessness (as Emotion spell), Insanity (permanent), Pain (−4 to DEX and attack rolls for 2d10 rounds), Sleep (4d6+level HP of creatures fall asleep), Stunning (all in area stunned 3d4 rounds). The symbol is permanent until triggered and can only be removed by Dispel Magic. Material components: V, S, M (mercury and diamond dust worth at least 5,000 gp).'
WHERE name = 'Symbol (Magier)' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Fängt die Lebensessenz (Seele) einer Kreatur in einem speziellen Behälter (einem Edelstein im Wert von mind. 1.000 GM pro TW des Ziels). Das Ziel erhält einen Rettungswurf gegen Zauber (mit −2 Malus). Bei Misserfolg wird die Seele aus dem Körper gerissen und im Edelstein gefangen. Der Körper bleibt leblos zurück. Die gefangene Seele kann nur durch das Zerstören des Edelsteins oder durch einen Wunsch-Zauber befreit werden. Zerstörung des Edelsteins befreit die Seele und ermöglicht Auferstehung. Wenn der Körper in der Zwischenzeit zerstört wurde, ist die Seele verloren. Der Zauber kann auch als Falle vorbereitet werden (an einen Gegenstand gebunden). Materialkomponenten: V, S, M (ein Edelstein des entsprechenden Werts).',
  description_en = 'Traps the life essence (soul) of a creature in a special container (a gem worth at least 1,000 gp per HD of the target). The target receives a saving throw vs. spell (with −2 penalty). On failure, the soul is torn from the body and trapped in the gem. The body remains lifeless. The trapped soul can only be freed by destroying the gem or by a Wish spell. Destroying the gem frees the soul and allows resurrection. If the body was destroyed in the meantime, the soul is lost. The spell can also be prepared as a trap (bound to an object). Material components: V, S, M (a gem of the appropriate value).'
WHERE name = 'Seele Fangen' AND spell_type = 'wizard';

-- ─── WIZARD LEVEL 9 ──────────────────────────────────────────────────────────

UPDATE public.spells SET
  description = 'Projiziert den Astralkörper des Zaubernden (und bis zu 7 Begleiter) auf die Astralebene, von wo aus sie zu anderen Ebenen der Existenz reisen können. Der physische Körper bleibt in einem tranceähnlichen Zustand zurück. Auf der Astralebene bewegt man sich durch reine Gedankenkraft. Eine silberne Nabelschnur verbindet den Astralkörper mit dem physischen Körper — wird sie durchtrennt, stirbt die Kreatur sofort. Auf der Astralebene gelten andere physikalische Gesetze. Die Projektion hält an, bis der Zaubernde sich entscheidet zurückzukehren, oder bis die Nabelschnur durchtrennt wird. Materialkomponenten: V, S, M (ein Jacinth im Wert von mind. 1.000 GM und ein Silberbarren im Wert von 5 GM für jeden Reisenden).',
  description_en = 'Projects the astral body of the caster (and up to 7 companions) onto the Astral Plane, from where they can travel to other planes of existence. The physical body remains in a trance-like state. On the Astral Plane, movement is by pure thought. A silver umbilical cord connects the astral body to the physical body — if severed, the creature dies instantly. Different physical laws apply on the Astral Plane. The projection lasts until the caster decides to return or until the cord is severed. Material components: V, S, M (a jacinth worth at least 1,000 gp and a silver bar worth 5 gp for each traveler).'
WHERE name = 'Astralzauber (Magier)' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt eine riesige, zerquetschende Hand aus magischer Kraft (RK −3, TP gleich dem vollen TP-Wert des Zaubernden), die einen Gegner packt und zerquetscht. Die Hand greift mit einer STR von 19 an, verursacht pro Runde 2W10 Schaden durch Zerquetschen (kein Trefferwurf nötig, sobald sie gepackt hat). Das Opfer kann versuchen, sich mit einem offenen STR-Wurf zu befreien (gegen STR 19). Die Hand bewegt sich mit 3 m/Runde und kann auch als Blockade verwendet werden (wie Bigbys Blockierende Hand). Magie Bannen, Desintegration oder Kraftwand können die Hand aufhalten. Dauer 1 Runde/Stufe. Materialkomponente: V, S, M (ein Handschuh und ein Tropfen Sekundenkleber).',
  description_en = 'Creates a huge, crushing hand of magical force (AC −3, HP equal to the caster''s full HP) that grabs and crushes an opponent. The hand grasps with STR 19, dealing 2d10 crushing damage per round (no attack roll needed once it has grabbed). The victim can attempt to break free with an open STR check (vs. STR 19). The hand moves at 3 m/round and can also be used as a barrier (like Bigby''s Interposing Hand). Dispel Magic, Disintegrate, or Wall of Force can stop the hand. Duration 1 round/level. Material component: V, S, M (a glove and a drop of fast-setting adhesive).'
WHERE name = 'Bigbys Zerquetschende Hand' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verwandelt Metall oder Mineral in eine extrem brüchige, kristalline Substanz. Rettungswurf für den Gegenstand negiert (basierend auf Material und Magie). Bei Misserfolg wird das Material so brüchig, dass es bei der nächsten Berührung oder bei Erschütterung zersplittert. Der Zauber betrifft bis zu 3 m³ Material pro Stufe des Zaubernden. Magische Gegenstände erhalten einen Rettungswurf mit Bonus (+2 bis +5 je nach Mächtigkeit). Besonders verheerend gegen metallene Rüstungen (die beim nächsten Treffer zerbrechen) und Waffen. Der Effekt ist permanent. Materialkomponente: V, S.',
  description_en = 'Transforms metal or mineral into an extremely brittle, crystalline substance. Saving throw for the object negates (based on material and magic). On failure, the material becomes so brittle it shatters at the next touch or vibration. The spell affects up to 3 m³ of material per caster level. Magical items receive a saving throw with bonus (+2 to +5 depending on power). Especially devastating against metal armor (which shatters on the next hit) and weapons. The effect is permanent. Components: V, S.'
WHERE name = 'Kristallbrüchigkeit' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ein schwarzer Strahl negativer Energie trifft eine Kreatur und entzieht ihr 2 Erfahrungsstufen (TW). Alle Vorteile der verlorenen Stufen gehen verloren: TP, THAC0-Verbesserung, Zauberslots, Rettungswurf-Boni usw. Das Ziel erhält keinen Rettungswurf. Verlorene Stufen können nur durch den Zauber Wiederherstellung (Priester 7. Stufe) oder Wunsch zurückgewonnen werden. Wenn eine Kreatur auf 0 TW oder darunter fällt, stirbt sie und wird als untote Kreatur (Geist) wiedergeboren, die dem Zaubernden feindlich gesinnt ist. Der Zauber wirkt nicht gegen Untote oder Konstrukte. Materialkomponente: V, S.',
  description_en = 'A black ray of negative energy strikes a creature and drains 2 experience levels (HD). All benefits of the lost levels are lost: HP, THAC0 improvement, spell slots, saving throw bonuses, etc. The target receives no saving throw. Lost levels can only be recovered by the Restoration spell (Priest 7th level) or Wish. If a creature drops to 0 HD or below, it dies and is reborn as an undead creature (wraith) hostile to the caster. The spell does not work on undead or constructs. Components: V, S.'
WHERE name = 'Energieentzug' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Zaubernde erhält eine übersinnliche Warnung vor drohender Gefahr. Für die Dauer des Zaubers kann der Zaubernde nicht überrascht werden, erhält +2 auf Trefferwürfe und Rettungswürfe, und seine RK verbessert sich um 2. Zusätzlich erhält er 1 Runde vor jedem gefährlichen Ereignis eine Warnung (er „weiß" einfach, dass Gefahr droht — Richtung und Art werden vage angedeutet). Der Zauber funktioniert auch im Schlaf und weckt den Zaubernden bei Gefahr. Dauer 2W4 Runden + 1 Runde/Stufe. Materialkomponenten: V, S, M (ein Stück einer Muschelschale und ein Stück Bergkristall).',
  description_en = 'The caster gains a supernatural warning of impending danger. For the spell''s duration, the caster cannot be surprised, gains +2 to attack rolls and saving throws, and his AC improves by 2. Additionally, he receives a warning 1 round before any dangerous event (he simply "knows" danger approaches — direction and type are vaguely indicated). The spell also works while sleeping and wakes the caster in case of danger. Duration 2d4 rounds + 1 round/level. Material components: V, S, M (a piece of seashell and a piece of rock crystal).'
WHERE name = 'Voraussicht' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Öffnet ein interdimensionales Portal zu einer anderen Ebene der Existenz und ruft eine mächtige Kreatur herbei. Der Zaubernde benennt eine spezifische Kreatur oder einen Typ (z.B. „ein Solarer" oder „ein Balor"). Die gerufene Kreatur ist NICHT verpflichtet, dem Zaubernden zu dienen — sie handelt nach eigenem Ermessen. Mächtige Wesen (Götter, Erzengel etc.) können verärgert sein, wenn sie ohne guten Grund gerufen werden. Der Zaubernde kann versuchen, mit der Kreatur zu verhandeln (Charisma-basiert). Das Tor bleibt offen, bis die Kreatur hindurchgetreten ist oder 1 Runde verstrichen ist. Materialkomponente: V, S.',
  description_en = 'Opens an interdimensional portal to another plane of existence and summons a powerful creature. The caster names a specific creature or type (e.g., "a Solar" or "a Balor"). The summoned creature is NOT obligated to serve the caster — it acts at its own discretion. Powerful beings (gods, archangels, etc.) may be angered if summoned without good reason. The caster can attempt to negotiate with the creature (Charisma-based). The gate remains open until the creature steps through or 1 round passes. Components: V, S.'
WHERE name = 'Tor (Magier)' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verbannt eine Kreatur in einen Zustand der suspendierten Animation tief unter der Erdoberfläche. Das Ziel wird in eine winzige Kugel eingeschlossen und 30 m + 3 m/Stufe unter die Erde versenkt. Die Kreatur erhält keinen Rettungswurf (bei Berührung) — bei Fernwirkung einen Rettungswurf gegen Zauber. Die eingesperrte Kreatur altert nicht, braucht keine Nahrung und ist gegen alle äußeren Einflüsse immun. Sie kann nur durch den Umkehrzauber (Freiheit) befreit werden, der den Namen und den genauen Aufenthaltsort der Kreatur erfordert. Permanent. Materialkomponente: V, S.',
  description_en = 'Banishes a creature into suspended animation deep beneath the earth''s surface. The target is enclosed in a tiny sphere and sunk 30 m + 3 m/level underground. The creature receives no saving throw (on touch) — at range, a saving throw vs. spell. The imprisoned creature does not age, needs no food, and is immune to all external influences. It can only be freed by the reverse spell (Freedom), which requires the creature''s name and exact location. Permanent. Components: V, S.'
WHERE name = 'Gefangenschaft' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt entweder 4 große Feuerbälle oder 8 kleine Meteore. Große Meteore: 4 Feuerkugeln, die jeweils ein separates Ziel in Reichweite treffen (kein Trefferwurf nötig). Jeder Meteor verursacht 10W4 Schaden im Aufschlagpunkt und 2W4 im 1,5-m-Splitterbereich (Rettungswurf gegen Zauber halbiert für Splitter). Kleine Meteore: 8 kleinere Kugeln, jede verursacht 5W4 Schaden plus 1W4 Splitterschaden im 1,5-m-Radius. Die Meteore können auf verschiedene Ziele verteilt werden. Brennbare Materialien werden entzündet. Materialkomponente: V, S.',
  description_en = 'Creates either 4 large fireballs or 8 small meteors. Large Meteors: 4 fire spheres, each hitting a separate target in range (no attack roll needed). Each meteor deals 10d4 damage at impact and 2d4 in a 1.5 m splash radius (saving throw vs. spell halves splash). Small Meteors: 8 smaller spheres, each dealing 5d4 damage plus 1d4 splash in 1.5 m radius. Meteors can be distributed among different targets. Combustible materials are ignited. Components: V, S.'
WHERE name = 'Meteorschwarm' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Beschwört 1W2 Monster der 7. Stufe (RK −2, 7 TW, 3W6 Schaden), die sofort dem Zaubernden dienen. Die genaue Art wird vom SL bestimmt. Monster erscheinen in 1W4 Runden und kämpfen bis zum Tod oder Zauberende. Dauer 8 Runden + 1 Runde/Stufe. Materialkomponenten: V, S, M (ein kleiner Beutel und ein Kerzenstummel).',
  description_en = 'Summons 1d2 7th-level monsters (AC −2, 7 HD, 3d6 damage) that immediately serve the caster. The exact type is determined by the DM. Monsters appear in 1d4 rounds and fight to death or spell''s end. Duration 8 rounds + 1 round/level. Material components: V, S, M (a small bag and a candle stub).'
WHERE name = 'Monsterbeschwörung VII' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der mächtigste antimagische Zauber. Der Zaubernde löst ALLE magischen Effekte und magischen Gegenstände in einem 9-m-Radius um sich herum auf (Rettungswurf für jeden Gegenstand, 1% pro Stufe des Zaubernden). Magische Gegenstände, die ihren Rettungswurf bestehen, funktionieren danach normal weiter. Gegenstände, die versagen, werden permanent zu gewöhnlichen Gegenständen (alle magischen Eigenschaften gehen unwiederbringlich verloren). Artefakte und Relikte sind immun. Der Zauber betrifft ALLE Gegenstände im Bereich — auch die des Zaubernden und seiner Verbündeten! Antimagische Hüllen blockieren die Disjunktion. Eine 1%-Chance besteht, dass der Zaubernde seine eigene Fähigkeit zu zaubern permanent verliert. Materialkomponente: V, S.',
  description_en = 'The most powerful anti-magic spell. The caster dissolves ALL magical effects and magical items in a 9 m radius around himself (saving throw for each item, 1% per caster level). Magical items that save continue to function normally. Items that fail permanently become ordinary items (all magical properties are irrecoverably lost). Artifacts and relics are immune. The spell affects ALL items in the area — including the caster''s and allies''! Anti-Magic Shells block the disjunction. There is a 1% chance the caster permanently loses his own ability to cast spells. Components: V, S.'
WHERE name = 'Mordenkainens Disjunktion' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Zaubernde spricht ein einzelnes Wort der Macht, das eine Kreatur mit 60 oder weniger aktuellen TP sofort tötet (kein Rettungswurf). Kreaturen mit 61-90 TP werden für 1W4×10 Runden gelähmt. Kreaturen mit mehr als 90 TP werden für 1W4 Runden benommen (−2 auf Trefferwürfe und RK). Der Zauber wirkt auf jede lebende Kreatur — Untote, Konstrukte und magisch geschützte Kreaturen sind immun. Der Tod ist sofort und kann nur durch Auferstehung, Wunsch oder ähnliche Magie rückgängig gemacht werden. Komponente: V.',
  description_en = 'The caster speaks a single word of power that instantly kills a creature with 60 or fewer current HP (no saving throw). Creatures with 61-90 HP are paralyzed for 1d4×10 rounds. Creatures with more than 90 HP are dazed for 1d4 rounds (−2 to attack rolls and AC). The spell works on any living creature — undead, constructs, and magically protected creatures are immune. Death is instant and can only be reversed by Resurrection, Wish, or similar magic. Component: V.'
WHERE name = 'Machtwort: Tod' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt eine undurchdringliche Kugel aus prismatischem Licht um den Zaubernden (3 m Radius). Wie die Prismatische Wand hat die Kugel sieben farbige Schichten, jede mit eigenem Effekt und eigenem Gegenzauber. Jede Kreatur, die versucht, die Kugel zu durchdringen, muss alle sieben Schichten passieren und alle Effekte erleiden (Feuer, Säure, Blitz, Gift, Versteinerung, Wahnsinn, Ebenentransport). Die Kugel kann nicht physisch bewegt werden und blockiert alle Formen der Teleportation und dimensionalen Reise. Im Innern ist der Zaubernde vor allen äußeren Angriffen geschützt. Dauer 1 Stunde/Stufe. Materialkomponente: V.',
  description_en = 'Creates an impenetrable sphere of prismatic light around the caster (3 m radius). Like the Prismatic Wall, the sphere has seven colored layers, each with its own effect and counterspell. Any creature attempting to penetrate the sphere must pass through all seven layers and suffer all effects (fire, acid, lightning, poison, petrification, insanity, plane shift). The sphere cannot be physically moved and blocks all forms of teleportation and dimensional travel. Inside, the caster is protected from all external attacks. Duration 1 hour/level. Component: V.'
WHERE name = 'Prismatische Kugel' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der mächtigste Verwandlungszauber: Der Zaubernde verwandelt sich nach Belieben in jede Kreatur — einschließlich magischer Kreaturen, Drachen, Dämonen usw. Er erhält ALLE physischen und magischen Fähigkeiten der neuen Form (Atemwaffen, magische Resistenz, Flug, Klauen, Regeneration etc.), behält aber seinen eigenen Intellekt, seine Persönlichkeit und seine Zauberfähigkeit (sofern die neue Form Sprache ermöglicht). Er kann beliebig oft die Form wechseln innerhalb der Dauer (jeder Wechsel erfordert 1 Runde). Jeder Formwechsel heilt 10%-100% des erlittenen Schadens. Der Zaubernde kann keine einzigartigen Individuen kopieren (nur Typen). Dauer Stufe des Zaubernden × 1 Stunde. Materialkomponente: V, S, M (ein Jade-Zirkus-Ring im Wert von mind. 5.000 GM).',
  description_en = 'The most powerful polymorph spell: the caster transforms at will into any creature — including magical creatures, dragons, demons, etc. He gains ALL physical and magical abilities of the new form (breath weapons, magic resistance, flight, claws, regeneration, etc.) but retains his own intellect, personality, and spellcasting ability (if the new form allows speech). He can change form any number of times within the duration (each change requires 1 round). Each form change heals 10%-100% of damage taken. The caster cannot copy unique individuals (only types). Duration caster''s level × 1 hour. Material component: V, S, M (a jade circlet worth at least 5,000 gp).'
WHERE name = 'Gestaltwandel' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Zaubernde erzeugt eine Miniatur-Abbildung seiner selbst auf einem kleinen Gegenstand (Elfenbein-Statuette, Edelstein etc.). Jeder, der diesen Gegenstand besitzt und ein Kommandowort spricht, wird sofort zum Standort des Zaubernden teleportiert — oder der Zaubernde kann den Gegenstand so verzaubern, dass er selbst zum Standort des Gegenstands teleportiert wird. In beiden Fällen ist die Teleportation fehlerfrei (wie Teleportieren ohne Fehler). Der Gegenstand kann nur einmal verwendet werden und wird danach zu einem normalen Gegenstand. Der Zauber kann als Notfall-Rettungsmechanismus oder als Rückkehr-Ticket verwendet werden. Materialkomponenten: V, S, M (ein fein gearbeiteter Gegenstand im Wert von mind. 5.000 GM).',
  description_en = 'The caster creates a miniature depiction of himself on a small object (ivory statuette, gem, etc.). Anyone possessing this object and speaking a command word is instantly teleported to the caster''s location — or the caster can enchant the object so he himself is teleported to the object''s location. In both cases, teleportation is error-free (as Teleport Without Error). The object can only be used once and becomes a normal object afterward. The spell can be used as an emergency rescue mechanism or return ticket. Material components: V, S, M (a finely crafted object worth at least 5,000 gp).'
WHERE name = 'Beistand (Magier)' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Zaubernde hält die Zeit in seiner Umgebung an. Für die Dauer des Zaubers (1W4+1 Runden, scheinbar) bewegt sich nur der Zaubernde — alle anderen Kreaturen, Gegenstände und Effekte sind eingefroren. Der Zaubernde kann sich frei bewegen, Zauber wirken, Gegenstände aufheben, Positionen wechseln etc. Er kann jedoch keine eingefrorenen Kreaturen direkt angreifen oder verletzen (sie sind durch den Zeitstillstand geschützt). Zauber, die auf eingefrorene Kreaturen gewirkt werden, treten erst in Kraft, wenn die Zeit wieder läuft. Antimagische Hüllen sind immun gegen den Zeitstillstand. Materialkomponente: V.',
  description_en = 'The caster stops time in his vicinity. For the spell''s duration (1d4+1 apparent rounds), only the caster moves — all other creatures, objects, and effects are frozen. The caster can freely move, cast spells, pick up objects, change positions, etc. However, he cannot directly attack or harm frozen creatures (they are protected by the time stop). Spells cast at frozen creatures take effect only when time resumes. Anti-Magic Shells are immune to Time Stop. Component: V.'
WHERE name = 'Zeitstillstand' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Versetzt eine einzelne Kreatur in einen Zustand suspendierter Animation. Die Kreatur erhält einen Rettungswurf gegen Zauber. Bei Misserfolg wird die Kreatur in einem zeitlosen Zustand eingefroren — sie altert nicht, braucht keine Nahrung und ist gegen alle äußeren Einflüsse immun (aber auch unfähig zu handeln, wahrzunehmen oder zu denken). Der Zustand hält permanent an und kann nur durch den Umkehrzauber (Zeitstasis Aufheben) oder einen Wunsch-Zauber beendet werden. Magie Bannen hat KEINE Wirkung. Die Kreatur behält ihre Position und Haltung bei — sie kann nicht bewegt werden, ohne den Zauber zu brechen. Materialkomponente: V, S.',
  description_en = 'Puts a single creature into suspended animation. The creature receives a saving throw vs. spell. On failure, the creature is frozen in a timeless state — it does not age, needs no food, and is immune to all external influences (but also unable to act, perceive, or think). The state lasts permanently and can only be ended by the reverse spell (Temporal Reinstatement) or a Wish spell. Dispel Magic has NO effect. The creature maintains its position and posture — it cannot be moved without breaking the spell. Components: V, S.'
WHERE name = 'Zeitstasis' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt illusorische Duplikate von Kreaturen aus den tiefsten Ängsten der Ziele — ähnlich dem Phantastischen Killer (4. Stufe), aber gegen mehrere Ziele gleichzeitig. Jede Kreatur im Wirkungsbereich (6 m Radius) sieht eine personalisierte Schreckensgestalt, die nur sie sehen kann. Jedes Ziel erhält zuerst einen Rettungswurf gegen Zauber — bei Erfolg wird die Illusion durchschaut und ist harmlos. Bei Misserfolg greift die Schreckensgestalt an: Das Ziel muss einen Rettungswurf gegen Tod bestehen oder stirbt vor Angst. Bei Erfolg erleidet es trotzdem 3W6 Schaden. Die Illusionen können nicht angegriffen werden. Dauer Konzentration. Materialkomponente: V, S.',
  description_en = 'Creates illusory duplicates of creatures from the targets'' deepest fears — similar to the Phantasmal Killer (4th level) but against multiple targets simultaneously. Each creature in the area (6 m radius) sees a personalized terror figure visible only to them. Each target first receives a saving throw vs. spell — on success, the illusion is seen through and is harmless. On failure, the terror figure attacks: the target must save vs. death or die of fright. On success, it still takes 3d6 damage. The illusions cannot be attacked. Duration concentration. Components: V, S.'
WHERE name = 'Bizarr' AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der mächtigste Zauber überhaupt. Ein Wunsch kann nahezu alles bewirken: Tote vollständig erwecken (ohne Stufenverlust), permanente Attributserhöhungen gewähren (+1 auf ein Attribut), Zauberwirkungen jeder Art duplizieren, vergangene Ereignisse rückgängig machen, Kreaturen zwischen Ebenen transportieren, magische Gegenstände erschaffen, und vieles mehr. Der genaue Effekt liegt im Ermessen des SL — schlecht formulierte Wünsche werden oft wörtlich interpretiert mit unerwarteten (negativen) Konsequenzen. Jeder Wunsch altert den Zaubernden um 5 Jahre. Nach dem Wirken ist der Zaubernde 2W4 Tage lang geschwächt (−3 auf STR, kann nur mit halber Bewegungsrate gehen). Materialkomponente: V.',
  description_en = 'The most powerful spell of all. A Wish can accomplish virtually anything: fully raise the dead (without level loss), grant permanent attribute increases (+1 to one attribute), duplicate spell effects of any type, undo past events, transport creatures between planes, create magical items, and much more. The exact effect is at the DM''s discretion — poorly worded wishes are often interpreted literally with unexpected (negative) consequences. Each Wish ages the caster by 5 years. After casting, the caster is weakened for 2d4 days (−3 to STR, can only walk at half movement rate). Component: V.'
WHERE name = 'Wunsch' AND spell_type = 'wizard';
