-- ═══════════════════════════════════════════════════════════════════════════════
-- PHB Priest Spells Level 5 (Batch 1: 15 Spells)
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  description = 'Ermöglicht dem Priester (und nur ihm), auf Luft zu gehen wie auf festem Boden. Er kann aufsteigen und absteigen in einem Winkel von bis zu 45 Grad. Die Bewegungsrate beträgt die Hälfte der normalen Landgeschwindigkeit. Der Priester kann in der Luft stehen bleiben. Wind beeinflusst ihn normal — starke Böen können ihn vom Kurs abbringen. Der Zauber schützt nicht vor Kälte oder Sauerstoffmangel in großen Höhen. Wenn der Zauber endet während der Priester in der Luft ist, sinkt er langsam (wie Federfall) für 1W6 Runden ab, danach normaler Fall. Dauer 1 Stunde/Stufe. Materialkomponenten: V, S, M (das heilige Symbol des Priesters).',
  description_en = 'Allows the priest (and only him) to walk on air as on solid ground. He can ascend and descend at angles up to 45 degrees. Movement rate is half normal land speed. The priest can stand still in midair. Wind affects him normally — strong gusts can blow him off course. The spell does not protect against cold or oxygen deprivation at high altitudes. If the spell ends while airborne, he sinks slowly (as Feather Fall) for 1d6 rounds, then normal fall. Duration 1 hour/level. Material components: V, S, M (the priest''s holy symbol).'
WHERE name = 'Luftwandeln' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Verdoppelt die Größe (und damit Stärke, Trefferwürfel und Schaden) von 1-8 normalen Tieren im Wirkungsbereich. Die vergrößerten Tiere haben doppelte TW, doppelten Schaden und proportional erhöhte Stärke. Ihre RK bleibt gleich. Magische Tiere sind nicht betroffen. Die Tiere werden nicht aggressiver oder intelligenter — sie sind einfach größer. Umkehrbar: Tierschrumpfung — halbiert die Größe von Tieren. Dauer 2 Runden/Stufe. Materialkomponente: V, S.',
  description_en = 'Doubles the size (and thus strength, hit dice, and damage) of 1-8 normal animals in the area. Enlarged animals have double HD, double damage, and proportionally increased strength. Their AC remains the same. Magical animals are not affected. The animals do not become more aggressive or intelligent — they are simply larger. Reversible: Shrink Animal — halves animal size. Duration 2 rounds/level. Components: V, S.'
WHERE name = 'Tierwachstum' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Wie Tierbeschwörung I, aber beschwört bis zu 12 TW an normalen Tieren. Die Tiere erscheinen aus der Umgebung, gehorchen einfachen Befehlen und kämpfen bis zum Tod. Mögliche Tiere hängen vom Terrain ab. Dauer 2 Runden/Stufe. Materialkomponente: V, S.',
  description_en = 'Like Animal Summoning I, but summons up to 12 HD of normal animals. The animals emerge from the surroundings, obey simple commands, and fight to death. Available animals depend on terrain. Duration 2 rounds/level. Components: V, S.'
WHERE name = 'Tierbeschwörung II' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Entfernt die Last einer schweren Sünde oder Verfehlung von einer Kreatur und stellt ihre Verbindung zu ihrer Gottheit wieder her. Notwendig für: Paladine, die ihre Ehre verloren haben; Priester, die gegen ihren Glauben verstoßen haben; Kreaturen, die unter einem göttlichen Fluch stehen. Ohne Buße kann ein gefallener Priester keine Zauber mehr wirken. Die Buße muss aufrichtig sein — der Priester kann keine Buße für eine Kreatur wirken, die nicht wirklich bereut. Der Zauber kann auch verwendet werden, um eine unfreiwillige Gesinnungsänderung rückgängig zu machen. Materialkomponenten: V, S, M (das heilige Symbol, Gebetsperlen und ein Opfer, das der Gottheit angemessen ist).',
  description_en = 'Removes the burden of a serious sin or transgression from a creature and restores its connection to its deity. Required for: paladins who have lost their honor; priests who have violated their faith; creatures under a divine curse. Without atonement, a fallen priest cannot cast spells. The atonement must be sincere — the priest cannot atone for a creature that does not truly repent. The spell can also reverse an involuntary alignment change. Material components: V, S, M (the holy symbol, prayer beads, and a sacrifice appropriate to the deity).'
WHERE name = 'Buße' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Der Priester kontaktiert seine Gottheit (oder einen göttlichen Boten) direkt und kann Fragen stellen. Er kann 1 Frage pro Stufe stellen. Die Gottheit antwortet mit Ja, Nein, oder einem kurzen Satz. Die Antworten sind immer korrekt — aber sie können kryptisch oder unvollständig sein (Götter enthüllen nicht gern die Zukunft). Die Kommunion ist geistig anstrengend: Nach dem Zauber muss der Priester 24 Stunden ruhen (kann keine Zauber wirken). Der Zauber kann nur einmal pro Woche gewirkt werden. Materialkomponenten: V, S, M (das heilige Symbol, Weihrauch und Weihwasser).',
  description_en = 'The priest contacts his deity (or a divine messenger) directly and can ask questions. He can ask 1 question per level. The deity answers with Yes, No, or a short phrase. Answers are always correct — but may be cryptic or incomplete (gods do not readily reveal the future). The communion is mentally exhausting: after the spell, the priest must rest 24 hours (cannot cast spells). The spell can only be cast once per week. Material components: V, S, M (the holy symbol, incense, and holy water).'
WHERE name = 'Kommunion' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Der Priester wird eins mit der umgebenden Natur und erhält Informationen über das Terrain in einem Radius von 1,6 km pro Stufe. Er erfährt: die allgemeine Beschaffenheit des Geländes (Wälder, Hügel, Sümpfe), das Vorhandensein von Wasser und dessen Reinheit, die Anwesenheit von Gebäuden oder bewohnten Gebieten, die dominanten Pflanzen- und Tierarten, und ob unnatürliche Einflüsse (Untote, böse Magie) vorhanden sind. Der Zauber funktioniert nur im Freien und in natürlicher Umgebung (nicht in Städten oder Dungeons). Dauer sofort (die Information wird auf einmal empfangen). Materialkomponente: V, S.',
  description_en = 'The priest becomes one with the surrounding nature and receives information about terrain in a radius of 1.6 km per level. He learns: general terrain features (forests, hills, swamps), presence of water and its purity, presence of buildings or inhabited areas, dominant plant and animal species, and whether unnatural influences (undead, evil magic) are present. The spell only works outdoors in natural environments (not in cities or dungeons). Duration instant (information is received all at once). Components: V, S.'
WHERE name = 'Kommunion mit der Natur' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Ermöglicht es dem Priester, die Windstärke in einem Bereich von 36 m Radius/Stufe zu verändern. Er kann die Windstärke um 1 Stufe pro 3 Stufen des Priesters erhöhen oder senken (auf der Beaufort-Skala). Windstille → leichte Brise → mäßiger Wind → starker Wind → Sturm → Orkan. Im Freien sind massive Effekte möglich: Orkane können Gebäude beschädigen, Kreaturen umwerfen (STR-Wurf), und Fernkampf unmöglich machen. In geschlossenen Räumen hat der Zauber eingeschränkte Wirkung. Dauer 1 Stunde/Stufe. Materialkomponente: V, S.',
  description_en = 'Allows the priest to change wind strength in a 36 m radius/level area. He can raise or lower wind strength by 1 level per 3 priest levels (on the Beaufort scale). Calm → light breeze → moderate wind → strong wind → storm → hurricane. Outdoors, massive effects are possible: hurricanes can damage buildings, knock creatures over (STR check), and make ranged combat impossible. In enclosed spaces the spell has limited effect. Duration 1 hour/level. Components: V, S.'
WHERE name = 'Winde Kontrollieren' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Heilt 3W8+3 Trefferpunkte bei einer berührten Kreatur. Kann nicht über das Maximum heilen. Der stärkste Standard-Heilzauber unterhalb von Heilung (6. Stufe). Umkehrbar: Kritische Wunden Verursachen — verursacht 3W8+3 Schaden bei Berührung (Rettungswurf negiert). Materialkomponente: V, S.',
  description_en = 'Heals 3d8+3 hit points on a touched creature. Cannot heal above maximum. The strongest standard healing spell below Heal (6th level). Reversible: Cause Critical Wounds — deals 3d8+3 damage on touch (saving throw negates). Components: V, S.'
WHERE name = 'Kritische Wunden Heilen' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Der Priester kanalisiert göttliche Macht, um böse und außerplanare Kreaturen zu vertreiben. Jede böse Kreatur im 9-m-Radius muss einen Rettungswurf gegen Zauber bestehen oder fliehen (wie unter dem Effekt des Furcht-Zaubers). Außerplanare böse Kreaturen (Dämonen, Teufel etc.) werden bei missglücktem Rettungswurf auf ihre Heimatebene zurückgeschickt. Zusätzlich hebt der Zauber Bezauberungseffekte auf, die von bösen Kreaturen verursacht wurden (Person Bezaubern etc.). Dauer 1 Runde/Stufe. Materialkomponenten: V, S, M (das heilige Symbol und Weihwasser).',
  description_en = 'The priest channels divine power to drive away evil and extraplanar creatures. Every evil creature in a 9 m radius must save vs. spell or flee (as if under Fear spell). Extraplanar evil creatures (demons, devils, etc.) are sent back to their home plane on a failed save. Additionally, the spell removes enchantment effects caused by evil creatures (Charm Person, etc.). Duration 1 round/level. Material components: V, S, M (the holy symbol and holy water).'
WHERE name = 'Böses Bannen' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Eine Säule göttlichen Feuers schlägt vom Himmel auf einen Punkt am Boden ein (Reichweite 18 m). Die Flamme ist ein 1,5 m breiter Strahl, der in einem 1,5-m-Radius am Boden explodiert. Verursacht 6W8 Schaden (halb Feuer, halb göttliche Energie). Rettungswurf gegen Zauber halbiert den Schaden. Der göttliche Anteil des Schadens wirkt auch gegen feuerresistente Kreaturen. Untote erleiden vollen Schaden (kein Bonus, aber keine Resistenz). Dauer sofort. Materialkomponenten: V, S, M (das heilige Symbol, ein Stück Schwefel und eine Prise Phosphor).',
  description_en = 'A pillar of divine fire strikes from the sky onto a point on the ground (range 18 m). The flame is a 1.5 m wide beam that explodes in a 1.5 m radius at ground level. Deals 6d8 damage (half fire, half divine energy). Saving throw vs. spell halves the damage. The divine portion of the damage also affects fire-resistant creatures. Undead take full damage (no bonus but no resistance). Duration instant. Material components: V, S, M (the holy symbol, a piece of sulphur, and a pinch of phosphorus).'
WHERE name = 'Flammenschlag' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Beschwört einen riesigen Schwarm stechender und beißender Insekten, der einen Bereich von 54 m × 54 m bedeckt. Jede Kreatur im Schwarm erleidet 1 Schadenspunkt pro Runde. Kreaturen mit weniger als 2 TW fliehen in Panik. Kreaturen mit 2+ TW kämpfen mit −2 auf Trefferwürfe. Der Schwarm bewegt sich mit 6 m/Runde in Windrichtung und kann vom Priester alle 1W4 Runden umgelenkt werden. Rauch vertreibt den Schwarm nicht (zu groß). Nur magischer Wind oder Feuer in großem Maßstab kann ihn zerstreuen. Dauer 2 Runden/Stufe. Materialkomponenten: V, S, M (das heilige Symbol, wenige Tropfen Honig und ein toter Käfer).',
  description_en = 'Summons a massive swarm of stinging and biting insects covering a 54 m × 54 m area. Every creature in the swarm takes 1 damage per round. Creatures with less than 2 HD flee in panic. Creatures with 2+ HD fight at −2 to attack rolls. The swarm moves at 6 m/round in wind direction and can be redirected by the priest every 1d4 rounds. Smoke does not disperse the swarm (too large). Only magical wind or large-scale fire can scatter it. Duration 2 rounds/level. Material components: V, S, M (the holy symbol, a few drops of honey, and a dead beetle).'
WHERE name = 'Insektenplage' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Verwandelt ein ruhiges Gewässer (heiliges Becken, Brunnen etc.) in ein magisches Beobachtungsmedium. Der Priester kann durch das Wasser entfernte Orte und Kreaturen beobachten, ähnlich wie Hellsehen. Die Chancen sind höher als bei Spiegelbecken: 15% + 5%/Stufe für ein bestimmtes Subjekt. Die Beobachtung ist rein visuell — kein Ton. Durch Nichterkennung oder Blei blockiert. Dauer 1 Runde/Stufe. Materialkomponenten: V, S, M (das heilige Symbol, Weihrauch und ein Stück Mondstein).',
  description_en = 'Transforms a calm body of water (holy font, well, etc.) into a magical viewing medium. The priest can observe distant locations and creatures through the water, similar to Clairvoyance. Chances are higher than Reflecting Pool: 15% + 5%/level for a specific subject. Observation is purely visual — no sound. Blocked by Non-Detection or lead. Duration 1 round/level. Material components: V, S, M (the holy symbol, incense, and a piece of moonstone).'
WHERE name = 'Magischer Quell' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Erzeugt einen Strahl konzentrierten Mondlichts von 1,5 m Durchmesser, der vom Himmel herabscheint. Der Strahl ist so hell wie Vollmondlicht und beleuchtet einen Bereich am Boden. Gegen Untote und Lykanthropen verursacht der Strahl keine Schäden, zwingt sie aber, den beleuchteten Bereich zu meiden (Rettungswurf gegen Zauber oder Flucht). Lykanthropen im Strahl werden in ihre Tierform gezwungen. Der Priester kann den Strahl pro Runde um 18 m bewegen. Der Zauber funktioniert nur bei Nacht oder unter freiem Himmel. Dauer 1 Runde/Stufe. Materialkomponenten: V, S, M (mehrere Samenkörnchen und ein Stück Mondstein).',
  description_en = 'Creates a beam of concentrated moonlight 1.5 m in diameter shining down from the sky. The beam is as bright as full moonlight and illuminates an area on the ground. Against undead and lycanthropes, the beam deals no damage but forces them to avoid the illuminated area (save vs. spell or flee). Lycanthropes in the beam are forced into animal form. The priest can move the beam 18 m per round. The spell only works at night or under open sky. Duration 1 round/level. Material components: V, S, M (several seeds and a piece of moonstone).'
WHERE name = 'Mondstrahl' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Ermöglicht dem Priester, sich durch einen Baum zu betreten und aus einem anderen Baum derselben Art in Reichweite wieder herauszutreten — eine Art pflanzliche Teleportation. Die Reichweite variiert je nach Baumart: Eiche bis 540 m, Buche bis 360 m, Ulme bis 270 m, andere Laubbäume bis 180 m, Nadelbäume bis 90 m. Der Priester kann nur Bäume derselben Art als Ziel verwenden, die er kennt oder sehen kann. Der Transport ist sofort. Der Priester kann pro Wirken 1 Passage + 1 pro 3 Stufen über der 9. durchführen. Dauer 1 Runde/Stufe. Materialkomponente: V, S, M (ein Stück Rinde des Zielbaums).',
  description_en = 'Allows the priest to step into a tree and emerge from another tree of the same type within range — a form of plant teleportation. Range varies by tree type: oak up to 540 m, beech up to 360 m, elm up to 270 m, other deciduous up to 180 m, coniferous up to 90 m. The priest can only use trees of the same type that he knows or can see as destinations. Transport is instant. The priest can make 1 passage + 1 per 3 levels above 9th per casting. Duration 1 round/level. Material component: V, S, M (a piece of bark from the destination tree type).'
WHERE name = 'Pflanzenpassage' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Transportiert den Priester und bis zu 7 Begleiter auf eine andere Ebene der Existenz. Das genaue Ziel auf der Zielebene ist ungenau — der Priester landet 8-800 km vom gewünschten Punkt entfernt. Ein spezielles Stimmgabel-artiges Gerät (aus einem bestimmten Material für jede Ebene) ist nötig, um die Zielebene zu bestimmen. Unfreiwillige Ziele erhalten einen Rettungswurf gegen Zauber. Die Rückkehr erfordert ein erneutes Wirken. Der Transport ist sofort. Materialkomponenten: V, S, M (ein Stimmgabel-artiges Instrument, das auf die Schwingung der Zielebene abgestimmt ist).',
  description_en = 'Transports the priest and up to 7 companions to another plane of existence. The exact destination on the target plane is imprecise — the priest lands 8-800 km from the desired point. A special tuning fork-like device (made of a specific material for each plane) is needed to determine the target plane. Unwilling targets receive a saving throw vs. spell. Return requires another casting. Transport is instant. Material components: V, S, M (a tuning fork-like instrument attuned to the vibration of the target plane).'
WHERE name = 'Ebenenreise' AND spell_type = 'priest';
