-- ═══════════════════════════════════════════════════════════════════════════════
-- PHB Priest Spells Level 6 (Batch 2: 7 Spells)
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  description = 'Ermöglicht dem Priester, mit jeder Kreatur zu kommunizieren — unabhängig von Sprache, Intelligenz oder Art. Der Priester kann mit Monstern, Tieren, Pflanzen, Elementaren, Untoten und sogar unintelligenten Kreaturen sprechen. Die Kommunikation ist auf die Intelligenz und Erfahrung der Kreatur begrenzt — ein Wurm kann nur einfachste Konzepte mitteilen. Der Zauber macht die Kreatur nicht freundlicher — feindliche Monster bleiben feindlich. Dauer 2 Runden/Stufe. Materialkomponente: V, S.',
  description_en = 'Allows the priest to communicate with any creature — regardless of language, intelligence, or type. The priest can speak with monsters, animals, plants, elementals, undead, and even unintelligent creatures. Communication is limited by the creature''s intelligence and experience — a worm can only convey the simplest concepts. The spell does not make the creature friendlier — hostile monsters remain hostile. Duration 2 rounds/level. Components: V, S.'
WHERE name = 'Mit Monstern Sprechen' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Der Priester kann einen Stein oder Felsen zum Sprechen bringen. Der Stein berichtet, was in seiner unmittelbaren Nähe geschehen ist — wer vorbeigegangen ist, was gesagt wurde, ob Gewalt stattfand etc. Steine haben ein sehr langes Gedächtnis (Jahrhunderte), aber ihre Wahrnehmung ist begrenzt: Sie spüren Vibrationen, Gewicht und Berührung, aber sehen und hören nur vage. Informationen wie „etwas Schweres ging hier vor 3 Tagen vorbei" sind typisch. Magisch geschützte Bereiche können den Stein zum Schweigen bringen. Dauer 1 Runde/Stufe. Materialkomponenten: V, S, M (Ton und ein Tropfen Honig).',
  description_en = 'The priest can make a stone or rock speak. The stone reports what happened in its immediate vicinity — who passed by, what was said, whether violence occurred, etc. Stones have very long memories (centuries), but their perception is limited: they sense vibrations, weight, and touch but only vaguely see and hear. Information like "something heavy passed here 3 days ago" is typical. Magically protected areas can silence the stone. Duration 1 round/level. Material components: V, S, M (clay and a drop of honey).'
WHERE name = 'Stein Erzählt' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Der Priester tritt in einen großen Baum ein und wird sofort zu einem anderen Baum derselben Art an einem vom Priester benannten Ort teleportiert — Reichweite unbegrenzt (auf derselben Ebene). Der Priester muss den Zielbaum kennen oder den Ort beschreiben können. Die Teleportation ist sofort und fehlerfrei. Nur der Priester wird transportiert (keine Begleiter). Wenn der Zielbaum zerstört wurde, erscheint der Priester am nächsten Baum derselben Art. Dauer sofort. Materialkomponente: V, S.',
  description_en = 'The priest enters a large tree and is instantly teleported to another tree of the same type at a priest-named location — range unlimited (on the same plane). The priest must know the target tree or be able to describe the location. Teleportation is instant and error-free. Only the priest is transported (no companions). If the target tree was destroyed, the priest appears at the nearest tree of the same type. Duration instant. Components: V, S.'
WHERE name = 'Pflanzenreise' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Erzeugt eine Kraft, die alles Holz in einem kegelförmigen Bereich (36 m lang, 12 m breit am Ende) zurückdrängt. Holzgegenstände (Waffen, Schilde, Türen, Möbel) werden mit einer STR von 18 vom Priester weggestoßen. Kreaturen, die Holzwaffen oder -schilde halten, müssen einen STR-Wurf bestehen oder werden entwaffnet. Holzpfeile und -bolzen werden automatisch abgelenkt. Lebende Bäume biegen sich vom Priester weg. Der Effekt bewegt sich mit dem Priester. Dauer 4 Runden/Stufe. Komponenten: V, S.',
  description_en = 'Creates a force that pushes all wood in a cone-shaped area (36 m long, 12 m wide at end) away. Wooden objects (weapons, shields, doors, furniture) are pushed away from the priest with STR 18. Creatures holding wooden weapons or shields must make a STR check or be disarmed. Wooden arrows and bolts are automatically deflected. Living trees bend away from the priest. The effect moves with the priest. Duration 4 rounds/level. Components: V, S.'
WHERE name = 'Holz Wenden' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Erzeugt eine undurchdringliche Wand aus verschlungenen Dornenranken von bis zu 3 m Würfel pro Stufe. Die Dornen sind rasiermesserscharf: Jede Kreatur, die versucht die Wand zu durchdringen, erleidet 8+Stufe Schadenspunkte pro Runde des Durchdringens. Die Durchdringungsgeschwindigkeit hängt von der Größe ab: Menschengroße Kreaturen brauchen 1 Runde pro 30 cm. Die Dornen verfangen sich in Rüstung und Kleidung. Feuer verbrennt die Dornen in 1W4 Runden, verursacht aber 4W8 Feuerschaden an allen Kreaturen darin. Dauer 1 Stunde/Stufe. Materialkomponenten: V, S, M (ein Dorn und ein Stück Holzkohle).',
  description_en = 'Creates an impenetrable wall of intertwined thorn vines up to 3 m cube per level. The thorns are razor-sharp: any creature attempting to penetrate the wall takes 8+level damage per round of penetration. Penetration speed depends on size: man-sized creatures need 1 round per 30 cm. Thorns catch on armor and clothing. Fire burns the thorns in 1d4 rounds but deals 4d8 fire damage to all creatures within. Duration 1 hour/level. Material components: V, S, M (a thorn and a piece of charcoal).'
WHERE name = 'Dornenwand' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Der Priester beschwört ein spezifisches Wetterphänomen herauf. Die Beschwörung dauert 1W4 × 10 Runden, und das Wetter hält 1W12 Stunden an. Mögliche Wetterbedingungen hängen von Klima und Jahreszeit ab: Schneesturm, Nebel, Gewitter, Starkregen, Hitzewelle, starke Winde etc. Das Wetter ist natürlich (nicht magisch) und betrifft einen Bereich von ca. 7 km Radius. Extreme Wetterphänomene (Tornado, Blizzard) können erheblichen Schaden anrichten. Dauer 1W12 Stunden nach Eintreten. Materialkomponenten: V, S, M (Räucherwerk, Gebetsmaterialien und das heilige Symbol).',
  description_en = 'The priest summons a specific weather phenomenon. The summoning takes 1d4 × 10 rounds, and the weather lasts 1d12 hours. Possible weather conditions depend on climate and season: blizzard, fog, thunderstorm, heavy rain, heat wave, strong winds, etc. The weather is natural (not magical) and affects an area of about 7 km radius. Extreme weather (tornado, blizzard) can cause significant damage. Duration 1d12 hours after onset. Material components: V, S, M (incense, prayer materials, and the holy symbol).'
WHERE name = 'Wetter Beschwören' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Teleportiert den Priester sofort und fehlerfrei zu seinem vorher festgelegten Zufluchtsort (typischerweise sein Tempel oder Heiligtum). Der Zufluchtsort muss beim Wirken des Zaubers (Stufe 6) als „Rückkehrpunkt" festgelegt werden. Die Teleportation ist sofort, hat unbegrenzte Reichweite (auf derselben Ebene) und transportiert auch bis zu 11 kg nichtlebende Materie pro Stufe. Keine Fehlerchance. Der Priester kann den Rückkehrpunkt ändern — erfordert erneutes Wirken des Zaubers am neuen Ort. Materialkomponente: V.',
  description_en = 'Teleports the priest instantly and without error to his predetermined sanctuary (typically his temple or shrine). The sanctuary must be designated as a "return point" when the spell is cast (at level 6). The teleportation is instant, has unlimited range (on the same plane), and also transports up to 11 kg of nonliving matter per level. No error chance. The priest can change the return point — requires recasting the spell at the new location. Component: V.'
WHERE name = 'Worte der Rückkehr' AND spell_type = 'priest';
