-- ═══════════════════════════════════════════════════════════════════════════════
-- PHB Priest Spells Level 7 (Batch 2: 7 Spells)
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  description = 'Stellt alle verlorenen Erfahrungsstufen (durch Untote-Stufenentzug, Energieentzug etc.) einer berührten Kreatur wieder her. Pro Wirken wird 1 verlorene Stufe wiederhergestellt. Die Kreatur erhält alle Vorteile der wiederhergestellten Stufe zurück: TP, THAC0, Rettungswürfe, Zauberslots etc. Der Priester altert beim Wirken um 2 Jahre. Der Zauber heilt keine anderen Effekte — nur Stufenverlust. Wenn die Kreatur mehrere Stufen verloren hat, muss der Zauber mehrfach gewirkt werden. Umkehrbar: Stufenentzug — entzieht einer berührten Kreatur 1 Stufe (Rettungswurf gegen Tod negiert). Materialkomponente: V, S.',
  description_en = 'Restores all lost experience levels (from undead level drain, Energy Drain, etc.) of a touched creature. Each casting restores 1 lost level. The creature regains all benefits of the restored level: HP, THAC0, saving throws, spell slots, etc. The priest ages 2 years per casting. The spell does not cure other effects — only level loss. If the creature lost multiple levels, the spell must be cast multiple times. Reversible: Energy Drain — drains 1 level from a touched creature (save vs. death negates). Components: V, S.'
WHERE name = 'Wiederherstellung' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Erweckt eine tote Kreatur vollständig zum Leben zurück — mächtiger als Tote Erwecken. Die Kreatur kann bis zu 10 Jahre pro Stufe des Priesters tot gewesen sein. Sie kehrt mit ALLEN Trefferpunkten zurück und muss nur 1 Tag ruhen (statt 1 Tag/Stufe wie bei Tote Erwecken). Sie verliert trotzdem 1 Punkt Konstitution permanent. Der Systemschock-Wurf muss bestanden werden. Funktioniert auch auf Elfen (im Gegensatz zu Tote Erwecken). Kann sogar auf Kreaturen angewandt werden, deren Körper zerstört wurde — der Körper wird rekonstruiert (erfordert ein kleines Stück des Originals). Materialkomponenten: V, S, M (das heilige Symbol und Weihwasser — die Zeremonie dauert 1 Stunde).',
  description_en = 'Raises a dead creature fully back to life — more powerful than Raise Dead. The creature can have been dead up to 10 years per priest level. It returns with ALL hit points and needs only 1 day of rest (instead of 1 day/level as with Raise Dead). It still permanently loses 1 point of Constitution. System shock roll must be passed. Also works on elves (unlike Raise Dead). Can even be used on creatures whose body was destroyed — the body is reconstructed (requires a small piece of the original). Material components: V, S, M (the holy symbol and holy water — the ceremony takes 1 hour).'
WHERE name = 'Auferstehung' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Wie der gleichnamige Magier-Zauber Beistand (9. Stufe). Der Priester erzeugt eine Miniatur-Abbildung seiner selbst auf einem Gegenstand. Jeder Besitzer kann ein Kommandowort sprechen und wird sofort zum Priester teleportiert — oder der Priester wird zum Gegenstand teleportiert (nach Wahl beim Wirken). Teleportation ist fehlerfrei. Einmaliger Gebrauch. Materialkomponenten: V, S, M (ein fein gearbeiteter Gegenstand im Wert von mind. 5.000 GM).',
  description_en = 'Like the wizard Succor spell (9th level). The priest creates a miniature depiction of himself on an object. Any holder can speak a command word and is instantly teleported to the priest — or the priest is teleported to the object (chosen at casting). Teleportation is error-free. One-time use. Material components: V, S, M (a finely crafted object worth at least 5,000 gp).'
WHERE name = 'Beistand (Priester)' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Erzeugt einen intensiven Strahl konzentrierten Sonnenlichts von 1,5 m Durchmesser und 3 m Länge. Der Strahl verursacht gegen die meisten Kreaturen 3W6 Schaden (Rettungswurf gegen Zauber halbiert) und verursacht temporäre Blindheit für 1W3 Runden bei missglücktem Rettungswurf. Gegen Untote verursacht der Strahl 6W6 Schaden (8W6 gegen besonders sonnenempfindliche Untote wie Vampire). Vampire, die vom Strahl getroffen werden, müssen einen Rettungswurf gegen Tod bestehen oder werden sofort vernichtet. Pilzkreaturen und lichtempfindliche Kreaturen erleiden 8W6 Schaden. Der Strahl kann auch als Lichtquelle dienen (Tageslichtäquivalent in 6-m-Radius). Dauer 1 Runde + 1 Segment/Stufe. Materialkomponenten: V, S, M (das heilige Symbol und ein Stück Sonnenstein).',
  description_en = 'Creates an intense beam of concentrated sunlight 1.5 m in diameter and 3 m long. The beam deals 3d6 damage to most creatures (save vs. spell halves) and causes temporary blindness for 1d3 rounds on failed save. Against undead, the beam deals 6d6 damage (8d6 against sun-sensitive undead like vampires). Vampires struck by the beam must save vs. death or be instantly destroyed. Fungus creatures and light-sensitive creatures take 8d6 damage. The beam also serves as a light source (daylight equivalent in 6 m radius). Duration 1 round + 1 segment/level. Material components: V, S, M (the holy symbol and a piece of sunstone).'
WHERE name = 'Sonnenstrahl' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Wie der gleichnamige Magier-Zauber Symbol (8. Stufe). Der Priester schreibt ein göttliches Symbol auf eine Oberfläche, das bei Berührung oder Lesen ausgelöst wird. Mögliche Symbole: Tod (80 TP Kreaturen sterben), Hoffnungslosigkeit, Schmerz, Überzeugung (Gesinnungsänderung), Betäubung etc. Permanent bis ausgelöst oder durch Magie Bannen entfernt. Materialkomponenten: V, S, M (Quecksilber und Diamantenstaub im Wert von mind. 5.000 GM).',
  description_en = 'Like the wizard Symbol spell (8th level). The priest inscribes a divine symbol on a surface that triggers when touched or read. Possible symbols: Death (80 HP creatures die), Hopelessness, Pain, Persuasion (alignment change), Stunning, etc. Permanent until triggered or removed by Dispel Magic. Material components: V, S, M (mercury and diamond dust worth at least 5,000 gp).'
WHERE name = 'Symbol (Priester)' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Verwandelt jedes Metall (einschließlich magischer Metalle, aber nicht Artefakte) in einem Bereich von bis zu 3 m × 3 m pro Stufe in Holz gleicher Form und Größe. Metallene Rüstungen werden zu Holzrüstungen (RK verschlechtert sich dramatisch), metallene Waffen werden zu Holzwaffen (Schaden reduziert, zerbricht leicht). Die Verwandlung ist permanent. Magische Gegenstände erhalten einen Rettungswurf. Adamantit und verzauberte Metalle sind besonders widerstandsfähig (Rettungswurf mit Bonus). Der Zauber ist besonders verheerend in Schlachten — ganze Reihen von Rittern können entwaffnet werden. Materialkomponente: V, S, M (ein kleines Stück Holz und ein Tropfen Quecksilber).',
  description_en = 'Transforms any metal (including magical metals, but not artifacts) in an area of up to 3 m × 3 m per level into wood of the same shape and size. Metal armor becomes wooden armor (AC degrades dramatically), metal weapons become wooden weapons (damage reduced, breaks easily). The transformation is permanent. Magical items receive a saving throw. Adamantite and enchanted metals are especially resistant (save with bonus). The spell is especially devastating in battles — entire ranks of knights can be disarmed. Material component: V, S, M (a small piece of wood and a drop of mercury).'
WHERE name = 'Metall zu Holz' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Der Priester und bis zu 1 Kreatur/Stufe werden in einen halbmateriellen, windartigen Zustand verwandelt. In dieser Form bewegen sie sich mit 18 m/Runde fliegend (bei starkem Rückenwind bis zu 108 m/Runde). Die Kreaturen können durch enge Spalten und unter Türen hindurchgleiten, sind aber verwundbar gegen Magie. Sie können nicht angreifen oder zaubern (außer der Priester, der den Zauber aufrechterhalten muss). Der Windwandel ermöglicht schnelles Reisen über große Entfernungen. Am Zielort materialisieren sich alle Reisenden gleichzeitig. Dauer 1 Stunde/Stufe. Materialkomponenten: V, S, M (Weihrauch und ein Stück Feuer).',
  description_en = 'The priest and up to 1 creature/level are transformed into a semi-material, wind-like state. In this form they move at 18 m/round flying (with strong tailwind up to 108 m/round). The creatures can slip through narrow gaps and under doors but are vulnerable to magic. They cannot attack or cast (except the priest who must maintain the spell). Wind Walk enables fast travel over great distances. At the destination, all travelers materialize simultaneously. Duration 1 hour/level. Material components: V, S, M (incense and a piece of fire).'
WHERE name = 'Windwandeln' AND spell_type = 'priest';
