-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 1 (Batch 1: 15 Spells — Adhesion to Balance)
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  description = 'Lässt zwei feste Objekte für die Zauberdauer aneinander haften. Der Zauberkundige muss die Verbindungsstelle berühren. Die Objekte können durch einen erfolgreichen Stangen-biegen/Gitter-heben-Wurf, durch Magie Bannen oder durch eine Kraft von mehr als 453,6 kg plus 45,4 kg pro Stufe getrennt werden. Wird der Zauber gegen getragene oder gehaltene Gegenstände einer unwilligen Kreatur eingesetzt, erhält das Ziel einen Rettungswurf gegen Zauber. Materialkomponente: V, S, M (eine Prise gepulverter Pferdehuf).',
  description_en = 'Causes two solid objects to adhere to one another for the spell duration. The caster must touch the juncture between the objects. The adhered objects can be separated by a successful bend bars/lift gates check, by Dispel Magic, or by exerting a force of more than 453.6 kg plus 45.4 kg per caster level. If the spell is used against objects worn or carried by an unwilling creature, the target gets a saving throw vs. spell. Material component: V, S, M (a pinch of powdered horse''s hoof).'
WHERE LOWER(name_en) = LOWER('Adhesion') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht einem Barden, ein Musikinstrument in ein anderes von ähnlicher Größe und gleichem Wert zu verwandeln. Jedes Handinstrument kann in ein anderes Handinstrument verwandelt werden. Für große Instrumente (Standharfe, Orgel etc.) muss das Ausgangsinstrument ebenso groß sein. Der Wert des neuen Instruments entspricht dem Original — ein goldener Blockflöte erzeugt eine versilberte Laute, eine Kindertrommel eine funktionslose Leier. Wird das Instrument von einer anderen Person gehalten, ist ein erfolgreicher Angriffswurf nötig, um es zu berühren. Komponenten: V, S.',
  description_en = 'Allows a bard to transform one musical instrument into another of similar size and equal value. Any hand-held instrument can be altered into any other hand-held instrument. For large instruments (base harp, organ, etc.), the bard must start with an equally large instrument. The value of the new instrument is identical to the original — a golden recorder generates a silver-plated lute, a child''s drum generates a nonfunctional lyre. If the instrument is being carried by another character, a successful attack roll is needed to touch it. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Alter Instrument — Bard') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht dem Zauberkundigen, einen nichtmagischen Wind um eine Stufe zu verändern (gemäß DMG Tabelle 79 „Wetterbedingungen"). Windstille kann zu leichter Brise werden, leichte Brise zu günstigem Wind oder zurück zu Windstille. Funktioniert auch in geschlossenen Räumen (Dungeons gelten als windstill). Zauberer der 9. Stufe oder weniger können nur Winde bis Sturmstärke beeinflussen. Ab Stufe 10 können Orkanwinde beeinflusst werden, ab Stufe 15 Hurrikanwinde. Der Wind kann nur einmal verändert werden. Solange der Zauber wirkt, können keine weiteren Alter-Wind-Zauber denselben Bereich betreffen. Kann nichtmagischen Nebel, Staub oder giftiges Gas für 1W6 Runden vertreiben. Hat keine Wirkung auf Elementarwesen der Luft oder Odemwaffen. Materialkomponente: V, S, M (ein kleines silbernes Rohr).',
  description_en = 'Enables the caster to change a nonmagical wind''s force by one rank (per DMG Table 79 "Weather Conditions"). Becalmed conditions can become a light breeze, a light breeze can become a favorable wind or return to calm. Works equally in enclosed areas like dungeons (considered becalmed). Wizards of 9th level or less can only modify winds of storm force or less. At 10th level, gale-force winds can be altered; at 15th level, hurricane-force winds. The wind can only be changed once. While shaped by this spell, no subsequent alter wind spells can affect the same area. Can move nonmagical fog, dust, or poisonous gas out of the way for 1d6 rounds. Has no effect on air elementals or breath weapons. Material component: V, S, M (a small silver tube).'
WHERE LOWER(name_en) = LOWER('Alter Normal Winds') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verändert die Lautstärke von Geräuschen nahe dem Wirkungszentrum. Der Zauberkundige erzeugt eine scheibenförmige Zone von 5,1 cm bis 0,3 m Durchmesser, die als Schallverstärker dient. Geräusche, die von der aktiven Seite eintreten, können auf der anderen Seite bis zu fünfmal lauter oder leiser als normal abgegeben werden — steuerbar durch mentalen Befehl des Zauberkundigen. Hat keine Wirkung auf spezielle schallbasierte Angriffe. Materialkomponente: V, S, M (ein kleiner Papierkegel).',
  description_en = 'Changes the volume of sounds near its center of effect. The caster creates a disk-shaped zone from 5.1 cm to 0.3 m in diameter that acts as a sound magnifier. Sounds entering the active (caster) side exit the other side at a different volume — up to five times louder or softer than normal, controllable by the caster''s mental command. Has no effect on special sound-based attacks. Material component: V, S, M (a small cone of paper).'
WHERE LOWER(name_en) = LOWER('Amplify') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Durch beruhigende Melodie hören alle normalen Tiere im Wirkungsbereich auf, aggressiv gegenüber der Gruppe des Barden zu handeln. Der Effekt wird aufgehoben, wenn die Gruppe die Tiere oder deren Lager belästigt. Der Zauber erzeugt keine Freundschaft seitens der Tiere und verleiht dem Barden weder Kommunikations- noch Kontrollfähigkeiten. Hat keine Wirkung auf magische Tiere oder normale Tiere unter magischer Kontrolle. Der Barde muss sowohl singen als auch ein Instrument spielen. Komponente: S (Gesang + Instrument).',
  description_en = 'Upon hearing the soothing tones, any normal animals in the area of effect cease to act aggressively toward the bard''s party. The effect is negated if the party molests the animals or their lairs. The song does not cause friendship on the animals'' part, nor does it grant the bard communicative or controlling ability. Has no effect on magical animals or normal animals under magical control. The bard must both sing and play an instrument. Component: S (singing + instrument).'
WHERE LOWER(name_en) = LOWER('Animal Nonaggression — Bard') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Angriffswürfe und Schaden gegen ein durch diesen Zauber geschütztes Tier erleiden einen Abzug von −4. Dieser Zauber wird häufig auf Reittiere, Haustiere und Vertraute angewandt. Wenn das geschützte Tier angreift, wird der Schutz gebrochen. Materialkomponente: V, S, M (eine Feder, ein Stück Fell oder eine Schuppe des zu schützenden Tieres).',
  description_en = 'Attack rolls and damage against an animal protected by this spell suffer a −4 penalty. This spell is frequently used on mounts, pets, and familiars. If the animal attacks, the protection is broken. Material component: V, S, M (a feather, bit of fur, or scale from the animal to be protected).'
WHERE LOWER(name_en) = LOWER('Animal Sanctuary') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erschafft untote Skelette und Zombies aus den Knochen und Körpern toter Tiere (Wirbeltiere: Fische, Amphibien, Reptilien, Vögel, Säugetiere). Die belebten Überreste gehorchen einfachen verbalen Befehlen des Zauberkundigen in beliebiger Sprache. Nur natürlich vorkommende Tiere mit höchstens Halb-Intelligenz können belebt werden. Die Untoten bleiben belebt, bis sie im Kampf zerstört oder vertrieben werden — die belebende Magie kann nicht gebannt werden. Die Anzahl der Untoten hängt von den ursprünglichen TW des Tieres und der Stufe des Zauberkundigen ab: Bei ¼ TW oder weniger: 4 Skelette/Stufe oder 2 Zombies/Stufe. Bei ½–1 TW: 2 Skelette/Stufe oder 1 Zombie/Stufe. Bei 1+–3+3 TW: 1 Skelett/Stufe oder 1 Zombie/2 Stufen. Höhere TW entsprechend weniger. Materialkomponente: V, S, M.',
  description_en = 'Creates undead skeletons and zombies from bones and bodies of dead animals (vertebrates: fish, amphibians, reptiles, birds, mammals). The animated remains obey simple verbal commands from the caster in any language. Only naturally occurring animals of semi-intelligence or less can be animated. The undead remain animated until destroyed in combat or turned — the animating magic cannot be dispelled. The number of undead depends on the animal''s original HD and the caster''s level: At ¼ HD or less: 4 skeletons/level or 2 zombies/level. At ½–1 HD: 2 skeletons/level or 1 zombie/level. At 1+–3+3 HD: 1 skeleton/level or 1 zombie/2 levels. Higher HD proportionally fewer. Material component: V, S, M.'
WHERE LOWER(name_en) = LOWER('Animate Dead Animals') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Wu Jen kann Holzgegenstände bewegen und biegen. Am wirksamsten bei lebenden Pflanzen, funktioniert aber auch bei totem Holz. Der Zauber verleiht dem Holz Geschmeidigkeit und Bewegung — Greifen, Verschlingen etc. sind möglich. Die Bewegung ist jedoch langsam und steif; belebte Objekte schlagen im Kampf immer zuletzt. Die Form des Gegenstands ändert sich nicht — ein Pfeil bleibt ein Pfeil, kann sich aber wie eine Schlange winden. Fixierte Objekte (z.B. verwurzelte Bäume) können sich nicht fortbewegen, aber angreifen. Belebte Objekte greifen an wie ein Stufe-0-Mensch mit Schaden entsprechend ihrer Größe (Ast = Keule etc.). RK 5–10 je nach Größe und Masse. Trefferpunkte: 1W10 pro 3 m Höhe oder Quadratmeter Fläche. Pro Stufe kann 1 lebende Pflanze (≤1,5 m) oder 2 pfeilgroße Stücke toten Holzes belebt werden. Materialkomponente: V, S, M.',
  description_en = 'The wu jen can cause wooden items to move and bend. Most effective on living plants, but works on all types of wood. The spell gives wood suppleness and motion — grasping, entangling, etc. are possible. Movement is slow and stiff; animated objects always strike last in combat. The item''s form doesn''t change — an arrow is still a shaft but can wriggle like a snake. Fixed objects (rooted trees) cannot move about but can attack. Animated items attack as a 0-level human with damage comparable to a weapon of similar size (branch = club, etc.). AC 5–10 based on size and mass. Hit points: 1d10 per 3 m of height or square meter of area. Per level, 1 living plant (≤1.5 m) or 2 arrow-sized pieces of dead wood can be animated. Material component: V, S, M.'
WHERE LOWER(name_en) = LOWER('Animate Wood') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Diese Verzauberung kann auf einen oder mehrere Bogenschützen gewirkt werden (max. 30 bei Stufe 10). Für die Zauberdauer wird die Reichweite der Bogenschützen für kurze, mittlere und lange Distanz verdoppelt. Zusätzlich verursachen Pfeile +1 Schadenspunkt bei jedem Treffer. Funktioniert nicht mit anderen Fernkampfwaffen (Speere, Schleudern, Armbrüste). Addiert sich nicht zu anderen magischen Boni für Reichweite oder Schaden; der Schadensbonus selbst ist nicht magisch. Materialkomponente: V, S, M (ein Stückchen Daunenfeder, in Form einer Pfeilbefiederung geschnitten).',
  description_en = 'This enchantment can be cast on one or more archers (max 30 at 10th level). For the spell duration, the archers'' range is doubled for short, medium, and long ranges. In addition, arrows inflict +1 damage per successful hit. Cannot be used with other missile weapons (spears, slings, crossbows). Does not add to other magical bonuses for range or damage; the damage bonus itself is not magical. Material component: V, S, M (a bit of downfeather trimmed into arrow fletching shape).'
WHERE LOWER(name_en) = LOWER('Arrowflight — Pluma') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Lässt eine Wasserquelle sofort seifig werden. Unsichtbare Hände schrubben Schaumblasen auf alle lebende Materie im Wasser. Hände und Seife verschwinden bei Ablauf des Zaubers. Dieser Zauber wurde von der alten Zauberin Aunty Carlys erfunden, die oft Abenteurerkinder beaufsichtigte. Besonders nützlich zum Waschen von Hunden, übel riechenden Freunden und lästigen wasserbasierten Monstern. Materialkomponente: V, S, M (ein Stück Seife).',
  description_en = 'Causes a water source to instantly become soapy. Unseen hands scrub bubbles upon all living matter in the water. The hands and soap disappear when the spell duration runs out. This spell was created by the old wizard Aunty Carlys, who often took care of adventurers'' children. Especially useful for washing dogs, odorous friends, and pesky water-based monsters. Material component: V, S, M (a bar of soap).'
WHERE LOWER(name_en) = LOWER('Aunty''s Bath') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ähnlich dem Priester-Zauber Feenfeuer der 1. Stufe. Umreißt ein oder mehrere Objekte oder Kreaturen mit blassem rötlichem Licht. Die Anzahl der umrissenen Ziele hängt von der verfügbaren Länge ab (3,6 m pro Stufe im 12-m-Radius). Umrissene Objekte/Kreaturen sind in der Dunkelheit auf 73,2 m sichtbar, bei heller Lichtquelle auf 36,6 m. Gegner erhalten +2 auf Angriffswürfe in Dunkelheit (einschließlich Mondnächte) und +1 bei Dämmerlicht oder besser. Kann ansonsten unsichtbare Kreaturen sichtbar machen. Funktioniert nicht gegen nichtkörperliche, ätherische oder gasförmige Kreaturen. Das Licht verursacht keinen Schaden und hat keine besondere Wirkung auf Untote. Komponenten: V, S.',
  description_en = 'Similar to the 1st-level priest spell Faerie Fire. Outlines one or more objects or creatures with a pale reddish light. The number of subjects outlined depends on available length (3.6 m per level within a 12 m radius). Outlined objects/creatures are visible at 73.2 m in the dark, 36.6 m near a bright light source. Opponents gain +2 on attack rolls in darkness (including moonlit nights) and +1 in twilight or better. Can render otherwise invisible creatures visible. Does not work against noncorporeal, ethereal, or gaseous creatures. The light causes no harm and has no special effect on undead. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Aura Fire — Red Wizard') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht einer Person (wie bei Bezaubern von Personen definiert), auf einem oder beiden Füßen in einer prekären Position das Gleichgewicht zu halten, wo ein Sturz sonst wahrscheinlich wäre. Die Person kann ein Seil begehen, einen schmalen oder instabilen Sims überqueren oder am Rand einer Klippe kämpfen, ohne Sturzgefahr. Balancier-Aktionen, die einen Geschicklichkeitswurf erfordern, gelingen automatisch wenn die Person unbehindert ist. Der Zauber modifiziert nicht RK, Kampf-, Fernkampfboni oder Kletterboni, negiert aber Abzüge aufgrund schlechter Balance. Bei zusätzlichen Störfaktoren (Schubsen, starker Wind, Eis) hat die Person eine effektive Minimalgeschicklichkeit von 15 und +1 bis +4 Vorteil gegenüber natürlicher Balance. Materialkomponente: V, S, M (eine Prise gepulverter Bergziegenhuf).',
  description_en = 'Enables a person (as defined in Charm Person) to balance on one or both feet in a precarious position where a fall would otherwise be likely. The person can walk a tightrope, cross a narrow or unstable ledge, or fight near a cliff edge without fear of falling. Balancing actions requiring a Dexterity check are passed automatically if unhindered. The spell does not modify AC, fighting, missile bonuses, or climbing bonuses, but negates penalties due to poor balance. With additional hindering factors (pushing, high winds, ice), the individual has a minimum effective Dexterity of 15 and +1 to +4 advantage over natural balance. Material component: V, S, M (a pinch of powdered mountain goat hoof).'
WHERE LOWER(name_en) = LOWER('Balance') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt eine transparente magische Barriere im 3-m-Radius um den Zauberkundigen, 3 m hoch. Diese solide magische Wand kann 5 Schadenspunkte pro Stufe des Zauberkundigen (max. 25) aushalten, bevor sie zerbricht. Der Zauberkundige kann keine schadenverursachenden Zauber durch die Barriere wirken und nicht physisch durch sie hindurch angreifen. Die Barriere hat RK 5 und erleidet automatisch vollen Schaden durch Zauber. Wird sie durch einen Schadenszauber zerstört, erhält der Zauberkundige den normalen Rettungswurf gegen den restlichen Schaden. Die Barriere bewegt sich mit dem Zauberkundigen. Materialkomponente: V, S, M (ein Stück Jade oder Amethyst im Wert von mind. 50 GM; wird beim Wirken verbraucht).',
  description_en = 'Creates a transparent magical barrier in a 3 m radius around the caster, 3 m high. This solid magical wall can withstand 5 hit points of damage per caster level (max 25) before it shatters. The caster cannot cast damage-causing spells through the barrier nor physically attack through it. The barrier has AC 5 and automatically suffers full damage from spells. If a damage spell destroys the barrier, the caster gets the normal saving throw against remaining damage. The barrier moves with the caster. Material component: V, S, M (a piece of jade or amethyst worth at least 50 gp; consumed in casting).'
WHERE LOWER(name_en) = LOWER('Barrier — Old Empire') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt einen unsichtbaren Diener in Form eines kleinen Bücherwurms, der ein einzelnes Buch oder eine Schriftrolle vor Schäden durch natürliche Insekten, Feuchtigkeit, Schimmel und normales Feuer schützt. Das geschützte Objekt wird von einer unsichtbaren Aura umgeben, die Insekten abwehrt, Feuchtigkeit fernhält und gegen normale Flammen immun macht (nicht gegen magisches Feuer). Der Zauber schützt nur ein einzelnes Buch oder eine Schriftrolle. Der Schutz ist permanent bis gebannt. Materialkomponente: V, S, M (ein Tropfen Zedernöl und ein winziges Stück Mottenkugel).',
  description_en = 'Creates an invisible servant in the form of a tiny bookworm that protects a single book or scroll from damage by natural insects, moisture, mold, and normal fire. The protected object is surrounded by an invisible aura that repels insects, keeps moisture away, and makes it immune to normal flames (not magical fire). The spell only protects a single book or scroll. The protection is permanent until dispelled. Material component: V, S, M (a drop of cedar oil and a tiny piece of mothball).'
WHERE LOWER(name_en) = LOWER('Bigby''s Bookworm Bane') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erschafft eine unsichtbare, körperlose Hand, die der Zauberkundige in einem Bereich von 3 m + 0,3 m/Stufe um sich herum kontrollieren kann. Die Hand kann Objekte bis zu 0,5 kg Gewicht ertasten, berühren und manipulieren — Schlösser fühlen, kleine Objekte aufheben, Knöpfe drücken, Schubladen öffnen etc. Die Hand hat den Tastsinn des Zauberkundigen und kann durch Tasten Fallen entdecken (Entdeckungswurf mit −20% Abzug). Die Hand kann nicht angreifen, Waffen führen oder Zauber wirken. Wird sie durch Schaden zerstört (RK 10, 1 TP), endet der Zauber. Materialkomponente: V, S, M (ein Lederhandschuh).',
  description_en = 'Creates an invisible, disembodied hand that the caster can control within a range of 3 m + 0.3 m/level around himself. The hand can feel, touch, and manipulate objects weighing up to 0.5 kg — feel locks, pick up small objects, push buttons, open drawers, etc. The hand has the caster''s sense of touch and can detect traps by feeling (detection roll at −20% penalty). The hand cannot attack, wield weapons, or cast spells. If destroyed by damage (AC 10, 1 HP), the spell ends. Material component: V, S, M (a leather glove).'
WHERE LOWER(name_en) = LOWER('Bigby''s Feeling Fingers') AND spell_type = 'wizard';
