-- ═══════════════════════════════════════════════════════════════════════════════
-- PHB Priest Spells Level 7 (Batch 1: 15 Spells)
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  description = 'Belebt einen großen Felsen oder Steinhaufen als einen steingolem-ähnlichen Wächter. Der belebte Stein hat TW abhängig von seiner Größe (max. 2 m³ = 5 TW, max. 6 m³ = 12 TW). Der Stein hat RK 0, bewegt sich mit 6 m/Runde und verursacht 3W6 Schaden pro Angriff. Er gehorcht einfachen Befehlen des Priesters. Nur magische Waffen +2 oder besser können den belebten Stein beschädigen. Feuer und Kälte haben keine Wirkung. Erdbeben-Zauber zerstören ihn sofort. Dauer 1 Runde/Stufe. Materialkomponenten: V, S, M (das heilige Symbol und ein Tropfen Quecksilber).',
  description_en = 'Animates a large rock or stone pile as a stone golem-like guardian. The animated rock has HD depending on its size (max 2 m³ = 5 HD, max 6 m³ = 12 HD). The rock has AC 0, moves at 6 m/round, and deals 3d6 damage per attack. It obeys simple commands from the priest. Only magical weapons +2 or better can damage the animated rock. Fire and cold have no effect. Earthquake spells destroy it instantly. Duration 1 round/level. Material components: V, S, M (the holy symbol and a drop of mercury).'
WHERE name = 'Stein Beleben' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Wie der gleichnamige Magier-Zauber (9. Stufe). Projiziert den Astralkörper des Priesters und bis zu 7 Begleiter auf die Astralebene. Der physische Körper bleibt in Trance. Eine silberne Nabelschnur verbindet Astral- und physischen Körper — Durchtrennung = sofortiger Tod. Auf der Astralebene kann man zu anderen Ebenen reisen. Dauer bis zur Rückkehr oder Durchtrennung der Schnur. Materialkomponenten: V, S, M (ein Jacinth im Wert von mind. 1.000 GM und ein Silberbarren im Wert von 5 GM pro Reisendem).',
  description_en = 'Like the wizard spell of the same name (9th level). Projects the astral body of the priest and up to 7 companions onto the Astral Plane. Physical body remains in trance. A silver umbilical cord connects astral and physical body — severance = instant death. On the Astral Plane, one can travel to other planes. Duration until return or cord severance. Material components: V, S, M (a jacinth worth at least 1,000 gp and a silver bar worth 5 gp per traveler).'
WHERE name = 'Astralzauber (Priester)' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Der Priester verwandelt seinen Holzstab in einen mächtigen Baumherren (Treant) mit 12 TW, RK 0, und 4W6 Schaden. Der Stab muss ein speziell vorbereiteter Holzstab sein, der 28 Tage lang mit heiligem Öl behandelt wurde. Der Baumherr gehorcht allen Befehlen des Priesters und hat alle normalen Fähigkeiten eines Treants: kann andere Bäume beleben (bis zu 2 Bäume), ist immun gegen normale Waffen, und anfällig für Feuer. Wenn der Baumherr getötet wird, ist der Stab für immer zerstört. Dauer bis der Priester den Baumherren zurückverwandelt oder er getötet wird. Materialkomponenten: V, S, M (der speziell vorbereitete Holzstab und das heilige Symbol).',
  description_en = 'The priest transforms his wooden staff into a mighty treant with 12 HD, AC 0, and 4d6 damage. The staff must be a specially prepared wooden staff treated with holy oil for 28 days. The treant obeys all commands and has all normal treant abilities: can animate other trees (up to 2 trees), immune to normal weapons, vulnerable to fire. If the treant is killed, the staff is destroyed forever. Duration until the priest reverts the treant or it is killed. Material components: V, S, M (the specially prepared wooden staff and the holy symbol).'
WHERE name = 'Stabwandlung' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Beschwört einen flammenden Wagen, der vom Himmel herabfährt und den Priester sowie bis zu 8 Begleiter transportiert. Der Wagen bewegt sich mit 72 m/Runde fliegend und ist in Flammen gehüllt — Kreaturen, die den Wagen berühren, erleiden 2W6 Feuerschaden. Der Wagen ist immun gegen normales Feuer und Kälte. Er kann auch auf dem Boden fahren (36 m/Runde). Der Priester steuert den Wagen mental. Der Wagen verschwindet am Ende der Dauer und alle Passagiere erscheinen sicher am Boden. Dauer 12 Stunden. Materialkomponenten: V, S, M (das heilige Symbol und ein kleiner goldener Wagen im Wert von mind. 500 GM).',
  description_en = 'Summons a flaming chariot that descends from the sky and transports the priest and up to 8 companions. The chariot moves at 72 m/round flying and is wreathed in flames — creatures touching the chariot take 2d6 fire damage. The chariot is immune to normal fire and cold. It can also travel on the ground (36 m/round). The priest steers the chariot mentally. The chariot vanishes at duration''s end and all passengers appear safely on the ground. Duration 12 hours. Material components: V, S, M (the holy symbol and a small golden chariot worth at least 500 gp).'
WHERE name = 'Chariot von Sustarre' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Wie der gleichnamige Magier-Zauber (4. Stufe). Erzeugt Verwirrung bei Kreaturen im Wirkungsbereich (bis zu 18-m-Würfel). 1W4+Stufe Kreaturen betroffen. Rettungswurf gegen Zauber mit −2. Verwirrte Kreaturen würfeln 1W10 jede Runde: 1 = wandert davon, 2-6 = steht verwirrt, 7-9 = greift nächste Kreatur an, 10 = handelt normal. Dauer 2 Runden + 1 Runde/Stufe. Materialkomponente: V, S, M (drei Nussschalen).',
  description_en = 'Like the wizard spell of the same name (4th level). Creates confusion in creatures in the area (up to 18 m cube). 1d4+level creatures affected. Saving throw vs. spell at −2. Confused creatures roll 1d10 each round: 1 = wander away, 2-6 = stand confused, 7-9 = attack nearest, 10 = act normally. Duration 2 rounds + 1 round/level. Material component: V, S, M (three nut shells).'
WHERE name = 'Verwirrung (Priester)' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Beschwört ein Erdelementar (12 TW, RK 2, 4W8 Schaden) aus einem Bereich natürlicher Erde (mind. 5 m³). Das Elemental dient dem Priester, solange dieser volle Konzentration aufrechterhält. Bei Konzentrationsverlust wird es unkontrolliert und greift den Priester an! Das Erdelementar bewegt sich mit 6 m/Runde, kann durch Erde und Stein gleiten, und hat eine STR von 22. Feuer verursacht doppelten Schaden. Es kann nur durch magische Waffen +2 oder besser verwundet werden. Dauer 1 Stunde/Stufe. Materialkomponenten: V, S, M (das heilige Symbol, ein Stück Erde und Opfergaben).',
  description_en = 'Summons an earth elemental (12 HD, AC 2, 4d8 damage) from an area of natural earth (at least 5 m³). The elemental serves the priest as long as full concentration is maintained. On concentration loss, it becomes uncontrolled and attacks the priest! The earth elemental moves at 6 m/round, can glide through earth and stone, and has STR 22. Fire deals double damage. It can only be harmed by magical weapons +2 or better. Duration 1 hour/level. Material components: V, S, M (the holy symbol, a piece of earth, and offerings).'
WHERE name = 'Erdelementar Beschwören' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Wie der gleichnamige Magier-Zauber (6. Stufe), aber mit göttlicher Macht. Der Priester kontrolliert das Wetter in einem 7-km-Radius: Temperatur, Wind, Niederschlag, Wolkendecke. Änderungen treten langsam ein (1W4 × 10 min). Das Wetter kann nur schrittweise verändert werden (nicht von Sonnenschein direkt zu Blizzard). Hält an solange der Priester sich konzentriert + 1W6 Stunden danach. Materialkomponenten: V, S, M (Räucherwerk und Gebetsmaterialien).',
  description_en = 'Like the wizard spell of the same name (6th level), but with divine power. The priest controls weather in a 7 km radius: temperature, wind, precipitation, cloud cover. Changes take effect slowly (1d4 × 10 min). Weather can only be changed stepwise (not sunshine directly to blizzard). Lasts as long as the priest concentrates + 1d6 hours afterward. Material components: V, S, M (incense and prayer materials).'
WHERE name = 'Wetter Kontrollieren (Priester)' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Beschwört eine riesige Masse kriechender Insekten (Käfer, Tausendfüßler, Spinnen, Skorpione) in einer 6-m-Wolke, die sich mit 3 m/Runde auf Befehl des Priesters bewegt. Die Masse verursacht 2 Schadenspunkte pro Runde an jeder Kreatur im Bereich (kein Rettungswurf für den Schaden). Kreaturen mit weniger als 5 TW müssen jede Runde einen Rettungswurf gegen Zauber bestehen oder fliehen in Panik. Die Insekten sind giftig: 25% Chance pro Runde, dass eine Kreatur gebissen wird und zusätzlich einen Rettungswurf gegen Gift bestehen muss (bei Misserfolg 1W6 zusätzlicher Giftschaden). Kann nicht durch Rauch vertrieben werden — nur durch Flächenfeuer oder Magie Bannen. Dauer 1 Runde/Stufe. Materialkomponente: V, S.',
  description_en = 'Summons a massive swarm of crawling insects (beetles, centipedes, spiders, scorpions) in a 6 m cloud that moves at 3 m/round at the priest''s command. The mass deals 2 damage per round to every creature in the area (no saving throw for damage). Creatures with less than 5 HD must save vs. spell each round or flee in panic. The insects are venomous: 25% chance per round that a creature is bitten and must additionally save vs. poison (on failure 1d6 extra poison damage). Cannot be dispersed by smoke — only by area fire or Dispel Magic. Duration 1 round/level. Components: V, S.'
WHERE name = 'Kriechender Tod' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Erzeugt ein gewaltiges Erdbeben in einem Bereich von 1,5 m Durchmesser pro Stufe. Das Beben dauert 1 Runde und hat verheerende Auswirkungen: Erdspalten (1,5 m breit, 1,5 m tief pro Stufe) verschlucken 1 von 4 Kreaturen im Bereich (Rettungswurf gegen Zauber); Gebäude und Mauern stürzen ein (Kreaturen darin erleiden 2W6 Schaden pro Stockwerk); Höhlen und Tunnel kollabieren (Kreaturen darin erleiden 5W6 Schaden und sind begraben); Wasser wird aufgewühlt (Schiffe werden beschädigt, Schwimmer gehen unter). Im Freien auf festem Boden verursacht das Beben zusätzlich: Kreaturen stürzen hin (GES-Wurf oder 1W4 Runden am Boden). Materialkomponenten: V, S, M (eine Prise Staub, ein Tropfen Wasser und ein Stück Lehm).',
  description_en = 'Creates a massive earthquake in an area of 1.5 m diameter per level. The quake lasts 1 round with devastating effects: earth crevasses (1.5 m wide, 1.5 m deep per level) swallow 1 in 4 creatures in the area (save vs. spell); buildings and walls collapse (creatures within take 2d6 damage per story); caves and tunnels collapse (creatures within take 5d6 damage and are buried); water is churned (ships are damaged, swimmers go under). Outdoors on solid ground, the quake additionally causes: creatures fall (DEX check or 1d4 rounds prone). Material components: V, S, M (a pinch of dust, a drop of water, and a piece of clay).'
WHERE name = 'Erdbeben' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Der Priester fordert eine mächtige außerplanare Kreatur auf, ihm einen Dienst zu erweisen. Die Kreatur erscheint und verhandelt — sie ist NICHT verpflichtet zu gehorchen. Der Priester muss eine angemessene Gegenleistung anbieten (Schatz, magische Gegenstände, einen Dienst). Die Art der Kreatur hängt von der Gottheit des Priesters ab (z.B. ein Solar für einen guten Priester, ein Pit Fiend für einen bösen). Wenn die Verhandlungen scheitern, verschwindet die Kreatur oder wird feindlich. Der Priester kann die Kreatur nicht zwingen. Dauer Spezial (bis die Verhandlung abgeschlossen ist). Materialkomponenten: V, S, M (das heilige Symbol, Opfergaben und ein spezielles Räucherwerk im Wert von mind. 500 GM).',
  description_en = 'The priest demands a powerful extraplanar creature to perform a service. The creature appears and negotiates — it is NOT obligated to obey. The priest must offer an appropriate compensation (treasure, magical items, a service). The creature type depends on the priest''s deity (e.g., a Solar for a good priest, a Pit Fiend for an evil one). If negotiations fail, the creature departs or becomes hostile. The priest cannot compel the creature. Duration special (until negotiation is concluded). Material components: V, S, M (the holy symbol, offerings, and special incense worth at least 500 gp).'
WHERE name = 'Forderung (Priester)' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Erzeugt einen gewaltigen Feuersturm, der einen Bereich von bis zu 6 m × 6 m pro Stufe (max. 24 × 24 m bei Stufe 16+) in Flammen hüllt. Alle Kreaturen im Bereich erleiden 2W8+Stufe Schadenspunkte (halb Feuer, halb göttliche Energie). Rettungswurf gegen Zauber halbiert den Schaden. Brennbare Materialien werden entzündet. Der göttliche Anteil wirkt auch gegen feuerresistente Kreaturen. Der Feuersturm kann auch umgekehrt werden: Ein Kaltsturm verursacht denselben Schaden als Kälte + göttliche Energie und löscht alle Feuer im Bereich. Dauer sofort. Materialkomponente: V, S.',
  description_en = 'Creates a massive fire storm engulfing an area of up to 6 m × 6 m per level (max 24 × 24 m at level 16+) in flames. All creatures in the area take 2d8+level damage (half fire, half divine energy). Saving throw vs. spell halves the damage. Combustible materials are ignited. The divine portion affects fire-resistant creatures too. The fire storm can also be reversed: a Cold Storm deals the same damage as cold + divine energy and extinguishes all fires in the area. Duration instant. Components: V, S.'
WHERE name = 'Feuersturm' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Wie der gleichnamige Magier-Zauber (9. Stufe). Öffnet ein interdimensionales Portal und ruft eine mächtige Kreatur herbei. Die Kreatur ist NICHT verpflichtet zu dienen — sie handelt nach eigenem Ermessen. Mächtige Wesen können verärgert sein, wenn sie grundlos gerufen werden. Das Tor bleibt offen, bis die Kreatur hindurchtritt oder 1 Runde verstreicht. Materialkomponente: V, S.',
  description_en = 'Like the wizard spell of the same name (9th level). Opens an interdimensional portal and summons a powerful creature. The creature is NOT obligated to serve — it acts at its own discretion. Powerful beings may be angered if summoned without reason. The gate stays open until the creature steps through or 1 round passes. Components: V, S.'
WHERE name = 'Tor (Priester)' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Das Heilige Wort ist die mächtigste priesterliche Waffe gegen das Böse. Alle bösen und nicht-guten Kreaturen im 12-m-Radius erleiden Effekte basierend auf ihren TW im Vergleich zur Stufe des Priesters: Kreaturen mit weniger als 4 TW werden getötet (kein Rettungswurf); 4-7 TW werden für 1W4 × 10 Runden gelähmt; 8-11 TW werden für 2W4 Runden verlangsamt und betäubt; 12+ TW werden für 1W4 Runden betäubt. Außerplanare böse Kreaturen (Dämonen, Teufel) werden bei missglücktem Rettungswurf auf ihre Heimatebene zurückgeschickt. Der Zauber wirkt nicht auf gute oder neutrale Kreaturen. Umkehrbar: Unheiliges Wort — wirkt gegen gute Kreaturen. Komponente: V.',
  description_en = 'The Holy Word is the most powerful priestly weapon against evil. All evil and non-good creatures in a 12 m radius suffer effects based on their HD compared to the priest''s level: creatures with less than 4 HD are killed (no save); 4-7 HD are paralyzed for 1d4 × 10 rounds; 8-11 HD are slowed and stunned for 2d4 rounds; 12+ HD are stunned for 1d4 rounds. Extraplanar evil creatures (demons, devils) are sent to their home plane on a failed save. The spell does not affect good or neutral creatures. Reversible: Unholy Word — affects good creatures. Component: V.'
WHERE name = 'Heiliges Wort' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Lässt ein fehlendes oder zerstörtes Körperteil (Arm, Bein, Auge, Ohr, Finger, Zeh etc.) einer berührten Kreatur nachwachsen. Die Regeneration dauert 2W4 Runden für kleine Körperteile (Finger, Zehen) und bis zu 2W6+2 Runden für ganze Gliedmaßen. Während der Regeneration ist die Kreatur geschwächt (−2 auf Trefferwürfe und RK). Der Zauber heilt auch Narbengewebe und Brandwunden. Er kann keine Kreaturen heilen, die magisch verstümmelt wurden (z.B. durch Desintegration). Umkehrbar: Verwelken — lässt ein Glied einer Kreatur bei Berührung verdorren (Rettungswurf negiert). Materialkomponente: V, S, M (ein Gebet und das heilige Symbol).',
  description_en = 'Regrows a missing or destroyed body part (arm, leg, eye, ear, finger, toe, etc.) of a touched creature. Regeneration takes 2d4 rounds for small body parts (fingers, toes) and up to 2d6+2 rounds for whole limbs. During regeneration the creature is weakened (−2 to attack rolls and AC). The spell also heals scar tissue and burns. It cannot heal creatures magically maimed (e.g., by Disintegrate). Reversible: Wither — causes a limb to wither on touch (save negates). Material component: V, S, M (a prayer and the holy symbol).'
WHERE name = 'Regeneration' AND spell_type = 'priest';

UPDATE public.spells SET
  description = 'Die Seele einer toten Kreatur wird in einem neuen Körper wiedergeboren. Der neue Körper wird zufällig bestimmt (SL würfelt auf einer Tabelle) und kann jede humanoide Rasse sein (Mensch, Elf, Zwerg, Halbork, Gnoll etc.). Die Kreatur behält ihr Gedächtnis und ihre Persönlichkeit, aber ihre physischen Attribute (STR, GES, KON, CHA) ändern sich entsprechend der neuen Rasse. INT und WEI bleiben gleich. Die Klasse und Stufe werden beibehalten, sofern die neue Rasse sie erlaubt. Die Reinkarnation funktioniert nur auf Kreaturen, die nicht länger als 1 Woche tot sind. Materialkomponente: V, S.',
  description_en = 'The soul of a dead creature is reborn in a new body. The new body is randomly determined (DM rolls on a table) and can be any humanoid race (human, elf, dwarf, half-orc, gnoll, etc.). The creature retains memory and personality, but physical attributes (STR, DEX, CON, CHA) change according to the new race. INT and WIS remain the same. Class and level are retained if the new race permits them. Reincarnation only works on creatures dead no longer than 1 week. Components: V, S.'
WHERE name = 'Reinkarnation' AND spell_type = 'priest';
