-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 3 (Batch 1: 15 Spells — Acid Lash to Basket Trick)
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  description = 'Erzeugt eine leuchtend purpurne, schwebende Linie aus magischer Kraft, die aus einer Hand des Zauberkundigen hervorgeht. Gewichtslos, 2,1 m lang. Die Säurepeitsche kann hin und her geschwungen werden, um Gegner zu treffen. Sie biegt sich um feste Körper herum. Sie ist ein korrosives Feld, das 4W4 Schaden verursacht (8W4 gegen Untote). ETW0 14. Auch bei mehrfachem Schwingen in einer Runde maximal 4W4 Schaden pro Wesen pro Runde. Beschädigt keine Rüstung, Metall oder Leder (kein echte Säure). Der Zauberkundige kann keine Zweihandwaffe führen, keinen größeren Gegenstand als einen Dolch in der anderen Hand halten und keinen Zauber mit somatischer Komponente wirken. Kann durch einen stillen Willensakt sofort aufgelöst werden. Materialkomponente: V, S, M (mindestens drei Tropfen einer sauren Flüssigkeit).',
  description_en = 'Creates a vivid purple, radiant line of magical force projecting from one of the caster''s hands. Weightless, 2.1 m long. The acid lash can be swept back and forth to strike opponents. It bends around solid bodies. It is a corrosive field dealing 4d4 damage (8d4 to undead). THAC0 14. Even if swept across a foe multiple times in a round, max 4d4 damage per being per round. Does not damage armor, metal, or leather (not true acid). The caster cannot wield two-handed weapons, hold anything larger than a dagger in the other hand, or cast spells with somatic components. Can be dismissed instantly by silent will. Material component: V, S, M (at least three drops of any acidic liquid).'
WHERE LOWER(name_en) = LOWER('Acid Lash') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Ninja kann jedes nichtlebende Material (max. 0,08 m³) um etwa 100 Jahre altern lassen. Das Objekt erhält einen Gegenstandsrettungswurf gegen Auflösung. Bei Misserfolg: Äußerlich leicht verwittert, aber innen von 100 Jahren Alterung gezeichnet. Stein wird kaum betroffen, aber Holz rottet, Metall rostet durch, andere Materialien ähnlich. Beim nächsten Gebrauch zerfällt das Objekt. Steht es bereits unter Spannung, gibt es sofort nach. Ideal zum Sabotieren: Leitersprossen, Holzstufen, Schwerter etc. Betrifft keine Lebewesen. Macht einen Trank der Langlebigkeit dauerhaft nutzlos (einziger Gegenstand ohne Rettungswurf). Komponente: S.',
  description_en = 'The ninja can age any nonliving material (max 0.08 m³) by about 100 years. The object makes an item saving throw vs. disintegration. On failure: appears slightly more weathered outside, but internally ravaged by 100 years. Stone is barely affected, but wood rots, metal rusts through, other materials similarly. Next time the object is used, it crumbles to ruin. If already under strain, it gives way immediately. Ideal for sabotage: ladder rungs, wooden steps, enemy swords, etc. Does not affect living creatures. Permanently renders a potion of longevity useless (the only item with no saving throw). Component: S.'
WHERE LOWER(name_en) = LOWER('Age to Destruction — Ninja') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Bündelt die Luft um den Zauberkundigen zu einem mächtigen unsichtbaren Bolzen — einem konzentrierten Luftstoß von ca. 7,6 cm Durchmesser. Nur verbale Komponente nötig. Unter Wasser besonders wirksam: 1W6 Schaden pro Stufe (max. 10W6 bei Stufe 10), Rettungswurf gegen Zauber für halben Schaden. In der Luft nur halber Würfelschaden (aufgerundet). Funktioniert nicht im Vakuum. Der Zauberkundige pustet einen Luftstoß beim Wirken. Komponente: V.',
  description_en = 'Focuses the air around the caster into a powerful invisible bolt — a concentrated blast of air roughly 7.6 cm in diameter. Only verbal component needed. Particularly effective underwater: 1d6 damage per level (max 10d6 at 10th level), save vs. spell for half. In air, only half the dice damage (round up). Does not work in a vacuum. The caster blows a puff of air when casting. Component: V.'
WHERE LOWER(name_en) = LOWER('Airbolt') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt eine mobile Kugel atembarer Luft (6-m-Radius), identisch mit der Atmosphäre der Heimatwelt des Zauberkundigen. Verdrängt in den ersten drei Runden jede verunreinigte Luft. Der Zauberkundige kann die Kugel mental in jede Richtung bewegen (Bewegungsrate 9, bis 9,1 m pro Stufe). Danach folgt sie der Schwerkraft naher Objekte und ist nicht mehr steuerbar. Oft genutzt, um gestrandeten Wesen im Weltraum Luft zuzuwerfen. Trifft die Kugel im Phlogiston eine feurige Explosion, dehnt sich der Feuerbereich auf die Kugelgrenzen aus und verunreinigt die Luft (+1 Schaden pro Feuerwürfel für Kreaturen darin). Materialkomponente: V, S, M (eine kleine Kristall- oder Glaskugel mit Luft darin; wird beim Wirken zerbrochen).',
  description_en = 'Creates a mobile sphere of breathable air (6 m radius), identical to the caster''s homeworld atmosphere. Displaces fouled air during the first three turns. The caster can mentally move the sphere in any direction (movement rate 9, up to 9.1 m per level). Afterwards it follows gravity of nearby objects and is no longer controllable. Often used to hurl air to a stranded being in space. If the sphere contacts a fiery explosion in the phlogiston, the fire area expands to the sphere limits and fouls the air (+1 damage per fire die for creatures within). Material component: V, S, M (a small crystal or glass sphere holding air; broken during casting).'
WHERE LOWER(name_en) = LOWER('Airsphere') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ruft die Bilder von Abenteurern herbei, die gerade „zwischen Questen" sind. Der Zauberkundige kontrolliert nicht, welche Art von Abenteurern erscheint — sie müssen innerhalb der Reichweite (16,1-km-Radius) sein. Der Zauber hat eine 30%-Fehlschlagchance und zeigt dann entweder nichts oder Szenen von einer völlig anderen Existenzebene. Bei Erfolg wird nur das vage, schattenhafte Bild von ein oder zwei Abenteurern und deren ungefährer Standort angezeigt. Materialkomponente: V, S, M (ein Silberspiegel, eine kleine Glocke und eine Bienenwachskerze; nur der Spiegel bleibt nach dem Wirken erhalten).',
  description_en = 'Calls forth images of adventurers who are "between quests" at the moment. The caster does not control what sort of adventurers appear — they must be within range (16.1 km radius). The spell has a 30% misfire chance, showing either nothing or scenes from another plane entirely. On success, only the vague shadowy image of one or two adventurers and their approximate location is shown. Material component: V, S, M (a silver mirror, a small bell, and a beeswax candle; only the mirror remains after casting).'
WHERE LOWER(name_en) = LOWER('Alahandra''s Questing Call') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt eine kleine Variation in den Wahrscheinlichkeiten. Ein Ereignis, das der Empfänger in der vorherigen Runde versucht hat, wird neu berechnet — neue Würfelwürfe. Nur Ereignisse, die in einer einzelnen Runde beginnen und enden, können betroffen werden. Nur ein Würfelwurf kann wiederholt werden. Bei einem willigen Empfänger wählt der Spieler das bessere Ergebnis (Original oder neu). Bei einem unwilligen Empfänger muss die Aktion wiederholt werden — das zweite Ergebnis gilt in jedem Fall. Typische Einsätze: Kämpfer-Angriffswurf wiederholen, Gegner Rettungswurf wiederholen lassen, Feuerkugel-Schaden neu würfeln. Materialkomponente: V, S, M (ein kleiner, unmarkierter Würfel).',
  description_en = 'Creates a small variation in probabilities. One event attempted by the recipient during the previous round is recalculated — new die rolls. Only events that begin and end in a single round can be affected. Only one die roll can be rerolled. For a willing recipient, the player chooses the better result (original or new). For an unwilling recipient, the action must be redone — the second result stands regardless. Typical uses: reroll a fighter''s attack, force an opponent to reroll a saving throw, reroll fireball damage. Material component: V, S, M (a small, unmarked die).'
WHERE LOWER(name_en) = LOWER('Alternate Reality*') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht einem Mechaniker-Magier, die Funktionsweise eines von einem anderen Magier erschaffenen Uhrwerk-Konstrukts zu ergründen. Pro Runde wird eine zufällige Funktion des Konstrukts enthüllt. Der Zauber zeigt nicht die Stärke einer Funktion, nur dass sie existiert (kein Unterschied zwischen Dolch- und Krummsäbelangriff — beides „Angriffsfunktion"). Implantierte Zauber werden enthüllt, aber nicht welcher Zauber es ist. Kann auch TP, RK und ETW0 des Konstrukts bestimmen (zählen als separate Funktionen). Das Konstrukt muss stationär sein — funktioniert nicht bei feindlicher Aktivität. Nicht-Mechaniker-Magier können den Zauber erlernen, enthüllen aber nur alle zwei Runden eine Funktion. Komponenten: V, S.',
  description_en = 'Allows a mechanician wizard to discern the workings of a clockwork device created by another wizard. Each round reveals one random function of the construct. The spell doesn''t reveal function strength, only that it exists (no difference between dagger and scimitar attack — both are "attack functions"). Implanted spells are revealed but not which spell. Can also determine HP, AC, and THAC0 (each counts as a separate function). The construct must be stationary — does not work during hostile action. Non-mechanician wizards can learn the spell but reveal one function every two rounds. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Analyze Device') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Variante von Tote Beleben, die einen ordnungsgemäß vorbereiteten Zombie pro Stufe des Nekromanten erzeugt. Nur Leichname von Menschen, Halbmenschen und Humanoiden mit 1 TW oder weniger können belebt werden. Ehemalige Erfahrungsstufen werden ignoriert — neue Zombies entsprechen dem Standard. Sie gehorchen verbalen Befehlen und bleiben belebt bis im Kampf zerstört oder von einem Priester vertrieben. Die Magie kann nicht gebannt werden. Vorbereitung: Der Nekromant muss die Leichname mindestens eine volle Runde in einem Bad aus Spezialsalzen einweichen (mind. 200 GM; reicht für bis zu 10 menschengroße Leichname nacheinander). Die Belebung kann innerhalb von 24 Stunden nach der Behandlung erfolgen. Materialkomponente: V, S, M (ein Tropfen Blut und eine Prise Knochenpulver).',
  description_en = 'Variation of Animate Dead that produces one properly prepared zombie per necromancer level. Only bodies of humans, demihumans, and humanoids of 1 HD or less can be animated. Former experience levels are ignored — new zombies are treated as standard. They obey verbal commands and remain animated until destroyed in combat or turned by a priest. The magic cannot be dispelled. Preparation: the necromancer must immerse the corpses in a bath of special salts for at least one full turn (at least 200 gp; accommodates up to 10 man-sized corpses one at a time). Animation can occur within 24 hours of treatment. Material component: V, S, M (a drop of blood and a pinch of bone powder).'
WHERE LOWER(name_en) = LOWER('Animate Zombies') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt die Illusion tausender krabbelnder Spinnen. Nur eine Anzahl Kreaturen gleich der Stufe des Zauberkundigen kann betroffen werden (alle in einer 3-m-Kugel). Jedes Ziel muss einen Rettungswurf gegen Zauber bestehen — Erfolg negiert den Effekt. Bei Misserfolg: zweiter RW — bei Erfolg flieht die Kreatur mit maximaler Bewegungsrate für 2-5 Runden. Bei Misserfolg ist sie so verängstigt, dass sie nichts anderes tun kann als zu versuchen, die Spinnen abzuschütteln, die sie auf ihrem Körper zu spüren glaubt. Die Illusion ist für jedes Individuum anders — die Spinnen nehmen eine Form an, die für das jeweilige Wesen erschreckend ist. Neogi nutzen diesen Zauber, um feindliche Truppen bei Enteraktionen aufzulösen. Komponenten: V, S.',
  description_en = 'Creates the illusion of thousands of crawling spiders. Only a number of creatures equal to the caster''s level can be affected (all within a 3 m sphere). Each target must save vs. spell — success negates. On failure: second save — on success, the creature flees at maximum movement rate for 2-5 rounds. On second failure, it is so frightened it can do nothing but try to remove the spiders it believes are crawling over its body. The illusion is different for each individual — the spiders take a form terrifying to the specific creature. Neogi use this spell to disrupt enemy forces during boarding actions. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Arachnophobia — Neogi') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Chronomant manipuliert die Zeit, sodass der Empfänger mehr aus einer einzelnen Kampfrunde herausholt. Gewährt einen zusätzlichen Nahkampfangriff pro fünf Stufen des Chronomanten (bis zu 4 Angriffe insgesamt). Außerdem −1 auf Initiative, Überraschungswurf und Rüstungsklasse durch die erhöhte Aufmerksamkeit. Nicht kumulativ mit sich selbst oder anderen Zauber, die Extraangriffe gewähren. Erlaubt nicht das Wirken von mehr als einem Zauber pro Runde oder die Nutzung von mehr als einem magischen Gegenstand. Materialkomponente: V, S, M (ein Tropfen Quecksilber).',
  description_en = 'The chronomancer manipulates time so the recipient gets more out of a single combat round. Grants one extra melee attack per five chronomancer levels (up to 4 total attacks). Also −1 adjustment to initiative, surprise roll, and Armor Class due to extra attention. Not cumulative with itself or other spells granting extra attacks. Does not allow casting more than one spell per round or using more than one magical item. Material component: V, S, M (a drop of mercury).'
WHERE LOWER(name_en) = LOWER('Articus''s Melee Manager') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Empfänger erhält 1W8 temporäre Trefferpunkte. Diese zusätzlichen TP können das normale Maximum übersteigen und werden zuerst im Kampf verloren. Sie können nicht durch Heilmagie wiederhergestellt werden. Dieser Zauber wird auch bei der Herstellung eines Tranks des Heldentums verwendet. Materialkomponente: V, S, M (eine kleine Phiole scharfer Kräuter, deren Duft der Empfänger einatmen muss).',
  description_en = 'The recipient gains 1d8 temporary hit points. These additional HP can exceed the character''s normal total and are the first lost in combat. They cannot be regained by curative magic. This spell is also used in creation of a potion of heroism. Material component: V, S, M (a small vial of pungent herbs whose scent the recipient must inhale).'
WHERE LOWER(name_en) = LOWER('Assist — Red Wizards') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht dem Zauberkundigen, feurige Zauberangriffe (Flammen und feurige Explosionen, nicht Hitze allein oder Blitze) an ihre Quelle zurückzuwerfen. Schützt eine einzelne Kreatur (meist den Zauberkundigen). Funktioniert automatisch ohne Konzentration und stört nachfolgendes Zaubern nicht. Reflektiert auch die mächtigsten Zauber wie Meteorschwarm und magische Gegenstandseffekte. Der Empfänger kann nicht wählen, den Schaden zu nehmen und den Schutz aufzusparen. Schützt auch alle brennbaren Gegenstände am Empfänger. Reflektiert alle feurigen Angriffe in einer Runde (z.B. mehrere Feuerkugeln), endet dann. Kann Zauber über große Entfernungen zur Quelle zurücksenden, aber nicht auf andere Ebenen. Hält bis Aktivierung, Magie Bannen, 1 Runde plus 1 Runde/Stufe, Tod oder Ebenenwechsel. Komponente: V.',
  description_en = 'Enables the caster to hurl back fiery spell attacks (flames and fiery explosions, not heat alone or lightning) at their source. Protects a single creature (usually the caster). Functions automatically without concentration and doesn''t disturb subsequent casting. Reflects even the most powerful spells like Meteor Swarm and magical item effects. The recipient cannot choose to take damage and keep the protection. Also protects all flammable items on the creature. Reflects all fiery attacks in a single round (e.g., multiple fireballs), then ends. Can send spells back over vast distances but not across planes. Lasts until activated, Dispel Magic, 1 turn plus 1 turn/level, death, or plane change. Component: V.'
WHERE LOWER(name_en) = LOWER('Backblast — Phaerimm') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht dem Zauberkundigen, bis zu vier leuchtende Blitzkugeln zu erzeugen (jederzeit während der Zauberdauer von 5 Runden/Stufe). Jede Kugel hält max. 4 Runden. Schaden hängt von der Anzahl ab: 4 Kugeln = je 2W4, 3 = je 2W6, 2 = je 5W4, 1 = 4W12. Die Kugeln sind ca. 0,9 m im Durchmesser. Der Zauberkundige kann sie mit Rate 4 bewegen (absorbiert seine Aufmerksamkeit für die Runde). Unkontrollierte Kugeln schweben an Ort und Stelle. Bei Berührung einer Kreatur entlädt sich der Schaden sofort (Rettungswurf gegen Zauber für halben Schaden). Kein Angriffswurf nötig, aber die meisten Kreaturen können einer Kugel durch schnelleres Bewegen ausweichen. Materialkomponente: V, S, M (ein Pulver aus blauen Drachenschuppen).',
  description_en = 'Allows the caster to create up to four glowing lightning spheres (at any time during the spell''s 5 rounds/level duration). Each ball lasts max 4 rounds. Damage depends on number: 4 balls = 2d4 each, 3 = 2d6 each, 2 = 5d4 each, 1 = 4d12. The balls are about 0.9 m in diameter. The caster can move them at rate 4 (absorbs attention for the round). Uncontrolled balls hover in place. On touching a creature, damage discharges immediately (save vs. spell for half). No attack roll needed, but most creatures can avoid a ball by moving faster. Material component: V, S, M (a powder of blue dragon scales).'
WHERE LOWER(name_en) = LOWER('Ball Lightning') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ähnlich dem Blinzeln-Zauber, erfordert aber einen großen Korb oder eine Urne, in die der Zauberkundige vor dem Wirken klettern muss. Nach dem Wirken teleportiert sich der Zauberkundige sofort zu einem zufällig bestimmten anderen Korb innerhalb von 3 m pro Stufe. Etwa eine Runde später „blinkt" der Zauber den Zauberkundigen erneut zu einem anderen Korb in Reichweite — genug Zeit, um hinauszuspähen und zu entscheiden ob es sicher ist. Der Zauber kann jederzeit beendet werden; sonst blinkt der Zauberkundige einmal pro Runde. Alle Materialien im Korb mit dem Zauberkundigen werden mittransportiert. Enthält der Zielkorb andere Materialien, werden diese magisch in den vorherigen Korb transportiert. Komponenten: V, S.',
  description_en = 'Similar to Blink, but requires a large basket or urn the caster must climb into before casting. After casting, the wizard instantly teleports to another randomly determined basket within 3 m per level. About one round later, the spell "blinks" the caster to another basket in range — enough time to peek out and decide if it''s safe. The spell can be ended at will; otherwise the wizard blinks once per round. All materials in the basket are transported with the caster. If the target basket holds other materials, they''re magically transported to the caster''s previous basket. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Basket Trick') AND spell_type = 'wizard';
