-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 2 (Batch 5: 13 Spells — Displace Self to Dust Curtain)
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  description = 'Ahmt die natürliche Fähigkeit der Versetzerbestie nach. Der Zauberkundige scheint etwa 0,6 m von seinem wahren Standort entfernt zu sein. Jede Kreatur, die den Zauberkundigen im Nah- oder Fernkampf angreift, verfehlt automatisch beim ersten Versuch und erleidet −2 auf alle nachfolgenden Angriffswürfe. Der Zauberkundige erhält außerdem +2 auf Rettungswürfe gegen jeden Zauber oder Spezialangriff, der direkt auf ihn gerichtet ist (nicht auf andere oder den Bereich). Nur Wahres Sehen enthüllt den wahren Standort. Materialkomponente: V, M (ein kleiner Papier- oder Lederstreifen, zu einer Schlaufe gedreht).',
  description_en = 'Emulates the natural ability of the displacer beast. The caster appears to be about 0.6 m away from his true location. Any creature making a melee or missile attack automatically misses with its first attempt and suffers −2 on all subsequent attack rolls. The wizard also gains +2 on saving throws against any spell or special attack aimed directly at him (not at others or the area). Only True Seeing reveals the caster''s true location. Material component: V, M (a small strip of paper or leather twisted into a loop).'
WHERE LOWER(name_en) = LOWER('Displace Self') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ähnlich dem Nachrichten-Zauber, ermöglicht aber einem Drachenritter, mit einem Drachen oder einem anderen Drachenritter zu kommunizieren. Der Ritter kann bis zu einen pro Zauberstufe einbeziehen. Die Nachricht reist in gerader Sichtlinie und wird von allen einbezogenen Empfängern innerhalb eines Durchmessers von 9,1 m plus 3 m pro Stufe gehört. Der Ritter muss nicht flüstern — unabhängig von Ton oder Windstärke wird die Nachricht klar gehört. Solange freie Sichtlinie besteht, muss der Ritter nicht auf den Empfänger zeigen. Komponenten: V, S, M.',
  description_en = 'Similar to the Message spell, but enables one dragon knight to communicate with a dragon or another dragon knight. The knight can include up to one per level of spellcasting ability. The message travels in a straight line of sight and is heard by all included within a diameter of 9.1 m plus 3 m per level. The knight need not whisper — regardless of tone or wind volume, the message is clearly heard. As long as there is a clear line of sight, the knight need not point to the recipient. Components: V, S, M.'
WHERE LOWER(name_en) = LOWER('Dragon Message — Dragon Knight') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verleiht der berührten Kreatur eine besondere Form von Glück. Für die Zauberdauer wirkt die Magie so, als hielte der Empfänger einen Glücksstein und nutze dessen magische Effekte. Materialkomponente: V, S, M (Rubinstaub im Wert von 5.000 GM, der über den Kopf der Kreatur gestreut wird; verschwindet nach Ablauf des Zaubers).',
  description_en = 'Bestows upon the touched creature a special form of luck. For the spell duration, the recipient acts as though holding a luckstone and using its magical effects. Material component: V, S, M (5,000 gp worth of ruby dust sprinkled over the creature''s head; vanishes after the spell expires).'
WHERE LOWER(name_en) = LOWER('Drawmij''s Adventurer''s Luck') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verleiht einer oder mehreren Kreaturen in Reichweite (1 pro Stufe) genug Ausdauer, um 5 volle Runden lang den Atem anzuhalten. Betroffene Kreaturen können nicht ertrinken und sind nicht den Effekten eingeatmeter Gase ausgesetzt, solange sie den Atem anhalten. Der Zauber besteht nur aus einem Wort und hat keine somatische oder materielle Komponente — kann daher in Notfällen schnell gewirkt werden. Komponente: V.',
  description_en = 'Endows one or more creatures within range (1 per level) with sufficient endurance to hold their breath for 5 full turns. Affected creatures cannot drown or be subject to inhaled gas effects while holding their breath. The spell is only one word long with no somatic or material components — can be cast quickly in emergencies. Component: V.'
WHERE LOWER(name_en) = LOWER('Drawmij''s Breath of Life') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verbirgt alle Gerüche, die von einer Kreatur ausgehen. Der Empfänger kann nicht durch Geruchssinn aufgespürt werden — weder von Tieren noch von Wesen, die ihre Nase zum Verfolgen nutzen (z.B. Bluthunde). Wird der Zauber auf eine Kreatur gewirkt, die ihren Geruch als Waffe oder Verteidigung nutzt (Stinktier, Troglodyt etc.), wird der Geruch bei missglücktem Rettungswurf gegen Zauber unterdrückt. Maximal 10 Kreaturen können pro Wirken betroffen werden. Materialkomponente: V, S, M (eine geruchlose Blume).',
  description_en = 'Conceals all odors emanating from a creature. The recipient cannot be detected by scent — neither by animals nor beings that use smell to track (e.g., bloodhounds). If cast on a creature that uses odor as weapon or defense (skunk, troglodyte, etc.), the odor is negated on a failed saving throw vs. spell. Maximum 10 creatures can be affected per casting. Material component: V, S, M (a scentless flower).'
WHERE LOWER(name_en) = LOWER('Drawmij''s Scent Mask') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verdoppelt die Bewegungsrate jedes Reittiers, das rennt, schwimmt oder fliegt, für die Zauberdauer. Nach Ablauf ist das Reittier vollständig erschöpft und weigert sich, 24 Stunden lang weiterzubewegen. Erhöht in keiner Weise die Tragfähigkeit — Überladung über das Limit negiert den Zauber automatisch. Kann nicht mit Drawmijs Lasttier kombiniert werden — in diesem Fall werden beide Zauber negiert. Pro 2 Stufen wird 1 Reittier betroffen. Materialkomponente: V, S, M (ein Hasenfuß oder ein Stück Gepardenfell).',
  description_en = 'Doubles the movement rate of any mount that runs, swims, or flies for the spell duration. After expiration, the mount is completely exhausted and refuses to move for 24 hours. Does not increase carrying capacity — overloading beyond the limit automatically negates the spell. Cannot be combined with Drawmij''s Beast of Burden — both spells are negated. 1 mount per 2 levels is affected. Material component: V, S, M (a hare''s foot or a bit of cheetah fur).'
WHERE LOWER(name_en) = LOWER('Drawmij''s Swift Mount') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Zauberkundige muss die verbale Komponente sprechen und das Opfer mit einer 8-10 cm langen Nähnadel stechen (1 Schadenspunkt). Von da an fühlt das Opfer jedes Mal, wenn es den Zauberkundigen eine Stoßbewegung machen sieht, einen erneuten Stich und erleidet 1 TP Schaden. Bei 0 TP fällt das Opfer in Ohnmacht und erwacht nach 1W4 Runden. Nach drei Stichen muss eine Kreatur mit INT 10 oder weniger einen Rettungswurf gegen Zauber bestehen oder gerät in Panik (50% — flieht für 1 Runde) oder Raserei (50% — greift den Zauberkundigen um jeden Preis an, außer bis zum Tod zu kämpfen). Materialkomponente: V, S, M (eine lange Nähnadel).',
  description_en = 'The caster must speak the verbal component and poke the victim with a 8-10 cm sewing needle (1 HP damage). From then on, whenever the creature sees the caster make a thrusting motion, it feels poked again and takes 1 HP damage. At 0 HP, the victim faints and awakens in 1d4 rounds. After three pokes, a creature of INT 10 or less must save vs. spells or be driven to panic (50% — runs for 1 round) or rage (50% — assaults the caster at any cost short of fighting to the death). Material component: V, S, M (a long sewing needle).'
WHERE LOWER(name_en) = LOWER('Drenal''s Annoying Poke') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Lenkt das Ziel von seiner aktuellen Tätigkeit ab, indem seine Aufmerksamkeit auf den Zauberkundigen gerichtet wird. Die Kreatur muss den Zauberkundigen klar sehen können. Kreaturen mit mehr als 6 TW sind immun. Bei missglücktem Rettungswurf gegen Zauber hört das Ziel momentan auf, auf seine Umgebung zu achten — bis zum Ende der Runde nach dem Wirken. In dieser Runde verliert es Initiative, alle Angriffe, GES- und Schildboni auf RK, und kann nicht zaubern oder andere Aktivitäten ausführen, die Denken erfordern. Materialkomponente: V, S, M (ein Stock mit einem bunt gefärbten Tuch oben dran).',
  description_en = 'Distracts the target from what it is doing by focusing its attention on the caster. The creature must be able to clearly see the caster. Creatures with more than 6 HD are immune. On a failed save vs. spell, the target momentarily stops paying attention to its surroundings — until the end of the round after casting. In that round, it loses initiative, all attacks, DEX and shield bonuses to AC, and cannot perform spellcasting or any activity requiring thought. Material component: V, S, M (a stick with a brightly colored piece of cloth on top).'
WHERE LOWER(name_en) = LOWER('Drenal''s Distraction') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verwandelt eine Phiole Tinte in trockene, pulverförmige Form und verzaubert gleichzeitig eine Federfeder, damit sie mit der trockenen Tinte schreiben kann, als wäre sie flüssig. Bei Berührung des Papiers verwandelt sich die Tinte zurück in flüssige Form, verschmiert aber nicht. Nur eine einzelne Tintenphiole und Feder pro Wirken. Verhindert, dass eine zerbrochene oder verschüttete Tintenflasche andere Materialien wie Zauberbücher, Schatzkarten oder Kleidung ruiniert. Materialkomponente: V, S, M (eine Tintenphiole, eine Federfeder und eine Prise gepulverte Kohle).',
  description_en = 'Renders one vial of ink dry (powdery form) and simultaneously enchants a quill pen so it can write with the dry ink as if liquid. When touched to paper, the ink changes back to liquid but won''t smear. Only a single ink vial and quill per casting. Prevents a shattered, broken, or spilled ink bottle from ruining other materials such as spellbooks, treasure maps, clothing, etc. Material component: V, S, M (a vial of ink, a feather quill, and a pinch of powdered coal).'
WHERE LOWER(name_en) = LOWER('Drenal''s Dry Ink') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Wird auf eine offene Flamme (höchstens Fackel- oder sehr kleine Lagerfeuergröße) gewirkt und verwandelt sie in einen orangefarbenen Stein, der Größe und Form der Flamme beim Wirken beibehält. Der Stein bleibt an der Fackel oder dem Boden befestigt. Er strahlt Licht wie eine Flamme aus, erzeugt aber keine Hitze. Am Ende der Dauer kehrt er zur Flamme zurück. Wird der Stein zerbrochen, erlischt die Flamme. Materialkomponente: V, S, M (eine Mischung aus feinem Sand und Zucker).',
  description_en = 'Cast on an open flame (no larger than a torch or very small campfire), it transforms the flame into an orange stone retaining the flame''s size and shape at casting. The stone remains attached to the torch or ground. It illuminates as if it were flame but produces no heat. At the end of the duration, it returns to flame. If the stone is shattered, the flame is extinguished. Material component: V, S, M (a mix of fine sand and sugar).'
WHERE LOWER(name_en) = LOWER('Drenal''s Stone Flame') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Gibt dem Zauberkundigen die unfehlbare Fähigkeit, die Richtung des wahren Nordens zu bestimmen. Der Zauber zeigt den polaren Norden (nicht den magnetischen) an und funktioniert in jeder Umgebung und jedem Setting. Befindet sich der Zauberkundige auf der Südhalbkugel, zeigt der Zauber stattdessen den wahren Süden an — der Zauberkundige spürt, welcher Pol angezeigt wird. Materialkomponente: V, S, M.',
  description_en = 'Provides the caster with an unerring ability to determine true north. The spell indicates polar north (as opposed to magnetic north) and operates in any environment or setting. If the caster is in the southern hemisphere, the spell instead indicates true south — the caster can sense which pole is indicated. Material component: V, S, M.'
WHERE LOWER(name_en) = LOWER('Due North') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt einen kontrollierten Sturm, der Sand und Staub vom Boden aufhebt und in der Luft formt. Der Zauberkundige wählt zwischen zwei Formen: einer Staubwand (zum Verbergen von Verbündeten) oder einer blendenden Staubwolke wie ein Sandsturm (zum Umgeben von Feinden). Die Form kann nach dem Wirken nicht geändert werden. Kreaturen in einer Wolke kämpfen wie in totaler Dunkelheit mit −4 auf Angriffswürfe (Blindkampf-Fertigkeit negiert). Fernkampfwaffen durch Wolke oder Wand erleiden −1. Der Zauberkundige muss sich durchgehend konzentrieren — bei Unterbrechung kollabiert die Staubwand. Kann die Wolke/Wand 9,1 m horizontal und vertikal pro Runde bewegen. Magie Bannen oder jede windkontrollierende Magie lässt den Vorhang einstürzen. Der Zauberkundige kann die Wolke auch in dekorative Formen bringen (Dschinn, Drache, Tentakel etc.), aber die Effekte bleiben gleich. Materialkomponente: V, S, M.',
  description_en = 'Creates a controlled gale that lifts sand and dust from the ground and shapes it in the air. The caster chooses between two forms: a dust wall (to conceal allies) or a blinding dust cloud resembling a sandstorm (to surround foes). The shape cannot be changed after casting. Creatures in a cloud fight as in total darkness with −4 on attack rolls (Blind-Fighting proficiency negates). Missile weapons through cloud or wall suffer −1. The caster must concentrate continuously — if interrupted, the curtain collapses. Can move the cloud/wall 9.1 m horizontally and vertically per round. Dispel Magic or any wind-controlling magic collapses the curtain. The caster can shape the cloud into decorative forms (djinni, dragon, tentacles, etc.), but effects remain the same. Material component: V, S, M.'
WHERE LOWER(name_en) = LOWER('Dust Curtain') AND spell_type = 'wizard';
