-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 2 (Batch 3: 15 Spells — Call Society to Corruption)
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  description = 'Ermöglicht Mitgliedern magischer Gesellschaften, ihre Brüder und Schwestern um Hilfe zu rufen. Der Zauber reist in eine vom Zauberkundigen bestimmte Richtung für eine Anzahl Meilen gleich der halben Stufe. Passiert er innerhalb von 1,6 km ein Mitglied der entsprechenden Gesellschaft, übermittelt er einen Hilferuf. Der Ruf gibt eine grobe Schätzung des Standorts und ein kurzes Bild der Notlage. Erfordert ein kleines Amulett, das die meisten Mitglieder von ihrer Gesellschaft erhalten. Verwendung des Amuletts einer anderen Gesellschaft lässt das Wirken automatisch scheitern. Das Amulett wird nicht verbraucht. Komponenten: V, S, M (Gesellschaftsamulett).',
  description_en = 'Allows members of sorcerous societies to call on their brothers and sisters for help. The spell travels in a direction designated by the caster for a number of miles equal to half the caster''s level. If it passes within 1.6 km of a member of the appropriate society, it delivers a plea for help. The call gives a rough estimate of the caster''s location and a quick image of the trouble. Requires a small amulet that most society members receive. Using an amulet from another society causes automatic failure. The amulet is not consumed. Components: V, S, M (society amulet).'
WHERE LOWER(name_en) = LOWER('Call Society') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht einem Drachen, die Effekte seiner eigenen Furchtaura vorübergehend aufzuheben. Solange der Drache sich konzentriert, erleiden Kreaturen keine Moraleffekte durch den Anblick oder die Anwesenheit des Drachen. Der Zauber endet sobald der Drache die Konzentration beendet, Schaden erleidet oder einen Zauber der 4. Stufe oder höher wirkt. Komponente: V.',
  description_en = 'Enables a dragon to temporarily nullify the effects of its own fear aura. While the dragon concentrates, creatures suffer no morale effects from the sight or presence of the dragon. The spell ends as soon as the dragon ceases concentration, suffers damage, or casts a spell of 4th level or higher. Component: V.'
WHERE LOWER(name_en) = LOWER('Calm — Dragon') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Funktioniert nur in der Wildnis. Ermöglicht dem Zauberkundigen, 1 Person pro Stufe sofort und vollständig zu verbergen — selbst gegen gründliche Durchsuchung geschützt. Der Zauber ändert Färbung und Schattierung der Betroffenen, um sich der natürlichen Umgebung anzupassen. Wirksam gegen Infrasicht und Ultrasicht. Verborgene Personen behalten alle Fähigkeiten und können die Tarnung jederzeit verlassen. Langsame Bewegung (bis 3 m pro Runde) ist möglich; schnellere Bewegung beendet den Zauber. Wie bei Unsichtbarkeit: Bei einem Angriff erhalten die Verborgenen Überraschungsbonus, Initiative und +4 auf den Angriffswurf, aber der Zauber bricht sofort. Nicht aufzuspüren außer durch Magie oder durch unvorsichtige Bewegung. Materialkomponente: S, M (eine Mistelbeere).',
  description_en = 'Only functions in wilderness settings. Allows the wizard to instantly and completely hide 1 person per level — concealed against even thorough searches. The spell changes coloring and shadowing of affected individuals to blend with natural surroundings. Effective against infravision and ultravision. Concealed individuals retain all faculties and can emerge at any time. Slow movement (up to 3 m per round) is possible; moving faster dissipates the spell. As with Invisibility: if attacking, concealed individuals gain surprise bonus, initiative, and +4 to hit, but the spell breaks immediately. Undetectable except by magic or careless movement. Material component: S, M (a mistletoe berry).'
WHERE LOWER(name_en) = LOWER('Camouflage — Elf') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Schützt einen Wildzauberer vor den Auswirkungen wilder Fluktuationen. Nur gegen wilde Fluktuationen durch eigene Zauber, nicht durch die eines anderen Zauberers. Tritt eine Fluktuation ein, erhält der geschützte Zauberkundige einen Rettungswurf gegen Zauber. Bei Erfolg wird der Fluktuationseffekt auf den Zauberkundigen negiert. Bei Misserfolg ist er normal betroffen. Schützt nicht gegen wilde Fluktuationen, die durch das eigene Wirken ausgelöst werden könnten. Schützt nur den Zauberkundigen — andere im Wirkungsbereich werden normal betroffen. Der Zauberkundige kann den Schutz nicht freiwillig aufheben; das Chaosschild schützt vor guten UND schädlichen Effekten. Bleibt aktiv bis eine Fluktuation negiert wird oder die Dauer abläuft. Komponenten: V, S.',
  description_en = 'Protects a wild mage against the effects of wild surges. Only against surges caused by the caster''s own spells, not another mage''s. When a surge occurs, the protected caster gets a saving throw vs. spell. On success, the surge effect on the caster is negated. On failure, the caster is affected normally. Does not protect against surges caused by its own casting. Protects only the caster — others in the area of effect are affected normally. The caster cannot voluntarily cancel the protection; it protects from both good AND harmful effects. Remains active until it negates a surge or the duration expires. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Chaos Shield*') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Wie der gleichnamige Magier-Zauber der 2. Stufe Charm Man I, aber mächtiger. Betrifft bis zu 3W4 Männer der 5. Stufe oder weniger in einem 6-m-Radius. „Mann" ist definiert als jeder männliche Mensch, Halbmensch oder Humanoide der Größe L oder kleiner mit 5 TW oder weniger. Bei einem CHR-Vergleich zwischen dem Anführer der Gruppe und dem Zauberkundigen kann der Zauber aufgehoben werden (Anführer-CHA + 1W8 muss 8 Punkte über dem CHA des Zauberkundigen liegen). Rettungswurf gegen Zauber negiert für einzelne Betroffene. Dauer 2W4 Runden. Komponenten: V, S.',
  description_en = 'Like the 1st-level Charm Man I spell, but more powerful. Affects up to 3d4 men of 5th level or less in a 6 m radius. "Man" is defined as any male human, demihuman, or humanoid of size L or less with 5 HD or less. A group leader can negate the charm if the leader''s CHA plus 1d8 is 8 or more points higher than the caster''s CHA. Saving throw vs. spell negates for individual targets. Duration 2d4 rounds. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Charm Man IT') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt ein Paar scheinbar körperloser Hände, die sich um den Hals des Opfers klammern, wenn dieses seinen Rettungswurf gegen Zauber nicht besteht. Das Opfer erleidet 1W4 Schaden pro Runde, die durch Rüstung nicht reduziert werden kann. Kann nicht durch physische Kraft entfernt werden. Der Zauber erfordert Konzentration des Zauberkundigen — wenn unterbrochen, löst sich der Würgegriff. Das Opfer kann versuchen, den Zauber durch eigene Magie oder durch Magie Bannen zu brechen. Komponenten: V, S.',
  description_en = 'Creates a pair of seemingly disembodied hands that clamp around the victim''s throat if they fail a saving throw vs. spell. The victim takes 1d4 damage per round that cannot be reduced by armor. Cannot be removed by physical force. The spell requires the caster''s concentration — if interrupted, the choke releases. The victim can attempt to break the spell through its own magic or Dispel Magic. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Choke') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt einen Kreis aus Flammen von 1,5 m Durchmesser um den Zauberkundigen. Die Flammen sind 0,6 m hoch und verursachen 2W4 Feuerschaden an jeder Kreatur, die versucht hindurchzugehen. Die Flammen bewegen sich mit dem Zauberkundigen. Der Zauberkundige kann durch die Flammen hindurchsehen, aber andere können nicht hindurchsehen. Brennbare Materialien, die die Flammen berühren, fangen sofort Feuer. Der Kreis bietet keinen Schutz gegen Fernkampfangriffe oder Zauber. Komponenten: V, S, M.',
  description_en = 'Creates a circle of flames 1.5 m in diameter around the caster. The flames are 0.6 m high and deal 2d4 fire damage to any creature attempting to pass through. The flames move with the caster. The caster can see through the flames, but others cannot see through them. Flammable materials touching the flames ignite immediately. The circle provides no protection against ranged attacks or spells. Components: V, S, M.'
WHERE LOWER(name_en) = LOWER('Circle of Flame') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Hüllt den Zauberkundigen in eine Aura, die ihn vor Entdeckung durch Untote schützt. Untote ignorieren den Zauberkundigen, als wäre er nicht vorhanden, solange er keine aggressiven Handlungen gegen sie unternimmt. Intelligente Untote (Vampire, Liches etc.) erhalten einen Rettungswurf gegen Zauber, um den Schutz zu durchschauen. Nichtintelligente Untote (Skelette, Zombies) erhalten keinen Rettungswurf. Der Zauber wird sofort gebrochen, wenn der Zauberkundige einen Untoten angreift, einen Zauber auf Untote wirkt oder Untote vertreiben versucht. Komponenten: V, S.',
  description_en = 'Cloaks the caster in an aura that protects from detection by undead. Undead ignore the caster as if not present, as long as the caster takes no aggressive actions against them. Intelligent undead (vampires, liches, etc.) get a saving throw vs. spell to see through the protection. Nonintelligent undead (skeletons, zombies) get no saving throw. The spell is immediately broken if the caster attacks an undead, casts a spell on undead, or attempts to turn undead. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Cloak From Undead') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Hüllt einen einzelnen Untoten in eine Aura, die ihn als lebendes Wesen erscheinen lässt. Priester können den getarnten Untoten nicht mit Untote Vertreiben aufspüren. Magie Entdecken enthüllt die Aura, aber nicht die untote Natur. Wahres Sehen oder Wahre Sicht durchschaut die Tarnung vollständig. Der Untote behält alle seine Fähigkeiten, sieht aber aus wie ein normales, lebendes Wesen seiner ungefähren Größe und Art. Der Zauber erfordert die Kooperation des Untoten (kann nicht auf unwillige Untote gewirkt werden). Materialkomponente: V, S, M.',
  description_en = 'Cloaks a single undead creature in an aura that makes it appear as a living being. Priests cannot detect the cloaked undead with Turn Undead. Detect Magic reveals the aura but not the undead nature. True Seeing or True Sight penetrates the disguise completely. The undead retains all abilities but looks like a normal living being of its approximate size and type. The spell requires the undead''s cooperation (cannot be cast on unwilling undead). Material component: V, S, M.'
WHERE LOWER(name_en) = LOWER('Cloak Undead') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Lässt eine Kreatur innerhalb von 1,5 m spontan in Flammen aufgehen. Verursacht 1W4 Feuerschaden pro Stufe des Zauberkundigen (max. 10W4). Die Kreatur erhält keinen Rettungswurf, aber Feuerresistenz und -immunität gelten normal. Brennbare Kleidung und Gegenstände müssen einen Rettungswurf gegen magisches Feuer bestehen oder fangen ebenfalls Feuer. Das Feuer erlischt am Ende der Runde, in der der Zauber gewirkt wurde, aber bereits entzündete Gegenstände brennen normal weiter. Hat keine Wirkung auf feuerimmune Kreaturen. Komponenten: V, S.',
  description_en = 'Causes a creature within 1.5 m to spontaneously burst into flames. Deals 1d4 fire damage per caster level (max 10d4). The creature gets no saving throw, but fire resistance and immunity apply normally. Flammable clothing and items must save vs. magical fire or also catch fire. The fire extinguishes at the end of the round the spell was cast, but already ignited items continue burning normally. Has no effect on fire-immune creatures. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Combust —Red Wizard') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Bringt den Geist des Zauberkundigen (oder einer berührten Kreatur) in einen Zustand tiefer Gelassenheit und Konzentration. Für die Zauberdauer erhält der Empfänger +2 auf alle Konzentrationswürfe, Rettungswürfe gegen Verzauberungs-/Beherrschungs-Zauber und mentale Widerstände. Furcht und Panik werden unterdrückt. Kann nicht zusammen mit Rage oder ähnlichen aufputschenden Effekten verwendet werden. Komponenten: V, S.',
  description_en = 'Brings the caster''s mind (or that of a touched creature) into a state of deep calm and concentration. For the spell duration, the recipient gains +2 on all concentration checks, saving throws vs. enchantment/charm spells, and mental resistances. Fear and panic are suppressed. Cannot be used together with rage or similar stimulating effects. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Compose Mind') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Lässt nichtlebende organische Materie (Holz, Leder, Stoff, Nahrung) schnell verfallen und verrotten. Ein Gegenstand von bis zu 0,3 m³ pro Stufe wird betroffen. Holz wird morsch, Leder brüchig, Stoff zerfällt, Nahrung verdirbt. Der Verfall dauert 1 Runde und ist danach permanent. Magische Gegenstände erhalten einen Rettungswurf gegen Säure (mit dem magischen Bonus als Modifikator). Kann nicht auf lebende Kreaturen oder Pflanzen gewirkt werden. Untote, die aus organischem Material bestehen (Zombies), erleiden 2W6 Schaden (Rettungswurf gegen Zauber für halben Schaden). Materialkomponente: V, S, M.',
  description_en = 'Causes nonliving organic matter (wood, leather, cloth, food) to rapidly decay and rot. Up to 0.3 m³ of material per level is affected. Wood becomes rotten, leather brittle, cloth disintegrates, food spoils. The decay takes 1 round and is permanent thereafter. Magical items get a saving throw vs. acid (with magical bonus as modifier). Cannot be cast on living creatures or plants. Undead consisting of organic material (zombies) take 2d6 damage (save vs. spell for half). Material component: V, S, M.'
WHERE LOWER(name_en) = LOWER('Corruption') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt einen unsichtbaren Doppelgänger des Zauberkundigen an einem vom Zauberkundigen gewählten Punkt innerhalb der Reichweite. Dieser Schadenspiegel ist an den Zauberkundigen gebunden: Jeder physische Schaden, den der Zauberkundige erleidet, wird gleichzeitig auch dem nächsten Feind innerhalb von 3 m um den Spiegel zugefügt. Der reflektierte Schaden ist vom gleichen Typ wie der erlittene. Magischer Schaden wird nicht reflektiert. Der Spiegel kann durch Magie Bannen aufgelöst werden. Materialkomponente: V, S, M.',
  description_en = 'Creates an invisible double of the caster at a point chosen within range. This damage mirror is linked to the caster: any physical damage the caster suffers is simultaneously dealt to the nearest enemy within 3 m of the mirror. The reflected damage is of the same type as the damage taken. Magical damage is not reflected. The mirror can be dispelled by Dispel Magic. Material component: V, S, M.'
WHERE LOWER(name_en) = LOWER('Damage Mirror — Old Empire') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Lässt vorhandene Schatten in einem Bereich tanzen, sich bewegen und in bedrohlicher Weise verzerren. Kreaturen im Wirkungsbereich erleiden −1 auf Angriffswürfe und Rettungswürfe durch die ablenkenden, beunruhigenden Schatten. Kreaturen mit 1 TW oder weniger müssen einen Moralwurf bestehen oder fliehen. Die tanzenden Schatten bieten tatsächliche Tarnung: Kreaturen, die sich im Bereich verbergen, erhalten +10% auf ihre Chance sich im Schatten zu verbergen. Der Zauberkundige ist nicht betroffen. Erfordert vorhandene Schatten — funktioniert nicht bei hellem, schattenlosem Licht. Komponenten: V, S.',
  description_en = 'Causes existing shadows in an area to dance, move, and distort in a threatening manner. Creatures in the area of effect suffer −1 on attack rolls and saving throws due to the distracting, unsettling shadows. Creatures with 1 HD or less must make a morale check or flee. The dancing shadows provide actual concealment: creatures hiding in the area gain +10% to hide in shadows. The caster is not affected. Requires existing shadows — does not work in bright, shadowless light. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Dancing Shadows') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt einen dunklen, nichtreflektierenden Spiegel in der Luft (bis zu 1,5 m × 1,5 m). Der Spiegel absorbiert Licht — alles was sich darin spiegeln würde, erscheint als tiefe Schwärze. Kann als Blickfalle dienen: Kreaturen die direkt hineinschauen müssen einen Rettungswurf gegen Zauber bestehen oder sind für 1W4 Runden fasziniert (können nichts anderes tun als in den Spiegel starren). Der Spiegel blockiert keine Zauber oder physischen Angriffe. Kann durch physischen Kontakt zerbrochen werden (RK 8, 5 TP). Materialkomponente: V, S, M.',
  description_en = 'Creates a dark, non-reflective mirror in the air (up to 1.5 m × 1.5 m). The mirror absorbs light — anything that would be reflected appears as deep blackness. Can serve as a gaze trap: creatures looking directly into it must save vs. spell or be fascinated for 1d4 rounds (unable to do anything but stare). The mirror does not block spells or physical attacks. Can be broken by physical contact (AC 8, 5 HP). Material component: V, S, M.'
WHERE LOWER(name_en) = LOWER('Dark Mirror') AND spell_type = 'wizard';
