-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 1 (Batch 4: 12 Spells — Detect Secret Passages to Drowsy Insects)
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  description = 'Ermöglicht dem Zauberkundigen, Geheimtüren, versteckte Fächer, Caches und ähnliche Vorrichtungen aufzuspüren. Nur absichtlich verborgene Durchgänge, Türen oder Öffnungen werden erkannt — eine Falltür unter Kisten oder eine illusionäre Wand ja, ein Amulett in einem unordentlichen Raum nein. Der Zauberkundige durchsucht einen Bereich von 3 m² pro Stufe. Erkannte Türen oder Öffnungen leuchten für eine volle Runde schwach. Der Zauber findet möglicherweise keine versteckten Fächer, die vollständig von einem anderen Objekt verdeckt werden. Er erkennt nur die Tür/Öffnung — der Zauberkundige muss separat nach dem Mechanismus suchen. Komponenten: V, S.',
  description_en = 'Enables the wizard to detect secret doors, compartments, caches, and similar devices. Only deliberately hidden passages, doors, or openings are detected — a trap door under crates or an illusionary wall yes, an amulet in a cluttered room no. The wizard affects an area of 3 m² per level. Any detected doorways or openings glow softly for one full turn. The spell may not find a secret compartment if it is completely covered by another object. It only detects the doorway/opening — the wizard must separately search for the mechanism. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Detect Secret Passages and Portals') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Chronomant wird auf Turbulenzen im Zeitstrom aufmerksam. Er kann pro Runde einen 90°×90°-Bereich (ein Achtel einer Kugel) abtasten. Nach dem Auffinden einer Anomalie kann deren Schwere durch eine weitere Runde Konzentration bestimmt werden. Der Zauberkundige hat eine 5%-Chance pro Stufe, die Ursache zu erkennen. Auf der Halbebene der Zeit ist Entfernung kein Faktor und der Zauber erkennt die nächste Turbulenz in jeder abgetasteten Richtung. Auf der Materiellen Ebene beträgt die Reichweite 27,4 m pro Stufe. In beiden Fällen ist auch Sicht ein begrenzender Faktor. Komponenten: V, S.',
  description_en = 'The chronomancer is attuned to turbulence in the timestream. He can scan a 90° × 90° area (one-eighth of a sphere) every round. After locating an anomaly, its severity can be determined by another round of concentration. The wizard has a 5% chance per level to recognize the cause. On the Demiplane of Time, distance is not a factor and the spell detects the nearest turbulence in any scanned direction. On the Prime Material, range is 27.4 m per level. In either case, line of sight is also a limiting factor. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Detect Temporal Anomaly') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Zauberkundige berührt ein Wesen, das betäubt, betrunken, bewusstlos oder schlafend ist, spricht die verbale Komponente und läutet eine kleine Silber- oder Messingglocke. Das Ziel erhält einen Rettungswurf gegen Zauber mit −2 Abzug; bei Misserfolg beginnt es zu sprechen — zufällig, in allen bekannten Sprachen, über zufällige, zusammenhanglose Themen. Es kann keine Fragen hören und kann nicht durch mentale oder magische Kontrolle zu bestimmten Antworten gezwungen werden. Pro Runde besteht eine kumulative 25%-Chance, dass es nützliche Informationen preisgibt: Namen (nicht wahre Namen), Passwörter, Aktivierungswörter, Codes, Wegbeschreibungen etc. Der Sprecher identifiziert solche Fragmente selten als das, was sie sind. Wird das Ziel geweckt, endet der Zauber. Materialkomponente: V, S, M (eine kleine Silber- oder Messingglocke).',
  description_en = 'The caster touches a being that is drugged, drunk, unconscious, or sleeping, speaks the verbal component and rings a small silver or brass bell. The target receives a saving throw vs. spell at −2; on failure, it begins to speak — randomly, in all languages known, on random rambling topics. It cannot hear questions and cannot be forced by mental or magical control to give specific answers. Each round there is a noncumulative 25% chance of revealing useful information: names (not true names), passwords, activation words, codes, directions, etc. The speaker rarely identifies such fragments for what they truly are. If the affected person is awakened, the spell breaks. Material component: V, S, M (a small silver or brass bell).'
WHERE LOWER(name_en) = LOWER('Detho''s Delirium') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Beschwört einen kleinen telekinetischen Stoß, der eine Person dazu zwingt, alle in den Händen gehaltenen Waffen oder Gegenstände fallenzulassen. Der Stoß hat genug Kraft, um die Gegenstände 1W6 × 0,3 m vom ehemaligen Träger weg zu bewegen, sodass eine Runde zum Aufheben benötigt wird. Betrifft nur handgehaltene Gegenstände, nicht Ringe, Gürtel oder andere getragene (nicht in den Händen gehaltene) Objekte. Komponenten: V, S.',
  description_en = 'Summons minor telekinetic bursts that cause a person to drop any hand-held weapons or items. The bursts have enough force to move the items 1d6 × 0.3 m away from the former wielder, forcing the person to spend a round retrieving them. Only affects hand-held items, not rings, belts, or other worn (not hand-carried) items. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Disarm') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verbirgt das allgemeine Erscheinungsbild des Zauberkundigen (kann nicht auf andere gewirkt werden). Verleiht keine Sprachfähigkeiten und kann die Körpergröße nicht drastisch verändern. Eine Verkleidung pro Wirken. Wählt der Zauberkundige ein allgemeines Individuum gleicher Rasse und Geschlechts, ist er für alle, die ihm begegnen, unerkennbar — er sieht einfach aus wie jemand, den sie nie gesehen haben. Versucht er dagegen, eine bestimmte Person nachzuahmen, erhalten Bekannte dieser Person einen Rettungswurf gegen Zauber mit je +1 für: Wechsel der Rasse, Wechsel des Geschlechts, oder wenn der Zauberkundige sich mit dem Prüfenden unterhält. Materialkomponente: V, S, M (die getrocknete Haut eines Chamäleons).',
  description_en = 'Conceals the caster''s general appearance (cannot be cast on others). Conveys no language capability and cannot dramatically alter size. One disguise per casting. If the caster specifies a general individual of the same race and sex, he is unrecognizable — simply looks like someone they''ve never seen. If attempting to create a specific individual''s appearance, acquaintances get a saving throw vs. spell with +1 for each: change of race, change of sex, or if the caster is in conversation with the person making the save. Material component: V, S, M (the dried skin of a chameleon).'
WHERE LOWER(name_en) = LOWER('Disguise — Hishna') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verändert die Art eines beliebigen Geräuschs, dessen Quelle innerhalb von 1,5 m liegt. Die Lautstärke bleibt gleich, aber Resonanz, Timbre, Tonhöhe oder Klangfarbe können verändert werden — z.B. summender Klang, Echo-Effekt, Unterwasser-Klang, oder Tonhöhenänderung. Durch mentalen Befehl legt der Zauberkundige Art und Ausmaß der Verzerrung fest; diese bleibt konstant, bis er sie aktiv ändert. Jede Verzerrung, die der Zauberkundige sich mental vorstellen kann, kann auferlegt werden. Kann nach Ermessen des SL den Rettungswurf eines schallbasierten Angriffs anpassen. Komponenten: V, S.',
  description_en = 'Alters the nature of any sound whose source is within 1.5 m. The volume remains the same, but resonance, timbre, pitch, or tone can be changed — e.g., buzzing quality, echo effect, underwater tonation, or pitch change. By mental command the caster sets the type and amount of distortion, which remains constant until actively changed. Any distortion the caster can mentally hear can be imposed. May, at the DM''s option, adjust the saving throw of a sound-based attack. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Distort') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verzaubert den Zweig eines Ginkgo- oder Obstbaums, um einen gewöhnlichen verborgenen Gegenstand aufzuspüren. Anders als Objekt Lokalisieren braucht der Zauberkundige kein konkretes mentales Bild — er benennt nur die allgemeine Art des Gesuchten (vergrabener Schatz, essbare Pflanzen, Frischwasser etc.). Findet keine unsichtbaren, magischen oder durch Objekt Verdunkeln geschützten Gegenstände. Der Zauberkundige hält den Y-förmigen Zweig mit beiden Händen. Ist das gesuchte Objekt innerhalb von 54,9 m, zeigt der Zweig in dessen Richtung und zieht den Zauberkundigen sanft dorthin. Wird durch kein Material blockiert. Bei einem undurchdringlichen Hindernis (Boden, Wand) drückt der Zweig dagegen und stoppt. Materialkomponente: V, S, M (ein Y-förmiger Zweig eines Ginkgo- oder Obstbaums).',
  description_en = 'Enchants the branch of a ginkgo or fruit tree to locate a common hidden item. Unlike Locate Object, the caster needs no specific mental image — he only names the general type of item sought (buried treasure, edible plants, fresh water, etc.). Does not find invisible, magical, or Obscure Item-protected items. The caster holds the Y-shaped branch with both hands. If the desired item is within 54.9 m, the enchanted branch points in its direction and gently pulls the caster along. Not blocked by any material. At an impenetrable obstacle (ground, wall), the branch presses against it and stops. Material component: V, S, M (a Y-shaped branch from a ginkgo or fruit tree).'
WHERE LOWER(name_en) = LOWER('Divining Rod') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt einen transparenten Helm aus psionischer Energie um den Kopf des Empfängers. Der Helm gewährt einen Rettungswurf gegen Zauber gegen alle psionischen Angriffe sowie alle psionischen Hingaben und Wissenschaften, die mentale Beeinflussung oder Kontrolle erlauben. Bietet keinen Schutz gegen Zauber. Der Zauber scheitert, wenn der Empfänger eine Kopfbedeckung trägt; ebenso wirkt der Zauber nicht, solange eine Kopfbedeckung getragen wird. Wenn die geschützte Kreatur aus anderem Grund einen Rettungswurf gegen eine psionische Fähigkeit erhielte, kann sie die vorteilhaftere Verteidigung nutzen. Komponenten: V, S.',
  description_en = 'Creates a transparent helm of psionic energy about the recipient''s head. The helm grants a saving throw vs. spell against all psionic attacks, as well as any psionic devotions or sciences that allow mental influence or control. Provides no protection against spells. The spell fails if the recipient is wearing any head covering; likewise, the spell does not work while any head covering is worn. If the protected creature would be allowed a save against a psionic ability for any other reason, it can use the most advantageous defense. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Dolent''s Helm') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verleiht die gleichen allgemeinen Sprachfähigkeiten wie der Sprachen-Zauber der 3. Stufe, beschränkt sich aber ausschließlich auf die von Drachen gesprochenen Sprachen. Komponenten: V, M.',
  description_en = 'Bestows the same general language abilities as the 3rd-level Tongues spell, but gives only knowledge of languages spoken by dragons. Components: V, M.'
WHERE LOWER(name_en) = LOWER('Dragon Tongues — Dragon Knight') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Halbiert die effektive Belastung aller Gegenstände auf einem einzelnen Reittier (einschließlich Reiter), verdoppelt damit effektiv die Tragfähigkeit des Tieres. Endet der Zauber plötzlich bei einem Reittier, das das Eineinhalbfache seiner maximalen Last trägt, kann es nicht laufen, sinkt langsam zu Boden und hat eine 50%-Chance lahm zu werden. Ein Reittier, das plötzlich die doppelte Maximallast ohne den Zauber trägt, bricht zu Boden zusammen, erleidet 1W6 Schaden und wird automatisch lahm. Materialkomponente: V, S, M (ein Magnetstein und eine Prise Metallspäne).',
  description_en = 'Halves the effective encumbrance of all objects on a single mount (including riders), effectively doubling the mount''s carrying capacity. If the spell ends suddenly on a mount carrying one-and-a-half times its maximum load, it cannot walk, slowly sinks to the ground, and has a 50% chance of going lame. A mount suddenly burdened by twice its maximum load collapses, suffering 1d6 damage and automatically going lame. Material component: V, S, M (a lodestone and pinch of metal filings).'
WHERE LOWER(name_en) = LOWER('Drawmij''s Beast of Burden') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verleiht einer Kreatur eine sehr begrenzte Form der Levitation. Die Kreatur läuft normal über jede Oberfläche, hinterlässt aber keine Spuren. Bei Rennen oder Ansturm endet der Zauber sofort. Die Kreatur kann auch über Flüssigkeiten laufen (mit halber normaler Gehgeschwindigkeit und vorsichtigen Schritten), nicht jedoch über turbulentes Wasser oder Ozeanwellen. Löst keine Fallgruben aus. Ermöglicht weder höheres Springen noch sicheres Herabspringen von Klippen — nur leichteres Gehen. Erhöht die Bewegungsrate der Kreatur für die Zauberdauer um 50%. Materialkomponente: V, S, M (ein Stück Fell von einer Katzenpfote und eine Entenfeder).',
  description_en = 'Gives a creature a very limited form of levitation. The creature walks normally over any surface but leaves no tracks. If the creature breaks into a charge or run, the spell ends immediately. The creature can also walk across fluids at half normal walking rate (must step carefully), but not across turbulent water or ocean waves. Cannot trigger pit traps. Does not enable higher jumping or safe falling from cliffs — only a lighter step. Increases the creature''s movement rate by 50% for the spell duration. Material component: V, S, M (a bit of fur from a cat''s paw and a duck''s feather).'
WHERE LOWER(name_en) = LOWER('Drawmij''s Light Step') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Beschwört eine kleine Wolke stechender und beißender Insekten an einem beliebigen Punkt innerhalb der Reichweite. Die Insekten schwärmen um alle im Wirkungsbereich, es sei denn die Opfer sind durch Feuer, Kälte oder Rauch geschützt. Die Stiche verursachen keinen Schaden und sind kaum zu spüren, aber alle Betroffenen müssen einen Rettungswurf gegen Gift bestehen. Bei Misserfolg fällt die Kreatur sofort in einen leichten Schlummer für 2W6 Runden (oder bis geweckt). Das Opfer erwacht durch Schütteln, Schläge oder sonstige Störung. Laute Geräusche wie Kampf haben eine 50%-Chance aufzuwecken; in sein Ohr schreien weckt mit Sicherheit. Materialkomponente: V, S, M (eine lebende Honigbiene oder ein stechendes Insekt).',
  description_en = 'Summons a small cloud of stinging and biting insects anywhere within spell range. The insects swarm around all in the area of effect unless victims are protected by fire, cold, or smoke. The stings cause no damage and are barely felt, but all swarmed creatures must save vs. poison. On failure, the creature instantly falls into a light slumber for 2d6 rounds (or until awakened). The victim wakes when shaken, struck, or otherwise disturbed. Loud noises such as fighting have a 50% chance of awakening; shouting in the ear certainly will. Material component: V, S, M (a live honeybee or stinging insect).'
WHERE LOWER(name_en) = LOWER('Drowsy Insects') AND spell_type = 'wizard';
