-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 1 (Batch 3: 15 Spells — Color to Detect Metals)
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  description = 'Ermöglicht eine permanente Farbänderung an Stoff, Leder oder ähnlichen Materialien. Mit einer Geste kann der Zauberkundige ein ganzes Stück sofort in einen einzelnen Farbton ändern. Für mehrere Farben muss er mit den Fingern die gewünschten Bereiche nachzeichnen und sich die Farbe vorstellen — die Änderung erfolgt entsprechend. Jeder Farbton kann erzeugt werden, einschließlich metallischer Töne, die jedoch nicht aus echten Edelmetallen bestehen. Alle Farbänderungen müssen innerhalb von zwei Stunden (maximale Wirkzeit) erfolgen. Der Effekt ist permanent bis gebannt. Komponenten: V, S, M.',
  description_en = 'Allows a permanent color change in cloth, leather, or similar substances. With a gesture, the caster can instantly change an entire piece to a single hue. For multiple colors, the caster must trace with his fingers the desired areas and picture the hue — the color changes accordingly. Any color or shade can be created, including metallic tints, though these cannot actually consist of precious metals. All color changes must be made within two hours (maximum casting time). The effect is permanent until dispelled. Components: V, S, M.'
WHERE LOWER(name_en) = LOWER('Color') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Macht den Empfänger farbenblind — alle Sicht ist in Schwarz-Weiß. Misslingt der Rettungswurf gegen Zauber, kann nur Magie Bannen oder Illusion Bannen den Effekt vor Ablauf entfernen; die verschiedenen Heilzauber heben den Effekt ebenfalls auf. Negative Effekte: Edelsteine, Bestien, Tränke, Banner und Pflanzen, die durch Farbe unterschieden werden, können nicht mehr identifiziert werden. Positive Effekte: +2 (oder +10%) Bonus beim Aufspüren getarnter Objekte, −2 (oder −10%) Abzug für Personen, die sich vor dem Farbenblinden im Schatten verbergen. Der farbenblinde Charakter erhält +1 auf seinen Überraschungswurf gegen getarnte oder im Schatten verborgene Gegner. Komponente: V.',
  description_en = 'Makes the recipient unable to distinguish colors — all vision is in black and white. If the saving throw vs. spell fails, only Dispel Magic or Dispel Illusion can remove the defect before expiration; the various cure spells also remove the effect. Negative effects: Gems, beasts, potions, banners, and plants distinguished by color cannot be identified. Positive effects: +2 (or +10%) bonus to locate camouflaged objects, −2 (or −10%) penalty for persons hiding in shadows from the colorblind individual. The colorblind character gets +1 to surprise roll against camouflaged or shadow-hiding opponents. Component: V.'
WHERE LOWER(name_en) = LOWER('Color Blindness') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht dem Zauberkundigen, Untote genau wie ein böser Priester gleicher Stufe zu befehligen. Der Zauberkundige kann dieselbe Anzahl und Art befehligen und benötigt denselben Wurf auf der Untote-Vertreiben-Tabelle. Nur ein Befehlsversuch pro Begegnung während der Zauberdauer — bei Erfolg kontrolliert er 2W6 Untote; misslingt der Versuch, kann er es nicht erneut versuchen. Komponenten: V, S.',
  description_en = 'Allows the wizard to command undead creatures exactly as an evil priest of the same level. The caster can control the same number and type, using the same roll on the Turn Undead table. Only one command check per encounter during the spell''s duration — if successful, he controls 2d6 undead; if the attempt fails, he cannot try again. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Command Undead') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erfordert eine Messingschale mit Wasser, einen Korkkreis darauf schwimmend, und eine lange Eisennadel mit rot bemaltem Ende auf dem Kork. Bei Wirkung bleibt der Kork zentriert und dreht sich, bis die Nadel in die vom Zauberkundigen definierte Richtung zeigt. Dies kann eine Himmelsrichtung sein oder abstrakter — z.B. immer zum Heimathafen oder zum Ziel zeigen. Der Zauberkundige kann nur eine vertraute Richtung wählen (ein Ort den er gesehen hat oder dessen Richtung er kennt). Bei ruhigem Wetter leicht abzulesen; bei rauer See erfordert das Ablesen einen INT-Wurf — bei Misserfolg weicht die Ablesung um 20°–180° ab. Wird alles Wasser entfernt oder der Kork herausgenommen, wird der Zauber gebrochen. Materialkomponente: V, S, M (Messingschale, Wasser, Kork, Eisennadel).',
  description_en = 'Requires a brass bowl filled with water, a circle of cork floating in it, and a long iron needle painted red on the pointing end atop the cork. When cast, the cork stays centered and rotates until the pointer aims in the direction defined by the caster. This can be a map direction or more abstract — always pointing to home port or destination, for example. The caster can only choose a familiar direction (a place he has seen or a direction he is certain of). In calm weather easy to read; in rough waters, reading requires an INT check — on failure, the reading is off by 20°–180°. If all water is drained or the cork removed, the spell is broken. Material component: V, S, M (brass bowl, water, cork, iron needle).'
WHERE LOWER(name_en) = LOWER('Compass') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Kann auf zwei Arten gewirkt werden: (1) Die Bewegung einer Menge Gas oder Dampf kontrollieren — die Wolke kann mit Bewegungsrate 6 innerhalb des Wirkungsbereichs gelenkt werden. Der Zauberkundige kann sich bewegen und kämpfen während er den Dampf kontrolliert. (2) Eine stationäre Blase dampffreier Luft von bis zu 9,1 m Durchmesser erzeugen — natürliche und magische Dämpfe sowie gasförmige Kreaturen werden verdrängt und können den geschützten Bereich nicht betreten. Wirksam gegen natürlich vorkommenden Nebel/Gas sowie gasförmige Zauber wie Nebelwand, Stinkende Wolke, Todeswolke, Feuerwolke und gasförmige Odemwaffen. Gasförmige Kreaturen erhalten einen Rettungswurf gegen Zauber. Materialkomponente: V, S, M (ein kleines Glasröhrchen).',
  description_en = 'Can be cast in two ways: (1) Control the movement of gas or vapor — the cloud can be directed at movement rate 6 within the area of effect. The caster can move and engage in combat while controlling the vapors. (2) Create a stationary bubble of vapor-free air up to 9.1 m in diameter — natural and magical vapors as well as gaseous creatures are pushed away and cannot enter the protected area. Effective against naturally occurring mist/gas as well as gaseous spells like Wall of Fog, Stinking Cloud, Cloudkill, Incendiary Cloud, and gaseous breath weapons. Gaseous creatures get a saving throw vs. spell. Material component: V, S, M (a small glass tube).'
WHERE LOWER(name_en) = LOWER('Control Vapor') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Schützt vor Sonnenstich, Hitzschlag, Sonnenbrand und anderen schädlichen Auswirkungen feindlicher Umgebungen. Nützlich für Wüstenreisen und lange Seereisen — überall wo sengende Hitze herrscht und Frischwasser knapp ist. Auch kaltblütige oder wasserbasierte Kreaturen profitieren; hält feuchthäutige Kreaturen feucht (ermöglicht aber wasseratmenden Kreaturen nicht, an Land zu funktionieren). Nach Ende des Schutzes funktioniert der Zauber für die doppelte Schutzdauer nicht erneut auf dieselbe Kreatur. Materialkomponente: V, S, M (eine Prise Sand, ein Tropfen Wasser und ein Tropfen Blut des Empfängers).',
  description_en = 'Prevents sunstroke, heat exhaustion, sunburn, and other harmful effects of hostile environments. Useful for desert travel and long sea voyages — anywhere blistering heat is abundant and fresh water is scarce. Even cold-blooded or water-based creatures benefit; keeps damp-skinned creatures damp (but does not allow water-breathing creatures to function on land). After protection ends, the spell won''t work again on the same creature for twice the protection duration. Material component: V, S, M (a pinch of sand, a drop of water, and a drop of blood from the recipient).'
WHERE LOWER(name_en) = LOWER('Cool Strength') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Lässt eine Person sich unter Bedingungen wohlfühlen, die sie sonst schwächen oder verletzen würden, wie Wüstenhitze. Nützlich für beschwerliche Reisen durch solches Gelände. Wenn tatsächlicher Feuer- oder Hitzeschaden verursacht würde — einschließlich magischem Feuer, Lava etc. — erhält die Person −1 Schadenspunkt pro Würfel (Minimum 1 TP pro Würfel). Materialkomponente: V, S, M (ein Stück Entendaunen).',
  description_en = 'Allows an individual to feel comfortable in conditions that would otherwise debilitate or injure, such as desert heat. Useful for arduous treks across such terrain. If actual fire or heat damage would be inflicted — including magical fires, lava, and the like — the individual receives −1 damage per die (minimum 1 HP per die). Material component: V, S, M (a bit of duck down).'
WHERE LOWER(name_en) = LOWER('Cool — Pluma') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erstellt eine perfekte Kopie einer Karte, eines Briefes oder eines anderen geschriebenen oder gezeichneten Dokuments. Der Zauberkundige benötigt ein leeres Pergament oder Buch mit genügend leeren Seiten. Er hält das leere Objekt über das zu kopierende Dokument und wirkt den Zauber — die Kopie erscheint sofort auf dem ehemals leeren Objekt. Textlänge begrenzt auf 10 Seiten Standardgröße (ca. 22,9 × 30,5 cm). Die Kopie ist permanent und ein perfektes Duplikat des Originals. Der Zauber kann keine magischen Schriften duplizieren. Materialkomponente: V, S, M (ein leeres Pergament oder Buch mit leeren Seiten und ein Tropfen schwarze Tinte).',
  description_en = 'Creates a perfect copy of a map, letter, or other written or drawn document. The caster needs blank parchment or a book with blank pages of sufficient size. He holds the blank object over the document to be copied and casts the spell — the copy appears instantly on the formerly blank object. Text length limited to 10 pages of standard size (roughly 22.9 × 30.5 cm). The copy is permanent and a perfect duplicate of the original. The spell cannot duplicate magical writings. Material component: V, S, M (blank parchment or book with blank pages and a drop of black ink).'
WHERE LOWER(name_en) = LOWER('Copy') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Stellt eine sensorische Verbindung zwischen dem Zauberkundigen und einer Leiche oder einem frisch belebten Zombie her. Pro drei Stufen über der 1. erhält der Zauberkundige Zugang zu einem weiteren Sinn über die Verbindung: Stufe 1 = 1 Sinn, Stufe 4 = 2, Stufe 7 = 3, Stufe 10 = 4, Stufe 13 = alle 5. Verfügbare Sinne: Sicht (durch ein Auge der Leiche sehen), Gehör (durch ein Ohr hören), Geruch (durch eine Nasenloch riechen, Verwesungsgestank wird ausgeblendet), Geschmack (Substanzen in den Mund der Leiche schmecken, nützlich zur Giftprüfung), Tastsinn (Oberflächenstruktur und Temperatur an einer Hand fühlen). Sinnenwahl erfolgt beim Wirken und kann nicht geändert werden. Materialkomponente: V, S, M.',
  description_en = 'Establishes a sensory link between the caster and a corpse or freshly animated zombie. For every three levels past 1st, the wizard gains access to an additional sense via the link: Level 1 = 1 sense, Level 4 = 2, Level 7 = 3, Level 10 = 4, Level 13 = all 5. Available senses: Sight (see through one of the corpse''s eyes), Sound (hear through one ear), Smell (smell through one nostril, putrefying stench is masked), Taste (taste substances placed in the corpse''s mouth, useful for poison detection), Touch (sense texture and temperature with one hand). Sense choice is made at casting and cannot be changed. Material component: V, S, M.'
WHERE LOWER(name_en) = LOWER('Corpse Link') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verwandelt das Gesicht des Zauberkundigen oder einer berührten Kreatur in das entsetzliche Antlitz einer verwesenden Leiche. Die Illusion ist so erschreckend, dass die Gruppe des Zauberkundigen +2 auf den Überraschungswurf erhält. Kreaturen mit niedriger oder höherer Intelligenz (INT 5+) und 1 TW oder weniger (oder 1. Stufe oder niedriger) müssen bei der ersten Sichtung einen Rettungswurf bestehen oder fliehen für 1W4 Runden in Panik. Der Zauber unterscheidet nicht zwischen Freund und Feind — alle Betrachter sind betroffen. Unwillige Opfer erhalten einen Rettungswurf zur Vermeidung. Materialkomponente: V, S, M (ein Stück Stoff von einer Leiche, mit verschiedenfarbiger Farbe betupft).',
  description_en = 'Transforms the caster''s face or that of a touched creature into the horrifying visage of a rotting corpse. The illusion is so startling that the wizard''s party gains +2 to its surprise roll. Creatures with Low Intelligence or higher (INT 5+) and 1 HD or less (or 1st level or lower) must save when first viewing the visage or flee in terror for 1d4 rounds. The spell does not distinguish between friend and foe — all who view it are subject to its effects. Unwilling victims get a saving throw to avoid. Material component: V, S, M (a rag or cloth from a corpse, dotted with paints of assorted colors).'
WHERE LOWER(name_en) = LOWER('Corpse Visage') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Lässt einen toten oder untoten Körper in bleichem Licht erstrahlen. Das Leuchten kann weiß, gelb, grün, bernsteinfarben oder rot sein — nach Wunsch des Zauberkundigen, änderbar solange er innerhalb von 9,1 m ist. Die Lichtstärke kann von kaum wahrnehmbarem Umriss bis zur Helligkeit einer Fackel variiert werden (ausreichend zum Lesen). Das Leuchten ist diffus und konstant und benachteiligt die untote Figur nicht im Kampf. Pro Stufe kann ein menschengroßer Körper betroffen werden (doppelt so viele kleine, halb so viele große, ein Viertel so viele riesige). Nichts größer als riesig kann betroffen werden. Das Leuchten schadet Untoten in keiner Weise. Materialkomponente: V, S, M (eine Prise Salpeter und etwas Phosphor oder ein Glühwürmchen).',
  description_en = 'Causes a dead or undead body to glow with a pale radiance. The glow can be white, yellow, green, amber, or red — as the caster desires, changeable while within 9.1 m. Light intensity can vary from the barest outline to torch brightness (suitable for reading). The glow is diffuse and constant and does not penalize the undead figure in combat. Per level, one man-sized body can be affected (twice as many small-sized, half as many large, one-quarter as many huge). Nothing larger than huge can be affected. The glow does not harm undead in any way. Material component: V, S, M (a pinch of saltpeter and a bit of phosphorus or glowworm).'
WHERE LOWER(name_en) = LOWER('Corpselight') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Belebt einen einzelnen toten Körper (max. doppelte Masse des Zauberkundigen) und lässt ihn sich wie eine Marionette bewegen. Die groben, unbeholfenen Bewegungen erlauben weder Angriffe noch präzise Handlungen, aber die Leiche kann schwere Objekte mit beiden Händen heben und fallenlassen. Die Leiche hat 1W8 Trefferpunkte und eine der Kleidung/Rüstung entsprechende Rüstungsklasse. Ein erfolgreicher Vertreiben-Versuch gegen Zombies beendet den Zauber. Viele Nekromanten nutzen diesen Zauber, um ein gefallenes Mitglied einer feindlichen Gruppe zu beleben — der SL kann einen Moralwurf verlangen, ob die Kreaturen in Panik fliehen. Materialkomponente: V, S, M (ein Tropfen Blut).',
  description_en = 'Animates a single dead body (max twice the caster''s mass) to move like a marionette. The crude, clumsy movements do not allow attacks or precise actions, but the corpse can lift and drop heavy objects with both hands. The corpse has 1d8 hit points and an Armor Class appropriate to its clothing or armor. A successful turning attempt against zombies dispels the enchantment. Many necromancers use this to animate a fallen member of a hostile group — the DM may require a morale check to see if creatures flee in fear. Material component: V, S, M (a drop of blood).'
WHERE LOWER(name_en) = LOWER('Dance Macabre') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt einen blitzenden, springenden, halbkreisförmigen horizontalen Feuerbogen in der Luft. Der Bogen ist 3,7 m von Ende zu Ende und 0,6 m dick. Er bewegt sich gleichmäßig mit Bewegungsrate 1 vom Ursprungspunkt in eine beim Wirken festgelegte (danach unveränderliche) Richtung, bis der Zauber endet oder der Bogen eine feste Barriere trifft. Brennt er sich durch eine Barriere (z.B. eine Holztür), bewegt er sich weiter in dieselbe Richtung. Die Flammen verursachen 3W4 Schaden bei jeder berührten Kreatur und erzwingen Rettungswürfe gegen magisches Feuer für alle brennbaren Gegenstände. Ein Treffer stoppt den Bogen nicht — eine Kreatur kann eine andere nicht vor seinen Effekten schützen. Komponente: V.',
  description_en = 'Creates a flashing, leaping, semicircular horizontal arc of flame in midair. The arc is 3.7 m from end to end and 0.6 m thick. It moves steadily at rate 1 from its point of origin in a direction set at casting (unalterable thereafter), until the spell expires or the arc strikes a solid barrier. If it burns through a barrier (e.g., a wooden door), it continues in the same direction. The flames inflict 3d4 damage on each being contacted and force saving throws vs. magical fire for all flammable items. Striking a target does not stop the arc — one being cannot shield another from its effects. Component: V.'
WHERE LOWER(name_en) = LOWER('Dancing Fire — Phaerimm') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Schützt den Alhoon-Zauberkundigen für den Rest der aktuellen oder die nächste Runde (Wahl beim Wirken). Beeinflusst nicht die Trefferchance, sondern nur den erlittenen Schaden. Angriffe können den Zauberkundigen nicht betäuben oder Körperteile abtrennen, und physischer Schaden wird um −1 TP pro Würfel reduziert (Minimum 1 TP pro Würfel). Wirkt auch bei „maximalem Schaden"-Situationen. Hat keine Wirkung gegen Säure, Gift oder rein magische Angriffe (magische Waffenangriffe werden aber reduziert, ebenso Fernkampfangriffe). Verzögerung auf die nächste Runde beeinträchtigt nicht das Wirken eines neuen Zaubers in jener Runde. Kann mit Schild und anderen Schutzzaubern kombiniert werden, schützt aber nur den Zauberkundigen selbst. Materialkomponente: V, S, M (ein Stück Nagel von der Hand oder Klaue einer Kreatur oder ein hartes Stück Chitin).',
  description_en = 'Protects the alhoon caster for the rest of the current or next round (chosen during casting). Does not affect chances of being hit, only damage suffered. Attacks cannot stun the caster or sever body parts, and physical damage is reduced by −1 HP per die (minimum 1 HP per die). Works even in "maximum damage" situations. No effect against acid, poison, or purely magical attacks (but magical weapon and missile attacks are reduced). Delaying to next round does not impair casting a new spell that round. Can be combined with Shield and other protective magics, but only affects the caster. Material component: V, S, M (a piece of nail from a creature''s hand or claw, or a hard piece of chitin).'
WHERE LOWER(name_en) = LOWER('Deflection — Alhoon') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Enthüllt dem Zauberkundigen, ob eine Kreatur oder ein Objekt eine Krankheit trägt — ob natürlich oder magisch. Zusätzlich hat der Zauberkundige eine 5%-Chance pro Stufe, die genaue Art der Krankheit zu identifizieren. Materialkomponente: V, S, M (ein Zweig oder kleiner Ast von einem Baum).',
  description_en = 'Reveals to the wizard whether a subject creature or object carries a disease, whether normal or magical. Additionally, the caster has a 5% chance per level to identify the exact type of disease. Material component: V, S, M (a twig or small branch from any tree).'
WHERE LOWER(name_en) = LOWER('Detect Disease') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht dem Zauberkundigen, eine Illusion zu sehen und sie als solche zu erkennen. Andere Kreaturen können ebenfalls befähigt werden, Illusionen als unwirklich zu erkennen, wenn der Zauberkundige sie mit beiden Händen berührt, während die Kreatur die Illusion betrachtet. Materialkomponente: V, S, M (ein Stück gelblich getönter Kristall, Glas oder Glimmer).',
  description_en = 'Allows the wizard to see an illusion and know it for what it is. Others can be enabled to see illusions as unreal if the caster touches the creature with both hands while the creature looks at the illusion. Material component: V, S, M (a piece of yellow-tinted crystal, glass, or mica).'
WHERE LOWER(name_en) = LOWER('Detect Illusion') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht dem Alhoon, die Anwesenheit intelligenten Lebens im Wirkungsbereich (18,3-m-Radius-Kugel) zu entdecken. Der Alhoon kann erkennen, ob das Leben wach ist (bei Bewusstsein, geistig gesund, frei von Berauschung oder sinnestrübender Magie), aber nicht genau wo, was oder wie viele Wesen anwesend sind. Erkennt unsichtbares, verborgenes, verkleidetes oder in Objekten eingeschlossenes Leben und erstreckt sich auf die Astral- und Ätherebene. Gibt keinen Hinweis auf Natur, Gedanken oder Gesinnung des entdeckten Lebens. Untote können nicht entdeckt werden. Magisch oder psionisch abgeschirmte Kreaturen sowie abwesende Späher werden nicht erkannt. Der Alhoon kann den Kugelradius kleiner wählen (3, 6, 9, 12 oder 15,2 m), muss dies aber beim Wirken festlegen. Komponenten: V, S.',
  description_en = 'Allows the alhoon to detect the presence of intelligent life within the spell area (18.3 m radius sphere). The alhoon can tell if the life is aware (awake, sane, free of intoxication or sensory-debilitating magic) but not precisely where, what, or how many entities are present. Detects invisible, concealed, disguised, or object-trapped life and extends into the Astral and Ethereal Planes. Gives no hint of the nature, thoughts, or inclination of life detected. Undead cannot be detected. Magically or psionically shielded creatures and absent scryers are not detected. The alhoon can choose a smaller sphere radius (3, 6, 9, 12, or 15.2 m) but must decide at casting. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Detect Life — Alhoon') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht dem Zauberkundigen, den Standort einer bestimmten Erz- oder Minerallagerstätte pro Wirken zu orten. Der Zauber enthüllt Richtung und Entfernung zu dem Material im Wirkungsbereich sowie die ungefähre Menge. Die Pfadlänge beträgt 6,1 m pro Stufe für gewöhnliche Materialien, 1,5 m pro Stufe für Edelmetalle oder Edelsteine. Nur eine Konzentration des Materials kann pro Runde gefunden werden (größere Konzentrationen werden zuerst bemerkt und können kleinere Mengen verbergen, es sei denn der Zauberkundige nimmt sich extra Zeit). Materialkomponente: V, S, M (ein kleiner Magnet, eine Phiole schwacher Säure und ein 60-Gramm-Stück des gewünschten Materials).',
  description_en = 'Allows the caster to divine the location of a single type of ore or mineral deposit per casting. The spell reveals direction and distance to any such material within its area of effect, as well as the approximate amount present. Path length is 6.1 m per caster level for common materials, 1.5 m per level for precious metals or gems. Only one concentration can be found per round (larger concentrations are noted first and may mask smaller amounts unless the caster spends extra time). Material component: V, S, M (a small magnet, a vial of weak acid, and a 60 g lump of the desired material).'
WHERE LOWER(name_en) = LOWER('Detect Metals and Minerals') AND spell_type = 'wizard';
