-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 3 (Batch 2: 15 Spells — Battlecurse to Close Path)
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  description = 'Beeinträchtigt eine Kreatur in Reichweite (nicht geschützt durch Kleine Kugel der Unverwundbarkeit oder stärkere Barriere). Rettungswurf gegen Zauber: bei Erfolg — die Kreatur kann in der nächsten Runde nicht angreifen (Verteidigungszauber, Bewegung, Waffen bereitmachen und Parieren möglich). Bei Misserfolg — die Rüstungsklasse der Kreatur verschlechtert sich um 4 Punkte (z.B. von RK 4 auf RK 8) für 4 Runden. Materialkomponente: V, S, M (ein gespaltenes Haar und ein Edelstein im Wert von mind. 200 GM).',
  description_en = 'Adversely affects one creature within range (not protected by Minor Globe of Invulnerability or stronger barrier). Save vs. spell: on success — the creature cannot attack on the following round (defensive spells, movement, readying weapons, and parrying are possible). On failure — the creature''s AC worsens by 4 points (e.g., from AC 4 to AC 8) for 4 rounds. Material component: V, S, M (a split hair and a gem worth at least 200 gp).'
WHERE LOWER(name_en) = LOWER('Battlecurse') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Betroffene Kreaturen verlieren ihren Orientierungs- und Zielsinn. Sie vergessen sofort ihr Ziel und ihre beabsichtigte Handlung — Angriffe, Zauber, Kartenfolgen etc. Die Kreatur fühlt sich plötzlich verloren, selbst an vertrauten Orten. Sie erkennt noch Kameraden und Besitz und ist nicht anfälliger für Betrug oder Zauber wie Bezauberung. Im Kampf verliert sie eine volle Runde an Aktionen. In der nächsten Runde: INT-Wurf nötig zum Wiederaufnehmen des Kampfes (Nahkampf-Selbstverteidigung auch ohne). Ein verwirrter Zauberkundiger vergisst seinen aktuellen Zauber (bei laufendem Wirken geht er verloren). Zaubern ist für die Dauer der Verwirrung unmöglich. Materialkomponente: V, S, M (ein Auge irgendeiner Kreatur und etwas Wolle).',
  description_en = 'Affected creatures lose their sense of direction and purpose. They immediately forget their destination and intended action — attacks, spells, trail-following, etc. The creature suddenly feels lost, even in familiar places. It still recognizes companions and belongings and is not more susceptible to trickery or charm/hold spells. In combat, it loses an entire round of actions. Next round: INT check needed to resume combat (melee self-defense continues regardless). A bewildered spellcaster forgets the current spell (if casting, it''s lost). Casting is impossible for the duration. Material component: V, S, M (an eye of any creature and a bit of wool).'
WHERE LOWER(name_en) = LOWER('Bewilder') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt ein Paar menschengroßer Hände, die als gepolsterte Fäuste erscheinen. Die Hände prügeln mit der Effektivität eines Kämpfers mit STR 18/50 und der halben Stufe des Zauberkundigen. Zusammen kämpfen sie als Einzelwesen mit RK 4 und 3 TP pro Stufe des Zauberkundigen. Sie werden aufgelöst wenn ihre TP aufgebraucht sind. Können nur prügeln — keine Waffen halten oder greifen. Können nicht gegriffen oder überrannt werden, da sie leicht davonfliegen. Materialkomponente: V, S, M (ein mit Baumwolle gefüllter Fäustling und eine Messingglocke).',
  description_en = 'Creates a pair of man-sized hands appearing as padded fists. The hands pummel with the effectiveness of an 18/50 STR fighter at half the caster''s level. Together they fight as an individual with AC 4 and 3 HP per caster level. They are dispelled when they run out of HP. Can only pummel — cannot hold weapons or grapple. Cannot be grappled or overborne as they easily flit away. Material component: V, S, M (a mitten stuffed with cotton and a brass bell).'
WHERE LOWER(name_en) = LOWER('Bigby''s Pugnacious Pugilist') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt einen stationären Bereich totaler Dunkelheit (6-m-Radius-Kugel), undurchdringlich für normales Sehen und Infrasicht. Der Zauberkundige selbst kann im Bereich normal sehen und handeln. Jede Runde erhalten andere Kreaturen einen Rettungswurf gegen Zauber mit −3 — bei Erfolg sehen sie für diese Runde wie der Zauberkundige. Wer von außen in die Kugel blickt, sieht nichts. Normale und magische Lichter werden gelöscht. Ein Licht-, Dauerlicht- oder Magie-Bannen-Zauber zerstört den Bereich. Kreaturen in der Dunkelheit erleiden −4 auf Angriffe und RW, RK verschlechtert um 4. Blindkampf-Fertigkeit: nur −2 auf Angriffe/RW, kein RK-Abzug. Kann vom Zauberkundigen jederzeit beendet werden. Materialkomponente: V, S, M (ein Stück Kohle und ein getrocknetes Auge).',
  description_en = 'Creates a stationary area of total darkness (6 m radius globe), impenetrable to normal vision and infravision. The caster can see and act normally within. Each round, other creatures get a save vs. spell at −3 — on success, they can see as the caster for that round. Those outside cannot see in. Normal and magical lights are doused. A Light, Continual Light, or Dispel Magic spell destroys the area. Creatures within suffer −4 on attacks and saves, AC worsened by 4. Blind-Fighting proficiency: only −2 on attacks/saves, no AC penalty. Can be ended by the caster at will. Material component: V, S, M (a piece of coal and a dried eyeball).'
WHERE LOWER(name_en) = LOWER('Blacklight') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Drache ritzt eine unsichtbare Glyphe auf einen wertvollen Edelstein (mind. 500 GM Wert). Nur der ritzende Drache kann das Symbol sehen (Magie Entdecken zeigt eine schwache Aura, Unsichtbares Entdecken/Wahres Sehen enthüllt die Glyphe). Der Zauber bleibt ruhend bis der Drache ihn mental aktiviert — aus jeder beliebigen Entfernung. Bei Aktivierung explodiert der Edelstein im 6,1-m-Radius mit 5W4 Splitterschaden (Rettungswurf gegen Odemwaffe für halben Schaden). Kreaturen die den Edelstein halten/tragen erhalten KEINEN Rettungswurf. In einem stabilen Behälter (Truhe, Metallbox) wird die Explosion eingedämmt und verursacht keinen Schaden an Kreaturen. Der Zauber wird aufgehoben wenn Edelstein und Drache durch eine Ebenengrenze getrennt werden oder der Drache stirbt. Drachen nutzen diesen Zauber als „letztes Lachen" gegen Diebe. Komponenten: V, M.',
  description_en = 'The dragon traces an invisible glyph on a prized gemstone (worth at least 500 gp). Only the tracing dragon can see the symbol (Detect Magic shows a faint aura, Detect Invisibility/True Seeing reveals the glyph). The spell remains dormant until the dragon mentally activates it — from any distance. On activation, the gemstone explodes in a 6.1 m radius dealing 5d4 shrapnel damage (save vs. breath weapon for half). Creatures holding/carrying the gem get NO saving throw. In a sturdy container (chest, metal box), the explosion is contained and deals no damage to creatures. The spell is negated if gem and dragon are separated by a planar boundary or the dragon is slain. Dragons use this as the "last laugh" against thieves. Components: V, M.'
WHERE LOWER(name_en) = LOWER('Blast Jewel — Dragon') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erfordert einen vollen Tag Konzentration im Zentrum des Wirkungsbereichs. Das Gebiet (91,4 m² pro Stufe) wird sofort fruchtbarer und üppiger — trockener Boden wird feucht, sumpfiger Boden entwässert sich zu frischem Lehm. Die Verbesserung ist graduell — eine extreme Dürre kann nicht allein durch diesen Zauber überwunden werden (aber in Kombination mit Wasserbeschwörung möglicherweise). Die Effekte halten bis zum Ende der aktuellen Wachstumsperiode. Materialkomponente: V, S, M (eine Ähre Getreide und ein Schlauch Wasser, ca. 4 Liter).',
  description_en = 'Requires a full day of concentration at the center of the area. The area (91.4 m² per level) immediately becomes more verdant and fertile — dry soil grows moist, fetid swampland drains to reveal fresh loam. The improvement is gradual — a truly terrible drought cannot be overridden by this spell alone (but might in combination with water summoning). Effects last until the end of the current growing season. Material component: V, S, M (an ear of grain and a skin of water, about 4 liters).'
WHERE LOWER(name_en) = LOWER('Blossom — Pluma') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verzaubert einen Knochen zu einer magischen Keule. Die Keule wirkt als Keule +1 und verursacht 2-7 (1W6+1) Schaden. Kann ohne Abzug von jedem mit Keulen-Waffenfertigkeit geführt werden. Der Knochen kann von jedem Tier stammen, muss aber als Keule führbar sein (z.B. ein menschlicher Oberschenkelknochen ja, ein Schädel nein). Am Ende der Zauberdauer wird die Keule wieder zum normalen Knochen. Materialkomponente: V, M (eine Prise Erde von einem Grab).',
  description_en = 'Enchants a bone to become a magical club. The club acts as a club +1, dealing 2-7 (1d6+1) damage. Can be wielded without penalty by anyone with club weapon proficiency. The bone can be from any animal, provided it can normally be wielded as a club (e.g., a human femur yes, a skull no). At the end of the duration, the club reverts to a normal bone. Material component: V, M (a pinch of dirt from a grave).'
WHERE LOWER(name_en) = LOWER('Bone Club') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Belebt die physischen Überreste eines Menschen, Halbmenschen oder Humanoiden temporär und schmiedet eine mystische Verbindung, die dem Zauberkundigen ermöglicht, die Bewegungen mental zu steuern — wie ein Puppenspieler eine Marionette. Das Skelett/der Zombie ist zu keinen eigenständigen Handlungen fähig. Der Zauberkundige muss mental befehlen: vorwärts gehen, Schwert aufheben, zuschlagen etc. Während der Konzentration kann der Zauberkundige nicht sprechen, zaubern oder aktiv am Nahkampf teilnehmen. Kann einfache Handlungen ausführen: Greifen, Heben, Tragen, Türen öffnen, grobes Mischen. Im Kampf kämpft es als normales Skelett/Zombie. Kombiniert mit Spektralstimme: effektiver Köder oder Bluff. Mit Leichenverbindung: Kundschafter jenseits der Sichtweite. Endet bei Konzentrationsunterbrechung oder außerhalb von Reichweite/Sicht. Materialkomponente: S, M (ein intaktes Skelett/Leichnam und eine kleine, grobe Puppe).',
  description_en = 'Temporarily animates the remains of a human, demihuman, or humanoid and forges a mystical link allowing the caster to mentally control its movements — like a puppeteer manipulating a puppet. The skeleton/zombie is incapable of independent actions. The caster must mentally command: walk forward, pick up sword, strike, etc. While concentrating, the caster cannot speak, cast spells, or engage in melee. Can perform simple actions: grasping, lifting, carrying, opening doors, crude mixing. In combat, it fights as a regular skeleton/zombie. Combined with Spectral Voice: effective decoy or bluff. With Corpse Link: scout beyond visual range. Ends if concentration is broken or beyond range/sight. Material component: S, M (an intact skeleton/corpse and a small crude puppet).'
WHERE LOWER(name_en) = LOWER('Bone Dance') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Fügt die Teile eines Skeletts wieder zusammen. Alle Stücke müssen vorhanden sein. Der Zauberkundige legt seine Hände über die Knochen (max. 0,3 m Abstand) und die Knochen verwandeln sich in ein ganzes Skelett. Wird dieses Skelett anschließend mit Tote Beleben belebt, hat es maximale Trefferpunkte. Kann auch auf ein untotes Skelett gewirkt werden, das nicht vollständig zerstört wurde, um es von physischem Schaden zu „heilen". In Kombination mit Permanenz: erzeugt ein Skelett, das 1W4 Punkte physischen Schaden alle 2 Runden „regeneriert" (Feuer-, Säureschaden und Effekte des Untoten-Vertreibens können nicht regeneriert werden). Materialkomponente: V, S, M (ein Tropfen Blut des Zauberkundigen und ein Tropfen Trollblut).',
  description_en = 'Rejoins the pieces of a skeleton. All pieces must be present. The caster places hands over the bones (max 0.3 m distance) and they transform into a whole skeleton. If subsequently animated with Animate Dead, it has maximum hit points. Can also be cast on an undead skeleton that hasn''t been utterly destroyed to "heal" it of physical damage. Combined with Permanency: creates a skeleton that "regenerates" 1d4 points of physical damage every 2 rounds (fire, acid damage, and turning effects cannot be regenerated). Material component: V, S, M (a drop of the caster''s blood and a drop of troll''s blood).'
WHERE LOWER(name_en) = LOWER('Bone Knit') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Überzieht die Hand des Zauberkundigen mit einer hochwirksamen Säure. Der Zauberkundige bleibt immun. Jede Kreatur, die er mit einem erfolgreichen Nahkampfangriff berührt, erleidet 1W3 + 1 Schadenspunkt pro Stufe des Zauberkundigen. Die Säure wirkt jede Runde der Exposition; wer gepackt und gehalten wird, erleidet Schaden jede Runde bis zum Losreißen. Kann auch nichtlebende Materie zerstören: brennt ein handgroßes Loch durch 5,1 cm Holz oder 2,5 cm Metall pro Runde. Magische Materialien sind immun. Komponenten: V, S.',
  description_en = 'Coats the caster''s hand with a highly potent acid. The caster remains immune. Any creature touched with a successful melee attack suffers 1d3 + 1 damage per caster level. The acid deals damage each round of exposure; creatures grabbed and held take damage each round until they break free. Can also destroy inanimate material: burns a hand-sized hole through 5.1 cm of wood or 2.5 cm of metal per round. Magical materials are immune. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Brannart''s Acidic Grip') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ruft alle Untoten mit 6 TW oder weniger innerhalb des Wirkungsbereichs (90 m/Stufe Radius) herbei, gibt dem Zauberkundigen aber KEINE Kontrolle über sie. Nützlich um versteckte Untote hervorzulocken (damit Gefährten sie bekämpfen können) oder um einen Untoten-Angriff auf Feinde auszulösen. Der Ruf ermöglicht den Untoten nicht, den Rufenden unfehlbar zu lokalisieren. Wirkt durch Wasser, Stein und alle nichtmagischen Barrieren, überquert aber keine Ebenengrenzen. Untote mit mehr als 6 TW können mitkommen, sind aber nicht gezwungen. Kann zuvor vertriebene Untote zurückholen und einen neuen Vertreibungsversuch erzwingen. Materialkomponente: V, S, M (ein mit einer Schnur zusammengebundenes Knochenstück).',
  description_en = 'Summons all undead of 6 HD or less within spell range (90 m/level radius), but gives the caster NO control over them. Useful for drawing out hidden undead (so companions can deal with them) or triggering an undead attack on foes. The call does not let undead unerringly locate the caller. Works through water, stone, and all nonmagical barriers, but does not cross planar boundaries. Undead with more than 6 HD may accompany them but are not compelled. Can bring back previously turned undead, forcing another turning attempt. Material component: V, S, M (a piece of bone tied with a string).'
WHERE LOWER(name_en) = LOWER('Call Undead') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt eine kleine hölzerne Gondel (3,7 m lang, 1,2 m breit), die 3-4 Passagiere plus einen (nichtmagischen) Gondoliere aufnimmt. Ihre verzauberte Natur lässt sie mit glitzernder Ausstrahlung leuchten. Die praktisch unzerstörbare beschworene Gondel gleitet so sanft durch Wasser, dass selbst ein Unsichtbarer Diener sie staken kann. Das ruderlose Boot ist viel zu leicht für größere Gewässer als einen kleinen Teich oder einen ruhigen Kanal. Ein 3,7-m-Stab wird mit der Gondel erzeugt. Materialkomponente: V, S, M (ein Stück Holz und Stroh).',
  description_en = 'Creates a small wooden gondola (3.7 m long by 1.2 m wide), holding 3-4 passengers plus a (nonmagical) gondolier. Its enchanted nature causes it to glow with glittering radiance. The virtually indestructible conjured gondola moves through water so smoothly that even an Unseen Servant can pole it. The rudderless boat is far too light for any body of water larger than a small pond or calm canal. A 3.7 m pole is created with the gondola. Material component: V, S, M (a bit of wood and thatch).'
WHERE LOWER(name_en) = LOWER('Callistram''s Gondola') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Insekten, Tiere, Halbmenschen, Humanoide und Monster mit 5 TW/Stufen oder weniger im 21-m-Radius verlieren ihren Kampfwillen — selbst mitten im Todeskampf. Nur Kreaturen beim Wirken im Bereich werden betroffen. Der Zauberkundige kann bis zu 1 Kreatur pro Stufe bewusst ausschließen. Magieresistenz ist um 15% gesenkt, Rettungswurf gegen Zauber mit −2. Beruhigte Kreaturen können keine andere lebende Kreatur angreifen, verteidigen sich aber normal. Wird eine beruhigte Kreatur angegriffen, erhält sie sofort einen neuen Rettungswurf mit +3 Bonus. Beruhigter Zustand hält 1 Stunde (6 volle Runden) oder bis zur Attacke, auch wenn die Kreatur den Bereich verlässt. Komponenten: V, S.',
  description_en = 'Insects, animals, demihumans, humanoids, and monsters of 5 HD/levels or less within the 21 m radius lose their will to fight — even in combat to the death. Only creatures in the area at casting are affected. The caster can exclude up to 1 creature per level. Magic resistance is lowered by 15%, saving throws vs. spell at −2. Calmed creatures cannot attack any living thing but defend themselves normally. If a calmed creature is attacked, it gets an immediate new save with +3 bonus. Calm lasts 1 hour (6 full turns) or until attacked, even if the creature leaves the area. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Calm') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Versperrt einem Zauberkundigen den Zugang zu einem Pfad magischen Wissens für den Rest des Tages (zufällig bestimmt). Bereits memorierte Zauber werden nicht vergessen, aber der Zugang ist gesperrt. Der Zauberkundige weiß nicht, welcher Pfad/welche Zauber gesperrt sind. Nach 24 Stunden kann der Zauberkundige wieder normal memorieren und wirken. Kann nicht die Hauptschule eines Spezialisten versperren. Materialkomponente: V, S, M (ein kleiner Silberschlüssel im Wert von mind. 50 GM, der beim Wirken zerbrochen werden muss).',
  description_en = 'Bars a wizard''s access to one path of magical knowledge for the remainder of the day (randomly determined). Spells already memorized are not forgotten, but access is blocked. The caster doesn''t know which path/spells are barred. After 24 hours, the wizard can memorize and cast normally again. Cannot close off a specialist wizard''s principal school. Material component: V, S, M (a small silver key worth at least 50 gp, which must be broken during casting).'
WHERE LOWER(name_en) = LOWER('Close Path') AND spell_type = 'wizard';
