-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 3 (Batch 3: 18 Spells — Cloudburst to Distraction)
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  description = 'Fällt sofort alle Feuchtigkeit in der Luft als durchnässender Regen aus (2,5 cm pro Runde). Löscht normale Feuer (kleine sofort, mittlere in einer halben Runde, große in einer vollen Runde) und magische Feuer für 1W2 Runden. Großflächige Feuerzauber werden in einer riesigen Dampfwolke gelöscht. Nebel wird als Regen ausgefällt, Rauch und ähnliche Partikelwolken werden zerstreut. Kann durch Klima und Temperatur beeinflusst werden (stärker im Dschungel, schwächer in Wüsten, Graupel/Schnee in der Arktis). Materialkomponente: V, S, M (ein kleiner Drachen und etwas Steinsalz).',
  description_en = 'Immediately precipitates all moisture in the air as drenching rain (2.5 cm per round). Quenches normal fires (small ones immediately, medium in half a round, large in a full round) and douses magical fires for 1d2 rounds. Large-area fire spells are extinguished in a huge cloud of steam. Fog is precipitated as rain, smoke and similar particle clouds are dispersed. May be affected by climate and temperature (greater effect in jungles, lesser in deserts, sleet/snow in arctic). Material component: V, S, M (a small kite and some rock salt).'
WHERE LOWER(name_en) = LOWER('Cloudburst') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Empfänger (bis zu 10 Kreaturen) fühlen keinen Schmerz, keine Hitze, Kälte, Hunger, Durst oder Erschöpfung und müssen für die Zauberdauer von 6 Stunden weder essen noch ruhen. Der Zauber negiert nicht erlittenen Schaden, hebt aber z.B. die Effekte eines Stabs der Furcht, Trommeln der Panik, ähnlicher magischer Gegenstände oder eines Schlaf-Zaubers auf. Empfänger erhalten +1 auf alle Rettungswürfe für die Dauer. Komponenten: V, S, M.',
  description_en = 'Recipients (up to 10 creatures) feel no pain, heat, cold, hunger, thirst, or exhaustion, and need not eat or rest for the 6-hour duration. The spell does not negate normal damage taken, but negates effects of a Wand of Fear, Drums of Panic, similar magical items, or a Sleep spell. Recipients receive +1 on all saving throws for the duration. Components: V, S, M.'
WHERE LOWER(name_en) = LOWER('Comfort') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Wu Jen kontaktiert einen lokalen Geist (z.B. Geist eines bestimmten Baumes, Felsens oder Baches; nicht mächtigere Geister wie Berge oder Flüsse). Der Wu Jen muss die Identität des Geistes kennen und innerhalb von 3 m sein. Pro Stufe kann eine Frage gestellt werden — spezifisch und klar formuliert, nicht auf Ja/Nein beschränkt. Der Geist antwortet wörtlich und gibt keine freiwilligen Informationen. Gute Geister helfen so viel wie möglich, neutrale antworten in Rätseln, böse versuchen die Antwort zu verdrehen. Der Geist kann nur Fragen beantworten, die sein unmittelbares Gebiet betreffen. Materialkomponente: V, S, M (Weihrauch und ein dem Geist angemessenes Opfer).',
  description_en = 'The wu jen contacts a local spirit (e.g., spirit of a specific tree, rock, or stream; not more powerful spirits like mountains or rivers). The wu jen must know the spirit''s identity and be within 3 m. One question per level can be asked — specific and clear, not limited to yes/no. The spirit answers literally and doesn''t volunteer information. Good spirits help as much as possible, neutral ones answer in riddles, evil ones try to distort answers. The spirit can only answer questions about its immediate area. Material component: V, S, M (incense and an appropriate offering for the spirit).'
WHERE LOWER(name_en) = LOWER('Commune with Lesser Spirit') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Löscht sofort alle nichtmagischen Lichtquellen im Wirkungsbereich (15-m-Radius). Magische Lichtquellen (einschließlich magischer Waffen) können ebenfalls gelöscht werden: Jedes Objekt erhält einen Rettungswurf gegen Auflösung. Bei Misserfolg sind sie nur gelöscht, nicht zerstört. Normale Lichtquellen können für eine Stunde nicht wieder angezündet werden. Magische Lichtquellen erhalten zu Beginn jeder Runde einen RW mit +4 Bonus; bei Erfolg entzünden sie sich wieder (schlimmstenfalls nach einer vollen Stunde). Komponenten: V, S.',
  description_en = 'Instantly extinguishes all nonmagical light sources in the area of effect (15 m radius). Magical light sources (including magical weapons) may also be extinguished: each item gets a saving throw vs. disintegration. On failure, they''re merely extinguished, not destroyed. Normal light sources cannot be relit for one hour. Magical light sources get a save at the start of each turn with +4 bonus; they relight on success (at worst, one full hour later). Components: V, S.'
WHERE LOWER(name_en) = LOWER('Create Darkness — Drow') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Zauberkundige schreibt den Namen seines Opfers auf eine Bleitafel, treibt einen Nagel hindurch, ruft die Geister der Toten an und legt die Tafel in ein besetztes Grab. Jeden Mitternacht muss das Opfer einen Rettungswurf gegen Zauber bestehen. Bei Misserfolg: schreckliche Todesträume, Erwachen krank und erschöpft, Verlust der Hälfte der aktuellen TP (oder 1 TP, je nachdem was mehr ist). Bei Erfolg: kein Effekt. Drei aufeinanderfolgende Erfolge brechen den Fluch (die Schrift auf der Tafel verschwindet, und dieser Zauberkundige kann ein Jahr lang keine Fluchtafel mehr gegen dieses Opfer einsetzen). Der Zauber kann sicher beendet werden, indem die Tafel gefunden und mit Segnen oder Fluch Aufheben behandelt wird. Schmelzen oder Zerbrechen der Tafel bricht den Fluch ebenfalls, fügt dem Opfer aber 1W4 Schaden zu. Komponenten: V, S, M.',
  description_en = 'The caster writes the victim''s name on a lead tablet, drives a nail through it, invokes the spirits of the dead, and places the tablet in an occupied tomb. Every midnight, the victim must save vs. spell. On failure: horrible death-dreams, awakens sick and exhausted, losing half current HP (or 1 HP, whichever is greater). On success: no effect. Three successes in a row break the curse (writing vanishes, that caster cannot use a curse tablet against the victim for one year). The spell can be safely ended by finding the tablet and casting Bless or Remove Curse on it. Melting or breaking the tablet also breaks the curse but inflicts 1d4 damage on the victim. Components: V, S, M.'
WHERE LOWER(name_en) = LOWER('Curse Tablet') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verwandelt ein Stück Fledermausflügel und ein Knochenstück in ein kurzlebiges, magisch unterstütztes Paar riesiger Fledermausflügel (4,6 m Spannweite). Sie wachsen aus den Schultern des Zauberkundigen oder einer berührten Kreatur. Die Flügel ermöglichen unbeholfenes Fliegen (BW Fl 15, MK: D) mit großer Kraft. Können einen Sturz verlangsamen, bis zu doppeltes Körpergewicht tragen oder bis zu dreifaches Gewicht sicher gleiten lassen. Im Flug können sie andere Kreaturen für 2W4 Schaden pro Runde stoßen (verlangsamt Flug auf 6). Können als Schild dienen (RK 4). Können beliebig viel Schaden einstecken ohne einzubrechen. Verlangsamen die Gehgeschwindigkeit auf maximal 6. Können nicht vor Ablauf entfernt werden (außer durch Magie Bannen oder Verwandlungsmagie). Materialkomponente: V, S, M (Fledermausflügel und Knochenstück).',
  description_en = 'Transforms a piece of bat wing and bone into a short-lived pair of giant bat wings (4.6 m wingspan). They sprout from the shoulders of the caster or a touched creature. The wings allow clumsy flight (MV Fl 15, MC: D) with great power. Can slow a fall, carry up to twice body weight, or glide up to three times body weight to a safe landing. In flight, they can buffet other creatures for 2d4 damage per round (slowing flight to 6). Can shield the creature, giving AC 4. Can take any amount of damage without collapsing. Slow walking to max rate 6. Cannot be removed before expiry (except by Dispel Magic or polymorph magic). Material component: V, S, M (bat wing piece and bone piece).'
WHERE LOWER(name_en) = LOWER('Dark Wings — Drow') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verleiht dem Empfänger die Fähigkeit, hochfrequente Schallwellen auszusenden und zu hören, wie es viele Fledermäuse tun. Dies gibt ein klares „Bild" der physischen Umgebung bis 36,6 m. Der Empfänger erleidet keine Abzüge in Dunkelheit oder bei Licht. Kann auch blind sein — muss aber die Augen schließen, um den Dunkelsinn zu nutzen. Farben, Temperaturunterschiede und Licht/Dunkel-Unterschiede werden nicht wahrgenommen — Schriftrollen lesen ist nicht möglich. Visuelle Illusionen, farbige Gase, Staubwolken, Spiegelbilder und unkörperliche Wesen können nicht erkannt werden. Unkörperliche Wesen greifen mit +4 an, als wäre die Kreatur blind. Funktioniert nicht in einem Stille-Bereich (gilt als blind). Braucht nur Mund und Ohren. Materialkomponente: V, S, M (zwei Fledermausohren und eine kleine silberne Stimmgabel).',
  description_en = 'Grants the recipient the ability to transmit and hear high-pitched sounds, as many bats do. This gives a clear "picture" of the physical area to 36.6 m. The recipient suffers no penalties in darkness or light. Can be blind — must close eyes to use darksense if not. Colors, temperature variations, and light/dark distinctions are not perceived — reading scrolls is impossible. Cannot detect visual illusions, colored gases, dust clouds, mirror images, or insubstantial beings. Insubstantial beings attack at +4 as if the creature were blind. Does not function in a silenced area (treated as blinded). Only needs mouth and ears. Material component: V, S, M (two bat ears and a small silver tuning fork).'
WHERE LOWER(name_en) = LOWER('Darksense') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verzaubert einen kleinen Gegenstand (meist ein poliertes Messer oder glänzendes Metallobjekt) und verknüpft ihn mit der Gesundheit des Zauberkundigen. Solange der Zauberkundige gesund bleibt, behält der Gegenstand seinen Zustand bei. Stirbt der Zauberkundige oder wird dauerhaft handlungsunfähig (z.B. versteinert), wird der Gegenstand korrodiert und stumpf. Die Erkennungswirkung hält an, solange der Zauberkundige innerhalb von 1.609 km des Gegenstands bleibt. Materialkomponente: V, S, M (der zu verzaubernde Gegenstand; wird nicht verbraucht).',
  description_en = 'Enchants a small item (usually a polished knife or shiny metal object), linking it to the caster''s health. As long as the caster stays healthy, the object remains in the same condition. When the caster dies or is permanently disabled (e.g., turned to stone), the enchanted object becomes corroded and dull. The divination effect lasts as long as the caster stays within 1,609 km of the item. Material component: V, S, M (the item to be enchanted; not consumed).'
WHERE LOWER(name_en) = LOWER('Death Talisman') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verschiebt den Tod einer lebenden Kreatur. Wird der Zauber gewirkt, BEVOR das Ziel 0 TP erreicht, kann der Empfänger bis −10 TP kämpfen, zaubern, kommunizieren und normal handeln. Bei −10 TP ist er tot und der Zauber endet. Die begrenzte Dauer (max. 1 Runde/Stufe) ist entscheidend: Läuft der Zauber ab, während das Ziel zwischen 0 und −10 TP liegt, stirbt es sofort. Ein verstorbenes Ziel, das unter diesem Zauber stand, kann durch jede normale Wiederbelebungsmethode zurückgebracht werden. Materialkomponente: V, S, M (ein Splitter von einem Grabstein oder ein Span Holz von einem Sarg).',
  description_en = 'Postpones the death of one living creature. If cast BEFORE the target reaches 0 HP, the recipient can fight, cast spells, communicate, and act normally until reaching −10 HP. At −10 HP, it is dead and the spell ends. The limited duration (max 1 turn/level) is critical: if the spell expires while the target is between 0 and −10 HP, it dies instantly. A deceased target previously under this spell can be revived by any normal method. Material component: V, S, M (a chip from a tombstone or a sliver of coffin wood).'
WHERE LOWER(name_en) = LOWER('Delay Death') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht dem Zauberkundigen durch Berührung, die genaue Art und den Basisstock eines Lykanthropen zu bestimmen — ob Werwolf, Werbär etc. Der Zauber lässt ein kleines leuchtendes Pentagramm auf der Handfläche eines Menschen/Humanoiden oder auf der Stirn eines Tieres erscheinen, das dann verblasst. Der Zauberkundige erfährt den genauen Typ und die Herkunft (Mensch bei Werwolf, Wolf bei Wolfwer). Oft unter einer anderen Aktivität wie Handlesen getarnt. Komponente: V.',
  description_en = 'By touch, the caster can determine the exact type and base stock of a lycanthrope — werewolf, werebear, etc. The spell causes a small glowing pentagram to appear on a human/humanoid''s palm or an animal''s brow, then fade. The caster learns the exact type and origin (human for a werewolf, wolf for a wolfwere). Often concealed under another activity such as palm-reading. Component: V.'
WHERE LOWER(name_en) = LOWER('Detect Lycanthrope — Gypsy') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Wu Jen kann die wahre Form jeder gestaltwandelnden Kreatur sehen (die am häufigsten angenommene Gestalt). Ist die Kreatur aktuell in wahrer Form, enthüllt der Zauber nur, dass sie ein Gestaltwandler ist — nicht die anderen möglichen Formen. Enthüllt nicht den spezifischen Typ des Gestaltwandlers, die Gesinnung oder Absichten. Eine Kreatur oder ein Quadratmeter Fläche kann pro Runde untersucht werden. Materialkomponente: V, S, M (Honigbalsam und Lotusblüte, auf die Augenlider des Zauberkundigen geschmiert).',
  description_en = 'The wu jen can see the true form of any shapechanging creature (the shape most commonly assumed). If the creature is currently in true form, the spell reveals it is a shapechanger but not the other possible forms. Does not disclose the specific type of shapechanger, alignment, or intentions. One creature or one square meter of area can be examined per round. Material component: V, S, M (balm of honey and lotus flower smeared on the caster''s eyelids).'
WHERE LOWER(name_en) = LOWER('Detect Shapechanger') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verzaubert eine Person so, dass sie wirklich Freude am Töten empfindet und sofort in Berserkerwut verfällt — greift Freund und Feind gleichermaßen an (Rettungswurf gegen Zauber negiert). Definition von „Person" wie bei Bezaubern von Personen. Die verzauberte Person greift den Zauberkundigen nicht an, es sei denn dieser greift zuerst an. Gibt es niemanden zum Angreifen, handelt sie normal — sobald jemand in Sicht kommt, greift der Rausch. Die Berserkrangriffe gewähren keine zusätzlichen Kräfte. Bei Wahl zwischen Angriffsmethoden wählt die Person immer die tödlichste (Feuerkugel vor Dolch). Wird sie gegen ein viel mächtigeres Wesen gezwungen, kann der SL einen zweiten RW erlauben. Materialkomponente: V, S, M.',
  description_en = 'Ensorcels a person to truly enjoy killing and immediately go berserk, attacking friend and foe alike (save vs. spell negates). Definition of "person" as in Charm Person. The charmed individual won''t attack the caster unless attacked first. With no one to attack, acts normally — as soon as someone comes in sight, the dire charm takes hold. The berserk attacks grant no additional powers. Given a choice between attack methods, always chooses the most deadly (fireball before dagger). If forced against something much more powerful, DM may permit a second save. Material component: V, S, M.'
WHERE LOWER(name_en) = LOWER('Dire Charm') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Wu Jen kann das Aussehen jeder Kreatur derselben Spezies annehmen, sofern er mit der Person vertraut ist. Erzeugt eine vollständige Illusion der angenommenen Identität — Gesicht, Körperbau und Stimme. Verleiht nicht die Fähigkeiten, persönlichen Gewohnheiten oder mentalen Muster der Person. Beobachter, die die Person kennen, haben eine 5%-Chance pro Stufe, die Verkleidung zu erkennen (Verhaltensänderung). Wer die Person nicht kennt, akzeptiert die Verkleidung automatisch. Völlig untypische Handlungen erlauben allen Anwesenden eine Prüfung. Strahlt eine schwache magische Aura aus (Magie Entdecken). Illusion Entdecken enthüllt den Zauber. Materialkomponente: V, S, M (ein Körperteil der nachgeahmten Person — Haar, Nagelschnitzel — oder ein ständig getragener/mitgeführter Gegenstand; muss während der Dauer am Körper getragen werden).',
  description_en = 'The wu jen can assume the appearance of any creature of the same species, provided he is familiar with the person. Creates a complete illusion of the assumed identity — face, build, and voice. Does not provide the abilities, personal habits, or mental patterns of the person. Observers who know the person have a 5% chance per level to detect the disguise (noticing behavioral changes). Those who don''t know the person automatically accept it. Entirely out-of-character actions allow all present to check. Radiates a faint magical aura (Detect Magic). Detect Illusion reveals the spell. Material component: V, S, M (a body part of the assumed individual — hair, nail clippings — or a constantly worn/carried item; must be carried during the duration).'
WHERE LOWER(name_en) = LOWER('Disguise — Wu Jen') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Eliminiert normalen und magischen Nebel aus dem Wirkungsbereich (3 m/Stufe Radius). Nur Nebel und Dunst werden betroffen, nicht Gewässer, Regen oder andere Niederschläge. Der beseitigte Nebel ist dauerhaft weg, aber neuer Nebel kann nachrücken. Der befreite Bereich bleibt für 1 Runde pro Stufe klar, unabhängig von anderen Bedingungen. Kann direkt auf ein Schiff gewirkt werden — der nebelfreie Bereich bewegt sich dann mit. Kreaturen in Nebel- oder Dunstform (z.B. Vampire) im Bereich müssen einen RW gegen Zauber bestehen. Erfolg: muss in eine andere Form wechseln. Misserfolg: 2W10 Schaden und muss ebenfalls die Form wechseln. Komponenten: V, S.',
  description_en = 'Eliminates normal and magical fog from the area of effect (3 m/level radius). Only fog and mist are affected, not bodies of water, rain, or other precipitation. The dispelled fog is gone permanently, but new fog may fill in. The cleared area stays clear for 1 turn per level regardless of conditions. Can be cast directly on a ship — the fog-free area moves with the vessel. Creatures in fog or mist form (e.g., vampires) in the area must save vs. spell. Success: must transform to a non-fog/mist form. Failure: 2d10 damage and must still change form. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Dispel Fog') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt ein Feld, das sofort alle natürlichen Illusionen wie Luftspiegelungen zerstört. Magische Illusionen werden zerstört und Unsichtbarkeit aufgehoben — mit drei Ausnahmen: natürliche Unsichtbarkeit, Illusionen durch Zauber der 6. Stufe und höher, und natürliche Fähigkeiten die solche Zauber nachahmen, werden nicht betroffen. Wirkt sofort auf visuelle Täuschungen, die den Bereich überlappen, berühren oder sich darin befinden. Normalerweise kontinuierliche oder erneuerbare Magien kehren eine Runde später wieder. Betrifft eine Grundfläche von 5,6 m² pro Stufe, 3 m hoch. Die Form kann frei gewählt werden. Materialkomponente: V, S, M (eine Handvoll Sand, beim Wirken in die Luft gestreut).',
  description_en = 'Creates a field that instantly destroys all natural illusions such as mirages. Magical illusions are destroyed and invisibility negated — with three exceptions: natural invisibility, illusions from 6th-level spells and up, and natural abilities mimicking such spells are not affected. Instantly banishes visual deceptions that overlap, touch, or occur within the area. Normally continuous or renewable magics recur one turn later. Affects a base area of 5.6 m² per level, 3 m high. The shape can be freely chosen. Material component: V, S, M (a handful of sand scattered into the air during casting).'
WHERE LOWER(name_en) = LOWER('Dispel Mirage') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Hebt die Wirkung magischer Stille im Wirkungsbereich auf (3 m/Stufe Radius). Nach dem Wirken können Zauberei, Sprache und alle Handlungen normal fortgesetzt werden. Für die Zauberdauer ist der geschützte Bereich immun gegen Stille-Zauber — sie funktionieren dort nicht. Der Zauber ist nach dem Wirken stationär und kann nicht auf eine Kreatur oder ein Objekt gewirkt werden. Materialkomponente: S, M (eine Prise gepulverter Diamant im Wert von mind. 50 GM, in die Luft geworfen).',
  description_en = 'Negates the effect of magical silence within the area of effect (3 m/level radius). Following the casting, all spellcasting, speaking, and actions can proceed normally. For the duration, the area is proof against Silence spells — they won''t function within. The spell is immobile once cast and cannot be cast on a creature or object. Material component: S, M (a pinch of powdered diamond worth at least 50 gp, flung into the air).'
WHERE LOWER(name_en) = LOWER('Dispel Silence') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Zerstreut jede gasförmige Substanz — natürlichen oder magischen Nebel, Wolken, Dampf, gasförmige Odemwaffen und Kreaturen in gasförmiger oder unkörperlicher Form. Alle Gase und Dämpfe werden im Wirkungsbereich (15-m-Würfel) sofort beim Wirken zerstreut und auch wenn sie später eintreten — erzeugt einen sicheren Bereich in einer großen Giftwolke. Magische Zaubereffekte der 1.–3. Stufe werden sofort negiert; höherstufige unterliegen dem Effekt eines Magie Bannen. Gasförmige Kreaturen erhalten einen RW gegen Zauber: bei Misserfolg 1W6 Schaden pro Stufe (max. 10W6); bei Erfolg halber Schaden und aus dem Bereich vertrieben. Materialkomponente: V, S, M (ein Stück Holzkohle).',
  description_en = 'Disperses any gaseous substance — natural or magical fog, clouds, vapor, gaseous breath weapons, and creatures in gaseous or insubstantial form. All gases are dissipated in the area (15 m cube) at casting and as they later enter — creates a safe area within a large harmful cloud. Magical effects of 1st–3rd level are immediately negated; higher-level spells suffer Dispel Magic effects at the caster''s level. Gaseous creatures get a save vs. spell: on failure, 1d6 damage per level (max 10d6); on success, half damage and forced from the area. Material component: V, S, M (a bit of charcoal).'
WHERE LOWER(name_en) = LOWER('Dissipate Vapor') AND spell_type = 'wizard';
