-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 2 (Batch 2: 15 Spells — Battering Ram to Calder's Starry Sky)
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  description = 'Umhüllt den Arm des Zauberkundigen mit durchscheinender magischer Kraft in Form eines Widderkopfes an der Faust. Der Zauberkundige hat STR 19 zum Öffnen von Türen, Zerbrechen von Gegenständen oder Treffen von Gegnern (2W6 Schaden). Alternativ kann die Kraft bis zu 9,1 m weit in die gezeigte Richtung geschleudert werden — trifft Barrieren wie ein Rammbock oder Kreaturen für 2W6 Schaden (Rettungswurf gegen Zauber oder umgeworfen; erfolgreicher RW negiert nur das Umwerfen, nicht den Schaden). Materialkomponente: V, S, M (ein Stück Widderhorn in der Faust des Zauberkundigen).',
  description_en = 'Wraps the caster''s arm in translucent magical force forming a ram''s head at the fist. The caster has STR 19 for opening doors, breaking items, or hitting opponents (2d6 damage). Alternatively, the force can be launched up to 9.1 m in the pointed direction — hits barriers like a battering ram or creatures for 2d6 damage (save vs. spell or be knocked down; successful save negates the knockdown but not the damage). Material component: V, S, M (a piece of ram''s horn held in the caster''s fist).'
WHERE LOWER(name_en) = LOWER('Battering Ram') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt eine stumpfe Verdichtung aus Kraft, die einen gewählten Feind von oben hämmert — trifft mit dem ETW0 des Zauberkundigen. Bei Treffer verursacht sie 1W8+2 Schaden und erzwingt einen Rettungswurf gegen Zauber. Bei Misserfolg fällt das Opfer für eine Runde bewusstlos um und lässt alle gehaltenen Gegenstände fallen. Getroffene Gegenstände müssen einen RW gegen Zermalmen bestehen. Die Keule hält nur zwei Runden (ob sie trifft oder nicht) und verblasst dann. Sie funktioniert selbst wenn ihr Erschaffer tot ist, geflohen ist oder einen anderen Zauber wirkt — kann dem Ziel folgen, aber bei abgelenkter Aufmerksamkeit nicht das Ziel wechseln. Komponenten: V, S.',
  description_en = 'Creates a blunt coalescence of force that bludgeons a chosen foe from above, hitting with the caster''s THAC0. On a hit, it deals 1d8+2 damage and forces a save vs. spell. On failure, the victim falls unconscious for one round, dropping all held items. Items struck must save vs. crushing blow. The mace lasts only two rounds (whether it hits or not), then fades. It operates even if its creator is dead, has fled, or is casting another spell — it can follow the target but cannot switch targets if the caster''s attention is elsewhere. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Belsham''s Mace') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verwandelt jeden Sturz des Zauberkundigen (ob unbeabsichtigt oder absichtlich) sofort in einen horizontalen Schwung. Die horizontale Bewegung von bis zu 9,1 m kann an jedem Punkt erfolgen, nachdem der Zauberkundige mindestens 3 m gefallen ist. Er kann den Zauber dort beenden (z.B. bei einem Sims oder Balkon), und die Landung ist wie durch Federfall geschützt. Wird der Zauber nicht beendet, folgt ein unfreiwilliger Sturzflug: +4 Angriffsbonus auf ein Ziel unten. Bei Misserfolg: 5W6 Aufprallschaden. Bei Treffer: 8W4 Schaden am Ziel (STR-Wurf oder umgeworfen, dann RW gegen Zauber oder 1 Runde betäubt). Der Zauberkundige erleidet 2W6 Aufprallschaden plus Waffenschaden des Ziels. RK-Abzug von 2, dreifacher Schaden durch aufgestellte Speere. Überlebt er den Angriff, springt er auf die Füße und kann ein betäubtes Ziel automatisch treffen. Komponenten: V, S.',
  description_en = 'Instantly turns any fall by the caster (accidental or deliberate) into a horizontal swoop. The horizontal movement of up to 9.1 m can occur at any point after descending at least 3 m. The caster can end the spell there (e.g., at a ledge or balcony), landing as if protected by Feather Fall. If not ended, an involuntary power dive follows: +4 attack bonus on a target below. On miss: 5d6 impact damage. On hit: 8d4 damage to the target (STR check or knocked down, then save vs. spell or stunned 1 round). The caster suffers 2d6 impact damage plus any weapon damage from the target. AC penalty of 2, triple damage from set spears. If surviving, the caster rebounds to his feet and can automatically hit a stunned target. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Bendal''s Swoop') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Beschwört ein Paar körperloser Hände, die dem Zauberkundigen überallhin folgen und jeden Befehl ausführen. Die Hände können alle Funktionen eines Unsichtbaren Dieners erfüllen, aber auch Aufgaben ausführen, die feine Koordination erfordern: Werkzeuge bedienen, Laborgeräte handhaben, Skulpturen formen, malen, Musikinstrumente spielen. Sie können jede Aufgabe ausführen, die der Zauberkundige beherrscht (einschließlich nichtwaffentechnischer Fertigkeiten), mit der GES des Zauberkundigen. Jede Hand trägt bis zu 9,1 kg (zusammen 22,7 kg). Bewegungsrate 12, maximal 27,4 m vom Zauberkundigen entfernt. Können keine Zauber-Gesten ausführen, keine Waffen führen und nicht zuschlagen. Immun gegen physische Angriffe, aber durch 6+ Punkte magischen Schaden zerstörbar. Materialkomponente: V, S, M (ein Paar Handschuhe mit den Initialen des Zauberkundigen).',
  description_en = 'Summons a pair of disembodied hands that follow the wizard and obey every order. The hands can perform all functions of an Unseen Servant, but also accomplish tasks requiring fine coordination: tinkering with tools, working with lab equipment, sculpting, painting, playing instruments. They can perform any task the caster can accomplish (including nonweapon proficiencies), with the caster''s DEX. Each hand carries up to 9.1 kg (22.7 kg together). Movement rate 12, max 27.4 m from the caster. Cannot perform somatic spell components, wield weapons, or punch/grapple. Immune to physical attacks, destroyed by 6+ points of magical damage. Material component: V, S, M (a pair of gloves embroidered with the wizard''s initials).'
WHERE LOWER(name_en) = LOWER('Bigby''s Dextrous Digits') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt eine passend große Hand, die auf die gewählte Kreatur zufliegt und sich fest über deren Mund klemmt (Rettungswurf negiert). Die betroffene Kreatur kann nicht klar sprechen, keine Zauber mit verbaler Komponente wirken und keine magischen Gegenstände mit hörbarem Befehlswort aktivieren. Die Hand kann nicht vom Mund weggerissen oder durch physische Angriffe beschädigt werden, aber durch 6+ Punkte magischen Schaden zerstört werden (wobei die meisten magischen Angriffe auch die Kreatur gefährden). Magie Bannen zerstört die Hand ohne Verletzung der Kreatur. Materialkomponente: V, S, M (ein Stoffhandschuh mit klebrigem Sirup oder Honig beschmiert).',
  description_en = 'Creates an appropriately sized hand that flies toward the chosen creature and clamps tightly over its mouth (saving throw negates). The affected creature cannot talk clearly, cast any spell requiring a verbal component, or use a magical item triggered by an audible command word. The hand cannot be pulled away or harmed by physical attacks, but can be destroyed by 6+ points of magical damage (though most magical attacks risk harming the creature). Dispel Magic destroys the hand without injury. Material component: V, S, M (a cloth glove smeared with sticky syrup or honey).'
WHERE LOWER(name_en) = LOWER('Bigby''s Silencing Hand') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Lässt eine Klingenwaffe aus der Hand des Zauberkundigen fliegen und einmal auf ein gewähltes Wesen zuschlagen. Der Zauberkundige muss nicht mit der Waffe geübt sein. Die Waffe schlägt einmal zu mit +4 magischem Bonus auf Angriff UND Schaden. Die Waffe wird nicht verbraucht, kehrt aber nicht zum Zauberkundigen zurück — sie fällt nach dem Angriff zu Boden. Überschreitet die Entfernung 3 m pro Stufe, fällt die Waffe an dieser Entfernungsgrenze zu Boden und der Zauber ist verschwendet. Materialkomponente: V, S, M (ein Haar des Zauberkundigen oder ein Faden seiner Kleidung).',
  description_en = 'Makes any bladed weapon fly from the caster''s hand to strike a chosen being once. The caster need not be proficient with the weapon. The weapon strikes once with +4 magical bonus on both attack AND damage rolls. The weapon is not consumed but does not return to the caster — it falls to the ground after the attack. If the caster tries to send it beyond 3 m per level, the weapon falls at that distance and the spell is wasted. Material component: V, S, M (a hair from the caster or a thread from the caster''s garments).'
WHERE LOWER(name_en) = LOWER('Bladeleap') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Für die Runde nach dem Wirken erhält jede einschneidige, hiebwaffentaugliche Klingenwaffe einen +3 Bonus auf den Angriffswurf (nicht auf Schaden). Die Klinge entzündet sich in feurig blauweißem Leuchten, das für alle sichtbar ist und verblasst, sobald die Waffe einen Gegner getroffen hat oder am Ende der nächsten Runde. Dieser Bonus addiert sich zu STR-Boni und magischen Boni der Waffe — ein Schwert +1 mit Bladethirst schlägt mit +4 zu. Nur ein Bladethirst-Zauber kann gleichzeitig auf einem Gegenstand liegen. Kann nicht permanent gemacht werden. Materialkomponente: V, S (plus M: ein Tropfen Blut und eine Prise gepulvertes Silber).',
  description_en = 'For the round following casting, any single-edged, slashing weapon gains a +3 bonus to hit (not to damage). The blade ignites with a fiery blue-white glow visible to all, which fades once the weapon strikes an opponent or at the end of the next round. This bonus stacks with STR bonuses and inherent magical bonuses — a sword +1 with Bladethirst strikes at +4. Only one Bladethirst can be placed on an item at a time. Cannot be made permanent. Material component: V, S (plus M: a drop of blood and a pinch of powdered silver).'
WHERE LOWER(name_en) = LOWER('Bladethirst') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Kann nur auf nichtlebende Materie gewirkt werden. Macht das Material vollständig geschmack- und geruchlos. Farbe, Textur etc. werden nicht beeinflusst. Eine giftige Substanz könnte so in Nahrung eingebracht werden und wäre nur durch verdächtige Farbe, Textur oder Konsistenz oder durch Gift Entdecken zu erkennen. Der Zauber selbst ist bei Lebensmitteln nur durch Magie Entdecken auffindbar. Materialkomponente: V, S, M (ein Drachme destilliertes Wasser).',
  description_en = 'Can only be cast on nonliving material. Renders the material completely tasteless and odorless. Color, texture, etc. are not affected. A poisonous substance could be inserted in food and detected only by suspicious color, texture, or consistency, or by Detect Poison. The spell itself, when used on foodstuffs, is detectable only by Detect Magic. Material component: V, S, M (a dram of distilled water).'
WHERE LOWER(name_en) = LOWER('Blandness') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Lässt freiliegende Knochen in einer heftigen Explosion zerbersten. Die Knochen können Teil eines einfachen untoten Skeletts, eines teilweisen Zombies oder unbelebter Skelettüberreste sein. Knochen von Kreaturen mit mehr als 4 TW/Stufen sind immun. Kann sofort oder zeitverzögert (wie Magischer Mund) wirken. Sofort: Explosion in 3-m-Radius-Kugel, 2W4 Schaden durch Knochensplitter (Rettungswurf für halben Schaden); untote Skelette werden zerstört. Untote erhalten einen RW — bei Erfolg nur ein kleiner Puff für 1W4+1 Schaden. Als Falle: Kann auf Überreste gewirkt werden, bevor sie als Untote belebt werden — dann kein RW für die Untoten. Kann durch Schrapnell-Material (z.B. Nägel in einem Zombie) verstärkt werden: Kreaturen innerhalb von 4,6 m werden von 1W12 Nägeln (je 1 Schaden) getroffen, plus 2W4 Knochensplitter-Schaden innerhalb von 3 m. Materialkomponente: V, S, M (ein Tropfen Wasser, ein Splitter Feuerstein).',
  description_en = 'Shatters exposed bones in a violent explosion. The bones can be part of a simple undead skeleton, partial zombie, or inanimate skeletal remains. Bones of creatures with more than 4 HD/levels are immune. Can trigger immediately or be delayed (like Magic Mouth). Immediately: explosion in 3 m radius sphere, 2d4 damage from bone shards (save for half); undead skeletons are destroyed. Undead get a save — on success, only a small puff for 1d4+1 damage. As a trap: can be cast on remains before they''re animated as undead — then no saves allowed. Can be augmented by shrapnel material (e.g., nails inside a zombie): creatures within 4.6 m are hit by 1d12 nails (1 damage each), plus 2d4 bone shard damage within 3 m. Material component: V, S, M (a drop of water, a fleck of flint).'
WHERE LOWER(name_en) = LOWER('Blastbones') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht die Übertragung von Blut von einem Spender, durch den Zauberkundigen, zu einem Empfänger. Pro wiederhergestelltem TP verliert der Spender einen TP. Die maximale Heilung beträgt 2 TP plus 1 pro Stufe des Zauberkundigen (Tagesmaximum pro Empfänger). Mehrere Spender sind möglich (erfordern jeweils separates Wirken), aber die Gesamtheilung kann das Maximum nicht überschreiten. Heilt nur Schaden durch Blutverlust (Waffen, Klauen, Bisse, Blutdrainierung) — nicht durch elektrischen Schock, Schläge, Gift, Erstickung oder rein magische Energie. Der Spender muss derselben Spezies angehören wie der Empfänger. Die Transfusion ist für den Zauberkundigen sehr anstrengend: −1 STR pro 5 übertragene TP und −1 KON pro Wirken (Erholung 1 pro 4 Stunden Ruhe). Blutentnahme von einem unwilligen Spender ist eine böse Tat — dieser muss für die gesamte Runde immobilisiert sein. Materialkomponente: V, S, M (zwei goldene Nadeln im Wert von je 1 GM; werden beim Wirken zerstört).',
  description_en = 'Allows transfer of blood from a donor, through the caster, into a recipient. For each HP restored to the recipient, the donor loses one HP. Maximum healing is 2 HP plus 1 per caster level (daily max per recipient). Multiple donors are possible (each requiring a separate casting), but total healing cannot exceed the maximum. Only heals damage from blood loss (weapons, claws, bites, blood drain) — not electrical shock, pummeling, poison, suffocation, or pure magical energy. The donor must be the same species as the recipient. The transfusion is extremely taxing for the caster: −1 STR per 5 HP transferred and −1 CON each casting (recovery 1 per 4 hours rest). Extracting blood from an unwilling donor is an evil act — they must be immobilized for the full round. Material component: V, S, M (two golden needles worth 1 gp each; destroyed in casting).'
WHERE LOWER(name_en) = LOWER('Bloodbridge') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht dem Zauberkundigen, die verbleibende Lebenskraft einer lebenden Kreatur grob einzuschätzen. Die Kreatur erhält einen Rettungswurf gegen Zauber mit −3 Abzug. Bei Erfolg erscheint das schwebende Bild einer Sanduhr nahe dem Kopf des Zauberkundigen, gefüllt mit leuchtendem Blut. Die obere Kammer zeigt den „gesunden" Anteil, die untere das „vergossene Blut". Das Bild ist für alle sichtbar (bis 15,2 m, auch in Dunkelheit), kann vom Zauberkundigen bewegt werden und erfordert keine Konzentration. Zeigt nicht die genauen TP, sondern den Anteil der verbleibenden Vitalität (z.B. ein Viertel voll bei einem Viertel der TP). Erlittener Schaden zeigt sich als rieselndes oder strömendes Blut — einzelne TP können nicht gezählt werden. Materialkomponente: V, S, M (eine kleine Sanduhr; wird beim Wirken verbraucht).',
  description_en = 'Allows the wizard to roughly gauge the vital force remaining in any living creature. The creature gets a saving throw vs. spell at −3. On success, the intangible image of an hourglass appears floating near the caster''s head, filled with luminous blood. The upper chamber shows the "healthy" portion, the lower the "blood spilled." The image is visible to all (up to 15.2 m, even in darkness), can be moved by the caster, and requires no concentration. Does not measure precise HP but rather the proportion of remaining vitality (e.g., quarter full at a quarter HP). Damage taken shows as trickling or streaming blood — individual HP cannot be counted. Material component: V, S, M (a small hourglass; consumed in casting).'
WHERE LOWER(name_en) = LOWER('Bloodglass') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht dem Zauberkundigen, eine sichtbare Wolke rauchigen Dampfes auszuatmen. Sie löst sich nach einer Runde auf, aber alle Kreaturen, die mit ihr in Kontakt kommen, müssen einen Rettungswurf gegen Gift bestehen oder sind für die folgende Runde betäubt — keine zusammenhängende, absichtliche Aktivität möglich. Der Zauberkundige ist nie von seinem eigenen Atem der Verwirrung betroffen; hat er den Zauber memoriert, auch nicht von dem eines anderen. Komponenten: V, S.',
  description_en = 'Allows the caster to breathe out a visible cloud of smoking vapor. It dissipates one round later, but all creatures contacting it must save vs. poison or be stunned for the following round — no coherent, deliberate activity possible. The caster is never affected by his own Breath of Bewilderment, nor (if he has this spell memorized) by anyone else''s. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Breath of Bewilderment') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht dem Zauberkundigen, alle atmenden Kreaturen innerhalb der Reichweite zu spüren — egal wie groß oder klein (außer Fische und Insekten). Der Zauberkundige kann sich bewegen und spürt weitere Kreaturen, sobald sie in Reichweite kommen. Zusammen mit der Wahrnehmung erhält er Kenntnis der ungefähren Größe der Kreatur. Komponente: V.',
  description_en = 'Allows the caster to sense all breathing creatures within range — no matter how large or small (excluding fish and insects). The caster can move, and as he moves within range of additional creatures he senses them. Along with this awareness comes knowledge of the creature''s approximate size. Component: V.'
WHERE LOWER(name_en) = LOWER('Breathsense — Pluma') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht Schiffen, bei bewölkten Nächten oder stürmischen Tagen zu navigieren, ohne den Kurs zu verlieren. Bei Wirkung erscheint eine Sternendarstellung ca. 9,1 m über dem Kopf des Zauberkundigen, die die korrekten Sternpositionen am Himmel zeigt. So kann ein Navigator nach dieser Projektion steuern. Kann auch in einer Schiffskabine (oder einem Gebäude für Studien- oder Dekorationszwecke) gewirkt werden — das Sternenfeld wird an die Decke projiziert. Der Zauber scheitert bei wolkenlosen Tagen. Materialkomponente: V, S, M (ein makelloser Silberspiegel, der beim Wirken himmelwärts gerichtet werden muss).',
  description_en = 'Enables ships to sail on cloudy nights or storm-swept days without losing their way. When cast, a display of stars appears about 9.1 m over the caster''s head, showing the correct positions of the stars in the sky. A navigator can steer by this projection. Can also be cast inside a ship''s cabin (or building for study or decorative effect), projecting the star field on the ceiling. The spell fails on cloudless days. Material component: V, S, M (an unblemished silver mirror that must be directed skyward during casting).'
WHERE LOWER(name_en) = LOWER('Calder''s Starry Sky') AND spell_type = 'wizard';
