-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 2 (Batch 4: 15 Spells — Darsson's Cooling Breeze to Drenal's Annoying Poke)
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  description = 'Eine weniger mächtige, aber länger anhaltende Version von Windstoß. Kann auf ein Objekt oder einen bestimmten Punkt gesetzt werden. Die Luft bewegt sich langsam im Uhrzeigersinn um das Zentrum mit max. 8 km/h — etwa wie ein Deckenventilator, viel zu schwach um ein Segelschiff zu bewegen. Nützlich um Luft in geschlossenen Räumen zirkulieren zu lassen und stickige Räume angenehmer zu machen. Besonders wirkungsvoll in Kombination mit großen Eisblöcken. Materialkomponente: V, S, M (eine getrocknete Hülsenfrucht).',
  description_en = 'A less powerful but longer lasting version of Gust of Wind. Can be placed on an object or at a specific point. The air moves slowly clockwise around the center at max 8 km/h — about like a ceiling fan, far too weak to move a sailing ship. Useful for keeping air moving in enclosed places, making stifling rooms more comfortable. Works well combined with large blocks of ice. Material component: V, S, M (a dried legume).'
WHERE LOWER(name_en) = LOWER('Darsson''s Cooling Breeze') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ein explosiver Feuerstoß, der einen Bereich von maximal 3 m³ füllt. Verursacht 1W4 Feuerschaden pro Stufe des Zauberkundigen (max. 10W4). Der Würfel füllt jeden offenen Raum im Wirkungsbereich, dehnt sich aber nicht darüber hinaus aus — in einem 1,5 m breiten, 2,1 m hohen Gang würde er einen 3 × 2,1 × 1,5 m Bereich füllen. Der Zauberkundige zeigt mit dem Finger und nennt Entfernung und Höhe. Ein orangefarbener Lichtstrahl schießt vom Finger und detoniert in Würfelform am Zielpunkt (oder bei vorzeitigem Aufprall auf ein festes Objekt). Rettungswurf gegen Zauber für halben Schaden. Entzündet alle Brennstoffe und schmilzt weiche Metalle. Materialkomponente: V, S, M (ein winziger Würfel Fledermausguano, etwas Schwefel und eine Phosphorflocke).',
  description_en = 'An explosive burst of flame filling an area of up to 3 m cube. Deals 1d4 fire damage per caster level (max 10d4). The cube fills any open space in its area but does not expand beyond it — in a 1.5 m wide, 2.1 m high corridor, it would fill a 3 × 2.1 × 1.5 m volume. The caster points and speaks the range (distance and height). An orange light streak flashes from the finger, detonating in cubic shape at the prescribed place (or on early impact with a solid object). Save vs. spell for half damage. Ignites all combustibles and melts soft metals. Material component: V, S, M (a tiny cube of bat guano, a small amount of sulphur, and a flake of phosphorus).'
WHERE LOWER(name_en) = LOWER('Darsson''s Fiery Cube') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt einen blendenden Lichtblitz im Wirkungsbereich. Jeder, der seinen Rettungswurf gegen Zauber nicht besteht, erleidet −4 auf Initiativewürfe, Angriffswürfe und Fertigkeitswürfe. Geblendete Individuen erleiden −20% Abzug auf alle Diebesfähigkeiten. Die Effekte halten 2W4 Runden an. Komponenten: V, S.',
  description_en = 'Creates a blinding flash of light in the area of effect. Everyone who fails a saving throw vs. spell suffers −4 on initiative rolls, attack rolls, and proficiency checks. Dazzled individuals receive −20% penalty to all thief abilities. Effects last 2d4 rounds. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Dazzle — Red Wizard') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erhöht die Erfolgschance einer prozentbasierten Diebesfähigkeit (Wahl beim Wirken) um 5% pro Stufe des Zauberkundigen. Gilt für alle Versuche während der Zauberdauer. Hat der Zauberkundige keine Diebesfähigkeiten, erhält er eine neue Fähigkeit mit 5% pro Stufe minus 10% Abzug (keine Rassen-, Rüstungs- oder GES-Boni). Die Diebesfähigkeit kann nicht über 99% steigen. Während der Zauber wirkt, kann der Zauberkundige keine Zauber wirken, aber andere Aktionen sind möglich. Kann jederzeit beendet werden. Komponenten: V, S.',
  description_en = 'Increases the success chance of one percentage-based thieving skill (chosen at casting) by 5% per caster level. Applies to all attempts during the spell''s duration. If the caster has no thief abilities, he gains one skill at 5% per level with a −10% penalty (no racial, armor, or DEX bonuses). The skill cannot exceed 99%. While the spell is in effect, the wizard cannot cast spells, but other actions are possible. Can be ended at will. Components: V, S.'
WHERE LOWER(name_en) = LOWER('DeGras''s Pilfering Fingers') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Umgibt den Zauberkundigen mit einer knisternden schwarzen Aura, die jede Kreatur verletzt, die damit in Kontakt kommt. Kreaturen, die den Zauberkundigen mit bloßen Händen oder natürlichen Waffen angreifen, müssen einen Rettungswurf gegen Todesmagie bestehen oder 2W6 Schaden erleiden. Der Zauberkundige nimmt vollen Schaden von erfolgreichen Angriffen. Betrifft normale Tiere, Monster ohne Waffen und Humanoide, die greifen, prügeln oder überwältigen. Waffen und Fernkampfangriffe verursachen normal Schaden ohne den Aura-Effekt. Der Zauber ist eine passive Verteidigung — der Zauberkundige selbst muss gegen die Effekte würfeln, wenn er einen Feind greift. Vorbereitung: Innerhalb von 8 Stunden vor dem Wirken muss der Zauberkundige 2 volle Runden mit einer seltenen Salbe (mind. 300 GM) einreiben. Materialkomponente: V, S, M (die seltene Salbe).',
  description_en = 'Surrounds the caster with a crackling black aura that injures any creature making contact. Creatures striking the wizard with bare hands or natural weapons must save vs. death magic or suffer 2d6 damage. The wizard takes full damage from successful attacks. Affects normal animals, unarmed monsters, and humanoids who grapple, pummel, or overbear. Weapons and ranged attacks deal damage normally without triggering the aura. The spell is a passive defense — the wizard himself must save if grasping an enemy. Preparation: within 8 hours before casting, the wizard must spend 2 full rounds anointing with a rare unguent (at least 300 gp). Material component: V, S, M (the rare unguent).'
WHERE LOWER(name_en) = LOWER('Death Armor') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht dem Zauberkundigen, die letzten Minuten des Lebens einer Kreatur oder Person zu sehen, die innerhalb der letzten 24 Stunden gestorben ist. Beim Berühren der Leiche fällt der Zauberkundige in Trance und hat eine Vision der letzten 10 Minuten des Lebens des Verstorbenen — aus dessen eigener Perspektive. Die Vision endet mit der letzten Szene, die das Opfer vor dem Tod sah, woraufhin der Zauberkundige aus der Trance erwacht. Materialkomponente: V, S, M (ein Fragment eines zerbrochenen Spiegels).',
  description_en = 'Enables the caster to visualize the final minutes of the life of any creature that died within the previous 24 hours. When touching the corpse, the caster enters a trance and has a vision of the subject''s final 10 minutes of life — from the subject''s own perspective. The vision ends with the last scene the subject saw before death, at which point the caster awakens. Material component: V, S, M (a fragment from a shattered mirror).'
WHERE LOWER(name_en) = LOWER('Death Recall') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ein kleines Holzstück verschwindet und wird durch einen 3 m langen, 5,1 cm dicken Stab aus magischer Kraft ersetzt. Nur der Zauberkundige kann den Stab führen — er hört auf zu existieren wenn er losgelassen oder durch Metall durchtrennt wird (Treffer gegen RK 0 nötig). Andere Kreaturen können den Stab greifen, aber nur bei einer Gesamtstärke über 18 können sie den Einsatz behindern. Als Waffe eingesetzt verursacht er 1W6 Schaden pro Treffer (normale Nichtgeübtheits-Abzüge wenn nicht mit Stäben geübt). Gilt als magische Waffe gegen Kreaturen, die nur von magischen Waffen getroffen werden. Einmal pro Zauber kann der Stab einem Ziel 1W4 zusätzliche TP entziehen (zusätzlich zum normalen Schaden, vor dem Angriffswurf entscheiden). Die entzogenen TP heilen den Träger (nur bestehenden Schaden). Materialkomponente: V, S, M (ein kleines Holzstück).',
  description_en = 'A small piece of wood vanishes and is replaced by a 3 m long, 5.1 cm diameter pole of magical force. Only the caster can wield the pole — it ceases to exist if released or cut by metal (requires a hit vs. AC 0). Other creatures can grasp it, but only if their total STR exceeds 18 can they hamper its use. As a weapon it deals 1d6 damage per hit (normal nonproficiency penalties if not proficient with staves). Counts as a magical weapon against creatures immune to normal weapons. Once per casting, the pole can drain 1d4 additional HP from a target (in addition to normal damage, must decide before attack roll). The drained HP heal the wielder (current damage only). Material component: V, S, M (a small piece of wood).'
WHERE LOWER(name_en) = LOWER('Decastave') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verdunkelt langsam und unauffällig den Raum, in dem sich der Ninja befindet. Die Veränderung dauert fünf Runden. Beim Abschluss ist der Raum so schattig und dunkel wie möglich, ohne Verdacht zu erregen — bei Tageslicht wirkt es, als hätte eine Wolke die Sonne verdeckt; bei Nacht, als wären Kerzen heruntergebrannt. Die Verdunklung erscheint nicht bedrohlich (aber Magie Entdecken enthüllt den Zauber). Der Zauberkundige erhält +2% pro Stufe auf seinen Im-Schatten-Verbergen-Wurf innerhalb des Effektbereichs — nur er, da nur er die Schattenverteilung vollständig versteht. Der Ninja muss den gesamten Raum mit dem Zauber abdecken können; reicht die Fläche nicht, schlägt der Zauber automatisch fehl. Komponente: S.',
  description_en = 'Slowly and inconspicuously darkens the room the ninja is in. The change takes five rounds. When complete, the room is as full of shadow as possible without arousing suspicion — in daylight it seems a cloud passed over the sun; at night the candles appear to have burned low. The dimming does not appear menacing (but Detect Magic reveals the spell). The caster receives +2% per level to hide in shadows within the effect area — only the caster, as only he fully understands the shadow patterns. The ninja must be able to cover the entire room; if insufficient area, the spell automatically fails. Component: S.'
WHERE LOWER(name_en) = LOWER('Deepen Shadows — Ninja') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt eine unsichtbare Lichtverzögerung. Der Alhoon kann eine oder mehrere Lichtquellen (natürlich oder magisch) berühren und einen verzögerten Lichtblitz in sie einpflanzen. Zu einem vom Alhoon bestimmten Zeitpunkt (oder auf ein Befehlswort) wird das gespeicherte Licht als greller Blitz freigesetzt, der alle Kreaturen im 6-m-Radius blendet (Rettungswurf gegen Zauber negiert). Geblendete Kreaturen erleiden −4 auf Angriffswürfe und RK für 1W4+1 Runden. Materialkomponente: V, S, M.',
  description_en = 'Creates an invisible light delay. The alhoon can touch one or more light sources (natural or magical) and implant a delayed light flash. At a time determined by the alhoon (or on a command word), the stored light is released as a harsh flash that blinds all creatures within a 6 m radius (save vs. spell negates). Blinded creatures suffer −4 on attack rolls and AC for 1d4+1 rounds. Material component: V, S, M.'
WHERE LOWER(name_en) = LOWER('Delayed Light — Alhoon') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Zauberkundige kann eine von zwei Versionen wählen: Kälte Verneinen oder Feuer Verneinen. Kälte Verneinen: Der Empfänger erleidet keinen Schaden durch natürliche Kälte (Schneestürme, Blizzards etc.) und erhält +2 auf Rettungswürfe gegen magische Kälte (Eissturm, Kältekegel etc.), wobei der Schaden bei erfolgreichem RW auf ein Viertel reduziert wird. Feuer Verneinen: Wie oben, aber für Hitze und Feuer. Beide Versionen: Pro Stufe können 2 Kreaturen geschützt werden. Der Schutz vor natürlichen Extremen ist vollständig; gegen magische Effekte gibt es nur den Bonus. Materialkomponente: V, S, M.',
  description_en = 'The caster chooses one of two versions: Deny Cold or Deny Fire. Deny Cold: The recipient takes no damage from natural cold (snowstorms, blizzards, etc.) and gains +2 on saves vs. magical cold (Ice Storm, Cone of Cold, etc.), with damage reduced to one-quarter on a successful save. Deny Fire: As above, but for heat and fire. Both versions: 2 creatures per caster level can be protected. Protection against natural extremes is complete; against magical effects only the bonus applies. Material component: V, S, M.'
WHERE LOWER(name_en) = LOWER('Deny Cold/Deny Fire') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Enthüllt dem Zauberkundigen, ob lebende Kreaturen in einem 3-m-Pfad pro Stufe anwesend sind. Der Zauber spürt die Anwesenheit, allgemeine Richtung und ungefähre Entfernung lebender Kreaturen. Es wird nicht offenbart, wie viele Kreaturen, ihre genaue Position oder was sie sind. Kann durch 0,3 m massiven Stein, 0,9 m Holz oder lose Erde oder eine dünne Metallschicht blockiert werden. Entdeckt keine Untoten, Konstrukte oder außerdimensionale Wesen. Materialkomponente: V, S.',
  description_en = 'Reveals to the caster whether living creatures are present in a 3 m path per level. The spell senses presence, general direction, and approximate distance of living creatures. Does not reveal how many, their exact position, or what they are. Blocked by 0.3 m of solid stone, 0.9 m of wood or loose earth, or a thin metal coating. Does not detect undead, constructs, or extraplanar beings. Material component: V, S.'
WHERE LOWER(name_en) = LOWER('Detect Life') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht dem Zauberkundigen, Lykanthropen im Wirkungsbereich zu entdecken, unabhängig von deren aktueller Form. Der Zauber zeigt die Anwesenheit und allgemeine Richtung, enthüllt aber nicht die genaue Art des Lykanthropen oder dessen genaue Position. Lykanthropen in Menschenform sind ebenso entdeckbar wie in Tierform oder Hybridform. Natürliche Lykanthropen und infizierte Lykanthropen werden gleichermaßen entdeckt. Materialkomponente: V, S, M.',
  description_en = 'Allows the caster to detect lycanthropes in the area of effect, regardless of their current form. The spell shows presence and general direction but does not reveal the exact type of lycanthrope or precise position. Lycanthropes in human form are as detectable as those in animal or hybrid form. Both natural and infected lycanthropes are detected equally. Material component: V, S, M.'
WHERE LOWER(name_en) = LOWER('Detect Lycanthrope') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Enthüllt Gift in einer einzelnen Kreatur oder einem einzelnen Objekt innerhalb der Reichweite. Der Zauberkundige hat eine Chance von 5% pro Stufe, die genaue Art des Giftes zu identifizieren. Zeigt auch an, ob Gift kürzlich angewandt wurde (innerhalb der letzten 24 Stunden). Funktioniert nicht gegen natürliche Gifte, die Teil des Körpers einer Kreatur sind (z.B. Schlangengift in der Drüse). Materialkomponente: V, S, M.',
  description_en = 'Reveals poison in a single creature or object within range. The caster has a 5% chance per level to identify the exact type of poison. Also indicates whether poison was applied recently (within the last 24 hours). Does not work against natural poisons that are part of a creature''s body (e.g., snake venom in the gland). Material component: V, S, M.'
WHERE LOWER(name_en) = LOWER('Detect Poison — Red Wizards') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Phaerimm spürt die Anwesenheit denkender Wesen in einer Sphäre um sich herum und erhält die oberflächlichsten Gedanken — emotionale Zustände, allgemeine Absichten (feindlich/freundlich), ob das Wesen sich konzentriert oder abgelenkt ist. Enthüllt nicht genaue Gedanken, Pläne oder Identitäten. Geschützte Geister (durch magische oder psionische Abschirmung) werden nicht entdeckt. Undead und geistlose Kreaturen bleiben unbemerkt. Komponente: V.',
  description_en = 'The phaerimm senses the presence of thinking beings in a sphere around itself and receives the most superficial thoughts — emotional states, general intentions (hostile/friendly), whether the being is concentrating or distracted. Does not reveal exact thoughts, plans, or identities. Protected minds (through magical or psionic shielding) are not detected. Undead and mindless creatures remain unnoticed. Component: V.'
WHERE LOWER(name_en) = LOWER('Detect Thought — Phaerimm') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt ein unsichtbares magisches Tagebuch, in das der Zauberkundige Gedanken und Beobachtungen mental diktieren kann. Das Tagebuch zeichnet die Worte des Zauberkundigen genau auf — auch Bilder, die der Zauberkundige sich vorstellt, können als Skizzen festgehalten werden. Die Einträge können nur vom Zauberkundigen abgerufen werden, indem er den Rückruf-Befehl spricht. Das Tagebuch kann bis zu 10 Seiten pro Stufe speichern. Materialkomponente: V, S, M.',
  description_en = 'Creates an invisible magical diary into which the caster can mentally dictate thoughts and observations. The diary records the caster''s words exactly — images the caster visualizes can also be captured as sketches. The entries can only be retrieved by the caster by speaking the recall command. The diary can store up to 10 pages per level. Material component: V, S, M.'
WHERE LOWER(name_en) = LOWER('Diary') AND spell_type = 'wizard';
