-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 2 (Batch 1: 15 Spells — Aerial Acceleration to Banish Dazzle)
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  description = 'Betrifft eine einzelne fliegende Kreatur (natürlich oder magisch befähigt). Reduziert den Luftwiderstand und erhöht die Flugbewegungsrate um 50%. Bei dieser erhöhten Geschwindigkeit verschlechtert sich die Manövrierklasse um eine Stufe, und spezielle Flugmanöver (z.B. Ergreifen) sind unmöglich. Die Kreatur muss nicht mit der erhöhten Rate fliegen. Der Zauber kann nicht nach Belieben abgebrochen werden, aber Magie Bannen oder ein mächtigerer Zauber kann ihn beenden. Drachen nutzen diesen Zauber vor Luftschlachten, um Gegner zu überraschen oder Verfolgern zu entkommen. Komponente: V.',
  description_en = 'Affects a single flying creature (natural or magically empowered). Reduces air friction and increases flying movement rate by 50%. At this increased speed, maneuverability class worsens by one step and special aerial maneuvers (e.g., snatch) are impossible. The creature is not required to move at the increased rate. The spell cannot be cancelled at will, but Dispel Magic or a more powerful spell can end it early. Dragons use this spell before aerial battles to surprise opponents or outdistance pursuers. Component: V.'
WHERE LOWER(name_en) = LOWER('Aerial Acceleration — Dragon') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ein Feuerstrahl schießt von den Fingerspitzen des Zauberkundigen auf ein gewähltes Ziel. Der Strahl ist 0,6 m breit und 18,3 m lang. Das Ziel erleidet 3W6 Feuerschaden in der ersten Runde und weitere 3W6 in der Folgerunde, wenn es in Reichweite bleibt. Kein Rettungswurf für das Hauptziel, aber Feuerschutz-Fähigkeiten (Feuerresistenz etc.) können den Schaden reduzieren oder eliminieren. Andere Kreaturen im Pfad des Strahls können mit einem Rettungswurf gegen Zauber 2W8 Feuerschaden vermeiden (bei Erfolg 1W8). Der Zauberkundige kann in der zweiten Runde keine anderen Aktionen ausführen. Brennbare Materialien im Pfad fangen Feuer. Komponenten: V, S.',
  description_en = 'A jet of flame bursts from the caster''s fingertips toward one chosen target. The jet is 0.6 m wide and 18.3 m long. The target takes 3d6 fire damage in the first round and 3d6 more the following round if it remains within range. No saving throw for the primary target, but anti-fire capabilities (fire resistance, etc.) may reduce or eliminate damage. Other creatures in the flame jet''s path can save vs. spell to avoid 2d8 fire damage (on success, 1d8). The caster cannot perform other actions during the second round. Flammable materials in the path catch fire. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Agannazar''s Scorcher') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Wird gegen psionische Gegner eingesetzt. Erzeugt eine mentale Falle im Geist des Empfängers. Unwillige Empfänger erhalten einen Rettungswurf gegen Zauber. Die Falle entlädt sich sofort bei jedem psionischen Kontakt oder Angriff sowie bei geistkontaktierenden Zaubern wie ESB und Telepathie. Die Falle verursacht 1W4 + 1 Schadenspunkt pro Stufe des Zauberkundigen am Initiator des Kontakts (Rettungswurf gegen Zauber für halben Schaden). Materialkomponente: V, S, M (grob gemahlenes Glas, das im Kreis um den Empfänger gestreut werden muss).',
  description_en = 'Used against psionic opponents. Creates a mental trap in the subject''s mind. Unwilling recipients get a saving throw vs. spell. The trap instantly discharges upon any psionic contact or attack, as well as mind-contacting spells such as ESP and Telepathy. The trap deals 1d4 + 1 damage per caster level to the initiator of the contact (save vs. spell for half damage). Material component: V, S, M (roughly ground glass that must be sprinkled in a circle around the recipient).'
WHERE LOWER(name_en) = LOWER('Agra''s Ambush') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt ein eindrucksvolles Fanfarensignal und lässt ein Banner in der Luft erscheinen, wo immer der Zauberkundige es innerhalb der Reichweite wünscht. Das Banner kann beliebige Größe und Erscheinung haben — von starr und schildartig bis zu einem langen Wimpel, neu oder alt wirkend. Der Zauberkundige kann wählen, ob es leuchtet (Lichtstärke bis zu einem Licht-Zauber, in gewünschter Farbe und Intensität). Die Fanfare dauert höchstens eine Runde und kann auch fehlen. Das Banner muss ein Wappen, Emblem oder Zeichen zeigen, das der Zauberkundige tatsächlich gesehen hat. Beliebt als Schlachtfeld-Erkennungszeichen, Sammelpunkt oder Richtungsmarker. Materialkomponente: V, S, M (eine echte Trompete/ein Horn oder ein Miniaturmodell davon).',
  description_en = 'Creates an impressive fanfare and a banner appears in midair wherever the caster desires within range. The banner can be any size and appearance — from rigid and shield-like to a long pennant, looking new or ancient. The caster can choose whether it glows (light equivalent up to a Light spell, in desired hue and intensity). The fanfare lasts only one round or less and can be absent. The banner must show a decoration, coat-of-arms, or rune the caster has actually seen. Popular as a battlefield recognition symbol, rally device, or directional marker. Material component: V, S, M (a real trumpet/horn or a miniature model of one).'
WHERE LOWER(name_en) = LOWER('Alustriel''s Banner') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht dem Zauberkundigen, einen Dolch, Wurfpfeil oder eine andere stechende Waffe (kürzer als der Unterarm) in gerader Linie auf ein Ziel innerhalb von 18,3 m abzufeuern. Der Zauberkundige muss mit der Waffe geübt sein. Die Waffe greift jede Runde einmal an, als wäre sie von einem Magier 2 Stufen über dem Zauberkundigen geführt, verursacht +1 Extraschaden pro Treffer und kehrt dann in die Hand des Zauberkundigen zurück (Flugrate 12, MK: A). Gilt als +1 magische Waffe. Um die Rückkehr zu verhindern, muss das getroffene Ziel einen GES-Wurf zum Ergreifen und dann einen STR-Wurf zum Festhalten bestehen. Wenn die Hände des Zauberkundigen belegt sind, schwebt die Waffe bewegungslos in der Luft, bis eine Hand frei wird. Komponenten: V, S.',
  description_en = 'Allows the caster to fire a dagger, dart, or other piercing weapon shorter than the forearm in a straight line at a foe within 18.3 m. The caster must be proficient with the weapon. The weapon attacks once per round as if wielded by a wizard two levels higher, deals +1 extra damage per hit, and returns to the caster''s hand (fly rate 12, MC: A). Counts as +1 magical weapon. To prevent the return, the struck target must make a DEX check to grasp and a STR check to retain hold. If the caster''s hands are busy, the weapon hovers motionless nearby until a hand is free. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Alustriel''s Fang') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht dem Zauberkundigen und anderen Personen (bis zu 30 bei Stufe 10), sich in jedem Außengelände zu verbergen. Die verborgenen Charaktere müssen einigermaßen still und leise bleiben, sonst wird der Zauber gebrochen. Solange sie dies tun, verschmelzen sie mit der Landschaft — ob Bäume, kurzes Gras oder flache Sandfläche. Der Anführer einer sich nähernden Gruppe erhält einen Rettungswurf gegen Zauber. Bei Erfolg wird die Magie aufgehoben und der Anführer hat die normale Chance, die Hinterhalttruppe zu entdecken. Bei Misserfolg wird die Gruppe überrascht, sofern keine anderen Faktoren eingreifen. Komponenten: V, S, M.',
  description_en = 'Allows the caster and other individuals (up to 30 at 10th level) to conceal themselves in any kind of outdoor terrain. The hidden characters must remain reasonably still and silent or the spell breaks. As long as they do, they blend in with the landscape — trees, short grass, even flat sand. The leading character of an approaching party gets a saving throw vs. spell. On success, the magic is negated and the leader has the normal chance to discover the ambushers. On failure, the party is surprised unless other factors intervene. Components: V, S, M.'
WHERE LOWER(name_en) = LOWER('Ambush — Hishna') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Nur im Freien wirksam. Beschwört ein normales Waldtier innerhalb von 1,6 km. Das Tier erhält einen Rettungswurf gegen Zauber. Der SL bestimmt die Art (abhängig von Gelände und Stufe des Zauberkundigen); die TW müssen gleich oder weniger als die halbe Stufe sein. Das Tier ist freundlich zum Wu Jen und bleibt bei ihm, solange er durch die Wildnis reist (maximal 32,2 km von seinem Zuhause). Beim Betreten von Siedlungen trennt es sich. Misshandlung führt dazu, dass es geht oder sich gegen den Zauberkundigen wendet. Kein telepathischer Kontakt, aber das Tier versteht den allgemeinen Sinn gesprochener Befehle. Es verteidigt den Wu Jen nach besten Kräften — ein Affe bevorzugt Belästigung, ein Tiger springt furchtlos in den Kampf. Materialkomponente: V, S, M (ein Stück Süßigkeit oder eine andere Leckerei).',
  description_en = 'Only effective outdoors. Summons one normal woodland creature within 1.6 km. The creature gets a saving throw vs. spell. The DM determines the type (based on terrain and caster level); HD must equal or be less than half the caster''s level. The beast is friendly and stays with the wu jen while traveling through wilderness (max 32.2 km from home). Upon entering settlements, it parts company. Mistreatment causes it to leave or turn on the caster. No telepathic communication, but the animal understands the general meaning of spoken commands. It defends the wu jen to the best of its ability — a monkey prefers harassment, a tiger fearlessly springs into combat. Material component: V, S, M (a piece of candy or other tasty morsel).'
WHERE LOWER(name_en) = LOWER('Animal Companion') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Spezialisierte Version von Tote Beleben, die ein Skelett pro Stufe des Zauberkundigen erzeugt. Die Skelette gehorchen einfachen verbalen Befehlen und bleiben belebt, bis sie im Kampf zerstört oder von einem Priester vertrieben werden — die Magie kann nicht gebannt werden. Nur Skelette von Menschen, Halbmenschen und zweibeinigen Humanoiden mit 1 TW oder weniger können belebt werden. Die ehemalige Erfahrungsstufe wird ignoriert; die neuen Skelette werden als normale Skelette behandelt. Der Zauberkundige muss die Knochen mit einer speziellen Salbe einreiben (mind. 10 GM pro Dosis). Eine Dosis belebt ein Skelett und braucht eine Runde zum Auftragen. Der Zauberkundige kann bis zu 24 Stunden warten, bevor er den Belebungszauber mit einem Wort vollendet. Materialkomponente: V, S, M (ein Tropfen Blut, eine Prise Knochenpulver, spezielle Salbe).',
  description_en = 'Specialized version of Animate Dead that produces one skeleton per caster level. The skeletons obey simple verbal commands and remain animated until destroyed in combat or turned by a priest — the magic cannot be dispelled. Only skeletons of humans, demihumans, and bipedal humanoids of 1 HD or less can be animated. Former experience levels are ignored; newly animated skeletons are treated as normal skeletons. The caster must rub the bones with a special salve (at least 10 gp per dose). One dose animates one skeleton and requires one round to apply. The caster can wait up to 24 hours before finishing the animation with a single word. Material component: V, S, M (a drop of blood, a pinch of bone powder, special salve).'
WHERE LOWER(name_en) = LOWER('Animate Skeletons') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Belebt eine Wassermenge bis zu 1,5 m³ pro Stufe. Der Wu Jen kann das Wasser nicht formen, aber es in jede gewünschte Richtung fließen lassen. Solange der Wu Jen sich konzentriert, bewegt sich das Wasser mit Rate 6. Das Wasser unterliegt weiterhin Verdunstung, Absorption und Schwerkraft — Feuer und Hitze lösen es schnell auf, Erde saugt es auf und bildet Schlamm. Das Wasser kann sanfte Steigungen erklimmen, aber Wände, Treppen und abrupte Anstiege sind unpassierbar. Bei Verwendung als Angriff verursacht das Wasser 1-2 Schaden pro 1,5-m-Würfel, als Welle gegen Gegner krachend. Während der Konzentration kann sich der Wu Jen mit Rate 3 bewegen, aber keine anderen Aktionen ausführen. Bei Konzentrationsunterbrechung endet der Zauber. Materialkomponente: V, S, M (eine kleine Phiole reinen Quellwassers mit Zinnober vermischt).',
  description_en = 'Animates a volume of water up to 1.5 m³ per level. The wu jen cannot shape the water but can bid it to flow in any desired direction. While concentrating, the water moves at rate 6. The water is still subject to evaporation, absorption, and gravity — fire and heat quickly destroy it, earth turns to mud absorbing most of it. The water can climb gentle grades but walls, staircases, and abrupt rises are impassable. When used to attack, the water deals 1-2 damage per 1.5 m cube, crashing as a wave against opponents. While concentrating, the wu jen can move at rate 3 but take no other actions. If concentration is broken, the spell ends. Material component: V, S, M (a small vial of pure spring water mixed with cinnabar).'
WHERE LOWER(name_en) = LOWER('Animate Water') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verwandelt das Gesicht des Empfängers in eine schreckliche und furchteinflößende Maske. Der Zauberkundige kann fast jede Kombination abscheulicher Züge erzeugen — blaue Haut, Papageiengesicht, Elefantennase, verrottende Hauer. Erlaubt nicht, das Aussehen einer bekannten Kreatur zu duplizieren, aber Teile verschiedener Kreaturen können kombiniert werden. Die Überraschungschance von Gegnern erhöht sich um +1. Kreaturen mit 1 TW/Stufe oder weniger müssen einen Rettungswurf gegen Zauber bestehen oder fliehen für 1W3 Runden in Panik. Der Zauber unterscheidet nicht zwischen Freund und Feind — alle Betrachter (auch der Empfänger) sind betroffen. Unwillige Opfer erhalten einen Rettungswurf. Materialkomponente: V, S, M (eine Miniaturpalette mit verschiedenfarbigen Farben).',
  description_en = 'Transforms the recipient''s face into a horrible and terrifying mask. The caster can create nearly any combination of hideous features — blue skin, parrot face, elephantine nose, rotting tusks. Does not allow duplicating the appearance of any known creature, but portions from different creatures can be combined. Opponents'' surprise chance increases by +1. Creatures with 1 HD/level or less must save vs. spell or flee in fright for 1d3 rounds. The spell does not distinguish friend from foe — all who look upon it (even the recipient) are affected. Unwilling victims get a saving throw. Material component: V, S, M (a miniature palette dotted with paints of assorted colors).'
WHERE LOWER(name_en) = LOWER('Apparition') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Beschwört einen Ghul als Gehilfen und Vertrauten des Nekromanten. Der Zauberkundige kann leicht mit dem Ghul kommunizieren und teilt eine empathische Verbindung. Er kann mentale Befehle auf bis zu 1,6 km erteilen und erhält emotionale Rückmeldungen (Zorn, Furcht, Hunger). Der Ghul dient als Wache, Kundschafter oder Spion, aber der Nekromant muss ihn gut füttern und einen geeigneten Unterschlupf bereitstellen. 5%-Chance, stattdessen einen Ghast anzulocken (greift unter 6. Stufe an, dient sonst wie ein Ghul). Der beschwörene Ghul hat mindestens 10 TP und durchschnittliche Intelligenz. Maximal ein Ghul-Diener gleichzeitig. Bleibt der Ghul länger als eine Woche über 1,6 km entfernt, bricht die Bindung. Wird der Ghul zerstört, muss der Nekromant einen Systemschock-Wurf bestehen oder wird für 1W6 Stunden handlungsunfähig. Kann nur einmal pro Jahr gewirkt werden. Materialkomponente: V, S, M (ein Räuchergefäß mit Myrrhe und bitteren Kräutern, Mindestwert 500 GM).',
  description_en = 'Summons a ghoul to act as the necromancer''s aide and familiar. The caster can converse easily with the ghoul and shares an empathic link. He can issue mental commands at up to 1.6 km range, receiving emotional responses (anger, fear, hunger) in return. The ghoul serves as guard, scout, or spy, but the necromancer must keep it well-fed and provide a suitable lair. 5% chance to attract a ghast instead (attacks unless caster is 6th level or higher, otherwise serves as a ghoul). The summoned ghoul has at least 10 HP and average Intelligence. Maximum one ghoul servant at a time. If the ghoul remains more than 1.6 km distant for a full week, the bond breaks. If the ghoul is destroyed, the necromancer must make a system shock check or be incapacitated for 1d6 hours. Can only be cast once per year. Material component: V, S, M (a censer of myrrh and bitter herbs worth at least 500 gp).'
WHERE LOWER(name_en) = LOWER('Attract Ghoul') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ein Drache verstärkt seine Furchtaura durch eine Illusion, die sein Erscheinungsbild bedrohlicher macht: Kampfnarben, veränderte Züge, längere Stacheln, Reißzähne und Klauen. Die Illusion kann die Größe oder Art des Drachen nicht ändern, lässt ihn aber älter wirken. Der Drache gewinnt zwei Alterskategorien für die Bestimmung von Reichweite, Rettungswurf und Effekt seiner Furchtaura. Junge Drachen erhalten eine Furchtaura, die sie normalerweise nicht hätten; ältere Drachen eine mächtigere. Rettungswürfe gegen die Aura erleiden −2 Abzug für Drachen ab „Junger Erwachsener". Die verstärkte Aura verursacht Panik bei Kreaturen bis 2 TW und Furcht bei Kreaturen, die normalerweise nicht betroffen wären (bis zu 2 TW über der normalen Grenze). Keine Konzentration nötig. Kreaturen können den Ungläubigkeitswurf vs. Zauber versuchen, aber normale Furchtaura-RW gelten weiterhin. Komponente: V.',
  description_en = 'A dragon enhances its fear aura through an illusion making it appear more menacing: battle scars, altered features, longer spine-spikes, fangs, and talons. The illusion cannot change size or species but makes the dragon seem older. The dragon gains two age categories for determining range, saving throw, and effect of its fear aura. Young dragons gain a fear aura they normally wouldn''t have; older dragons gain a more powerful one. Saving throws suffer −2 penalty for dragons of "young adult" age and older. The enhanced aura causes panic in creatures up to 2 HD and fear in creatures normally unaffected (up to 2 more HD than normal). No concentration needed. Creatures can attempt a disbelief save vs. spell, but normal fear aura saves still apply. Component: V.'
WHERE LOWER(name_en) = LOWER('Aura of Terror — Dragon') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Macht ein Wesen, mit dem der Zauberkundige spricht, verwirrt und desorientiert. Das verwirrte Wesen ist zu keiner rationalen Handlung oder Unterhaltung fähig und sitzt still da, vor sich hinmurmelnd. Wird das Wesen angegriffen, wird der Zauber gebrochen sobald der erste Schaden zugefügt wird. Zauberkundiger und Ziel müssen sich in einer Unterhaltung befinden, und der Zauberkundige muss Blickkontakt mit dem Ziel herstellen. Komponenten: V, S.',
  description_en = 'Makes a being the caster is speaking to become confused and disoriented. The baffled being is incapable of any rational action or conversation, sitting quietly and mumbling to himself. If the being is attacked, the spell breaks as soon as the first damage is dealt. The caster and subject must be engaged in conversation, and the caster must make eye contact with the subject. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Bafflement — Pluma') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Belebt einen erschöpften Empfänger. Die betroffene Kreatur fühlt sich, als hätte sie eine angemessene Ruheperiode (z.B. eine Nachtruhe) gehabt und kann weitere 16 Stunden problemlos aktiv sein. Erlaubt NICHT die Wiederherstellung verlorener Zauber oder Trefferpunkte und lindert weder Hunger, Durst noch Krankheit. Ein zweites Wirken vor Ablauf des ersten verlängert die Wachzeit um weitere 16 Stunden, aber am Ende muss der gesamte versäumte Schlaf nachgeholt werden (z.B. 16 Stunden Schlaf nach zwei Wirkungen). Ein Wesen, das durch mehrere Wirkungen länger als 48 Stunden wach bleibt, verliert 1 TP pro 8-Stunden-Periode über 48 Stunden hinaus. Komponenten: V, S.',
  description_en = 'Revives an exhausted recipient. The affected creature feels as though it had an appropriate rest period (e.g., a night''s sleep) and can easily operate for 16 more hours. Does NOT allow recovery of lost spells or hit points, nor does it alleviate hunger, thirst, or illness. A second casting before the first ends extends wakefulness by another 16 hours, but all missed sleep must be made up when the second spell ends (e.g., 16 hours of sleep after two castings). A being kept awake more than 48 hours by multiple castings loses 1 HP per 8-hour period beyond 48 hours. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Balliard''s Rejuvenating Touch') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht dem Empfänger, in blendender Sonne klar zu sehen, frei von Hitzeflimmern. Der Empfänger erkennt, dass Luftspiegelungen und gewöhnliche Illusionen (Ergebnis von Zaubern der 5. Stufe oder niedriger) nicht real sind. Gewährt +4 Rettungswurfbonus gegen Farbsprühen, Feuerzauber und ähnliche visuelle Zauber basierend auf Farbe, Hitze oder Feuer. Reflektiertes Sonnenlicht (Spiegel, glänzendes Schild) behindert nicht. Verhindert Blendung durch helles Licht, einschließlich Dauerlicht und Sonnenblendung. Kann die Effekte von Sonnenblendung und Licht-Zaubern aufheben, nicht aber von Dauerlicht oder mächtigeren Zaubern. Kein Schutz gegen Machtwort: Blindheit. Materialkomponente: V, S, M (eine Scherbe aus Glas, Edelstein, Glimmer oder klarem Kristall; wird beim Wirken verbraucht).',
  description_en = 'Enables the recipient to see clearly in or through blinding sun, free from heat shimmer effects. The recipient knows that mirages and common illusions (5th-level spells or less) are not real. Grants +4 saving throw bonus vs. Color Spray, Fire Charm, and similar visual spells related to color, heat, or fire. Reflected sunlight (mirror, shiny shield) does not hinder. Prevents blinding by bright light including Continual Light and Sundazzle. Can remove effects of Sundazzle and Light spells, but not Continual Light or more powerful spells. No protection against Power Word: Blind. Material component: V, S, M (a shard of glass, gemstone, mica, or clear crystal; consumed in casting).'
WHERE LOWER(name_en) = LOWER('Banish Dazzle') AND spell_type = 'wizard';
