-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 4 (Batch 2: 15 Spells — Bigby's Battering Gauntlet to Blood Lightning)
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  description = 'Erzeugt einen schimmernden violetten Rammbock aus Kraft in Form eines 3,7 m langen, 0,6 m dicken Zylinders mit einer geballten Faust als Kopf (verkürzbar auf 0,9 m für enge Räume). Zerstört eine normale Tür mit einem Treffer, eine verstärkte Tür mit drei, eine Steintür mit fünf Treffern, und hat 50% Chance eine Metalltür zu zerstören (bei Misserfolg wird der Rammbock zerstört). Ein Angriff pro Runde. Gegen magisch verstärkte Türen: RW auf Stufe des verstärkenden Magiers — bei Erfolg wird der Rammbock zerstört. Hat KEINE Wirkung gegen lebende Ziele. Der Zauberkundige muss innerhalb von 18,3 m bleiben. Immun gegen physische Angriffe, zerstörbar durch magischen Schaden gleich der halben TP des Zauberkundigen. Funktioniert nur gegen Portale, die zum Öffnen gedacht sind. Materialkomponente: V, S, M (ein Metallstab mit einem Kettenhandschuh über einem Ende).',
  description_en = 'Creates a shimmering violet battering ram of force: 3.7 m long, 0.6 m diameter cylinder with a clenched fist head (shortenable to 0.9 m for cramped spaces). Destroys a normal door in 1 hit, reinforced in 3, stone in 5, 50% chance for metal door (ram destroyed on failure). One attack per round. Against magically reinforced doors: save at the reinforcing wizard''s level — success destroys the gauntlet. Has NO effect against living targets. The caster must stay within 18.3 m. Immune to physical attacks, destroyed by magical damage equal to half the caster''s HP. Only works against portals designed to open. Material component: V, S, M (a metal rod with a chain mail gauntlet over one end).'
WHERE LOWER(name_en) = LOWER('Bigby''s Battering Gauntlet') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Beschwört körperlose Hände, die die Arbeit einer ganzen Bautruppe erledigen. Pro Stufe ein Paar Hände, alle mit Zimmermannswerkzeug ausgestattet. Sie arbeiten wie ein professionelles Team von Zimmerleuten, Maurern, Bergleuten oder Sappern. Die Hände brauchen weder Ruhe noch Nahrung, jedes Paar arbeitet wie ein Arbeiter. Können nicht kämpfen oder physischen Schaden verursachen. Unzerstörbar durch nichtmagische Mittel; jedes Paar hat so viele TP wie der Zauberkundige Stufen hat. Dauer 12 Stunden. Materialkomponente: V, S, M (eine Auswahl miniaturisierter Werkzeuge im Wert von mind. 500 GM).',
  description_en = 'Summons disembodied hands doing the work of an entire construction crew. One pair per caster level, all equipped with carpentry tools. They work as a professional team of carpenters, masons, miners, or sappers. The hands never need rest or food; each pair performs as one worker. Cannot fight or inflict physical damage. Indestructible by nonmagical means; each pair has as many HP as the caster has levels. Duration 12 hours. Material component: V, S, M (an assortment of miniature tools worth at least 500 gp).'
WHERE LOWER(name_en) = LOWER('Bigby''s Construction Crew') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt eine sichtbare Kraftebene, die in jede vom Zauberkundigen gewünschte Form gebracht werden kann: Tisch, Leiter, Keule, Eimer, Stelzen etc. Einmal geformt, behält sie ihre Form für die Dauer. Das imitierte Objekt muss ziemlich starr sein, darf keine beweglichen Teile haben, keine Spitze oder Schneide und keine fein detaillierten Merkmale. Seil, Langbogen, Schwert, Streitwagen oder genaue Statuen können NICHT erzeugt werden. Immun gegen physische Angriffe, kann durch magischen Schaden zerstört werden, der die TP des Erschaffers übersteigt. Bis zu 0,03 m³ pro Stufe können simuliert werden. Materialkomponente: V, S, M (ein Klumpen weicher Ton mit Diamantstaub).',
  description_en = 'Creates a visible plane of force shapeable into any form: table, ladder, club, bucket, stilts, etc. Once formed, retains shape for the duration. The imitated object must be fairly rigid, no moving parts, no sharp points or edges, and no fine details. Rope, longbow, sword, chariot, or accurate statues CANNOT be created. Immune to physical attacks, can be destroyed by magical damage exceeding the creator''s HP. Up to 0.03 m³ per level can be simulated. Material component: V, S, M (a lump of soft clay with diamond dust mixed in).'
WHERE LOWER(name_en) = LOWER('Bigby''s Force Sculpture') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ähnlich Vogelzauber I, aber mächtiger. Ermöglicht das Beschwören und Kontrollieren aller Arten gefiederter Kreaturen — einschließlich des mächtigen Couatl und anderer monströser Wesen mit Gefieder (z.B. Eulenbären). Wirkt nicht auf Gottheiten. Verzauberte Kreaturen können komplexere Befehle erhalten als beim niedrigstufigen Zauber: Papageien und Aras können Nachrichten von bis zu 100 Wörtern übermitteln, verzauberte Kreaturen greifen furchtlos an wenn befohlen. Materialkomponente: V, M (eine Pfeife aus einem feinen Stück Jade geschnitzt; dauert 2-5 Wochen).',
  description_en = 'Similar to Bird Charm I but more powerful. Allows summoning and controlling all types of feathered creatures — including the powerful couatl and other monstrous plumed beings (e.g., owlbears). Does not affect deities. Enchanted creatures can receive more complex commands: parrots and macaws relay messages up to 100 words, charmed creatures attack fearlessly if ordered. Material component: V, M (a whistle carved from fine jade; carving takes 2-5 weeks).'
WHERE LOWER(name_en) = LOWER('Bird Charm II — Pluma') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ein schwarzer Kraftstoß detoniert am gewünschten Fokuspunkt und verursacht 1W4 + 1 Schaden pro Stufe an allen Kreaturen im 3-m-Radius. Kreaturen, die den Rettungswurf gegen Zauber nicht bestehen, werden in einer 3-m-Radius-Kraftkugel für die Zauberdauer eingesperrt — Entkommen nur mit Mitteln, die eine Kraftwand zerstören würden. Bei erfolgreichem RW wird die Kreatur aus dem eingekapselten Bereich herausgeblasen (nimmt aber trotzdem Schaden). Materialkomponente: V, S, M (ein kleines Stück Holzkohle und ein kleines Stück Onyx).',
  description_en = 'A black force burst erupts at the desired focal point, dealing 1d4 + 1 damage per caster level to all creatures in a 3 m radius. Creatures failing a save vs. spell are trapped in a 3 m radius sphere of force for the duration — escape only by means that destroy a Wall of Force. A successful save blows the creature out of the encapsulated area (but still takes damage). Material component: V, S, M (a small piece of charcoal and a small piece of onyx).'
WHERE LOWER(name_en) = LOWER('Blacksphere') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Kann auf den Zauberkundigen oder eine berührte Kreatur gewirkt werden und aktiviert sich erst, wenn die Kreatur das nächste Mal blutet. Praktisch unentdeckbar bis zur Aktivierung (nur Fluch Aufheben verhindert die Auslösung). Innerhalb einer Runde nach dem ersten Bluten kann die Kreatur durch stillen Willen das Blitzblut freisetzen. Wenn nicht, heilt die Magie 1W4+1 TP und vergeht. Bei Freisetzung: ein Netz aus springenden blutroten Blitzen rast aus allen Wunden — verursacht 6W6 Schaden an allen Wesen innerhalb von 12,2 m (Rettungswurf gegen Zauber für halben Schaden). Der Freisetzer wird nie durch sein eigenes Blitzblut verletzt und kann ein Wesen durch direkten Kontakt vor Schaden schützen. Nach 24 Stunden ohne Aktivierung vergeht die Magie. Nicht kumulativ. Materialkomponente: V, S, M.',
  description_en = 'Can be cast on the caster or a touched creature, activating only when the creature next bleeds. Virtually undetectable until triggered (only Remove Curse prevents activation). Within a turn after first bleeding, the creature can release the blood lightning by silent will. If not, the magic heals 1d4+1 HP and dissipates. On release: a web of leaping blood-red lightning rages from all wounds — deals 6d6 damage to all beings within 12.2 m (save vs. spell for half). The releaser is never harmed by their own blood lightning and can protect a touched being from damage. After 24 hours without activation, the magic dissipates. Not cumulative. Material component: V, S, M.'
WHERE LOWER(name_en) = LOWER('Blood Lightning') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verleiht einer Kreatur tierischer Intelligenz oder weniger Sapienz (Bewusstsein). Systemschock-Wurf nötig — bei Überleben neue Intelligenz mit 3W6 auswürfeln. Auch bei halbintelligenten Kreaturen (INT 2+) möglich: erlaubt einen Neuwurf mit 3W6, aber bei keiner Verbesserung sinkt die INT um 1. Der Prozess ist äußerst schmerzhaft und anstrengend — der Zauberkundige kann 24 Stunden lang keine Zauber über der 3. Stufe wirken (ohne eigenen Systemschock-Wurf). Erfordert mindestens eine volle Woche Vorbereitung in einem Labor. Kann pro Kreatur nur einmal durchgeführt werden. Ergebnisse sind nur durch vollen Wunsch-Zauber änderbar. Die verliehene Intelligenz wird NICHT an Nachkommen weitergegeben (außer mit Alter Beast fixiert). Materialkomponente: V, S, M (ein getrockneter Fisch und ein Stück Hirnkoralle).',
  description_en = 'Grants sapience to a creature of animal Intelligence or less. System shock roll required — on survival, roll 3d6 for new Intelligence. Also works on semi-intelligent creatures (INT 2+): allows an INT reroll with 3d6, but if no improvement, INT decreases by 1. The process is excruciatingly painful and taxing — the caster cannot cast spells above 3rd level for 24 hours (without own system shock roll). Requires at least one full week of preparation in a laboratory. Can only be performed once per creature. Results only changeable by a full Wish. The granted intelligence is NOT passed to offspring (unless locked with Alter Beast). Material component: V, S, M (a dried fish and a piece of brain coral).'
WHERE LOWER(name_en) = LOWER('Awaken Intelligence') AND spell_type = 'wizard';
