-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 3 (Batch 4: 15 Spells — Distraction to Dweomer Vortex)
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  description = 'Eine oder mehrere Personen im Wirkungsbereich werden so abgelenkt, dass sie keine Bewegung, kein Geräusch und keinen Geruch in ihrer Umgebung bemerken. Gegen Schlaf und Bezauberung immune Individuen sind auch gegen diesen Zauber immun. Rettungswurf gegen Zauber. Bei 2-3 Zielen: RW mit −1; bei nur einem Ziel: RW mit −2. Ist die zu verbergende Handlung ausdrücklich verboten und wird offen versucht (z.B. durch eine bewachte Tür gehen), werden die Abzüge negiert und stattdessen +2 RW-Bonus gewährt. Der Zauber kann einen Überraschungsangriff ermöglichen. Ein physischer Schlag oder Kontakt (selbst ein Anstoß) beendet den Zauber sofort. Materialkomponente: S, M (ein Stück schwarze Gaze).',
  description_en = 'One or more persons in the area of effect become too preoccupied to notice any movement, sound, or smell around them. Individuals resistant to sleep and charm are likewise resistant. Saving throw vs. spell. For 2-3 targets: save at −1; for a single target: save at −2. If the action to be concealed is expressly forbidden and attempted in plain sight (e.g., passing through a guarded door), penalties are negated and a +2 save bonus is received instead. The spell can set up a surprise attack. A physical blow or contact, even jostling, negates the spell immediately. Material component: S, M (a piece of black gauze).'
WHERE LOWER(name_en) = LOWER('Distraction') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ersetzt ein Skelett oder einen Zombie durch zwei identische Untote mit maximalen TP. Betrifft ein animiertes Skelett oder Zombie mit 3 TW oder weniger (keine speziellen Untoten wie Ju-Ju-Zombies etc.). Muss innerhalb von 3 Runden nach der Belebung gewirkt werden und bleibt ruhend bis zur Auslösung. Zwei Auslöser sind üblich (einer beim Wirken wählen): Zauberauslöser (wenn ein Zauber auf den geschützten Untoten wirkt) oder Vertreibungsauslöser (wenn ein Priester versucht, den Untoten zu vertreiben). Die Duplikate sind immun gegen Vertreiben. Zauber des Originals übertragen sich nicht. Der Zauberkundige kontrolliert die Duplikate. Sie verschwinden bei Zerstörung oder nach 2 Stunden pro Stufe. Materialkomponente: V, S, M (ein kleines Kristallprisma und zwei Haare).',
  description_en = 'Replaces one skeleton or zombie with two identical undead with maximum HP. Affects one animated skeleton or zombie of 3 HD or less (not special undead like ju-ju zombies). Must be cast within 3 rounds of animation and remains dormant until triggered. Two triggers are common (choose one at casting): Spell Trigger (when any spell affects the protected undead) or Turning Trigger (when a priest attempts to turn it). The duplicates are immune to turning. Spells on the original don''t carry over. The caster controls the duplicates. They vanish when destroyed or after 2 hours per level. Material component: V, S, M (a small crystal prism and two hairs).'
WHERE LOWER(name_en) = LOWER('Double Undead') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ähnlich dem Federfall-Zauber, aber speziell für Drachen konzipiert — rettet einen im Flug verletzten Drachen vor dem Absturz. Pro Stufe kann eine Alterskategorie des Drachen betroffen werden (z.B. ein Drachenritter der 7. Stufe kann Drachen bis zum reifenden Erwachsenen betreffen). Wie andere Drachenritterzauber funktioniert er nicht bei anderen Kreaturen oder Objekten. Komponente: V.',
  description_en = 'Similar to Feather Fall, but designed specifically for dragons — saves a dragon injured in flight from plummeting. One age class of dragon per caster level can be affected (e.g., a 7th-level dragon knight can affect dragons up to mature adult). As with other dragon knight spells, it does not work on other creatures or objects. Component: V.'
WHERE LOWER(name_en) = LOWER('Dragon Fall — Dragon Knight') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Bietet einem normalen Sack oder Rucksack erhöhten Schutz. Der betroffene Sack wird geschützt, als wäre er innen vollständig mit 2,5 cm dickem massivem Stahl ausgekleidet — ohne schwerer oder weniger flexibel zu werden. Der Sack besteht Rettungswürfe gegen physischen oder magischen Schaden, als wäre er aus hartem Metall gefertigt, mit +2 Bonus. Gegenstände darin werden nur geprüft, wenn der Sack seinen RW nicht besteht. Materialkomponente: V, S, M (ein Lederstreifen mit Eisengeflecht auf einer Seite).',
  description_en = 'Provides greater protection for the contents of one normal sack or backpack. The affected sack is protected as if the interior were lined with 2.5 cm thick solid steel — without becoming heavier or less flexible. The sack makes saving throws against physical or magical damage as if made of hard metal, with +2 bonus. Items within check only if the sack fails its save. Material component: V, S, M (a strip of leather with iron mail sewn on one side).'
WHERE LOWER(name_en) = LOWER('Drawmij''s Iron Sack') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verbesserte Version des Schild-Zaubers der 1. Stufe. Schützt den Zauberkundigen gegen Angriffe von ALLEN Seiten (einschließlich Rücken und oben), sofern er den Angriff wahrnimmt. Ein Überraschungsangriff hebt den Schutz des Schilds vollständig auf. Der Schutz beträgt eine Verbesserung von 2 gegen alle Angriffe: RK 0 gegen handgeworfene Geschosse, RK 1 gegen gerätegetriebene Geschosse, RK 2 gegen alle anderen Angriffsformen. Komponenten: V, S.',
  description_en = 'Improved version of the 1st-level Shield spell. Protects the caster against attacks from ALL sides (including rear and above), provided the wizard is aware of the attack. A surprise attack completely dispels the protection. The protection is an increase of 2 against all attacks: AC 0 vs. hand-hurled missiles, AC 1 vs. device-propelled missiles, AC 2 vs. all other attacks. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Drawmij''s Marvelous Shield') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Zauberkundige wirft eine oder mehrere große Nadeln in die Luft und zeigt auf das Ziel. Die Nadeln fliegen zum Opfer und beginnen es zu stechen — 1-2 Schadenspunkte pro Nadel pro Runde. Bewegt sich die Kreatur, folgen die Nadeln, aber nicht über die Reichweitengrenze hinaus. Pro drei Stufen kann eine Nadel verzaubert werden (max. vier). Magischer Schutz (Schild, Rüstung etc.) erfordert einen Angriffswurf pro Nadel. Nach dem Wirken braucht der Zauberkundige keine Konzentration. Die Nadeln müssen 12,7 cm lang sein und aus einer leichten Metalllegierung bestehen (Herstellung 25 GM pro Stück). Sie müssen in magischer Flüssigkeit gelagert werden (25 GM pro Monat). Können wiederverwendet werden, falls geborgen. Materialkomponente: V, S, M (die Metallnadeln).',
  description_en = 'The caster throws one or more large needles into the air and points at the target. The needles dart toward the victim and start poking — 1-2 damage per needle per round. If the creature moves, the needles follow but won''t pass beyond range. One needle per three levels can be enchanted (max four). Magical protection (Shield, Armor, etc.) requires an attack roll per needle. After casting, no concentration needed. The needles must be 12.7 cm long of light metal alloy (25 gp each to make). Must be stored in magical liquid (25 gp/month). Can be reused if recovered. Material component: V, S, M (the metal needles).'
WHERE LOWER(name_en) = LOWER('Drenal''s Amok Needles') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Eine rotglühende Nadel wird verzaubert und fliegt auf das Auge des Ziels zu. Rettungswurf gegen Zauber negiert. Bei Misserfolg: 1W4 Schaden und das Ziel sinkt vor unerträglichem Schmerz auf die Knie für 1W4 Runden. In dieser Zeit kann es sich verteidigen (−2 RK-Abzug), aber nicht angreifen. Kreaturen der Größe L oder größer mit 6+ TW: 50% Chance in Raserei zu verfallen — greift mit doppelter normaler Rate an, +2 auf Treffer und Schaden für 2W4 Runden. Wenn nicht in Raserei, kann es physisch angreifen (−2 auf Treffer, +2 Schaden). Materialkomponente: V, S, M (eine graue Talgkerze und eine 4-12,7 cm feine Metallnadel, Mindestwert 10 GM). Die Kerze wird angezündet, die Nadel erhitzt; wenn sie nicht mehr gehalten werden kann, fliegt sie zum Opfer.',
  description_en = 'A red-hot needle is enchanted to dart at the target''s eye. Save vs. spell negates. On failure: 1d4 damage and the target drops to its knees from excruciating pain for 1d4 rounds. During this time it can defend itself (−2 AC penalty) but cannot attack. Large or larger creatures with 6+ HD: 50% chance of becoming enraged — attacks at twice normal rate, +2 to hit and damage for 2d4 rounds. If not enraged, can still physically attack at −2 to hit, +2 damage. Material component: V, S, M (a gray tallow candle and a 4-12.7 cm fine metal needle, min value 10 gp). The candle heats the needle; when it can no longer be held, it darts at the victim.'
WHERE LOWER(name_en) = LOWER('Drenal''s Eyesore') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt eine transparente Barriere, durch die kein Geräusch dringen kann. Wenn die Wand einen gesamten Durchgang, Passage oder ein Loch abdeckt, kann kein Schall von einer Seite zur anderen gelangen. Die Schallbarriere muss an vier Oberflächen verankert sein. Der Effekt funktioniert nur, wenn der gesamte Durchgang bedeckt ist und Schall nicht leicht durch die umgebenden Wände dringt. Kann horizontal oder vertikal sein. Pro Stufe kann eine Fläche von 3 × 3 m abgedeckt werden. Materialkomponente: V, S, M (kleine weiche Tonklumpen mit eingesteckten Federn, in zwei Ecken des zu blockierenden Bereichs platziert).',
  description_en = 'Creates a transparent barrier through which no sound can pass. When placed to block an entire portal, passage, or hole, no sound passes from one side to the other. The sound barrier must be anchored to four surfaces. The effect only works when the entire passage is covered and sounds don''t easily travel through surrounding walls. Can be horizontal or vertical. One 3 × 3 m pane per level. Material component: V, S, M (small soft clay mounds with feathers, placed in two corners of the area to be blocked).'
WHERE LOWER(name_en) = LOWER('Drenal''s Sound Barrier') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erfordert eine volle Stunde Konzentration im Zentrum des Wirkungsbereichs (91,4 m² pro Stufe). Das Gebiet beginnt auszutrocknen — Sumpf und Marsch: Wasser fließt ab; Feld oder Wald: Boden verdorrt zu Staub, Vegetation stirbt innerhalb weniger Tage. Wirkt nicht auf Gebiete mit mehr als 30 cm stehendem Wasser (Wasser fließt ab, neues strömt nach). Die magische Dürre hält an, bis natürliche oder magische Wetteränderungen Regen bringen. Magie Bannen wirkt nur, wenn vor Ablauf der Wirkzeit des Dürre-Zaubers gewirkt. Materialkomponente: V, S, M (der getrocknete Fuß einer Wüstenratte).',
  description_en = 'Requires a full hour of concentration at the center of the area (91.4 m² per level). The area begins drying out — swamp and marsh: water drains away; field or forest: ground withers to dust, vegetation perishes within days. No effect on areas with more than 30 cm of standing water (water drains but refills). The magical drought lasts until natural or magical weather changes bring rain. Dispel Magic only works if completed before the drought spell''s casting time elapses. Material component: V, S, M (the dried foot of a desert rat).'
WHERE LOWER(name_en) = LOWER('Drought — Hishna') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt ein schimmerndes kegelförmiges Feld in der Luft (3 m lang, 1,2 m Radius am offenen Ende), das schmale Ende zum Zauberkundigen. Der Kegel bewegt sich nach Gedanke des Zauberkundigen mit Bewegungsrate 6, wird aber von festen Barrieren aufgehalten. Trifft der Kegel auf magische Wirkungsbereiche (einschließlich noch nicht ausgelöster magischer Fallen), wirbelt er, blitzt und „trinkt" sie. Kann bis zu sechs Zauberstufen absorbieren, bevor er in einem harmlosen Lichterwirbel verschwindet. Ein Zauber, der diese Grenze übersteigt, wird zerstört, während der Vortex kollabiert. Wird nicht durch andere Zauber oder magische Gegenstände des Zauberkundigen beeinflusst. Magie Bannen lässt ihn kollabieren und absorbiert den gesamten Bannen-Effekt. Kann keine Anti-Magie-Hüllen, Kugeln der Unverwundbarkeit oder prismatische Zauber der 3. Stufe oder höher beeinflussen. Überträgt keine absorbierte Zauberenergie an den Zauberkundigen. Komponente: V.',
  description_en = 'Creates a shimmering conical field in midair (3 m long, 1.2 m radius at open end), small end toward the caster. The cone moves by the caster''s thought at movement rate 6 but is stopped by solid barriers. If it encounters magical areas of effect (including untriggered magical traps), it whirls, flashes, and "drinks" them. Can drain up to six spell levels before vanishing in a harmless whirl of lights. A spell exceeding this limit is destroyed as the vortex collapses. Not affected by the caster''s other spells or magical items. Dispel Magic causes collapse while absorbing the entire dispel effect. Cannot affect Antimagic Shells, Globes of Invulnerability, or prismatic spells of 3rd level or higher. Does not transmit drained energy to the caster. Component: V.'
WHERE LOWER(name_en) = LOWER('Dweomer Vortex — Phaerimm') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verursacht Blindheit ODER Taubheit (Wahl des Zauberkundigen) bei einer berührten Kreatur (erfordert erfolgreichen Berührungsangriff und missglückten Rettungswurf gegen Zauber). Blindheit: −4 auf Angriffswürfe, +4 RK-Abzug, +2 auf Initiative. Taubheit: −1 auf Überraschungswurf, +1 auf Initiative, 20% Chance des Zauberversagens bei verbalen Komponenten, reagiert nur auf Sicht und Berührung. Die Behinderung ist magischer Natur und kann durch einen entsprechenden Heilzauber oder durch den Zauberkundigen (nach Belieben) aufgehoben werden. Magie Bannen wirkt nicht. Oft in Kombination mit Spektralhand eingesetzt. Das Wirken ist eine böse Handlung. Komponenten: V, S.',
  description_en = 'Inflicts blindness OR deafness (caster''s choice) on a touched creature (requires successful touch attack and failed save vs. spell). Blindness: −4 on attacks, +4 AC penalty, +2 on initiative. Deafness: −1 on surprise rolls, +1 on initiative, 20% spell failure chance for verbal components, reacts only to sight and touch. The affliction is magical and can be removed by an appropriate cure spell or by the caster at will. Dispel Magic is not effective. Often used with Spectral Hand. Casting is an evil act. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Cause Blindness or Deafness') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Befällt die berührte Kreatur (erfordert erfolgreichen Berührungsangriff und missglückten Rettungswurf gegen Zauber) mit einer schwächenden oder tödlichen Krankheit nach Wahl des Zauberkundigen. Die Krankheit muss natürlich verlaufen oder magisch geheilt werden (Krankheit Heilen; Magie Bannen wirkt nicht). Lykanthropie kann nicht verursacht werden. Kombination mit Spektralhand möglich. Das Wirken ist eine böse Handlung. Schwächend: Wirkt in 1W6 Runden, −1 STR pro Stunde bis STR 2 oder weniger (dann hilflos). Natürliche Erholung: 1W3 Wochen. Tödlich: Wirkt sofort. Heilzauber haben keine Wirkung, Wunden heilen nur mit 10% der natürlichen Rate. In 1W6 Monaten tödlich. Pro Monat −2 CHA permanent. Nur magisch heilbar. Komponenten: V, S, M.',
  description_en = 'Afflicts the touched creature (requires successful touch attack and failed save vs. spell) with a debilitating or fatal disease at the caster''s option. The disease must run its course or be cured magically (Cure Disease; Dispel Magic ineffective). Lycanthropy cannot be caused. Can be combined with Spectral Hand. Casting is an evil act. Debilitating: takes effect in 1d6 turns, −1 STR per hour until STR 2 or less (then helpless). Natural recovery: 1d3 weeks. Fatal: effective immediately. Cure wound spells have no effect, wounds heal at only 10% natural rate. Fatal in 1d6 months. Each month −2 CHA permanently. Only curable magically. Components: V, S, M.'
WHERE LOWER(name_en) = LOWER('Cause Disease') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Variante von Monsterbeschwörung I. Beschwört jedoch nur EINE Kreatur mit 1-2 TW/Stufen. Der Zauberkundige bestimmt die genaue Kreatur. Ist die Kreatur nicht mehr am Leben oder hat mehr TW als der Zauber erlaubt, schlägt er fehl. Die Kreatur erscheint in 1W4 Runden und bleibt für 2 Runden plus 1 Runde pro Stufe. Am Ende wird sie an ihren Ursprungsort zurückgebracht. Dies kann ein Segen sein — wird eine Kreatur aus den Klauen des Todes gerissen, hat das Monster Zeit wegzuziehen. Kann aber auch nur ein Aufschub sein. Materialkomponente: V, S, M (ein kleiner Beutel, eine brennende Kerze und ein Zeichen der Kreatur — Schuppe oder Haarbüschel; wird beim Wirken zerstört).',
  description_en = 'Variation of Monster Summoning I. However, summons only ONE creature of 1-2 HD/levels. The caster determines the exact creature. If the creature is no longer living or has more HD than allowed, the spell fails. The creature arrives in 1d4 rounds and remains for 2 rounds plus 1 round per level. At expiration, it is returned to its original location. This can be a blessing — if snatched from the jaws of death, companions may figure out how to help before it returns. But it may also just postpone doom. Material component: V, S, M (a tiny bag, a lit candle, and a token from the creature — scale or tuft of hair; destroyed in casting).'
WHERE LOWER(name_en) = LOWER('Cervate''s Summoning') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Schützt den Zauberkundigen oder einen berührten Empfänger teilweise gegen Schaden durch Zauber der 3. Stufe oder weniger und gleichwertige magische Gegenstandsentladungen. Hat keinen Einfluss auf Rettungswürfe oder schadenslose Zauber. Für Zauber mit zufälligem Schaden: −3 Punkte pro Würfel für 1.-Stufe-Zauber, −2 pro Würfel für 2.-Stufe, −1 pro Würfel für 3.-Stufe (Minimum 1 pro Würfel). Für Zauber mit festem Schaden oder Basis + Stufe: −12 Punkte für 1.-Stufe, −8 für 2.-Stufe, −4 für 3.-Stufe (Minimum 1). Materialkomponente: V, S, M (eine Handvoll Eisenspäne von ehemaliger Plattenrüstung und ein Fetzen Spinnwebe).',
  description_en = 'Partially protects the caster or a touched recipient against damage from spells of 3rd level or less and equivalent magical item discharges. No effect on saving throws or damage-free spells. For random damage spells: −3 per die for 1st-level, −2 per die for 2nd-level, −1 per die for 3rd-level (min 1 per die). For set damage or base + level spells: −12 for 1st-level, −8 for 2nd-level, −4 for 3rd-level (min 1). Material component: V, S, M (a handful of iron filings from former plate armor and a scrap of cobweb).'
WHERE LOWER(name_en) = LOWER('Cloak of Adeamozs') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Hüllt den Geist des Zauberkundigen vorübergehend in wilde, irrsinnige Oberflächengedanken — sein Geist kann nicht gelesen oder beeinflusst werden, selbst nicht durch Psionik. Verleiht kurzfristige Immunität gegen psionische Angriffe und alle geistbeeinflussenden Zauber: Bezauberung, Befehl, Verwirrung, ESB, Furcht, Schwachsinn, Phantasie-Killer, Besessenheit, Herrschaft, Suggestion, Telepathie — und ähnliche Effekte von magischen Gegenständen. Begrenzter Wunsch und Wunsch sowie Kräfte von Halbgöttern/Gottheiten durchdringen den Schutz. Während des Schutzes kann der Zauberkundige KEINEN anderen Zauber wirken (sofortige Schwachsinn-Effekte für 1 Runde/Stufe). Kann aber schwierig magische Gegenstände nutzen, Tränke trinken, Zauberbücher durchblättern. Kampf und physische Aktivität beenden den Zauber nicht. 12% Chance bei jedem Einsatz, dass der Zauberkundige nach Ablauf für 2W4 Runden verwirrt wird. Komponenten: V, S.',
  description_en = 'Temporarily cloaks the caster''s mind with wild, insane surface thoughts — the mind cannot be read or influenced, even by psionics. Confers short-term immunity to psionic attack and all mind-affecting spells: Charm, Command, Confusion, ESP, Fear, Feeblemind, Phantasmal Killer, Possession, Rulership, Suggestion, Telepathy — and similar magical item effects. Limited Wish and Wish and demipower/deity abilities can penetrate. While protected, the caster CANNOT cast another spell (causes instant feeblemind for 1 turn/level). Can use magical items with difficulty, drink potions, scan spellbooks. Combat and physical activity do not end the spell. 12% chance each use that the caster becomes confused for 2d4 rounds when it expires. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Cloak of Insanity — Drow') AND spell_type = 'wizard';
