-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 6 (Batch 2: 13 Spells — Blackmantle to Cubehopper)
-- Alle mechanischen Details, Materialkomponenten, Spezialfälle
-- Metrisch, eng an Originaltexten orientiert
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  name = 'Schwarzmantel',
  description = 'Erzeugt eine schimmernde Aura um jede Kreatur im Wirkungsbereich (4,6 m Radius), die ihren Rettungswurf gegen Zauber nicht besteht. Die Aura negiert jegliche Heilung und Regeneration für die Dauer des Zaubers (1 Runde pro Stufe). Heiltränke haben keine Wirkung, Trolle können verlorene Trefferpunkte nicht regenerieren, und Heilzauber sind nutzlos. Ist die Kreatur am Ende der Wirkungsdauer noch am Leben, funktionieren aktive Heilkräfte (z.B. Ring der Regeneration) wieder normal. Materialkomponente: Ein kleines mumifiziertes Tier wie eine Maus oder Kröte.',
  description_en = 'Creates a shimmering aura around each creature within the area of effect (4.6 m radius) that fails a saving throw vs. spell. The aura negates all healing and regeneration for the spell''s duration (1 turn per level). Potions of healing have no effect, trolls cannot regenerate lost hit points, and cure spells are useless. If the creature is still alive when the spell expires, any active curative forces (e.g. ring of regeneration) resume normal function. Material component: A small mummified animal such as a mouse or toad.'
WHERE LOWER(name_en) = LOWER('Blackmantle') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Klinge des Verhängnisses',
  description = 'Eine spezialisierte Form des Fluchs. Beim Wirken erscheint eine große Klinge aus magischer Kraft über dem Ziel, die nur für den Zauberkundigen, Wesen mit Unsichtbares-Sehen und durch Magie Entdecken sichtbar ist. Die Klinge fällt auf den Kopf des Opfers, wenn eine vom Zauberkundigen festgelegte Bedingung eintritt (z.B. ein bestimmtes Wort sprechen, einen Zauber wirken oder eine Waffe ziehen). Bei Auslösung verursacht die Klinge 1 Schadenspunkt pro Stufe des Zauberkundigen (Rettungswurf gegen Zauber negiert). Kann vom Zauberkundigen jederzeit aufgehoben werden; auch Begrenzter Wunsch oder Wunsch wirken. Einfaches Magie Bannen hat keine Wirkung. Nur eine Klinge des Verhängnisses pro Person möglich. Hält bis zu einem Jahr an. Materialkomponente: Ein kleiner Krummsäbel aus Bergkristall (Wert 300 GM) oder Diamant/klarem Saphir (Wert 3.000 GM).',
  description_en = 'A specialized type of curse. When cast, a large blade of magical force appears above the target, visible only to the caster, those who can see invisible items, and via Detect Magic. The blade drops on the victim''s head when a condition specified by the caster occurs (e.g. speaking a particular word, beginning to cast a spell, or drawing a weapon). When triggered, the blade inflicts 1 point of damage per caster level (saving throw vs. spell negates). Can be dispelled by the caster at will; Limited Wish or Wish also work. Simple Dispel Magic has no effect. Only one Blade of Doom per individual at a time. Lasts up to one year. Material component: A small scimitar carved of rock crystal (300 gp) or diamond/clear sapphire (3,000 gp).'
WHERE LOWER(name_en) = LOWER('Blade of Doom') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Verschmelzung',
  description = 'Verleiht dem berührten Wesen (maximal menschengroß) Fähigkeiten ähnlich einer Robe der Verschmelzung. Das Wesen erscheint als Teil des Hintergrunds — eine Felswand, eine Pflanze, ein Möbelstück oder sogar eine andere Kreatur (z.B. ein Ork unter Orks). Farbe, Form und sogar Geruch werden erzeugt, das Wesen kann aber nicht größer als das Doppelte oder kleiner als die Hälfte seiner normalen Größe erscheinen. Keine Sprach- oder Geräuschnachahmung. Das Aussehen kann während der Wirkungsdauer (5 Runden pro Stufe) beliebig gewechselt werden (halbe Runde Konzentration). Bekannte und freundliche Wesen sehen die Kreatur normal. Innerhalb von 9,1 m haben Wesen mit außergewöhnlicher Intelligenz (1 % pro INT-Punkt) oder 10+ TW (1 % pro TW) eine kumulative Chance, etwas Ungewöhnliches zu bemerken. Materialkomponente: Ein Stück getrocknete Chamäleonhaut.',
  description_en = 'Grants the touched creature (man-size or smaller) abilities similar to a Robe of Blending. The creature appears as part of the background — a rock wall, a plant, furniture, or even another creature (e.g. an orc among orcs). Proper coloration, form, and even odor are produced, but the creature cannot appear more than twice or less than half its normal height. No language or sound-mimicking capability. Appearance can be changed at will during the duration (5 rounds per level), each change requiring half a round of concentration. All those acquainted with and friendly to the creature see it normally. Within 9.1 m, creatures with exceptional Intelligence (1% per INT point) or 10+ HD (1% per HD) have a cumulative chance to notice something unusual. Material component: A piece of dried chameleon skin.'
WHERE LOWER(name_en) = LOWER('Blending') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Verteidigung Durchbrechen',
  description = 'Der Fluch magischer Kreaturen — negiert vorübergehend die magischen Abwehrkräfte einer Kreatur, die sonst gegen normale Waffen immun ist. Die Kreatur wird für normale Waffen verwundbar und ihre Rüstungsklasse verschlechtert sich um 2 (z.B. von RK 4 auf RK 6, maximal RK 10). Unter diesem Zauber werden Schemen greifbarer, Eisengolems weicher, und Werwölfe müssen mehr als nur Silberwaffen fürchten. Hat keinen Einfluss auf Magieresistenz, Rettungswürfe oder natürliche/magische Immunitäten gegen bestimmte Angriffsformen (z.B. Feuerresistenz eines Salamanders). Entzieht lediglich den Schutz gegen nicht-magische Waffen, egal ob die Kreatur normalerweise +1 oder +3 Waffen benötigt. Wirkt auch auf Magier unter dem Effekt von Schemenform. Rettungswurf gegen Zauber negiert. Materialkomponente: Je eine murmelgroße Kugel aus Eisen und Glas.',
  description_en = 'The bane of magical creatures — temporarily negates the magical defenses of a creature otherwise immune to normal weapons. The creature becomes vulnerable to normal weapons and its Armor Class is worsened by 2 (e.g. from AC 4 to AC 6, maximum AC 10). Wraiths become more tangible, iron golems soften, and lycanthropes must fear more than silver weapons. Has no effect on magic resistance, saving throws, or natural/magical immunities to certain attack forms (e.g. a salamander''s fire resistance). Simply drains magical weapon-immunity defenses, whether the creature normally requires +1 or +3 weapons. Also affects wizards under Wraithform. Saving throw vs. spell negates. Material component: One marble-sized ball each of iron and glass.'
WHERE LOWER(name_en) = LOWER('Breach Defenses') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Leuchtendes Lied',
  description = 'Wird durch einen gesungenen Zauberspruch ausgelöst und erzeugt Freie Aktion (wie der Priesterzauber 4. Stufe oder der Ring der Freien Aktion) in einem kugelförmigen Wirkungsbereich (6,1 m Radius), zentriert auf den Zauberkundigen und mit ihm bewegend. Alle Kreaturen darin können sich normal bewegen und angreifen. Folgende magische Effekte werden negiert oder verhindert: Netz, Verlangsamen, Verstricken, Kraftkäfig, Halten, und alle Arten von Lähmung und Versteinerung. Alle Schlösser (mechanisch und magisch) werden geöffnet, alle Knoten gelöst. Wesen unter Zwang (Bezauberungen, Geas, psionische Einflüsse) erhalten beim Betreten des Bereichs einen sofortigen Rettungswurf zur Befreiung (nur ein Versuch pro Wesen). Funktioniert nicht unter Wasser.',
  description_en = 'Unleashed by a sung incantation, creates Free Action (akin to the 4th-level priest spell or Ring of Free Action) in a spherical area (6.1 m radius) centered on the caster, moving with him. All creatures within can move and attack normally. The following magical effects are negated or prevented: Web, Slow, Entangle, Forcecage, Hold, and all types of paralysis and petrification. All locks (mechanical and magical) are opened, all knots untied. Beings under any compulsion (charms, geas, psionic influences) receive an immediate saving throw to escape upon entering the area (one attempt per being only). Does not work underwater.'
WHERE LOWER(name_en) = LOWER('Brightsong') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Kondensator',
  description = 'Platziert eine elektrische Ladungsfalle auf einer Kiste aus nicht-leitendem Material. Die elektrische Ladung wird an die erste Metallmasse von mehr als 0,5 kg entladen, die innerhalb von 3 m der Kiste kommt. Bei mehreren Metallmassen trifft die Ladung die größte. Die Ladung verursacht 3W8 Schadenspunkte plus 1 Trefferpunkt pro Stufe des Zauberkundigen. Ein erfolgreicher Rettungswurf gegen Zauber erdet den Funken harmlos (optional wird er auf die nächste passende Metallmasse umgeleitet). Die Kiste wird nicht beschädigt. Wird die Kiste zerstört, geht die nicht entladene Ladung verloren. Maximale Kistengröße: ca. 0,23 Kubikmeter pro Stufe. Materialkomponente: Etwas Schleim eines blauen oder bronzenen Drachen. Nach dem Wirken spricht der Magier ein Befehlswort zur Aktivierung.',
  description_en = 'Places an electrically charged trap on a box made of any non-conductive material. The charge is delivered to the first mass of metal greater than 0.5 kg that comes within 3 m of the box. If multiple metal masses are present, the charge targets the largest. The charge deals 3d8 points of damage plus 1 hit point per caster level. A successful saving throw vs. spell harmlessly grounds the spark (optionally redirected to the next suitable metal mass). The box is not damaged. If the box is destroyed, any undelivered charge is lost. Maximum box size: approximately 0.23 cubic meters per level. Material component: A bit of phlegm from a blue or bronze dragon. After casting, the caster speaks a command word to activate the charge.'
WHERE LOWER(name_en) = LOWER('Capacitor') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Cathalas Zwang',
  description = 'Wird auf ein einzelnes Wesen gewirkt. Bei erfolgreichem Rettungswurf gegen Zauber ist der Zauber wirkungslos. Bei Misserfolg wird das Opfer gezwungen, auf den Zauberkundigen zuzustürmen, bis dieser die Magie beendet (typischerweise kurz vor dem Aufprall), das Opfer den Zauberkundigen berührt, oder 1 Runde pro Stufe verstrichen ist. Ein Opfer, das durch eine Barriere oder einen Feind am Erreichen des Zauberkundigen gehindert wird, versucht verbissen, das Hindernis zu überwinden — und lässt sich dabei für Angriffe anderer offen. Das Opfer kann Waffen in Reichweite bereithalten. Stürmende Kreaturen bewegen sich mit anderthalbfacher Bewegungsrate, erhalten +2 Angriffsbonus und können mit bestimmten Waffen (z.B. Lanze) doppelten Schaden verursachen. Sie verlieren alle DEX-basierten RK-Boni und erleiden −1 RK-Malus. Gegner mit gesetzten Speeren erhalten −2 Initiative und verursachen doppelten Schaden. Materialkomponente: Ein Kupferhaken an einer Schnur oder Angelschnur.',
  description_en = 'Cast on a single being. If the saving throw vs. spell succeeds, the spell is wasted. On failure, the victim is forced to charge at the caster until the caster ends the magic (typically just before impact), the victim touches the caster, or 1 round per caster level has elapsed. A victim prevented from reaching the caster by a barrier or foe single-mindedly tries to climb, get past, or batter down the obstacle — leaving themselves vulnerable to other attacks. The victim can ready weapons within reach. Charging creatures move at one-and-a-half times full movement rate, gain +2 attack bonus, and can inflict double damage with certain weapons (e.g. lance). They lose all DEX-based AC bonuses and suffer −1 AC penalty. Opponents with set spears gain −2 initiative and deal double damage. Material component: A copper hook on a string or fishing line.'
WHERE LOWER(name_en) = LOWER('Cathala''s Compulsion') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Tier Klonen',
  description = 'Funktioniert nur bei Kreaturen mit weniger als humanoider Intelligenz. Der Klon hat exakt die gleichen Eigenschaften, Merkmale und Defekte wie das Original und erreicht während der Wirkzeit das Wachstum des Originals. Der Zauber ist nach Abschluss der Wirkzeit nicht durch Magie Bannen oder ähnliche Effekte aufhebbar. Die resultierende Kreatur muss jedoch jeden Tag nach dem Wirken einen Rettungswurf gegen Todesmagie bestehen oder stirbt. Der Klon kann mit einem Permanenz-Zauber stabilisiert werden, wobei der Zauberkundige eine 10%ige Chance hat, dauerhaft 1 Punkt Konstitution zu verlieren. Materialkomponente: 0,5 Liter Blut pro Trefferwürfel der zu klonenden Kreatur.',
  description_en = 'Works only on creatures of less than humanoid intelligence. The clone has exactly the same traits, aspects, and defects as the original, reaching the original''s growth during the casting time. The spell is not subject to Dispel Magic or similar effects once casting is complete. However, the resulting creature must save vs. death magic each day after casting or perish. The clone can be stabilized with a Permanency spell, but the caster has a 10% chance to permanently lose 1 point of Constitution. Material component: 1 pint of blood per Hit Die of creature to be cloned.'
WHERE LOWER(name_en) = LOWER('Clone Animal') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Zeitanomalie Verbergen',
  description = 'Spaltet den Zeitfluss um eine temporale Störung herum, reduziert die verursachte Turbulenz und schirmt sie vor magischer Entdeckung ab. Ein Zeitanomalie-Entdecken-Zauber hat nur noch eine Grundchance von 25 %, die verborgene Anomalie zu entdecken. Andere Entdeckungszauber (Wahres Sehen, Unsichtbares Sehen etc.) haben ebenfalls nur 25 % Chance, aber Nicht-Chrononauten erkennen wahrscheinlich nicht, was sie sehen. Wirbel können verborgen werden, aber die beteiligten Kräfte sind extrem gefährlich — der Chronomant muss einen Weisheitswurf mit −4 bestehen. Misserfolg zerstört den Wirbel, altert den Zauberkundigen um 1W20 Jahre und reduziert die Weisheit permanent um 1 Punkt. Nicht kumulativ mit sich selbst. Materialkomponente: Eine Glaskugel gefüllt mit dem Blut einer Wirbelspinne.',
  description_en = 'Splits the flow of time around a temporal disturbance, reducing its turbulence and shielding it from magical detection. A Detect Temporal Anomaly spell has only a 25% base chance to detect the hidden anomaly. Other detection spells (True Seeing, Detect Invisibility, etc.) also have only a 25% chance, but those uninitiated in chronomancy are unlikely to know what they are seeing. Vortices can be hidden this way, but the forces involved become extremely hazardous — the chronomancer must check against Wisdom at −4. Failure destroys the vortex, ages the caster 1d20 years, and permanently reduces Wisdom by 1 point. Cannot be used cumulatively with itself. Material component: A glass bulb filled with the blood of a vortex spider.'
WHERE LOWER(name_en) = LOWER('Conceal Temporal Anomaly') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Untoten Erschaffen — Ghul',
  description = 'Erschafft einen untoten Diener aus beliebigen Teilen menschlicher oder tierischer Leichen. Der Ghul-Lord muss vor dem Wirken festlegen, welche Aufgabe der Diener erfüllen soll. Der resultierende Diener ist ideal für seinen vorgesehenen Zweck, besitzt aber keine Intelligenz und kann nur physische Aufgaben ausführen. Die Untoten dienen als Arbeiter oder Haushaltshilfen und sind darin hervorragend — sie brauchen bei ihrer Arbeit nicht überwacht zu werden und können auch Zombie- oder Skelett-Arbeitstrupps beaufsichtigen. Sie können keine künstlerischen oder technischen Aufgaben ausführen und sind für den Kampf ungeeignet (kämpfen als 0-TW-Monster mit nur 1 TP). Allerdings werden sie beim Vertreiben behandelt, als hätten sie die gleichen Trefferwürfel wie ihr Erschaffer. Materialkomponente: Eine vollständige oder nahezu vollständige Leiche oder ein Skelett.',
  description_en = 'Creates an undead servant from assorted parts of human or animal corpses. The ghul lord must decide the servant''s purpose before casting. The resulting servant is ideal for its intended task but has no intelligence and can only perform physical tasks. These undead serve as laborers or household help and excel at their duties — they need no supervision and can oversee zombie or skeleton work details. They cannot perform artistic or technical tasks and are poor in combat (fight as 0 HD monsters with only 1 HP). However, they are turned as if having the same Hit Dice as their creator. Material component: A complete or near-complete corpse or skeleton.'
WHERE LOWER(name_en) = LOWER('Construct Undead — Ghul') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Konstruktion — Elf',
  description = 'Mit diesem Zauber werden die Gebäude und Strukturen von Evermeet errichtet. Natürliche Materialien wie Stein, Kristall und Holz können in Skulpturen, Unterkünfte, Gebäude oder sogar große Paläste verwandelt werden. Das Baumaterial muss stets Kontakt mit der Erde behalten. Der Radius des betroffenen Materials beträgt 3 m mal Stufe des Zauberkundigen. Pro Stufe können 28,3 Kubikmeter (10 × 10 × 3 m) erschaffen werden, wobei jedes solche Volumen einen ganzen Tag benötigt. Einmal erschaffen, kann das Objekt mit der gleichen Rate erweitert werden. Das Objekt kann mit Räumen, Wänden, Fluren und Kammern unterteilt werden — komplexe Bereiche wie Gewölbedecken oder Säulen erhöhen die Bauzeit. Die Struktur ist permanent und benötigt keine weitere magische Verstärkung. Sie ist immun gegen Magie Bannen (aber nicht gegen Verzauberung Bannen) und erhält +5 auf alle Rettungswürfe bei Belagerungen.',
  description_en = 'Used to construct the buildings and structures of Evermeet. Natural materials such as stone, crystal, and wood can be transformed into sculptures, shelters, buildings, or even great palaces. The building material must maintain contact with the earth at all times. The radius of affected material equals 3 m times the caster''s level. The caster can create 28.3 cubic meters (10 × 10 × 3 m) per level, each volume requiring one full day. Once created, the structure can be added to at the same rate. It can be subdivided with rooms, walls, hallways, or chambers — complex areas like vaulted ceilings or columns increase construction time. The structure is permanent and needs no further magical maintenance. It is immune to Dispel Magic (but not Dispel Enchantment) and receives +5 to all saving throws when besieged.'
WHERE LOWER(name_en) = LOWER('Construction — Elf') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Winde Kontrollieren — Roter Magier',
  description = 'Erlaubt dem Zauberkundigen, die Windstärke im Wirkungsbereich (12,2 m Radius pro Stufe) zu verändern. Pro drei Stufen Erfahrung kann die Windstärke um eine Stufe erhöht oder verringert werden: Leichte Brise (3-11 km/h), Mäßige Brise (13-29 km/h), Starke Brise (31-50 km/h), Sturm (52-87 km/h), Orkan (89-116 km/h), Hurrikan (117-283 km/h). Winde über 50 km/h vertreiben kleine Flugwesen vom Himmel; über 83 km/h auch menschengroße. Winde über 143 km/h entwurzeln kleine Bäume, reißen Dächer ab und gefährden Schiffe. Um den Zauberkundigen existiert ein windstilles „Auge" von 12,2 m Radius. In unterirdischen Bereichen schrumpft das Auge um 0,3 m pro Fuß Begrenzung.',
  description_en = 'Allows the caster to alter wind force in the area of effect (12.2 m radius per level). For every three experience levels, wind force can be increased or decreased by one level: Light Breeze (3-11 km/h), Moderate Breeze (13-29 km/h), Strong Breeze (31-50 km/h), Gale (52-87 km/h), Storm (89-116 km/h), Hurricane (117-283 km/h). Winds over 50 km/h drive small flying creatures from the skies; over 83 km/h also man-sized ones. Winds over 143 km/h uproot small trees, tear off roofs, and endanger ships. A calm "eye" of 12.2 m radius exists around the caster. In underground areas, the eye shrinks 0.3 m per foot of confinement.'
WHERE LOWER(name_en) = LOWER('Control Winds — Red Wizard') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Leichenbesitzer',
  description = 'Ermöglicht es einem Wesen (das der Zauberkundige berührt, einschließlich sich selbst), seine Lebenskraft zu übertragen und die frische Leiche eines Menschen, Halbmenschen oder Humanoiden vorübergehend zu beleben. Die Reichweite zum echten Körper beträgt bis zu 8 km pro Stufe des Zauberkundigen. Während der Belebung zersetzt sich die Leiche nicht, erscheint aber wie Untote (z.B. Ju-Ju-Zombie), wenn keine Illusions-Magie angewendet wird. Der Empfänger sieht, hört und fühlt durch den Wirtskörper, kann kämpfen, heiser sprechen und Zauber wirken. Der Geist des Empfängers funktioniert gleichzeitig in beiden Körpern — der echte Körper behält alle Sinne, ist aber gelähmt (außer Atmen, Blinzeln, Augenbewegung). Der Wirtskörper hat TP gleich dem normalen Maximum des Empfängers, RK 10 (kann Rüstung tragen). Fällt der Wirtskörper auf 0 TP, muss der Empfänger einen Systemschock-Wurf bestehen oder stirbt ebenfalls. Die Verbindung kann durch Magie Bannen, Begrenzter Wunsch oder Wunsch getrennt werden.',
  description_en = 'Enables a creature (touched by the caster, including himself) to transfer its lifeforce to temporarily animate the fresh corpse of a human, demihuman, or humanoid. Range to the real body is up to 8 km per caster level. While animated, the corpse ceases to decay but appears undead-like (e.g. ju-ju zombie) unless illusionary magic is applied. The recipient sees, hears, and senses through the host body, can fight, speak hoarsely, and cast spells. The recipient''s mind functions in both bodies simultaneously — the real body retains all senses but is paralyzed (except breathing, blinking, eye movement). The host body has HP equal to the recipient''s normal maximum, AC 10 (can wear armor). If the host drops to 0 HP, the recipient must make a system shock roll or also dies. The link can be severed by Dispel Magic, Limited Wish, or Wish.'
WHERE LOWER(name_en) = LOWER('Corpse Host') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Kleinen Helm Erschaffen',
  description = 'Verwandelt einen normalen Stuhl oder Sitz in einen kleinen Spelljammer-Helm, der ein Schiff durch den Weltraum antreiben kann. Dies ersetzt nicht die Notwendigkeit eines permanenten magischen Helms an Bord und wird hauptsächlich in Notfällen eingesetzt. Das Wirken altert den Zauberkundigen um ein Jahr. Der kleine Helm kann ein Schiff von maximal der doppelten Stufe des Zauberkundigen in Tonnage antreiben (ein Magier der 20. Stufe kann einen Helm für ein 40-Tonnen-Schiff erschaffen). In der Bedienung ist er identisch mit einem normalen Spelljammer-Helm, mit einer Ausnahme: Wird er erfolgreich gebannt, verschwindet er und muss neu erschaffen werden. Das Erschaffen zählt als ein gewirkter Zauber und reduziert die Effektivität des Zauberkundigen als Steuermann für diesen Tag. Materialkomponente: Ein Stuhl, Hocker oder anderer Sitz.',
  description_en = 'Transforms a normal chair or seat into a minor spelljammer helm suitable for powering a ship through space. This does not replace the need for a permanent magical helm onboard and is used primarily in emergencies. Casting ages the caster one year. The minor helm can power a ship of no more than twice the caster''s level in tonnage (a 20th-level wizard can power a 40-ton ship). In operation, it is identical to a regular spelljammer helm, with one exception: if successfully dispelled, it disappears and must be created anew. Creating counts as one cast spell, reducing the caster''s effectiveness as helmsman for that day. Material component: A chair, stool, or other suitable seat.'
WHERE LOWER(name_en) = LOWER('Create Minor Helm') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Zerdrückende Kugel — Phaerimm',
  description = 'Erzeugt eine schimmernde Kraftkugel um eine einzelne Kreatur (max. Größe L), die sich über vier Runden zusammenzieht und das Opfer zerquetscht. Das Ziel erhält einen Rettungswurf gegen Zauber mit −3; bei Erfolg kollabiert die Kugel in einem Lichtblitz. Bei Misserfolg bildet sich die Kugel und beginnt sich zusammenzudrücken. Nur in der ersten Runde kann das Opfer frei zaubern oder Gegenstände aktivieren. Das Opfer wird verlangsamt, verliert DEX-basierte RK-Boni, erhält aber +2 RK-Verbesserung durch die Kugel. Angriffe durch die Kugel erleiden −2 Schaden pro Würfel (min. 1). Das Opfer hat −4 auf Angriffswürfe. Quetschschaden: 1W4 (1. Runde), 2W4 (2.), 3W4 (3.), 4W4 (4. Runde). Rüstung, Borkenhaut oder Schild reduziert den Schaden um 1W4 pro Runde. Lange, starre Gegenstände (z.B. Kampfstab) verhindern Schaden für eine Runde und begrenzen ihn danach auf 1W4 pro Runde.',
  description_en = 'Creates a shimmering sphere of force around a single creature (size L or smaller) that over four rounds tightens and crushes the trapped individual. The target receives a saving throw vs. spell at −3; on success, the sphere collapses in a burst of white light. On failure, the sphere forms and begins pressing inward. Only in the first round can the victim freely cast spells or trigger items. The victim is slowed, loses DEX-related AC bonuses, but gains +2 AC improvement from the sphere. Attacks through the sphere deal −2 damage per die (minimum 1). The victim has −4 attack roll penalty. Constriction damage: 1d4 (1st round), 2d4 (2nd), 3d4 (3rd), 4d4 (4th round). Armor, Barkskin, or Shield reduces damage by 1d4 per round. Long, rigid items (e.g. quarterstaff) prevent damage for one round and limit it to 1d4 per round thereafter.'
WHERE LOWER(name_en) = LOWER('Crushing Sphere — Phaerimm') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Würfelhüpfer',
  description = 'Öffnet ein temporäres Portal zwischen zwei beliebigen „Würfeln" auf der Unteren Ebene Acheron und ermöglicht schnellen, sicheren Transport für kleine Überfallgruppen. Das Portal besteht, bis eine Anzahl von Kreaturen gleich der Stufe des Zauberkundigen hindurchgegangen ist oder die Dauer (1 Stunde pro Stufe) endet. Der Zauberkundige kann das Portal jederzeit auflösen. Gerüchte besagen, dass der Zauber auch zum Teleportieren zwischen den planaren Schichten Acherons verwendet werden kann, aber dies soll einen speziellen Zauberschlüssel erfordern. Anführer von Ork- und Goblin-Armeen nutzen den Würfelhüpfer-Zauber berüchtigterweise, um Niederlagen und Massakern zu entkommen. Materialkomponente: Ein Eisensplitter von jedem der zu verbindenden Würfel.',
  description_en = 'Opens a temporary portal between any two "cubes" in the lower plane of Acheron, providing quick, safe transport for small raiding parties. The portal lasts until a number of creatures equal to the caster''s level have passed through or the duration (1 hour per level) ends. The caster can dispel the portal at will. Rumors state it can also teleport between Acheron''s planar layers, but this reportedly requires a special spell key. Leaders of orc and goblin armies are notorious for using Cubehopper to escape routs and massacres. Material component: A chip of iron from each of the cubes to be connected.'
WHERE LOWER(name_en) = LOWER('Cubehopper') AND spell_type = 'wizard';
