-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 6 (Batch 1: 12 Spells — Accelerate Metabolism to Bigby's Besieging Bolt)
-- Alle mechanischen Details, Materialkomponenten, Spezialfälle
-- Metrisch, eng an Originaltexten orientiert
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  name = 'Stoffwechsel Beschleunigen',
  description = 'Beschleunigt die Lebensprozesse des berührten Wesens. Schlafen, Essen und Heilen schreiten mit einer Rate von 1 Tag pro Runde fort. Das Wesen kann sich nicht schneller bewegen oder kämpfen als normal. Unfreiwillige Ziele erhalten einen Rettungswurf gegen Zauber. Pro Runde müssen 7 Segmente für Essen/Trinken (eine Tagesration) und 3 Segmente für Ruhe aufgewendet werden — andernfalls drohen Erschöpfung und Hunger. Das Wesen regeneriert 1 TP pro Runde für die ersten 7 Runden; in weiteren 7-Runden-Zyklen kommen CON-Boni hinzu. Nach 28 Runden ist das Wesen vollständig geheilt, altert aber eine Woche (statt eines Tages) durch die Belastung des erhöhten Stoffwechsels. Materialkomponente: Eine Kerze, die an beiden Enden angezündet werden muss und für die gesamte Dauer brennen muss.',
  description_en = 'Accelerates the life processes of the touched creature. Sleeping, eating, and healing progress at a rate of 1 day per turn. The creature cannot move or fight faster than normal. Unwilling targets receive a saving throw vs. spell. Per turn, 7 rounds must be spent eating/drinking a day''s rations and 3 rounds resting — otherwise exhaustion and starvation occur. The creature regains 1 HP per turn for the first 7 turns; in subsequent 7-turn cycles, CON bonuses provide additional healing. After 28 turns, the creature is fully healed but ages one week (instead of one day) due to the stress of the artificially high metabolic rate. Material component: A candle that must be lit at both ends and burn for the spell''s duration.'
WHERE LOWER(name_en) = LOWER('Accelerate Metabolism') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Säureregen — Roter Magier',
  description = 'Erzeugt einen intensiven Sturm aus brennender, ätzender Säure über einem Kreis von 0,9 m Durchmesser pro Stufe des Zauberkundigen (ein Magier der 12. Stufe erzeugt einen Kreis von 11 m Durchmesser). Die Säure verursacht 6W4+6 Schadenspunkte pro Runde, solange das Ziel im Wirkungsbereich bleibt. Freiliegende Ausrüstung muss jede Runde einen Rettungswurf gegen Säure bestehen oder wird zerstört. Materialkomponente: Ein Fläschchen starker Säure.',
  description_en = 'Creates an intense storm of burning, corrosive acid over a circle 0.9 m in diameter per caster level (a 12th-level wizard creates an 11 m diameter circle). The acid inflicts 6d4+6 points of damage per round as long as the target remains within the area of effect. Exposed equipment must save vs. acid each round or be destroyed. Material component: A vial of strong acid.'
WHERE LOWER(name_en) = LOWER('Acid Rain — Red Wizard') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Tier Altern Lassen',
  description = 'Kann nur auf Tiere angewendet werden, einschließlich Riesenarten und Minimals. Altert das Tier augenblicklich um bis zu ein Jahr pro Stufe des Zauberkundigen — der genaue Betrag wird vom Magier bestimmt. Der Magier muss beim Wirken einen Rettungswurf gegen Zauber ablegen; bei Misserfolg altert der Magier selbst um so viele Monate, wie das Tier an Jahren altert. Wird häufig für Zuchtexperimente eingesetzt, da der Zauber die Nachkommen weniger beeinflusst als andere Magie. Materialkomponente: V, S, M.',
  description_en = 'Can only be used on animals, including giant types and minimals. Instantly ages the animal by as much as one year per caster level — the exact amount is determined by the wizard. The wizard must make a saving throw vs. spell when casting; failure means the wizard ages by as many months as the creature ages years. Often used for breeding experiments, as it has less chance of adversely affecting offspring than other magic. Material component: V, S, M.'
WHERE LOWER(name_en) = LOWER('Age Animal') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Traum Verändern',
  description = 'Wirkt wie Traum Betreten, erlaubt dem Zauberkundigen aber zusätzlich, den Verlauf des Traums zu beeinflussen — ähnlich einem Regisseur, der ein Theaterstück lenkt. Der Zauberkundige kann eine Suggestion (wie der Zauber 3. Stufe) im Traum implantieren. Außerdem kann er den Traum so verzerren, dass er den Träumer angreift — mit denselben Effekten wie Phantastischer Killer (Illusion 4. Stufe). Ein fehlgeschlagener Tötungsversuch alarmiert den Träumer jedoch automatisch und gibt ihm die Chance, den Phantastischen Killer gegen den Zauberkundigen zu wenden. Der Zauberkundige muss dann sofort den Zauber beenden oder sich dem Phantastischen Killer stellen. Materialkomponente: Ein Stück geschmolzenes Glas und ein 30 g schwerer Streifen Traumweidenrinde, der in heißem Wasser eingeweicht und getrunken werden muss.',
  description_en = 'Functions as an Enter Dream spell, but additionally allows the caster to affect the course of the dream — much as a director affects a play. The caster can implant a Suggestion (as the 3rd-level spell) within the dream. He can also warp the dream to attack the dreamer with the same effects as Phantasmal Killer (4th-level illusion). However, a failed attempt to kill the dreamer automatically alerts the subject and gives them a chance to turn the Phantasmal Killer back on the caster. The caster must then immediately end the spell or face the Phantasmal Killer. Material component: A bit of melted glass and a 30 g strip of dreamwillow bark, steeped in hot water and imbibed.'
WHERE LOWER(name_en) = LOWER('Alter Dream') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Alviras Stasishülle',
  description = 'Umgibt einen Gegenstand (maximal so groß wie ein großes Zauberbuch, minimal so groß wie ein Trankfläschchen) mit einem Stasisfeld. Der geschützte Gegenstand kann von keiner Kraft unterhalb eines Auflösungszaubers beeinflusst werden, obwohl die Stasishülle selbst gebannt werden kann. Wasser, Feuer, Säure, Blitze und sogar Drachenodem gleiten an der äußeren Hülle ab. Der Gegenstand leuchtet schwach blau, behält sein normales Gewicht und kann bewegt werden, aber nicht physisch berührt oder geöffnet werden. Der Zauber wirkt nicht direkt auf lebendes Gewebe. Für alle Zwecke ist die Zeit für den Gegenstand im Feld angehalten. Alvira aus der Lebenden Stadt erschuf diesen Zauber, um ihn zusammen mit Permanenz auf eine Kopie ihres Zauberbuchs zu wirken.',
  description_en = 'Surrounds an object (maximum size of a large standard spellbook, minimum size of a potion vial) with a stasis field. The protected object cannot be affected by any force less powerful than a Disintegrate spell, though the stasis shell itself can be dispelled. Water, fire, acid, lightning, and even dragon breath merely move along the outer shell. The object glows faintly blue, retains its normal weight, and can be moved normally, but cannot be physically touched or opened. The spell cannot affect living tissue directly. For all intents, time has stopped for the object in the field. Alvira of the Living City created this spell to use in conjunction with Permanency on a copy of her spellbook.'
WHERE LOWER(name_en) = LOWER('Alvira''s Stasis Shell') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Blut Beleben',
  description = 'Erschafft kleine, belebte Wesen aus dem Blut des Zauberkundigen. Der Magier muss sich selbst schneiden und einige Blutstropfen vergießen (1W6 Tropfen). Die Tropfen nehmen die Form kleiner Tiere an und bewegen sich nach dem Willen des Zauberkundigen mit einer Geschwindigkeit von 18,3 m pro Runde. Sie sind klein genug, um unter den meisten Türen hindurchzugleiten und durch jede nicht wasserdichte Ritze zu sickern (halbe Bewegung in dieser Runde). Der Zauberkundige sieht und hört, als befände er sich am Ort der Blutstropfen, und kann seine Wahrnehmung beliebig zwischen den Tropfen wechseln. Verlassen Tropfen die Reichweite, werden sie zu normalen Blutstropfen und der Zauber endet. Magie Entdecken lässt die Tropfen hell aufleuchten. Böse Magier können die Tropfen als Angriffsform nutzen — sie springen bis zu 6,1 m weit auf ein Ziel (Angriff als Kämpfer 5. Stufe). Ein Treffer im Auge oder Ohr verursacht 4 Runden lang 1W6 Schaden pro Runde (aufhaltbar durch Weihwasser), der Magier erleidet 1 Schadenspunkt pro Runde durch sympathetische Magie.',
  description_en = 'Creates small, animated beings from the caster''s blood. The wizard must cut himself, spilling a few drops of blood (1d6 drops). The droplets take the shape of small animals and move at the caster''s bidding at 18.3 m per round. They are small enough to move under most doors and ooze through any crack that is not watertight (half movement that round). The caster sees and hears as if at the blood drops'' location and can shift perception between drops at will. If drops pass beyond range, they become ordinary blood and the spell ends. Detect Magic causes the drops to flare brightly. Evil wizards can use drops as an attack form — they can leap at a target up to 6.1 m distant, striking as a 5th-level fighter. A hit in the eye or ear causes 1d6 damage per round for 4 rounds (stopped by holy water), and the wizard suffers 1 damage per round from sympathetic magic.'
WHERE LOWER(name_en) = LOWER('Animate Blood') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Antimagische Aura — Elf',
  description = 'Wirkt ähnlich wie Antimagiehülle, ist aber für den Einsatz gegen feindliche Zauberkundige oder verzauberte Kreaturen gedacht. Eine glitzernde Lichtaura umgibt das Ziel und passt sich genau dem Körper an. Das Ziel kann keine Magie wirken, und verzauberte Kreaturen können keine zauberähnlichen Fähigkeiten einsetzen. Verzauberte Waffen verlieren ihre Boni und besonderen Kräfte und funktionieren wie normale Waffen. Wie bei Antimagiehülle ist der Zauber gegen außerplanare Kreaturen auf ihrer Heimatebene unwirksam. Anders als Antimagiehülle kann die Aura durch einen erfolgreichen Magie Bannen eines nicht betroffenen Zauberkundigen aufgehoben werden. Rettungswurf gegen Zauber negiert den Effekt.',
  description_en = 'Functions similarly to Antimagic Shell, but is intended for use against an enemy spellcaster or enchanted creature. A glittering aura of light surrounds the target, conforming exactly to the body. The subject cannot cast magic, and affected enchanted creatures cannot attack or use spell-like abilities. Enchanted weapons lose bonuses and special powers, functioning as ordinary weapons. As with Antimagic Shell, this spell is ineffective against extra-planar creatures on their home plane. Unlike Antimagic Shell, the aura can be eliminated by a successful Dispel Magic from an unaffected caster. Saving throw vs. spell negates.'
WHERE LOWER(name_en) = LOWER('Antimagic Aura — Elf') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Knochenpfeil',
  description = 'Durch das Einritzen mächtiger Runen auf einen einfachen Pfeil, Bolzen, Wurfpfeil oder Speer verwandelt der Zauberkundige das Geschoss in ein unheimliches Projektil aus kaltem, verzaubertem Knochen. Der Magier kann das Geschoss selbst abfeuern (ETW0 eines Kriegers der halben eigenen Stufe, +3 Angriffsbonus) oder es einem Gefährten geben (+1 Angriffsbonus). Ein getroffenes Wesen muss einen Rettungswurf gegen Todesmagie ablegen oder stirbt; auch bei Erfolg erleidet das Opfer normalen Geschossschaden plus den maximalen Grundschaden des Geschosses (z.B. 1W6+6 für einen Pfeil, 1W3+3 für einen Wurfpfeil). Untote und nicht-lebende Kreaturen sterben nicht sofort, erleiden aber normalen Schaden plus das Vierfache des maximalen Grundschadens (z.B. 1W6+24 für einen Pfeil), halbiert bei erfolgreichem Rettungswurf. Materialkomponente: Pulverisierter Knochensplitter gemischt mit schwarzem Drachenblut, als Runen auf das Geschoss gemalt. Stammt der Knochen von einem nahen Blutsverwandten des Ziels, erleidet das Opfer −4 auf den Rettungswurf.',
  description_en = 'By drawing runes of dire power upon a simple arrow, bolt, dart, or javelin, the caster changes the weapon into a sinister missile of cold, enchanted bone. The wizard can fire it himself (THAC0 of a warrior of half his level, +3 attack bonus) or give it to a companion (+1 attack bonus). A struck creature must save vs. death magic or die; even on success, the victim sustains normal missile damage plus the weapon''s maximum base damage (e.g. 1d6+6 for an arrow, 1d3+3 for a dart). Undead and nonliving creatures are not slain outright but take normal damage plus four times the missile''s maximum base damage (e.g. 1d6+24 for an arrow), halved on a successful save. Material component: Powdered bone sliver mixed with black dragon blood, painted as runes on the weapon. If the bone comes from a close blood relative of the target, the victim suffers −4 on the saving throw.'
WHERE LOWER(name_en) = LOWER('Arrow of Bone') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Aura',
  description = 'Erlaubt einem Wu Jen, die Aura eines Gebiets zu lesen und die grundlegende Gesinnung sowie magische Tendenzen der meisten Bewohner und Gegenstände im Bereich zu bestimmen. Über jeder Behausung oder jedem Gebäude im Wirkungsbereich (1,6 km Durchmesser pro Stufe) erscheint eine Aura, die anzeigt, ob die Hauptbewohner gut, böse, rechtschaffen, neutral oder chaotisch sind. Zusätzlich werden Gebiete mit hoher Konzentration ungeschützter Magie offenbart. Tempel, Schreine, verfluchte und spukende Orte zeigen entsprechende Auren. Die Aura erscheint auch über Behausungen, die der Zauberkundige nicht direkt sehen kann. Die Umkehrung, Maske, verbirgt die Aura einer einzelnen Behausung für eine volle Woche vor Entdeckung durch den Aura-Zauber.',
  description_en = 'Allows a wu jen to read the aura of an area, determining the basic alignment and magical tendencies of most inhabitants and items within range. An aura appears over every dwelling or structure within the area of effect (1.6 km diameter per level), indicating whether the principal occupants are good, evil, lawful, neutral, or chaotic. Areas with high concentration of unwarded magic are also revealed. Temples, shrines, haunted, and cursed areas show appropriate auras. The aura even appears over dwellings the caster cannot directly see. The reverse, Mask, hides the aura of any one dwelling from detection by the Aura spell for a full week.'
WHERE LOWER(name_en) = LOWER('Aura') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Ballants Steinspaltung',
  description = 'Spaltet den nächsten Steingegenstand, den der Zauberkundige berührt. Die Kraft manifestiert sich als Lichtfontäne und erzeugt einen dicken, gewundenen Riss, der am Ende der folgenden Runde ein Steinvolumen gleich dem Wirkungsbereich (3 m Würfel pro Stufe) zu Schutt reduziert. Bei einem Magier der 12. Stufe wird ein 12,2 m breiter Abschnitt einer Mauer zerstört. Der Schutt füllt die Bresche bis zur halben Höhe der Originalmauer. Auf einem Steinboden öffnet sich eine Spalte und der Boden senkt sich um 1 bis 1,2 m (1W4 Schaden für alle im Bereich). Gegen steinbasierte Kreaturen (Galeb Duhr, Xorn) verursacht ein erfolgreicher Berührungsangriff 12W8 Schaden (halb bei erfolgreichem Rettungswurf gegen Zauber). Versteinerte Kreaturen werden ausgelöscht (magische Gegenstände überleben bei erfolgreichem Gegenstandsrettungswurf gegen Auflösung mit −4). Kann durch Magie Bannen gekontert werden, wenn vor der Zertrümmerung gewirkt. Materialkomponente: Ein einzelner diamantbesetzter Meißel im Wert von mindestens 1.000 GM, der beim Wirken zerstört wird.',
  description_en = 'Cleaves the next stone object the caster touches. Force manifests as a spray of light, creating a thick, winding crack that reduces stone equal to the area of effect (10-ft. cube per level) to rubble at the end of the following round. A 12th-level wizard destroys a 12.2 m wide section of wall. Rubble fills the breach to half the original wall''s height. On a stone floor, a fissure opens and the floor drops 1 to 1.2 m (1d4 damage to those in the area). Against stone-based creatures (galeb duhr, xorn), a successful touch attack deals 12d8 damage (half on a successful save vs. spell). Petrified creatures are obliterated (magical items survive on a successful item save vs. disintegration at −4). Can be countered by Dispel Magic if cast before the rubble forms. Material component: A single diamond-tipped chisel worth at least 1,000 gp, destroyed in the casting.'
WHERE LOWER(name_en) = LOWER('Ballant''s Stonesplit') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Barrierebrecher',
  description = 'Erzwingt eine Öffnung in jeder magischen Barriere, einschließlich Antimagiehülle, Prismatische Kugel oder beschworener physischer Barrieren wie Eisenwand. Die Öffnung entsteht am Ende der Wirkrunde und besteht für die gesamte nächste Runde. Während dieser Zeit können Zauber und Angriffe durch die Öffnung geschickt, passende Kreaturen hindurchgehen und der Bereich dahinter beobachtet werden. Der Zauberkundige kann in der Runde der offenen Passage einen weiteren Zauber wirken. Der Barrierebrecher zerstört die Barriere nicht — die Öffnung schließt sich am Ende der Runde und verursacht 6W6 Scherschaden bei jeder Kreatur, die sich darin befindet. Betroffene werden gewaltsam auf eine Seite der Barriere geschleudert (50 % Chance für jede Seite). Durchmesser und Länge der zylindrischen Öffnung: 0,3 m pro Stufe. Materialkomponente: Ein kleiner Metallschlüssel.',
  description_en = 'Forces an opening in any magical barrier, including Antimagic Shell, Prismatic Sphere, or conjured physical barriers such as Wall of Iron. The opening appears at the end of the casting round and lasts for the entire next round. During this time, spells and attacks can be launched through it, fitting creatures can pass through, and the area beyond can be observed. The caster is free to cast another spell during the round the opening exists. The spell does not destroy the barrier — the opening closes at the end of the round, inflicting 6d6 shearing damage on any creature caught within it and forcibly expelling them to one side (50% chance for either side). Cylinder diameter and length: 0.3 m per level. Material component: A small metal key.'
WHERE LOWER(name_en) = LOWER('Barrier Reaver') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Bigbys Belagerungsbolzen',
  description = 'Ähnlich wie Magisches Geschoss, aber deutlich mächtiger. Der Zauberkundige kann einen magischen Belagerungsbolzen pro zwei Stufen abfeuern. Jeder Bolzen verhält sich wie ein Geschoss eines bestimmten Belagerungsgeräts in Reichweite und Wirkung. Die Art hängt von der Stufe ab: Ab Stufe 12 leichtes Katapult, ab Stufe 14 schweres Katapult, ab Stufe 16 Trebuchet. Die Bolzen müssen einzeln in aufeinanderfolgenden Runden abgefeuert werden (einer alle zwei Runden). Während dieser Zeit kann der Zauberkundige nichts anderes tun. Wird der Zauber unterbrochen, können keine weiteren Bolzen abgefeuert werden. Die Bolzen treffen ihr Ziel unfehlbar. Materialkomponente: Ein kleiner Stein, bestreut mit Diamantstaub.',
  description_en = 'Similar to Magic Missile but far more powerful. The wizard can fire one magical siege bolt per two caster levels. Each bolt behaves as a given siege engine missile in range and effect. The type depends on caster level: 12th — light catapult, 14th — heavy catapult, 16th — trebuchet. Bolts must be launched one at a time in succeeding rounds (one every two rounds). During this time the caster can do nothing else. If the spell is interrupted, no additional bolts can be launched. The bolts strike their target unerringly. Material component: A small stone sprinkled with diamond dust.'
WHERE LOWER(name_en) = LOWER('Bigby''s Besieging Bolt') AND spell_type = 'wizard';
