-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 4 (Batch 1: 15 Spells — Acid Bolt to Bands of Ice)
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  description = 'Beschwört zwei tropfenförmige Bolzen fleischzersetzender Kraft, die von den Händen des Zauberkundigen auf ihre Ziele zufliegen — unfehlbar treffend. Jedes Ziel muss eine einzelne sichtbare Kreatur sein. Einmal geworfen, folgt ein Bolzen auch einem fliehenden Ziel und weicht Hindernissen und anderen Kreaturen aus. Der Zauberkundige kann nicht auf bestimmte Körperteile oder getragene Gegenstände zielen. Jeder Treffer verursacht 4W4 Schaden. Skelettartige oder nichtkörperliche Untote und nichtlebende Objekte werden nicht betroffen. Komponenten: V, S.',
  description_en = 'Summons two teardrop-shaped bolts of flesh-corrosive force that dart from the caster''s hands to unerringly strike their targets. Each target must be a single visible creature. Once hurled, a bolt follows a fleeing target and dodges obstacles and other creatures. The caster cannot aim at specific body parts or carried items. Each hit deals 4d4 damage. Skeletal or noncorporeal undead and nonliving objects are unaffected. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Acid Bolt') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt einen kontinuierlichen, geraden Strom schimmernder Flüssigkeit aus der Hand des Zauberkundigen (Angriffswurf für direkten Treffer). Beim Aufprall bildet sich eine 3-m-Radius-Kugel aus Säure und explodiert nach außen. Kreaturen in der Kugel: 4W4 Säureschaden, alle getragenen Gegenstände müssen RW gegen Säure bestehen. Fortgesetzter Effekt: 1W4 zusätzlicher Säureschaden pro 3 Stufen des Zauberkundigen pro Runde (bei Stufe 10: max. 3 Zusatzrunden mit 3W4). Säure kann durch mindestens 2 Liter Wasser/Wein neutralisiert werden. Spritzschaden (6,1-m-Gefahrenzone): 2W4 Säureschaden, nur in der Aufschlagrunde. Materialkomponente: V, S, M (Speichel, ein Wurfpfeil/Dorn/Nadel/Eiszapfen, eine Kristall-/Glaskugel und eine Glasphiole Säure).',
  description_en = 'Creates a continuous straight stream of shimmering liquid from the caster''s hand (attack roll for direct hit). On impact, it forms a 3 m radius sphere of acid and explodes outward. Creatures in the sphere: 4d4 acid damage, all exposed items must save vs. acid. Continuing effect: 1d4 additional acid damage per 3 caster levels per round (at level 10: max 3 extra rounds of 3d4). Acid can be neutralized by at least 2 liters of water/wine. Splash damage (6.1 m danger zone): 2d4 acid damage, only the impact round. Material component: V, S, M (spittle, a dart/thorn/needle/icicle, a crystal/glass sphere, and a glass vial of acid).'
WHERE LOWER(name_en) = LOWER('Acid Bolt — Drow') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Betrifft eine Kreatur, die durch eine Klingenwaffe verwundet wurde. Öffnet verbundene Wunden wieder (oder lässt unverbundene schwer bluten): 2W6 Schaden. Rettungswurf gegen Zauber: bei Erfolg kein weiterer Schaden. Bei Misserfolg: 1W3 zusätzlicher Schaden pro Runde bis die Wunde verbunden wird. Kreaturen ohne Blut (Skelette), mit Regeneration oder unter Wirkung eines Periapts der Wundschließung sind immun. Materialkomponente: V, S, M (eine Prise Salz).',
  description_en = 'Affects a creature wounded by an edged weapon. Reopens bound wounds (or causes unbound wounds to bleed severely): 2d6 damage. Save vs. spell: on success, no further damage. On failure: 1d3 additional damage per round until the wound is dressed and bound. Creatures without blood (skeletons), with regeneration, or under a periapt of wound closure are immune. Material component: V, S, M (a pinch of salt).'
WHERE LOWER(name_en) = LOWER('Agitate Wounds — Old Empire') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Schützt den Zauberkundigen oder einen berührten Empfänger durch ein enganliegendes magisches Verteidigungsfeld. Normalerweise unsichtbar, kann aber auf Wunsch des Trägers schimmern, schwach leuchten (in jeder Farbe) oder hell strahlen (ausreichend zum Lesen oder um 3 m in Dunkelheit zu sehen). Wehrt alle physischen Waffen ab, AUSSER magisch verzauberte. Verhindert die Wirkung aller Zauber der 1. oder 2. Stufe oder gleichwertiger magischer Gegenstände innerhalb des Feldes. Der Zauberkundige könnte z.B. in einer Flammenkugel stehen ohne Schaden zu nehmen. Treffen zwei Mäntel aufeinander, verursacht das wirbelnde magische Chaos beiden Trägern 4W8 Schaden und 1W2 Runden Hilflosigkeit, die Mäntel kollabieren. Materialkomponente: V, S, M (eine winzige Glasphiole, in die der Zauberkundige mindestens 24 Stunden vorher hineingeatmet und sie dann verschlossen hat).',
  description_en = 'Protects the caster or a touched recipient with a close-fitting magical defensive field. Normally invisible, but can shimmer, glow faintly (any hue), or shine brightly (enough to read or see 3 m in darkness) at the wearer''s will. Wards off all physical weapons EXCEPT those bearing magical enchantment. Prevents functioning of all 1st- or 2nd-level spells or equivalent magical item effects within. The caster could stand in a Flaming Sphere''s path unharmed. If two Mantles ever touch, the swirling magical chaos deals 4d8 damage to both wearers and 1d2 rounds of helplessness as the mantles collapse. Material component: V, S, M (a tiny glass vial the caster breathed into and stoppered at least 24 hours before casting).'
WHERE LOWER(name_en) = LOWER('Alustriel''s Mantle') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Wird oft von Magiern für Zuchtprojekte verwendet. Erhöht die Chance einer erfolgreichen Paarung um 5% pro Stufe (max. 95%), vorausgesetzt die Subjekte sind nicht steril. Garantiert keinen lebensfähigen Nachwuchs — nur eine erfolgreiche Paarung. Kann einmal pro Paar pro Paarungssaison gewirkt werden. Scheitert bei Kreaturen ohne spezifische Paarungssaison. Materialkomponente: V, S, M (ein Haar, eine Schuppe, eine Feder o.ä. von jeder Kreatur).',
  description_en = 'Often used by wizards for breeding projects. Raises the chance of successful mating by 5% per level (max 95%), assuming the subjects are not sterile. Does not guarantee viable offspring — only a successful mating. Can be cast once per pair per mating season. Fails on creatures without a specific mating season. Material component: V, S, M (a hair, scale, feather, or similar item from each creature).'
WHERE LOWER(name_en) = LOWER('Animal Magnetism') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ein Arcane — oder ein in deren Runen ausgebildeter Magier — kann eine Nachricht oder einen längeren Text unsichtbar in einer Schriftrolle, einem Buch oder Band verbergen. Ähnlich dem Magierzeichen der 1. Stufe, aber die Runen werden NICHT von Magie Entdecken angezeigt. Nur Wahres Sehen oder der Zauber Arkane Runen Lesen enthüllt sie. Arcane (Spelljammer-Händler) können ihre Runen auf Sicht lesen. Materialkomponente: V, S, M (eine Prise getrockneter, gepulverter Zitrone und ein Griffel).',
  description_en = 'An Arcane — or a wizard trained in their runes — can inscribe a message or longer text, hiding it invisibly within a scroll, book, or tome. Similar to the 1st-level Wizard Mark, but the runes do NOT show up with Detect Magic. Only True Seeing or the Read Arcane Runes spell reveals them. Arcane (Spelljammer traders) can read their runes on sight. Material component: V, S, M (a pinch of dried powdered lemon and a stylus).'
WHERE LOWER(name_en) = LOWER('Arcane Runes') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt einen leuchtenden Energieblitz, indem ein kristalliner Fokus auf ein Ziel geworfen wird (bis 3 m pro Stufe). 1,2 m Durchmesser, beginnt 3 m vom Zauberkundigen. Hält 2 Runden. Direkter Treffer (Angriffswurf als Geschoss): 1W6 Schaden pro TW/Stufe der getroffenen Kreatur (max. 10W6), RW gegen Zauber für halben Schaden plus Systemschock-Wurf. Jede lebende Kreatur, die den Blitz berührt (nicht direkt vom Kristall getroffen): 1W4 Schockschaden pro TW/Stufe (max. 10W4). Bildet sich nicht in Wasser. Kann nicht abgelenkt, geerdet oder isoliert werden (nur durch Antimagie). Materialkomponente: V, S, M (ein kristalliner Fokus von mind. 2,5 cm — facettierter Edelstein, Quarz oder Schliffglas; wird beim Werfen verbraucht).',
  description_en = 'Creates a luminescent energy bolt by hurling a crystalline focus at a target (up to 3 m per level). 1.2 m diameter, starts 3 m from caster. Lasts 2 rounds. Direct hit (attack roll as missile): 1d6 damage per target''s HD/level (max 10d6), save vs. spell for half plus system shock roll. Any living creature touching the bolt (not hit by crystal): 1d4 shock damage per HD/level (max 10d4). Won''t form in water. Cannot be deflected, grounded, or insulated (only antimagic). Material component: V, S, M (a crystalline focus at least 2.5 cm — faceted gem, quartz, or cut glass; consumed when thrown).'
WHERE LOWER(name_en) = LOWER('Archveult''s Skybolt') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Hüllt den Empfänger in ein ständig wechselndes, wallendes Geflecht aus unkörperlichen, dunklen Schatten. Verschleiert Gesicht, Erscheinungsbild und genaue Position. Gewährt +2 RK-Bonus (z.B. RK 6 wird RK 4). Fernkampfwaffen erleiden −1 auf Angriffswürfe. Evards Schwarze Tentakel und Netz-Zauber werden bei Kontakt sofort negiert und zerstört. Diebe mit dem Zauber erhalten +5% auf Im-Schatten-Verbergen. Materialkomponente: V, S, M (ein Stück Spinnwebe und eine Prise Staub).',
  description_en = 'Wraps the recipient in an ever-shifting, roiling webwork of intangible dark shadows. Veils face, appearance, and precise location. Grants +2 AC bonus (e.g., AC 6 becomes AC 4). Missile weapons suffer −1 to attack rolls. Evard''s Black Tentacles and Web spells are immediately negated and destroyed on contact. Thieves with the spell gain +5% to Hide in Shadows. Material component: V, S, M (a bit of cobweb and a pinch of dust).'
WHERE LOWER(name_en) = LOWER('Argaster''s Cloak of Shadows') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Lässt eine unsichtbare Gliedmaße (Arm, Hand, Bein oder Fuß) entstehen. Kann eine fehlende Gliedmaße ersetzen oder eine zusätzliche erzeugen. Die unsichtbare Gliedmaße funktioniert genau wie eine normale, kann aber auf Wunsch des Empfängers teilweise immateriell werden und durch feste Objekte hindurchgreifen (z.B. eine Flasche in einer geschlossenen Truhe entkorken — aber nicht aus der Truhe entfernen). Kann keine magischen Kraftbarrieren passieren und wird von Schutz vor Bösem abgehalten. Kann eine Waffe nur führen, wenn sie eine fehlende Hand/Arm ersetzt. Hat normalen Tastsinn, verleiht aber keine anderen Sinne. Hat keine TP oder RK und kann nicht beschädigt werden (nur gebannt). Materialkomponente: V, S, M (der Schwanz einer Eidechse, die verlorene Körperteile regeneriert).',
  description_en = 'Creates an invisible limb (arm, hand, leg, or foot). Can replace a missing limb or create an extra one. The invisible limb functions exactly as normal but parts can become immaterial to pass through solid objects (e.g., uncork a potion inside a closed chest — but not remove it). Cannot pass magical force barriers and is hedged out by Protection from Evil. Can wield a weapon only if replacing a missing arm/hand. Has normal touch sensation but no other senses. Has no HP or AC and cannot be harmed (only dispelled). Material component: V, S, M (the tail of a lizard that regenerates lost body parts).'
WHERE LOWER(name_en) = LOWER('Arnvid''s Unseen Limb') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Durch diesen Fluch kann ein Magier die Magie eines anderen Zauberkundigen nach hinten losgehen lassen. Rettungswurf gegen Zauber beim Wirken; bei Erfolg kein Effekt. Bei Misserfolg: kein sofortiges Ergebnis (nur eine schwache magische Spur erkennbar). Der Rückschlag wird ausgelöst, wenn: (1) ein offensiver Zauber scheitert, weil das Ziel seinen RW besteht, (2) ein offensiver Zauber unterbrochen wird, oder (3) ein offensiver Zauber gegen eine immune Kreatur eingesetzt wird. Der Rückschlag bewirkt, dass der offensive Zauber mit voller Wirkung auf den eigenen Zauberkundigen wirkt — alle RW und Immunitäten ignorierend. Wirkt nur einmal. Wirkt nicht auf Nichtmagier, natürliche zauberartige Fähigkeiten oder magische Gegenstände. Nur durch Fluch Aufheben oder stärkeren Zauber entfernbar (Magie Bannen unwirksam). Komponenten: V, S.',
  description_en = 'Through this curse, a wizard can make another caster''s magic backfire. Save vs. spell when cast; success negates. On failure: no immediate result (only a faint magical trace detectable). The backlash triggers when: (1) an offensive spell fails because the target saved, (2) an offensive spell is interrupted, or (3) an offensive spell is used against an immune creature. The backlash causes the offensive spell to work with full effect on the caster, disregarding all saving throws and immunities. Works only once. No effect on non-spellcasters, natural spell-like powers, or magical devices. Only removable by Remove Curse or stronger (Dispel Magic ineffective). Components: V, S.'
WHERE LOWER(name_en) = LOWER('Backlash — Drow') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Fängt eine Kreatur in dicken Eisbändern ein. Kann Kreaturen bis zu 0,3 m pro Stufe Höhe halten (Stufe 10 = bis 3 m). Breite Kreaturen (z.B. Umber Hulk): +0,3-0,6 m zur effektiven Höhe addieren. Rettungswurf gegen Zauber: bei Erfolg — Eis ist spröde, Entkommen in einer Runde. Bei Misserfolg — mindestens 1 Runde gefangen, dann pro Runde Stangen-biegen/Gitter-heben-Wurf ob das Eis genug geschmolzen ist. Normale Dauer: 2 Runden. In kalter Umgebung (≤4°C): 4 Runden. Sehr kalt (≤−18°C): 6 Runden. Fackel verkürzt um 1 Runde pro Runde Erhitzung. Magisches Feuer (Feuerkugel) schmilzt das Eis, verletzt aber die gefangene Kreatur. Kälteschaden: 1W6 pro Runde (Kältewesen immun, Feuerwesen doppelter Schaden, hitzekörpige Kreaturen schmelzen das Eis doppelt so schnell). Materialkomponente: V, S, M (Nickelkettenglieder, ein eisernes Reifenstück und etwas Schnee).',
  description_en = 'Traps a creature in thick bands of ice. Can hold creatures up to 0.3 m tall per level (level 10 = up to 3 m). Broad creatures (umber hulk): add 0.3-0.6 m to effective height. Save vs. spell: success — ice is brittle, escape in one round. Failure — trapped for at least 1 turn, then bend bars/lift gates roll each turn. Normal duration: 2 turns. Cold environment (≤4°C): 4 turns. Very cold (≤−18°C): 6 turns. Torch shortens by 1 round per round of heating. Magical fire (fireball) melts ice but injures the trapped creature. Cold damage: 1d6 per turn (cold creatures immune, fire creatures double damage, high body heat creatures melt ice twice as fast). Material component: V, S, M (nickel chain links, iron hoop piece, and a bit of snow).'
WHERE LOWER(name_en) = LOWER('Bands of Ice') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Wird vom Wu Jen genutzt, um die Dienste niederer und höherer Geister zu erhalten. Vorher muss der Geist kontaktiert werden (durch einen Kommunion-Zauber). Bei missglücktem Rettungswurf gegen Zauber kann der Wu Jen einen Dienst verlangen, sofern dieser in der Macht des Geistes liegt. Der Geist ist verpflichtet, wenn der Wu Jen eine Gegenleistung erbringt, die der Geist verlangt. Der Zauber begrenzt die Forderungen des Geistes auf maximal den halben Wert des vom Wu Jen verlangten Dienstes. Spieler und SL verhandeln die genauen Bedingungen. Erfüllt der Wu Jen seinen Teil nicht, sendet die Himmlische Bürokratie eine Strafe: −2 auf alle Angriffs- und Rettungswürfe bis zur Erfüllung. Materialkomponente: V, S, M (eine Schale Weihrauch).',
  description_en = 'Used by the wu jen to obtain services of lesser and greater spirits. The spirit must first be contacted (through a Commune spell). On a failed save vs. spell, the wu jen can demand one service within the spirit''s power. The spirit is compelled if the wu jen provides something the spirit demands. The spell limits the spirit''s demands to max half the value of the wu jen''s requested service. Player and DM negotiate exact terms. If the wu jen fails to deliver, the Celestial Bureaucracy sends punishment: −2 on all attack and saving throws until fulfilled. Material component: V, S, M (a bowl of incense).'
WHERE LOWER(name_en) = LOWER('Bargain') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Lässt die offenen, blutenden Wunden einer Kreatur in Flammen aufgehen und verwandelt das Blut in eine ätzende Mischung: 3W4 zusätzlicher Schaden pro Runde. „Offene Wunden" = Wunden durch Klingenwaffen, die nicht verbunden oder geheilt wurden. Die Kreatur muss Blut haben — Untote und blutlose extraplanare Wesen (Elementare) sind immun. Feuerresistente Kreaturen ebenfalls. In jeder der 3 Wirkrunden: Rettungswurf gegen Zauber mit −3; bei Erfolg kein weiterer Schaden. Der Zauberkundige muss das Ziel weder berühren noch sehen — nur innerhalb der Reichweite. Kreaturen in veränderter Gestalt oder in Objekten (Baum, Fels) sind weiterhin verwundbar. Regeneration: normaler RW um weiteren Schaden zu verhindern. Materialkomponente: V, S, M (Vorhandensein von freiliegendem Blut und eine Prise Salpeter).',
  description_en = 'Causes the open, bleeding wounds of a creature to burst into flame, converting blood to a corrosive mix: 3d4 additional damage per round. "Open wounds" = wounds from edged weapons not dressed or healed. The creature must have blood — undead and bloodless extraplanar creatures (elementals) are immune. Fire-resistant creatures are also immune. Each of 3 rounds: save vs. spell at −3; success prevents further damage. The caster need not touch or see the target — just within range. Creatures in changed shape or inside objects (tree, rock) are still vulnerable. Regeneration: normal save to prevent further damage. Material component: V, S, M (presence of exposed blood and a pinch of saltpeter).'
WHERE LOWER(name_en) = LOWER('Beltyn''s Burning Blood') AND spell_type = 'wizard';
