-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 4 (Batch 3: 19 Spells — Bone Form to Darsson's Potion)
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  description = 'Erschafft ein beliebiges Objekt kleiner als 0,9 m (Länge/Höhe/Tiefe) aus Knochenmaterial. Der Zauberkundige braucht einen Vorrat an Knochen. Waffen können erschaffen werden — diese sind böse, aber nicht magisch zum Treffen von Kreaturen, die nur von magischen Waffen getroffen werden. Keine Boni oder Abzüge auf Angriff oder Schaden. Dauer 1-20 Stunden. Materialkomponente: V, S, M (genug Knochen für den gewünschten Gegenstand und ein Tropfen Körperflüssigkeit).',
  description_en = 'Creates any object less than 0.9 m (length/height/depth) out of bone matter. The caster needs a supply of bones. Weapons can be created — they are evil but not magical for striking creatures only hit by magic weapons. No bonuses or penalties to attack or damage. Duration 1-20 hours. Material component: V, S, M (enough bones for the desired item and a drop of body fluid).'
WHERE LOWER(name_en) = LOWER('Bone Form') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Zerstört permanent einen Teil des Gehirns einer intelligenten Kreatur und löscht damit unwiderruflich Erinnerungen an einen bestimmten Ort, eine Person oder einen Zeitraum von bis zu einem Jahr (Wahl des Zauberkundigen). Rettungswurf gegen Todesmagie: bei Erfolg nur schmerzhafte Kopfschmerzen für 1W4 Stunden. Bei Misserfolg: 1W6 Schaden und ausgewählte Gedächtnislücken. Betrifft nur Erinnerungen und Faktenrückruf — erlernte Fähigkeiten bleiben erhalten (Schwimmen-Fertigkeit bleibt, aber keine Erinnerung an den Unterricht). „Getötete" Erinnerungen können nur durch einen Wunsch wiederhergestellt werden. Komponente: V.',
  description_en = 'Permanently destroys a portion of an intelligent creature''s brain, irrevocably erasing memories of either a specific place, a person, or a time period of up to one year (caster''s choice). Save vs. death magic: on success, only a painful headache for 1d4 hours. On failure: 1d6 damage and selected memory gaps. Affects only memory and fact recall — learned skills are retained (swimming proficiency remains, but no memory of lessons). "Killed" memories can only be regained by a Wish. Component: V.'
WHERE LOWER(name_en) = LOWER('Brainkill') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Zauberkundige atmet 1W6 Blasen in Richtung eines oder mehrerer Feinde. Pro Blase ein Angriffswurf nötig; verfehlt sie, schwebt sie harmlos davon und platzt. Bei Treffer wird die Kreatur sofort mit einer filmartigen Schmiere überzogen: Bewegungsrate halbiert, −2 auf alle Kampfwürfe und Rettungswürfe. Materialkomponente: V, S, M (ein Stück Baumsaft, das der Zauberkundige schlucken muss).',
  description_en = 'The caster breathes forth 1d6 bubbles toward one or more foes. Each bubble requires an attack roll; on a miss, it floats harmlessly away and pops. On a hit, the creature is instantly coated with filmy goo: movement rate halved, −2 on all combat rolls and saving throws. Material component: V, S, M (a bit of tree sap the caster must swallow).'
WHERE LOWER(name_en) = LOWER('Bubble Breath') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verursacht bei erfolgreichem Berührungsangriff 2W8+1 Schadenspunkte. Nichtkörperliche, nichtlebende und extraplanare Kreaturen werden nicht betroffen, außer Untoten — diese werden stattdessen geheilt. Oft in Kombination mit Spektralhand (2. Stufe) eingesetzt. Das Wirken ist eine böse Handlung. Materialkomponente: V, S, M (Paste auf die Hände aufgetragen und durch Befehlswort aktiviert; Kosten 200 GM für vier Anwendungen).',
  description_en = 'Inflicts 2d8+1 damage on a successful touch attack. Noncorporeal, nonliving, and extraplanar creatures are not affected, except undead — which are cured instead. Often used with Spectral Hand (2nd level). Casting is an evil act. Material component: V, S, M (paste rubbed on the hands, activated by command word; 200 gp cost for four castings).'
WHERE LOWER(name_en) = LOWER('Cause Serious Wounds') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Nekromanten-Version von Monster Bezaubern. Kann geistlose Untote (Zombies, Skelette) gleich der Stufe des Zauberkundigen ohne RW beherrschen — dient bis zum Aufheben. Alternativ ein einzelner halbintelligenter oder intelligenterer Untoter (INT 2+): RW gegen Zauber (bei halber Stufe des Zauberkundigen: −3 Abzug). Der beherrschte Untote betrachtet den Magier als seinen Herrn und gehorcht allen außer selbstzerstörerischen Befehlen. Feindliche Handlungen des Zauberkundigen brechen den Zauber. Entweichungschance pro Woche variiert mit TW (5% bei 2 TW bis 90% bei 12+ TW). Mächtige Untote (75% Chance) greifen den Zauberkundigen nach Ablauf an. Komponenten: V, S.',
  description_en = 'Necromancer''s version of Charm Monster. Can control mindless undead (zombies, skeletons) equal to the caster''s level without save — serves until countered. Alternatively, one single semi-intelligent+ undead (INT 2+): save vs. spell (at half caster level: −3 penalty). The charmed undead regards the wizard as its lord and obeys all but self-destructive orders. Hostile acts by the caster break the spell. Weekly escape chance varies with HD (5% at 2 HD to 90% at 12+ HD). Powerful undead (75% chance) attack the wizard when the spell ends. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Charm Undead') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht dem Zauberkundigen, eine einzelne Kreatur von einer Elementar- oder Para-Elementarebene zu befehligen (oder die Kontrolle zu entreißen). Das Ziel erhält einen Rettungswurf; Elementare mit niedriger Intelligenz oder weniger erleiden −4 Abzug. Bei Misserfolg: der Zauberkundige kontrolliert den Elementar für die Zauberdauer und überschreibt alle anderen Kontrollen (einschließlich anderer Elementar-Befehlen-Zauber). Komponenten: V, S.',
  description_en = 'Enables the caster to command (or wrest command of) a single creature from an elemental or para-elemental plane. The target gets a saving throw; elementals of low intelligence or lower suffer −4 penalty. On failure: the wizard controls the elemental for the duration, overriding all other controls including other Command Elemental spells. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Command Elementals — Old Empire') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Nur von Barden wirkbar. Der Barde muss zuvor ein spezielles Kabinett anfertigen lassen (mind. 1.000 GM, max. 1,2 × 1,2 × 2,4 m), es benennen und erstmalig verzaubern. Bei späterem Wirken teleportiert das benannte Kabinett vorübergehend zum aktuellen Standort des Barden (mit allen Aufführungsgegenständen darin). Würfelwurf: 01-04 = erscheint 737,6 m in der Luft und zerstört sich beim Aufprall (Inhalt bergbar); 99-00 = teleportiert in den Boden, zerstört; sonst sicher. Das Kabinett bleibt bis Ablauf oder bis der Barde seinen Namen spricht; dann teleportiert es sicher zurück. Nur ein solches Kabinett gleichzeitig. Funktioniert nicht zwischen Ebenen. Nichtperformante Gegenstände verhindern die Teleportation. Komponenten: V, S.',
  description_en = 'Only castable by bards. The bard must first have a special cabinet made (at least 1,000 gp, max 1.2 × 1.2 × 2.4 m), name it, and initially enchant it. Later castings teleport the named cabinet temporarily to the bard''s current location (with all performing items inside). Roll: 01-04 = appears 737.6 m in the air and falls, destroying itself (contents recoverable); 99-00 = teleports into the ground, destroyed; otherwise safe. The cabinet remains until expiry or until the bard speaks its name; then teleports safely back. Only one such cabinet at a time. Does not work between planes. Non-performing items prevent teleportation. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Conjure Cabinet — Bard') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Beschwört ein reales Objekt (bis Schwertgröße) aus dem Traumreich einer anderen Person. Der Zauberkundige muss das Objekt in jemandes Traum gesehen haben (durch Traum Betreten). Das beschworene Objekt ist in jeder Hinsicht real, hat aber NIEMALS magische Eigenschaften (selbst wenn im Traum magisch). Am Ende der Dauer kehrt es ins Traumreich zurück und kann erneut beschworen werden. Materialkomponente: V, S, M (ein Streifen Traumweidenrinde und ein Stück Material des gleichen Typs wie das zu beschwörende Objekt).',
  description_en = 'Conjures a real object (up to sword size) from another person''s dream realm. The caster must have seen the object in someone''s dream (via Enter Dream). The conjured object is real in all respects but NEVER has magical properties (even if magical in the dream). At the end of the duration, it returns to the dream realm and can be conjured again. Material component: V, S, M (a strip of dreamwillow bark and a bit of matter of the same type as the object to be summoned).'
WHERE LOWER(name_en) = LOWER('Conjure Dream Object') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Beschwört eine treue weibliche gefleckte Löwin. Sie greift nur auf Befehl des Zauberkundigen an. Der Zauberkundige kann durch die Augen der Löwin sehen (eigene Sicht unverändert). Keine Konzentration nötig zur Aufrechterhaltung oder Kontrolle. Kämpft bis zum Tod, Ablauf oder Entlassung. Kann als Reittier (BW 9) oder Packtier dienen (Tragkraft wie ein leichtes Pferd, BW 9 beibehalten). Immun gegen Verzauberung/Bezauberung und Nekromantie-Zauber sowie Priester-Sphären Tier, Heilung und Nekromantie. Aber: Zauber die speziell Kreaturen der Elementarebene der Erde betreffen (z.B. Phasentür) können das Tier verletzen. Materialkomponente: V, S, M (eine Handvoll Sand, in die Luft geworfen).',
  description_en = 'Conjures a faithful female spotted lion. It attacks only at the caster''s direction. The caster can see through the lion''s eyes (own vision unchanged). No concentration needed for maintenance or control. Fights to the death, expiry, or dismissal. Can serve as steed (MV 9) or pack animal (carries as much as a light horse, MV 9 maintained). Immune to Enchantment/Charm and Necromancy schools and Priest spheres of Animal, Healing, and Necromantic. But: spells specifically affecting creatures from the Elemental Plane of Earth (e.g., Phase Door) can harm the creature. Material component: V, S, M (a handful of sand tossed into the air).'
WHERE LOWER(name_en) = LOWER('Conjure Sand Lion') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Macht den Empfänger immun gegen die Effekte eines bestimmten Zaubers (beim Wirken benannt; der Zauberkundige muss ihn kennen oder in einem Zauberbuch/einer Rolle haben). Verbraucht die Materialkomponenten des zu konternden Zaubers. Dauer 1W6 Runden plus 1 pro Stufe — beginnt erst, NACHDEM der zu konternde Zauber auf das Ziel gewirkt wurde. Chance gleich der Stufe des Zauberkundigen in Prozent, den gekonkonterten Zauber auf seinen eigenen Wirker zurückzureflektieren. Zauber mit Flächeneffekt werden NICHT reflektiert. Materialkomponente: Verbraucht die Materialkomponenten des Gegenzaubers.',
  description_en = 'Makes the recipient immune to the effects of one specific spell (named at casting; the caster must know it or have it in a spellbook/scroll). Uses the material components of the countered spell. Duration 1d6 rounds plus 1 per level — only begins AFTER the countered spell has been targeted on the recipient. Chance equal to the caster''s level percentage to reflect the countered spell back on its caster. Spells with area effects are NOT reflected. Material component: uses the material components of the countered spell.'
WHERE LOWER(name_en) = LOWER('Counterspell Immunity') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verwandelt ein oder mehrere Säugetiere (max. 2 TW, 1 pro Stufe) in Dunkelbestien. Nur in Dunkelheit wirkbar (Nacht, drinnen, unterirdisch). Wirkt automatisch auf gewöhnliche, nichtmagische Säugetiere halb-intelligenter oder niedrigerer Stufe. Tiere mit INT 5+ erhalten einen Rettungswurf. Menschen, Humanoide und Halbmenschen sind immun. Die Verwandlung hält an, bis Tageslicht die Dunkelbestie trifft — dann kehrt sie sofort in ihre wahre Gestalt zurück. Getötete Dunkelbestien kehren bei Tageslicht ebenfalls zurück. Sonnenstrahl und magische Sonnenschwerter brechen den Zauber; Dauerlicht hat keinen Effekt. Materialkomponente: V, S, M (getrockneter Wyvern-Schuppen).',
  description_en = 'Transforms one or more mammals (max 2 HD, 1 per level) into darkenbeasts. Can only be cast in darkness (night, inside, underground). Automatically affects ordinary nonmagical mammals of semi-intelligence or lower. Animals with INT 5+ get a save. Humans, humanoids, and demihumans are immune. The transformation lasts until daylight strikes the darkenbeast — it instantly reverts. Slain darkenbeasts also revert in daylight. Sunray and magical sun swords break the spell; Continual Light has no effect. Material component: V, S, M (dried wyvern scale).'
WHERE LOWER(name_en) = LOWER('Create Darkenbeast') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht dem Zauberkundigen, einem entfernten Opfer Bestrafung und Schaden zuzufügen. Erfordert eine kleine Tonabbildung des Opfers (Herstellungsprozess = Wirkzeit). Der Zauberkundige muss den ungefähren Aufenthaltsort und das Aussehen des Ziels kennen. Festhalten der Abbildung: Opfer wird immobilisiert (Rettungswurf gegen Zauber pro Runde erlaubt 1 Runde Bewegung). Auf die Abbildung einschlagen: 1W10 Schaden pro Runde (RW für halben Schaden). Nicht gleichzeitig halten und schlagen möglich. Wird ein Stück Haar, Haut, Nagelschnitzel etc. des Opfers in die Abbildung eingearbeitet: −2 auf alle Rettungswürfe des Opfers. Materialkomponente: V, S, M (die Tonabbildung).',
  description_en = 'Allows the caster to inflict punishment and damage on a distant victim. Requires a small clay image of the victim (molding process = casting time). The caster must know the target''s general whereabouts and appearance. Holding the image tightly: victim is immobilized (save vs. spell per round allows 1 round of movement). Pummeling the image: 1d10 damage per round (save for half). Cannot hold and pummel simultaneously. If a bit of hair, skin, nail clippings, etc. of the victim is incorporated: −2 on all victim''s saves. Material component: V, S, M (the clay image).'
WHERE LOWER(name_en) = LOWER('Cursed Image — Hishna') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt eine feurige Faust (menschengroß) in der Luft innerhalb von 9,1 m, steuerbar innerhalb von 54,9 m. Einmal pro Runde: Berührung eines brennbaren Objekts (RW gegen magisches Feuer oder es brennt) ODER Angriff auf einen Gegner (Angriffswurf des Zauberkundigen, 1W4+1 Feuerschaden in 0,9-m-Radius). Bei Verfehlung: Schadenspotential wird gespeichert — nächster Treffer addiert allen gespeicherten Schaden (z.B. 2 Fehlschüsse + Treffer = 3W4+3). Bei Dauer-Ablauf ohne Treffer: gespeicherter Schaden explodiert am aktuellen Standort (RW gegen Zauber). Bei Konzentrationsverlust: Faust greift automatisch das letzte Ziel an. Materialkomponente: V, S, M (ein Handschuh passend für den Zauberkundigen, plus Schwefel und Phosphor).',
  description_en = 'Creates a fiery fist (human-sized) in midair within 9.1 m, controllable within 54.9 m. Once per round: touch a flammable object (save vs. magical fire or it burns) OR strike an opponent (caster''s attack roll, 1d4+1 fire damage in 0.9 m radius). On miss: damage potential is stored — next hit adds all stored damage (e.g., 2 misses + hit = 3d4+3). On duration expiry without hits: stored damage explodes at current location (save vs. spell). On loss of concentration: fist automatically attacks last target. Material component: V, S, M (a glove fitting the caster, plus sulphur and phosphorus).'
WHERE LOWER(name_en) = LOWER('Daltim''s Flaming Fist') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Der Wu Jen belebt ein nichtmagisches Schwert, das in die Luft springt und für eine vom Zauberkundigen bestimmte Person kämpft. Das Schwert muss von der Klasse des Beschützten nutzbar sein und darf nicht im Besitz eines anderen sein. Bleibt stets innerhalb von 1,5 m des Beschützten; fällt dieser, fällt das Schwert zu Boden. Erfordert keine Konzentration — der Beschützte kann gleichzeitig mit einer anderen Waffe kämpfen. Das Schwert hat dieselbe Anzahl Angriffe und Trefferchance wie der Beschützte, verursacht normalen Schaden (ohne STR-Bonus). Materialkomponente: V, S, M (eine winzige Stabpuppe, die in Richtung des zu Beschützenden geschwenkt wird).',
  description_en = 'The wu jen animates a nonmagical sword that springs into the air and fights for a person designated by the caster. The sword must be usable by the protected individual''s class and cannot be in another''s possession. Stays within 1.5 m of the individual; if they are slain, the sword drops. Requires no concentration — the protected person can fight with another weapon simultaneously. The sword has the same number of attacks and hit chance as the protected individual, dealing normal damage (no STR bonuses). Material component: V, S, M (a tiny stick puppet waved toward the individual to be protected).'
WHERE LOWER(name_en) = LOWER('Dancing Blade') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Belebt eine einzelne Waffe zum Fliegen und selbstständigen Angreifen (BW Fl 27, MK A) gegen ein bei der Wirkung gewähltes Ziel. Der Zauberkundige kann danach andere Zauber wirken oder sich anderen Aufgaben widmen. Die Waffe trifft IMMER: Beide Seiten würfeln 1W20 — Waffe höher: maximaler Schaden; Gleichstand: normaler Schadenswurf; Opfer höher: Nachwurf (gerade = 2 Schaden, ungerade = 1 Schaden). RK −1, 44 TP. Keine Gesinnung, immun gegen Geisteskontrolle. Kann nicht das Ziel wechseln; wenn das Ziel entkommt, endet der Zauber. Funktioniert nicht mit magischen Waffen (permanenter Dweomer). Dauer 7 Runden. Materialkomponente: V, S, M (ein Insektenflügel oder eine Vogelfeder).',
  description_en = 'Animates a single weapon to fly and attack independently (MV Fl 27, MC A) against a target chosen at casting. The caster can then cast spells or attend to other tasks. The weapon ALWAYS hits: both sides roll 1d20 — weapon higher: maximum damage; tie: normal damage roll; victim higher: reroll (even = 2 damage, odd = 1 damage). AC −1, 44 HP. No sentience, immune to mind control. Cannot switch targets; if target escapes, spell ends. Won''t work on magical weapons (permanent dweomer). Duration 7 rounds. Material component: V, S, M (an insect wing or bird feather).'
WHERE LOWER(name_en) = LOWER('Dancing Weapon — Alhoon') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt einen Blitz aus „negativem Licht". Der Blitz ist so schwarz, dass jeder der ihn sieht eine 10%-Chance hat, für 1W4 Runden zu erblinden. Schwarze Funken und Dunkelheitstentakel spielen um den Blitz. Er beginnt bis zu 164,6 m vom Zauberkundigen entfernt und erstreckt sich 18,3 m weiter (18,3 m lang, 1,5 m breit). Verursacht 1W6 Schaden pro Stufe (max. 10W6), Rettungswurf gegen Zauber für halben Schaden. Trifft der Blitz eine feste Oberfläche (Wand), prallt er zum Zauberkundigen zurück bis die Gesamtlänge von 18,3 m erreicht ist. Materialkomponente: V, S, M (ein Onyxstab und ein Stück schwarzes Fell).',
  description_en = 'Creates a bolt of "negative lightning." The bolt is so black that anyone seeing it has a 10% chance of going blind for 1d4 turns. Black sparks and tendrils of darkness play about it. It starts up to 164.6 m from the caster and extends 18.3 m further (18.3 m long, 1.5 m wide). Deals 1d6 damage per level (max 10d6), save vs. spell for half. If the bolt strikes a solid surface (wall), it bounces back toward the caster until the total length of 18.3 m is reached. Material component: V, S, M (an onyx rod and a bit of black fur).'
WHERE LOWER(name_en) = LOWER('Darkning Bolt') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Programmierte Levitation: Alle Personen und lose Objekte im 3-m-Durchmesser-Bereich schweben auf eine gewünschte Höhe (max. 9,1 m pro Stufe, Limit 91,4 m), drehen sich einmal im Kreis und kehren sanft zum Boden zurück. Aufstieg: 1 Runde. Kreisen: 1 Runde (Objekte in der Mitte drehen sich an Ort und Stelle). Abstieg: Ende der 3. Runde. Alle betroffenen Objekte steigen und fallen gleich schnell und behalten ihre relativen Positionen. Bei Deckenblockade stoppen sie sanft davor. Ein einzelnes größeres Objekt kann ebenfalls gehoben werden. Ermöglicht Aufklärung aus der Luft und sichere Rückkehr zum Boden. Materialkomponente: V, S, M (ein Vogelauge).',
  description_en = 'Programmed levitation: all people and loose objects in a 3 m diameter area float up to a desired height (max 9.1 m per level, limit 91.4 m), rotate once, and return gently to the ground. Ascent: 1 round. Circling: 1 round (center objects just rotate in place). Descent: end of 3rd round. All affected objects rise and fall at the same rate, maintaining relative positions. If blocked by a ceiling, they stop gently. A single larger object can also be lifted. Enables aerial scouting and safe return. Material component: V, S, M (the eye of a bird).'
WHERE LOWER(name_en) = LOWER('Darsson''s Eye in the Sky') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Bereitet eine Phiole Wasser vor, einen anderen Zauber aufzunehmen — erzeugt einen „sofortigen" temporären Trank. Sofort nach dem Wirken muss der Zauberkundige (oder ein anderer Magier) einen zweiten Zauber auf die Phiole wirken. Statt normal zu wirken, wird der zweite Zauber im Wasser absorbiert und erzeugt einen temporären Trank. Der zweite Zauber muss 3. Stufe oder niedriger sein und einer sein, den der Wirker auf sich selbst wirken könnte (z.B. Federfall, Schild, Leichte Wunden Heilen — aber nicht Freunde, Identifizieren, Schockgriff oder Feuerkugel). Der Trank kann jederzeit während der Dauer getrunken werden und wirkt auf den Trinker als wäre der Zauber auf ihn gewirkt worden. Materialkomponente: V, S, M (eine Phiole mit mindestens 30 ml sauberem Wasser).',
  description_en = 'Prepares a vial of water to accept another spell — creates an "instant" temporary potion. Immediately after casting, the wizard (or another spellcaster) must cast a second spell at the vial. Instead of its normal effect, the second spell is absorbed into the water, creating a temporary potion. The second spell must be 3rd level or lower and one the caster could cast on himself (e.g., Feather Fall, Shield, Cure Light Wounds — but not Friends, Identify, Shocking Grasp, or Fireball). The potion can be drunk anytime during the duration, taking effect as if the spell were cast on the drinker. Material component: V, S, M (a vial with at least 30 ml of clean water).'
WHERE LOWER(name_en) = LOWER('Darsson''s Potion') AND spell_type = 'wizard';
