-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 5 (Batch 1: 15 Spells — Aiming at the Target to Bind Undead)
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  description = 'Ergebnis des Wu-Jen-Ki-Trainings. Erlaubt dem Wu Jen, sich auf eine einzelne Handlung zu konzentrieren, ungeachtet anderer Aktionen. Einer von nur zwei Zaubern, die ein Wu Jen wirken kann, ohne die Konzentration eines anderen Zaubers zu brechen. Nach dem Wirken kann sich der Wu Jen normal bewegen, seinen GES-Verteidigungsanpassung nutzen, Schaden erleiden und Rettungswürfe bestehen, ohne die Konzentration zu verlieren. Dauer: 2 Runden oder bis die Konzentration auf den ersten Zauber endet. Komponente: S.',
  description_en = 'Result of the wu jen''s ki training. Allows the wu jen to concentrate on a single action regardless of other actions. One of only two spells castable without breaking concentration on another spell. After casting, the wu jen can move normally, receive DEX defensive adjustment, suffer damage, and make saves without breaking concentration. Duration: 2 turns or until concentration on the first spell ends. Component: S.'
WHERE LOWER(name_en) = LOWER('Aiming at the Target') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Schützt ein magisches Objekt oder eine verzauberte Kreatur vor Manipulation durch andere Magier. Bleibt ruhend bis jemand Magie Bannen auf das Objekt wirkt. Der Rückschlag lässt den Bannen-Versuch automatisch scheitern UND der bannende Magier verliert einen memorierten Zauber gleicher Stufe wie der zu bannende Effekt (oder den nächstniedrigeren, falls keiner vorhanden). Wirkt nicht gegen einen Magier höherer Stufe als den Wirkenden — dieser bannt dann sowohl den Schutz als auch den geschützten Zauber. Materialkomponente: V, S, M (ein Stück Katzenfell und ein ca. 7,5 cm großes Stück Teppich).',
  description_en = 'Protects a magical item or enchanted creature from tampering by other spellcasters. Remains dormant until someone casts Dispel Magic on the object. The backfire causes the dispel to fail automatically AND the dispelling caster loses one memorized spell of equal level to the effect being dispelled (or next lower if none available). Not effective against a caster of higher level — who then dispels both the ward and the protected spell. Material component: V, S, M (a bit of cat fur and a roughly 7.5 cm piece of carpeting).'
WHERE LOWER(name_en) = LOWER('Andrui''s Baneful Backfire') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Macht das Ziel bewusstlos und empfindungslos. Nur lebende Kreaturen betroffen (Untote, Golems etc. immun). Während der Wirkung: +10% auf Systemschock-Würfe, nur halber Schaden durch physische Effekte, Vorteile eines Langsames-Gift-Zaubers. Der Empfänger ist aber völlig hilflos. Willige Empfänger: bei erfolgreichem RW gegen Zauber halbiert sich die Dauer. Unwillige: bei Erfolg endet der Zauber. Nach Ablauf: −2 auf Angriffe, Rettungswürfe und Fertigkeitswürfe (willig: 1 Runde/Stufe; unwillig: 1W8 Runden). Materialkomponente: V, S, M (eine Lotusblüte).',
  description_en = 'Renders the subject unconscious and insensate. Only living creatures affected (undead, golems, etc. immune). While in effect: +10% on system shock rolls, half damage from physical effects, benefits of a Slow Poison spell. The recipient is completely helpless. Willing: on successful save vs. spell, duration halved. Unwilling: on success, spell ends. After expiry: −2 on attacks, saves, and proficiency rolls (willing: 1 round/level; unwilling: 1d8 rounds). Material component: V, S, M (a lotus flower).'
WHERE LOWER(name_en) = LOWER('Anesthesia') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Kehrt die Evolutionsuhr eines Menschen/Halbmenschen/Humanoiden zurück — Kampffähigkeit steigt auf Kosten des Geistes. +1W6 auf STR, GES, KON (max. 19), −3W6 auf INT, WIS, CHA (min. 1). Nägel und Zähne werden zu Waffen. Körperveränderungen (längere Arme, gebückte Haltung, mehr Körperbehaarung). Bei INT unter 5: Waffen werden zugunsten von Klaue/Klaue/Biss aufgegeben (1W2/1W2/1W4). Unwillige: Rettungswurf gegen Zauber. Am Ende: Systemschock-Wurf oder der devolvierte Zustand bleibt (umkehrbar durch Begrenzten Wunsch). Funktioniert NICHT bei Elfen. Halbelfen: nur +1W3 STR/GES/KON und −2W6 WIS/INT/CHA. Materialkomponente: V, S, M (Zahn eines Gorillas oder fleischfressenden Affen).',
  description_en = 'Reverses the evolutionary clock of a human/demihuman/humanoid — fighting ability increases at the cost of mind. +1d6 to STR, DEX, CON (max 19), −3d6 to INT, WIS, CHA (min 1). Nails and teeth become weapons. Body changes (longer arms, hunched posture, more body hair). At INT below 5: weapons are shunned for claw/claw/bite (1d2/1d2/1d4). Unwilling: save vs. spell. At the end: system shock check or the devolved state remains (reversible with Limited Wish). Does NOT work on elves. Half-elves: only +1d3 STR/DEX/CON and −2d6 WIS/INT/CHA. Material component: V, S, M (a gorilla or carnivorous ape tooth).'
WHERE LOWER(name_en) = LOWER('Articus''s Devolutionary Warrior') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Lässt alle Kreaturen im 6-m-Radius in blauen Flammen aufgehen. Rettungswurf gegen Zauber negiert. Die Flamme brennt bis sie durch Magie Bannen gelöscht wird — nichts anderes wirkt — und springt auf jedes berührte Lebewesen über. Nichtlebende Objekte (einschließlich Untote und Konstrukte) brennen nicht. Brennende Kreaturen erleiden 1W4 Schaden pro Runde. Fluch Aufheben oder jeder Priester-Zauber über der 3. Stufe, der magisches Feuer löscht, wirkt ebenfalls. Kreaturen, die auf −10 TP sinken, zerfallen zu blauer Asche und können NICHT auferweckt werden. Permanent. Nur von Paramandaren wirkbar (in direktem Dienst ihrer Gottheit). Wirken ohne göttliche Billigung befällt den Wirker selbst. Mehr als einmal pro Monat zu wirken ist äußerst gefährlich. Materialkomponente: V, S, M (ein kleines Stück Azurit; erfordert GES 13+).',
  description_en = 'Causes all creatures in a 6 m radius to burst into blue flame. Save vs. spell negates. The flame burns until extinguished by Dispel Magic — nothing else works — and spreads to any living thing touched. Lifeless items (including undead and constructs) don''t burn. Burning creatures take 1d4 damage per round. Remove Curse or any priest spell above 3rd level that extinguishes magical fire also works. Creatures reduced to −10 HP crumble to blue ash and CANNOT be resurrected. Permanent. Only castable by paramanders (in direct deity service). Casting without divine approval afflicts the caster. Casting more than once per month is extremely dangerous. Material component: V, S, M (a small piece of azurite; requires DEX 13+).'
WHERE LOWER(name_en) = LOWER('Azure Flame — Paramander') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erhöht die strukturelle Festigkeit eines einzelnen Steinbauwerks (beliebige Größe) um 10% pro Stufe des Zauberkundigen. Bei Stufe 10: +100% (Verdopplung). Der Stein wird zäher und rissbeständiger. Schaden am Bauwerk reduziert zuerst die magische Verstärkung. Wirkt nur auf Stein — nicht auf Erd- oder Holzverteidigungen. Bei Mischkonstruktionen: proportionale Wirksamkeit (40% Stein = 40% Wirkung). Repariert steinbasierte Kreaturen (Steingolem, Xorn, Galeb Duhr) vollständig für die Zauberdauer. Auf versteinerte Individuen: virtuelle Immunität gegen zufälliges Absplittern. Verstärkt auch steinerzeugende Magie (Steinwand). Materialkomponente: V, S, M (ein kleiner Granitkeil und eine Prise Eisenpulver).',
  description_en = 'Increases the structural strength of any single stone structure (any size) by 10% per caster level. At level 10: +100% (doubling). The stone becomes tougher and more resistant to cracking. Damage to the structure reduces the magical strengthening first. Only affects stone — not earth or wood defenses. For mixed constructions: proportional effectiveness (40% stone = 40% effective). Completely repairs stone-based creatures (stone golem, xorn, galeb duhr) for the duration. On petrified individuals: virtual immunity to incidental chipping. Also enhances stone-creating magic (Wall of Stone). Material component: V, S, M (a small granite wedge and a pinch of powdered iron).'
WHERE LOWER(name_en) = LOWER('Ballant''s Stonestrength') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht einem Verzauberer, einen Zauber mit Reichweite 0 und Wirkungsbereich „Der Zauberkundige" auf ein anderes Wesen zu übertragen. Zuerst Verzauberung Übertragen wirken, dann den zu übertragenden Zauber — der Empfänger kann den Zauber manipulieren, als hätte er ihn selbst gewirkt. Die Dauer von Verzauberung Übertragen endet, wenn der übertragene Zauber endet. Komponente: V.',
  description_en = 'Allows an enchanter to cast on another being a spell normally restricted to range 0, area "The caster." First cast Bestow Enchantment, then the spell to bestow — the recipient can manipulate the bestowed spell as if they had cast it themselves. The duration of Bestow Enchantment ends when the bestowed spell ends. Component: V.'
WHERE LOWER(name_en) = LOWER('Bestow Enchantment') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt eine Hand pro 3 Stufen, jede mit einem Langschwert bewaffnet. Jede Hand kämpft mit der Geschicklichkeit eines Kämpfers halber Stufe des Zauberkundigen. RK 2, 15 TP pro Hand. Kann Gegner entwaffnen (bei einem Wurf 4 über dem Trefferwurf). Wird eine Hand selbst entwaffnet, verschwindet sie automatisch. Keine Konzentration nötig — der Zauberkundige gibt ihnen Befehle wie Gefolgsleuten. Materialkomponente: V, S, M (ein kleines silbernes Amulett in Form eines gepanzerten Handschuhs mit einem edelsteinbesetzten Schwert, Mindestwert 1.000 GM; verschwindet beim Wirken).',
  description_en = 'Creates one hand per 3 levels, each holding a long sword. Each hand fights with the skill of a fighter at half the caster''s level. AC 2, 15 HP per hand. Can disarm opponents (on a roll 4 above the needed hit roll). A hand disarmed of its sword is automatically dispelled. No concentration needed — the caster gives orders as to henchmen. Material component: V, S, M (a small silver amulet shaped like a mailed gauntlet holding a gem-encrusted sword, worth at least 1,000 gp; vanishes when cast).'
WHERE LOWER(name_en) = LOWER('Bigby''s Fantastic Fencers') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt ein Paar körperloser Hände, die den Hals einer Kreatur suchen und sie wie mit einer Garrotte erwürgen. Angriffswurf mit +4 auf den ETW0 des Zauberkundigen nötig. Erster Treffer: 1W4 Schaden. Am Ende der nächsten Runde: Erwürgungstod, sofern die Kreatur sich nicht mit einem Stangen-biegen-Wurf befreit. Konzentrationsverlust des Magiers löst den Griff. Hat keinen Effekt auf Kreaturen, die der Zauberkundige nicht physisch erwürgen könnte (Schleimwesen, Kühe, Kreaturen über Größe L). Halsschutz (gehärtetes Lederhalsband, Metallkehlschutz) verhindert den Angriff. Kann mit einer bereiten Waffe pariert werden. Materialkomponente: V, S, M (ein Paar Handschuhe, zu einem Würgegriff um einen Flaschenhals genäht).',
  description_en = 'Creates a pair of disembodied hands that seek a creature''s throat and strangle it like a garrote. Attack roll at +4 to the caster''s THAC0 needed. First hit: 1d4 damage. By the end of the next round: strangulation death unless the creature breaks free with a bend bars roll. Loss of the wizard''s concentration releases the grip. Has no effect on creatures the caster couldn''t physically strangle (oozes, cows, creatures above size L). Throat protection (hardened leather collar, metal gorget) frustrates the attack. Can be parried with a ready weapon. Material component: V, S, M (a pair of gloves sewn into a clutching grip around a bottle neck).'
WHERE LOWER(name_en) = LOWER('Bigby''s Strangling Grip') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Fortgeschrittene Version des Kraftskulptur-Zaubers der 4. Stufe. Die geformten Objekte können komplexer sein, aus großen beweglichen Teilen bestehen oder eine Schneide/Spitze haben, müssen aber ziemlich starr bleiben. Wagen, Köcher mit Bolzen, Schaufel, Schwert oder Wasserrad ja — aber kein Uhrwerk, keine Armbrust, keine Feder. Feine Details können eingearbeitet werden (erfordern 2W4 Runden). Bis zu 0,23 m³ pro Stufe können simuliert werden. Längere Dauer als Kraftskulptur (3 Runden + 1 Runde/Stufe). Sonst identisch mit dem 4.-Stufe-Zauber. Materialkomponente: V, S, M (ein Klumpen Ton mit Diamantstaub).',
  description_en = 'Advanced version of the 4th-level Force Sculpture spell. Formed objects can be more complex, with large moving parts or edges/points, but must be fairly rigid. Wagon, quiver of quarrels, shovel, sword, or water wheel yes — but not a timepiece, crossbow, or spring. Fine details can be worked in (require 2d4 rounds). Up to 0.23 m³ per level can be simulated. Longer duration than Force Sculpture (3 turns + 1 turn/level). Otherwise identical to the 4th-level spell. Material component: V, S, M (a lump of clay with diamond dust).'
WHERE LOWER(name_en) = LOWER('Bigby''s Superior Force Sculpture') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Hochwirksam gegen bestimmte Untote (keine Wirkung auf Lebende). Betrifft automatisch (ohne RW) alle gewählten körperlichen Untoten mit 6* TW oder weniger (Skelette, Zombies, Ghule, Ghasts, Mumien, Totengräber etc.) — sie rollen sich zu einer Kugel zusammen (bei mehreren: eng zusammengepackte Kugel von 0,6–0,9 m pro Untotem). Gehaltene Untote sind hilflos und immobil, Spezialfähigkeiten in Stasis. Wird oft genutzt um die „Knochenkugel" in die Mitte von Feinden zu befördern und dort die Magie zu lösen. Gegen nichtkörperliche Untote (Geister, Gespenster) und Untote ab 7 TW (keine „Special"-Untoten): wirkt nur als Langsam-Zauber (Rettungswurf gegen Zauber negiert). Materialkomponente: V, S, M (ein Knochen beliebiger Kreatur in der linken Hand).',
  description_en = 'Highly effective against certain undead (no effect on living). Automatically affects (no save) all chosen corporeal undead of 6* HD or less (skeletons, zombies, ghouls, ghasts, mummies, wights, etc.) — they curl into a ball (multiple: tightly packed sphere of 0.6–0.9 m per undead). Held undead are helpless and immobile, special abilities in stasis. Often used to convey the "boneball" into the midst of foes, then release them. Against noncorporeal undead (ghosts, spectres) and undead of 7+ HD (not "Special"): acts only as a Slow spell (save vs. spell negates). Material component: V, S, M (the bone of any creature, held in the left hand).'
WHERE LOWER(name_en) = LOWER('Bind Undead') AND spell_type = 'wizard';
