-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 4 (Batch 4: 18 Spells — Death's Door to Duplicate)
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  description = 'Wie der gleichnamige Priester-Zauber der 3. Stufe, wirkt bei Berührung auf eine Kreatur „an der Schwelle des Todes" (−1 bis −9 TP). Die Nekromanten-Version funktioniert auf jede lebende oder untote Kreatur. Bringt die berührte Kreatur auf 0 TP und stoppt Blutungen und Verschlechterung für die Zauberdauer. Anders als die Priester-Version: Der Nekromant muss einen Systemschock-Wurf bestehen oder so viele TP verlieren wie nötig, um die Kreatur auf 0 zu bringen. Würde ihn das unter 1 TP senken, wird er auf 1 TP reduziert und für 1 Runde pro fehlendem TP bewusstlos. Kann mit einem Befehl beendet werden. Materialkomponente: V, S, M (ein klarer Edelstein/Kristall, Tropfen Wasser, Blut, Milch und eine Salbe).',
  description_en = 'Like the 3rd-level priest spell, works by touch on a creature "at death''s door" (−1 to −9 HP). The necromancer''s version works on any living or undead creature. Brings the touched creature to 0 HP and stops bleeding and deterioration for the duration. Unlike the priest version: the necromancer must make a system shock check or lose as many HP as needed to bring the creature to 0. If this would reduce the necromancer below 1 HP, he''s reduced to 1 HP and rendered unconscious for 1 turn per missing HP. Can be ended with a command. Material component: V, S, M (a clear gem/crystal, drops of water, blood, milk, and unguent).'
WHERE LOWER(name_en) = LOWER('Death''s Door') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Visuell fast identisch mit Magisches Geschoss der 1. Stufe, aber mit wichtigen Unterschieden: mehr Schaden über längere Zeit; zweiter und folgende Angriffe treffen NICHT automatisch; ein Schild-Zauber blockiert NICHT. Bei Wirkung: Energiepfeile sammeln sich zu einem Geschoss und treffen das Ziel (muss bei Wirkung zumindest teilweise sichtbar sein). Verursacht 1W6 Schaden pro 3 Stufen des Zauberkundigen (z.B. 4W6 bei Stufe 12). Erster Aufprall: 1W6 Schaden, dann jede Runde weitere 1W6. Ab der zweiten Runde: Rettungswurf gegen Zauber mit −2 pro Runde (Erfolg = kein Schaden diese Runde, Magie bleibt aber bis Ablauf bestehen). Verhindert die Konzentration eines Zauberkundigen auf Zauber. Komponenten: V, S.',
  description_en = 'Visually near-identical to 1st-level Magic Missile but with key differences: more damage staggered over time; second and subsequent attacks do NOT auto-hit; a Shield spell does NOT block. On casting: energy darts collect into one missile and hit the target (must be at least partially visible). Deals 1d6 damage per 3 caster levels (e.g., 4d6 at level 12). Initial impact: 1d6 damage, then 1d6 more each round. From round 2: save vs. spell at −2 each round (success = no damage that round, but magic persists until duration expires). Prevents targeted spellcaster from concentrating. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Delayed Magic Missile') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = '2W4 intelligente Kreaturen (INT 3+) im 6-m-Würfel müssen einen Rettungswurf gegen Zauber bestehen oder verfallen in eine verzweifelte Depression. Sie erkennen die Hoffnungslosigkeit und Torheit ihrer Überzeugungen und sind unfähig zu Angriff, Zaubern, Bewegung oder grundlegenden Aktivitäten wie Essen/Trinken. Verzweifelte Kreaturen verteidigen sich nicht — Gegner können automatisch treffen, entwaffnen oder fesseln. Wenn eine Kreatur Schaden erleidet oder gefesselt wird, erhält sie einen neuen Rettungswurf. Komponenten: V, S.',
  description_en = '2d4 sentient creatures (INT 3+) in a 6 m cube must save vs. spell or lapse into despondent depression. They realize the hopelessness and folly of their beliefs and are unable to attack, cast spells, move, or even eat/drink. Despairing creatures don''t defend themselves — opponents can automatically strike, disarm, or bind them. When damaged or bound, the creature gets another save. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Despair') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Mächtige Variante von Untote Halten. Desintegriert körperliche Untote mit TW gleich oder weniger als der Stufe des Zauberkundigen. Untote mit 3 TW oder weniger: automatisch zerstört. 3+1 bis 7 TW: Rettungswurf gegen Zauber oder Zerstörung (bei erfolgreichem RW: 2W10 Schaden). Über 7 TW: nicht direkt zerstört, aber 5W10 Schaden (bei erfolgreichem RW: 1W10 Schaden). Nichtkörperliche Untote (Schemen, Gespenster, Geister) werden NICHT betroffen. Betrifft 1W3 Untote in einem 6-m-Würfel. Erfordert ein heiliges Symbol, das einmal von einem Priester der 8. Stufe oder höher benutzt wurde.',
  description_en = 'Powerful variation of Hold Undead. Disintegrates corporeal undead with HD equal to or less than the caster''s level. 3 HD or less: automatically destroyed. 3+1 to 7 HD: save vs. spell or destruction (on success: 2d10 damage). Over 7 HD: not destroyed outright but suffer 5d10 damage (on success: 1d10 damage). Noncorporeal undead (wraiths, spectres, ghosts) are NOT affected. Affects 1d3 undead in a 6 m cube. Requires a holy symbol once used by a priest of 8th level or higher.'
WHERE LOWER(name_en) = LOWER('Destroy Undead') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ein Opfer dieses schrecklichen Fluches muss einen Rettungswurf gegen Zauber bestehen oder wird grauenhaft verwandelt — bedeckt mit Narben, Beulen, Warzen und anderen Deformitäten. CHA wird sofort auf 1 reduziert. Jeder Betrachter muss einen RW gegen Zauber bestehen oder kann die Anwesenheit des Opfers nicht ertragen. Feindlich gesinnte Kreaturen greifen möglicherweise an; freundliche verlassen angewidert den Raum; neutrale: 50% Chance für beides. Wird als Bestrafung, zur Sicherung der Loyalität von Gefolgsleuten oder zur Bestrafung von Rivalen eingesetzt. Nur durch Fluch Aufheben, Begrenzten Wunsch oder Wunsch zu beheben (Magie Bannen unwirksam). Komponenten: V, S.',
  description_en = 'The victim of this terrible curse must save vs. spell or be horribly transformed — covered in scars, boils, welts, warts, and other deformities. CHA is instantly reduced to 1. Every viewer must save vs. spell or be unable to bear the victim''s presence. Hostile creatures may attack; friendly ones might leave in disgust; neutral creatures: 50% chance of either. Used as punishment, to ensure loyalty, or to punish rivals. Only removable by Remove Curse, Limited Wish, or Wish (Dispel Magic ineffective). Components: V, S.'
WHERE LOWER(name_en) = LOWER('Disfigure — Red Wizards') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht dem Empfänger, das Aussehen jeder Person oder Kreatur ähnlicher Größe (±25%) anzunehmen — einschließlich einer bestimmten Person. Die Illusion ändert Kleidung und Stimme (wenn der Zauberkundige die nachzuahmende Stimme gehört hat). Verleiht keine Sprachfähigkeit, Fertigkeiten der angenommenen Identität oder Klassenfähigkeiten. Unter normalen Umständen als Illusion nicht erkennbar. Illusion Entdecken, Wahres Sehen oder Magie Entdecken durchdringen sie. Die Illusion hält bis gebannt oder bis der Verkleidete getötet wird. Unwillige Empfänger: Rettungswurf gegen Zauber. Materialkomponente: V, S, M (eine miniaturisierte Holzmaske).',
  description_en = 'Allows the recipient to assume the appearance of any person or creature of similar size (±25%) — including a specific individual. The illusion changes garments and voice (if the caster has heard the mimicked voice). Grants no language ability, skills of the assumed identity, or class abilities. Cannot be recognized as an illusion under normal circumstances. Detect Illusion, True Seeing, or Detect Magic penetrate it. The illusion lasts until dispelled or the disguised individual is slain. Unwilling recipients: save vs. spell. Material component: V, S, M (a miniature wooden mask).'
WHERE LOWER(name_en) = LOWER('Disguise') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ein Illusionist oder Wu Jen kann sofort jede Illusion oder Phantasie bannen, die von einem Magier einer anderen Schule gewirkt wurde. Gegen Zauber gemischter Schulen, eigener Schulen und Nicht-Magier-Illusionen wirkt der Zauber wie Magie Bannen (11 oder höher auf 1W20, +1 pro Stufenunterschied). Auf Ermessen des SL kann der Zauber auch Gegenstände betreffen, die Illusions- und Phantasie-Effekte erzeugen. Komponenten: V, S.',
  description_en = 'An illusionist or wu jen can instantly dispel any illusion or phantasm cast by a wizard of another school. Against spells of mixed schools, own schools, and non-wizard illusions, this spell acts as Dispel Magic (11+ on 1d20, +1 per level difference). At the DM''s option, may also affect items creating illusion and phantasmal effects. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Dispel Illusion') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt einen Kegel unsichtbarer, stiller, leicht kalter Kraft (3 m Durchmesser, 6,1 m lang) aus der ausgestreckten Hand des Zauberkundigen. Untote darin werden wie folgt betroffen: Skelette, Zombies, Ghule, Schatten und ähnliche mit weniger als 4 TW: sofort aus der Existenz gelöscht. Totengräber, Ghasts, Schemen, Mumien, Gespenster, Vampire, Geister, Liches und ähnliche mächtige Untote: Rettungswurf gegen Todesmagie oder Zerstörung; bei Erfolg sofort 1W6 Schaden pro Stufe (max. 10W6). Materialkomponente: V, S, M (eine Prise Staub oder ein Faden Spinnwebe).',
  description_en = 'Creates a cone of invisible, silent, mildly cold force (3 m diameter, 6.1 m long) from the caster''s outstretched hand. Undead within are affected: Skeletons, zombies, ghouls, shadows, and similar with less than 4 HD: instantly blasted out of existence. Wights, ghasts, wraiths, mummies, spectres, vampires, ghosts, liches, and similar powerful undead: save vs. death magic or destruction; on success, instantly 1d6 damage per caster level (max 10d6). Material component: V, S, M (a pinch of dust or a strand of cobweb).'
WHERE LOWER(name_en) = LOWER('Disrupt Undead') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Mächtigere Version des Tagebuch-Zaubers. Hauptunterschiede: Das Tagebuch zeichnet unabhängig von der Entfernung des Zauberkundigen auf (solange auf derselben Ebene). Wenn der Zauber vor Ablauf erneuert wird, geht das Tagebuch ohne Pause weiter. Wenn der Zauberkundige mehrere Bände vorbereitet, füllt der Zauber automatisch den nächsten Band. So könnte ein Magier Tagebücher im Turm hinterlassen und ständig diktieren, solange er den Zauber rechtzeitig erneuert. Zeichnet alles Gesprochene und Gehörte auf, mentale Notizen und Szenen durch Konzentration (1 Runde für Skizze). Typisch: 10-20 Seiten pro Stunde. Kann keine magischen Texteigenschaften kopieren. Materialkomponente: V, S, M (ein Buch).',
  description_en = 'More powerful version of the Diary spell. Key differences: The diary records regardless of the caster''s distance (same plane required). If the spell is recast before it lapses, the diary continues without pause. If the wizard prepares multiple volumes, the spell automatically fills the next one. A wizard could leave journals in his tower and dictate constantly as long as each spell is recast in time. Records all things said/heard, mental notes and scenes via concentration (1 round for a sketch). Typically 10-20 pages per hour. Cannot copy magical text properties. Material component: V, S, M (a book).'
WHERE LOWER(name_en) = LOWER('Distant Diary') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verändert ein Merkmal einer ungeborenen Kreatur nach Willen des Zauberkundigen. Nur äußere Merkmale. Der Erfolg hängt vom gewünschten Merkmal ab und kann mehrere Generationen erfordern. Typische Erfolgschancen: Färbung (Grundfarbe, Streifen, Flecken): 80%. Bedeckung (Haut→Fell→Schuppen→Federn): 40%. Abhärtung (+1 RK pro 2 Generationen): 20% + aktuelle RK × 5%. Gliedmaßen-Enden (Klauen, Stachelschwanz, Finger): 40%. Ganze Gliedmaßen (Flügel, Greifschwanz, Tempo +1): 30%. Sinne (schärferes Hören, Sehen etc., Infrasicht +9,1 m/Generation): 50%. Maul (Zahngröße, Hohlzähne): 40%. Stimme (Tonhöhe, Lautstärke): 70%. Bei Misserfolg: unbeabsichtigte Veränderung, Defekte oder kein Effekt. Materialkomponente: V, S, M.',
  description_en = 'Alters one aspect of an unborn creature as the wizard wills. Only external features. Success depends on the desired trait and may require multiple generations. Typical chances: Coloring (base, stripes, spots): 80%. Covering (hide→fur→scales→feathers): 40%. Toughening (+1 AC per 2 generations): 20% + current AC × 5%. Limb endings (claws, spiked tail, digits): 40%. Whole limbs (wings, prehensile tail, speed +1): 30%. Senses (sharper hearing, vision, etc., infravision +9.1 m/gen): 50%. Mouth (tooth size, hollow fangs): 40%. Voice (pitch, volume): 70%. On failure: unintended change, defects, or no effect. Material component: V, S, M.'
WHERE LOWER(name_en) = LOWER('Distort Life I') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Verlängert sowohl die Dauer als auch die Reichweite des Magierauge-Zaubers und aller Erkennungszauber der 1.–4. Stufe um 50% für die Dauer der Verbesserung (2 Runden + 2 Runden/Stufe). Alle innerhalb der Verbesserungsdauer gewirkten Erkennungszauber werden verstärkt. Ablauf der Verbesserung beendet alle aktiven Erkennungszauber. Komponenten: V, S.',
  description_en = 'Extends both the duration and range of the Wizard Eye spell and any divination spells of 1st–4th level by 50% for the enhancement duration (2 turns + 2 rounds/level). All divination spells cast within the enhancement are increased. Expiration of the enhancement ends all active divination spells. Components: V, S.'
WHERE LOWER(name_en) = LOWER('Divination Enhancement') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Nach dem Wirken wird der nächste Zauber des gleichen Magiers zeitlich überwacht. Ein kleiner goldener Gong erscheint und schlägt eine Minute (1 Runde) vor Ablauf des Zaubers leise Alarm. Funktioniert nur bei Zaubern mit einer Dauer unter 48 Stunden. Materialkomponente: V, S, M (eine Feder eines Zugvogels, eine Fruchtfliege, einige Sandkörner, ein massives Silberpendel im Wert von 100 GM und eine goldene Kugel im Wert von 5.000 GM; alle außer der goldenen Kugel verschwinden mit dem Zauber).',
  description_en = 'After casting, the next spell cast by the same wizard is timed. A small golden gong appears and softly chimes a warning one minute (1 round) before the spell ends. Only works with spells with a duration less than 48 hours. Material component: V, S, M (a migratory bird feather, a fruit fly, a few grains of sand, a 100 gp solid silver pendulum, and a 5,000 gp solid gold orb; all but the gold orb vanish with the spell).'
WHERE LOWER(name_en) = LOWER('Drawmij''s Handy Timepiece') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht eine begrenzte und riskante Form der Teleportation. Bei Wirkung erscheint eine Tür auf einer Wand oder Fläche innerhalb von 2,7 m. Der Zauberkundige und bis zu 10 Personen (in 1 Runde durchgehend) betreten durch die Tür eine Null-Raum-Zone. Schließt der Magier die Tür, werden alle in der Zone an einen ZUFÄLLIGEN Ort innerhalb von 228,6 m der Tür teleportiert. Wird die Tür nicht rechtzeitig geschlossen, knallt sie am Rundenende zu. Die Gruppe hat KEINE Kontrolle über den Zielort. 5% Chance auf Fehlfunktion — die Gruppe landet auf der Ätherebene. Materialkomponente: V, S, M (eine silberne Miniaturtür mit Rubinsplittern im Wert von 500 GM; verschwindet nach dem Wirken).',
  description_en = 'Enables a limited and risky form of teleportation. On casting, a door appears on a wall or flat surface within 2.7 m. The caster and up to 10 persons (passing through in 1 round) enter a nil-space zone. If the wizard closes the door, everyone is teleported to a RANDOM location within 228.6 m. If not closed in time, the door slams shut at round''s end. The party has NO control over the destination. 5% chance of malfunction — the party is dumped into the Ethereal Plane. Material component: V, S, M (a miniature silver door with ruby chips worth 500 gp; vanishes after casting).'
WHERE LOWER(name_en) = LOWER('Drawmij''s Instant Exit') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Ermöglicht dem Zauberkundigen, vorübergehend 1-10 Werkzeuge bei Bedarf zu beschwören (bis 9,1 kg Gesamtgewicht). Der Zauberkundige kann während der Dauer ständig Werkzeuge austauschen — Hammer und Meißel nehmen, gegen Säge tauschen, dann gegen Brecheisen etc. Nur nichtlebende Materie. Werkzeuge dürfen nicht weiter als 91,4 m von der Kiste entfernt werden. Die Kiste ist unbeweglich und nur der Zauberkundige kann Werkzeuge entnehmen. Nur Zimmermanns-/Bau-Werkzeuge (Seil, Skelettschlüssel, große Hämmer, Planen, Netze, Sand) — keine Diebeswerkzeuge, Wachsschlüsselrohlinge, magische Waffen etc. Materialkomponente: V, S, M (eine miniaturisierte Holzwerkzeugkiste).',
  description_en = 'Allows the wizard to temporarily acquire 1-10 tools when needed (up to 9.1 kg total). The caster can exchange items throughout the duration — take hammer and chisel, swap for saw, trade for pry bar, etc. Only nonliving matter. Tools cannot go beyond 91.4 m from the box. The box is immovable; only the caster can take tools. Only carpenter/builder tools (rope, skeleton key, large hammers, canvas sheets, nets, sand) — no thief tools, wax key blanks, magical weapons, etc. Material component: V, S, M (a miniature wooden tool box).'
WHERE LOWER(name_en) = LOWER('Drawmij''s Tool Box') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt einen magischen Arm aus vorhandenem Material (Wand, Boden — Holz, Erde oder Stein). Der Arm kann menschengroß bis gigantisch sein (max. 0,9 m + Stufe in Metern). Einmal geformt, ist er an seinem Entstehungspunkt verankert. Primärer Zweck: Greifen und Festhalten (ETW0 des Magiers +2, STR 19 Haltekraft). Kann Wände und Türen einschlagen (wie Rammbock, 2W6 Schaden gegen Gegner). Berührungszauber des kontrollierenden Magiers können durch den Arm übertragen werden (wie Spektralhand). Der Magier kann während der Kontrolle keine anderen Aktionen ausführen. Holzarm: RK 4, Steinarm: RK 0; TP gleich der des Magiers. Kollabiert bei 0 TP. Materialkomponente: V, S, M.',
  description_en = 'Creates a magical arm from materials present (wall, ground — wood, packed dirt, or stone). The arm can be man-sized to gargantuan (max 0.9 m + level in meters). Once formed, rooted to its creation point. Primary purpose: grabbing and holding (caster''s THAC0 +2, STR 19 grip). Can punch down walls and doors (like a battering ram, 2d6 damage to opponents). Touch-delivered spells from the controlling wizard can be projected through the arm (like Spectral Hand). The wizard cannot perform other actions while controlling. Wooden arm: AC 4, stone arm: AC 0; HP equal to the wizard''s. Collapses at 0 HP. Material component: V, S, M.'
WHERE LOWER(name_en) = LOWER('Duhlark''s Long Reach') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt eine magische Sanddüne, die pro 2 Stufen eine menschengroße Kreatur tragen kann (z.B. 3 bei Stufe 7, 5 bei Stufe 10). Bewegt sich nur durch sandige Gebiete mit Rate 4 pro Stufe (max. Rate 48). Materialkomponente: V, S, M (eine Handvoll Sand).',
  description_en = 'Creates a magical sand dune that can carry one man-sized creature per 2 caster levels (e.g., 3 at level 7, 5 at level 10). Moves only through sandy areas at rate 4 per level (max rate 48). Material component: V, S, M (a handful of sand).'
WHERE LOWER(name_en) = LOWER('Dune — Old Empire') AND spell_type = 'wizard';

UPDATE public.spells SET
  description = 'Erzeugt eine exakte Kopie eines einzelnen berührten Gegenstands (passt in einen 6,1-m-Würfel). Wirkt nicht auf Lebewesen, Untote oder magische Gegenstände. Das Duplikat ist in jeder Hinsicht identisch (z.B. ein dupliziertes Schwert kann als normales Schwert Schaden verursachen). Magie Entdecken enthüllt die wahre Natur, Magie Bannen lässt es verschwinden. Existiert für 1 Stunde pro Stufe, dann verschwindet es. Permanenz wirkt nicht auf Duplikate. Materialkomponente: S, M (eine Prise Kohlenstaub).',
  description_en = 'Creates an exact copy of any single touched item (fits in a 6.1 m cube). Does not work on living creatures, undead, or magical items. The duplicate is identical in every way (e.g., a duplicated sword can deal damage as a normal sword). Detect Magic reveals its true nature, Dispel Magic causes it to disappear. Exists for 1 hour per level, then vanishes. Permanency does not affect duplicates. Material component: S, M (a pinch of coal dust).'
WHERE LOWER(name_en) = LOWER('Duplicate') AND spell_type = 'wizard';
