-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 7 (Batch 1: 13 Spells — Alter Reality to Create Shade)
-- Alle mechanischen Details, Materialkomponenten, Spezialfälle
-- Metrisch, eng an Originaltexten orientiert
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  name = 'Realität Verändern',
  description = 'Ein mächtiger, aber schwer einzusetzender Zauber, der eine vom Magier visualisierte Bedingung buchstäblich, aber nur teilweise oder für begrenzte Dauer erfüllt. Der Zauberkundige muss die gewünschte Realitätsänderung durch das Wirken eines Phantastische-Kraft-Zaubers darstellen und den gewünschten Zustand verbalisieren. Vergangenheit, Gegenwart oder Zukunft können begrenzt verändert werden. Der Zauber verändert keine großen Realitäten und bringt kein Vermögen oder Erfahrung durch bloßes Bitten. Kann z.B. verlorene TP wiederherstellen, gegnerische Trefferwürfe reduzieren, magische Effekte verlängern, Kreaturen wohlgesonnen machen oder Zauber der 7. Stufe oder niedriger nachahmen. Gierige Wünsche enden meist in einer Katastrophe. Kann fast immer anstelle eines Begrenzten Wunsches verwendet werden. Altert den Zauberkundigen um ein Jahr pro 100 Jahre normaler Lebensspanne.',
  description_en = 'A potent but difficult spell that literally but only partially or for limited duration fulfills a condition visualized by the caster. The wizard must depict the desired reality alteration through casting a Phantasmal Force spell and verbalizing the desired state. Past, present, or future can be altered in limited ways. The spell will not substantially change major realities nor bring wealth or experience by merely asking. Can restore lost HP, reduce opponent hit probabilities, increase magical effect duration, make creatures favorably disposed, or mimic spells of 7th level or less. Greedy desires usually end in disaster. Can nearly always substitute for a Limited Wish. Ages the caster one year per 100 years of normal lifespan.'
WHERE LOWER(name_en) = LOWER('Alter Reality') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Alustriels Verbesserter Mantel',
  description = 'Umhüllt den Zauberkundigen oder ein berührtes williges Wesen mit einem eng anliegenden magischen Schutzfeld. Der Mantel ist normalerweise unsichtbar, kann aber auf Wunsch des Trägers schimmern, schwach leuchten (in beliebiger Farbe) oder hell strahlen (ausreichend zum Lesen oder um 3 m in Dunkelheit zu sehen). Wehrt alle physischen Waffen mit +1 Verzauberung oder weniger ab. Verhindert die Wirkung aller Zauber oder magischen Gegenstandseffekte der 4. Stufe oder niedriger innerhalb des Feldes. Der Träger steht z.B. im Zentrum eines Feuerballs völlig unversehrt. Zusätzlich +2 auf alle Rettungswürfe. Warnung: Direkter Kontakt zweier Mäntel (verbessert oder normal) verursacht 4W10 Schaden, 1W2 Runden Hilflosigkeit und beide Mäntel kollabieren. Materialkomponente: Ein Edelstein (Wert mind. 50 GM) und ein mindestens 24 Stunden vorher versiegeltes Glasfläschchen, in das der Zauberkundige geatmet hat.',
  description_en = 'Envelops the caster or a willing touched recipient in a close-fitting magical defensive field. The mantle is normally invisible but can shimmer, glow faintly (any hue), or shine brightly (enough to read by or see 3 m in darkness) at the wearer''s will. Wards off all physical weapons of +1 enchantment or less. Prevents all spells or magical item effects of 4th level or less from functioning within its confines. The wearer could stand in a fireball''s heart completely unharmed. Also grants +2 bonus on all saving throws. Warning: Direct contact between two mantles (improved or standard) causes 4d10 damage, 1d2 rounds of helplessness, and both mantles collapse. Material component: A gem worth at least 50 gp and a tiny glass vial the caster has breathed into and stoppered at least 24 hours before casting.'
WHERE LOWER(name_en) = LOWER('Alustriel''s Improved Mantle') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Alustriels Sternenschwert',
  description = 'Erschafft ein schimmerndes, durchscheinendes Konstrukt aus Kraft in Form eines Zweihandschwerts — bestehend aus blinkenden, pulsierenden Lichtern wie Sterne am Nachthimmel. Gilt als +2 magische Waffe (ohne Angriffs-/Schadensbonus). Das Schwert bildet sich in der Runde nach dem Wirken und greift lautlos ein gewähltes Ziel an: 2 Angriffe pro Runde mit ETW0 9 (unabhängig vom ETW0 des Zauberkundigen), je 4W4 Schaden. Es verfolgt das Ziel überall auf derselben Ebene (Fernteleportation beendet den Zauber). Flugrate 21 (BK: A), RK −2, 22 TP. Physische Angriffe können es zerstören; magische Angriffe haben keine Wirkung (außer Magie Bannen, Begrenzter Wunsch oder Wunsch). Kämpft selbstständig. Materialkomponente: Eine Waffe mit Metallklinge (wird beim Wirken verbraucht).',
  description_en = 'Creates a shimmering, translucent construct of force shaped like a two-handed sword — a cluster of winking, pulsing star-like lights. Counts as a +2 magical weapon (without attack/damage bonus). The sword forms the round after casting and silently attacks a chosen target: 2 attacks per round at THAC0 9 (regardless of caster''s THAC0), dealing 4d4 damage each. Pursues the target anywhere on the same plane (long-distance teleports end the spell). Flight rate 21 (MC: A), AC −2, 22 HP. Physical attacks can destroy it; magical attacks have no effect (except Dispel Magic, Limited Wish, or Wish). Fights independently. Material component: Any metal-bladed weapon (consumed in casting).'
WHERE LOWER(name_en) = LOWER('Alustriel''s Sword of Stars') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Amorpher Klumpen',
  description = 'Aktiviert eine gefährliche amöbenartige Lebensform in einer Glaskugel, die mit speziell vorbereiteter Flüssigkeit gefüllt ist. Die Flüssigkeit gerinnt zur Lebensform, die freigelassen wird, wenn das Glas zerbricht (Wurf als granatenartiges Geschoss möglich). Der Zauberkundige hat keine Kontrolle über die Kreatur nach der Freisetzung. Der Klumpen beginnt mit einem Volumen von ca. 0,11 Kubikmetern. Bei einem tödlichen Angriff verschlingt er seine Beute und gewinnt 1 TP pro TW des Opfers. Je 8 gewonnene TP = 1 zusätzlicher TW + 0,11 m³ Volumen + kumulativer +1 Schadensbonus (max. 12 Schaden/Runde). Benötigt 1 Runde zum Wachsen. Regeneriert 1 TP pro Runde. Kann durch enge Öffnungen fließen. Kein bekanntes Limit für maximales Volumen — kann ohne schnelle Bekämpfung extrem mächtig werden.',
  description_en = 'Activates a dangerous amoeboid lifeform inside a glass orb filled with specially prepared fluid. The fluid congeals into the lifeform, released when the glass shatters (can be hurled as a grenade-like missile). The caster has no control over the creature once released. The blob starts at about 0.11 cubic meters volume. On a killing attack, it engulfs prey and gains 1 HP per victim''s HD. Every 8 HP gained = 1 additional HD + 0.11 m³ volume + cumulative +1 damage bonus (max 12 damage/round). Needs 1 round to grow. Regenerates 1 HP per round. Can flow through narrow openings. No known limit to total volume — can become extremely powerful if not quickly destroyed.'
WHERE LOWER(name_en) = LOWER('Amorphous Blob') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Vorahnung',
  description = 'Erlaubt dem Zauberkundigen, korrekt zu wissen, welche Angriffe und Aktionen alle Wesen innerhalb von 18,3 m in der nächsten Runde planen. Für jeden Waffenangriff werden Waffentyp, ob die Waffe magisch ist (aber nicht welche Kraft), und das beabsichtigte Ziel offenbart. Bei Zaubern wird das Ziel oder der Wirkungsbereich enthüllt, aber nicht die Art des Zaubers. Bei Gegenstandsaktivierungen wird der genaue Gegenstand erkannt — was oft verborgene Gegenstände enthüllt. Untote und außerplanare Kreaturen können nicht gelesen werden. Der Zauber enthüllt die Anwesenheit (aber nicht den Ort) unsichtbarer oder verkleideter Wesen durch ihre geplanten Aktivitäten.',
  description_en = 'Allows the caster to correctly know what attacks and actions all beings within 18.3 m will attempt on the following round. For each weapon attack, the weapon type, whether it is magical (but not which power), and the intended target are revealed. For spells, the intended target or area of effect is revealed but not the spell type. For item activities, the precise item is learned — often revealing hidden items. Undead and extraplanar creatures cannot be read. The spell reveals the presence (but not location) of invisible or disguised beings by communicating their intended activities.'
WHERE LOWER(name_en) = LOWER('Anticipation') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Basiliskenblick',
  description = 'Lässt die Augen des Zauberkundigen in hellem Rubinrot erstrahlen. Jede Kreatur, die der Zauberkundige ansieht und auf die er seinen Willen richtet, kann für die Dauer des Zaubers plus 1W3 Runden in einen steinernen Zustand verwandelt werden (max. 1 Wesen pro Runde). Das Ziel muss teilweise sichtbar sein, muss aber nicht den Blick des Zauberkundigen erwidern. Rettungswurf gegen Versteinerung; bei Erfolg ist die Runde verschwendet. Bei Misserfolg: 1W4 physischer Schaden bei der Verwandlung, Systemschock-Wurf nötig — Misserfolg reduziert auf 2W4 TP und Bewusstlosigkeit. Versteinertes Wesen ist unbeweglich, blind, taub und kann nicht durch physische Angriffe zertrümmert werden (flackert unmerklich zwischen Stein und Fleisch). Während des Basiliskenblicks kann der Magier keine Zauber wirken oder andere Magie aktivieren, kann aber aktivierte Gegenstände halten oder eine magische Waffe führen.',
  description_en = 'Causes the caster''s eyes to glow with bright ruby-red radiance. Any creature the caster looks at and bends will upon can be transformed into a stony state for the spell''s duration plus 1d3 rounds (maximum 1 being per round). Target must be at least partially visible but need not meet the caster''s gaze. Saving throw vs. petrification; on success the round is wasted. On failure: 1d4 physical damage from transformation, system shock roll required — failure reduces to 2d4 HP and unconsciousness. Petrified being is immobile, blind, deaf, and cannot be shattered by physical attacks (flickers imperceptibly between stone and flesh). While using Basilisk Glare, the wizard cannot cast spells or activate other magic, but can hold activated items or wield a magical weapon.'
WHERE LOWER(name_en) = LOWER('Basilisk Glare') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Blutsterne',
  description = 'Erschafft sieben sternförmige, stachelige Kraftfelder aus sieben Tropfen des Bluts des Zauberkundigen. Die Blutsterne bewegen sich nach dem Willen des Magiers (Flug 21, BK: A) und können separate Ziele angreifen. Sie lösen sich auf, wenn sie sich weiter als 27,4 m vom Zauberkundigen entfernen. Der Magier ist auf halbe Bewegung und keine anderen Aktionen beschränkt. Ein Blutstern trifft mit ETW0 6 (angepasst für DEX und magischen Schutz), durchschneidet normale Rüstung und nicht-magische Barrieren und verursacht 1W4 Schaden. Nur ein Blutstern pro Runde kann dasselbe Wesen treffen. Sobald ein Blutstern Blut gezogen hat, kann der Magier ihn in einer folgenden Runde explodieren lassen: 2W6 Schaden für alle Kreaturen innerhalb von 3 m (Rettungswurf gegen Zauber für halben Schaden). Am Zauberende verschwinden alle nicht explodierten Blutsterne.',
  description_en = 'Creates seven star-shaped, spiked fields of whirling, sparkling force from seven drops of the caster''s blood. Bloodstars move at the caster''s will (Flight 21, MC: A) and can attack separate targets. They dissipate beyond 27.4 m from the caster. The caster is limited to half movement and no other actions. A bloodstar strikes at THAC0 6 (adjusted for DEX and magical protection), slashes through normal armor and non-magical barriers, dealing 1d4 damage. Only one bloodstar per round can strike the same creature. Once a bloodstar has drawn blood, the caster can make it explode on a subsequent round: 2d6 damage to all creatures within 3 m (save vs. spell for half). At spell''s end, all unexploded bloodstars wink out.'
WHERE LOWER(name_en) = LOWER('Bloodstars') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Körper Außerhalb des Körpers',
  description = 'Erlaubt dem Wu Jen, ein oder mehrere Duplikate seiner selbst zu erschaffen (1 Duplikat pro 5 Stufen). Die Duplikate haben die normalen Attributswerte und die Persönlichkeit des Wu Jen, tragen seine normale Ausrüstung, aber keine magischen Gegenstände und besitzen keine Zauberfähigkeiten. Ihre Trefferpunkte betragen ein Viertel der TP des Zauberkundigen. Sie gehorchen dem Zauberkundigen und sind kooperativ untereinander. Die Duplikate können alles tun, was der Wu Jen normalerweise kann, außer Zauber wirken. Wird ein Duplikat getötet, verschwindet es sofort und der Zauberkundige erleidet 10 Schadenspunkte. Am Ende der Wirkungsdauer (1 Runde pro 2 Stufen) verschwinden alle Duplikate schadlos. Die Duplikate sind selbst durch Wahres Sehen nicht vom Zauberkundigen zu unterscheiden. Materialkomponente: Einige Haare vom Kopf oder Bart des Wu Jen.',
  description_en = 'Allows the wu jen to create one or more duplicates of himself (1 duplicate per 5 levels). Duplicates have the wu jen''s normal ability scores and personality, carry normal equipment but no magical items, and possess no spell abilities. Their HP equal one-quarter of the caster''s. They obey the caster and are cooperative with each other. Duplicates can do anything the wu jen normally can except cast spells. If a duplicate is slain, it instantly disappears and the caster suffers 10 points of damage. At the end of the duration (1 round per 2 levels), all duplicates vanish without damage. Duplicates are indistinguishable from the caster even by True Seeing. Material component: A few hairs from the wu jen''s head or beard.'
WHERE LOWER(name_en) = LOWER('Body Outside Body') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Knochenwurfspeer',
  description = 'Ein Knochenwurfspeer erscheint in der Luft über der Hand des Zauberkundigen und schießt mit Bewegungsrate 30 auf das Ziel, wenn der Magier zeigt. Nach dem Treffer oder bei maximaler Reichweite kehrt er mit gleicher Geschwindigkeit zum Zauberkundigen zurück und schwebt über seiner Hand bis zum nächsten Einsatz. Der Magier kann zwischen den Würfen zaubern oder andere Aktionen ausführen. Der Speer kann Kurven und Wendungen fliegen, um Hindernissen auszuweichen. Trifft nur einmal pro Runde (Angriffswurf erforderlich). Verursacht 1W4 Schaden plus 1 Punkt pro Stufe des Zauberkundigen. Kann Untote, ätherische, außerplanare und materielle Kreaturen gleichermaßen treffen. RK −4, zerbricht bei 7+ Schadenspunkten. Materialkomponente: Eine winzige geschnitzte Speerreplika aus organischem Material, ein Tropfen Blut des Zauberkundigen und ein Knochensplitter (alle beim Wirken zerstört).',
  description_en = 'A bone javelin springs into being above the caster''s hand and flashes at a target when the caster points, at movement rate 30. After striking or reaching maximum range, it returns at the same speed and floats above the caster''s hand. The caster can cast spells or perform other activities between throws. The javelin can twist and turn to overcome barriers. Strikes only once per round (attack roll required). Deals 1d4 damage plus 1 point per caster level. Can damage undead, ethereal, other-planar, and Prime Material creatures alike. AC −4, shatters if dealt at least 7 points of damage. Material component: A tiny carved javelin replica of any organic material, a drop of the caster''s blood, and a bone fragment (all destroyed in casting).'
WHERE LOWER(name_en) = LOWER('Bone Javelin') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Wanze',
  description = 'Erschafft eine mentale Verbindung zwischen dem Zauberkundigen und einem Insekt, das als effektiver Spion eingesetzt werden kann. Alles, was das Insekt hört, hört auch der Zauberkundige. Durch Konzentration kann er auch durch die Augen des Insekts sehen. Da der Magier unerwartet durch Geräusche gestört werden kann, besteht eine 20%ige Chance, dass jede Konzentrationstätigkeit (z.B. Zaubern, Zauber Memorieren, psionische Kräfte) gestört wird. Der Zauberkundige ist auch verwundbar gegenüber Zaubern, die das Insekt betreffen — sie wirken auch auf ihn (ohne Rettungswurf). Wird das Insekt getötet, während die Verbindung besteht, erleidet der Magier 1W4 Schaden. Die Verbindung kann jederzeit getrennt werden. Reichweite: 16,1 km pro Stufe. Dauer: 1W4 Tage + 1 Tag pro 2 Stufen. Materialkomponente: Ein lebendiges Insekt und ein zerdrücktes Rosenblatt.',
  description_en = 'Creates a mental link between the caster and an insect, which can be used as an effective spy. Everything heard by the insect is heard by the caster. By concentrating, the caster can see through the insect''s eyes. Since the caster may be disturbed unexpectedly, there is a 20% chance that any concentration activity (e.g. spellcasting, memorizing spells, psionic powers) is disrupted. The caster is also vulnerable to spells affecting the insect — they affect the caster too (no saving throw). If the insect is killed while linked, the wizard suffers 1d4 damage. The link can be broken at any time. Range: 16.1 km per level. Duration: 1d4 days + 1 day per 2 levels. Material component: A live bug and a crushed rose petal.'
WHERE LOWER(name_en) = LOWER('Bug') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Kakofiend',
  description = 'Ein gefährlicher Zauber, mit dem normalerweise NPC-Bösewichte einen mächtigen Fiend beschwören: einen wahren Tanar''ri, einen höheren Baatezu oder einen großen Yugoloth (nicht mächtig genug für einzigartige Fiends, schwächere können nicht beschworen werden). Der Zauberkundige muss den Namen der Kreatur kennen. Der beschworene Fiend ist extrem zornig und feindlich. Der Magier muss durch Schutz vor Bösem und ein magisches Diagramm geschützt sein. Unterbrechung vor Erscheinen: Zauber scheitert. Unterbrechung nach Erscheinen: 10 % Chance pro Runde (kumulativ), dass der Fiend entkommt. Der Fiend erhält einen speziellen Rettungswurf: 2W10 > Stufe des Magiers = Misserfolg (20 scheitert immer). Der Fiend kann durch Drohung mit Geisterpeitsche, durch Versprechen eines Geschenks oder durch Bitten gezwungen werden, eine Aufgabe auszuführen. Wirkzeit: 1-8 Stunden.',
  description_en = 'A perilous spell normally used by NPC villains to summon a powerful fiend: a true tanar''ri, a greater baatezu, or a great yugoloth (not powerful enough for unique fiends; lesser sorts cannot be summoned). The caster must know the creature''s name. The summoned fiend is most angry and hostile. The wizard must be warded by Protection from Evil and a magical diagram. Interruption before appearance: spell fails. Interruption after: 10% cumulative chance per round the fiend escapes. The fiend gets a special saving throw: 2d10 > caster''s level = failure (roll of 20 always fails). The fiend can be coerced through threatening Spiritwrack, promising a gift, or requesting service. Casting time: 1-8 hours.'
WHERE LOWER(name_en) = LOWER('Cacofiend') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Kommunion mit Großem Geist',
  description = 'Identisch mit dem gleichnamigen Shukenja-Zauber der 5. Stufe. Jede Art von Geist kann kontaktiert werden, einschließlich göttlicher Mächte. Typische große Geister sind Geister eines Berges oder Flusses. Der Wu Jen muss die Identität des Geistes kennen (ermittelbar durch einen Trance-Zauber) und sich innerhalb von 3 m des Gebiets befinden, in dem der Geist zu finden ist. Nach Kontaktaufnahme kann der Wu Jen eine Frage pro Erfahrungsstufe stellen. Fragen müssen spezifisch sein und auf Ja/Nein beschränkt (auch „Vielleicht" und „Weiß nicht" möglich). Der Geist antwortet buchstäblich und gibt keine zusätzlichen Informationen preis — korrekt, wenn bekannt. Gute Geister versuchen hilfreich zu sein, neutrale antworten rätselhaft, böse versuchen die Antwort zu verdrehen. Der Geist kann nur Fragen über sein unmittelbares Gebiet beantworten.',
  description_en = 'Identical to the 5th-level shukenja spell of the same name. Any type of spirit can be contacted, including divine powers. Typical greater spirits are spirits of a mountain or river. The wu jen must know the spirit''s identity (obtainable via a Trance spell) and be within 3 m of the area where the spirit is found. Once contacted, the wu jen can ask one question per experience level. Questions must be specific, limited to yes/no answers ("maybe" and "I don''t know" also acceptable). The spirit answers literally and does not volunteer information — correct if known. Good spirits try to be helpful, neutral spirits answer in riddles, evil spirits try to distort answers. The spirit can only answer questions concerning its immediate area.'
WHERE LOWER(name_en) = LOWER('Commune With Greater Spirit') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Wissen Konsumieren',
  description = 'Erlaubt dem Magier, den Inhalt eines Buches, einer Schriftrolle oder ähnlichen Mediums augenblicklich zu absorbieren — mit einer Rate von einem Buch (ca. 200 Seiten) pro Runde. Die Magie zerstört jedoch das Buch oder den Datenträger physisch im Prozess. Nur ein Wunsch kann das konsumierte Schriftstück wiederherstellen. Hilft nicht beim Memorieren von Zaubern. Magische Bücher, Tomes, Librams usw. sind immun. Erlaubt nicht den schnelleren Erwerb von Fertigkeiten — die schnelle Informationsaufnahme kann Übung nicht ersetzen. Gewährt kein perfektes Erinnerungsvermögen — die Fakten unterliegen normalem Gedächtnisverlust und Verzerrung. Dauer: 1 Runde + 1 Runde pro Stufe.',
  description_en = 'Allows the wizard to instantly absorb the contents of a book, scroll, or similar medium — at a rate of one book (about 200 pages) per round. However, the dweomer physically destroys the book in the process. Only a Wish can restore consumed writing. Does not help memorize spells. Magical books, tomes, librams, etc. are immune. Does not allow faster proficiency gain — quick information consumption cannot replace practice. Does not grant perfect recall — facts are subject to normal memory loss and distortion. Duration: 1 turn + 1 round per level.'
WHERE LOWER(name_en) = LOWER('Consume Knowledge') AND spell_type = 'wizard';
