-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 8 (Batch 1: 13 Spells — Afterclap to Brain Spider)
-- Alle mechanischen Details, Materialkomponenten, Spezialfälle
-- Metrisch, eng an Originaltexten orientiert
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  name = 'Nachschlag',
  description = 'Dupliziert den Schaden, den ein einzelnes Wesen innerhalb der Zauberreichweite (3 m pro Stufe) in der vorherigen Runde erlitten hat. Der Schaden wird in Art und Menge exakt reproduziert — dieselben Schadenswürfe, Rettungswürfe, Eigenschaftsprüfungen usw. finden auf die gleiche Weise statt. Der Schaden kann aus jeder Quelle stammen, nicht nur aus magischen Angriffen. Beispiel: Ein Kämpfer erleidet 33 Schadenspunkte durch Pfeile, Gift und Finger des Todes in einer Runde — Nachschlag verdoppelt diesen Schaden in der nächsten Runde zusätzlich zum normalen Kampfschaden. Materialkomponente: Ein Stück steifer Gummi, der gezogen wird, bis er zurückschnellt.',
  description_en = 'Duplicates the damage suffered by a single creature within spell range (3 m per level) in the previous round. Damage is precisely duplicated in type and amount — the same damage rolls, saving throws, ability checks occur identically. Damage may have been caused by any source, not just magical attacks. Example: A fighter takes 33 damage from arrows, poison, and Finger of Death in one round — Afterclap duplicates this damage the next round in addition to normal combat damage. Material component: A bit of stiff rubber or gum that is pulled until it snaps back.'
WHERE LOWER(name_en) = LOWER('Afterclap') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Luftspirale',
  description = 'Erschafft eine aufrechte, spiralförmige, rotierende Treppe in der Luft (27,4 m hoch, 6,1 m Durchmesser). Sie erscheint mit einer Stufe unter den Füßen des Zauberkundigen. Der Magier kann sich oben, unten oder dazwischen befinden. Die Treppe kann mit Flugbewegungsrate 9 (BK: D) steigen oder sinken. Obwohl sie nicht durch feste Objekte hindurchgehen kann, durchdringt sie alle bekannten magischen Barrieren (Kraftkäfige, Prismatische Kugeln) und öffnet permanente sichere Durchgänge. Alle Wesen auf der Treppe können unter Wasser atmen und sind immun gegen Hitze, Kälte, elektrische Entladungen und alle Quetsch-/Einschnürungsangriffe (einschließlich Wasserdruck). Pro Runde kann der Magier ein Wesen auf der Treppe heilen (1W4+4 TP), es teleportieren oder 1W4+4 Schaden durch Blitz verursachen.',
  description_en = 'Creates an upright, helix-shaped, revolving staircase in the air (27.4 m high, 6.1 m diameter). It appears with one tread under the caster''s feet. The caster can be at the top, bottom, or anywhere in between. The staircase flies at movement rate 9 (MC: D). Although it cannot move through solid objects, it pierces all known magical barriers (forcecages, prismatic spheres), opening permanent safe-passage holes. All beings on the stair can breathe underwater and are immune to heat, cold, electrical discharges, and all crushing/constricting attacks (including water pressure). Per round, the caster can heal one creature on the stair (1d4+4 HP), teleport it, or deal 1d4+4 lightning damage.'
WHERE LOWER(name_en) = LOWER('Air Spiral') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Luftball',
  description = 'Erschafft eine sturmblau schimmernde, felsbrockengroße Kugel aus unglaublich komprimierter Luft (ca. 3 m Durchmesser) innerhalb von 109,7 m. Die Kugel (ca. 2,3 kg) fällt sofort zu Boden. Fällt sie 6,1 m oder mehr, zerbricht sie beim Aufprall in acht separate Windstoß-Zauber (jeder wie ein Windstoß eines Magiers der 8. Stufe, Winde von ca. 48 km/h) in alle acht Himmelsrichtungen. Zusätzlich wird Staub und Schmutz für 1W4 Runden aufgewirbelt (Sicht auf 3 m begrenzt). Fällt die Kugel nicht tief genug, bleibt sie am Boden liegen — unbeweglich und permanent, bis sie zerstört wird (RK 6, jeder Schaden löst sie aus; Berühren oder Schieben nicht). Benötigt 1 Million Kubikfuß Luft (ca. 100 × 100 × 30,5 m Volumen) — erzeugt aber kein Vakuum.',
  description_en = 'Creates a stormy-blue, boulder-sized sphere of incredibly compressed air (about 3 m diameter) within 109.7 m. The ball (about 2.3 kg) immediately falls to the ground. If it falls 6.1 m or more, it breaks on impact into eight separate Gust of Wind spells (each as an 8th-level caster, winds of about 48 km/h) in all eight compass directions. Additionally, dust and dirt are stirred up for 1d4 rounds (vision limited to 3 m). If it doesn''t fall far enough, it stays on the ground — stationary and permanent until broken (AC 6, any damage triggers it; touching or pushing does not). Requires one million cubic feet of air (about 100 × 100 × 30.5 m volume) — does not create a vacuum.'
WHERE LOWER(name_en) = LOWER('Airball') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Luftboot',
  description = 'Muss unter bewölktem Himmel gewirkt werden. Der Magier zeigt auf eine Wolke, die sofort herabsteigt und sich in ein beliebiges Gefäß verwandelt (drachenförmige Galeere, Einmann-Jolle usw.). Obwohl aus Wolke bestehend, fühlt sich das Luftboot solide an und kann das Gewicht des Zauberkundigen plus einem Passagier pro Stufe tragen. Bewegungsrate 21 (BK: D). Der Magier hat vollständige telepathische Kontrolle über Geschwindigkeit und Richtung. Während der Steuerung kann er andere Aktionen ausführen, aber keine Zauber wirken. Dauer: 1 Stunde pro Stufe.',
  description_en = 'Must be cast under a cloudy sky. The caster points at a cloud, which immediately descends and transforms into any vessel imagined (dragon-shaped galley, one-man dinghy, etc.). Although made of cloud, the airboat feels solid and can support the caster''s weight plus one passenger per level. Movement rate 21 (MC: D). The caster maintains total telepathic control over speed and direction. While controlling the vessel, the wizard can perform other actions but cannot cast spells. Duration: 1 hour per level.'
WHERE LOWER(name_en) = LOWER('Airboat') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Tier Modifizieren',
  description = 'Erlaubt dem Zauberkundigen, einen ausgewählten Teil der physischen Form einer lebenden Kreatur zu modifizieren — z.B. Pfoten in Hände verwandeln, einem Vierbeiner aufrechten Gang geben oder die Hirnkapazität erhöhen. Der Prozess erfordert ein Labor und mindestens eine Woche Vorbereitungszeit. Das Wirken verursacht starke Schmerzen, daher muss das Subjekt stark willig, immobilisiert oder bewusstlos sein. Das Subjekt muss einen Systemschock-Überlebenswurf bestehen (Basis 80 % + 1 % pro TW, wenn kein KON-Wert verfügbar). Die Veränderungen betreffen den genetischen Aufbau der Kreatur und können an Nachkommen weitergegeben werden, wenn sie sich mit einem ähnlich veränderten Wesen derselben Art paart. Nur Begrenzter Wunsch oder Wunsch kann die Effekte rückgängig machen. Materialkomponente: Zwei schwere Golddrahtstränge, zu einer Doppelhelix verdreht.',
  description_en = 'Allows the caster to modify a selected part of a living creature''s physical form — such as changing paws into hands, giving a quadruped an upright stance, or increasing brain capacity. The process requires a laboratory and at least a week''s preparation time. The casting inflicts much pain, so the subject must be strongly willing, immobilized, or unconscious. The subject must make a system shock survival roll (base 80% + 1% per HD if no CON score available). Changes affect the creature''s genetic makeup and may be passed on to offspring if mating with a similarly altered creature. Only Limited Wish or Wish can reverse the effects. Material component: Two strands of heavy gold wire twisted together in a double helix.'
WHERE LOWER(name_en) = LOWER('Alter Beast') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Magie Analysieren',
  description = 'Offenbart dem Magier alle Zauber, Verzauberungen und magischen Eigenschaften eines Gegenstands oder einer Kreatur. Eine Eigenschaft/Zauber/Kraft wird pro Runde in ungefährer chronologischer Reihenfolge enthüllt. Der Magier hat eine Grundchance von 50 % + 2 % pro Stufe (max. 99 %), eine bestimmte Eigenschaft zu erkennen. Nur Artefakte und Relikte bleiben undurchschaubar. Wirkzeit: 8 Stunden. Dauer: 1 Runde pro 2 Stufen. Beispiel: Ein Magier der 16. Stufe untersucht einen Stab des Feuers — er hat 82 % Chance, jede einzelne Verzauberung (Gegenstand Verzaubern, Feuerball, Brennende Hände, Feuerwand) pro Runde zu identifizieren. Der SL kann entscheiden, dass auch seltene Materialien oder Herstellungsprozesse wie Zauber enthüllt werden.',
  description_en = 'Reveals to the caster all spells, enchantments, dweomers, and magical properties present in one creature or object. One property/spell/power is revealed each round in approximate chronological order. The caster has a base 50% chance + 2% per level (max 99%) to discern each property. Only artifacts and relics remain inscrutable. Casting time: 8 hours. Duration: 1 round per 2 levels. Example: A 16th-level wizard analyzing a Wand of Fire has an 82% chance each round to identify each enchantment (Enchant an Item, Fireball, Burning Hands, Wall of Fire). The DM may decide that rare materials or processes used in creation are also revealed as if they were spells.'
WHERE LOWER(name_en) = LOWER('Analyze Dweomer') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Avissars Flammenwaffe',
  description = 'Durchdringt das berührte Wesen mit teuflischer Hitzeenergie aus der Ebene Baator. Kann nur einmal pro Woche gewirkt werden. Der Zauberkundige muss das Opfer berühren (erfolgreicher Angriffswurf). Wirkt auf jede einzelne Kreatur, außer: Kreaturen, die nur von magischen Waffen getroffen werden können, sind immun; Untote, feuerbasierte oder außerplanare Kreaturen sind nicht betroffen; Kreaturen, deren TW/Stufe die des Magiers übersteigen, sind unberührt. Kein Rettungswurf, aber Magieresistenz wirkt. Effekte: TP des Opfers werden auf 1 reduziert; ständige Qual wie lebendig verbrannt (schwitzend); erschöpft mit −4 auf Angriffs- und Schadenswürfe; jede Stunde 15 % Chance (nicht kumulativ), vor Schmerzen bewusstlos zu werden.',
  description_en = 'Infuses the touched creature with diabolic heat energy from the plane of Baator. Can only be cast once per week. The caster must touch the victim (successful attack roll). Affects any single creature except: creatures only hit by magical weapons are immune; undead, fire-based, or extraplanar creatures cannot be affected; creatures whose HD/level exceeds the caster''s level are unaffected. No saving throw, but magic resistance applies. Effects: victim''s HP reduced to 1; constant agony as if being burned alive (continuous sweating); exhausted with −4 on attack and damage rolls; each hour, 15% chance (non-cumulative) to be overcome by pain and lose consciousness.'
WHERE LOWER(name_en) = LOWER('Avissar''s Flaming Weapon') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Schwarzstab',
  description = 'Eine Kopie des berühmten Zaubers des Erzmagiers Khelben „Schwarzstab" Arunsun. Lässt jeden nicht-magischen Stab, Knüppel, Holzstück oder Stangenwaffe mit schwarzer, kriechender Strahlung schimmern. Eigenschaften: Kann den Zauberkundigen und Berührer während des Wirkens nicht verletzen; trifft als +4 magische Waffe (kein Schadensbonus); verursacht 1W8 Schaden unabhängig von Größe und Form; absorbiert auf sie gerichtete Magie ohne Folgen (nur Wunsch oder Antimagiehülle negiert ihn). Pro Runde kann eine Spezialfähigkeit gewählt werden: Berührung entzieht automatisch 1 TP (Rettungswurf gegen Todesmagie für temporären statt permanenten Verlust); oder verursacht Lähmung (1 Runde, Rettungswurf gegen Zauber negiert); oder erzeugt Magie Bannen bei Berührung. Dauer: 1 Runde pro Stufe.',
  description_en = 'A close copy of the famous spell by archmage Khelben "Blackstaff" Arunsun. Causes any non-magical staff, club, piece of wood, or pole arm to shimmer with black, crawling radiance. Properties: Cannot harm the caster or beings touching the staff during casting; strikes as a +4 magical weapon (no damage bonus); inflicts 1d8 damage regardless of size and shape; absorbs magic cast upon it without consequence (only Wish or Antimagic Shell negates it). Per round, one special ability can be chosen: touch automatically drains 1 HP (save vs. death magic for temporary rather than permanent loss); or causes paralysis (1 round, save vs. spell negates); or produces Dispel Magic on touch. Duration: 1 round per level.'
WHERE LOWER(name_en) = LOWER('Blackstaff') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Aufstieg Blockieren',
  description = 'Entzieht einem Magier (5.-15. Stufe, gleiche Gesinnung wie der Zauberkundige) dauerhaft die Fähigkeit, in Zauberstufen aufzusteigen, bis er die Prüfung eines Selbstbezwingungs-Zaubers besteht. Nur durch Wunsch ansonsten aufhebbar. Rettungswurf gegen Zauber (kann freiwillig aufgegeben werden). Bei unwilligem Ziel mit erfolgreichem Rettungswurf: 1W12 + 1 pro Stufe des Zauberkundigen als Schaden, aber sonst unbetroffen. Der Blockierte kann keine neuen Zauber lernen (aber im Zauberbuch aufzeichnen) und keine Zauber über dem aktuell höchsten verfügbaren Level wirken. Zusätzliche Zauber auf bereits verfügbaren Stufen können erworben werden. Der Zauber verhindert nicht den normalen Erfahrungspunktegewinn. Wurde ursprünglich vom Schwarzen Kreis entworfen, um unwürdige Magier zu kontrollieren.',
  description_en = 'Permanently strips a wizard (5th-15th level, same alignment as caster) of the ability to advance in spellcasting ability until surviving a Conquer Self spell ordeal. Only removable by Wish otherwise. Saving throw vs. spell (can be voluntarily forfeited). If unwilling target succeeds: 1d12 + 1 per caster level as damage, but otherwise unaffected. The blocked wizard cannot learn new spells (but can record them in a spellbook) and cannot cast spells above the currently highest available level. Additional spells at currently castable levels can be gained. Does not prevent normal experience point gain. Originally designed by the Black Circle to control unworthy wizards.'
WHERE LOWER(name_en) = LOWER('Block Advancement') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Körperverbindung',
  description = 'Verhindert den Tod durch Enthauptung oder Zerstückelung. Der Zauber verbindet die Körperteile des Magiers, sodass eine Trennung vom Hauptkörper sie in keiner Weise beeinträchtigt. Ein abgetrennter Kopf kann weiterhin sprechen und sogar essen; ein abgetrennter Arm behält die Muskelkontrolle und kann Waffen führen. Wird der Kopf abgetrennt, fällt der Körper schlaff zusammen, es sei denn der Magier besteht eine Intelligenzprüfung. Grunddauer: 1 Runde pro Stufe (passiv wartend). Nach Abtrennung: 1 Runde pro Stufe aktive Wirkung. Wird das Glied oder der Kopf in dieser Zeit zurückgesetzt, verbindet es sich sofort wieder. Schützt nur vor Enthauptung/Zerstückelung — anderer Schaden wirkt normal (ein Schwerthieb ins Herz tötet trotzdem). Materialkomponente: Eine Perle (Wert mind. 500 GM, beim Wirken zerstört) und etwas Baumsaft (muss konsumiert werden).',
  description_en = 'Prevents death by decapitation or dismemberment. Links the caster''s body parts so that separation does not impair them. A severed head can still talk and eat; a severed arm retains muscular control and can wield weapons. If the head is cut off, the body falls limp unless the caster rolls a successful Intelligence check. Base duration: 1 turn per level (passively waiting). After severance: 1 round per level of active effect. If the limb or head is replaced during this time, it immediately reattaches. Only protects against decapitation/dismemberment — other damage applies normally. Material component: A pearl worth at least 500 gp (destroyed in casting) and a small amount of tree sap (consumed by the caster).'
WHERE LOWER(name_en) = LOWER('Body Link') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Bombardierung — Altes Imperium',
  description = 'Beim Wirken auf eine einzelne Kreatur erscheinen riesige Steine und bombardieren das Ziel mit 10W6 Schadenspunkten (Rettungswurf gegen Zauber für halben Schaden). In jeder folgenden Runde trifft ein neues Bombardement mit erneut 10W6 Schaden. Die Dauer beträgt 1 Runde pro 4 Stufen des Zauberkundigen (abgerundet): Ein Magier der 16.-19. Stufe bombardiert 4 Runden, der 20.-23. Stufe 5 Runden usw. Jedes Folgebombardement trifft vor allen anderen Aktionen in der Runde. Kreaturen mit Magieresistenz prüfen jede Runde — Erfolg beendet den Zauber (vor dem Schaden). Verlässt das Ziel die Reichweite, endet der Zauber. Magie Bannen auf das Ziel negiert den Zauber. Materialkomponente: Ein Stück Meteoreisen.',
  description_en = 'When cast on a single creature, giant stones appear and bombard the target for 10d6 damage (saving throw vs. spell for half). Each successive round, a new bombardment strikes for 10d6 damage. Duration is 1 round per 4 caster levels (rounded down): a 16th-19th level wizard bombards for 4 rounds, 20th-23rd for 5 rounds, etc. Each follow-up bombardment strikes before any other actions in the round. Creatures with magic resistance check each round — success ends the spell (before taking damage). The spell ends if the target moves out of range. Dispel Magic on the target negates the spell. Material component: A piece of meteoric iron.'
WHERE LOWER(name_en) = LOWER('Bombard — Old Empire') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Knochenklinge',
  description = 'Erschafft eine temporäre, aber sehr effektive Waffe. Die Klinge kann von jedem Wesen geführt werden, das normalerweise Klingenwaffen führen kann. Sie ist identisch in Größe, Gewicht und Schaden mit der Klingenwaffe, die als Materialkomponente dient. Besondere Eigenschaften: Unzerbrechlich bis zum Zerfall am Zauberende; gilt als magische Waffe für Angriffszwecke; jedes untote Wesen, das zum ersten Mal von einer bestimmten Knochenklinge getroffen wird, muss einen Rettungswurf gegen Todesmagie bestehen oder wird sofort ausgelöscht (bei 8+ TW wird die Klinge dabei ebenfalls zerstört); verursacht doppelten Schaden gegen Untote; wirkt gegen Untote wie ein Schwert der Verwundung (1 zusätzlicher Schadenspunkt pro Runde pro Wunde; 1 Runde Behandlung negiert den Effekt für diese Wunde; magische Heilung ist unwirksam). Dauer: 1 Runde pro Stufe.',
  description_en = 'Creates a temporary but very effective weapon. The blade can be wielded by any being normally able to wield edged weapons. It is identical in size, weight, and damage to the bladed weapon serving as material component. Special properties: Unbreakable until it crumbles to dust at spell''s end; counts as a magical weapon for attack purposes; any undead struck for the first time must save vs. death magic or be instantly destroyed (if 8+ HD, the bone blade is also destroyed); deals double damage against undead; functions against undead as a Sword of Wounding (1 additional damage per round per wound; 1 round treating a wound negates the effect; magical curing is ineffective). Duration: 1 round per level.'
WHERE LOWER(name_en) = LOWER('Bone Blade') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Gedankenspinne',
  description = 'Erlaubt dem Magier, die Gedanken von bis zu acht Wesen gleichzeitig zu belauschen. Optionen: Das endlose Chaos der Oberflächengedanken hören; einzelne Gedankenstränge in gewünschter Reihenfolge verfolgen; Informationen aller Geister zu einem bestimmten Thema sammeln (1 Information pro Stufe); oder die Gedanken und Erinnerungen eines einzelnen Wesens detailliert studieren. Einmal pro Runde (in der keine detaillierte Studie stattfindet) kann der Magier eine Suggestion in den Geist eines der acht Wesen implantieren. Betrifft alle intelligenten Wesen nach Wahl des Zauberkundigen in Reichweite (bis zu 8). Rettungswurf gegen Zauber zum Widerstehen. Psionisch begabte oder Verzauberungs-Magie nutzende Wesen erkennen die Sonde sofort und entkommen automatisch. Kontakt mit wahnsinnigen oder schwachsinnigen Geistern verursacht 1W4+1 Schaden pro betroffenem Geist. Materialkomponente: Eine Spinne.',
  description_en = 'Allows the caster to eavesdrop on thoughts of up to eight beings simultaneously. Options: Hear the ceaseless chaos of surface thoughts; follow individual thought trains in desired order; gather information from all minds about one topic (1 nugget per level); or study one creature''s thoughts and memories in detail. Once per round (in rounds without detailed study), the caster can implant a Suggestion in one creature''s mind. Affects all intelligent beings of the caster''s choice within range (up to 8). Saving throw vs. spell to resist. Psionically gifted creatures or those casting enchantment/charm spells instantly detect the probe and automatically escape. Contact with insane or feebleminded minds inflicts 1d4+1 damage per deranged mind. Material component: A spider.'
WHERE LOWER(name_en) = LOWER('Brain Spider') AND spell_type = 'wizard';
