-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 6 (Batch 3: 12 Spells — Curse of Lycanthropy to Dusts of Death)
-- Alle mechanischen Details, Materialkomponenten, Spezialfälle
-- Metrisch, eng an Originaltexten orientiert
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  name = 'Fluch der Lykanthropie',
  description = 'Legt eine spezielle Form der Lykanthropie auf das berührte Wesen. Nur Menschen, Halbmenschen und einige Humanoide können betroffen werden — echte Lykanthropen und Gestaltwandler sind immun. Rettungswurf gegen Zauber negiert. In jeder Vollmondnacht (und den Nächten davor und danach) erleidet das Opfer einen lykanthropischen Anfall von Mondaufgang bis Monduntergang. Es wird von wahnsinniger Blutwut ergriffen und greift jeden an, der seinen Weg kreuzt — besonders Personen mit starker emotionaler Bindung. Während des Anfalls: STR steigt auf effektiv 19, waffenloser Angriff verursacht 1-2/1-2/1-3 Schaden, 2W10 temporäre TP, nur durch Silber- oder magische Waffen verwundbar. Das Opfer ist kein echter Lykanthrop und kann den Fluch nicht weitergeben. Nach dem dreitägigen Anfall erhält das Opfer einen neuen Rettungswurf gegen Zauber mit −3, um den Fluch zu brechen. Hält an, bis der monatliche Rettungswurf gelingt oder ein Wunsch gewirkt wird. Fluch Brechen erlaubt einen sofortigen neuen Rettungswurf.',
  description_en = 'Inflicts a special form of lycanthropy on the touched creature. Only humans, demihumans, and some humanoids can be affected — true lycanthropes and shapeshifters are immune. Saving throw vs. spell negates. On each full moon night (and nights before and after), the victim suffers a lycanthropic episode from moonrise to moonset. The victim is maddened with maniacal bloodrage, attacking anyone in their path — especially those for whom they feel strong emotion. During the episode: STR rises to effective 19, unarmed attacks deal 1-2/1-2/1-3 damage, 2d10 temporary HP, vulnerable only to silver or magical attacks. The victim is not a true lycanthrope and cannot pass on the curse. After the three-day episode, the victim receives a new saving throw vs. spell at −3 to break free. The curse lasts until the monthly save succeeds or a Wish is used. Remove Curse grants an immediate new saving throw.'
WHERE LOWER(name_en) = LOWER('Curse of Lycanthropy') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Dauntras Umhang',
  description = 'Schützt den Empfänger gegen alle bekannten Gifte und Venome (einschließlich giftiger Gase, aber nicht erstickenden Rauch oder andere physische Luftgefahren). Trotz des Namens ist der Zauber keine sichtbare Aura, kein Schild oder Umhang, sondern ein innerer Körperzustand, der automatisch jedes Gift neutralisiert, das mit ihm in Kontakt kommt — ideal zur Vorbereitung auf bekannte Giftgefahren. Die Wirkungsdauer basiert auf der Stufe des Zauberkundigen (1 Runde pro Stufe). Der Zauber wirkt vermutlich bei allen Säugetieren. Materialkomponente: Ein menschliches Haar und mindestens zwei Tropfen eines bekannten (flüssigen) Gifts.',
  description_en = 'Protects the recipient against all known venoms and poisons (including poisonous gases, but not choking smoke or other physical airborne dangers). Despite its name, the spell is not a visible aura, shield, or cloak, but an internal body state that automatically negates any poison coming into contact with it — ideal for preparing against known poison threats. Duration is based on the caster''s level (1 round per level). The spell is thought to be effective on all mammalian creatures. Material component: A human hair and at least two drops of a known (liquid) poison.'
WHERE LOWER(name_en) = LOWER('Dauntra''s Cloak') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Augen des Toten',
  description = 'Ein tödlicher nekromantischer Blickangriff. Die Augenweißen des Zauberkundigen werden schwarz und seine Pupillen formen sich zu kleinen weißen Totenköpfen. Der Zauberkundige kann ein Opfer pro Runde treffen, solange es innerhalb von 9,1 m ist und seinen Blick erwidert. Der Blickangriff erfolgt zusätzlich zu anderen Aktionen. Kreaturen mit 2 TW oder weniger (oder 2. Stufe oder niedriger) sterben sofort ohne Rettungswurf. Kreaturen mit 2+ bis 5 TW (3.-5. Stufe) sterben sofort, wenn sie keinen Rettungswurf gegen Todesmagie mit −2 bestehen; bei Erfolg erleiden sie 2W6 Schaden. Kreaturen mit 5+ TW oder mehr (6. Stufe+) erleiden 2W6 Schaden, wenn sie ihren Rettungswurf gegen Todesmagie nicht bestehen. Wird der Blick reflektiert (Spiegel, ruhiges Wasser), muss der Zauberkundige selbst einen Rettungswurf gegen Zauber ablegen. Nach Ende des Zaubers besteht eine 5%ige Chance auf Blindheit für 5-10 Stunden. Materialkomponente: Zwei augengroße Glasmurmeln in der Augenfarbe des Zauberkundigen.',
  description_en = 'A deadly necromantic gaze attack. The caster''s eye whites turn black and pupils reshape into small white skulls. The caster can affect one victim per round within 9.1 m who meets his gaze. The gaze attack is in addition to other actions. Creatures with 2 HD or fewer (2nd level or lower) instantly die with no saving throw. Creatures with 2+ to 5 HD (3rd-5th level) instantly die unless they save vs. death magic at −2; those who succeed suffer 2d6 damage. Creatures with 5+ HD or more (6th level+) suffer 2d6 damage unless they save vs. death magic. If the gaze is reflected (mirror, calm water), the caster must save vs. spell or suffer the effects. When the spell ends, there is a 5% chance of blindness for 5-10 hours. Material component: Two eyeball-sized glass marbles the same color as the caster''s eyes.'
WHERE LOWER(name_en) = LOWER('Dead Man''s Eyes') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Cinnabryl Entleeren',
  description = 'Entleert Cinnabryl augenblicklich. Pro drei Stufen des Zauberkundigen kann eine Wochenration (ca. 30 g) entleert werden (vier Wochen bei Stufe 12, fünf bei Stufe 13-15 usw.). Der Zauberkundige kann auch weniger entleeren. Wird hauptsächlich verwendet, um rohes Cinnabryl schnell in Rotstahl umzuwandeln, kann aber auch als Angriff gegen Erben eingesetzt werden, indem deren schützende Cinnabryl-Amulette entleert werden. Der Zauberkundige muss den Gegenstand berühren. Wird der Gegenstand von jemandem getragen, der nicht berührt werden will, ist ein Angriffswurf mit −4 erforderlich (gezielter Schuss). Der Zauber bleibt eine Runde nach dem Wirken aktiv; berührt der Zauberkundige in dieser Zeit kein Ziel, muss er einen Rettungswurf gegen Zauber bestehen, oder sein eigenes Cinnabryl wird betroffen. Ist weniger unverbrauchtes Cinnabryl im Gegenstand als der Zauberkundige beeinflussen kann, wirkt der Überschuss sofort auf die Zeit des Verlusts und der Veränderung.',
  description_en = 'Depletes cinnabryl instantly. As much as one week''s worth (approximately 30 g) per three caster levels can be depleted (four weeks at 12th level, five at 13th-15th, etc.). The caster can choose to deplete less. Primarily used to quickly turn raw cinnabryl into red steel, but can also attack Inheritors by depleting their protective cinnabryl amulets. The caster must touch the item. If the item is worn by an unwilling creature, an attack roll at −4 is required (called shot). The spell remains active for one round after casting; if the caster doesn''t touch a target in time, they must save vs. spell or their own cinnabryl is affected. If the item contains less undepleted cinnabryl than the caster can affect, leftover depletion applies instantly to the Time of Loss and Change.'
WHERE LOWER(name_en) = LOWER('Deplete Cinnabryl') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Doppelter Stahl',
  description = 'Erschafft ein Duplikat jeder Klingenwaffe, die der Zauberkundige berührt oder im Einsatz gesehen hat, aus dem Nichts. Das Duplikat entspricht dem Original exakt — einschließlich magischer Kräfte und Verzauberungen. Wenn der Zauber endet (1 Runde pro Stufe), verblasst die Klinge und kann nicht erneut dupliziert werden (diese spezifische Waffe kann von diesem Magier nie wieder kopiert werden). Der Zauberkundige oder ein anderes Wesen kann die Klinge führen und kennt beim Berühren sofort alle ihre Kräfte. Das Duplikat verschwindet sofort, wenn der Zauberkundige es führt und versucht, einen Zauber zu wirken — er kann aber frei zaubern, wenn jemand anderes die Klinge führt. Jeder, der das Duplikat führt, ist damit geübt. Der Zauberkundige kann wählen, ob er die Waffe mit seinem eigenen ETW0 oder dem eines Wesens führt, das er die Originalwaffe hat benutzen sehen. Die Wahl ist endgültig. Das Duplikat hat für die Dauer des Zaubers physische Existenz und kann auch von Feinden ergriffen werden — der Zauberkundige kann es aber jederzeit durch Willenskraft verschwinden lassen.',
  description_en = 'Creates a duplicate of any bladed weapon the caster has touched or seen in use, out of thin air. The duplicate matches the original exactly — including magical powers and enchantments. When the spell expires (1 round per level), the blade fades and cannot be recalled (that particular weapon cannot be duplicated by that wizard again). The caster or another being can wield the blade and upon touching it is made instantly aware of all its powers. The duplicate vanishes if wielded by the caster who attempts to cast a spell, but the caster is free to work magic if someone else wields it. Anyone who wields the duplicate does so as if proficient. The caster can choose to wield it with his own THAC0 or that of a being he has seen using the original. The choice cannot be changed. The duplicate has tangible physical existence and can even be seized by foes — but the caster can will it out of existence at any time.'
WHERE LOWER(name_en) = LOWER('Double Steel') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Drachenschuppen',
  description = 'Bedeckt den Körper des Empfängers vollständig mit Drachenschuppen und verbessert dadurch die Rüstungsklasse um 2 für die Dauer des Zaubers (1 Runde pro Stufe). Diese Modifikation gilt zusätzlich zur normalen Rüstungsklasse (z.B. von RK 6 auf RK 4). Drachenschuppen reduziert vorübergehend auch das Charisma des Empfängers um 2 Punkte. Die Farbe der Schuppen entspricht der als Materialkomponente verwendeten Drachenschuppe, hat aber keinen weiteren Einfluss auf den Zauber. Materialkomponente: Eine Schuppe eines beliebigen Drachen.',
  description_en = 'Completely covers the recipient''s body with dragon scales, effectively raising the subject''s Armor Class by 2 for the spell''s duration (1 turn per level). This modification is in addition to the subject''s normal AC (e.g. from AC 6 to AC 4). Dragon Scales also temporarily reduces the subject''s Charisma by 2 points. The color of the scales matches the dragon scale used as material component but has no other effect. Material component: A scale from any dragon.'
WHERE LOWER(name_en) = LOWER('Dragon Scales') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Drawmijs Wohltätige Verwandlung',
  description = 'Verleiht dem berührten und willigen Wesen alle Vorteile eines Selbstverwandlungs-Zaubers. Das Wesen muss keinen Systemschock-Wurf überstehen. Die erste Form wird vom Zauberkundigen gewählt, danach hat das Wesen volle Kontrolle über seine Formwechsel für die restliche Wirkungsdauer (1 Runde pro Stufe) und kann sich so oft verwandeln, wie es möchte — unter Beachtung aller Einschränkungen von Selbstverwandlung. Der Zauber verleiht keine besonderen Fähigkeiten der angenommenen Form und beeinflusst den Geisteszustand des Wesens in keiner Weise. Kehrt das Wesen in seine ursprüngliche Form zurück, werden 1W12 Trefferpunkte wiederhergestellt und der Zauber endet. Materialkomponente: Ein weicher Seidenkokon einer Raupe.',
  description_en = 'Endows the touched and willing creature with all benefits of a Polymorph Self spell. The creature does not need to make a system shock roll. While the first form is chosen by the caster, the creature has total control over form changes for the remainder of the duration (1 turn per level), changing as often as desired within all Polymorph Self limitations. The spell does not bestow special abilities of a polymorphed form and does not affect the creature''s mental state. When the creature returns to its original form, 1d12 hit points are restored and the spell ends. Material component: A soft silk caterpillar cocoon.'
WHERE LOWER(name_en) = LOWER('Drawmij''s Beneficent Polymorph') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Drawmijs Barmherzige Metamorphose',
  description = 'Von Drawmij als barmherzige Art entwickelt, einen Gegner loszuwerden. Verwandelt einen Gegner permanent in eine andere Kreatur wie bei Andere Verwandeln, aber der Rettungswurf gegen Verwandlung erfolgt mit −2. Das Ziel kann nur in ein natürliches Tier verwandelt werden, das nicht größer als ein typisches Herdentier ist. Kein Systemschock-Wurf nötig. Das verwandelte Wesen nimmt sofort den Geisteszustand des Tieres an und vergisst alles Wissen über sein früheres Selbst. Das Tier strahlt weder Magie noch die ursprüngliche Gesinnungsaura aus. Bei Rückverwandlung durch Magie Bannen, Begrenzter Wunsch oder Wunsch ist das Wesen völlig verwirrt (wie Verwirrung 4. Stufe für 2W4 Runden). Danach kehren Wissen und Erinnerungen über 1W4 Tage langsam zurück. Materialkomponente: Ein Kokon, eingeweicht in einem Balsam aus Honig, pulverisiertem gelbweißem Moosachat (Wert 500 GM) und pulverisiertem Smaragd (Wert 700 GM).',
  description_en = 'Developed by Drawmij as a merciful way to get rid of an adversary. Permanently polymorphs an opponent into another creature as Polymorph Other, but the saving throw vs. polymorph is at −2. The target can only become a natural animal no larger than a typical herd beast. No system shock roll required. The polymorphed creature immediately assumes the animal''s mental state, forgetting all knowledge of its previous self. The animal does not radiate magic or the creature''s original alignment aura. If returned to original form by Dispel Magic, Limited Wish, or Wish, the creature suffers Confusion (as 4th-level spell) for 2d4 rounds. After confusion passes, previous knowledge and memories gradually recover over 1d4 days. Material component: A cocoon soaked in a balm of honey, powdered yellow-white moss agate (500 gp), and powdered emerald (700 gp).'
WHERE LOWER(name_en) = LOWER('Drawmij''s Merciful Metamorphosis') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Staub des Todes',
  description = 'Verwandelt eine Prise Sand in ein unglaublich toxisches Gift. Der vergiftete Sand kann durch normale Mittel nicht entdeckt werden, obwohl Magie Entdecken oder Gift Entdecken die Anwesenheit des Zaubers offenbaren. Wird der Sand in Essen oder Getränke gemischt, wird er sicher aufgenommen. Wer den Sand konsumiert, muss einen Rettungswurf gegen Zauber bestehen oder stirbt augenblicklich. Der einzige Hinweis auf die Todesursache ist eine leichte Sandstaubung um Mund und Nasenlöcher des Opfers. Magiergesellschaften schätzen diesen Zauber als Methode der Attentatskunst, und sein Geheimnis wird eifersüchtig gehütet. Der Zauber hält 1 Stunde an, bevor der Sand seine Wirkung verliert. Materialkomponente: Eine Prise Sand.',
  description_en = 'Turns a pinch of sand into an incredibly toxic poison. The envenomed sand cannot be detected by any normal means, though Detect Magic or Detect Poison will reveal the spell''s presence. If introduced into food and drink, it will surely be ingested. Whoever consumes the sand must save vs. spell or die instantly. The only clue to the cause of death is a small dusting of sand around the victim''s mouth and nostrils. Sorcerous societies are fond of using this as an assassination method, and the spell''s secret is jealously guarded. The spell lasts 1 hour before the sand loses potency. Material component: A pinch of sand.'
WHERE LOWER(name_en) = LOWER('Dusts of Death') AND spell_type = 'wizard';
