-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 8 (Batch 2: 13 Spells — Burn Path to Death Link)
-- Alle mechanischen Details, Materialkomponenten, Spezialfälle
-- Metrisch, eng an Originaltexten orientiert
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  name = 'Pfad Verbrennen',
  description = 'Diese mächtige zerstörerische Magie vernichtet dauerhaft alles Wissen eines Magiers über einen magischen Pfad (eine Reihe verwandter Zauber). Der Zauberkundige wählt den zu verbrennenden Pfad. Alle Formeln und Zauber des Pfades werden sofort vergessen, memorierte Zauber verschwinden aus dem Geist des Opfers, und alle Zauber dieses Pfades müssen neu erlernt werden. Der Effekt ist irreversibel, aber bei erfolgreichem Rettungswurf wird der Pfad nur versiegelt (wie bei Pfad Versiegeln). Kann nur auf ein hilfloses oder bewusstloses Opfer gewirkt werden. Wirkzeit: 8 Stunden. Materialkomponente: Eine dünne gehämmerte Goldplatte (Wert mind. 3.000 GM), beschriftet mit der Formel des Einstiegszaubers des Pfades.',
  description_en = 'This powerful destructive magic permanently destroys all knowledge a wizard has of one path of magic (a series of related spells). The caster chooses which path is burned. All spells and formulas of the path are instantly forgotten, memorized spells vanish from the victim''s mind, and all spells on that path must be relearned from scratch. The effect is irreversible, but on a successful saving throw the path is merely sealed (as by a Seal Path spell). Can only be cast on a helpless or unconscious recipient. Casting time: 8 hours. Material component: A thin sheet of beaten gold (worth at least 3,000 gp) inscribed with the formula for the path''s starting spell.'
WHERE LOWER(name_en) = LOWER('Burn Path') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Rufen',
  description = 'Ermöglicht dem Wu Jen, jede einzelne Kreatur, die er vom Sehen kennt, in seine Gegenwart zu beschwören. Der Wu Jen muss die spezifische Identität der gerufenen Kreatur kennen, nicht nur die allgemeine Art. Kreaturen mit Namen müssen bei ihrem wahren Namen gerufen werden. Ein erfolgreicher Rettungswurf gegen Zauber erlaubt der Kreatur, den Ruf zu ignorieren. Gerufene Kreaturen müssen sich auf derselben Ebene befinden wie der Zauberkundige. Einmal gerufen, steht die Kreatur unter keinem Zwang zu bleiben oder dem Zauberkundigen zu helfen. Gottheiten und ähnlich mächtige Wesen müssen dem Ruf nicht folgen. Wirkzeit: 1 Runde. Materialkomponente: Ein Räucherstäbchen und ein Papierstreifen, die beim Wirken verbrannt werden.',
  description_en = 'Allows the wu jen to summon any single creature he knows by sight into his presence. The wu jen must know the specific identity of the creature called, not just the general type. Creatures with names must be summoned by their true name. A successful saving throw vs. spell allows the creature to ignore the call. Called creatures must be on the same plane as the caster. Once called, the creature is under no compulsion to remain or aid the caster. Deities and similarly powerful beings need not heed the call. Casting time: 1 turn. Material component: A stick of incense and a strip of paper, burned when casting.'
WHERE LOWER(name_en) = LOWER('Call') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Ruf der Verzweiflung — Elf',
  description = 'Alle Kreaturen im Wirkungsbereich (3 m pro Stufe Radius, Reichweite 3 m pro Stufe), außer der Armee, Verbündeten oder Gefährten des Zauberkundigen, müssen eine Moralprüfung mit der Hälfte ihres aktuellen Moralwertes ablegen. Wer scheitert, flieht sofort in Terror direkt vom Zauberkundigen weg. Der Terror hält 1 Runde pro Stufe an — Sammeln ist während dieser Zeit nicht möglich. Materialkomponente: Ein Messinggong. Eingeschränkt auf Elfen, die elfische Hochmagie wirken können — wird hauptsächlich zur Verteidigung der elfischen Heimat (z.B. Evermeet) eingesetzt.',
  description_en = 'All creatures in range (3 m per level radius, range 3 m per level), except the caster''s army, allies, or companions, must check morale at half their current morale rating. Those who fail immediately flee in terror, directly away from the caster. The terror lasts 1 turn per caster level — rally checks cannot be made during this time. Material component: A brass gong. Restricted to elves able to cast Elven High Magic — primarily used for defense of the elven homeland (e.g. Evermeet).'
WHERE LOWER(name_en) = LOWER('Call of Despair — Elf') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Form Wechseln',
  description = 'Leitet einen Prozess ein, der mit der vollständigen Metamorphose des Empfängers in ein völlig neues Wesen endet — physisch und mental. Die Veränderung ist total, unabhängig von der Größe des Empfängers. Die neue Form kann so klein wie eine Ameise oder so groß wie ein Wal sein, darf aber nicht mehr TW haben als das Subjekt aktuell besitzt. Muss ein lebendes, auf der Materiellen Ebene heimisches Wesen sein (keine Untoten, Dämonen, Konstrukte, Elementare). Ein anfänglicher Rettungswurf gegen Verwandlung negiert den Effekt; bei Misserfolg kann nur ein Wunsch den Prozess stoppen (aber nicht umkehren — dafür ein zweiter Wunsch, ein dritter beschleunigt die Erholung auf 1 Tag). Die Verwandlung findet über mehrere Wochen statt: Alle Eigenschaften (Attribute, Gesinnung, Form, RK, TW) bewegen sich schrittweise zum Zielwesen, alle 10 Tage eine Stufe näher. Materialkomponente: V, S, M.',
  description_en = 'Initiates a process ending in the complete metamorphosis of the recipient into an entirely new creature — physical and mental. The change is total, regardless of the recipient''s size. The new form can be as tiny as an ant or huge as a whale, but cannot have more HD than the subject currently possesses. Must be a living creature native to the Prime Material Plane (no undead, fiends, constructs, elementals). An initial saving throw vs. polymorph negates; on failure, only a Wish can stop (but not reverse — a second Wish reverses, a third speeds recovery to 1 day). Transformation occurs over several weeks: all characteristics (ability scores, alignment, form, AC, HD) shift one step toward the target creature every 10 days. Material component: V, S, M.'
WHERE LOWER(name_en) = LOWER('Change Form') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Mann Bezaubern III',
  description = 'Der stärkste der Mann-Bezaubern-Zauber. Betrifft bis zu 1W8+8 Männer der 5. Stufe oder niedriger innerhalb eines 6,1-m-Radius. „Mann" ist definiert als jeder männliche Mensch, Halbmensch oder humanoide Kreatur der Größe L oder kleiner mit 3 TW oder weniger. Alternativ kann der Zauber auf eine einzelne männliche Kreatur beliebiger Stufe oder TW gewirkt werden. Wirkt nicht auf Untote. Kreaturen, die normalerweise gegen Bezauberungen resistent sind (z.B. Elfen), sind gegen diesen Zauber NICHT resistent. Der Einfluss der Zauberin kann von einem starken Anführer unter den Zielen angefochten werden (Reaktionswurf mit CHA-Modifikatoren, Zauberin erhält −2 Bonus). Betroffene betrachten die Zauberin als vertrauenswürdige Verbündete, befolgen Vorschläge und beschützen sie. Selbstzerstörerische Befehle werden ignoriert. Dauer: 1W6+6 Runden.',
  description_en = 'The strongest of the Charm Man spells. Affects up to 1d8+8 men of 5th level or lower within a 6.1 m radius. "Man" is defined as any male human, demihuman, or humanoid creature of size L or less with 3 HD or less. Alternatively, the spell can target a single male creature of any level or HD. Does not affect undead. Creatures normally resistant to charm spells (such as elves) are NOT resistant to this spell. The caster''s influence can be contested by a strong leader among subjects (Reaction check with CHA modifiers, caster gains special −2 bonus). Charmed subjects regard the caster as a trusted ally, follow suggestions, and protect her. Self-destructive commands are ignored. Duration: 1d6+6 turns.'
WHERE LOWER(name_en) = LOWER('Charm Man III') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Kreis der Blindheit',
  description = 'Wird eingesetzt, um Feinde zu verzögern und zu verwirren. Im Wirkungsbereich (9,1 m Radius, Reichweite 219,5 m) neutralisiert der Zauber normales und magisch verstärktes Sehen und Hören. Er unterdrückt auch die Effekte verschiedener Erspähungszauber. Kein Rettungswurf. Dauer: 3 Runden. Dieser Zauber wird häufig im Kampf eingesetzt, um feindliche Einheiten zu blenden und zu tauben, während die eigenen Truppen angreifen.',
  description_en = 'Used to delay and confuse enemies. Within the area of effect (9.1 m radius, range 219.5 m), the spell neutralizes normal and magically enhanced vision and hearing. It also suppresses the effects of various scrying spells. No saving throw. Duration: 3 turns. This spell is frequently used in combat to blind and deafen enemy units while friendly troops attack.'
WHERE LOWER(name_en) = LOWER('Circle of Blindness') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Wolkentrapez',
  description = 'Ermöglicht dem Wu Jen, auf einer magischen Wolke mit unglaublicher Geschwindigkeit zu fliegen. Beim Wirken hebt der Wu Jen sanft auf einer kleinen Wolke in die Luft ab und saust in die gewünschte Richtung. Pro vier Stufen kann ein weiteres menschengroßes Wesen mitgenommen werden. Die Bewegungsrate beträgt 16,1 km pro Runde. Der Wu Jen hat volle Kontrolle über Richtung und Geschwindigkeit. Der Zauber endet automatisch nach 1 Runde, kann aber mit weiteren Wirkungen verlängert werden. Das Wolkentrapez bietet keinen Schutz vor Wettereinflüssen oder Angriffen — der Wu Jen und seine Passagiere sind während des Fluges verwundbar.',
  description_en = 'Allows the wu jen to soar on a magical cloud at incredible speeds. Upon casting, the wu jen gently lifts into the air on a small cloud and whizzes away in any desired direction. One additional man-sized creature can be taken per four caster levels. Movement rate is 16.1 km per round. The wu jen has full control over direction and speed. The spell ends automatically after 1 turn but can be extended with further castings. The cloud trapeze provides no protection from weather or attacks — the wu jen and passengers are vulnerable during flight.'
WHERE LOWER(name_en) = LOWER('Cloud Trapeze') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Kältevorhang — Drache',
  description = 'Ein Schutzzauber ähnlich Todestür. Der drachische Zauberkundige schützt einen Durchgang oder ein Portal (bis 9,1 m Durchmesser) so, dass jede Kreatur ohne Befehlswort einer modifizierten Energieentzugsform unterliegt. Das Portal strahlt starke nekromantische Magie aus und ist ca. 11°C kälter als die Umgebung. Ein Portal kann bis zu 30 TW/Stufen entziehen. Rettungswurf gegen Stäbe mit −2; Erfolg = unbetroffen. Misserfolg = 1 Stufe/TW sofort verloren (wie bei einem Wight). Jede weitere Runde im geschützten Bereich verliert man eine weitere Stufe/TW (kein Rettungswurf). Der Verlust hält an, bis die Kreatur den Bereich durch das Portal wieder verlässt. Das Portal kann sichtbar gemacht werden (schwach blau schimmernd, nicht bei Tageslicht erkennbar). Nur das Portal selbst ist geschützt — man könnte theoretisch die Wand daneben durchbrechen.',
  description_en = 'A warding spell similar to Door of Death. The draconic caster wards a doorway or portal (up to 9.1 m diameter) so that any creature without a command word is subject to a modified energy drain. The portal radiates strong necromantic magic and is about 11°C colder than surroundings. Can drain up to 30 HD/levels total. Saving throw vs. wands at −2; success = unaffected. Failure = lose 1 level/HD immediately (as if struck by a wight). Each further round in the warded area costs another level/HD (no save). Loss continues until the creature exits through the portal. The portal can be made visible (faint blue shimmer, not visible in daylight). Only the portal itself is warded — one could theoretically breach the wall beside it.'
WHERE LOWER(name_en) = LOWER('Cold Curtain — Dragon') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Portal Kollabieren',
  description = 'Diese seltene Magie kann die Kristallsphäre versiegeln, in der eine Fantasiewelt schwebt. Der Zauber ist unzuverlässig — der Zauberkundige muss eine Intelligenzprüfung bestehen, um ein Scheitern zu vermeiden. Wurde in der letzten Runde innerhalb von 1,6 km ein Portal-Erschaffen-Zauber gewirkt, erfolgt die Prüfung mit −3 Malus. Bei Erfolg versiegelt sich die Kristallsphäre. Erreicht ein Schiff die Sphäre während der zweirundigen Wirkzeit, wird per W10 bestimmt, was passiert: Das Portal schließt sich vor dem Schiff (Schiff muss wenden oder rammt), gleichzeitig (unvermeidliche Kollision), auf dem Schiff (schneidet es sauber in zwei Hälften), oder knapp danach (Schiff passiert sicher). Wirkungsbereich: 6,1 m Radius pro Stufe. Wirkzeit: 2 Runden.',
  description_en = 'This rare magic can seal the crystal sphere in which a fantasy world floats. The spell is unreliable — the caster must make an Intelligence check to avoid failure. If a Create Portal spell was cast within 1.6 km in the past turn, the check is at −3 penalty. On success, the crystal sphere seals. If a ship reaches the sphere during the two-round casting time, roll d10: portal closes before the ship (must turn or ram), simultaneously (unavoidable ram), on the ship (cuts it cleanly in two), or just after (ship passes safely). Area of effect: 6.1 m radius per level. Casting time: 2 rounds.'
WHERE LOWER(name_en) = LOWER('Collapse Portal') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Todestyrann Erschaffen — Betrachter',
  description = 'Erlaubt einem Zauberkundigen (normalerweise einem Ältesten-Orb), Todestyrannten aus den Hüllen oder Leichen toter Betrachter zu erschaffen. Ein Todestyrann wird pro TW des Ältesten-Orbs oder Stufe des Zauberkundigen erschaffen. Der Zauber gewährt keine permanente Kontrolle über die untoten Betrachter. Der Zauberkundige kontrolliert die Todestyrannten nur für die Dauer des Zaubers. Danach sind die Todestyrannten frei und können ihren eigenen Willen ausüben — was sie oft gefährlich und unberechenbar macht. Reichweite: 6,1 m. Wirkzeit: V.',
  description_en = 'Allows a caster (usually an elder orb) to create death tyrants from the shells or corpses of dead beholders. One death tyrant is created per Hit Die of the elder orb or level of the caster. The spell does not grant permanent control of the undead beholders. The caster controls the death tyrants only for the spell''s duration. Afterward, the death tyrants are free-willed — often making them dangerous and unpredictable. Range: 6.1 m. Casting time: V.'
WHERE LOWER(name_en) = LOWER('Create Death Tyrant — Beholder') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Spektralen Magier Erschaffen',
  description = 'Ermöglicht dem Zauberkundigen, einen menschlichen oder elfischen Magier oder einen Gnom-Illusionisten sterben zu lassen und in einen Spektralen Magier zu verwandeln. Bei unwilligem Empfänger: Rettungswurf gegen Todesmagie negiert den Zauber. Beim Sterben und Untot-Werden verliert der Empfänger 1W4 Stufen. Einmal belebt, hat der Spektrale Magier einen freien Willen, aber jede Äußerung seines Erschaffers wirkt wie ein Suggestions-Zauber auf ihn. Nur ein Wunsch kann den untoten Zustand aufheben. Ein wiederhergestellter Spektraler Magier hat eine 50%ige Chance, mit seinen ursprünglichen Stufen zurückzukehren. Wirkzeit: 1 Runde.',
  description_en = 'Allows the caster to cause a human or elf wizard or gnome illusionist to die and become a spectral wizard. If cast on an unwilling recipient: saving throw vs. death magic negates. In the process of dying and becoming undead, the recipient is drained of 1d4 levels. Once animated, the spectral wizard is free-willed, but any utterance from its creator acts as a Suggestion spell upon it. Only a Wish can free a spectral wizard of its undead state. A restored spectral wizard has a 50% chance to retain original levels. Casting time: 1 turn.'
WHERE LOWER(name_en) = LOWER('Create Spectral Wizard') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Wächtergeist Erschaffen',
  description = 'Belebt eine Leiche mit dem Geist und der Intelligenz ihres früheren Selbst und bindet sie in den Dienst bis zum Tod des Erschaffers. Muss innerhalb von fünf Jahren nach dem Tod der Leiche gewirkt werden. Während des Wirkens erteilt der Nekromant die Befehle des Wächtergeists. Befehle dürfen nicht mehr als eine Aufgabe umfassen und müssen genau definieren, was der Wächtergeist tun soll, wie er es ausführt, und eine Ausnahme (falls vorhanden). Beispiel: „Bewache mein Labor gegen alle Eindringlinge außer mir. Töte alles, das mein Labor zu betreten versucht." Die Gesinnung wird während des Dienstes rechtschaffen. Beim Tod des Erschaffers wird der Wächtergeist von seinen Befehlen befreit. RK 1, BW 9/Fl 9 (C), TW 10+, ETW0 6, Schaden 2W8 + Kälte, MR 25 %. Materialkomponente: Diamantstaub (Wert 1.500 GM), vier zu Pulver gemahlene Zähne und eine Handvoll Haare des Erschaffers.',
  description_en = 'Animates a corpse with the spirit and intelligence of its former self, binding it into service until the caster''s demise. Must be cast within five years of the corpse''s death. During casting, the necromancer issues commands. Commands cannot require more than one task and must specifically define what the watchghost does, how it carries out the task, and one exemption if any. Example: "Guard my laboratory against all intruders except myself. Kill anything that tries to enter." Alignment becomes lawful during service. Upon the caster''s death, the watchghost is freed. AC 1, MV 9/Fl 9 (C), HD 10+, THAC0 6, damage 2d8 + chill, MR 25%. Material component: Diamond dust (1,500 gp), four of the caster''s teeth ground to powder, and a handful of the caster''s hair.'
WHERE LOWER(name_en) = LOWER('Create Watchghost') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Todesverbindung',
  description = 'Auch als Körpersympathie bekannt. Stellt eine zweiseitige sympathetische Verbindung zwischen dem Zauberkundigen und einer Zielkreatur her. Jeder Schaden, den der Magier erleidet, wird automatisch auch der verbundenen Kreatur zugefügt; stirbt der Magier, stirbt auch die verbundene Kreatur. Umgekehrt: Wird die verbundene Kreatur verletzt, wird auch der Magier verletzt. Rettungswürfe, Eigenschaftsprüfungen und RK gelten für das jeweils angegriffene Individuum — nur der Effekt wird übertragen. Ausnahme: Stirbt die verbundene Kreatur, überlebt der Magier, sofern der übertragene Schaden nicht tödlich war. Sowohl heilende als auch zerstörende Zauber überqueren die Verbindung. Kann nach dem Wirken nicht vorzeitig beendet werden — hält bis zum Ende der Dauer (1 Runde pro Stufe) oder bis eine Partei die Ebene verlässt. Wird gelegentlich als Vergeltungswerkzeug oder als Verhandlungssicherheit eingesetzt.',
  description_en = 'Also called Body Sympathy. Creates a two-way sympathetic link between the wizard and a target creature. Any damage inflicted on the wizard is automatically inflicted on the linked creature; if the caster dies, so does the linked creature. Conversely, damage to the linked creature hurts the caster. Saving throws, ability checks, and AC apply to the individual attacked — only the effect carries over. Exception: if the linked creature dies, the caster survives unless enough damage transferred through the link proves fatal. Both curative and destructive spells cross the link. Cannot be ended early once cast — lasts until duration expires (1 turn per level) or one party leaves the plane. Occasionally used as a revenge tool or negotiation safeguard.'
WHERE LOWER(name_en) = LOWER('Death Link') AND spell_type = 'wizard';
