-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 7 (Batch 2: 13 Spells — Create Major Helm to Draincone)
-- Alle mechanischen Details, Materialkomponenten, Spezialfälle
-- Metrisch, eng an Originaltexten orientiert
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  name = 'Großen Helm Erschaffen',
  description = 'Verwandelt einen normalen Stuhl oder Sitz in einen großen Spelljammer-Helm zum Antrieb eines Schiffs durch den Weltraum. Ersetzt nicht die Notwendigkeit eines permanenten magischen Helms an Bord — hauptsächlich für Notfälle gedacht. Altert den Zauberkundigen um ein Jahr. Der große Helm kann ein Schiff von maximal der dreifachen Stufe des Zauberkundigen in Tonnage antreiben (ein Magier der 20. Stufe kann einen Helm für ein 60-Tonnen-Schiff erschaffen). In der Bedienung identisch mit einem permanenten Helm, mit einer Ausnahme: wird er gebannt, verschwindet er für eine einzelne Runde und erscheint dann wieder. Das Erschaffen zählt als ein Zauber und reduziert die Effektivität des Zauberkundigen als Steuermann für diesen Tag. Materialkomponente: Ein Stuhl, Hocker oder anderer Sitz.',
  description_en = 'Transforms a normal chair or seat into a major spelljammer helm suitable for powering a ship through space. Does not replace the need for a permanent magical helm onboard — primarily for emergencies. Ages the caster one year. The major helm can power a ship of no more than three times the caster''s level in tonnage (a 20th-level wizard can power a 60-ton ship). In operation, identical to a permanent helm, with one exception: if dispelled, it disappears for a single round then reappears. Creating counts as one spell cast, reducing the caster''s helmsman effectiveness for that day. Material component: A chair, stool, or other suitable seat.'
WHERE LOWER(name_en) = LOWER('Create Major Helm') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Schatten Erschaffen',
  description = 'Erschafft einen kühlen, schattigen Fleck Boden zum Ausruhen und Überleben für Kreaturen, die in einer heißen Wüste oder einem anderen sonnenverbrannten Ort gestrandet sind. Der Bereich ist klar durch einen dunklen Schattenfläche auf dem Boden abgegrenzt, obwohl kein Objekt existiert, das diesen Schatten werfen könnte. Wesen im Schattenbereich benötigen weniger Wasser, wie bei natürlichem Schatten. Der Zauber verändert die Temperatur nicht anderweitig. Beliebig viele Kreaturen können die Vorteile genießen, solange sie in den Bereich passen — allerdings zieht der Schatten oft unerwünschte Lebensformen (z.B. Insekten) an. Andere Zauber können im Schattenbereich gewirkt werden, ohne ihn zu zerstören. Magie Bannen beendet den Schatten sofort. Keine Konzentration nötig. Der Zauberkundige kann den Schatten jederzeit durch Willenskraft beenden. Muss auf Sand oder natürlichem Boden gewirkt werden — auf Dächern oder Schiffsdecks scheitert er. Einmal gewirkt, ist der Schatten unbeweglich.',
  description_en = 'Creates a cool, shaded patch of ground for rest and survival of creatures stranded in a hot desert or sun-baked place. The area is clearly delineated by dark shade on the ground, though no object casts the shadow. Those within require less water, as in natural shade. The spell does not otherwise modify temperature. Any number of creatures can benefit if they fit in the area — though it often attracts unwanted life-forms (e.g. insects). Other spells can be cast within the shade without destroying it. Dispel Magic ends the shade immediately. No concentration needed. The caster can end the shade at will. Must be cast on sand or solid natural ground — fails on roofs or ship decks. Once cast, the shade cannot be moved.'
WHERE LOWER(name_en) = LOWER('Create Shade') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Klangstab Erschaffen',
  description = 'Erschafft einen Klangstab, der für 60 Tage überschüssigen Lärm dämpft und absorbiert. Der Stab wird in den Boden oder auf ein Dach gesteckt und erzeugt einen kugelförmigen Bereich relativer Ruhe (bis zu 91,4 m in jede Richtung). Normale Gespräche und Zauberwirken sind möglich, aber der Stab erzeugt die Illusion eines friedlichen Bereichs — selbst in einer lauten Marktplatzmenge oder vor einem Aufruhr. Der Stab „dämpft" Klangangriffe (+1 auf Rettungswürfe dagegen) und absorbiert alle abgelenkten Klänge und klangbasierten Angriffe (z.B. Harpiengesang, Schrei-Zauber, Machtwort-Zauber) vollständig. Nach 60 Tagen kann der Stab als Waffe für 10 Tage eingesetzt werden: Er emittiert einen Klangkegel (18,3 m lang, 6,1 m Basis), der wie Machtwort Betäuben wirkt. Der Stab enthält 2W6 Ladungen. Am 11. Tag dissipiert verbleibende Magie harmlos.',
  description_en = 'Creates a soundstaff that dampens and absorbs excess noise for 60 days. The staff is planted in the ground or atop a roof and creates a spherical area of relative peace and quiet (up to 91.4 m in any direction). Normal conversations and spellcasting can occur, but the staff creates the illusion of a placid area — even in a marketplace or near a riot. The staff "muffles" sonic attacks (+1 to saves against them) and fully absorbs all dumped sounds and sound-based attacks (e.g. harpy songs, Shout spells, Power Word spells). After 60 days, the staff functions as a weapon for 10 days: it emits a sonic cone (18.3 m long, 6.1 m base) with the effect of Power Word Stun. The staff contains 2d6 charges. On the 11th day, remaining magic dissipates harmlessly.'
WHERE LOWER(name_en) = LOWER('Create Soundstaff') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Zyklon-Streitwagen',
  description = 'Beschwört eine wirbelwindartige Kraft von großer Stärke unter den Füßen des Magiers und bis zu acht weiterer menschengroßer Kreaturen und hebt sie bis zu 6,1 m hoch. Der Magier steuert den Streitwagen mental mit Bewegungsrate 48 (BK: E) auf flachem, offenem Gelände (18 im Gebirge, 12 im Wald). Kann über Gruben, Schluchten, Gewässer usw. schweben. Geschosse leichter als Felsblöcke werden vom Zyklon abgelenkt (Magisches Geschoss ist davon unberührt). Physische Angriffe gegen die Insassen nur durch Flieger oder sehr lange Waffen möglich (−3 Malus). Der Streitwagen ist immun gegen physische Angriffe. Als Waffe bei Bewegungsrate 6 oder weniger: Kreaturen mit 4 TW oder weniger müssen Rettungswurf gegen Todesmagie bestehen oder sterben. Kreaturen unter Größe R (riesig) müssen gegen Lähmung retten oder werden 1W4 Runden durchgewirbelt und dann 10W3 m weit geschleudert (10-100 % der TP als Schaden).',
  description_en = 'Conjures a whirlwind-like force of great strength beneath the wizard and up to eight man-sized creatures, lifting them up to 6.1 m high. The wizard mentally controls the chariot at movement rate 48 (MC: E) on flat, open terrain (18 in mountains, 12 in woodland). Can float over pits, chasms, water, etc. Missiles lighter than boulders are blown aside (Magic Missile unaffected). Physical attacks against occupants only by fliers or long weapons (−3 penalty). The chariot is immune to physical attack. As a weapon at movement rate 6 or less: creatures with 4 HD or less must save vs. death magic or die. Creatures below size H (huge) must save vs. paralysis or be drawn in for 1d4 rounds, then thrown 10d3 m in a random direction (10-100% of total HP as damage).'
WHERE LOWER(name_en) = LOWER('Cyclone Chariot') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Daltims Feuerschutz',
  description = 'Verleiht einem Gegenstand permanente Feuerimmunität. Der geschützte Gegenstand kann durch keinerlei Mittel verbrannt werden. Pro Stufe des Zauberkundigen kann bis zu ca. 0,03 Kubikmeter Material geschützt werden (ein Magier der 14. Stufe schützt bis zu 0,4 Kubikmeter). Nur feste Gegenstände können betroffen werden. Der Gegenstand bleibt kühl bei Berührung. Wird der Zauber auf einen tragbaren Gegenstand (Rüstung, Umhang) gewirkt, bietet dieser Schutz gegen normale Feuer — der Träger ist immun gegen Flammen, die vom Gegenstand blockiert werden. Der Träger erhält zusätzlich +2 auf Rettungswürfe gegen magisches Feuer. Materialkomponente: Eine Tinte aus rotem Drachenblut und einem zermahlenen Rubin (Wert 5.000 GM). Schutzrunen werden vor dem Wirken auf den Gegenstand gemalt und verschwinden beim Wirken.',
  description_en = 'Grants permanent fire immunity to an object. The protected object cannot be burned by any means. Up to approximately 0.03 cubic meters of material per caster level can be protected (a 14th-level wizard protects up to 0.4 cubic meters). Only solid objects can be affected. The item remains cool to the touch. If cast on a wearable item (armor, cloak), it provides protection against normal fires — the wearer is immune to flames blocked by the item. The wearer also receives +2 to saving throws against magical fire. Material component: An ink made of red dragon blood and a crushed ruby worth 5,000 gp. Protective runes are brushed onto the item before casting and disappear when the spell is cast.'
WHERE LOWER(name_en) = LOWER('Daltim''s Proof Against Fire') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Erkennen',
  description = 'Verleiht dem Empfänger (muss ein Magier mindestens der 5. Stufe sein) permanent die Fähigkeit, das Potential einer Person für mächtige Zauberei zu erkennen. Die Fähigkeit funktioniert kontinuierlich und kann durch Magie Bannen aufgehoben werden. Wird verwendet, um Mitglieder für magische Orden und Schulen zu rekrutieren. Der Empfänger erkennt magisches Potential als schwache Aura um den Kandidaten, wenn er sich innerhalb von 3 m befindet und 2 Runden normal interagiert. Die Aura ist bei hellem Licht (direktes Sonnenlicht) nicht erkennbar und durch andere Mittel (auch Wahres Sehen) nicht feststellbar. Menschen, Elfen und Halbelfen registrieren positiv bei INT 15+ und allen anderen Attributen 6+. Gnome zusätzlich bei DEX 16+. Ein positives Ergebnis garantiert nicht, dass die Person ein großer Magier wird — zeigt nur Potential.',
  description_en = 'Permanently grants the recipient (must be a wizard of at least 5th level) the ability to detect a person''s potential for powerful wizardry. Functions continuously and can be dispelled by Dispel Magic. Used to recruit members for magical orders and schools. The recipient perceives magical potential as a dim aura around the candidate when within 3 m and interacting normally for 2 rounds. The aura is imperceptible in bright light (direct sunlight) and undetectable by other means (including True Seeing). Humans, elves, and half-elves register positively with INT 15+ and all other attributes 6+. Gnomes additionally require DEX 16+. A positive result does not guarantee the person will become a great wizard — only indicates potential.'
WHERE LOWER(name_en) = LOWER('Discern') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Verdammungslegion',
  description = 'Erschafft Skelette oder Zombies aus den Überresten einer im Kampf geschlagenen Armee. Der Zauber muss am Ort des Konflikts gewirkt werden, wo die gefallenen Körper noch liegen. Nur die Körper oder Skelette der unterlegenen Seite werden belebt. Liegt der Kampf weniger als drei Monate zurück, entstehen Zombies; bei längerem Zeitraum entstehen Skelette — selbst wenn die Knochen zu Staub zerfallen sind, setzen sie sich beim Wirken wieder zusammen. Die Anzahl der Belebten hängt vom Radius (109,7 m) und der Intensität des Konflikts ab. Belebte Körper bis zu 0,9 m unter der Oberfläche graben sich innerhalb von 1 Runde aus; tiefere werden nicht belebt. Körper, die am selben Tag bewegt, durchsucht oder anderweitig gestört wurden, werden nicht belebt. Wirkzeit: 7 Runden.',
  description_en = 'Creates skeletons or zombies from the remains of a defeated army. The spell must be cast at the battle site where fallen bodies still lie. Only bodies or skeletons of the losing side are animated. If the battle occurred less than three months ago, the undead will be zombies; longer yields skeletons — even bones turned to dust reassemble. The number animated depends on the 109.7 m radius and conflict intensity. Animated bodies up to 0.9 m below the surface dig themselves out within 1 turn; deeper ones are not animated. Bodies that have been moved, searched, or disturbed on the same day are not animated. Casting time: 7 rounds.'
WHERE LOWER(name_en) = LOWER('Doom Legion') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Todestür — Drache',
  description = 'Ermöglicht einem drachischen Zauberkundigen, einen Durchgang oder ein Portal (einschließlich Höhlenöffnung oder Tunnel bis 9,1 m Durchmesser) so zu schützen, dass jede Kreatur, die ohne Befehlswort hindurchgeht, einem modifizierten Todes-Zauber unterliegt. Ein einzelnes Wirken kann bis zu 50 Trefferwürfel oder Stufen an Kreaturen töten. Jede Kreatur, die hindurchgeht, macht einen Rettungswurf gegen Stäbe mit −2; Erfolg bedeutet Überleben. Selbst bei erfolgreichem Rettungswurf werden die TW/Stufe der Kreatur vom verbleibenden Reservoir abgezogen. Hat eine Kreatur mehr TW/Stufe als im Zauber verbleiben, endet der Zauber und die Kreatur ist unbetroffen. Wirkzeit: 2 Runden.',
  description_en = 'Allows a draconic caster to ward a doorway or portal (including cave openings or tunnels up to 9.1 m diameter) so that any creature passing through without speaking a command word is subject to a modified Death spell. A single casting can kill up to 50 Hit Dice or levels of creatures. Each creature passing through makes a saving throw vs. wand at −2; success means survival. Even on a successful save, the creature''s HD/level is deducted from remaining power. If a creature has more HD/level than remain, the spell ends and the creature is unharmed. Casting time: 2 rounds.'
WHERE LOWER(name_en) = LOWER('Door of Death — Dragon') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Doppelzauber',
  description = 'Erlaubt dem Zauberkundigen, mit einem einzeln gezielten Zauber zwei Ziele statt einem zu treffen. Der betroffene Zauber muss 6. Stufe oder niedriger sein und eine einzelne Kreatur oder ein einzelnes Objekt als Ziel haben. Er muss in der Runde direkt nach dem Doppelzauber gewirkt werden, sonst ist der Doppelzauber verschwendet. Die Ziele müssen innerhalb von 9,1 m voneinander sein. Die übrigen Details des betroffenen Zaubers bleiben gleich (Reichweite, betroffene TW usw.). So kann z.B. ein Auflösungszauber, Steinhaut oder Melfs Säurepfeil auf zwei Kreaturen gleichzeitig wirken. Hat keine Wirkung auf Zauber wie Bigbys Blockierende Hand, Eiswand, Schlaf, Feuerball oder andere Zauber, die nicht direkt eine Kreatur betreffen oder bereits mehrere Ziele haben. Berührungszauber erfordern gleichzeitige Berührung beider Ziele. Materialkomponente: Ein dünner Glasstab (3-10 cm lang), den der Magier beim Wirken entzweibricht.',
  description_en = 'Allows the caster to affect two targets with a single-target spell instead of one. The affected spell must be 6th level or less targeting a single creature or object. It must be cast the round immediately after Double Dweomer, or the Double Dweomer is wasted. Targets must be within 9.1 m of each other. Other spell details remain unchanged (range, HD affected, etc.). Thus Disintegrate, Stoneskin, or Melf''s Acid Arrow can affect two creatures simultaneously. Has no effect on spells like Bigby''s Interposing Hand, Wall of Ice, Sleep, Fireball, or other spells that don''t directly target a creature or already have multiple targets. Touch-delivered spells require touching both targets simultaneously. Material component: A thin glass rod (3-10 cm long), snapped in half when casting.'
WHERE LOWER(name_en) = LOWER('Double Dweomer') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Drachenodem',
  description = 'Repräsentiert eine ganze Familie von Zaubern — für jeden Drachentyp existiert ein eigener Zauber, der separat gefunden oder erforscht werden muss. Jeder erfordert den Zahn eines Drachen des entsprechenden Typs (mindestens erwachsen). Der Zauber ermöglicht dem Magier, bis zu dreimal einen Drachenodem auszustoßen, als wäre er ein Drache des entsprechenden Typs (einmal pro Runde, keine anderen Aktionen außer Bewegung). Die genauen Effekte (Reichweite, Wirkungsbereich, Rettungswurf) entsprechen der MONSTROUS MANUAL-Beschreibung. Das „Alter" des Drachen wird durch die Stufe des Magiers bestimmt (z.B. ein Magier der 14. Stufe spuckt Säure wie ein junger schwarzer Drache und verursacht 8W4+4 Schaden). Die am weitesten verbreiteten Varianten sind Weiß, Schwarz, Grün und Blau; Rot und Kupfer sind schwer zu finden. Dauer: 3 Runden.',
  description_en = 'Represents a whole family of spells — a different spell exists for each dragon type, each requiring separate research. Each needs the tooth of its dragon type (at least adult age). The spell enables the wizard to unleash a breath weapon up to three times as if the wizard were a dragon of that sort (once per round, no actions other than movement). Precise effects (range, area, saving throw) follow the MONSTROUS MANUAL dragon description. The dragon''s "age" is determined by the wizard''s level (e.g. a 14th-level wizard spitting acid as a black dragon deals 8d4+4 damage as a juvenile). The most widely known variants are white, black, green, and blue; red and copper are hard to find. Duration: 3 rounds.'
WHERE LOWER(name_en) = LOWER('Dragon Breath') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Saugkegel — Phaerimm',
  description = 'Eine verbesserte Version des Dweomer-Wirbels, bei der die abgezogene Zauberenergie dem Wirker zugutekommt. Erschafft ein schimmerndes kegelförmiges Feld in der Luft (3 m lang, 1,2 m Radius Öffnung), das sich nach dem Willen des Wirkers bewegt (Bewegungsrate 6). Der Kegel absorbiert („trinkt") magische Wirkungsbereiche und wartende magische Fallen bei Kontakt. Kann keine Antimagiehülle oder prismatische Zauber der 5. Stufe oder höher beeinflussen. Hat keine Wirkung auf astrale Silberschnüre. Wird bei Kontakt mit Globen der Unverwundbarkeit und ähnlichen Barrieren zusammen mit diesen zerstört. Der Saugkegel kann bis zu 12 Zauberstufen absorbieren. Beim Kollabieren erhält der Wirker die absorbierten Stufen als Energie, die sofort einen einzelnen memorierten Zauber „verstärkt" — dieser wirkt dann, als wäre er von einem Magier gewirkt worden, der um die absorbierten Stufen höher ist. Magie Bannen lässt den Kegel kollabieren und wird dabei absorbiert.',
  description_en = 'An improved version of Dweomer Vortex where drained spell energy benefits the caster. Creates a shimmering conical field in midair (3 m long, 1.2 m radius opening) that moves at the caster''s will (movement rate 6). The cone absorbs ("drinks") magical areas of effect and waiting magical traps upon contact. Cannot affect Antimagic Shells or prismatic spells of 5th level or higher. Has no effect on astral silver cords. Destroyed along with Globes of Invulnerability and similar barriers upon contact. The draincone can absorb up to 12 spell levels. When it collapses, the caster receives the absorbed levels as energy that must immediately "boost" a single memorized spell — it takes effect as if cast by a wizard of 12 (or however many levels drained) levels higher. Dispel Magic collapses the cone and is absorbed.'
WHERE LOWER(name_en) = LOWER('Draincone — Phaerimm') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Geist Rufen',
  description = 'Ermöglicht dem Zauberkundigen, den Geist eines bestimmten Verstorbenen zu beschwören und zu befragen. Muss nachts gewirkt werden, innerhalb von 18,3 m vom Ort, an dem die Überreste der Kreatur liegen. Anders als Bei Toten Sprechen spielt die seit dem Tod verstrichene Zeit keine Rolle, aber der Name des Geistes muss bekannt sein. Der Geist erscheint 1W4 Runden nach dem Wirken. Der Magier kann drei Fragen stellen, plus eine weitere pro vier Stufen über 14 (vier bei Stufe 18, fünf bei 22 usw.). Der Geist ist gezwungen, wahrheitsgemäß und ohne Ausflüchte zu antworten. Es besteht eine 50%ige Chance, dass der Geist die Antwort kennt (vom SL anpassbar je nach Relevanz). Der Zauberkundige kann den Geist in die Geisterwelt schicken, um nach einer Antwort zu suchen (+20% Bonus, dauert 1 Runde bis 1 Tag). Der Zauber hält an, bis gebannt oder alle Fragen beantwortet sind. Materialkomponente: Ein Andenken, das dem Geist wichtig war.',
  description_en = 'Enables the wizard to summon the spirit of a specific deceased individual and question it. Must be cast at night, within 18.3 m of the creature''s remains. Unlike Speak with Dead, time elapsed since death does not matter, but the spirit''s name must be known. The spirit arrives 1d4 rounds after casting. The caster can ask three questions, plus one more per four levels over 14th (four at 18th, five at 22nd). The spirit is compelled to answer truthfully and without evasion. There is a 50% chance the spirit knows the answer (adjustable by DM based on relevance). The caster can command the spirit to search the spirit world for answers (+20% bonus, takes 1 turn to 1 day). The spell lasts until dispelled or all questions are answered. Material component: An item or keepsake prized by the spirit.'
WHERE LOWER(name_en) = LOWER('Call Sp') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Kontakt mit Erztyp — Drache',
  description = 'Ähnlich dem Zauber Andere Ebene Kontaktieren der 5. Stufe, ermöglicht es einem Drachen aber, einen der beiden Erztypen des Drachengeschlechts zu kontaktieren — Bahamut, den Platindrachen, oder Tiamat, den Chromatischen Drachen. Beide Mächte verabscheuen solchen Kontakt, daher werden nur kurze Antworten gegeben. Pro drei effektive Stufen (oder Bruchteil davon) kann eine Frage gestellt werden. Der Kontakt birgt das Risiko des Wahnsinns: Bahamut — 30% Wahnsinnschance, 70% Wissenschance, 90% Wahrhaftigkeitschance; Tiamat — 45% Wahnsinn, 85% Wissen, 75% Wahrhaftigkeit. Pro effektive Stufe sinkt die Wahnsinnschance um 1%. Wahnsinn dauert 2W10 Wochen. Tiamats Wahrhaftigkeitschance sinkt um 15% pro Gesinnungsschritt, der vom rechtschaffen Bösen abweicht. Kennt der Erztyp die Antwort nicht und die Wahrhaftigkeitsprüfung scheitert, wird emphatisch eine falsche Antwort gegeben.',
  description_en = 'Similar to the 5th-level Contact Other Plane spell, but allows a dragon to contact one of the two archetypes of dragonkind — Bahamut, the Platinum Dragon, or Tiamat, the Chromatic Dragon. Both powers resent such contact, so only brief answers are given. One question per three effective levels (or fraction thereof). Contact risks insanity: Bahamut — 30% insanity chance, 70% knowledge chance, 90% veracity chance; Tiamat — 45% insanity, 85% knowledge, 75% veracity. Insanity chance decreases by 1% per effective caster level. Insanity lasts 2d10 weeks. Tiamat''s veracity decreases by 15% per alignment step away from lawful evil. If the archetype doesn''t know and veracity fails, an emphatically incorrect answer is given.'
WHERE LOWER(name_en) = LOWER('_ (Divination)') AND spell_type = 'wizard';
