-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 8 (Batch 3: 12 Spells — Death Spider to Reversible)
-- Alle mechanischen Details, Materialkomponenten, Spezialfälle
-- Metrisch, eng an Originaltexten orientiert
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  name = 'Todesspinne — Drow',
  description = 'Dieser grauenhafte Zauber verwandelt eines der Gliedmaßen des Opfers augenblicklich in eine geistlose, haarige schwarze Spinne. Die Spinne dreht sich um und beginnt, das Fleisch des Opfers zu fressen (1-2 Schadenspunkte pro Runde). Alles, was von dem Glied getragen oder gehalten wird, fällt herab. Rettungswurf gegen Zauber negiert. Bei Misserfolg kann nur Fluch Brechen zusammen mit Verwandlung, Begrenzter Wunsch oder Stärkeres die Verwandlung aufheben (Magie Bannen nur innerhalb von 2 Runden wirksam). Das betroffene Glied kann abgetrennt und verbrannt werden: Innerhalb von 1 Runde nur Hand/Fuß verloren (1W4+1 Schaden + Systemschock); danach das gesamte Glied (1W12+4 Schaden + Systemschock). Eine Todesspinne hat keinen Giftbiss, frisst aber unaufhaltsam ihren Wirt. Einen Tag nachdem der Wirt vollständig gefressen ist, entwickelt die Spinne Netzspinn-, Gift- und andere Fähigkeiten einer Riesenspinne. Materialkomponente: Eine kleine lebende Spinne, ein Tropfen Verdauungssaft einer beliebigen Kreatur und ein Zahn.',
  description_en = 'This horrible spell instantly transforms one of the victim''s own limbs into a mindless, hairy black spider. The spider twists about and starts eating the victim''s flesh (1-2 damage per round). Anything worn or carried by that limb drops away. Saving throw vs. spell negates. On failure, only Remove Curse combined with Polymorph, Limited Wish, or stronger can end the condition (Dispel Magic only effective within 2 rounds). The afflicted limb can be severed and burned: within 1 round only a hand/foot is lost (1d4+1 damage + system shock); later the entire limb must go (1d12+4 damage + system shock). A death spider has no poisonous bite but inexorably consumes its entire host. One day after the host is fully eaten, the spider develops webspinning, venom, and other abilities of the spider type it resembles. Material component: A small live spider, a drop of digestive juice, and a tooth.'
WHERE LOWER(name_en) = LOWER('Death Spider — Drow') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Todesblitz — Altes Imperium',
  description = 'Sendet einen Bolzen aus Todesenergie auf ein Ziel, das jede lebende Kreatur der Materiellen Ebene sein kann. Wird das Ziel getroffen, stirbt es, wenn es keinen Rettungswurf gegen Zauber besteht. Selbst bei erfolgreichem Rettungswurf erleidet das Opfer 10W6 Schadenspunkte. Reichweite: 3 m pro Stufe. Materialkomponente: Vampir-Ichor.',
  description_en = 'Sends a bolt of death energy at a target, which may be any living creature native to the Prime Material Plane. When struck, the target dies unless it makes a successful saving throw vs. spell. Even on a successful save, the victim suffers 10d6 points of damage. Range: 3 m per level. Material component: Vampire ichor.'
WHERE LOWER(name_en) = LOWER('Deathbolt — Old Empire') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Todesschleier',
  description = 'Umgibt den Zauberkundigen mit einer dunklen, schattenhaften Aura lebensentzierender Energie von der Negativen Materiellen Ebene. Der Zauberkundige erleidet keine Nachteile. Magische Konstrukte und Untote werden nicht geschädigt und können die Aura nicht aktivieren. Der Magier kann die tödliche Kraft durch Berührung aktivieren (Angriffswurf erforderlich). Ein berührtes Wesen muss einen Rettungswurf gegen Todesmagie mit −4 bestehen oder ein schwarzer Todesnebel bildet sich: 20 % der aktuellen TP werden sofort entzogen, und am Ende jeder folgenden Runde erneut dieselbe Menge. Auch Kreaturen, die den Magier berühren oder mit Handwaffen angreifen, müssen retten (ohne Malus). Der Nebel-Effekt ist nicht kumulativ. Beendet durch: Schwere Wunden Heilen, Heilung, Begrenzter Wunsch, Wunsch oder erfolgreiche Magie Bannen. Geringere Heilzauber und Heiltränke verhindern das Fallen unter 1 TP in der Runde ihrer Anwendung. Max. Dauer: 2 Runden pro Stufe.',
  description_en = 'Surrounds the caster with a dark, shadowy aura of life-draining energy from the Negative Material Plane. The caster suffers no ill effects. Magical constructs and undead are unharmed and cannot activate the aura. The wizard activates the deadly power by touching a victim (attack roll required). A touched creature must save vs. death magic at −4 or a black death haze forms: 20% of current HP drained immediately, and the same amount again at the end of each subsequent round. Creatures touching the wizard or striking with hand-held weapons must also save (no penalty). The haze effect is not cumulative. Ended by: Cure Critical Wounds, Heal, Limited Wish, Wish, or successful Dispel Magic. Lesser cures and healing potions prevent dropping below 1 HP in the round used. Maximum duration: 2 rounds per level.'
WHERE LOWER(name_en) = LOWER('Deathshroud') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Tiefer Tauchgang',
  description = 'Verursacht erhebliche Veränderungen in der Unterwasserumgebung um den Zauberkundigen und seine Gefährten. Verbessert Reise- und Kampfbedingungen unter Wasser. Gewährt allen im Wirkungsbereich (4,6 m Radius Kugel, zentriert auf den Zauberkundigen, bewegt sich mit ihm) den Effekt von Wasseratmung für die Dauer des Zaubers. Der Zauberkundige kann die Kugel mental mit Bewegungsrate 18 durchs Wasser treiben. Wer den Bereich verlässt, während die Kugel sich bewegt, riskiert zurückgelassen zu werden und zu ertrinken. Die Bewegung erzeugt keinerlei Turbulenzen oder nennenswerte Wasserverdrängung. Dauer: 4W6 Stunden + 1 Stunde pro Stufe. Wirkzeit: 2 Runden.',
  description_en = 'Causes major changes in the underwater environment around the caster and companions. Improves traveling and fighting conditions underwater. Grants all within the area of effect (4.6 m radius sphere, centered on and moving with the caster) the effects of Water Breathing for the spell''s duration. The caster can mentally propel the sphere through water at movement rate 18. Those leaving the sphere while it''s moving risk being left behind to drown. The movement never causes turbulence or significant water displacement. Duration: 4d6 hours + 1 hour per level. Casting time: 2 rounds.'
WHERE LOWER(name_en) = LOWER('Deep Delve') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Entlauben',
  description = 'Durch diesen bösen Zauber lässt der Zauberkundige alle Vegetation im Wirkungsbereich (ca. 4,6 m Quadrat pro Stufe) welken und sterben — sie zerfällt zu schwarzer Asche. Alle Vegetation ist betroffen, vom größten Baum bis zum kleinsten Grashalm. Intelligentes Pflanzenleben wie Treants wird ebenfalls zerstört. Nur die Macht eines Wunsches oder Gleichwertiges kann die betroffene Vegetation wiederherstellen. Im betroffenen Gebiet wird kein neues Pflanzenleben für mindestens ein Jahr wachsen. Das Wirken dieses Zaubers ist eine böse Tat. Materialkomponente: S, M.',
  description_en = 'Through this evil spell, the caster causes all vegetation within the affected area (approximately 4.6 m square per level) to wither and die, crumbling into black ashes. All vegetation is affected, from the tallest tree to the tiniest blade of grass. Intelligent plant life such as treants is also destroyed. Only the power of a Wish or equivalent can restore the affected vegetation. No new plant life will grow in the affected area for at least one year. Casting this spell is an evil act. Material component: S, M.'
WHERE LOWER(name_en) = LOWER('Defoliate') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Verwüsten — Altes Imperium',
  description = 'Bewirkt, dass alle Zauber des Magiers mit verheerender Wirkung treffen. Alle Ziele erleiden −5 auf Rettungswürfe gegen die Zauber des Wirkers, und aller Zauberschaden wird um +2 pro Würfel erhöht (der Gesamtschaden kann jedoch den maximal möglichen Würfelschaden nicht übersteigen; z.B. kann ein Feuerball nur die 60 Punkte aus 10W6 verursachen). Der Zauber muss durch einen massiven Goldanhänger (Wert 100 GM) fokussiert werden, der mit dem Siegel des Zauberkundigen versehen und um den Hals getragen wird. Wird der Anhänger entfernt oder zerstört, endet der Zauber sofort. Dauer: 1 Runde pro Stufe.',
  description_en = 'Causes all of the caster''s spells to strike with devastating effect. All targets suffer −5 penalty to saving throws against the caster''s spells, and all spell damage is increased by +2 per die (but total damage cannot exceed the maximum possible rolled damage; e.g. a Fireball can only cause the 60 points possible from 10d6). The spell must be focused through a solid gold pendant (100 gp) inscribed with the caster''s sigil and worn around the neck. If the pendant is removed or destroyed, the spell ends instantly. Duration: 1 round per level.'
WHERE LOWER(name_en) = LOWER('Devastate — Old Empire') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Verzauberung Bannen',
  description = 'Eine mächtigere Version von Magie Bannen. Kann auf zwei Arten gewirkt werden: Erstens als persistentes Negationsfeld (36,6 m Radius), das Zauber innerhalb des Wirkungsbereichs für die Dauer negiert (1 Runde pro Stufe). Zweitens kann es magische Gegenstände vorübergehend neutralisieren (1 Runde pro Stufe, Berührung erforderlich). Im Negationsfeld-Modus werden alle Zauber beim Wirken oder Eintreten in den Bereich aufgehoben. Im Gegenstandsmodus verliert der Gegenstand vorübergehend alle magischen Eigenschaften. Anders als Magie Bannen hat Verzauberung Bannen eine höhere Erfolgschance und kann auch mächtige permanente Verzauberungen aufheben, die Magie Bannen nicht berührt.',
  description_en = 'A more potent version of Dispel Magic. Can be cast in two ways: First, as a persistent negation field (36.6 m radius) that negates spells cast within or entering the area of effect for the duration (1 round per level). Second, it can temporarily neutralize magical items (1 turn per level, touch required). In negation field mode, all spells are suppressed when cast or entering the area. In item mode, the item temporarily loses all magical properties. Unlike Dispel Magic, Dispel Enchantment has a higher success chance and can lift powerful permanent enchantments that Dispel Magic cannot affect.'
WHERE LOWER(name_en) = LOWER('Dispel Enchantment') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Herrschaft Stören',
  description = 'Ermöglicht dem Zauberkundigen, die Kontrolle über untote Kreaturen von einer anderen kontrollierenden Entität zu übernehmen. Die kontrollierende Entität muss einen Rettungswurf gegen Zauber ablegen. Bei Erfolg scheitert der Versuch. Bei Misserfolg hat der Zauberkundige die Untoten mit verschiedenen Negativenergie-Mustern umnebelt und die Kontrolle gestört. Die Untoten werden nicht automatisch die Diener des Zauberkundigen, aber er ist frei, seinen Willen auf sie auszuüben und in folgenden Runden die Kontrolle zu übernehmen. Dauer: Permanent. Reichweite: 6,1 m. Dieser Zauber kann nur auf der Halbebene des Schreckens erforscht werden.',
  description_en = 'Allows the caster to take control of undead creatures from another commanding entity. The controlling entity must attempt a saving throw vs. spell. On success, the disruption fails. On failure, the caster has clouded the undead with assorted negative energy patterns that disrupt control. The undead do not automatically become the caster''s minions, but the caster is free to exert will and assume control in subsequent rounds. Duration: Permanent. Range: 6.1 m. This spell can only be researched on the Demiplane of Dread.'
WHERE LOWER(name_en) = LOWER('Disrupt Dominion') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Drachenwut — Elf',
  description = 'Verändert das äußere Erscheinungsbild des Zauberkundigen nicht, verleiht ihm aber vorübergehend die Kräfte eines zufällig bestimmten Drachen. Beim Wirken wird per 1W6 der Drachentyp bestimmt (Kupfer, Messing, Bronze, Silber oder Gold) und per 1W8 das Alter (Jungtier bis Ehrwürdig). Der Zauberkundige erhält den Drachenodem, die Klauen-/Bisangriffe, die Immunität und andere Spezialfähigkeiten des bestimmten Drachen für die Dauer des Zaubers (1 Runde pro Stufe). Er behält seine eigene Rüstungsklasse und Trefferpunkte. Eingeschränkt auf Elfen, die elfische Hochmagie wirken können. Wirkzeit: 10.',
  description_en = 'Does not outwardly change the caster''s appearance, but temporarily grants the powers of a randomly determined dragon. When cast, roll 1d6 for dragon type (copper, brass, bronze, silver, or gold) and 1d8 for age (juvenile to venerable). The caster gains the determined dragon''s breath weapon, claw/bite attacks, immunity, and other special abilities for the spell''s duration (1 turn per level). The caster retains his own AC and HP. Restricted to elves able to cast Elven High Magic. Casting time: 10.'
WHERE LOWER(name_en) = LOWER('Dragonrage — Elf') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Magieverleugnung',
  description = 'Verbannt einen bestimmten Zauber für immer aus dem Geist und Verständnis eines zauberkundigen Wesens. Der Zauberkundige muss das Ziel berühren (Angriffswurf bei unwilligen Zielen). Wirkt nicht auf Nicht-Zauberkundige. Rettungswurf gegen Zauber mit −6. Bei Erfolg: Der gewählte Zauber verschwindet nur aus dem aktuellen Gedächtnis (wenn memoriert), ist aber sonst unberührt. Bei Misserfolg: Alle Erinnerungen an den Zauber sind für immer verloren — er kann nie wieder gelernt, memoriert oder von einer Schriftrolle gelesen werden. Nur Begrenzter Wunsch, Wiederherstellung oder Wunsch kann den Verlust rückgängig machen. Wirkt nur gegen einen spezifischen Zauber, nicht gegen eine ganze Schule. Z.B. könnte Feuerball verboten werden, aber nicht Flammenkugel oder Meteorschwarm.',
  description_en = 'Banishes a particular spell forever from the mind and comprehension of a spellcasting being. The caster must touch the target (attack roll for unwilling beings). Wasted on non-spellcasters. Saving throw vs. spell at −6. On success: the chosen spell vanishes from current memory only (if memorized), otherwise no effect. On failure: all memory of the spell is gone forever — it can never be learned, memorized, or read from a scroll again. Only Limited Wish, Restoration, or Wish can reverse the loss. Works only against a specific spell, not an entire school. E.g. could ban Fireball but not Flaming Sphere or Meteor Swarm.'
WHERE LOWER(name_en) = LOWER('Dweomerdeny') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Kraftskulptur',
  description = 'Die fortgeschrittenste Form der Kraftskulptur-Zauber. Das geformte Objekt kann hochkomplex sein und viele bewegliche Teile enthalten, wie z.B. eine Belagerungsmaschine oder ein Segelschiff. Teile eines simulierten Objekts können flexibel wie Seile oder scharf wie Klingen sein. Das Volumen beträgt ca. 0,76 Kubikmeter pro Stufe des Zauberkundigen. Die Skulptur kann nicht durch physische Angriffe beschädigt werden, aber durch magische Angriffe zerstört werden, die mehr Schaden verursachen als der Magier Trefferpunkte hat. Das Objekt hält 6 Runden plus 1 Runde pro Stufe. Reichweite: 27,4 m. Materialkomponente: V, S, M.',
  description_en = 'The most advanced form of the force sculpture spells. The object formed can be highly complex, containing many moving parts, such as a siege machine or sailing ship. Parts of a simulated object can be as flexible as ropes or as sharp as blades. Volume is approximately 0.76 cubic meters per caster level. The sculpture cannot be harmed by physical attacks, but can be destroyed by magical attacks dealing more damage than the caster''s hit points. The object lasts 6 turns plus 1 turn per level. Range: 27.4 m. Material component: V, S, M.'
WHERE LOWER(name_en) = LOWER('Force Sculpture') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Umkehrbar',
  description = 'Mit diesem Zauber kann ein Magier jede Vergiftung, Versalzung oder andere Verunreinigung von Wasser, Boden oder einer anderen natürlichen Substanz innerhalb des Wirkungsbereichs (ca. 0,17 Kubikmeter pro Stufe) reinigen. Alle Giftstoffe, Salze und Verunreinigungen werden sofort neutralisiert. Der gereinigte Bereich bleibt danach in seinem natürlichen, unbelasteten Zustand. Die Umkehrform des Zaubers kann sauberes Wasser oder Boden vergiften und verseuchen. Reichweite: Berührung. Wirkung: Sofort.',
  description_en = 'With this spell, a wizard can cleanse any poison, saltiness, or other contamination from water, soil, or another natural substance within the area of effect (approximately 0.17 cubic meters per level). All toxins, salts, and contaminants are instantly neutralized. The cleansed area remains in its natural, uncontaminated state afterward. The reversed form of this spell can poison and contaminate clean water or soil. Range: Touch. Effect: Instantaneous.'
WHERE LOWER(name_en) = LOWER('Reversible') AND spell_type = 'wizard';
