-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 9 (Batch 1: 11 Spells — Absorption to Brainblaze)
-- Alle mechanischen Details, Materialkomponenten, Spezialfälle
-- Metrisch, eng an Originaltexten orientiert
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  name = 'Absorption',
  description = 'Ermöglicht dem Zauberkundigen, magische Energie zu absorbieren und umzuleiten — bis zu zehn Zauberstufen. Der eingehende Zauber wird aufgehoben und seine Energie für spätere Nutzung gespeichert. Kann jeden Zauber absorbieren, außer: Flächenzauber, die nicht direkt auf den Magier gerichtet sind, Berührungsangriffe und magische Gegenstandseffekte. Priesterzauber, Schriftrollenmagie und zauberähnliche Fähigkeiten können absorbiert werden. Gespeicherte Energie kann jederzeit ausgegeben werden, um einen memorierten Zauber zu wirken, ohne ihn aus dem Gedächtnis zu löschen (Wirkzeit: 1). Überschreitet ein eingehender Zauber die verbleibende Kapazität, erhält der Magier +2 auf seinen Rettungswurf pro absorbierter Stufe (auch gegen Zauber ohne Rettungswurf; 1 scheitert immer). Der Magier kann die Absorption für eine Runde unterdrücken, um nützliche Zauber zu empfangen. Materialkomponente: Ein Amulett (Wert mind. 1.000 GM). Dauer: 5 Runden pro Stufe.',
  description_en = 'Enables the caster to absorb and redirect magical energy — up to ten spell levels. The incoming spell is nullified and its energy stored for later use. Can absorb any spell except: area spells not targeted at the caster, touch attacks, and magical device effects. Priest spells, scroll magic, and spell-like abilities can be absorbed. Stored energy can be expended at any time to cast a memorized spell without wiping it from memory (casting time: 1). If an incoming spell exceeds remaining capacity, the caster gains +2 to saving throw per absorbed level (even against spells allowing no save; 1 always fails). The caster can suppress absorption for a round to receive beneficial spells. Material component: An amulet worth at least 1,000 gp. Duration: 5 rounds per level.'
WHERE LOWER(name_en) = LOWER('Absorption') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Alamanthers Rückkehr',
  description = 'Dieser mächtige Zauber ermöglicht es dem Magier, nach seinem Tod als Geistmagier zurückzukehren. Der Zauber muss vor dem Tod gewirkt werden und verankert die Essenz des Magiers an einen bestimmten Ort oder Gegenstand. Nach dem Tod des Magiers manifestiert sich sein Geist an diesem Ort, behält seine vollen Zauberfähigkeiten und kann mit der materiellen Welt interagieren. Der Geistmagier ist untot, aber behält seinen freien Willen und seine Erinnerungen. Nur Wunsch oder vergleichbar mächtige Magie kann diesen Zustand aufheben.',
  description_en = 'This powerful spell enables the wizard to return as a spectral mage after death. The spell must be cast before death and anchors the wizard''s essence to a specific location or object. After the wizard''s death, his spirit manifests at that location, retaining full spellcasting abilities and the ability to interact with the material world. The spectral mage is undead but retains free will and memories. Only Wish or comparably powerful magic can end this state.'
WHERE LOWER(name_en) = LOWER('Alamanther''s Return') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Algarths Kampfbereitschaft',
  description = 'Auch als „Zauberkasten" bekannt — einer der wenigen Zauber, die es einem Magier erlauben, mehr als einen Zauber pro Runde zu entfesseln. Nach dem Wirken kann der Magier bis zu sechs weitere Zauber (jeder auf normalem Weg mit Komponenten usw.) speichern. Gespeicherte Zauber bleiben memoriert und verhindern das Memorieren anderer Zauber. Pro gespeichertem Zauber verliert der Magier 1W4 TP (nicht heilbar bis der Zauber gewirkt wird). Zauber jeder Stufe können gespeichert und jederzeit durch stillen Willensakt entfesselt werden — maximal zwei pro Runde. Der Magier muss bei Bewusstsein sein, muss aber weder sprechen, sich bewegen noch Materialkomponenten einsetzen. Gespeicherte Zauber können nicht einmal durch Mordenkainens Disjunktion zerstört werden und überdauern sogar den Tod des Wirkers. Materialkomponente: Vier Tropfen Wasser und ein Edelstein (Wert mind. 4.000 GM). Dauer: 1 Tag pro Stufe.',
  description_en = 'Also called the "box of spells" — one of very few known magics that allow a caster to unleash more than one spell per round. After casting, the wizard can cast up to six additional spells and store them unreleased. Stored spells remain memorized and prevent memorizing replacements. For each stored spell, the caster loses 1d4 HP (unrecoverable until the stored spell is cast). Spells of any level can be stored and unleashed by silent act of will at any time — maximum two per round. The caster must be conscious but need not speak, move, or employ material components. Stored spells cannot be destroyed even by Mordenkainen''s Disjunction and persist beyond the caster''s death. Material component: Four drops of water and a gem worth at least 4,000 gp. Duration: 1 day per level.'
WHERE LOWER(name_en) = LOWER('Algarth''s Embattlement') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Allisandros Bindender Fluch',
  description = 'Eine verbesserte Version des Permanenz-Zaubers, angepasst für Verfluchungen. Erlaubt dem Magier, einen normalerweise temporären Zauber auf ein Individuum zu wirken und permanent zu machen. Das Wirken oder der Wunsch, diesen Zauber zu lernen, ist eine böse Tat. Es gibt keine lineare Reichweitenbegrenzung, aber das Opfer muss auf derselben Ebene sein. Auf der Halbebene des Schreckens kann der Zauber niemanden außerhalb der Domäne betreffen. Zauber, die in Verbindung verwendet werden können: Antimagiehülle, Babel, Fluch, Klauen des Umberhulks, Sprachen Verwirren, Ansteckung, Emotion, Energieentzug, Vergrößern, Scheintod, Scheinuntot, Steinfaust, Unstillbarer Durst, Reizung, Levitation, Widerstand Senken, Flammen-Faust, Endloser Alptraum, Ottos Unwiderstehlicher Tanz, Verkleinern, Suggestion, Tashas Unkontrollierbares Lachen und Entsperren. Der Magier muss den verbundenen Zauber während des Wirkens mitcasten. Wirkzeit: 3 Stunden.',
  description_en = 'An improved version of Permanency adapted for laying curses. Permits the caster to make a normally temporary spell permanent upon an individual. Casting or desiring to learn this spell is an evil act. No linear range limit, but the victim must be on the same plane. On the Demiplane of Dread, cannot affect someone outside the domain. Spells usable in conjunction: Antimagic Shell, Babble, Bestow Curse, Claws of the Umber Hulk, Confuse Languages, Contagion, Emotion, Enervation, Enlarge, Feign Death, Feign Undead, Fist of Stone, Insatiable Thirst, Irritation, Levitate, Lower Resistance, Flame Fist, Neverending Nightmare, Otto''s Irresistible Dance, Reduce, Suggestion, Tasha''s Uncontrollable Hideous Laughter, and Unlock. The associated spell must be cast during the casting. Casting time: 3 hours.'
WHERE LOWER(name_en) = LOWER('Allisandro''s Binding Curse') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Alyssindras Ruf',
  description = 'Ähnelt dem Zauber Beistand der 9. Stufe, bringt aber ein unwilliges Wesen aus bis zu 160,9 km Entfernung herbei. Der Magier muss einen Gegenstand besitzen, den die gerufene Kreatur in der letzten Woche berührt hat, sowie deren Namen kennen und eine genaue Vorstellung von ihrem Aussehen haben. Ein Rettungswurf gegen Zauber negiert die Beschwörung. Der Magier kann nicht genau kontrollieren, wo das Wesen erscheint (z.B. nicht in eine Feuergrube oder Fesseln). Falls das gewünschte Ziel nicht erscheint (außer Reichweite, ungültige Komponente, erfolgreicher Rettungswurf usw.), besteht eine 50%ige Chance, versehentlich eine zufällige Kreatur von einer anderen Ebene zu beschwören (nur 1 % bei erfolgreichem Rettungswurf des Ziels).',
  description_en = 'Resembles the 9th-level Succor spell but brings an unwilling creature from up to 160.9 km away. The caster must possess an item the summoned creature touched within the last week, know the creature''s name, and have a detailed idea of their appearance. Saving throw vs. spell negates. The caster cannot precisely control where the creature appears (e.g. not into a fire pit or shackles). If the desired target doesn''t appear (out of range, invalid component, successful save, etc.), there is a 50% chance to accidentally summon a random creature from another plane (only 1% if the target simply made a successful save).'
WHERE LOWER(name_en) = LOWER('Alyssindra''s Summons') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Armee — Altes Imperium',
  description = 'Erschafft eine sofortige Armee, die in Form von Erd-, Stein- oder Sandsoldaten aus dem Boden aufsteigt. Pro vier Stufen des Zauberkundigen entsteht eine Einheit von 10 Soldaten (auf Basisstufe also 40 Soldaten). Die Einheiten müssen innerhalb eines 228,6-m-Radius erscheinen. Wenn die Zauberdauer (2 Runden pro Stufe) abläuft, verschwinden die Überlebenden. Soldatenwerte: RK 4, BW 3, TW 2, ETW0 19, 1 Angriff für 1W6+2 Schaden, nur +1 oder bessere Waffen treffen, MR 20 %, immun gegen alle Bezauberungs-Zauber, dienen nur dem Beschwörer. Materialkomponente: Ein Diamant (Wert mind. 5.000 GM), der beim Wirken zermalmt wird.',
  description_en = 'Creates an instant army rising from the ground as earth, stone, or sand soldiers. One unit of 10 soldiers per four caster levels (40 soldiers at base level). Units must appear within a 228.6 m radius. When the duration expires (2 turns per level), surviving units vanish. Soldier stats: AC 4, MV 3, HD 2, THAC0 19, 1 attack for 1d6+2 damage, +1 or better weapons to hit, MR 20%, immune to all enchantment/charm spells, serve only the summoner. Material component: A diamond worth at least 5,000 gp, crushed in casting.'
WHERE LOWER(name_en) = LOWER('Army — Old Empire') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Avissars Fluch',
  description = 'Durchdringt das berührte Wesen mit teuflischer Hitzeenergie aus Baator. Kann nur einmal pro Woche gewirkt werden. Angriffswurf zum Berühren nötig. Wirkt auf jede einzelne Kreatur, außer: Immun gegen nicht-magische Waffen = immun; Untote, Feuer- und Außerplanare unberührt; TW/Stufe über dem Magier = unberührt. Kein Rettungswurf, Magieresistenz wirkt. Effekte: TP auf 1 reduziert; ständige Qual (lebendig verbrannt, Schwitzen); erschöpft (−4 Angriff/Schaden); jede Stunde 15 % Chance, vor Schmerzen bewusstlos zu werden.',
  description_en = 'Infuses the touched creature with diabolic heat energy from Baator. Once per week only. Attack roll to touch required. Affects any single creature except: immune to non-magical weapons = immune; undead, fire-based, extraplanar unaffected; HD/level exceeding caster = unaffected. No saving throw, magic resistance applies. Effects: HP reduced to 1; constant agony (burning alive, sweating); exhausted (−4 attack/damage); each hour 15% chance to lose consciousness from pain.'
WHERE LOWER(name_en) = LOWER('Avissar''s Bane') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Schwarze Klinge der Katastrophe — Drow',
  description = 'Erschafft einen schwarzen, klingenförmigen planaren Riss (ca. 0,9 m lang), der sich nach dem Willen des Magiers bewegt (Bewegungsrate 9), solange er sehen und sich konzentrieren kann. Ohne Konzentration kollabiert die Klinge am Rundenende. Die Klinge greift 2× pro Runde mit dem ETW0 des Magiers an. Gegen Kreaturen: 2W12 Schaden pro Treffer; bei natürlicher 20 wird die Kreatur aufgelöst (nur Wunsch stellt wieder her). Durchschneidet leicht nicht-magische Gegenstände. Kann prismatische Wände, Kraftwände und alle anderen magischen Barrieren durchschneiden, sogar eine Antimagiehülle durchdringen. Gegen Gebäude: Schaden wie schwerer Katapulttreffer. Alle magischen Angriffe auf den Riss werden absorbiert. Wer die Klinge ergreifen oder physisch angreifen will, wird wie von der Klinge getroffen. Der Magier erleidet 1W2 Schaden pro eigenem Treffer (unterbricht die Konzentration nicht). Materialkomponente: V, S.',
  description_en = 'Creates a black, blade-shaped planar rift (about 0.9 m long) that moves at the caster''s will (movement rate 9) while he can see and concentrate. Without concentration, it collapses at round''s end. The blade strikes twice per round with the caster''s THAC0. Against creatures: 2d12 damage per hit; on natural 20 the creature is disintegrated (only Wish restores). Easily carves through non-magical objects. Can cut through prismatic walls, walls of force, and all other magical barriers, even penetrating Antimagic Shells. Against structures: damage as heavy catapult hit. All magical attacks on the rift are absorbed. Anyone trying to seize or physically attack the blade is struck by it. The caster suffers 1d2 damage per own hit (does not disrupt concentration). Material component: V, S.'
WHERE LOWER(name_en) = LOWER('Black Blade of Disaster — Drow') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Klinge in der Seele',
  description = 'Implantiert eine unsichtbare magische „Klinge" in der Seele des Opfers, die bei Erfüllung bestimmter Bedingungen aktiviert wird. Die Klinge verursacht enormen internen Schaden, wenn das Opfer eine vom Magier festgelegte Aktion ausführt (z.B. einen bestimmten Ort betritt, eine bestimmte Person angreift oder einen Zauber wirkt). Die Klinge bleibt verborgen und kann nur durch Wahres Sehen, Wunsch oder vergleichbare Magie entdeckt und entfernt werden. Der Schaden ist in der Regel tödlich oder extrem schwächend.',
  description_en = 'Implants an invisible magical "blade" in the victim''s soul that activates when certain conditions are met. The blade causes enormous internal damage when the victim performs an action specified by the caster (e.g. entering a specific location, attacking a certain person, or casting a spell). The blade remains hidden and can only be detected and removed by True Seeing, Wish, or comparable magic. The damage is typically lethal or extremely debilitating.'
WHERE LOWER(name_en) = LOWER('Blade in the Soul') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Blutlinie Verderben',
  description = 'Ändert die Blutlinie einer Kreatur von ihrer ursprünglichen Quelle zu der Azrais und zwingt das Subjekt, ein Awnshegh zu werden. Bildet eine Verbindung zwischen dem Wirker (oder einem anderen „Spender") und dem Empfänger. Pro drei Punkte Blutlinienstärke des Empfängers wird ein Punkt vom Wirker/Spender abgezogen. Der Empfänger behält seine aktuelle Stärke und Fähigkeiten, aber sein Blut wird Azrais Blut — er erhält den Fluch der Blutform und 1W4 Azrai-Blutlinienfähigkeiten. Reichweite: 15,2 m. Wirkzeit: 60 Stunden. Der Mantikor ist der einzige bekannte Empfänger, und der Magier der einzige bekannte Kenner des Zaubers in Cerilia.',
  description_en = 'Changes the bloodline of a creature from its original source to that of Azrai, forcing the subject to become an awnshegh. Forms a link between the caster (or another "donor") and the recipient. For every three points of bloodline strength in the recipient, one point is drained from the caster/donor. The recipient maintains current strength and abilities, but his blood becomes Azrai''s — gaining the curse of bloodform and 1d4 Azrai bloodline abilities. Range: 15.2 m. Casting time: 60 hours. The Manticore is the only known recipient, and the Magian the only wizard with knowledge of this spell in Cerilia.'
WHERE LOWER(name_en) = LOWER('Bloodline Corruption') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Gedankenflamme',
  description = 'Verwandelt den Körper des Magiers in eine Säule reiner Lebensenergie. Der Körper scheint „abzufallen" und enthüllt eine Säule aus hellem weißem Licht gleicher Höhe. Die Säule kann in der Luft schweben und ist durch nicht-magische Mittel nicht verletzbar. Flugrate 21 (BK: A). Die Säule kann keine Zauber wirken, aber einen oder mehrere Bolzen aus sich selbst auf lebende Ziele schleudern (ETW0 des Magiers). Die Anzahl der Angriffe bestimmt Schaden und Zauberentzug: Trifft ein Bolzen einen Geist mit memorierten Zaubern, stiehlt er einen zufälligen Zauber — der Magier erhält den gestohlenen Zauber und kann ihn nach dem Zauberende wirken (sofern Materialkomponenten vorhanden). Der gestohlene Zauber stammt immer von den höchsten verfügbaren Stufen. Dauer: 1 Runde.',
  description_en = 'Transforms the caster''s body into a pillar of pure life energy. The body appears to "fall away" revealing a pillar of bright white light of the same height. The pillar can float in midair and cannot be harmed by non-magical means. Flight rate 21 (MC: A). The pillar cannot cast spells but can hurl one or more bolts of itself at living targets (caster''s base THAC0). The number of attacks determines damage and spell draining: if a bolt contacts a mind containing memorized spells, it steals a random spell — the caster gains the stolen spell and can cast it after the Brainblaze expires (if material components are available). The stolen spell is always from the highest available levels. Duration: 1 round.'
WHERE LOWER(name_en) = LOWER('Brainblaze') AND spell_type = 'wizard';
