-- ═══════════════════════════════════════════════════════════════════════════════
-- WSC1 Wizard Spells Level 9 (Batch 2: 11 Spells — Call to Reversed form)
-- Alle mechanischen Details, Materialkomponenten, Spezialfälle
-- Metrisch, eng an Originaltexten orientiert
-- ═══════════════════════════════════════════════════════════════════════════════

UPDATE public.spells SET
  name = 'Ruf — Altes Imperium',
  description = 'Eine Variante des Tor-Zaubers. Lenkt die Aufmerksamkeit eines einzelnen Bewohners der Materiellen Ebene auf sich. Der Zauberkundige ruft den Namen des Wesens, das bemerkt, dass jemand es herbeirufen möchte. Das Individuum kann den Ruf annehmen oder ablehnen. Bei Annahme wird es augenblicklich fehlerfrei an einen vom Magier gewählten Ort innerhalb von 61 m teleportiert. Bei Ablehnung wird der Ruf unterdrückt. Ein Gebot-Zauber kann vorher gewirkt werden, um das Ziel zur Annahme zu überreden. Das Ziel muss dem Magier nicht bekannt sein, aber sein genauer Aufenthaltsort muss bekannt sein. Funktioniert nur auf der Materiellen Ebene (kann parallele Welten erreichen, aber nicht Äther, Astral oder andere Ebenen). Materialkomponente: Eine Miniatur-Wachsstatue des Ziels.',
  description_en = 'A variant of the Gate spell. Attracts the attention of a single Prime Material Plane native. The caster calls the being''s name, and the individual becomes aware someone wants them to appear. The individual is free to accept or reject the call. If accepted, the being is instantly teleported without error to a spot within 61 m chosen by the caster. If rejected, the call is silenced. A Demand spell can be cast prior to persuade the subject. The subject need not be known to the caster, but their exact location must be known. Only works on the Prime Material Plane (can reach parallel worlds but not Ethereal, Astral, or other planes). Material component: A miniature wax statue of the target.'
WHERE LOWER(name_en) = LOWER('Call — Old Empire') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Himmlische Armee — Elf',
  description = 'Dieser elfische Hochmagie-Zauber ist nur für die schlimmsten Notfälle reserviert, wenn die Elfenheimat selbst bedroht ist. Beim Wirken beschwört der Zauber eine Schar von Wesen der oberen Ebenen, die auf der Seite des Magiers kämpfen. Per 1W10 wird bestimmt: 1-3 Astrale Devas, 1 Licht-Aasimon, 3-18 Laternen-Archonten, 1-6 Schwert-Archonten, 5-20 Bariaur, 1 Himmlischer Lammasu, 1-3 Phönixe, 2-20 Ehrwürdige, 10W10 Einheriar oder 1 Adamantdrache. Die beschworenen Kreaturen dienen, bis der Feind besiegt oder sie getötet werden. Getötete Kreaturen verschwinden mit ihrer Ausrüstung und kehren auf ihre Heimatebene zurück. Materialkomponente: Eine Kerze, die an einem Altar aus Elfenholz verbrannt werden muss.',
  description_en = 'This Elven High Magic spell is reserved for only the most dire emergencies when the elf homeland itself is threatened. When cast, the spell summons a host of beings from the upper planes to fight on the caster''s side. Roll 1d10: 1-3 Astral Devas, 1 Light Aasimon, 3-18 Lantern Archons, 1-6 Sword Archons, 5-20 Bariaur, 1 Celestial Lammasu, 1-3 Phoenixes, 2-20 Reverend Ones, 10d10 Einheriar, or 1 Adamantine Dragon. Summoned creatures serve until the enemy is defeated or they are slain. Slain creatures vanish with gear and return to their home plane. Material component: A candle burned at an altar crafted of elfwood.'
WHERE LOWER(name_en) = LOWER('Celestial Army — Elf') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Übertragen',
  description = 'Wird normalerweise von einem Lich in Verbindung mit Diener Erschaffen gewirkt, um einen „Quasimanten" (einen Diener mit Zauberfähigkeit) zu erschaffen. Stimmt den Geist des untoten Dieners auf Zauber-Memorierung ab. Der Zauberkundige kann dann das Zauberrepertoire eines hochstufigen Magiers in den Geist des Dieners implantieren. Der Quasimant kann die implantierten Zauber nach eigenem Ermessen wirken, als wäre er der Magier. Benötigt alle Materialkomponenten. Der Zauberkundige muss Zauberenergie gleich der Stufe jedes implantierten Zaubers aufwenden. Der Quasimant erhält nur einmal Zauber — wenn alle gewirkt sind, wird er ein geistloser Untoter. Auf Lebende gewirkt verursacht der Zauber sofortigen Wahnsinn (nur durch psychische Chirurgie oder Wunsch heilbar). Materialkomponente: Der Diener und etwas Hirngewebe eines intelligenten Wesens.',
  description_en = 'Normally cast by a lich in conjunction with Create Minion to create a "quasimancer" (a minion with spellcasting ability). Attunes the undead minion''s mind to spell memorization. The caster can then implant a high-level wizard''s spell repertoire in the minion''s mind. The quasimancer can cast the implanted spells at its discretion as if it were the wizard. Requires all material components. The caster must imbue spell energy equal to each implanted spell''s level. The quasimancer receives spells only once — when all are cast, it becomes a mindless undead. Cast on a living person, it instantly causes insanity (curable only by psychic surgery or Wish). Material component: The minion and a bit of brain tissue from a sapient being.'
WHERE LOWER(name_en) = LOWER('Confer') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Feuersbrunst',
  description = 'Setzt ein lebendes Wesen in Brand und verbrennt Haare, Kleidung und mindestens die oberste Hautschicht. Das Ziel erleidet 2W6 Schaden pro Runde ohne Rettungswurf. Wesen innerhalb von 3 m müssen einen Rettungswurf gegen Zauber ablegen (Misserfolg: 2W6 Schaden, Erfolg: halber Schaden). Alle Gegenstände des Ziels müssen einen Gegenstandsrettungswurf gegen magisches Feuer mit −2 bestehen oder werden zerstört. Die Flammen entzünden alle brennbaren Gegenstände innerhalb von 3 m und schmelzen weiche Metalle. Gilt als „extrem heißes Feuer" für Feuerresistenz-Gegenstände. Das Ziel kann sich normal bewegen und kämpfen (solange es lebt), aber nicht zaubern (zauberähnliche Fähigkeiten funktionieren). Alle Wesen innerhalb von 3 m erleiden Feuerschaden. Dauer: 1 Runde pro Stufe. Reichweite: 6,1 m pro Stufe.',
  description_en = 'Sets a living creature on fire, incinerating hair, clothing, and at least the top layer of flesh. The target suffers 2d6 damage per round with no saving throw. Individuals within 3 m must save vs. spells (failure: 2d6 damage, success: half). All items carried by the target must save vs. magical fire at −2 or be destroyed. The flames ignite all flammable items within 3 m and melt soft metals. Counts as "extremely hot flame" for fire resistance devices. The target can move and fight normally while alive but cannot cast spells (spell-like abilities still function). All within 3 m are subject to fire damage. Duration: 1 round per level. Range: 6.1 m per level.'
WHERE LOWER(name_en) = LOWER('Conflagration') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Selbstbezwingung',
  description = 'Bei Abschluss dieses Initiationszaubers beginnt der Empfänger eines Aufstieg-Blockieren-Zaubers eine große persönliche Prüfung, die entweder mit seinem Tod oder der Aufhebung der Blockade und einem Erfahrungspunktebonus endet. Hat keinen anderen Zweck. Auf jemanden ohne Aufstiegsblockade gewirkt, scheitert der Zauber. Muss von einem Magier gleicher Gesinnung gewirkt werden. Der Empfänger durchleidet eine sechsstündige Prüfung mit lähmenden Schmerzen und mächtigen halluzinatorischen Visionen (wird daher meist in einem geschützten Bereich platziert). Die Visionen können gelegentlich prophetisch oder auf realen Ereignissen basierend sein. Das Ergebnis hängt von den Handlungen des Empfängers seit Erhalt der Blockade ab und erfordert einen Rettungswurf von 20, der durch verschiedene Bedingungen modifiziert wird. Keine Magie beeinflusst diesen Rettungswurf.',
  description_en = 'Upon completion, the recipient of a Block Advancement spell begins a great personal ordeal resulting in either death or removal of the block with an experience point bonus. Has no other purpose. Cast on someone without Block Advancement, the spell fails. Must be cast by a wizard of the same alignment. The recipient undergoes a six-hour ordeal of wrenching pains and powerful hallucinatory visions (usually placed in a safe area). The visions can occasionally be prophetic or based on actual events. The outcome depends on the recipient''s actions since receiving the block and requires a saving throw of 20, modified by various conditions. No magic affects this saving throw.'
WHERE LOWER(name_en) = LOWER('Conquer Self') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Todeswacht',
  description = 'Durch das Beschriften eines Durchgangs mit den verbotendsten und tödlichsten nekromantischen Runen kann ein Magier ein Portal so schützen, dass jede Kreatur ohne Befehlswort einem modifizierten Todes-Zauber unterliegt. Kann auf einen Gegenstand (meist Zauberbuch oder Phylakterium) oder einen Tunnel/Höhleneingang (max. 9,1 m Durchmesser) gewirkt werden. Nicht subtil — der geschützte Bereich ist mit komplizierten Runen bedeckt, die bei Annäherung (3 m) bedrohlich rot oder blau aufblitzen. Strahlt tödliche nekromantische Magie aus. Kann bis zu doppelt so viele TW/Stufen töten wie der Magier Stufen hat (Magier der 20. Stufe = bis zu 40 Stufen). Rettungswurf gegen Todesmagie mit −4; bei Erfolg überlebt das Wesen und die Wacht verliert keine Kraft. Bei Misserfolg sofortiger Tod (wie Todes-Zauber), TW/Stufe werden von der Kraft der Wacht abgezogen. Wirkzeit: 1 Runde.',
  description_en = 'By covering a doorway with the most forbidden and lethal necromantic runes, a wizard can protect a portal so that any creature without a command word is subject to a modified Death spell. Can be cast on an item (usually spellbook or phylactery) or tunnel/cave entrance (max 9.1 m diameter). Not subtle — the protected area is covered with intricate runes that flash ominously red or blue when approached within 3 m. Radiates lethal necromantic magic. Can kill up to twice as many HD/levels as the caster has levels (20th-level wizard = up to 40 levels). Saving throw vs. death magic at −4; on success the creature survives and the ward loses no potency. On failure, instant death (as Death spell), HD/levels subtracted from the ward''s power. Casting time: 1 turn.'
WHERE LOWER(name_en) = LOWER('Death Ward') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Fleisch Auflösen — Hexe',
  description = 'Ermöglicht der Hexe, das Fleisch einer Kreatur bei Berührung aufzulösen. Nur der lebende Körper wird betroffen — Kleidung, Ausrüstung und Knochen bleiben unversehrt. Das Opfer muss einen Rettungswurf gegen Todesmagie bestehen oder sein Fleisch löst sich auf und es stirbt augenblicklich. Bei erfolgreichem Rettungswurf erleidet das Opfer dennoch 6W6 Schadenspunkte. Berührungsangriff erforderlich. Wirkt nicht auf Untote, Konstrukte oder Wesen ohne Fleisch.',
  description_en = 'Enables the witch to dissolve a creature''s flesh on touch. Only the living body is affected — clothing, equipment, and bones remain intact. The victim must save vs. death magic or their flesh dissolves and they die instantly. On a successful save, the victim still suffers 6d6 damage. Touch attack required. Does not work on undead, constructs, or fleshless beings.'
WHERE LOWER(name_en) = LOWER('Disintegrate Flesh — Witch') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Störung',
  description = 'Erzeugt ein mächtiges Störfeld, das alle magischen Effekte in einem großen Bereich vorübergehend unterdrückt und aufhebt. Funktioniert ähnlich wie Antimagiehülle, wirkt aber auf einen viel größeren Bereich und kann auch permanente magische Effekte vorübergehend unterdrücken. Der Zauber stört alle Formen von Magie — arkane, göttliche und natürliche magische Fähigkeiten sind gleichermaßen betroffen. Magische Gegenstände funktionieren nicht im Bereich. Nach Ende des Zaubers nehmen alle unterdrückten Effekte ihren normalen Betrieb wieder auf.',
  description_en = 'Creates a powerful disruption field that temporarily suppresses and negates all magical effects in a large area. Functions similarly to Antimagic Shell but affects a much larger area and can temporarily suppress permanent magical effects. The spell disrupts all forms of magic — arcane, divine, and natural magical abilities are equally affected. Magical items do not function within the area. After the spell ends, all suppressed effects resume normal operation.'
WHERE LOWER(name_en) = LOWER('Disruption') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Drachengestalt',
  description = 'Ermöglicht dem Zauberkundigen oder einem anderen berührten Wesen, die Gestalt eines Drachentyps anzunehmen, den der Magier persönlich gesehen hat. Ein bestimmter individueller Drache (einschließlich Avatare von Drachengottheiten) kann nicht nachgeahmt werden. Kann nur auf Personen der 15. Stufe oder höher gewirkt werden. Die Person muss eine Gesinnung (Ethos oder Moral) mit der gewählten Drachenform teilen, sonst scheitert der Zauber. Die Person erhält alle Kräfte des Drachentyps: angeborene zauberähnliche Fähigkeiten, Immunitäten, Magieresistenz, Odemwaffe, Furchtaura, Sinne, Bewegung, RK, ETW0 und alle physischen Fähigkeiten. Jede Alterskategorie bis Erwachsen kann gewählt werden. Eigene Intelligenz bleibt, aber eigene memorierte Zauber können nicht gewirkt werden (Drachen-Zauberfähigkeiten möglicherweise verfügbar). Eigene Rassen- oder magische Fähigkeiten funktionieren nicht. Alle getragenen/mitgeführten Gegenstände werden Teil der Drachenform.',
  description_en = 'Enables the caster or another touched being to take the form of a dragon type the caster has personally seen. A specific individual dragon (including avatars of dragon deities) cannot be mimicked. Can only be cast on persons of 15th level or higher. The person must share one alignment (ethos or moral) with the dragon form, or the spell fails. The person acquires all powers of that dragon type: innate spell-like abilities, immunities, magic resistance, breath weapon, fear aura, senses, movement, AC, THAC0, and all physical abilities. Any age category up to adult can be chosen. Own intelligence is retained but own memorized spells cannot be cast (dragon spell abilities may become available). Own racial or magical abilities do not function. All worn/carried items become part of the dragon form.'
WHERE LOWER(name_en) = LOWER('Dragonshape') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Entzugsverdammnis — Phaerimm',
  description = 'Die mächtigste Form der Magie-Entzugszauber der Phaerimm. Erschafft ein dauerhaftes Feld, das alle magische Energie in einem großen Bereich absaugt und dem Wirker zuführt. Jeder Zauber, der im Bereich gewirkt oder hineingetragen wird, wird absorbiert. Die absorbierte Energie verstärkt die nächsten Zauber des Wirkers erheblich. Das Feld ist permanent und kann nur durch Mordenkainens Disjunktion oder einen Wunsch aufgehoben werden. Alle magischen Gegenstände im Bereich verlieren vorübergehend ihre Kraft. Magische Kreaturen erleiden 1W4 Schaden pro Runde im Feld.',
  description_en = 'The most powerful form of the Phaerimm magic-draining spells. Creates a permanent field that siphons all magical energy in a large area and feeds it to the caster. Any spell cast within or brought into the area is absorbed. The absorbed energy significantly boosts the caster''s subsequent spells. The field is permanent and can only be negated by Mordenkainens Disjunction or a Wish. All magical items in the area temporarily lose their power. Magical creatures suffer 1d4 damage per round in the field.'
WHERE LOWER(name_en) = LOWER('Draindoom — Phaerimm') AND spell_type = 'wizard';

UPDATE public.spells SET
  name = 'Kryptding Zerstören',
  description = 'Die Umkehrform von Kryptding Erschaffen. Dieser Zauber zerstört ein Kryptding (Crypt Thing) endgültig, indem er die nekromantische Energie auflöst, die es zusammenhält. Das Kryptding erhält keinen Rettungswurf, aber Magieresistenz kann den Zauber blockieren. Berührung erforderlich. Bei Erfolg zerfällt das Kryptding zu Staub. Der Zauber wirkt nur auf Kryptdinge, nicht auf andere Untote.',
  description_en = 'The reversed form of Create Crypt Thing. This spell permanently destroys a crypt thing by dissolving the necromantic energy that holds it together. The crypt thing receives no saving throw, but magic resistance can block the spell. Touch required. On success, the crypt thing crumbles to dust. The spell only works on crypt things, not other undead.'
WHERE LOWER(name_en) = LOWER('Reversed form, see create crypt thing') AND spell_type = 'wizard';
