-- ============================================================================
-- 00181_seed_monsters_core.sql
-- Seed ~200 core monsters from the AD&D 2e Monstrous Manual
-- ============================================================================

-- ============================================================================
-- HUMANOIDS (~30)
-- ============================================================================

INSERT INTO monsters (name, name_en, climate_terrain, frequency, organization, activity_cycle, diet, intelligence, treasure, alignment, ac, movement, hit_dice, hit_dice_value, thac0, attacks_per_round, damage, special_attacks, special_defenses, magic_resistance, size, morale, morale_value, xp_value, default_zone, has_ranged_attack, source_book, description) VALUES
('Kobold', 'Kobold', 'Jedes/Unterirdisch', 'common', 'Stamm', 'Nacht', 'Allesfresser', 'Durchschnittlich', 'J,O', 'LE', 7, '6', '1/2', 0.5, 20, '1', '1d4', 'Fallen', NULL, 0, 'S', 'Unsicher (2-4)', 3, 7, 'melee', FALSE, 'MM', 'Kleine, reptilienartige Humanoide, die in unterirdischen Höhlen leben und für ihre tödlichen Fallen bekannt sind.'),
('Xvart', 'Xvart', 'Gemäßigt/Hügel', 'common', 'Stamm', 'Nacht', 'Allesfresser', 'Niedrig', 'K', 'CE', 7, '6', '1', 1.0, 20, '1', '1d4+1', NULL, NULL, 0, 'S', 'Durchschnittlich (8-10)', 9, 15, 'melee', FALSE, 'MM', 'Kleine blauhäutige Humanoide, die in großen Gruppen angreifen und Ratten als Verbündete nutzen.'),
('Goblin', 'Goblin', 'Jedes/Unterirdisch', 'common', 'Stamm', 'Nacht', 'Allesfresser', 'Niedrig', 'K (C)', 'LE', 6, '6', '1-1', 0.5, 20, '1', '1d6', NULL, 'Infrarot 60''', 0, 'S', 'Durchschnittlich (7-10)', 8, 15, 'melee', FALSE, 'MM', 'Kleine, hinterhältige Humanoide die in unterirdischen Komplexen leben und größere Kreaturen als Reittiere nutzen.'),
('Orc', 'Orc', 'Jedes/Unterirdisch', 'common', 'Stamm', 'Nacht', 'Durchschnittlich', 'Durchschnittlich', 'L (C,O,Q×10,S)', 'LE', 6, '9', '1', 1.0, 19, '1', '1d8', NULL, NULL, 0, 'M', 'Durchschnittlich (8-10)', 9, 15, 'melee', FALSE, 'MM', 'Aggressive, schweinegesichtige Humanoide die in Stammesverbänden leben und häufig als Söldner dienen.'),
('Hobgoblin', 'Hobgoblin', 'Jedes/Unterirdisch', 'uncommon', 'Stamm', 'Jeder', 'Allesfresser', 'Durchschnittlich', 'J,M (D,Q×10)', 'LE', 5, '9', '1+1', 1.5, 19, '1', '1d8', NULL, NULL, 0, 'M', 'Standhaft (11-12)', 11, 35, 'melee', FALSE, 'MM', 'Disziplinierte, militärisch organisierte Humanoide die größer und stärker als Orks sind.'),
('Bugbear', 'Bugbear', 'Jedes/Unterirdisch', 'uncommon', 'Stamm', 'Jeder', 'Fleischfresser', 'Niedrig-Durchschnittlich', 'J,K (B,L,M,N)', 'CE', 5, '9', '3+1', 3.5, 17, '1', '2d4 oder nach Waffe', 'Überraschung -3', NULL, 0, 'L', 'Standhaft (11-12)', 11, 120, 'melee', FALSE, 'MM', 'Große, pelzige Humanoide die für ihre Heimlichkeit und Brutalität bei Überfällen bekannt sind.'),
('Gnoll', 'Gnoll', 'Jedes/Unterirdisch', 'uncommon', 'Stamm', 'Nacht', 'Fleischfresser', 'Niedrig', 'L,M (D,Q×5,S)', 'CE', 5, '9', '2', 2.0, 19, '1', '2d4 oder nach Waffe +2', NULL, NULL, 0, 'L', 'Standhaft (11-12)', 11, 35, 'melee', FALSE, 'MM', 'Hyänenköpfige Humanoide die in Rudeln jagen und für ihre Grausamkeit bekannt sind.'),
('Norker', 'Norker', 'Unterirdisch', 'rare', 'Stamm', 'Nacht', 'Allesfresser', 'Niedrig', 'K (O)', 'CE', 3, '9', '1+2', 1.5, 19, '1', '1d6', 'Fangzähne 1d3', NULL, 0, 'S', 'Standhaft (11-12)', 11, 35, 'melee', FALSE, 'MM', 'Entfernte Verwandte der Goblins mit extrem harter, knochiger Haut die als natürliche Rüstung dient.'),
('Lizardman', 'Lizard Man', 'Tropisch-Warm/Sumpf', 'uncommon', 'Stamm', 'Jeder', 'Allesfresser', 'Niedrig', 'D', 'N', 5, '6, Sw 12', '2+1', 2.5, 19, '1', '1d6+1', NULL, NULL, 0, 'M', 'Standhaft (11-12)', 11, 65, 'melee', FALSE, 'MM', 'Reptilienartige Humanoide die in Sümpfen und Marschen leben und primitive Stammesgesellschaften bilden.'),
('Troglodyte', 'Troglodyte', 'Unterirdisch', 'uncommon', 'Clan', 'Jeder', 'Fleischfresser', 'Niedrig', 'D', 'CE', 5, '12', '2', 2.0, 19, '3', '1d4/1d4/1d4+1', 'Gestank (SV-Gift oder -1)', 'Chamäleon-Haut', 0, 'M', 'Standhaft (11)', 11, 65, 'melee', FALSE, 'MM', 'Unterirdische Reptilien-Humanoide deren übler Gestank Feinde schwächt und die sich in Fels tarnen können.'),
('Bullywug', 'Bullywug', 'Tropisch/Sumpf', 'uncommon', 'Stamm', 'Jeder', 'Fleischfresser', 'Niedrig-Durchschnittlich', 'J,K', 'CE', 6, '3, Sw 9', '1', 1.0, 19, '3', '1d2/1d2/1d4+1', NULL, 'Sprung', 0, 'S', 'Durchschnittlich (8-10)', 9, 35, 'melee', FALSE, 'MM', 'Froschartige Humanoide die in Sümpfen leben und dort ihr Revier aggressiv gegen Eindringlinge verteidigen.'),
('Sahuagin', 'Sahuagin', 'Tropisch-Warm/Salzwasser', 'uncommon', 'Königreich', 'Nacht', 'Fleischfresser', 'Hoch', 'N (I,O,P,Q×5,S,X)', 'LE', 5, '12, Sw 24', '2+2', 2.5, 19, '1', '1d6+1 oder nach Waffe', 'Klauen/Biss im Nahkampf', NULL, 0, 'M', 'Standhaft (11-12)', 11, 175, 'melee', FALSE, 'MM', 'Gefürchtete Meeres-Humanoide mit einem unstillbaren Hass auf Oberflächenbewohner, auch "Seeteufel" genannt.'),
('Kuo-Toa', 'Kuo-Toa', 'Unterirdisch/Wasser', 'rare', 'Theokratie', 'Jeder', 'Allesfresser', 'Hoch', 'Z', 'NE', 4, '9, Sw 18', '2', 2.0, 19, '1', '2d4 oder nach Waffe', 'Blitzschlag (Peitsche)', 'Schleim (Waffen haften)', 0, 'M', 'Durchschnittlich (8-10)', 9, 65, 'melee', FALSE, 'MM', 'Fischäugige Unterirdische Kreaturen die Blibdoolpoolp verehren und über einzigartige Wahrnehmungsfähigkeiten verfügen.'),
('Drow', 'Drow', 'Unterirdisch', 'very rare', 'Clan/Haus', 'Jeder', 'Allesfresser', 'Genial-Überragend', 'N (G,W)', 'CE', 4, '12', '2', 2.0, 19, '1', 'Nach Waffe', 'Magie (Dunkelheit, Feenfeuer)', 'Magieresistenz', 50, 'M', 'Elite (13-14)', 13, 650, 'ranged', TRUE, 'MM', 'Dunkelelfen aus den Tiefen der Erde mit angeborener Magie und einer grausamen, matriarchalischen Gesellschaft.'),
('Duergar', 'Duergar', 'Unterirdisch', 'rare', 'Clan', 'Jeder', 'Allesfresser', 'Durchschnittlich-Hoch', 'M (G,Q×20)', 'LE', 4, '6', '1+2', 1.5, 19, '1', 'Nach Waffe', 'Vergrößerung, Unsichtbarkeit', 'Magieresistenz', 0, 'S', 'Elite (13-14)', 13, 175, 'melee', FALSE, 'MM', 'Graue Zwerge der Underdark die über psionische Fähigkeiten wie Vergrößerung und Unsichtbarkeit verfügen.'),
('Derro', 'Derro', 'Unterirdisch', 'rare', 'Clan', 'Jeder', 'Allesfresser', 'Hoch', 'M (I,O)', 'CE', 5, '9', '3', 3.0, 17, '1', 'Nach Waffe', 'Gift, Wahnsinn-Magie', 'Magieresistenz 30%', 30, 'S', 'Standhaft (12)', 12, 175, 'melee', FALSE, 'MM', 'Wahnsinnige Zwergenverwandte aus dem Underdark die für ihre Grausamkeit und seltsame Magie gefürchtet werden.'),
('Githyanki', 'Githyanki', 'Astral/Jedes', 'very rare', 'Monarchie', 'Jeder', 'Allesfresser', 'Außergewöhnlich', 'R,S', 'CE', 5, '12', '3+3', 3.5, 17, '1', '2d4+2 (Silberschwerter)', 'Psionische Kräfte', 'Magieresistenz', 0, 'M', 'Elite (13-14)', 13, 270, 'melee', FALSE, 'MM', 'Astrale Krieger die einst Sklaven der Illithiden waren und nun mit ihren Silberschwertern das Multiversum durchstreifen.'),
('Githzerai', 'Githzerai', 'Limbo/Jedes', 'very rare', 'Monarchie', 'Jeder', 'Allesfresser', 'Außergewöhnlich', 'R,S', 'CN', 5, '12', '3+3', 3.5, 17, '1', '1d8+2', 'Psionische Kräfte', 'Magieresistenz', 0, 'M', 'Elite (13-14)', 13, 270, 'melee', FALSE, 'MM', 'Disziplinierte Bewohner von Limbo und Todfeinde der Githyanki, die psionische Meisterschaft anstreben.'),
('Ogre', 'Ogre', 'Jedes', 'common', 'Horde', 'Jeder', 'Fleischfresser', 'Niedrig', 'B (Q×10,S)', 'CE', 5, '9', '4+1', 4.5, 17, '1', '1d10+6', NULL, NULL, 0, 'L', 'Standhaft (11-12)', 11, 270, 'melee', FALSE, 'MM', 'Große, dumme Humanoide die alles fressen was sie fangen können und oft als Söldner für intelligentere Kreaturen arbeiten.'),
('Ogermagier', 'Ogre Mage', 'Jedes/Kalt', 'rare', 'Clan', 'Jeder', 'Fleischfresser', 'Durchschnittlich-Hoch', 'E,S', 'LE', 4, '9, Fl 15', '5+2', 5.5, 15, '1', '1d12', 'Magie (Kältestrahl, Dunkelheit, Gasgestalt, Unsichtbarkeit, Polymorph)', 'Regeneration 1 HP/Runde, Flug', 0, 'L', 'Standhaft (13)', 13, 975, 'ranged', TRUE, 'MM', 'Gehörnte, blau- oder grünhäutige Oger mit angeborener Magie und der Fähigkeit die Gestalt zu wandeln.'),
('Troll', 'Troll', 'Jedes/Kalt', 'uncommon', 'Einzelgänger', 'Nacht', 'Fleischfresser', 'Niedrig', 'D', 'CE', 4, '12', '6+6', 6.5, 13, '3', '1d4+4/1d4+4/1d8+4', 'Zerfetzen (bei doppeltem Klauenhit)', 'Regeneration 3 HP/Runde', 0, 'L', 'Elite (13-14)', 13, 1400, 'melee', FALSE, 'MM', 'Schlanke, grünhäutige Riesen mit übernatürlicher Regeneration — nur Feuer und Säure können sie dauerhaft töten.'),
('Minotaurus', 'Minotaur', 'Unterirdisch', 'uncommon', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Niedrig', 'C', 'CE', 6, '12', '6+3', 6.5, 13, '2', '1d4/2d4 oder nach Waffe +3', 'Hörnerstoß bei Sturmangriff 2d4', 'Nie verirrt (Labyrinth-Sinn)', 0, 'L', 'Standhaft (12)', 12, 975, 'melee', FALSE, 'MM', 'Stierköpfige Humanoide die in Labyrinthen leben und sich dort nie verirren können.'),
('Ettin', 'Ettin', 'Kalt/Hügel', 'rare', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Niedrig', 'B,C (O,Q×10,S)', 'CE', 3, '12', '10', 10.0, 11, '2', '2d8/3d6 (zwei Keulen)', 'Überraschung nur 1 auf 1d10', NULL, 0, 'H', 'Standhaft (13)', 13, 3000, 'melee', FALSE, 'MM', 'Zweiköpfige Riesen — jeder Kopf kontrolliert einen Arm, was sie zu gefährlichen Kämpfern macht.'),
('Hügelriese', 'Hill Giant', 'Jedes/Hügel', 'uncommon', 'Stamm', 'Jeder', 'Allesfresser', 'Niedrig-Durchschnittlich', 'D', 'CE', 3, '12', '12+2', 12.5, 9, '1', '2d6+7 oder Fels 2d8', 'Felsschleudern (60 m)', NULL, 0, 'H', 'Standhaft (12)', 12, 5000, 'melee', TRUE, 'MM', 'Die kleinsten und primitivsten der echten Riesen, bekannt für ihre Brutalität und Gier.'),
('Steinriese', 'Stone Giant', 'Gemäßigt-Subtropisch/Berge', 'uncommon', 'Stamm', 'Jeder', 'Allesfresser', 'Durchschnittlich', 'D', 'N', 0, '12', '14+3', 14.5, 7, '1', '2d10 oder Fels 3d10', 'Felsschleudern (90 m)', 'Felsen fangen', 0, 'H', 'Elite (13-14)', 13, 8000, 'melee', TRUE, 'MM', 'Grauhäutige Riesen die in Bergfestungen leben und mit tödlicher Präzision Felsen schleudern.'),
('Frostriese', 'Frost Giant', 'Arktisch-Kalt/Berge', 'rare', 'Stamm', 'Jeder', 'Allesfresser', 'Niedrig-Durchschnittlich', 'E', 'CE', 0, '12', '14+4', 14.5, 7, '1', '2d8+9 oder Fels 2d10', 'Felsschleudern (60 m)', 'Kälteimmunität', 0, 'H', 'Elite (13-14)', 13, 8000, 'melee', TRUE, 'MM', 'Blauhäutige Riesen aus den eisigen Norden, immun gegen Kälte und gefürchtete Krieger.'),
('Feuerriese', 'Fire Giant', 'Warm/Berge-Vulkane', 'rare', 'Stamm', 'Jeder', 'Allesfresser', 'Durchschnittlich-Hoch', 'E', 'LE', -1, '12', '15+5', 15.5, 5, '1', '2d10+10 oder Fels 2d10', 'Felsschleudern (60 m)', 'Feuerimmunität', 0, 'H', 'Elite (13-14)', 13, 10000, 'melee', TRUE, 'MM', 'Massige, feuerrote Riesen die in Vulkanen und Schmieden leben und hervorragende Schmiede sind.'),
('Wolkenriese', 'Cloud Giant', 'Jedes/Berge-Wolken', 'very rare', 'Clan', 'Jeder', 'Allesfresser', 'Außergewöhnlich', 'E,Q×10', 'N (50% gut, 50% böse)', -1, '12', '16+7', 16.5, 3, '1', '6d6 oder Fels 2d12', 'Felsschleudern (100 m)', 'Geruchssinn', 0, 'H', 'Fanatic (15)', 15, 12000, 'melee', TRUE, 'MM', 'Majestätische Riesen die über den Wolken in schwebenden Burgen residieren und über den Sturm gebieten.'),
('Sturmriese', 'Storm Giant', 'Jedes/Berge-Meer', 'very rare', 'Einzelgänger', 'Jeder', 'Allesfresser', 'Genial', 'E,Q×20,R', 'CG', -6, '15, Sw 15', '19+7', 19.5, 3, '1', '7d6 oder Fels 3d10', 'Blitzschlag (8d8), Magie', 'Blitz/Kälteimmunität', 0, 'G', 'Fanatic (16)', 16, 16000, 'ranged', TRUE, 'MM', 'Die mächtigsten und edelsten aller Riesen, die Blitze schleudern und Stürme kontrollieren können.');

-- ============================================================================
-- UNDEAD (~20)
-- ============================================================================

INSERT INTO monsters (name, name_en, climate_terrain, frequency, organization, activity_cycle, diet, intelligence, treasure, alignment, ac, movement, hit_dice, hit_dice_value, thac0, attacks_per_round, damage, special_attacks, special_defenses, magic_resistance, size, morale, morale_value, xp_value, default_zone, has_ranged_attack, source_book, description) VALUES
('Skelett', 'Skeleton', 'Jedes', 'common', 'Gruppe', 'Nacht', 'Keins', 'Nicht intelligent', 'Keins', 'N', 7, '12', '1', 1.0, 19, '1', '1d6', NULL, 'Immun gegen Schlaf/Bezauberung, Halbschaden durch Stichwaffen', 0, 'M', 'Spezial', 12, 65, 'melee', FALSE, 'MM', 'Animierte Knochengerüste, die blind dem Willen ihres Erschaffers folgen.'),
('Zombie', 'Zombie', 'Jedes', 'common', 'Gruppe', 'Nacht', 'Keins', 'Nicht intelligent', 'Keins', 'N', 8, '6', '2', 2.0, 19, '1', '1d8', NULL, 'Immun gegen Schlaf/Bezauberung, verliert immer Initiative', 0, 'M', 'Spezial', 12, 65, 'melee', FALSE, 'MM', 'Willenlose Untote, die langsam aber unaufhaltsam ihre Opfer verfolgen.'),
('Juju-Zombie', 'Juju Zombie', 'Jedes', 'very rare', 'Einzelgänger', 'Nacht', 'Keins', 'Niedrig', 'Keins', 'NE', 6, '9', '3+12hp', 3.5, 17, '1', '3d4', 'Klettern', 'Immun gegen Feuer/Blitz/Magiemissile, +1 Waffen nötig', 0, 'M', 'Spezial', 14, 975, 'melee', FALSE, 'MM', 'Mächtige Untote die ihre Kampffähigkeiten aus dem Leben behalten und extrem schwer zu vernichten sind.'),
('Ghul', 'Ghoul', 'Jedes', 'common', 'Rudel', 'Nacht', 'Leichen', 'Niedrig', 'B,T', 'CE', 6, '9', '2', 2.0, 19, '3', '1d3/1d3/1d6', 'Paralyse (Berührung, SV-Lähmung)', 'Immun gegen Schlaf/Bezauberung', 0, 'M', 'Standhaft (12)', 12, 65, 'melee', FALSE, 'MM', 'Leichenressende Untote deren Berührung Lebende lähmt. Elfen sind immun gegen ihre Paralyse.'),
('Ghast', 'Ghast', 'Jedes', 'rare', 'Rudel', 'Nacht', 'Leichen', 'Sehr', 'B,Q,R,S,T', 'CE', 4, '15', '4', 4.0, 17, '3', '1d4/1d4/1d8', 'Paralyse (auch Elfen), Gestank', 'Immun gegen Schlaf/Bezauberung', 0, 'M', 'Standhaft (12)', 12, 650, 'melee', FALSE, 'MM', 'Mächtigere Verwandte der Ghule, deren Paralyse sogar Elfen betrifft und deren Gestank überwältigend ist.'),
('Schatten', 'Shadow', 'Jedes', 'uncommon', 'Schwarm', 'Nacht', 'Keins', 'Niedrig', 'F', 'CE', 7, '12', '3+3', 3.5, 17, '1', '1d4+1', 'Stärke-Entzug (1 Punkt pro Treffer)', '+1 Waffen nötig, Immun gegen Schlaf/Bezauberung', 0, 'M', 'Spezial', 14, 420, 'melee', FALSE, 'MM', 'Undeutliche dunkle Gestalten die an Wänden und Böden entlanggleiten und die Lebenskraft ihrer Opfer aussaugen.'),
('Wight', 'Wight', 'Jedes', 'uncommon', 'Rudel', 'Nacht', 'Keins', 'Durchschnittlich', 'B', 'LE', 5, '12', '4+3', 4.5, 15, '1', '1d4', 'Stufenentzug (1 Stufe)', 'Silber- oder Magiewaffen nötig', 0, 'M', 'Elite (14)', 14, 1400, 'melee', FALSE, 'MM', 'Hasserfüllte Untote die mit einer einzigen Berührung eine Stufe an Erfahrung rauben können.'),
('Geisterscheinung', 'Wraith', 'Jedes', 'uncommon', 'Rudel', 'Nacht', 'Keins', 'Sehr', 'E', 'LE', 4, '12, Fl 24', '5+3', 5.5, 15, '1', '1d6', 'Stufenentzug (1 Stufe)', 'Silber- oder Magiewaffen nötig, Immun gegen Schlaf/Bezauberung', 0, 'M', 'Elite (15)', 15, 2000, 'melee', FALSE, 'MM', 'Körperlose Manifestationen reinen Hasses die durch Wände gleiten und die Essenz der Lebenden verschlingen.'),
('Mumie', 'Mummy', 'Trocken/Wüste', 'rare', 'Einzelgänger', 'Nacht', 'Keins', 'Niedrig', 'D', 'LE', 3, '6', '6+3', 6.5, 13, '1', '1d12', 'Furcht (SV-Zauber), Mumienfäule', 'Nur Magiewaffen (halbiert), Immun gegen Schlaf/Bezauberung/Gift', 0, 'M', 'Elite (15)', 15, 3000, 'melee', FALSE, 'MM', 'Einbalsamierte Untote die jeden mit Mumienfäule infizieren können und nur durch Magiewaffen verwundbar sind.'),
('Gespenst', 'Spectre', 'Jedes', 'rare', 'Einzelgänger', 'Nacht', 'Keins', 'Hoch', 'Q,X', 'LE', 2, '15, Fl 30', '7+3', 7.5, 13, '1', '1d8', 'Stufenentzug (2 Stufen!)', '+1 Waffen nötig', 0, 'M', 'Champion (15-16)', 15, 4000, 'melee', FALSE, 'MM', 'Schreckliche körperlose Untote die mit jedem Treffer gleich zwei Erfahrungsstufen rauben.'),
('Vampir', 'Vampire', 'Jedes', 'rare', 'Einzelgänger', 'Nacht', 'Blut', 'Außergewöhnlich', 'F', 'CE', 1, '12, Fl 18', '8+3', 8.5, 11, '1', '5d4', 'Stufenentzug (2 Stufen), Bezauberung (Blick)', '+1 Waffen nötig, Regeneration 3 HP/Runde, Gasgestalt, Spinnenklettern', 0, 'M', 'Champion (16)', 16, 8000, 'melee', FALSE, 'MM', 'Die gefürchtetsten aller gewöhnlichen Untoten — mächtig, intelligent und nahezu unzerstörbar.'),
('Geist', 'Ghost', 'Jedes', 'very rare', 'Einzelgänger', 'Nacht', 'Keins', 'Hoch', 'E,S', 'LE', 0, 'Fl 9', '10', 10.0, 11, '1', 'Altern 10-40 Jahre', 'Magie-Glas, Besitz', 'Nur auf Ätherebene treffbar, Immun gegen Schlaf/Bezauberung', 0, 'M', 'Spezial', 14, 7000, 'melee', FALSE, 'MM', 'Ruhelose Seelen deren bloßer Anblick altern lässt und die Körper von Lebenden besitzen können.'),
('Lich', 'Lich', 'Jedes', 'very rare', 'Einzelgänger', 'Nacht', 'Keins', 'Überragend', 'A', 'NE', 0, '6', '11+', 11.0, 9, '1', '1d10', 'Paralyse-Berührung, Magie (18.+ Stufe)', '+1 Waffen nötig, Immun gegen Schlaf/Bezauberung/Kälte', 0, 'M', 'Fanatic (18)', 18, 12000, 'ranged', TRUE, 'MM', 'Untote Magier von unvorstellbarer Macht die ihre Seele in einem Phylakterium verwahren.'),
('Banshee', 'Banshee', 'Jedes', 'very rare', 'Einzelgänger', 'Nacht', 'Keins', 'Außergewöhnlich', 'D', 'CE', 0, 'Fl 15', '7', 7.0, 13, '1', '1d8', 'Todesschrei (SV-Tod oder sterben)', '+1 Waffen nötig, Magieresistenz 50%', 50, 'M', 'Fanatic (18)', 18, 4000, 'melee', FALSE, 'MM', 'Geisterhafte Elfengestalten deren markerschütternder Schrei sofortigen Tod bringen kann.'),
('Revenant', 'Revenant', 'Jedes', 'very rare', 'Einzelgänger', 'Nacht', 'Keins', 'Außergewöhnlich', 'Keins', 'N', 10, '9', '8', 8.0, 13, '1', '2d8', 'Paralyse (Blick, SV-Lähmung)', 'Regeneration, Immun gegen Schlaf/Bezauberung, +1 Waffen nötig', 0, 'M', 'Fanatic (20)', 20, 5000, 'melee', FALSE, 'MM', 'Rachsüchtige Untote die von ihren Gräbern auferstehen um ihren Mörder zu finden und zu vernichten.'),
('Skelettritter', 'Skeleton Warrior', 'Jedes', 'very rare', 'Einzelgänger', 'Jeder', 'Keins', 'Genial', 'Keins', 'NE', 2, '6', '9+12hp', 9.5, 11, '1', 'Nach Waffe', 'Kampffähigkeit eines Kämpfers', '+1 Waffen nötig, Immun gegen Schlaf/Bezauberung/Kälte, Zaubern', 90, 'M', 'Fanatic (20)', 20, 8000, 'melee', FALSE, 'MM', 'Mächtige untote Krieger die einst Lords waren und nun dazu verdammt sind für immer zu kämpfen.'),
('Kryptenwächter', 'Crypt Thing', 'Jedes', 'rare', 'Einzelgänger', 'Jeder', 'Keins', 'Sehr', 'Keins', 'N', 3, '12', '6', 6.0, 15, '1', '1d8', 'Teleportation von Eindringlingen', 'Immun gegen Schlaf/Bezauberung', 0, 'M', 'Spezial', 14, 975, 'melee', FALSE, 'MM', 'Skeletthafter Wächter der Toten der Grabräuber durch Teleportation verwirrt und vertreibt.'),
('Huecuva', 'Huecuva', 'Jedes', 'rare', 'Einzelgänger', 'Nacht', 'Keins', 'Niedrig', 'Keins', 'CE', 3, '9', '2', 2.0, 19, '1', '1d6', 'Krankheit (SV-Gift)', 'Immun gegen Schlaf/Bezauberung, +1 Waffen nötig', 0, 'M', 'Standhaft (12)', 12, 270, 'melee', FALSE, 'MM', 'Untote abtrünnige Priester die als Strafe für ihren Glaubensbruch verdammt wurden.'),
('Todesritter', 'Death Knight', 'Jedes', 'very rare', 'Einzelgänger', 'Jeder', 'Keins', 'Genial', 'Keins', 'CE', 0, '12', '9+11', 9.5, 11, '1', '2d8+6 (Zweihandschwert)', 'Feuerball 1/Tag (20d6), Machtwort Töten, Furcht-Aura', 'Magieresistenz 75%, +1 Waffen nötig', 75, 'M', 'Fanatic (20)', 20, 14000, 'melee', FALSE, 'MM', 'Ehemals edle Ritter die durch unheilige Macht als untote Schrecken auferstanden sind — fast so mächtig wie Lichs.'),
('Poltergeist', 'Poltergeist', 'Jedes', 'rare', 'Einzelgänger', 'Nacht', 'Keins', 'Niedrig', 'Keins', 'LE', 0, 'Fl 6', '1/2', 0.5, 20, '0', '-', 'Telekinese (Gegenstände schleudern 1d4)', 'Unsichtbar, +1 Waffen nötig', 0, 'S', 'Durchschnittlich (8-10)', 9, 120, 'ranged', TRUE, 'MM', 'Unsichtbare Geister die Gegenstände durch die Luft schleudern und Lebende terrorisieren.');

-- ============================================================================
-- DRAGONS (~15)
-- ============================================================================

INSERT INTO monsters (name, name_en, climate_terrain, frequency, organization, activity_cycle, diet, intelligence, treasure, alignment, ac, movement, hit_dice, hit_dice_value, thac0, attacks_per_round, damage, special_attacks, special_defenses, magic_resistance, size, morale, morale_value, xp_value, default_zone, has_ranged_attack, source_book, description) VALUES
('Weißer Drache (Jung)', 'White Dragon (Young)', 'Arktisch', 'rare', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Niedrig', 'Spezial', 'CE', 3, '12, Fl 40, Sw 12', '6', 6.0, 15, '3', '1d4/1d4/2d8', 'Frostatem (Kegel, 7d6+1)', NULL, 0, 'L', 'Champion (15-16)', 15, 3000, 'melee', TRUE, 'MM', 'Der kleinste und dümmste der chromatischen Drachen — lebt in eisigen Höhlen und friert Beute mit seinem Frostodem ein.'),
('Weißer Drache (Erwachsen)', 'White Dragon (Adult)', 'Arktisch', 'rare', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Niedrig', 'Spezial', 'CE', 0, '12, Fl 40, Sw 12', '10', 10.0, 11, '3', '1d6/1d6/3d6', 'Frostatem (Kegel, 12d6+4)', 'Kälteimmunität', 0, 'H', 'Fanatic (17)', 17, 8000, 'melee', TRUE, 'MM', 'Ein ausgewachsener Weißer Drache, mächtig genug eine ganze Siedlung in Eis zu hüllen.'),
('Schwarzer Drache (Erwachsen)', 'Black Dragon (Adult)', 'Tropisch/Sumpf', 'uncommon', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Durchschnittlich', 'Spezial', 'CE', -1, '12, Fl 30, Sw 12', '12', 12.0, 9, '3', '1d6/1d6/3d8', 'Säureatem (Linie, 12d4+4)', 'Säureimmunität', 0, 'H', 'Fanatic (17)', 17, 10000, 'melee', TRUE, 'MM', 'Hinterhältiger Sumpfdrache der Säure speit und mit dunkler List Schätze hortet.'),
('Grüner Drache (Erwachsen)', 'Green Dragon (Adult)', 'Subtropisch/Wald', 'uncommon', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Sehr', 'Spezial', 'CE', -2, '9, Fl 30, Sw 9', '13', 13.0, 7, '3', '1d8/1d8/2d10', 'Giftatem (Wolke, 14d6+5)', 'Giftimmunität', 0, 'H', 'Fanatic (17)', 17, 12000, 'melee', TRUE, 'MM', 'Gerissener Walddrache der seine Beute durch Manipulation und seinen tödlichen Giftadem vernichtet.'),
('Blauer Drache (Erwachsen)', 'Blue Dragon (Adult)', 'Trocken/Wüste', 'rare', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Sehr', 'Spezial', 'LE', -3, '9, Fl 30, Br 4', '15', 15.0, 5, '3', '1d8/1d8/3d8', 'Blitzatem (Linie, 16d8+8)', 'Blitzimmunität', 0, 'H', 'Fanatic (18)', 18, 14000, 'ranged', TRUE, 'MM', 'Eitelster der chromatischen Drachen, herrscht über Wüsten und schleudert vernichtende Blitze.'),
('Roter Drache (Erwachsen)', 'Red Dragon (Adult)', 'Berge/Hügel', 'rare', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Außergewöhnlich', 'Spezial', 'CE', -4, '9, Fl 30, Jp 3', '17', 17.0, 3, '3', '1d10/1d10/3d10', 'Feueratem (Kegel, 18d10+9)', 'Feuerimmunität', 0, 'G', 'Fanatic (19)', 19, 18000, 'melee', TRUE, 'MM', 'Der mächtigste und gierigste aller chromatischen Drachen — sein Feuerodem kann eine kleine Armee vernichten.'),
('Golddrache (Erwachsen)', 'Gold Dragon (Adult)', 'Jedes', 'very rare', 'Einzelgänger', 'Jeder', 'Allesfresser', 'Genial', 'Spezial', 'LG', -4, '12, Fl 40, Sw 12', '17', 17.0, 3, '3', '1d10/1d10/6d6', 'Feuer-/Gasatem, Zauber', 'Feuerimmunität, Polymorph', 0, 'G', 'Fanatic (19)', 19, 20000, 'ranged', TRUE, 'MM', 'Weisester und mächtigster aller metallischen Drachen, oft in menschlicher Gestalt unterwegs.'),
('Silberdrache (Erwachsen)', 'Silver Dragon (Adult)', 'Gemäßigt/Berge', 'very rare', 'Einzelgänger', 'Jeder', 'Allesfresser', 'Genial', 'Spezial', 'LG', -3, '9, Fl 30, Jp 3', '16', 16.0, 5, '3', '1d8/1d8/5d6', 'Frost-/Paralyse-Atem, Zauber', 'Kälteimmunität, Polymorph', 0, 'G', 'Fanatic (19)', 19, 16000, 'ranged', TRUE, 'MM', 'Freundlichster der metallischen Drachen, lebt oft unter Menschen in verwandelter Gestalt.'),
('Bronzedrache (Erwachsen)', 'Bronze Dragon (Adult)', 'Tropisch/Küste', 'rare', 'Einzelgänger', 'Jeder', 'Allesfresser', 'Außergewöhnlich', 'Spezial', 'LG', -3, '9, Fl 30, Sw 12', '15', 15.0, 5, '3', '1d8/1d8/4d6', 'Blitz-/Abstoßungs-Atem, Zauber', 'Blitzimmunität, Polymorph', 0, 'H', 'Fanatic (18)', 18, 14000, 'ranged', TRUE, 'MM', 'Neugieriger Küstendrache der sich oft in die Angelegenheiten der Sterblichen einmischt.'),
('Kupferdrache (Erwachsen)', 'Copper Dragon (Adult)', 'Trocken/Berge', 'rare', 'Einzelgänger', 'Jeder', 'Allesfresser', 'Hoch', 'Spezial', 'CG', -2, '9, Fl 30, Jp 3', '14', 14.0, 7, '3', '1d6/1d6/5d4', 'Säure-/Verlangsamungs-Atem, Zauber', 'Säureimmunität', 0, 'H', 'Fanatic (17)', 17, 12000, 'ranged', TRUE, 'MM', 'Witzig und verspielt — Kupferdrachen lieben Rätsel und Scherzfragen über alles.'),
('Messingdrache (Erwachsen)', 'Brass Dragon (Adult)', 'Trocken/Wüste', 'rare', 'Einzelgänger', 'Jeder', 'Allesfresser', 'Hoch', 'Spezial', 'CG', -1, '12, Fl 30, Br 6', '13', 13.0, 7, '3', '1d6/1d6/4d4', 'Feuer-/Schlaf-Atem, Zauber', 'Feuerimmunität', 0, 'H', 'Fanatic (17)', 17, 10000, 'ranged', TRUE, 'MM', 'Gesprächigster aller Drachen — sie reden sogar mit ihren Gegnern bevor sie angreifen.'),
('Schattendrache', 'Shadow Dragon', 'Schattenebene/Unterirdisch', 'very rare', 'Einzelgänger', 'Nacht', 'Fleischfresser', 'Genial', 'Spezial', 'CE', -1, '12, Fl 30', '14', 14.0, 7, '3', '1d8/1d8/2d10', 'Schattenodem (Energie-Entzug)', 'Im Schatten nahezu unsichtbar, +2 Waffen nötig', 0, 'H', 'Fanatic (17)', 17, 14000, 'melee', TRUE, 'MM', 'Seltene Drachen die auf der Schattenebene jagen und Lebensenergie mit ihrem Odem rauben.'),
('Dracolich', 'Dracolich', 'Jedes', 'very rare', 'Einzelgänger', 'Jeder', 'Keins', 'Genial', 'Spezial', 'CE', -4, '6, Fl 30', '17', 17.0, 3, '3', '1d10/1d10/3d10', 'Drachenodem, Paralyse-Berührung, Furcht-Aura', 'Wie Drache + Untoten-Immunitäten, +1 Waffen nötig', 0, 'G', 'Fanatic (20)', 20, 22000, 'melee', TRUE, 'MM', 'Ein untoter Drache von verheerender Macht — vereint die Stärke eines Drachen mit der Unzerstörbarkeit eines Lichs.'),
('Drachenschildkröte', 'Dragon Turtle', 'Tropisch-Gemäßigt/Salzwasser', 'very rare', 'Einzelgänger', 'Jeder', 'Allesfresser', 'Sehr', 'R,S,T,V', 'N', -3, 'Sw 9', '14-16', 15.0, 5, '3', '2d6/2d6/4d8', 'Dampfatem (Wolke, 20d6)', 'Unterwasser', 0, 'G', 'Fanatic (17)', 17, 14000, 'melee', TRUE, 'MM', 'Riesige Meereskreaturen die ganze Schiffe mit einem einzigen Dampfstoß vernichten können.'),
('Wyvern', 'Wyvern', 'Gemäßigt/Berge', 'uncommon', 'Rudel', 'Jeder', 'Fleischfresser', 'Niedrig', 'E', 'NE', 3, '6, Fl 24', '7+7', 7.5, 13, '2', '2d8/1d6+Gift', 'Giftstachel (SV-Gift oder Tod)', 'Flug', 0, 'L', 'Standhaft (12)', 12, 2000, 'melee', FALSE, 'MM', 'Zweibeinge Drachenverwandte mit einem tödlichen Giftstachel am Schwanz.');

-- ============================================================================
-- ABERRATIONS & PLANAR (~20)
-- ============================================================================

INSERT INTO monsters (name, name_en, climate_terrain, frequency, organization, activity_cycle, diet, intelligence, treasure, alignment, ac, movement, hit_dice, hit_dice_value, thac0, attacks_per_round, damage, special_attacks, special_defenses, magic_resistance, size, morale, morale_value, xp_value, default_zone, has_ranged_attack, typical_spells, source_book, description) VALUES
('Betrachter', 'Beholder', 'Unterirdisch', 'rare', 'Einzelgänger', 'Jeder', 'Allesfresser', 'Außergewöhnlich', 'I,S,T', 'LE', 0, 'Fl 3', '12+12', 12.5, 7, '1', '2d4 (Biss)', 'Anti-Magiestrahl, 10 Augenstiele (Desintegration, Todesstrahl, etc.)', 'Anti-Magie-Zentralauge', 0, 'L', 'Fanatic (18)', 18, 14000, 'ranged', TRUE, '["charm person","charm monster","sleep","telekinesis","flesh to stone","disintegrate","fear","slow","cause serious wounds","death ray"]'::jsonb, 'MM', 'Schwebende Kugel mit einem riesigen Auge und zehn Augenstielen — eine der tödlichsten Kreaturen der Unterwelt.'),
('Illithid', 'Mind Flayer', 'Unterirdisch', 'rare', 'Gemeinschaft', 'Jeder', 'Gehirne', 'Genial', 'S,T,X', 'LE', 5, '12', '8+4', 8.5, 11, '4', '1d2×4', 'Gedankenexplosion (SV-Zauber), Gehirn-Extraktion', 'Magieresistenz 90%', 90, 'M', 'Champion (15)', 15, 9000, 'ranged', TRUE, '["charm monster","ESP","levitate","suggestion","domination","plane shift"]'::jsonb, 'MM', 'Tentakelgesichtige Psioniker die von den Gehirnen intelligenter Wesen leben — Herren des Underdark.'),
('Aboleth', 'Aboleth', 'Unterirdisch/Wasser', 'rare', 'Einzelgänger', 'Jeder', 'Allesfresser', 'Hoch-Genial', 'F', 'LE', 4, '3, Sw 18', '8', 8.0, 13, '4', '1d6×4', 'Schleimumwandlung, Versklavung (SV-Zauber)', 'Schleim-Schild', 0, 'H', 'Fanatic (17)', 17, 5000, 'melee', FALSE, '[]'::jsonb, 'MM', 'Uralte amphibische Wesen die sogar älter sind als die Götter und ganze Zivilisationen versklaven.'),
('Umber Hulk', 'Umber Hulk', 'Unterirdisch', 'rare', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Durchschnittlich', 'G', 'CE', 2, '6, Br 1-6', '8+8', 8.5, 11, '3', '3d4/3d4/1d10', 'Verwirrender Blick (SV-Zauber)', 'Panzerung', 0, 'L', 'Elite (13)', 13, 4000, 'melee', FALSE, '[]'::jsonb, 'MM', 'Massige Tunnelbauer mit verwirrenden Facettenaugen und mächtigen Grabklauen.'),
('Rostmonster', 'Rust Monster', 'Unterirdisch', 'uncommon', 'Einzelgänger', 'Nacht', 'Metall', 'Animalisch', 'Keins', 'N', 2, '18', '5', 5.0, 15, '2', '0', 'Berührung rostet Metall (Rüstung & Waffen)', NULL, 0, 'M', 'Unsicher (2-4)', 3, 270, 'melee', FALSE, '[]'::jsonb, 'MM', 'Alptraum jedes Kriegers — ein insektenartiges Wesen das Metallausrüstung bei Berührung zu Rost zerfallen lässt.'),
('Aasräuber', 'Carrion Crawler', 'Unterirdisch', 'uncommon', 'Einzelgänger', 'Jeder', 'Aas', 'Nicht intelligent', 'B', 'N', 3, '12', '3+1', 3.5, 17, '8', '0 (Paralyse)', '8 Tentakel (SV-Lähmung bei jedem Treffer)', NULL, 0, 'L', 'Spezial', 9, 420, 'melee', FALSE, '[]'::jsonb, 'MM', 'Riesiges wurmartiges Wesen mit acht paralysierenden Tentakeln — ein häufiger Bewohner von Verliesen.'),
('Otyugh', 'Otyugh', 'Unterirdisch', 'uncommon', 'Einzelgänger', 'Jeder', 'Abfall', 'Niedrig', 'D', 'N', 3, '6', '6', 6.0, 15, '3', '1d8/1d8/1d4+1', 'Krankheit (bei Biss)', NULL, 0, 'L', 'Durchschnittlich (7-10)', 8, 975, 'melee', FALSE, '[]'::jsonb, 'MM', 'Dreibeinge Abfallbeseitiger mit Tentakelklauen die in Müllhaufen und Abwässern leben.'),
('Gibbernder Schlund', 'Gibbering Mouther', 'Unterirdisch', 'rare', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Niedrig-Durchschnittlich', 'Keins', 'CN', 1, '3', '4+3', 4.5, 17, '6+', '1 (pro Mund)', 'Gibbern (Verwirrung, SV-Zauber), Boden erweichen', 'Amorph (Halbschaden von Stich)', 0, 'M', 'Standhaft (12)', 12, 2000, 'melee', FALSE, '[]'::jsonb, 'MM', 'Ein ständig plappernder Haufen aus Augen und Mündern, der den Boden unter seinen Opfern erweicht.'),
('Cloaker', 'Cloaker', 'Unterirdisch', 'uncommon', 'Einzelgänger', 'Nacht', 'Fleischfresser', 'Hoch', 'C', 'CN', 3, '1, Fl 15', '6', 6.0, 15, '2', '1d6/Spezial', 'Umhüllen (automatisch 1d4+Stärkeentzug), Stöhnen', 'Illusionen, Schattenmanipulation', 0, 'L', 'Standhaft (12)', 12, 975, 'melee', FALSE, '[]'::jsonb, 'MM', 'Mantelförmige Kreaturen die an Höhlendecken lauern und sich auf ahnungslose Opfer stürzen.'),
('Hakengrausamkeit', 'Hook Horror', 'Unterirdisch', 'uncommon', 'Clan', 'Jeder', 'Allesfresser', 'Niedrig', 'D', 'N', 1, '9', '5', 5.0, 15, '3', '1d8/1d8/1d6', NULL, 'Geierschrei-Kommunikation', 0, 'L', 'Standhaft (11-12)', 11, 650, 'melee', FALSE, '[]'::jsonb, 'MM', 'Insektenartige Höhlenbewohner mit mächtigen Hakenklauen — kommunizieren durch klopfende Geräusche.'),
('Piercer', 'Piercer', 'Unterirdisch', 'uncommon', 'Kolonie', 'Jeder', 'Fleischfresser', 'Nicht intelligent', 'Keins', 'N', 3, '1', '1-4', 2.5, 19, '1', '1d6-4d6 (nach HD)', 'Fallattacke', NULL, 0, 'M', 'Durchschnittlich (8-10)', 9, 65, 'melee', FALSE, '[]'::jsonb, 'MM', 'Stalaktitenartige Kreaturen die sich von Höhlendecken auf Beute fallen lassen.'),
('Roper', 'Roper', 'Unterirdisch', 'rare', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Außergewöhnlich', 'D', 'CE', 0, '3', '12', 12.0, 9, '1', '5d4', '6 Stränge (STR-Entzug, 15 m Reichweite)', 'Magieresistenz 80%', 80, 'L', 'Fanatic (16)', 16, 10000, 'ranged', TRUE, '[]'::jsonb, 'MM', 'Stalagmitenartige Kreaturen die mit sechs klebrigen Strängen Beute heranziehen und verschlingen.'),
('Bulette', 'Bulette', 'Gemäßigt/Hügel', 'rare', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Animalisch', 'Keins', 'N', -2, '14, Br 3', '9', 9.0, 11, '3', '4d12/3d6/3d6', 'Sprung (2,5 m hoch)', NULL, 0, 'H', 'Standhaft (11)', 11, 6000, 'melee', FALSE, '[]'::jsonb, 'MM', 'Der "Landhai" — ein gepanzerter Erdräuber der alles frisst was sich bewegt.'),
('Xorn', 'Xorn', 'Erdebene/Unterirdisch', 'rare', 'Einzelgänger', 'Jeder', 'Minerale', 'Durchschnittlich', 'O,P,Q,U', 'N', -2, '9, Br 9', '7+7', 7.5, 13, '4', '1d3/1d3/1d3/6d4', 'Durch Erde gleiten', 'Immun gegen Feuer/Kälte, Halbschaden von Blitz', 0, 'M', 'Durchschnittlich (8-10)', 9, 4000, 'melee', FALSE, '[]'::jsonb, 'MM', 'Dreiarmige Kreaturen der Elementarebene der Erde die sich von Edelsteinen und Metall ernähren.'),
('Dao', 'Dao', 'Erdebene', 'very rare', 'Sultanat', 'Jeder', 'Erde, Edelsteine', 'Hoch-Genial', 'Keins', 'NE', 3, '9, Fl 15, Br 6', '8+3', 8.5, 11, '1', '3d6', 'Magie (Wandversteinerung, Erdbeben, etc.)', 'Magieresistenz 30%', 30, 'L', 'Standhaft (13)', 13, 5000, 'melee', TRUE, '["dig","passwall","wall of stone","transmute rock to mud"]'::jsonb, 'MM', 'Gierige Erdgeister die Schätze horten und Sterbliche gerne zu Sklavenarbeit zwingen.'),
('Dschinn', 'Djinni', 'Luftebene', 'very rare', 'Kalifat', 'Jeder', 'Keins', 'Genial', 'Keins', 'CG', 4, '9, Fl 24', '7+3', 7.5, 13, '1', '2d8', 'Magie (Wirbelwind, Gasgestalt, Illusion, Unsichtbarkeit)', 'Magieresistenz 20%', 20, 'L', 'Elite (13-14)', 13, 3000, 'ranged', TRUE, '["create food and water","create soft goods","create wooden items","wind wall","gaseous form","invisibility"]'::jsonb, 'MM', 'Edle Luftgeister die für ihre Wunscherfüllung und großmütige Art bekannt sind.'),
('Efrit', 'Efreeti', 'Feuerebene', 'very rare', 'Sultanat', 'Jeder', 'Keins', 'Genial', 'Keins', 'LE', 2, '9, Fl 24', '10', 10.0, 11, '1', '3d8', 'Magie (Feuerwand, Pyrotechnik, Gasgestalt, Vergrößerung)', 'Magieresistenz 25%', 25, 'L', 'Elite (13-14)', 13, 5000, 'ranged', TRUE, '["wall of fire","produce flame","pyrotechnics","enlarge","gaseous form","grant up to 3 wishes"]'::jsonb, 'MM', 'Mächtige und tyrannische Feuergeister die in der Stadt des Messings auf der Feuerebene herrschen.'),
('Marid', 'Marid', 'Wasserebene', 'very rare', 'Einzelgänger', 'Jeder', 'Keins', 'Genial', 'Keins', 'CN', 5, '9, Sw 24', '13', 13.0, 7, '1', '5d6', 'Magie (Wasserstrahl, Nebel, Gasgestalt)', 'Magieresistenz 25%', 25, 'L', 'Champion (15-16)', 15, 10000, 'ranged', TRUE, '["lower water","part water","water breathing","wall of fog","gaseous form"]'::jsonb, 'MM', 'Mächtigste der Genies — arrogante Wassergeister die Sterbliche als amüsante Ablenkung betrachten.'),
('Rakshasa', 'Rakshasa', 'Tropisch/Dschungel', 'rare', 'Einzelgänger', 'Nacht', 'Fleischfresser', 'Sehr', 'F', 'LE', -4, '15', '7', 7.0, 13, '3', '1d3/1d3/2d4', 'Illusion (ESP, Suggestion)', 'Immun gegen Zauber unter 8. Stufe, +1 Waffen nötig', 0, 'M', 'Fanatic (16)', 16, 4000, 'melee', FALSE, '["ESP","suggestion"]'::jsonb, 'MM', 'Gestaltwandelnde Tiger-Dämonen aus der indischen Mythologie die durch gesegnete Armbrustbolzen getötet werden.'),
('Yugoloth (Mezzoloth)', 'Yugoloth (Mezzoloth)', 'Untere Ebenen', 'common', 'Trupp', 'Jeder', 'Fleischfresser', 'Niedrig', 'Keins', 'NE', 5, '12', '5', 5.0, 15, '2', '1d4+1/1d4+1', 'Magie (Dunkelheit, Teleportation)', 'Magieresistenz 25%, +1 Waffen nötig', 25, 'L', 'Durchschnittlich (8-10)', 9, 1400, 'melee', FALSE, '["darkness","teleport without error"]'::jsonb, 'MM', 'Insektenartige Fußsoldaten der neutralen bösen Ebenen, als Söldner in den Blutkriegen eingesetzt.');

-- ============================================================================
-- BEASTS & ANIMALS (~20)
-- ============================================================================

INSERT INTO monsters (name, name_en, climate_terrain, frequency, organization, activity_cycle, diet, intelligence, treasure, alignment, ac, movement, hit_dice, hit_dice_value, thac0, attacks_per_round, damage, special_attacks, special_defenses, magic_resistance, size, morale, morale_value, xp_value, default_zone, has_ranged_attack, source_book, description) VALUES
('Riesenratte', 'Giant Rat', 'Jedes', 'common', 'Rudel', 'Nacht', 'Allesfresser', 'Halb-', 'C', 'NE', 7, '12, Sw 6', '1/2', 0.5, 20, '1', '1d3', 'Krankheit (5%)', NULL, 0, 'T', 'Unsicher (2-4)', 3, 7, 'melee', FALSE, 'MM', 'Scheue aber aggressive Nager die in großen Rudeln leben und gefährliche Krankheiten übertragen.'),
('Schrecklicher Wolf', 'Dire Wolf', 'Kalt-Gemäßigt', 'uncommon', 'Rudel', 'Jeder', 'Fleischfresser', 'Halb-', 'Keins', 'N', 6, '18', '4+4', 4.5, 17, '1', '2d4', NULL, NULL, 0, 'M', 'Unsicher (8)', 8, 175, 'melee', FALSE, 'MM', 'Massige prähistorische Wölfe, doppelt so groß wie normale Wölfe und deutlich aggressiver.'),
('Riesenspinne', 'Giant Spider', 'Jedes', 'common', 'Kolonie', 'Jeder', 'Fleischfresser', 'Niedrig', 'J,K', 'CE', 4, '3, Wb 12', '4+4', 4.5, 17, '1', '1d8+Gift', 'Gift (SV-Gift oder Tod)', 'Netze', 0, 'L', 'Durchschnittlich (8-10)', 9, 650, 'melee', FALSE, 'MM', 'Riesige, intelligente Spinnen die Netze spinnen und Beute mit tödlichem Gift lähmen.'),
('Riesenskorpion', 'Giant Scorpion', 'Trocken/Wüste', 'uncommon', 'Einzelgänger', 'Nacht', 'Fleischfresser', 'Nicht intelligent', 'Keins', 'N', 3, '15', '5+5', 5.5, 15, '3', '1d10/1d10/1d4+Gift', 'Gift (SV-Gift oder Tod)', NULL, 0, 'L', 'Standhaft (11)', 11, 975, 'melee', FALSE, 'MM', 'Riesige Wüstenskorpione deren Schwanzstachel sofortigen Tod durch Gift verursachen kann.'),
('Riesentausendfüßler', 'Giant Centipede', 'Jedes', 'common', 'Schwarm', 'Jeder', 'Fleischfresser', 'Nicht intelligent', 'Keins', 'N', 9, '15', '1/4', 0.25, 20, '1', '0', 'Gift (schwach, +4 auf SV)', NULL, 0, 'T', 'Unsicher (2-4)', 3, 7, 'melee', FALSE, 'MM', 'Kleine giftige Tausendfüßler deren Biss zwar schmerzhaft aber selten tödlich ist.'),
('Riesenwespe', 'Giant Wasp', 'Gemäßigt-Tropisch', 'uncommon', 'Nest', 'Tag', 'Allesfresser', 'Animalisch', 'Keins', 'N', 4, '6, Fl 21', '4', 4.0, 17, '2', '2d4/1d4+Gift', 'Gift (SV-Gift -4 oder Paralyse)', 'Flug', 0, 'M', 'Standhaft (11)', 11, 420, 'melee', FALSE, 'MM', 'Aggressive Riesenwespen die Beute paralysieren und in ihr Nest verschleppen.'),
('Stirge', 'Stirge', 'Jedes', 'common', 'Schwarm', 'Nacht', 'Blut', 'Animalisch', 'D', 'N', 8, '3, Fl 18', '1+1', 1.5, 19, '1', '1d3', 'Blut saugen (1d4/Runde nach Treffer)', 'Flug', 0, 'T', 'Durchschnittlich (8-10)', 9, 35, 'melee', FALSE, 'MM', 'Blutsaugende Flugwesen die sich an Opfer heften und Blut trinken bis sie platzen oder das Opfer verblutet.'),
('Roc', 'Roc', 'Jedes/Berge', 'rare', 'Einzelgänger', 'Tag', 'Allesfresser', 'Animalisch', 'C', 'N', 4, '3, Fl 30', '18', 18.0, 3, '3', '3d6/3d6/4d6', 'Entführung', 'Flug', 0, 'G', 'Standhaft (12)', 12, 12000, 'melee', FALSE, 'MM', 'Legendäre Riesenvögel die Elefanten davontragen können und auf den höchsten Berggipfeln nisten.'),
('Greif', 'Griffon', 'Gemäßigt-Tropisch/Berge', 'uncommon', 'Schwarm', 'Tag', 'Fleischfresser', 'Halb-', 'C,S', 'N', 3, '12, Fl 30', '7', 7.0, 13, '3', '1d4/1d4/2d8', NULL, 'Flug', 0, 'L', 'Standhaft (11-12)', 11, 975, 'melee', FALSE, 'MM', 'Majestätische Kreaturen mit dem Körper eines Löwen und den Flügeln und dem Kopf eines Adlers.'),
('Hippogryph', 'Hippogriff', 'Gemäßigt-Tropisch/Berge', 'uncommon', 'Schwarm', 'Tag', 'Allesfresser', 'Halb-', 'Keins', 'N', 5, '18, Fl 36', '3+3', 3.5, 17, '3', '1d6/1d6/1d10', NULL, 'Flug', 0, 'L', 'Standhaft (11)', 11, 270, 'melee', FALSE, 'MM', 'Halbpferd-Halbadler-Wesen die als edle Reittiere geschätzt werden.'),
('Pegasus', 'Pegasus', 'Jedes', 'rare', 'Herde', 'Tag', 'Pflanzenfresser', 'Durchschnittlich', 'Keins', 'CG', 6, '24, Fl 48', '4', 4.0, 17, '3', '1d8/1d8/1d3', NULL, 'Flug, nur von Guten reitbar', 0, 'L', 'Standhaft (11-12)', 11, 420, 'melee', FALSE, 'MM', 'Geflügelte Pferde die sich nur von aufrichtigen Helden reiten lassen.'),
('Einhorn', 'Unicorn', 'Gemäßigt/Wald', 'rare', 'Herde', 'Tag', 'Pflanzenfresser', 'Durchschnittlich', 'Keins', 'CG', 2, '24', '4+4', 4.5, 15, '3', '1d6/1d6/1d12', 'Teleportation, Heilung', 'Immun gegen Gift, Bezauberung, Todesmagie', 0, 'L', 'Elite (14)', 14, 1400, 'melee', FALSE, 'MM', 'Edle magische Geschöpfe deren Horn heilen und Gift neutralisieren kann — Symbol der Reinheit.'),
('Nachtmahr', 'Nightmare', 'Untere Ebenen', 'rare', 'Einzelgänger', 'Jeder', 'Keins', 'Hoch', 'Keins', 'NE', -4, '15, Fl 36', '6+6', 6.5, 13, '3', '2d4+2/2d4+2/2d4', 'Feueratem (Nebel, SV-Zauber), brennende Hufe', 'Astral-/Ätherreise', 0, 'L', 'Fanatic (17)', 17, 3000, 'melee', FALSE, 'MM', 'Schwarze Pferde mit flammenden Mähnen und Hufen — Reittiere mächtiger Böser auf den unteren Ebenen.'),
('Winterwolf', 'Winter Wolf', 'Arktisch', 'rare', 'Rudel', 'Jeder', 'Fleischfresser', 'Durchschnittlich', 'Keins', 'NE', 5, '18', '6', 6.0, 15, '1', '2d4', 'Frostatem (Kegel, 6d4)', 'Kälteimmunität', 0, 'L', 'Standhaft (12)', 12, 975, 'melee', TRUE, 'MM', 'Intelligente Eiswölfe die Frosthauch speien und die Sprache anderer Wesen verstehen.'),
('Warg', 'Worg', 'Gemäßigt/Wald', 'uncommon', 'Rudel', 'Nacht', 'Fleischfresser', 'Niedrig', 'Keins', 'NE', 6, '12', '4+4', 4.5, 17, '1', '2d4', NULL, NULL, 0, 'L', 'Standhaft (11)', 11, 270, 'melee', FALSE, 'MM', 'Riesige, bösartige Wölfe die ihre eigene Sprache sprechen und oft als Reittiere für Goblins dienen.'),
('Riesenadler', 'Giant Eagle', 'Berge', 'rare', 'Horst', 'Tag', 'Fleischfresser', 'Durchschnittlich', 'Keins', 'NG', 7, '3, Fl 48', '4', 4.0, 17, '3', '1d6/1d6/2d6', 'Sturzflug +4 Schaden', 'Flug', 0, 'L', 'Standhaft (12)', 12, 270, 'melee', FALSE, 'MM', 'Riesige intelligente Adler die ihre eigene Sprache sprechen und oft als Boten des Guten dienen.'),
('Rieseneule', 'Giant Owl', 'Gemäßigt/Wald', 'rare', 'Einzelgänger', 'Nacht', 'Fleischfresser', 'Durchschnittlich', 'Keins', 'NG', 6, '3, Fl 18', '4', 4.0, 17, '3', '2d4/2d4/1d4+1', 'Überraschungsangriff (+6 auf Überraschung)', 'Flug, Nachtsicht', 0, 'L', 'Standhaft (12)', 12, 420, 'melee', FALSE, 'MM', 'Weise riesige Eulen die nachts nahezu lautlos fliegen und gelegentlich mit Waldbewohnern sprechen.'),
('Höhlenbär', 'Cave Bear', 'Kalt-Gemäßigt/Höhlen', 'uncommon', 'Einzelgänger', 'Jeder', 'Allesfresser', 'Halb-', 'Keins', 'N', 6, '12', '6+6', 6.5, 13, '3', '1d8/1d8/1d12', 'Umarmung (2d8 bei doppeltem Klauenhit)', NULL, 0, 'L', 'Standhaft (12)', 12, 975, 'melee', FALSE, 'MM', 'Riesige prähistorische Bären die in Höhlen leben und alles angreifen was ihr Revier betritt.'),
('Wildschwein', 'Wild Boar', 'Jedes', 'common', 'Einzelgänger', 'Jeder', 'Allesfresser', 'Animalisch', 'Keins', 'N', 7, '15', '3+3', 3.5, 17, '1', '3d4', 'Weiterkämpfen bei 0 bis -7 HP', NULL, 0, 'S', 'Standhaft (12)', 12, 175, 'melee', FALSE, 'MM', 'Aggressive Wildschweine die selbst tödlich verwundet weiterkämpfen und niemals fliehen.'),
('Rieseneidechse', 'Giant Lizard', 'Tropisch/Sumpf', 'uncommon', 'Einzelgänger', 'Tag', 'Fleischfresser', 'Nicht intelligent', 'Keins', 'N', 5, '15', '3+1', 3.5, 17, '1', '1d8', NULL, NULL, 0, 'L', 'Standhaft (12)', 12, 120, 'melee', FALSE, 'MM', 'Große Raubeidechsen die in tropischen Regionen lauern und blitzschnell zuschlagen.');

-- ============================================================================
-- DEMONS & DEVILS (~15)
-- ============================================================================

INSERT INTO monsters (name, name_en, climate_terrain, frequency, organization, activity_cycle, diet, intelligence, treasure, alignment, ac, movement, hit_dice, hit_dice_value, thac0, attacks_per_round, damage, special_attacks, special_defenses, magic_resistance, size, morale, morale_value, xp_value, default_zone, has_ranged_attack, typical_spells, source_book, description) VALUES
('Imp', 'Imp', 'Jedes', 'rare', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Durchschnittlich', 'Keins', 'LE', 2, '6, Fl 18', '2+2', 2.5, 19, '1', '1d4+Gift', 'Gift (SV-Gift -2 oder Tod)', 'Regeneration 1 HP/Runde, Polymorph, +1 Waffen nötig', 25, 'T', 'Durchschnittlich (7)', 7, 650, 'melee', FALSE, '["suggestion"]'::jsonb, 'MM', 'Winzige teuflische Vertraute die Hexenmeistern dienen und böse Ratschläge flüstern.'),
('Quasit', 'Quasit', 'Jedes', 'rare', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Niedrig', 'Keins', 'CE', 2, '6, Fl 15', '3', 3.0, 17, '3', '1d2/1d2/1d4', 'Gift (SV-Gift oder DEX -1 permanent)', 'Regeneration 1 HP/Runde, Polymorph, +1 Waffen nötig', 25, 'T', 'Durchschnittlich (7)', 7, 420, 'melee', FALSE, '["fear"]'::jsonb, 'MM', 'Dämonische Vertraute — klein, bösartig und fähig Gift und Furcht zu verbreiten.'),
('Lemure', 'Lemure', 'Neun Höllen', 'common', 'Schwarm', 'Jeder', 'Keins', 'Halb-', 'Keins', 'LE', 7, '3', '2', 2.0, 19, '1', '1d3', NULL, 'Regeneration 1 HP/Runde', 0, 'M', 'Unsicher (5)', 5, 65, 'melee', FALSE, '[]'::jsonb, 'MM', 'Formlose, geistlose Höllengeburten — die niedrigsten aller Teufel, aus verlorenen Seelen geformt.'),
('Dretch', 'Dretch', 'Abyss', 'common', 'Horde', 'Jeder', 'Keins', 'Niedrig', 'Keins', 'CE', 6, '9', '2', 2.0, 19, '3', '1d4/1d4/1d4+1', 'Gestank (SV-Gift oder Übelkeit)', 'Teleportation', 0, 'S', 'Unsicher (5-7)', 6, 65, 'melee', FALSE, '["scare","stinking cloud","teleport without error"]'::jsonb, 'MM', 'Niederste Dämonen des Abyss — feige, stinkend und nur in Massen gefährlich.'),
('Babau', 'Babau', 'Abyss', 'uncommon', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Niedrig', 'Keins', 'CE', 3, '15', '6+6', 6.5, 13, '3', '1d4+1/1d4+1/2d4', 'Säure-Schleim (1d6 an Angreifer)', '+1 Waffen nötig', 50, 'M', 'Standhaft (13)', 13, 4000, 'melee', FALSE, '["darkness","dispel magic","fear","heat metal","levitate"]'::jsonb, 'MM', 'Skelettartige Assassinen-Dämonen deren schleimige Haut Angreifern Säureschaden zufügt.'),
('Vrock', 'Vrock', 'Abyss', 'uncommon', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Niedrig', 'Keins', 'CE', 0, '12, Fl 18', '8', 8.0, 13, '5', '1d4/1d4/1d8/1d8/1d6', 'Sporenausstoß, Schreiender Tanz', '+1 Waffen nötig', 70, 'L', 'Standhaft (14)', 14, 6000, 'melee', FALSE, '["darkness","detect magic","mass charm","mirror image","telekinesis","teleport without error"]'::jsonb, 'MM', 'Geierartige Dämonen die tödliche Sporen verbreiten und mit ihrem Kreischen betäuben.'),
('Hezrou', 'Hezrou', 'Abyss', 'uncommon', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Niedrig', 'Keins', 'CE', -2, '6', '9', 9.0, 11, '3', '1d4/1d4/4d4', 'Gestank (SV-Gift oder -2 auf Angriffe)', '+2 Waffen nötig', 60, 'L', 'Standhaft (14)', 14, 8000, 'melee', FALSE, '["blink","darkness","detect magic","teleport without error"]'::jsonb, 'MM', 'Krötenartige Dämonen deren widerlicher Gestank alle Gegner in der Nähe schwächt.'),
('Glabrezu', 'Glabrezu', 'Abyss', 'uncommon', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Hoch', 'Keins', 'CE', -7, '15', '10', 10.0, 11, '5', '2d6/2d6/1d3/1d3/1d4+1', 'Wunschgewährung (Verderben)', '+2 Waffen nötig', 60, 'H', 'Elite (14-15)', 14, 12000, 'melee', FALSE, '["chaos","confusion","darkness","detect magic","dispel magic","mirror image","power word stun","reverse gravity","teleport without error"]'::jsonb, 'MM', 'Vierscherige Verführer-Dämonen die sterbliche Magier mit Wünschen korrumpieren.'),
('Nalfeshnee', 'Nalfeshnee', 'Abyss', 'rare', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Hoch', 'Keins', 'CE', -4, '9, Fl 15', '11', 11.0, 9, '3', '1d4/1d4/2d4', 'Licht des Untergangs (SV-Zauber oder Verwirrung)', '+2 Waffen nötig', 65, 'H', 'Fanatic (16)', 16, 12000, 'melee', TRUE, '["detect magic","dispel magic","call lightning","feeblemind","slow","project image","symbol","teleport without error","wall of fire"]'::jsonb, 'MM', 'Massige Affen-Eber-Dämonen die über die Seelen der Verdammten im Abyss richten.'),
('Marilith', 'Marilith', 'Abyss', 'very rare', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Genial', 'Keins', 'CE', -7, '15', '12', 12.0, 9, '7', '6× Waffe + 2d4 (Umschlingung)', 'Umschlingung (Schlangenkörper)', '+2 Waffen nötig', 70, 'L', 'Fanatic (17)', 17, 16000, 'melee', FALSE, '["animate dead","cause serious wounds","cloudkill","detect magic","project image","teleport without error"]'::jsonb, 'MM', 'Sechsarmige Schlangendämoninnen — brillante Strategen und tödliche Kämpferinnen in einem.'),
('Balor', 'Balor', 'Abyss', 'very rare', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Genial', 'Keins', 'CE', -8, '15, Fl 36', '13', 13.0, 7, '1', '2d6+6 (Flammenklinge)', 'Feuer-Aura (4d6 im Umkreis), Blitzschlag, Todesexplosion', '+3 Waffen nötig', 70, 'H', 'Fanatic (18)', 18, 20000, 'melee', TRUE, '["darkness","detect magic","dispel magic","fear","fire storm","gate","pyrotechnics","suggestion","symbol","telekinesis","teleport without error","wall of fire"]'::jsonb, 'MM', 'Die mächtigsten Dämonen — gewaltige Feuerwesen mit Flammenschwertern und Peitschen, Fürsten des Abyss.'),
('Grubenteufel', 'Pit Fiend', 'Neun Höllen', 'rare', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Genial', 'Keins', 'LE', -5, '15, Fl 24', '13', 13.0, 7, '6', '1d4/1d4/1d6/2d6/2d4/1d4+2', 'Gift (SV-Tod), Furcht-Aura, Feuerball 1/Runde', '+3 Waffen nötig, Regeneration 2 HP/Runde', 50, 'L', 'Fanatic (18)', 18, 20000, 'melee', TRUE, '["detect magic","detect invisibility","fireball","hold person","improved invisibility","polymorph self","produce flame","pyrotechnics","wall of fire","meteor swarm (1/day)","symbol (1/day)"]'::jsonb, 'MM', 'Mächtigste der normalen Teufel — riesige geflügelte Schrecken die über Legionen der Hölle gebieten.'),
('Erinye', 'Erinyes', 'Neun Höllen', 'uncommon', 'Einzelgänger', 'Jeder', 'Keins', 'Hoch', 'Keins', 'LE', 2, '12, Fl 21', '6+6', 6.5, 13, '1', '2d4 (Schwert)', 'Seil der Verstrickung', 'Magieresistenz 30%, +1 Waffen nötig', 30, 'M', 'Elite (13-14)', 13, 4000, 'melee', FALSE, '["charm person","detect magic","fear","invisibility","teleport without error"]'::jsonb, 'MM', 'Verführerische Teuflinnen die mit Stricken der Verstrickung und betörender Schönheit jagen.'),
('Knochenteufel', 'Bone Devil', 'Neun Höllen', 'uncommon', 'Einzelgänger', 'Jeder', 'Keins', 'Hoch', 'Keins', 'LE', -1, '15', '9+9', 9.5, 11, '1', '3d4 (Stachel)', 'Gift (SV-Gift oder STR-Verlust)', '+2 Waffen nötig, Magieresistenz 40%', 40, 'L', 'Fanatic (16)', 16, 8000, 'melee', FALSE, '["detect magic","detect invisibility","fear","fly","generate ice","wall of ice","teleport without error"]'::jsonb, 'MM', 'Skeletthafte Teufel mit einem giftigen Schwanzstachel — sadistische Aufseher der Höllenarmeen.'),
('Eisteufel', 'Ice Devil', 'Neun Höllen', 'uncommon', 'Einzelgänger', 'Jeder', 'Keins', 'Hoch', 'Keins', 'LE', -4, '6', '11', 11.0, 9, '4', '1d4/1d4/2d4/3d4', 'Kälte-Aura (-10 im Umkreis)', '+2 Waffen nötig, Magieresistenz 55%, Regeneration', 55, 'L', 'Fanatic (17)', 17, 12000, 'melee', FALSE, '["detect magic","detect invisibility","fly","gate","ice storm","wall of ice","teleport without error"]'::jsonb, 'MM', 'Eisige Kriegsherren der Hölle die eine Aura bitterster Kälte verbreiten.');

-- ============================================================================
-- CONSTRUCTS & GOLEMS (~10)
-- ============================================================================

INSERT INTO monsters (name, name_en, climate_terrain, frequency, organization, activity_cycle, diet, intelligence, treasure, alignment, ac, movement, hit_dice, hit_dice_value, thac0, attacks_per_round, damage, special_attacks, special_defenses, magic_resistance, size, morale, morale_value, xp_value, default_zone, has_ranged_attack, source_book, description) VALUES
('Lebende Rüstung', 'Animated Armor', 'Jedes', 'rare', 'Einzelgänger', 'Jeder', 'Keins', 'Nicht intelligent', 'Keins', 'N', 3, '9', '4', 4.0, 17, '1', '1d8', NULL, 'Immun gegen Schlaf/Bezauberung/Gift', 0, 'M', 'Spezial', 12, 270, 'melee', FALSE, 'MM', 'Magisch animierte Rüstungen die lautlos Eindringlinge angreifen und schwer von normaler Ausrüstung zu unterscheiden sind.'),
('Lehmgolem', 'Clay Golem', 'Jedes', 'very rare', 'Einzelgänger', 'Jeder', 'Keins', 'Nicht intelligent', 'Keins', 'N', 7, '7', '11', 11.0, 9, '1', '3d10', 'Verfluchte Wunden (heilen nur durch Heilen-Zauber)', 'Immun gegen die meiste Magie, +1 Waffen nötig', 100, 'L', 'Spezial', 20, 8000, 'melee', FALSE, 'MM', 'Aus heiliger Erde geschaffene Golems deren Schläge verfluchte Wunden hinterlassen die nicht normal heilen.'),
('Steingolem', 'Stone Golem', 'Jedes', 'very rare', 'Einzelgänger', 'Jeder', 'Keins', 'Nicht intelligent', 'Keins', 'N', 5, '6', '14', 14.0, 7, '1', '3d8', 'Verlangsamungs-Aura (3 m)', 'Immun gegen die meiste Magie, +2 Waffen nötig', 100, 'L', 'Spezial', 20, 12000, 'melee', FALSE, 'MM', 'Massive Steinstatuen die zum Leben erweckt wurden und eine verlangsamende Aura ausstrahlen.'),
('Eisengolem', 'Iron Golem', 'Jedes', 'very rare', 'Einzelgänger', 'Jeder', 'Keins', 'Nicht intelligent', 'Keins', 'N', 3, '6', '18', 18.0, 3, '1', '4d10', 'Giftgas-Atem (3 m Radius, 1/7 Runden)', 'Immun gegen alle Magie außer Blitz/Feuer, +3 Waffen nötig', 100, 'L', 'Spezial', 20, 16000, 'melee', FALSE, 'MM', 'Die mächtigsten Golems — unzerstörbare Eisenkolosse die giftiges Gas ausatmen.'),
('Fleischgolem', 'Flesh Golem', 'Jedes', 'very rare', 'Einzelgänger', 'Jeder', 'Keins', 'Halb-', 'Keins', 'N', 9, '8', '9', 9.0, 11, '2', '2d8/2d8', 'Berserker (Chance bei Schaden)', 'Immun gegen die meiste Magie, +1 Waffen nötig, Blitze heilen', 100, 'L', 'Spezial', 20, 4000, 'melee', FALSE, 'MM', 'Aus Leichenteilen zusammengeflickte Kreaturen — berüchtigt durch die Geschichte von Frankensteins Monster.'),
('Schildwächter', 'Shield Guardian', 'Jedes', 'very rare', 'Einzelgänger', 'Jeder', 'Keins', 'Halb-', 'Keins', 'N', 2, '9', '10+3', 10.5, 11, '2', '1d8+4/1d8+4', NULL, 'Schadensteilung mit Meister, Zauberspeicher', 0, 'L', 'Spezial', 20, 6000, 'melee', FALSE, 'MM', 'Magische Konstrukte die durch ein Amulett an ihren Meister gebunden sind und dessen Schaden teilen.'),
('Gargoyle', 'Gargoyle', 'Jedes', 'uncommon', 'Rudel', 'Jeder', 'Fleischfresser', 'Niedrig', 'M×10', 'CE', 5, '9, Fl 15', '4+4', 4.5, 15, '4', '1d3/1d3/1d6/1d4', NULL, '+1 Waffen nötig', 0, 'M', 'Standhaft (11-12)', 11, 650, 'melee', FALSE, 'MM', 'Steinerne Kreaturen die sich als Statuen tarnen und ahnungslose Opfer aus dem Hinterhalt überfallen.'),
('Behelmter Schrecken', 'Helmed Horror', 'Jedes', 'very rare', 'Einzelgänger', 'Jeder', 'Keins', 'Hoch', 'Keins', 'N', 2, '12, Fl 12', '4+8', 4.5, 15, '1', '1d8+4', 'Schwebend, Zauberspeicherung', 'Immun gegen 3 bestimmte Zauber', 0, 'M', 'Fanatic (20)', 20, 1400, 'melee', FALSE, 'MM', 'Magisch animierte Rüstungen mit eigenem Willen — weitaus gefährlicher als gewöhnliche Animierte Rüstungen.'),
('Vogelscheuche', 'Scarecrow', 'Jedes', 'rare', 'Einzelgänger', 'Nacht', 'Keins', 'Nicht intelligent', 'Keins', 'CE', 6, '6', '5', 5.0, 15, '1', '1d6+Faszinierender Blick', 'Faszinierender Blick (SV-Zauber)', 'Immun gegen Schlaf/Bezauberung, Feuer-Schwäche', 0, 'M', 'Spezial', 14, 650, 'melee', FALSE, 'MM', 'Magisch belebte Vogelscheuchen die ihre Opfer mit einem Blick fesseln und dann vernichten.'),
('Homunculus', 'Homunculus', 'Jedes', 'rare', 'Einzelgänger', 'Jeder', 'Keins', 'Niedrig', 'Keins', 'N', 6, '6, Fl 18', '2', 2.0, 19, '1', '1d3+Schlaf', 'Schlafgift (SV-Gift -2)', 'Telepathischer Link zum Meister', 0, 'T', 'Durchschnittlich (7)', 7, 35, 'melee', FALSE, 'MM', 'Winzige Konstrukte die als magische Vertraute und Spione für Zauberer dienen.');

-- ============================================================================
-- FEY & SHAPESHIFTERS (~10)
-- ============================================================================

INSERT INTO monsters (name, name_en, climate_terrain, frequency, organization, activity_cycle, diet, intelligence, treasure, alignment, ac, movement, hit_dice, hit_dice_value, thac0, attacks_per_round, damage, special_attacks, special_defenses, magic_resistance, size, morale, morale_value, xp_value, default_zone, has_ranged_attack, source_book, description) VALUES
('Doppelgänger', 'Doppelganger', 'Jedes', 'uncommon', 'Einzelgänger', 'Jeder', 'Allesfresser', 'Sehr', 'E', 'N', 5, '9', '4', 4.0, 17, '1', '1d12', 'Gedankenlesen (ESP)', 'Immun gegen Schlaf/Bezauberung, Gestaltwandel', 0, 'M', 'Elite (13-14)', 13, 420, 'melee', FALSE, 'MM', 'Gestaltwandler die jede humanoide Erscheinung annehmen und Gedanken lesen können um ihre Tarnung zu perfektionieren.'),
('Mimic', 'Mimic', 'Unterirdisch', 'rare', 'Einzelgänger', 'Jeder', 'Allesfresser', 'Durchschnittlich-Hoch', 'Keins', 'N', 7, '3', '7-8', 7.5, 13, '1', '3d4', 'Klebend (festgeklebt, STR-Check zum Lösen)', 'Tarnung als Objekt', 0, 'L', 'Durchschnittlich (8-10)', 9, 1400, 'melee', FALSE, 'MM', 'Gestaltwandler die sich als Truhen, Türen oder andere Objekte tarnen und Abenteurer verschlingen.'),
('Werwolf', 'Werewolf', 'Jedes', 'uncommon', 'Rudel', 'Nacht', 'Fleischfresser', 'Durchschnittlich', 'B', 'CE', 5, '15', '5+1', 5.5, 15, '1', '2d4', 'Lykanthropie (bei Biss)', 'Nur Silber- oder +1 Waffen', 0, 'M', 'Standhaft (12)', 12, 420, 'melee', FALSE, 'MM', 'Die bekanntesten Lykanthropen — bei Vollmond verwandeln sie sich in rasende Wolfsmenschen.'),
('Werrate', 'Wererat', 'Jedes/Städtisch', 'uncommon', 'Rudel', 'Nacht', 'Allesfresser', 'Sehr', 'C,D', 'LE', 6, '12', '3+1', 3.5, 17, '1', '1d8', 'Lykanthropie (bei Biss)', 'Nur Silber- oder +1 Waffen', 0, 'S', 'Standhaft (12)', 12, 270, 'melee', FALSE, 'MM', 'Hinterhältige Ratten-Lykanthropen die in den Abwasserkanälen von Städten lauern.'),
('Wereber', 'Wereboar', 'Jedes', 'rare', 'Einzelgänger', 'Jeder', 'Allesfresser', 'Durchschnittlich', 'B,C', 'N', 4, '12', '5+2', 5.5, 15, '1', '2d6', 'Lykanthropie (bei Biss)', 'Nur Silber- oder +1 Waffen', 0, 'L', 'Standhaft (12)', 12, 420, 'melee', FALSE, 'MM', 'Zähe Eber-Lykanthropen die in ihrer Tierform wild und nahezu unaufhaltsam sind.'),
('Nixe', 'Nixie', 'Gemäßigt/Süßwasser', 'uncommon', 'Stamm', 'Tag', 'Allesfresser', 'Durchschnittlich', 'Keins', 'N', 7, '6, Sw 12', '1', 1.0, 20, '1', '1d4', 'Bezauberung (10 Kreaturen, SV-Zauber -2)', NULL, 0, 'S', 'Durchschnittlich (7)', 7, 65, 'melee', FALSE, 'MM', 'Kleine Wasserfeen die Eindringlinge bezaubern und als Diener unter Wasser halten.'),
('Pixie', 'Pixie', 'Gemäßigt/Wald', 'rare', 'Clan', 'Tag', 'Allesfresser', 'Außergewöhnlich', 'K,L,M,N', 'NG', 5, '6, Fl 12', '1', 1.0, 20, '1', '1d4+Spezial', 'Polymorph-Pfeile, Schlaf-Pfeile', 'Natürliche Unsichtbarkeit', 25, 'S', 'Durchschnittlich (7)', 7, 175, 'ranged', TRUE, 'MM', 'Winzige, unsichtbare Feen die mit magischen Pfeilen Chaos stiften und Streiche spielen.'),
('Dryade', 'Dryad', 'Gemäßigt/Wald', 'rare', 'Einzelgänger', 'Jeder', 'Allesfresser', 'Hoch', 'D,Q×5', 'N', 9, '12', '2', 2.0, 19, '1', '1d2 (Dolch)', 'Bezauberung (SV-Zauber -3)', 'Dimensionstor zum Baum', 50, 'M', 'Unsicher (4)', 4, 975, 'melee', FALSE, 'MM', 'Schüchterne Baumnymphen die mit ihrem übernatürlichen Charme Sterbliche in ihren Wald locken.'),
('Satyr', 'Satyr', 'Gemäßigt/Wald', 'rare', 'Herde', 'Jeder', 'Allesfresser', 'Durchschnittlich-Hoch', 'D,I,J,K', 'N', 5, '18', '5', 5.0, 15, '1', '2d4+Spezial', 'Panflöte (Schlaf, Furcht, Bezauberung)', 'Magieresistenz 50%', 50, 'M', 'Standhaft (12)', 12, 650, 'melee', FALSE, 'MM', 'Ziegenbeinige Waldbewohner die für ihre Feiern, Musik und ihre magischen Panflöten bekannt sind.'),
('Treant', 'Treant', 'Gemäßigt/Wald', 'rare', 'Hain', 'Jeder', 'Wasser, Mineralien', 'Sehr', 'Q×10', 'CG', 0, '12', '12', 12.0, 9, '2', '4d6/4d6', 'Bäume beleben (2 pro Runde)', 'Nie von normalen Feuern bedroht', 0, 'H', 'Standhaft (16)', 16, 7000, 'melee', FALSE, 'MM', 'Uralte, baumgestaltige Waldwächter die andere Bäume zum Leben erwecken können.');

-- ============================================================================
-- OOZES & FUNGI (~10)
-- ============================================================================

INSERT INTO monsters (name, name_en, climate_terrain, frequency, organization, activity_cycle, diet, intelligence, treasure, alignment, ac, movement, hit_dice, hit_dice_value, thac0, attacks_per_round, damage, special_attacks, special_defenses, magic_resistance, size, morale, morale_value, xp_value, default_zone, has_ranged_attack, source_book, description) VALUES
('Schwarzer Pudding', 'Black Pudding', 'Unterirdisch', 'uncommon', 'Einzelgänger', 'Jeder', 'Allesfresser', 'Nicht intelligent', 'Keins', 'N', 6, '6', '10', 10.0, 11, '1', '3d8', 'Löst Metall und organisches Material auf', 'Immun gegen Säure/Kälte, Waffen teilen die Kreatur', 0, 'H', 'Spezial', 12, 4000, 'melee', FALSE, 'MM', 'Riesige schwarze Schleimansammlungen die alles außer Stein auflösen und sich bei Schwertschlägen teilen.'),
('Grauer Schleim', 'Gray Ooze', 'Unterirdisch', 'uncommon', 'Einzelgänger', 'Jeder', 'Allesfresser', 'Animalisch', 'Keins', 'N', 8, '1', '3+3', 3.5, 17, '1', '2d8', 'Löst Metall auf', 'Immun gegen Kälte/Feuer', 0, 'M', 'Spezial', 12, 270, 'melee', FALSE, 'MM', 'Metallauflösender Schlamm der sich als nasser Fels tarnt und Rüstungen und Waffen zersetzt.'),
('Ockergelee', 'Ochre Jelly', 'Unterirdisch', 'uncommon', 'Einzelgänger', 'Jeder', 'Allesfresser', 'Nicht intelligent', 'Keins', 'N', 8, '3', '6', 6.0, 15, '1', '3d4', 'Löst organisches Material auf', 'Immun gegen Blitz, Waffen teilen die Kreatur', 0, 'L', 'Spezial', 12, 975, 'melee', FALSE, 'MM', 'Ockerfarbener Schleim der sich durch Ritzen quetscht und organisches Material auflöst.'),
('Grüner Schleim', 'Green Slime', 'Unterirdisch', 'common', 'Kolonie', 'Jeder', 'Allesfresser', 'Nicht intelligent', 'Keins', 'N', 9, '0', '2', 2.0, 19, '0', 'Spezial', 'Verwandelt Fleisch in Grünen Schleim (1d4 Runden)', 'Nur durch Kälte/Feuer/Heilung zerstörbar', 0, 'M', 'Spezial', 12, 65, 'melee', FALSE, 'MM', 'Ätzende grüne Masse an Decken und Wänden die alles was sie berührt in mehr Schleim verwandelt.'),
('Gelatinöser Würfel', 'Gelatinous Cube', 'Unterirdisch', 'uncommon', 'Einzelgänger', 'Jeder', 'Allesfresser', 'Nicht intelligent', 'V', 'N', 8, '6', '4', 4.0, 17, '1', '2d4', 'Paralyse (SV-Lähmung), Verschlingen', 'Nahezu unsichtbar (Überraschung 1-3)', 0, 'L', 'Spezial', 12, 650, 'melee', FALSE, 'MM', 'Transparenter gallertartiger Würfel der Korridore reinigt und alles Organische in sich auflöst.'),
('Kreischer', 'Shrieker', 'Unterirdisch', 'common', 'Kolonie', 'Jeder', 'Keins', 'Nicht intelligent', 'Keins', 'N', 7, '1', '3', 3.0, 17, '0', '-', 'Schreien (alarmiert Monster im Umkreis von 40 m)', NULL, 0, 'M', 'Spezial', 12, 120, 'melee', FALSE, 'MM', 'Pilze die bei Annäherung ohrenbetäubend schreien und damit alle Monster der Umgebung herbeirufen.'),
('Violetter Pilz', 'Violet Fungus', 'Unterirdisch', 'uncommon', 'Kolonie', 'Jeder', 'Fleischfresser', 'Nicht intelligent', 'Keins', 'N', 7, '1', '3', 3.0, 17, '1-4', '1d4 (Fäulnis)', 'Berührungs-Fäulnis', NULL, 0, 'M', 'Spezial', 12, 175, 'melee', FALSE, 'MM', 'Lila leuchtende Pilze neben Kreischern die mit ihren Tentakeln Fleisch zum Verwesen bringen.'),
('Gelber Schimmel', 'Yellow Mold', 'Unterirdisch', 'common', 'Kolonie', 'Jeder', 'Keins', 'Nicht intelligent', 'Keins', 'N', 9, '0', '2', 2.0, 19, '0', 'Spezial', 'Sporenwolke (1d8 Schaden, SV-Gift oder Tod)', 'Nur durch Feuer zerstörbar', 0, 'M', 'Spezial', 12, 65, 'melee', FALSE, 'MM', 'Gefährlicher Schimmel der bei Berührung tödliche Sporen freisetzt — nur durch Feuer vernichtbar.'),
('Senfgelee', 'Mustard Jelly', 'Unterirdisch', 'rare', 'Einzelgänger', 'Jeder', 'Allesfresser', 'Nicht intelligent', 'Keins', 'N', 4, '3', '6+2', 6.5, 13, '1', '5d4', 'Organisches Material auflösen, Verlangsamungs-Dampf', 'Immun gegen Blitz/normales Feuer', 0, 'L', 'Spezial', 12, 1400, 'melee', FALSE, 'MM', 'Senffarbenes Gelee das einen verlangsamenden Dampf absondert und nahezu unaufhaltsam ist.'),
('Kristallschleim', 'Crystal Ooze', 'Unterirdisch', 'rare', 'Einzelgänger', 'Jeder', 'Allesfresser', 'Nicht intelligent', 'Keins', 'N', 8, '1', '4', 4.0, 17, '1', '4d4', 'Paralyse (SV-Lähmung)', 'Nahezu unsichtbar in Wasser', 0, 'M', 'Spezial', 12, 650, 'melee', FALSE, 'MM', 'Kristallklarer Schleim der in Pfützen und flachen Gewässern lauert und kaum zu erkennen ist.');

-- ============================================================================
-- CLASSIC DUNGEON MONSTERS (~18, without Rust Monster already above)
-- ============================================================================

INSERT INTO monsters (name, name_en, climate_terrain, frequency, organization, activity_cycle, diet, intelligence, treasure, alignment, ac, movement, hit_dice, hit_dice_value, thac0, attacks_per_round, damage, special_attacks, special_defenses, magic_resistance, size, morale, morale_value, xp_value, default_zone, has_ranged_attack, source_book, description) VALUES
('Verlagerungsbestie', 'Displacer Beast', 'Gemäßigt/Wald', 'rare', 'Rudel', 'Jeder', 'Fleischfresser', 'Halb-', 'D', 'LE', 4, '15', '6', 6.0, 15, '2', '2d4/2d4', NULL, 'Verlagerung (-2 auf feindliche Angriffe)', 0, 'L', 'Elite (13-14)', 13, 975, 'melee', FALSE, 'MM', 'Sechsbeinige pantherhafte Kreaturen die eine optische Verschiebung erzeugen — man sieht sie nie dort wo sie wirklich sind.'),
('Blinzelhund', 'Blink Dog', 'Gemäßigt/Ebene', 'rare', 'Rudel', 'Jeder', 'Allesfresser', 'Durchschnittlich', 'C', 'LG', 5, '12', '4', 4.0, 17, '1', '1d6', 'Teleportation im Kampf', 'Teleportation (Schwer zu treffen)', 0, 'M', 'Durchschnittlich (8-10)', 9, 270, 'melee', FALSE, 'MM', 'Intelligente Hunde die sich im Kampf teleportieren — natürliche Erzfeinde der Verlagerungsbestien.'),
('Phasenspinne', 'Phase Spider', 'Jedes', 'rare', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Niedrig', 'D', 'N', 7, '6, Wb 15', '5+5', 5.5, 15, '1', '1d6+Gift', 'Gift (SV-Gift -2 oder Tod), Phasenwechsel', 'Phasenwechsel (Ätherebene)', 0, 'L', 'Standhaft (12)', 12, 1400, 'melee', FALSE, 'MM', 'Riesenspinnen die zwischen Material- und Ätherebene wechseln und mit tödlichem Gift zuschlagen.'),
('Basilisk', 'Basilisk', 'Unterirdisch', 'uncommon', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Animalisch', 'Keins', 'N', 4, '6', '6+1', 6.5, 13, '1', '1d10', 'Versteinerungsblick (SV-Versteinerung)', NULL, 0, 'M', 'Standhaft (12)', 12, 1400, 'melee', FALSE, 'MM', 'Achtbeinige Reptilien deren Blick Lebewesen in Stein verwandelt — selbst ihr Spiegelbild ist gefährlich.'),
('Cockatrice', 'Cockatrice', 'Gemäßigt/Wald', 'uncommon', 'Schwarm', 'Tag', 'Allesfresser', 'Animalisch', 'D', 'N', 6, '6, Fl 18', '5', 5.0, 15, '1', '1d3+Versteinerung', 'Versteinerung (Berührung, SV-Versteinerung)', 'Flug', 0, 'S', 'Standhaft (11-12)', 11, 650, 'melee', FALSE, 'MM', 'Hahnähnliche Wesen mit einem Eidechsenschwanz deren bloße Berührung versteinert.'),
('Medusa', 'Medusa', 'Gemäßigt/Jedes', 'rare', 'Einzelgänger', 'Jeder', 'Allesfresser', 'Sehr', 'P,Q,O', 'LE', 5, '9', '6', 6.0, 15, '1', '1d4+Gift', 'Versteinerungsblick (SV-Versteinerung), Schlangenhaar (Gift)', 'Blick-Attacke', 0, 'M', 'Standhaft (12)', 12, 3000, 'melee', FALSE, 'MM', 'Schlangenharige Frauen deren Blick zu Stein verwandelt — einer der berühmtesten Schrecken der Mythologie.'),
('Gorgon', 'Gorgon', 'Gemäßigt/Ebene', 'rare', 'Herde', 'Jeder', 'Pflanzenfresser', 'Animalisch', 'Keins', 'N', 2, '12', '8', 8.0, 13, '1', '2d6', 'Versteinerungs-Atem (SV-Versteinerung)', 'Panzerung', 0, 'L', 'Standhaft (12)', 12, 4000, 'melee', TRUE, 'MM', 'Metallische Stiere die einen versteinernden Atem ausstoßen — nicht zu verwechseln mit der mythischen Medusa.'),
('Chimäre', 'Chimera', 'Gemäßigt-Tropisch/Berge', 'rare', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Halb-', 'F', 'CE', 6, '9, Fl 18', '9', 9.0, 11, '6', '1d3/1d3/1d4/1d4/2d4/3d4', 'Feueratem (Ziegenkopf, 3d8)', 'Flug', 0, 'L', 'Durchschnittlich (8-10)', 9, 4000, 'melee', TRUE, 'MM', 'Dreiköpfige Bestie — Löwe, Ziege und Drache vereint — die Feuer speit und wahllos alles angreift.'),
('Mantikor', 'Manticore', 'Jedes', 'uncommon', 'Rudel', 'Jeder', 'Fleischfresser', 'Niedrig', 'E', 'LE', 4, '12, Fl 18', '6+3', 6.5, 13, '3', '1d3/1d3/1d8', 'Schwanzstacheln (6/Runde, je 1d6, 60 m)', 'Flug', 0, 'L', 'Standhaft (12)', 12, 1400, 'ranged', TRUE, 'MM', 'Löwenkörper mit Fledermausflügeln und einem Schwanz voller tödlicher Stacheln die wie Geschosse fliegen.'),
('Peryton', 'Peryton', 'Berge', 'uncommon', 'Schwarm', 'Jeder', 'Fleischfresser', 'Durchschnittlich', 'B', 'CE', 7, '12, Fl 21', '4', 4.0, 17, '3', '4d4 (Geweih)', 'Geweih-Sturmangriff, benötigt menschliche Herzen', 'Nur +1 Waffen schaden', 0, 'M', 'Standhaft (11-12)', 11, 650, 'melee', FALSE, 'MM', 'Hirsch-Adler-Hybriden die menschliche Herzen fressen müssen um sich fortzupflanzen.'),
('Eulenbär', 'Owlbear', 'Gemäßigt/Wald', 'rare', 'Rudel', 'Jeder', 'Fleischfresser', 'Niedrig', 'C', 'N', 5, '12', '5+2', 5.5, 15, '3', '1d6/1d6/2d6', 'Umarmung (2d8 bei doppeltem Klauenhit)', NULL, 0, 'L', 'Standhaft (12)', 12, 420, 'melee', FALSE, 'MM', 'Magisch gezüchtete Kreuzung aus Eule und Bär — extrem territorial und unbarmherzig aggressiv.'),
('Ankheg', 'Ankheg', 'Gemäßigt/Acker', 'rare', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Nicht intelligent', 'C', 'N', 2, '12, Br 6', '3-8', 5.0, 15, '1', '3d6+1d4 (Säure)', 'Säurespucken (4d4, einmal/6 Stunden)', NULL, 0, 'L', 'Durchschnittlich (7-9)', 8, 975, 'melee', TRUE, 'MM', 'Riesige grabende Insekten die aus dem Boden schießen und Beute mit Säure auflösen.'),
('Wandelnder Hügel', 'Shambling Mound', 'Feucht/Sumpf', 'rare', 'Einzelgänger', 'Jeder', 'Allesfresser', 'Niedrig', 'A', 'N', 0, '6', '9+9', 9.5, 11, '2', '2d8/2d8', 'Umschlingung (automatisch 2d8+2d8)', 'Immun gegen Feuer, Blitze heilen, Halbschaden von Waffen', 0, 'L', 'Fanatic (17)', 17, 6000, 'melee', FALSE, 'MM', 'Pflanzliche Ungeheuer die Opfer verschlingen und durch Blitze stärker statt schwächer werden.'),
('Dunkelmantel', 'Darkmantle', 'Unterirdisch', 'uncommon', 'Kolonie', 'Jeder', 'Fleischfresser', 'Niedrig', 'Keins', 'N', 6, '6, Fl 9', '1+1', 1.5, 19, '1', '1d4+1', 'Umhüllen (Erstickung), Dunkelheits-Aura (5 m)', NULL, 0, 'S', 'Durchschnittlich (8-10)', 9, 35, 'melee', FALSE, 'MM', 'Stalaktitenartige Kreaturen die eine Dunkelheitsaura erzeugen und Köpfe ihrer Opfer umhüllen.'),
('Deckenlauerer', 'Lurker Above', 'Unterirdisch', 'uncommon', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Niedrig', 'D', 'N', 6, '1, Fl 9', '10', 10.0, 11, '1', '1d6+Ersticken', 'Umhüllen und Ersticken (Automatisch)', 'Tarnung als Höhlendecke', 0, 'H', 'Durchschnittlich (10)', 10, 3000, 'melee', FALSE, 'MM', 'Riesige mantelartige Kreaturen die als Höhlendecke getarnt auf Beute fallen und sie ersticken.'),
('Fallensteller', 'Trapper', 'Unterirdisch', 'rare', 'Einzelgänger', 'Jeder', 'Fleischfresser', 'Hoch', 'Keins', 'N', 4, '3', '12', 12.0, 9, '4', '4d4', 'Umschließen (automatisch 4d4/Runde)', 'Tarnung als Boden', 0, 'H', 'Standhaft (14)', 14, 6000, 'melee', FALSE, 'MM', 'Flache Kreaturen die sich als Boden tarnen, zuklappen und ihre Opfer langsam verdauen.'),
('Intellektverschlinger', 'Intellect Devourer', 'Unterirdisch', 'rare', 'Rudel', 'Jeder', 'Gehirne', 'Außergewöhnlich', 'B', 'CE', 4, '15', '6+6', 6.5, 13, '4', '1d4×4', 'Psionische Attacke (INT auf 0 reduzieren, Körper übernehmen)', '+3 Waffen nötig, Magieresistenz', 0, 'S', 'Standhaft (14)', 14, 5000, 'melee', FALSE, 'MM', 'Gehirnförmige Monster auf Beinen die den Verstand ihrer Opfer verschlingen und deren Körper übernehmen.'),
('Irrlicht', 'Will-o''-Wisp', 'Sumpf/Unterirdisch', 'rare', 'Einzelgänger', 'Nacht', 'Lebenskraft', 'Außergewöhnlich', 'Z', 'CE', -8, 'Fl 18', '9', 9.0, 11, '1', '2d8', NULL, 'Immun gegen alle Magie außer Magic Missile/Maze, Blitz heilt', 0, 'S', 'Spezial', 16, 7000, 'melee', FALSE, 'MM', 'Tödliche Lichterscheinungen die Reisende in Sümpfe locken — fast unmöglich zu treffen oder zu töten.'),
('Unsichtbarer Pirscher', 'Invisible Stalker', 'Jedes', 'very rare', 'Einzelgänger', 'Jeder', 'Keins', 'Hoch', 'Keins', 'N', 3, '12, Fl 12', '8', 8.0, 13, '1', '4d4', 'Überraschung', 'Unsichtbarkeit (natürlich)', 0, 'L', 'Spezial', 12, 3000, 'melee', FALSE, 'MM', 'Luftelementare die als unermüdliche Jäger beschworen werden — sie geben nie auf.');

-- ============================================================================
-- ELEMENTALS (~8, without Djinni, Invisible Stalker already above)
-- ============================================================================

INSERT INTO monsters (name, name_en, climate_terrain, frequency, organization, activity_cycle, diet, intelligence, treasure, alignment, ac, movement, hit_dice, hit_dice_value, thac0, attacks_per_round, damage, special_attacks, special_defenses, magic_resistance, size, morale, morale_value, xp_value, default_zone, has_ranged_attack, source_book, description) VALUES
('Luftelemental (12 TW)', 'Air Elemental (12 HD)', 'Luftebene', 'very rare', 'Einzelgänger', 'Jeder', 'Keins', 'Niedrig', 'Keins', 'N', 2, 'Fl 36', '12', 12.0, 9, '1', '2d10', 'Wirbelwind (Kreaturen unter 3 HD), +1d8 in der Luft', '+2 Waffen nötig', 0, 'H', 'Standhaft (13)', 13, 7000, 'melee', FALSE, 'MM', 'Mächtiger Luftelemental der als Wirbelwind Feinde durch die Luft schleudert.'),
('Erdelemental (12 TW)', 'Earth Elemental (12 HD)', 'Erdebene', 'very rare', 'Einzelgänger', 'Jeder', 'Keins', 'Niedrig', 'Keins', 'N', 2, '6', '12', 12.0, 9, '1', '4d8', '+1d8 gegen Bodenkontakt', '+2 Waffen nötig, kann nicht fliegen', 0, 'H', 'Standhaft (13)', 13, 7000, 'melee', FALSE, 'MM', 'Massiger Erdelemental der Mauern und Befestigungen mit Leichtigkeit durchbricht.'),
('Feuerelemental (12 TW)', 'Fire Elemental (12 HD)', 'Feuerebene', 'very rare', 'Einzelgänger', 'Jeder', 'Keins', 'Niedrig', 'Keins', 'N', 2, '12', '12', 12.0, 9, '1', '3d8', 'Entzündet Brennbares, +1d8 gegen kältebasierte Kreaturen', '+2 Waffen nötig, Feuerimmunität, Wasser schwächt', 0, 'H', 'Standhaft (13)', 13, 7000, 'melee', FALSE, 'MM', 'Lodernder Feuerelemental der alles Brennbare in seiner Nähe entzündet.'),
('Wasserelemental (12 TW)', 'Water Elemental (12 HD)', 'Wasserebene', 'very rare', 'Einzelgänger', 'Jeder', 'Keins', 'Niedrig', 'Keins', 'N', 2, '6, Sw 18', '12', 12.0, 9, '1', '5d6', 'Boote kentern, +1d8 im Wasser', '+2 Waffen nötig, muss in der Nähe von Wasser bleiben', 0, 'H', 'Standhaft (13)', 13, 7000, 'melee', FALSE, 'MM', 'Gewaltiger Wasserelemental der Schiffe kentern lässt und Feinde in Wassermassen ertränkt.'),
('Mephit (Feuer)', 'Mephit (Fire)', 'Feuerebene', 'common', 'Schwarm', 'Jeder', 'Keins', 'Durchschnittlich', 'Keins', 'NE', 5, '12, Fl 24', '3+1', 3.5, 17, '2', '1d3/1d3', 'Feuerstrahl (1d8+1, 5 m), Magisches Feuer', 'Feuerimmunität, Regeneration 1 HP/Runde in Feuer', 0, 'M', 'Durchschnittlich (7-8)', 7, 270, 'ranged', TRUE, 'MM', 'Kleine, bösartige Feuergeister die Flammen speien und sich an der Qual anderer erfreuen.'),
('Mephit (Eis)', 'Mephit (Ice)', 'Wasserebene', 'common', 'Schwarm', 'Jeder', 'Keins', 'Durchschnittlich', 'Keins', 'NE', 5, '6, Fl 12', '3+1', 3.5, 17, '2', '1d3/1d3', 'Frosthauch (1d4, 1,5 m), Eiswolke', 'Kälteimmunität, Regeneration 1 HP/Runde in Kälte', 0, 'M', 'Durchschnittlich (7-8)', 7, 270, 'ranged', TRUE, 'MM', 'Eisige kleine Elementarwesen die Frosthauch verbreiten und alles einfrieren wollen.'),
('Galeb Duhr', 'Galeb Duhr', 'Berge', 'very rare', 'Einzelgänger', 'Tag', 'Mineralien', 'Durchschnittlich-Hoch', 'Keins', 'N', -2, '6', '10', 10.0, 11, '2', '2d8/2d8', 'Felsen beleben (1d2 pro Runde), Stampfen (SV oder fallen)', 'Magieresistenz 20%, Immun gegen Feuer/Blitz', 20, 'L', 'Fanatic (16)', 16, 6000, 'melee', FALSE, 'MM', 'Uralte Steinwesen die Felsbrocken zum Leben erwecken und ihre Bergheimaten fanatisch verteidigen.'),
('Salamander', 'Salamander', 'Feuerebene', 'rare', 'Clan', 'Jeder', 'Fleischfresser', 'Hoch', 'F', 'CE', 5, '9', '7+7', 7.5, 13, '2', '2d6/1d6+Hitze', 'Hitze-Aura (1d6 im Umkreis), Umschlingung', 'Immun gegen Feuer, +1 Waffen nötig', 0, 'M', 'Standhaft (13)', 13, 3000, 'melee', FALSE, 'MM', 'Feurige Schlangenwesen mit menschlichem Oberkörper, deren bloße Nähe verbrennend heiß ist.');

-- ============================================================================
-- UPDATE typical_spells for spellcasting undead (not in their INSERT column list)
-- ============================================================================

UPDATE monsters SET typical_spells = '["fireball","power word stun","finger of death","globe of invulnerability","time stop","meteor swarm"]'::jsonb WHERE name_en = 'Lich';
UPDATE monsters SET typical_spells = '["wall of fire","power word kill","symbol of fear"]'::jsonb WHERE name_en = 'Death Knight';

-- ============================================================================
-- Verify count
-- ============================================================================

DO $$
DECLARE
  cnt INTEGER;
BEGIN
  SELECT COUNT(*) INTO cnt FROM monsters WHERE source_book = 'MM';
  RAISE NOTICE 'Total MM monsters seeded: %', cnt;
END $$;
